### PR TITLE
[Merged by Bors] - refactor(Algebra/Bilinear): generalize to non-commutative base rings

### PR DESCRIPTION
**Pull request by eric-wieser**
This removes unnecessary `IsScalarTower R A A` and `SMulCommClass R A A` arguments from `LinearMap.mulLeft` and `LinearMap.mulRight`, respectively.

As described in the new docstring, this allows respective specializations to `R := Aᵐᵒᵖ` and `R := A`.

Unfortunately all of the lemmas have to be reordered to take advantage of these relaxed assumptions.

In the chaos, a few lemmas also became generalized to non-unital rings.

There is some overlap here with `DistribMulAction.toLinearMap`, but that doesn't work in the case of non-unital rings.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
!bench

**Comment by j-loreaux** [comment]
@eric-wieser this looks pretty reasonable aside from the slowdown, which is admittedly pretty minimal. Do you think you could try taking a look at `PiTensorProduct` though? Especially the one declaration in the file that has an intersection with the diff, as that's likely the culprit.

If you can't find the slowdown it's not a big deal, but we might as well have a short look.

**Comment by eric-wieser** [comment]
!bench

**Comment by j-loreaux** [comment]
Thanks!

bors d+

**Comment by eric-wieser** [comment]
bors merge

**Pull request closed without merging**
