### PR TITLE
[Merged by Bors] - refactor(Mathlib/Init/Data/List/Instances): deduplicate `Decidable (∀ x, x ∈ l → p x)` & `Decidable (∃ x, x ∈ l → p x)` instances

### LINKED ISSUE #2910: Mathlib.Init.Data.List.Instances is redundant
`Mathlib.Init.Data.List.Instances` contains duplicates of some instances that are now in `Init.Data.List.Basic`. This has the potential to break proofs.

### Minimal example

If the `Mathlib` import is uncommented, the following proof breaks because `List.decidableBAll` and `[List.decidableForallMem](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Init/Data/List/Instances.html#List.decidableForallMem)` are not definitionally equal.

```lean
-- import Mathlib

theorem List.pwFilter_cons {R : α → α → Prop} [DecidableRel R] (x : α) (xs : List α) :
    (x :: xs).pwFilter R = if ∀ y ∈ xs.pwFilter R, R x y then x :: xs.pwFilter R else xs.pwFilter R :=
  rfl
```

### PR DESCRIPTION
**Pull request by Komyyy**
---

Resolves #2910

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by YaelDillies — APPROVED** [review]
maintainer merge

**Comment by sgouezel** [comment]
Can you fix the lint, and then send it back to bors?
bors d+

**Pull request closed without merging**
