### PR TITLE
[Merged by Bors] - feat: `positivity` extension for `Real.log` of natural/integer casts and numeric literals

### PR DESCRIPTION
**Pull request by dupuisf**
This PR adds a positivity extension for expressions of the form `Real.log n` where `n` is a cast from a natural number or an integer. (Since `positivity` can't handle conditions like `1 ≤ x`, this is pretty much the best we can do for the log.)

Also, the namespace of the positivity extension for `exp` is corrected.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by fpvandoorn** [comment]
Does extension prove
```
0 ≤ Real.log 1
0 < Real.log 37
```
If so: can you add the tests?

**Comment by dupuisf** [comment]
It doesn't (since there is no `Nat.cast`). I'll try to add support for this when I get time in a few days.

**Comment by dupuisf** [comment]
I just added support for logs of numeric literals.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
