### PR TITLE
[Merged by Bors] - Focus post-installation steps in the README

### LINKED ISSUE #7339: Error on non-Debian Linux distros and VS Code: unknown package
Hi all,

I have followed the exact instructions on how to install Lean on VS Code I could find on https://leanprover-community.github.io/install/linux.html which also happen to be the instructions [specified for this project](https://github.com/leanprover-community/mathlib4#installation) and despite my best effort when I try to import modules (e.g. here `data`) from mathlib4 I get:
```
unknown package 'data'
You might need to open '' as a workspace in your editor
```
From what I can gather in the official instruction above there is no mention that `mathlib4` needs separate installation steps and the documentation suggests that I should have been installed together with the VS Code extension and/or the main `elan-init.sh` step. Otherwise I would have expected separate instructions in the link above.

Am I missing something obvious here? Is there some path environment variable I can use to just set the path to the mathlib library if I simply clone it or documentation about how to do this I have missed?

Thanks in advance.

### PR DESCRIPTION
**Pull request by pevogam**
Installation of mathlib4 is never explicitly explained with the main link focusing on installing Lean4 itself. As most of the setup and making the library available happens when creating a Lean workspace, combine both links into the same section to follow right after the fairly short installation section.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alexjbest** [comment]
Hi, thanks for the PR. Mathlib uses a slightly non-standard workflow for PRs to the Github default though: can you please reopen your PR following https://leanprover-community.github.io/contribute/index.html#how-to-contribute-to-mathlib and https://leanprover-community.github.io/contribute/index.html#making-a-pull-request-pr, i.e. ask for commit permission on the Zulip and push to a branch of this repo rather than a fork, follow the title convention and label it awaiting-review when ready. Thank you.

**Comment by semorrison** [comment]
@alexjbest @pevogam, as this is a documentation only PR there's no need to run CI or open it from a branch on the main repo.

**Comment by semorrison** [comment]
I'd prefer we keep the sections separate, but definitely we should move the "mathlib4 as a dependency" section up, either before or after "experimenting".

**Comment by alexjbest** [comment]
> @alexjbest @pevogam, as this is a documentation only PR there's no need to run CI or open it from a branch on the main repo.

I agree in principle but if CI doesnt run then bors will refuse to merge if I understand it correctly, or am I missing something there?

**Comment by semorrison** [comment]
Hmm... I'm not sure. Won't bors just create a staging branch itself and run CI there? I certainly send things to bors before CI completes. :-)

**Comment by alexjbest** [comment]
> Hmm... I'm not sure. Won't bors just create a staging branch itself and run CI there? I certainly send things to bors before CI completes. :-)

I guess we can just try it and see

**Comment by pevogam** [comment]
> > Hmm... I'm not sure. Won't bors just create a staging branch itself and run CI there? I certainly send things to bors before CI completes. :-)
> 
> I guess we can just try it and see

I assume then this means we can just continue with this more standard Github process and update this PR instead of permission to commit on a main repo branch then.

> I'd prefer we keep the sections separate, but definitely we should move the "mathlib4 as a dependency" section up, either before or after "experimenting".

My initial problem was that I was looking for a way to install mathlib locally and due to the order of the sections ended up following the "experimenting" section link that then brought me to the section "We will now create a new project depending on mathlib." The second section worked much better but its topic overlaps significantly with the topics covered in the link https://leanprover-community.github.io/install/project.html which has the example on using mathlib as well as a section "Contributing to mathlib". So my idea was to have all these tutorials more focused in just one section that covers both "experimenting" and "using mathlib" just like the provided link. @semorrison what do you think about this?

**Comment by semorrison** [comment]
> My initial problem was that I was looking for a way to install mathlib locally and due to the order of the sections ended up following the "experimenting" section link that then brought me to the section "We will now create a new project depending on mathlib." The second section worked much better but its topic overlaps significantly with the topics covered in the link https://leanprover-community.github.io/install/project.html which has the example on using mathlib as well as a section "Contributing to mathlib". So my idea was to have all these tutorials more focused in just one section that covers both "experimenting" and "using mathlib" just like the provided link. @semorrison what do you think about this?

Sorry, I don't really follow. Let's just do the minimal change of moving "mathlib4 as a dependency" above "experimenting".

**Comment by pevogam** [comment]
> Sorry, I don't really follow. Let's just do the minimal change of moving "mathlib4 as a dependency" above "experimenting".

Ok, what you suggest is already a step in the right direction so let's go with that then. I would have preferred less topic overlap among the sections if possible but documentation may be improved more incrementally if it proves worthwhile.

Pushed with the requested changes and updated commit message.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
