### PR TITLE
[Merged by Bors] - chore(Init): remove empty files

### PR DESCRIPTION
**Pull request by grunweg**
Several files in `Init` only contained #align information and are now empty.

---

- [x] depends on: #14914 for simplicity

This may require several rounds of CI, to fix for transitive imports.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
bors d+

**Comment by urkud** [comment]
There was a commit changing `import`s on `master`, so I updated this branch.

**Comment by grunweg** [comment]
And I think I just accidentally overwrote that you pushed, sorry! (I only saw your comment on this PR afterwards.)

**Comment by urkud** [comment]
I'll merge `master` again.

**Comment by grunweg** [comment]
So... from my side, everything in the diff looks good. Let's have CI build this once more, and if it works, it's good to go!

**Comment by grunweg** [comment]
CI is done (except for linting, which this PR should not affect at all) - time to bors it.
bors r+

**Comment by riccardobrasca** [comment]
bors merge

**Pull request closed without merging**
