### PR TITLE
[Merged by Bors] - style: change the notation for `CategoryTheory.Limits.piObj` from `∏ f` to `∏ᶜ f`

### PR DESCRIPTION
**Pull request by Komyyy**
This notation is conflicting with `∏ x ∈ s, f x`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Komyyy** [comment]
@loefflerd updated.

**Comment by Komyyy** [comment]
@loefflerd sorry.

**Comment by loefflerd** [comment]
No problem, thanks for your work on this! 

maintainer merge

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
