### PR TITLE
[Merged by Bors] - perf: Use spread notation in ring transfer definitions

### PR DESCRIPTION
**Pull request by YaelDillies**
Make sure that `Function.Injective.somethingRing` looks like
```
def ... : SomethingRing β where
  toA := hf.a f ...
  __ := hf.b f ...
  __ := hf.c f ...
```
  if `SomethingRing α extends A α, B α, C α`.

This should hopefully give a performance boost in applications.

Incidentally, there were a few missing transfer definitions, so I added them as I needed them.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
I mean here

**Comment by YaelDillies** [comment]
!bench

**Comment by YaelDillies** [comment]
Seems to be slightly better overall, but nothing crazy.

**Comment by mattrobball** [comment]
What happens if you also change the instances in `RingTheory.Subring.Basic`?

**Comment by YaelDillies** [comment]
What do you mean exactly? There's no such instances in `RingTheory.Subring.Basic`. There's a few uses of transfer instances for ordered rings, so I changed those as well, but I'm not sure that's what you meant.

**Comment by YaelDillies** [comment]
!bench

**Comment by mattrobball** [comment]
I think that was a good interpretation. What I had in mind is probably out of scope here. It looks like #8386 will get in later today so let's wait until we can bench against that also. As both PRs have slowdowns around instances `subX`'s, just want to be safe. (Who knows they might cancel each other out.)

In the meantime, are there any other transfer lemmas hiding in the repo?

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
Let's just do it all together here. 

bors merge

**Comment by YaelDillies** [comment]
For the record, yes there's plenty more: `Field`, `Module`, `Lattice`...

**Comment by mattrobball** [comment]
Do you want to pull those in or just merge?

**Comment by YaelDillies** [comment]
I will do them when I have time, which will be in about a week, so let's just merge now.

**Comment by mattrobball** [comment]
bors merge

**Comment by jcommelin** [comment]
bors d+

**Comment by YaelDillies** [comment]
@mattrobball, do you understand what's going on here?

**Comment by mattrobball** [comment]
[Yes](http://speed.lean-fro.org/mathlib4/run-detail/5df475b9-b2c3-4b42-b86b-144d5bfcb847)

**Comment by mattrobball** [comment]
Ok, found it. `FractionalIdeal.commSemiring`. We can hackily fix the timeouts with 
```lean
attribute [-instance] FractionalIdeal.commSemiring in
 theorem exists_ne_zero_mem_ringOfIntegers_of_norm_le_mul_sqrt_discr :
```
and 
```lean
attribute [-instance] FractionalIdeal.commSemiring
 variable (w₁ : InfinitePlace K) {B : ℕ} (hB : minkowskiBound K 1 < (convexBodyLTFactor K) * B)
```

But this doesn't particularly make me happy

**Comment by YaelDillies** [comment]
I guess it's better than not merging this PR?

**Comment by mattrobball** [comment]
I will add some notes and then retry.

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
