### PR TITLE
[Merged by Bors] - chore(Topology/MetricSpace/PseudoMetric): Split

### PR DESCRIPTION
**Pull request by YaelDillies**
This reduces the long pole.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Let me cross-reference #13977 which tries the same. (I'll be happy to review either, but submitting my PhD thesis takes priority -> I may take about a week to get to this.)

**Comment by semorrison** [comment]
Ah, a pity, I wish I'd seen this before duplicating the work. I'm perfectly happy to defer to Yael's version if they can fix the merge conflicts. (Although, the import analyzer does seem to rate mine epsilonically better. :-)

**Comment by semorrison** [comment]
bors merge

**Comment by adomani** [comment]
To add yet another comment: the diff here also had those stray `structure`-less "structure."!

**Comment by YaelDillies** [comment]
Oh sorry @semorrison I wanted to compare our two approaches to understand why your PR performs better on import changes. I merely merged master to check the new long pole. 🙈

**Pull request closed without merging**
