### PR TITLE
[Merged by Bors] - port: `Nat.fib` extension for `norm_num`

### PR DESCRIPTION
**Pull request by kmill**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by kmill** [comment]
@digama0 Here's a port of the `Nat.fib` extension that we wrote (well, the one that I wrote poorly and that you rewrote from scratch :wink:)

**Comment by kmill** [comment]
I'm a bit surprised that typechecking takes a relatively large amount of time, and I worry that there's some mistake I've made that's causing the kernel to do too much reduction work.

For example:
```lean
-- type checking took 906ms
example : Nat.fib 10000 + Nat.fib 10001 = Nat.fib 10002 := by norm_num1

-- tactic execution of Lean.Parser.Tactic.refl took 1.18s
-- type checking took 1.17s
example : Nat.fib 10000 + Nat.fib 10001 = Nat.fib 10002 := by rfl
```
At least it's better that `rfl`, but less than I'd expect.

For comparison, I changed the extension to generate a `rfl` proof to avoid time spent unifying in the elaborator:
```lean
/-- Evaluates the `Nat.fib` function. -/
@[norm_num Nat.fib _]
def evalNatFib : NormNumExt where eval {u α} e := do
  let .app _ (x : Q(ℕ)) ← Meta.whnfR e | failure
  let sℕ : Q(AddMonoidWithOne ℕ) := q(instAddMonoidWithOneNat)
  let ⟨ex, p⟩ ← deriveNat x sℕ
  have y := Nat.fib ex.natLit!
  have ey : Q(ℕ) := mkRawNatLit y
  have pf : Q(Nat.fib $ex = $ey) := (q(Eq.refl $ey) : Expr)
  let pf' : Q(IsNat (Nat.fib $x) $ey) := q(isNat_fib $p $pf)
  return .isNat sℕ ey pf'

-- type checking took 1.27s
example : Nat.fib 10000 + Nat.fib 10001 = Nat.fib 10002 := by norm_num1
```

**Comment by kmill** [comment]
As a followup, I defined `fib` as an `axiom`, and `norm_num` can prove `Nat.fib 10000 + Nat.fib 10001 = Nat.fib 10002` in 30ms, so somehow the current implementation is causing `fib` to be reduced by the kernel...

**Comment by kmill** [comment]
One oddity that seems worth mentioning is that
```lean
example : Nat.fib 10000 = Nat.fib 10000 := by norm_num1
```
is fast (and one can check it does generate the full `Nat.fib` proofs, it's not just a trivial `rfl`), but
```lean
example : Nat.fib 10000 + 0 = Nat.fib 10000 := by norm_num1
```
triggers a slow kernel check.

**Comment by fpvandoorn** [comment]
I can confirm that this seems to be a problem with any norm num extension where the kernel reduction is slow. In #3892 I can reproduce
```
example : Nat.minFac 1277 + 0 = 1277 := by norm_num1 -- slow
```
(slow means ">8000ms", fast means "<50ms")

**Comment by fpvandoorn** [comment]
Here is a minimal example of something similar, but I'm not sure if it's exactly the same issue. This might be slow in the elaborator, not the kernel.
```lean
def A : Nat → Nat → Nat
| 0,     m     => m + 1
| n + 1, 0     => A n 1
| n + 1, m + 1 => A n (A (n + 1) m)
termination_by _ a b => (a, b)

example : A 3 5 + 0 = A 3 5 := rfl -- slow
```

**Pull request closed without merging**
