### PR TITLE
[Merged by Bors] - feat: port Algebra.DirectLimit

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
A few times `rw [RingHom.map_neg]` worked, `rw [(FreeCommRing.lift _).map_neg]` failed, and `rw [(FreeCommRing.lift <explicit function>).map_neg]` succeeded. So there was some "sweet spot" where `rw` would fail, and if you either gave it strictly less or strictly more information it would succeed. Other than that, not much to say.
 
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by kbuzzard** [comment]
This should be ready for review now.

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by joelriou** [comment]
(Oops, I though I had delegation for this one.)

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
