### PR TITLE
[Merged by Bors] - perf(LinearAlgebra.Quotient): de-simp theorems with weak keys

### PR DESCRIPTION
**Pull request by mattrobball**
For an example, the simp keys for `mk''_eq_mk` are `Quotient.mk'' _ _ _` meaning it will be tried on *anything* whose left-hand side reduces to `Quotient.mk''` regardless of the context. These are used a total of 6 times. 

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Review by Ruben-VandeVelde — APPROVED** [review]
Sounds reasonable.

maintainer merge

**Comment by mattrobball** [comment]
Reduction of linting instructions by 1%

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
Now actually over 1% reduction for linting instructions.

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Pull request closed without merging**
