### PR TITLE
[Merged by Bors] - chore: add more gcongr attributes

### PR DESCRIPTION
**Pull request by grunweg**
This PR tags (analogues of) lemmas tagged with `mono` also with `gcongr`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Thanks for your fixes! They look good to me. If you agree with my changes, the could maintainer merge this one "together" :-)

**Comment by YaelDillies** [comment]
I agree with your changes 😄 

maintainer merge

**Comment by grunweg** [comment]
(Last commit also LGTM.)

**Comment by jcommelin** [comment]
Please fix the build

**Comment by grunweg** [comment]
Fixed now (thanks, Yael!).

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by bryangingechen** [comment]
Cleaning up after a bors crash.
bors r+

**Pull request closed without merging**
