### PR TITLE
[Merged by Bors] - refactor(LinearAlgebra/Matrix/BilinearForm): Derive BilinearForm results from SesquilinearForm

### PR DESCRIPTION
**Pull request by mans0954**
Give definitions in `LinearAlgebra/Matrix/BilinearForm` in terms of the equivalent definitions in `LinearAlgebra/Matrix/SesquilinearForm` and derive the `BilinearForm` results as effectively special cases of the equivalent results in `SesquilinearForm`. This reduces the length of  `LinearAlgebra/Matrix/BilinearForm` by over 100 lines.

The aim is to:

* Clarify how results in `BilinearForm` relate to results in `SesquilinearForm`
* Reduce duplication of argument between the two files
* Validate that the results in `SesquilinearForm` are sufficiently general to provide the results in `BilinearForm` in their existing form - in fact, some loosening of the hypothesis in `SesquilinearForm` is required. Further loosening was already applied in #9475

---

This PR partially superceeds #8256

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mans0954** [comment]
!bench

**Comment by jcommelin** [comment]
The diff looks really good!

But these benchmark results are a bit surprising... @mattrobball do you have a clue what's going on?

**Comment by mattrobball** [comment]
Were there timeouts in this area of the library? Why all the `(R₂ := R₂)`? Lean is spending too much time turning `BilinForm.toLin` and `LinearMap.toBilin` into functions.

**Comment by mattrobball** [comment]
Performance is fixed by @Vierkantor with [leanprover-community/mathlib@Vierkantor/unbundled-FunLike-testings](https://github.com/leanprover-community/mathlib4/tree/Vierkantor%2Funbundled-FunLike-testings)

Actually greatly improved :)

**Review by mattrobball — APPROVED** [review]
I think merging in advance of the pending `FunLike` refactor is a good plan.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
