### PR TITLE
[Merged by Bors] - chore: update Std dependency to match leanprover/std4#397

### PR DESCRIPTION
**Pull request by kim-em**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This turned out to require non-trivial changes, so I have removed `auto-merge-after-CI`.

**Comment by semorrison** [comment]
This PR has some failures in `Mathlib.Computability.Primrec`, arising because the definition of `List.indexOf` has changed (the `==` test has flipped).

I'm not familiar with this file. It looks like @digama0 is listed as the author, and @prakol16 did the port. Might either of you be able to take a look at the failures in that file?

**Comment by PatrickMassot** [comment]
bors d+

**Comment by semorrison** [comment]
bors p=10

bors merge

**Pull request closed without merging**
