### PR TITLE
[Merged by Bors] - field_simp: Use positivity as a discharger

### LINKED ISSUE #4835: positivity discharger for field_simp
It would be nice if  `field_simp` could try `positivity` to discharge all non-zero denominator side conditions. See https://github.com/leanprover-community/mathlib/pull/15701#discussion_r932184472.

### PR DESCRIPTION
**Pull request by nomeata**
The main reasons is that having `h : 0 < denom` in the context should suffice for `field_simp` to do its job, without the need to manually pass `h.ne` or similar.

Quite a few `have := … ≠ 0` could be dropped, and some `field_simp` calls no longer need explicit arguments; this is promising.

This does break some proofs where `field_simp` was not used as a closing tactic, and it now
shuffles terms around a bit different. These were fixed. Using `field_simp` in the middle of a proof seems rather fragile anyways.

As a drive-by contribution, `positivity` now knows about `π > 0`.

fixes: #4835

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by nomeata** [comment]
This is my attempt at #4835. Some questions:

* Should I refactor `positivity` like that to be able to pass an `Expr` to it, or should I do it differently?
* I did not match on the goal in `field_simp` to see if we can expect positivity to succeed, but simply try `positivity` every time, as that will do that check first. ok?
* If the same `denom ≠ 0` precondition comes up multiple times, will this run `positivity` multiple times? Should we maybe remember and reuse the result (as a new hypothesis)? If so, should we remove them afterwards somehow?

**Comment by nomeata** [comment]
There will be a merge conflict with @mattrobball’s https://github.com/leanprover-community/mathlib4/pull/6034, and they eliminate some of the same extra steps, but both additions seem to be useful.

**Comment by mattrobball** [comment]
Yeah. This looks great. My motivation was code like

```lean
have : n \neq 0 := sorry
have : (n : Real) := by norm_cast; exact this
```

A real world example is in `Geometry.Manifold.Instances.Sphere` which I saw when porting. 

#6034 handles this. But it makes more sense to operate on the norm casted term directly. This runs into the problem that often there are simp args fed into `field_simp` un-normalized to work around the existing issues. 

Right now I want to `norm_cast` all the simp theorems in the context and then go. But I haven't gotten back to it yet.

**Comment by nomeata** [comment]
What does this mean for the present PR? Go ahead, wait for yours first, do them together?

**Comment by mattrobball** [comment]
Go full speed ahead. Feel free to incorporate whatever from #6013 or nothing.

**Comment by nomeata** [comment]
In that case I’ll just be lazy and ignore your PR for now, and see if I can get this change in without learning more about `normCast` :-)

**Comment by sgouezel** [comment]
!bench

**Comment by nomeata** [comment]
I couldn’t find information on `!bench`; where will I see the result?

**Comment by mattrobball** [comment]
The bot will come back once it clears the [queue](http://speedcenter.informatik.kit.edu/mathlib4/queue)

**Comment by nomeata** [comment]
I’ll be traveling without a laptop for week, and will address review comments afterwards. Should anyone want to adopt this PR and see it through, that’s fine with me as well.

**Comment by nomeata** [comment]
Back from vacation. What’s needed to make progress here?

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
!bench

**Comment by nomeata** [comment]
Looks like latest master (or the speedcenter) had stricter linting. Fixed.

**Comment by mattrobball** [comment]
leanprover-community/mathlib4#6579

**Comment by nomeata** [comment]
`Mathlib.Algebra.ContinuedFractions.Computation.CorrectnessTerminating` uses a bunch of `field_simp`, not unexpected that it got slower. A quick glance at it doesn’t show any obvious ways to fix this. Other modules sped up… not sure what to make of it.

**Comment by mattrobball** [comment]
I think `field_simp` should be closer to a finishing call than what that file wants to do. 

I think the performance profile is good and the PR definitely improve user ergonomics. 

@sgouezel do you have any concerns?

**Comment by sgouezel** [comment]
I'm perfectly happy with the performance, given how it improves readability and usability. Someone more skilled than me in meta code should still review it properly, however. If noone shows up, you can ping on Zulip.

**Comment by semorrison** [comment]
Looks great, thanks!

bors merge

**Pull request closed without merging**
