### PR TITLE
[Merged by Bors] - feat: port Control.Traversable.Basic

### PR DESCRIPTION
**Pull request by kbuzzard**
thing copied from mathlib3port: 1fc36cc9c8264e6e81253f88be7fb2cb6c92d76a

- [x] Depends on: #803 (for `list.traverse`)

### CODE REVIEW

**Comment by kbuzzard** [comment]
OK so this is compiling but not quite ready to go. 

Here's what I need advice on:

1) `List.traverse` was in `data.list.defs` in Lean 3 and this file hasn't been ported. So the corresponding
declaration should be moved to the right place and this PR shouldn't be merged until `data.list.defs` is ported.

2) There are two dubious translation errors; `List.traverse` and `Sum.traverse`. The error is
```
/- warning: sum.traverse -> Sum.traverse is a dubious translation:
lean 3 declaration is
  forall {σ : Type.{u}} {F : Type.{u} -> Type.{u}} [_inst_1 : Applicative.{u u} F] {α : Type.{u_1}} {β : Type.{u}}, (α -> (F β)) -> (Sum.{u u_1} σ α) -> (F (Sum.{u u} σ β))
but is expected to have type
  forall {σ : Type.{u}} {F : Type.{u} -> Type.{u}} [_inst_1 : Applicative.{u u} F] {α : Type.{_aux_param_0}} {β : Type.{u}}, (α -> (F β)) -> (Sum.{u _aux_param_0} σ α) -> (F (Sum.{u u} σ β))
Case conversion may be inaccurate. Consider using '#align sum.traverse Sum.traverseₓ'. -/
```
The error for `List.traverse` is similar. Discussion [here](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/why.20dubious.3F/near/310627146).

**Comment by semorrison** [comment]
I think no rush; the `Control` files are not really used much. :-)

**Comment by kbuzzard** [comment]
@semorrison I ported the file because the port-status script was telling me about two days ago that it was the most important file to be ported right now :-)

**Comment by semorrison** [comment]
Yes, in mathlib3 these files are all imported very early, but then not used much.

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#803
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by kbuzzard** [comment]
OK; the status of this PR now is that we're waiting on [#803 ](https://github.com/leanprover-community/mathlib4/pull/803) and I'm still a little confused about a possible dubious translation which could well not be dubious; I've asked [here](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/list.2Etraverse/near/313705787).

**Comment by kbuzzard** [comment]
Re the possibly dubious translation: I've explicitly checked the declarations in mathlib3 and mathlib4 and they're exactly the same including universes, so I think this PR is ready to go when #803 is merged.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#803~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
