### PR TITLE
[Merged by Bors] - chore(*): `LinearOrder` + `IsWellOrder α (· < ·)` → `LinearOrder` + `WellFoundedLT`

### PR DESCRIPTION
**Pull request by vihdzp**
These hypotheses are equivalent, but the former spelling contains duplicated hypotheses throughout both typeclasses.

---

- [x] depends on: #15904

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by vihdzp** [comment]
!bench

**Comment by vihdzp** [comment]
!bench

**Review by alreadydone — APPROVED** [review]
LGTM. Removal of IsWellOrder instances might be controversial, but I see it as a way to discourage the use of IsWellOrder (at least as a typeclass). It seems it's currently used to define Ordinal, and I wonder if it would be easier to use LinearOrder+WellFoundedLT to define it ...

**Comment by vihdzp** [comment]
I've thought about this, but it seems a bit messy given that `LinearOrder` carries a lot of data (the `≤` relationship, maximums and minimums, decidability instances...) that aren't needed. 

We can instead expose induction and recursion principles that use `LinearOrder` + `WellFoundedLT`, and in fact I've already done that in a branch I plan to PR in the near future.

**Comment by alreadydone** [comment]
I see, it's just [these two instances](https://github.com/leanprover-community/mathlib4/pull/18217/files#diff-39ff588cfd8afa83f18c2c9afa4e355f23c987dc7e99ab14a677f71ba9666ab7L818-L820) that can no longer be synthesized.

maintainer merge

**Comment by vihdzp** [comment]
Oh, removing those instances was a mistake. But if they're not used, I think it's fine to have them removed since you shouldn't be using `IsWellOrder α (· < ·)` anyways...

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Pull request closed without merging**
