### PR TITLE
[Merged by Bors] - feat(CategoryTheory): surjective-injective factorizations in concrete categories

### PR DESCRIPTION
**Pull request by joelriou**
In this PR, we formalize the notion of surjective/injective factorizations in concrete categories. We show that this obviously holds in the category of types. In future PRs, it shall be promoted to locally-surjective/locally-injective factorizations in categories of (pre)sheaves, and this shall be used in order to relate locally surjective morphisms and epimorphisms in categories of sheaves (beyond the case of sheaves of types which was obtained in #7721 and #13318).

---

- [x] depends on: #13331

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
Should the spelling be surjective-injective or epi-mono?

**Comment by joelriou** [comment]
This API (and the downstream applications I intend to do) is very much a surjective/injective thing. (In the future, we may deduce this property from epi/mono factorizations, for categories where we can compare epi/surjective and mono/injective, but I feel it would be ackward otherwise.)

**Comment by erdOne** [comment]
Thanks!
maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
