### PR TITLE
[Merged by Bors] - fix: adaptations for nightly-2024-01-24 (leanprover/lean4#3060)

### PR DESCRIPTION
**Pull request by eric-wieser**
leanprover/lean4#3060 exposed the latent https://github.com/leanprover-community/quote4/issues/30 (by propagating it from `if let` and `match` to `let`). The workaround is thankfully trivial.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

I haven't adjusted the lean-toolchain yet.

### CODE REVIEW

**Comment by semorrison** [comment]
Please merge once you've updated the `lean-toolchain`, and #9960 is in.

bors d+

**Comment by eric-wieser** [comment]
It looks like there are other changes in this nightly that require a change to Std first.

**Comment by nomeata** [comment]
@eric-wieser, I think this is good to go.

**Comment by eric-wieser** [comment]
bors merge

**Pull request closed without merging**
