### PR TITLE
[Merged by Bors] - chore: review of automation in category theory

### PR DESCRIPTION
**Pull request by kim-em**
Clean up of automation in the category theory library. Leaving out unnecessary proof steps, or fields done by `aesop_cat`, and making more use of available autoparameters.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
This currently doesn't build. Once it builds, I would be interested in running a benchmark to see how much of a difference this use of automation makes. (Hopefully very little!)

**Comment by semorrison** [comment]
!bench

**Comment by semorrison** [comment]
!bench

**Comment by semorrison** [comment]
bench suggests an increase of 0.75% in wall-clock.

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Comment by jcommelin** [comment]
bors d+

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
