### PR TITLE
[Merged by Bors] - chore: classify `was rw` porting notes

### PR DESCRIPTION
**Pull request by pitmonticone**
Classifies by adding issue number (#10691) to porting notes claiming `was rw`.

### CODE REVIEW

**Comment by kbuzzard** [comment]
maintainer merge

**Comment by kbuzzard** [comment]
Whilst I would prefer issues which covered hundreds of porting notes rather than just 8, several of the examples here are where `rw` has become `erw` and in my mind this indicates that something is wrong, so my feeling is that this is a good category even if it's a small one.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
