### PR TITLE
[Merged by Bors] - perf: hard-code typeclass inference in linarith

### PR DESCRIPTION
**Pull request by hrmacbeth**
This PR modifies the `linarith` tactic to rely on custom copies of many lemmas, rather than the library versions of these lemmas.  The difference is that the copies use high-level typeclasses (such as `OrderedSemiring`) rather than lower-level typeclasses (such as `AddRightMono`).

This seems to improve `linarith` performance.  The PR also introduces a performance test to the `linarith` test file, with a heartbeat limit which failed before this PR and passes (with leeway) after this PR.

[Zulip](https://leanprover.zulipchat.com/#narrow/channel/287929-mathlib4/topic/typeclass.20inference.20in.20linarith)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by hrmacbeth** [comment]
!bench

**Comment by kim-em** [comment]
I think this is a bug in the summary bot!

The actual line in the speed center result here is

```
build | instructions |   | - | 135.517T | -111.85B -0.083 % | 135.405T
```

which is a -0.08% reduction (i.e. negligible), not a -0.8% reduction as reported by the summary bot... Somehow has been careless with their decimals??

**Comment by grunweg** [comment]
> I think this is a bug in the summary bot!
> 
> The actual line in the speed center result here is
> 
> ```
> build | instructions |   | - | 135.517T | -111.85B -0.083 % | 135.405T
> ```
> 
> which is a -0.08% reduction (i.e. negligible), not a -0.8% reduction as reported by the summary bot... Somehow has been careless with their decimals??

CC @adomani in case you want to investigate. (I'll also add that to my list, but I'm somewhat busy with other projects right now.)

**Comment by adomani** [comment]
#18732 should fix the error: you can see in the linked PR that the "new" report does indeed say `-0.08%` as change in `build` instructions.

**Comment by hrmacbeth** [comment]
!bench

**Comment by hrmacbeth** [comment]
!bench

**Comment by kim-em** [comment]
bors d+

**Pull request closed without merging**
