### PR TITLE
[Merged by Bors] - feat: port Algebra.CharP.MixedCharZero

### PR DESCRIPTION
**Pull request by joneugster**
---

Renamed some statements to fit them a bit more into the mathlib naming convention.

- [x] depends on: #3292

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3292
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3292~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
