### PR TITLE
[Merged by Bors] - chore: Rename `Finset.inter_sdiff` to `Finset.inter_sdiff_assoc`

### PR DESCRIPTION
**Pull request by YaelDillies**
... and turn it around. This matches `Set.inter_diff_assoc`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by loefflerd** [comment]
> This matches Set.inter_sdiff_assoc

No, it doesn't, since `Set.inter_sdiff_assoc` does not exist; it's called `Set.inter_diff_assoc` (without the `s`). Is there a good reason for not making the `Finset` lemma actually match the `Set` one?

**Comment by YaelDillies** [comment]
Note that the operator is called `sdiff` but all `Set` lemmas call it `diff`. So, yes, it matches the `Set` lemma, up to a naming issue that's out of scope for this PR.

**Comment by loefflerd** [comment]
> So, yes, it matches the Set lemma, up to a naming issue that's out of scope for this PR

This seems like a slightly awkward argument to justify. There was a naming inconsistency about this lemma before; there'll still be a naming inconsistency afterwards; and it's not obvious to me that the new inconsistency is strictly less severe than the old one – they're both pretty trivial imho. So does the PR actually achieve anything?

**Comment by YaelDillies** [comment]
No, the new lemma name is perfectly consistent with the existing (imperfect) naming convention, namely that the `sdiff` lemmas for `Set` call it `diff` while the `Finset` lemmas call it `sdiff`. See eg `Set.diff_self` vs `Finset.sdiff_self`.

**Review by eric-wieser — APPROVED** [review]
bors merge

This also matches `inf_sdiff_assoc`

I agree that the `sdiff` / `diff` thing is unfortunate, but I don't think we need to spill that can of worms here.

**Pull request closed without merging**
