### PR TITLE
[Merged by Bors] - chore: better VSCode extension recommendations

### PR DESCRIPTION
**Pull request by fpvandoorn**
* This PR gets rid of the following pop-up, which is especially confusing for new users:
image
* Also remove the setting `search.usePCRE2` which is marked as "deprecated" and "enabled by default"

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alexjbest** [comment]
Do you know if we can instead make it so it recommends the lean4 plugin if not already installed. That would be even more useful IMO

**Comment by fpvandoorn** [comment]
That would be useful, yes, but I would have to look how to do that.
I guess that will also be disabled if we use this setting...

**Comment by alexjbest** [comment]
Ok I looked it up and pushed a file that recommends the lean 4 extension and explicitly bans the devcontainers one

**Comment by fpvandoorn** [comment]
Great! Did you test it? It looks good to me.

**Comment by alexjbest** [comment]
Nope I didn't sorry. I can try tomorrow but I didn't really want to uninstall the extension and restart my collection of vscode instances at the time

**Comment by semorrison** [comment]
Testing requires a fresh install of VSCode, as these settings only affect the first time you open a workspace in VSCode.

Happily I had a VM sitting around with a fresh install of VSCode as a snapshot, so I tried it out and it worked beautifully.

bors merge

**Pull request closed without merging**
