### PR TITLE
[Merged by Bors] - chore(Algebra/Module/Equiv/Defs): remove `FunLike` instance

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
!bench

**Comment by mo271** [comment]
!bench

**Comment by mo271** [comment]
!bench

**Comment by mo271** [comment]
!bench

**Comment by mo271** [comment]
Not sure how/if this interacts with #17870, but this one here is ready for review.

**Review by Vierkantor — APPROVED** [review]
Not sure why the benchmark is so positive, but I'll take it.

bors d+

**Comment by Vierkantor** [comment]
(It's still marked as a draft so I can't merge it.)

**Comment by mo271** [comment]
oops, marked as ready for review now...

**Pull request closed without merging**
