### PR TITLE
[Merged by Bors] - feat: port Topology.UrysohnsLemma

### PR DESCRIPTION
**Pull request by lua-vr**
---

It's my first mathlib PR, I hope I got it right.
(edit: sorry, I missed the step of asking for permission to assign labels in Zulip.)

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
@Parcly-Taxel, I think it was incorrect to restore (commented out) the `@[protect_proj]` attribute. @lucasvreis had already done the correct thing, using `protected` explicitly on the fields. Could you please revert that change?

**Comment by semorrison** [comment]
Once the issue with `protected` is sorted out, you can merge, @lucasvreis!

bors d+

**Comment by Parcly-Taxel** [comment]
> @Parcly-Taxel, I think it was incorrect to restore (commented out) the `@[protect_proj]` attribute. @lucasvreis had already done the correct thing, using `protected` explicitly on the fields. Could you please revert that change?

Right then, done.

**Pull request closed without merging**
