### PR TITLE
[Merged by Bors] - feat: port Combinatorics.Additive.Etransform

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

- [x] depends on: #3227

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3227
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3227~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by YaelDillies** [comment]
I would suggest renaming `ETransform` to `Etransform` everywhere. It currently reads very poorly.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
