### PR TITLE
[Merged by Bors] - chore(Mathport/Syntax): add syntax for coherence tactic

### PR DESCRIPTION
**Pull request by kim-em**
Should have been added after https://github.com/leanprover-community/mathlib/pull/13417.

### CODE REVIEW

**Comment by semorrison** [comment]
Perhaps we should disable the doc-string linter for `Mathport/Syntax.lean`, @gebner?

**Comment by gebner** [comment]
You can add a `@[nolint docBlame]`, but I think it's good to have docstrings for syntax.

**Comment by gebner** [comment]
That is disappointing, `syntax` doesn't seem to support any attributes at all. :-/  In the worst case you can always use `attribute [nolint docBlame] coherence pure_coherence`.

**Comment by semorrison** [comment]
Leo has updated Lean4 to allow this, so I'll wait for the next nightly to arrive then update this.

**Pull request closed without merging**
