### PR TITLE
feat(Equiv/QuotProd): new file

### PR DESCRIPTION
**Pull request by urkud**
---
I'm surprised we don't have this.
I also plan to add versions for `Con`s and `QuotientGroup`.
`pi` version awaits a refactor turning `piSetoid` into a `def`.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jsm28** [comment]
See #15947. In fact the `piSetoid` equiv is the one I need there; I simply did the `prod` version as well for completeness. Once that's in I have followup material ready to PR about `leftRel` and `rightRel`

```lean
@[to_additive]
lemma leftRel_prod {β : Type*} [Group β] (s' : Subgroup β) :
    leftRel (s.prod s') = (leftRel s).prod (leftRel s') := by

@[to_additive]
lemma rightRel_prod {β : Type*} [Group β] (s' : Subgroup β) :
    rightRel (s.prod s') = (rightRel s).prod (rightRel s') := by

@[to_additive]
lemma leftRel_pi {ι : Type*} {β : ι → Type*} [∀ i, Group (β i)] (s' : ∀ i, Subgroup (β i)) :
    leftRel (Subgroup.pi Set.univ s') = @piSetoid _ _ fun i ↦ leftRel (s' i) := by

@[to_additive]
lemma rightRel_pi {ι : Type*} {β : ι → Type*} [∀ i, Group (β i)] (s' : ∀ i, Subgroup (β i)) :
    rightRel (Subgroup.pi Set.univ s') = @piSetoid _ _ fun i ↦ rightRel (s' i) := by
```

and then my actual goal there, also ready to PR, is

```lean
@[to_additive]
lemma index_prod (H : Subgroup G) (K : Subgroup G') : (H.prod K).index = H.index * K.index := by

@[to_additive]
lemma index_pi {ι : Type*} [Fintype ι] (H : ι → Subgroup G) :
    (Subgroup.pi Set.univ H).index = ∏ i, (H i).index := by
```

(where again, the `pi` version is the one I have a use for and the `prod` one is for completeness).

**Comment by jsm28** [comment]
(I agree that `piSetoid` would be better as a `def`.)

**Comment by urkud** [comment]
I'm sorry I've missed your PR. I'm closing this one. Could you please open PRs about groups (depending on #15947), so that I can merge them into my branch and work on what I want here (same equivalence as a homeomorphism for topological groups)?

**Comment by jsm28** [comment]
The first four lemmas I mentioned about groups are now in #17585.

**Pull request closed without merging**
