### PR TITLE
feat: Match mathlib#17801

### PR DESCRIPTION
**Pull request by YaelDillies**
There's a syntax error with the final `simpa` that I'm stupid to fix. I will just hope someone jumps in and fixes it for me.

See https://github.com/leanprover-community/mathlib/pull/17801.

### CODE REVIEW

**Comment by semorrison** [comment]
bors d+

Please merge when the mathlib3 PR is approved.

**Comment by YaelDillies** [comment]
bors merge

**Comment by digama0** [comment]
By the way, I think that we should not have PR titles like this one, it is very uninformative. It should be something like `feat: A quasilinear function is either monotone or antitone (mathlib#17801)` with the mathlib#17801 part either in the title or in the description.

**Comment by YaelDillies** [comment]
Sure, I'm happy to change.

**Pull request merged**
