### PR TITLE
[Merged by Bors] - chore/refactor: avoid vector notation in character defs

### PR DESCRIPTION
**Pull request by MichaelStollBayreuth**
This changes the definition of the quadratic character `ZMod.χ₄` to use ane explicit `match` expression instead of `![0, 1, 0, -1]` (which relied on defeq abuse `ZMod = Fin`), and similarly for `ZMod.χ₈` and `ZMod.χ₈'`.

We also deal with some porting notes,  tidy up some files and speed up `Mathlib.NumberTheory.GaussSum`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by MichaelStollBayreuth** [comment]
!bench

**Comment by MichaelStollBayreuth** [comment]
```text
General information:
  lint:                                                +2.7113 * 10⁹ (+0.0224%)
  build:                                               -21.020 * 10⁹ (-0.0172%)

1 file got slower by at least 10⁹ instructions:
  Mathlib.CategoryTheory.Category.Cat.Limit:           +1.0899 * 10⁹ (+1.07%)

No file got slower by at least 10%.

3 files got faster by at least 10⁹ instructions:
  Mathlib.NumberTheory.GaussSum:                       -12.159 * 10⁹ (-28.2%)
  Mathlib.Analysis.NormedSpace.PiTensorProduct.InjectiveSeminorm:
                                                       -7.6365 * 10⁹ (-2.52%)
  Mathlib.NumberTheory.LegendreSymbol.ZModChar:        -1.7566 * 10⁹ (-11.9%)

2 files got faster by at least 10%:
  Mathlib.NumberTheory.GaussSum:                                      -28.2%
  Mathlib.NumberTheory.LegendreSymbol.ZModChar:                       -11.9%
```

**Comment by loefflerd** [comment]
I'm afraid this is going to conflict with Yaël's PR which removes `AddChar.IsPrimitive` (which is being merge-tested by bors as I write).

**Comment by loefflerd** [comment]
... actually less severe than I thought. I have the merge ready + will push it to your branch once the current bors run finishes.

**Comment by loefflerd** [comment]
If I understand the output of the various auto-review scripts, this PR speeds up `GaussSum` by 30% without any change to the functionality. I looked at the code, and it all seems sensible. Great stuff!

maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
