### PR TITLE
[Merged by Bors] - chore: `LinearOrderedSemiring α → LinearOrderedCancelAddCommMonoid α`

### PR DESCRIPTION
**Pull request by YaelDillies**
This was accidentally about `LinearOrderedCommSemiring`, probably due to confusion over which operation the `Comm` in the name refers to.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by j-loreaux** [comment]
!bench

**Comment by YaelDillies** [comment]
Very strange that the benchmark fails. Let me try merging master.

**Comment by mattrobball** [comment]
Sorry. Despite authoring to the commit fix this problem with the bench bot, I seem to have completely forgotten. 

Merging master will fix it

**Comment by YaelDillies** [comment]
!bench

**Comment by vihdzp** [comment]
I think the tech debt label isn't intended for general "stuff we've missed over the years", but specifically things left over from the Mathlib 3 port.

**Comment by YaelDillies** [comment]
That would be a valid interpretation, but in practice that's not how we are using it.

**Pull request closed without merging**
