### PR TITLE
[Merged by Bors] - chore: remove terminal, terminal `refine`s

### PR DESCRIPTION
**Pull request by adomani**
I replaced a few "terminal" `refine/refine'`s with `exact`.

The strategy was very simple-minded: essentially any `refine` whose following line had smaller indentation got replaced by `exact` and then I cleaned up the mess.

This PR certainly leaves some further terminal `refine`s, but maybe the current change is beneficial.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by fpvandoorn** [comment]
Thanks!

bors merge

**Comment by adomani** [comment]
@fpvandoorn I merged the new master into this PR to fix the conflicts, but there were none.  Should I push the merge?

**Comment by fpvandoorn** [comment]
bors merge

**Pull request closed without merging**
