### PR TITLE
feat: Add postUpdate hook for projects depending on Mathlib.

### PR DESCRIPTION
**Pull request by PatrickMassot**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This is still WIP. I would love to merge to reduce this pain point!

**Comment by eric-wieser** [comment]
I think #8243 is a duplicate?

**Comment by tydeu** [comment]
Oops, yeah, I didn't know that there was already a PR in a similar vein.

**Comment by semorrison** [comment]
Closed in favour of #8243

**Pull request closed without merging**
