### PR TITLE
[Merged by Bors] - chore: import Mathlib.Init in all files

### PR DESCRIPTION
**Pull request by grunweg**
This manually adds 'import Mathlib.Init' to all files which are currently missing this.
A future PR will add an automatic check for this.

---

This PR itself is easy to review: it just adds that one import. The fact that everything builds shows there is no import cycle.

The `large-imports` changes are by design (and show this change does something).

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Comment by bryangingechen** [comment]
I'm guessing the motivation is [this thread](https://leanprover.zulipchat.com/#narrow/channel/345428-mathlib-reviewers/topic/Lean.20rebuilding.20everything)? Could you add a word or two to the PR description about it?

**Comment by grunweg** [comment]
In fact, my motivation is unrelated to that: as I understand it, upon Mathlib.Init''s creation, the idea was that every file in Mathlib should import it --- this was just postponed to a later PR and never enforced so far. This PR is an easy way to enforce it.

**Comment by grunweg** [comment]
If you think the zulip thread you reference is also useful motivation, feel free to add it to the description!

**Comment by bryangingechen** [comment]
Reading over the thread again, I'm not sure that it's relevant anymore... I guess there's a tradeoff here between making the imports consistent and keeping a handful of files slightly lighter (many of them seem like they won't be imported without the rest of mathlib anyways).

bors d=adomani

**Comment by adomani** [comment]
Thanks!

Another consequence of importing Init everywhere is that the style linters will lint most files.

bors merge

**Pull request closed without merging**
