### PR TITLE
[Merged by Bors] - perf (CategoryTheory.ComposableArrows): swap out `linarith` for `omega` 

### PR DESCRIPTION
**Pull request by mattrobball**
This file now has the lead in the number of CPU instructions amongst all of mathlib. The majority come from `linarith` being an `autoparam` for many definitions, often in multiple arguments. This uses `omega` in place of `linarith` to improve performance. 

---

- [x] depends on: leanprover/std4#518

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
!bench

**Comment by semorrison** [comment]
bors d+

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
