### PR TITLE
[Merged by Bors] - feat: enable cancel_denoms preprocessor in linarith

### LINKED ISSUE #2714: `Rat`-dependent `linarith` functionality
As of #1711 `ring` can deal with fractions, so it should be possible to take the next step and let `linarith` deal with fractions.  For example,
```lean
import Mathlib.Tactic.Linarith

example (h : 0 < x) : 0 < x / 2 := by linarith
```

### PR DESCRIPTION
**Pull request by kim-em**
Enable the `cancelDenoms` preprocessor in `linarith`. Closes #2714.

- [x] depends on: #3797

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3797
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This will close #2714. I've updated nearly all the porting notes referencing linarith failures. (There's one remaining where a typeclass inference still fails.)

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3797~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by PatrickMassot** [comment]
bors merge

**Pull request closed without merging**
