### PR TITLE
[Merged by Bors] - chore: removing unnecessary imports of Batteries.Logic

### PR DESCRIPTION
**Pull request by kim-em**

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Sure, why not? (I'm not sure *if/why* this is important --- perhaps you have that context and I do not, but it surely doesn't hurt.)
maintainer merge

**Comment by j-loreaux** [comment]
bors merge

**Comment by j-loreaux** [comment]
bors d+

**Comment by j-loreaux** [comment]
bors merge

**Pull request closed without merging**
