### PR TITLE
[Merged by Bors] - feat: port AlgebraicTopology.DoldKan.GammaCompN

### PR DESCRIPTION
**Pull request by joelriou**
---
- [x] depends on: #3561
- [x] depends on: #3563
- [x] depends on: #3566

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3561
* leanprover-community/mathlib4#3563
* leanprover-community/mathlib4#3566
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3561~~
* ~~leanprover-community/mathlib4#3563~~
* ~~leanprover-community/mathlib4#3566~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
@joelriou, I've pushed a commit that fixes the timeout with `exact h`, by adding some `irreducible` attributes.

I haven't tested this downstream (or by backporting), so please feel free to revert if this won't work out.

I wish carefully adding `irreducible` everywhere possible was part of our usual routine building an API, but it isn't. :-)

**Comment by joelriou** [comment]
Thanks very much @semorrison ! I had similar timeout problems downstream in `NCompGamma` and `EquivalenceAdditive`. As the proofs relies much more on the simplification lemmas than the actual `def`, making some definitions irreducible seems to be the best solution. So far, `NCompGamma` and `EquivalenceAdditive` still compiles with this change, so that this PR should be good to go.

**Pull request closed without merging**
