### PR TITLE
[Merged by Bors] - chore: deprecate Nat.div_mod_eq_mod_mul_div and Nat.mul_div_mul_comm_of_dvd_dvd

### PR DESCRIPTION
**Pull request by dwrensha**
* `div_mod_eq_mod_mul_div` is a flipped version of [`mod_mul_right_div_self`](https://github.com/leanprover/lean4/blob/91334702431b8a7bf07f3f9e5696603de7b11fb6/src/Init/Data/Nat/Mod.lean#L50).
* `mul_div_mul_comm_of_dvd_dvd` is a flipped version of [`div_mul_div_comm`](https://github.com/leanprover-community/mathlib4/blob/b6cb80af68d53667dbbe8267f20ca075d5ffa953/Mathlib/Data/Nat/Defs.lean#L583).

These were found by [tryAtEachStep](https://github.com/dwrensha/tryAtEachStep).

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Thanks! This raises the question whether having both lemmas is useful - but I think this can also happen in a follow-up.
maintainer merge

**Comment by sgouezel** [comment]
I'd rather remove the lemmas (and deprecate them properly).

**Comment by dwrensha** [comment]
Deprecated in https://github.com/leanprover-community/mathlib4/pull/13336/commits/671100db12b1e4dde3d988629c969001a9d7d358.

I wanted to replace the lemmas with `alias`, because I don't think it's possible because then there's no way to apply the `symm`.

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by YaelDillies** [comment]
`Nat.mul_div_mul_comm_of_dvd_dvd`/`Nat.div_mul_div_comm` is supposed to mimic `mul_div_mul_comm`/`div_mul_div_comm`. Can you revert? (or maybe reintroduce `Nat.mul_div_mul_comm` instead of `Nat.mul_div_mul_comm_of_dvd_dvd` since I agree the name is strange)

**Comment by dwrensha** [comment]
https://github.com/leanprover-community/mathlib4/pull/13833

**Pull request closed without merging**
