### PR TITLE
[Merged by Bors] - chore: Split large file `MeasureTheory.MeasurableSpace.Basic`

### PR DESCRIPTION
**Pull request by loefflerd**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — APPROVED** [review]
Thanks a lot for doing this. Splitting large files is a tedious task, but very important in the long term. The split you have found makes sense to me.

Can I ask for one more thing, namely extending the module docstring of `MeasurableSpace/Embedding.lean` a bit, to mention its main results? I could be convinced that refl, symm, trans, products etc., are standard and can be omitted - but the measurable Schröder-Bernstein theorem definitely seems worth mentioning.

**Comment by grunweg** [comment]
awaiting-author

**Comment by grunweg** [comment]
I just saw you asked for Yael's opinion - well, now you have mine as well. Hope it's helpful :-)

**Comment by loefflerd** [comment]
Thanks for the review Michael! I asked Yael for a review initially since he was already reviewing #13353, but your input is also very welcome. I have adjusted the imports and added a fuller docstring as you suggested.

**Comment by grunweg** [comment]
Thanks for these changes; this split looks good to me now!
Let me approve already - if Yael has strong opinions, the split can always be tweaked later.
maintainer merge

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
