### PR TITLE
[Merged by Bors] - feat: `{Mv}Polynomial.algebraMap_apply` simps

### PR DESCRIPTION
**Pull request by BoltonBailey**
* Adds lemma `Polynomial.algebraMap_eq` analogous to `MvPolynomial.algebraMap_eq`
  * Adds some namespace disambiguations in various places to make this possible 
* Adds `simp` to these, and the related `{Mv}Polynomial.algebraMap_apply` lemmas.
  * Removes simp tag from later lemmas which linter says these additions now allow to be simp-proved

---

- [x] depends on: #11205

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by fpvandoorn — APPROVED** [review]
This looks good to me, but it's outside the part of Mathlib I'm familiar with.

(note that the last commit is a clean merge into master)

maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by riccardobrasca** [comment]
Sorry, I didn't notice CI was still running.

bors d+

**Comment by fpvandoorn** [comment]
The previous merge succeeded (it just shows an X because of the canceled bors run)

bors merge

**Pull request closed without merging**
