### PR TITLE
chore: make OreLocalization.smul not irreducible

### PR DESCRIPTION
**Pull request by kbuzzard**
Needed for #16650

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

Zulip discussion [here](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/ring.20structure.20on.20algebra.20localization/near/468865880).

### CODE REVIEW

**Comment by kbuzzard** [comment]
!bench

**Comment by kbuzzard** [comment]
(this benchmark is just smul)

**Comment by eric-wieser** [comment]
Can you add a test-case that failed before this change and succeeds after? Or is that not really possible until #16650 lands?

**Comment by kbuzzard** [comment]
I don't need this code any more, I only need these ideas in the commutative case and I'd misunderstood how to do this.

**Pull request closed without merging**
