### PR TITLE
[Merged by Bors] - chore: Move order lemmas about `zpow`

### PR DESCRIPTION
**Pull request by YaelDillies**
These lemmas can be proved earlier.

Part of #9411

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
CI = :sob:

**Review by Parcly-Taxel — APPROVED** [review]

**Comment by Parcly-Taxel** [comment]
CI = 🙂

**Comment by YaelDillies** [comment]
You're not helping me, Jeremy, but after close investigation I think your changes are fine.

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
