### PR TITLE
[Merged by Bors] - chore: add shortcut instances after LinearOrder Nat

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
This prevents Lean from going through the Lattice structure, which requires additional imports.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
(All import changes were found by shake here.)

**Comment by kim-em** [comment]
!bench

**Comment by kim-em** [comment]
Happy to merge this if `!bench` is happy.

**Comment by kim-em** [comment]
bors d+

**Comment by Ruben-VandeVelde** [comment]
As far as I can tell, the bench looks much better than I would have dared to hope.

bors merge

**Pull request closed without merging**
