### PR TITLE
feat: port Algebra.Group.With_One

### PR DESCRIPTION
**Pull request by kbuzzard**
Mathlib commit 1fc36cc9c8264e6e81253f88be7fb2cb6c92d76a .

WIP right now (half-finished; needs `mul_hom` ` →ₙ* `)

- [x] depends on: #826 
- [x] depends on: #659

### CODE REVIEW

**Comment by kbuzzard** [comment]
This is currently blocked by the Algebra.Hom.Group PR

**Comment by semorrison** [comment]
@kbuzzard, if you use the full URLs rather than just numbers github typesets them nicely so you can see their status without clicking.

**Comment by semorrison** [comment]
I've merged https://github.com/leanprover-community/mathlib4/pull/659.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#826~~
* ~~leanprover-community/mathlib4#659~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by kbuzzard** [comment]
OK so this file no longer exists; I will fix things up tomorrow and this will become a port of Algebra.Group.With_One.Defs

**Comment by kbuzzard** [comment]
Actually perhaps its' just easier to close this and start a new PR.

**Comment by kbuzzard** [comment]
https://github.com/leanprover-community/mathlib4/pull/841

**Pull request closed without merging**
