### PR TITLE
chore(MvPolynomial/PDeriv): remove superfluous use of DecidableEq

### PR DESCRIPTION
**Pull request by grunweg**
Found by the linter in #10235.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
Thanks!
maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by grunweg** [comment]
Sorry, I realised I meant to include one more tiny change (one line, analogous to the approved one). Do you mind re-approving?

**Comment by grunweg** [comment]
Superseeded by #17396.

**Pull request closed without merging**
