### PR TITLE
[Merged by Bors] - feat: port Algebra.Category.Ring.Limits

### PR DESCRIPTION
**Pull request by jjaassoonn**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jjaassoonn** [comment]
`FilteredColimits.lean` and `Limits` both contains `SemiRingCatMax` definition, so I will add merge conflict label for now

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by jjaassoonn** [comment]
@ChrisHughes24 let's not merge it for now, `FilteredColimits.lean` and `Limits` both contains `SemiRingCatMax` definition, so I am not sure if something will go wrong. Can you delegate to me so that when `FilteredColimits` is merged I will merge master and ensure everything is good

**Comment by jjaassoonn** [comment]
I think now it should be fine @ChrisHughes24

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
