### PR TITLE
[Merged by Bors] - fix: undeprecate `List.get_mono` and `List.get_strictMono`

### PR DESCRIPTION
**Pull request by urkud**
I see no reason for these lemmas to be deprecated.

---

- [x] depends on: #2311

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
@Ruben-VandeVelde Could you please have a look? Did you make them `deprecated` accidentally or you have a reason? In the latter case, please add back `@[deprecated]` with a comment about the reason for deprecation.

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2311
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2311~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
