### PR TITLE
[Merged by Bors] - feat: generalize tensor product constructions to semirings

### PR DESCRIPTION
**Pull request by riccardobrasca**
The current proofs already work for semirings.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
Is it worth to benchmark this?  It might simplify the typeclass search space to only look for `Semiring` instances...

**Comment by riccardobrasca** [comment]
!bench

**Comment by adomani** [comment]
I agree that it probably will not have a huge effect overall, but tensor stuff seems to be straining TC, so any little helps!

**Review by eric-wieser — APPROVED** [review]
bors merge

Thanks!

**Comment by eric-wieser** [comment]
bors merge

**Pull request closed without merging**
