### PR TITLE
[Merged by Bors] - feat: Port `Data.Nat.Size`

### PR DESCRIPTION
**Pull request by 0art0**
550b58538991c8977703fdeb7c9d51a5aa27df11

### CODE REVIEW

**Comment by 0art0** [comment]
Depends on #1075.

**Comment by 0art0** [comment]
Most errors are now fixed. There are two other declarations that used to be in [`data.nat.order.basic`](https://leanprover-community.github.io/mathlib_docs/data/nat/order/basic.html#nat.bit0_le_bit`) but are not in the ported version `Data.Nat.Order.Basic`.

There is also a strange linting error left to be addressed.

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
