### PR TITLE
[Merged by Bors] - feat: port Analysis.Analytic.Inverse

### PR DESCRIPTION
**Pull request by Komyyy**
---

- [x] depends on: leanprover/std4#155
- [x] depends on: #5409

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Komyyy** [comment]
TODO:
- [ ] fix the bug of `unusedHavesSuffices`
- [ ] add a config to `congr`

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5068
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by Komyyy** [comment]
This PR should be merged after #5068.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover/std4#155~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover/std4#155~~
* ~~leanprover-community/mathlib4#5409~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by Komyyy** [comment]
@Parcly-Taxel Thank you!

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
