### PR TITLE
[Merged by Bors] - feat: Port Data.QPF.Multivariate.Constructions.Comp

### PR DESCRIPTION
**Pull request by casavaca**
---

- [x] depends on: #2223 
[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2223
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by casavaca** [comment]
CI is happy. Just need to rebase on master when its dependency is merged. Adding `awaiting-review`.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2223~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
