### PR TITLE
[Merged by Bors] - chore: add missing hypothesis names to by_cases

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
I've also got a change to make this required, but I'd like to land this first.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alexjbest** [comment]
Sorry but why do we want to make this required?

**Comment by Ruben-VandeVelde** [comment]
Lean 4 generally leans towards not introducing accessible names implicitly, and in fact doesn't introduce one in core `by_cases`; this only works because mathlib overrides the core implementation to expose it. This is inconsistent with most (all?) other tactics.

Of course, this PR is only desirable if the maintainers agree with that view; I'm not claiming that to be the case a priori (though I hope it is).

**Comment by alexjbest** [comment]
I certainly agree that implicitly introducing accessible names is a bug that should be fixed, I just missed the first time I looked the fact that in all your examples h is already used by name!

maintainer merge

**Comment by alexjbest** [comment]
maintainer merge

**Comment by kmill** [comment]
Thanks!

bors r+

**Pull request closed without merging**
