### PR TITLE
[Merged by Bors] - feat(Data/Matrix/Basic): add missing theorem mulVec_sub

### PR DESCRIPTION
**Pull request by awueth**
Adds the following missing theorem
```
theorem mulVec_sub [Fintype n] (A : Matrix m n α) (x y : n → α) :
    A *ᵥ (x - y) = A *ᵥ x - A *ᵥ y
```
Currently there only is ```mulVec_sub```. I asked about it here on [zulip](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/No.20theorem.20Matrix.2EmulVec_sub).

### CODE REVIEW

**Review by eric-wieser — COMMENTED** [review]
Can you add `sub_vecMul` as well?

**Comment by awueth** [comment]
done

**Review by loefflerd — APPROVED** [review]
Looks good to me

maintainer merge

**Comment by j-loreaux** [comment]
bors merge

**Pull request closed without merging**
