### PR TITLE
[Merged by Bors] - chore(scripts/bench): benchmark with `--no-cache`

### PR DESCRIPTION
**Pull request by Kha**
There appears to be some incompatibility with executables downloaded from the cloud cache on NixOS, which broke the speedcenter. We used to benchmark all dependencies before the upgrade to 4.13.0-rc1, so let's go back to doing that.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Kha** [comment]
!bench

**Comment by jcommelin** [comment]
bors d+

**Comment by Kha** [comment]
!bench

**Comment by Kha** [comment]
!bench

**Comment by Kha** [comment]
!bench

**Comment by Kha** [comment]
!bench

**Pull request closed without merging**
