### PR TITLE
[Merged by Bors] - feat: port/CategoryTheory.Sites.Limits

### PR DESCRIPTION
**Pull request by kbuzzard**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by kbuzzard** [comment]
OK so I've basically got this file compiling, but it's no good. Typeclass inference can't solve certain universe problems, which means that the instances defined in this file aren't going to fire.

**Comment by kbuzzard** [comment]
Ok so it looks like a good fix is to change the objects of C to live in `Type u`. I've done this in mathlib3 at https://github.com/leanprover-community/mathlib/pull/18817 and will then forward-port to this and the instances should then fire.

**Comment by kbuzzard** [comment]
I think the only thing left with this PR is an `erw` which is generating two extra goals in lean 4 which it wasn't doing in lean 3. I think one can be closed with `(F.obj k).cond` but I'm not sure about the other one; it can't be hard though, if lean 3 was closing it automatically.

**Comment by adamtopaz** [comment]
> I think the only thing left with this PR is an `erw` which is generating two extra goals in lean 4 which it wasn't doing in lean 3. I think one can be closed with `(F.obj k).cond` but I'm not sure about the other one; it can't be hard though, if lean 3 was closing it automatically.

I got the file to build. The proof was hidden under two layers of definitions, so it was just a matter of unfolding the right stuff.

**Pull request closed without merging**
