### PR TITLE
[Merged by Bors] - refactor(Algebra/Lie/BaseChange): use new tensor product machinery

### PR DESCRIPTION
**Pull request by eric-wieser**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ocfnash** [comment]
It's great that this works but given how slow it is, it seems like we're still not ready to use `TensorProduct.AlgebraTensorModule.tensorTensorTensorComm` here. How about just updating the comment and leaving the implementation as it was?

**Comment by eric-wieser** [comment]
I managed to speed it up, I didn't need the heterobasic `curry` after all, and that just slowed it down.
It's still a bit slower, but it's manageable.

**Review by ocfnash — APPROVED** [review]
Thanks, now that this is not too slow, I think it's worth doing this to have an application of `TensorProduct.AlgebraTensorModule.tensorTensorTensorComm`.

It looks like further golfing is now possible (we should no longer need both `bracket_tmul'` and `bracket_tmul` and even `bracket_def` should not be necessary) but I don't think it's worth spending more time on this.

bors merge

**Comment by eric-wieser** [comment]
> Thanks, now that this is not too slow, I think it's worth doing this to have an application of `TensorProduct.AlgebraTensorModule.tensorTensorTensorComm`.

There's always #6306 if you want another one :)

**Pull request closed without merging**
