### PR TITLE
[Merged by Bors] - feat: implement basic version of tauto tactic

### PR DESCRIPTION
**Pull request by dwrensha**
Adds a basic version of the `tauto` tactic, mostly a line-by-line translation of the Lean 3 version.
* As per [this zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Understanding.20tauto.2Elean.20.28mathlib3.29/near/303177080), makes `tauto` always-classical and eliminates `tauto!`.
* Does not yet add any symmetry-based logic or the fancy union-find datastructure from https://github.com/leanprover-community/mathlib/pull/180.
* Adds a `andThenOnSubgoals` tactic combinator in `Mathlib.Tactic.Basic`.

### CODE REVIEW

**Comment by dwrensha** [comment]
Ok, got it. I'll re-remove the `tauto!` syntax. What about the `import Mathlib.Tactic.Tauto` in `Syntax.lean`. Is that still needed?

**Comment by semorrison** [comment]
I did some refactoring (not changing the algorithm at all), and moved some declarations to other homes.

I wouldn't mind one day have a `MetaM` level version of `tautoCore` and `tautology`, but there's no immediate need.

**Comment by semorrison** [comment]
Before we can widely deploy `tauto` we'll need the fix for https://github.com/leanprover/lean4/issues/1963. However I'm inclined to merge now as it is already useful.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
