### PR TITLE
[Merged by Bors] - chore: Split RingTheory.IntegralClosure

### PR DESCRIPTION
**Pull request by riccardobrasca**
We create a new folder `RingTheory.IntegralClosure` and we move the relevant files (also doing some splitting).

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
I don't really understand the difference between `Basic` and `Defs`, and the fact that `Defs` is more basic than `Basic` is confusing to me. IMHO that file should be split up into integral elements / integral algebras / integral closures instead.

**Comment by riccardobrasca** [comment]
> I don't really understand the difference between `Basic` and `Defs`, and the fact that `Defs` is more basic than `Basic` is confusing to me. IMHO that file should be split up into integral elements / integral algebras / integral closures instead.

`Defs` is more fundamental than `Basic` everywhere, isn't it? Anyway let me see if I can split the folder into three subfolders.

**Comment by riccardobrasca** [comment]
What do you think if this further splitting? (I still have to fix the docs)

**Comment by erdOne** [comment]
I like the split, thanks! I still don't understand the `def` / `basic` split though (I learnt of it just now). It seems to me like a hack on low-hierarchical files to reduce imports, which IMO is not a problem here. This breaks the "when I need to find API lemmas, just `Go to Definition`" workflow that I (and maybe others?) rely on.

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
