### PR TITLE
[Merged by Bors] - chore: tidy up a factorization proof

### PR DESCRIPTION
**Pull request by ericrbg**
This used to not work because the finsupp poisoned the computability, but it seems fine now. Also slightly tidied it whilst I was there.

However, I'm not sure if this is actually wise to keep as something towards `Sort*`: the created term on `k + 2` is not pretty and has an `Eq.mpr`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
bors d+

Thanks! I think this was probably a result of my recent refactor of `Multiset.toFinsupp`.

**Comment by eric-wieser** [comment]
> However, I'm not sure if this is actually wise to keep as something towards `Sort*`: the created term on `k + 2` is not pretty and has an `Eq.mpr`.

This is pretty unavoidable; the important thing is to use `convert` so that there's only one `Eq.mpr` and not a whole pile of them.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by ericrbg** [comment]
I completely missed that Eric had given it a `d+` instead of just approving, haha

**Pull request closed without merging**
