### PR TITLE
[Merged by Bors] - chore: use `Pairwise (_ on _)` where possible

### PR DESCRIPTION
**Pull request by eric-wieser**
---

- [x] depends on: #9236

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by joneugster — APPROVED** [review]
looks very reasonable! Can you resolve the merge conflicts then I think this can be merged.

**Comment by j-loreaux** [comment]
@joneugster I think I've fixed the conflicts. CI is pending, but I *think* it will pass.

**Comment by urkud** [comment]
Thanks! I've merged `master` to see if there are CI failures.
bors d+

**Comment by eric-wieser** [comment]
bors merge

**Pull request closed without merging**
