### PR TITLE
[Merged by Bors] - chore(MonoidAlgebra/Grading): drop `DecidableEq` assumption

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by adomani — APPROVED** [review]
Let's see if maintainer merge works here.

maintainer merge

**Review by adomani — COMMENTED** [review]
maintainer merge

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Review by Vierkantor — APPROVED** [review]
LGTM, thanks!

bors merge

**Comment by Vierkantor** [comment]
Another race you win in the same day! This is my fault though, for opening a few PRs in tabs as a todo list and not refreshing them when I get to them :)

**Pull request closed without merging**
