### PR TITLE
[Merged by Bors] - perf: remove some `with` instance construction patterns

### PR DESCRIPTION
**Pull request by mattrobball**
The general thought here is that
```lean
  { hf.distribMulAction f smul with
    smul := (· • ·)
    ... }
```
is treated roughly as
```lean
  let src := hf.distribMulAction f smul
  { toDistribMulAction :=
    { toMulAction :=
      { smul := (· • ·)
        one_smul := src.one_smul
        mul_smul := src.mul_smul}
      smul_add := src.smul_add 
      smul_zero := src.smul_zero  }
    ... }
```
which is a much larger term (especially once the `let` is reduced, due to how many arguments `hf.distribMulAction` consumes) than
```lean
  { toDistribMulAction := hf.distribMulAction f smul
    ... }
```

In some places the long version is _maybe_ still more desirable, if we want a specific syntactic equality for `smul` that the base structure defines differently; but none of the examples in this PR are such a case.

Co-authored-by: Eric Wieser <wieser.eric@gmail.com>

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by eric-wieser** [comment]
Before we merge, I'll add an explanation to the PR description of why I think this happens.

**Comment by eric-wieser** [comment]
bors d+

Please check you agree with the description before merging. I added myself as a co-author since I think the explanation is almost as important as the change here!

**Comment by eric-wieser** [comment]
!bench

**Comment by eric-wieser** [comment]
(the previous benchmark apparently might be bogus)

**Comment by mattrobball** [comment]
So I guess it caches the runs?

**Comment by eric-wieser** [comment]
Seems so; I've asked it to discard the last run

**Comment by eric-wieser** [comment]
!bench

**Comment by mattrobball** [comment]
That is what I expect

**Comment by eric-wieser** [comment]
I think this is probably still worth merging; do you agree?

**Comment by mattrobball** [comment]
Do you want to amend?

**Comment by mattrobball** [comment]
Oh already done.

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
