### PR TITLE
[Merged by Bors] - feat: port Algebra.Homology.Homotopy

### PR DESCRIPTION
**Pull request by joelriou**
---
- [x] depends on: #3505
- [x] depends on: #3517

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3505
* leanprover-community/mathlib4#3517
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ChrisHughes24** [comment]
There seem to have been some comments that were lost before the definition of `fromNext` and `toPrev`. Was this intentional?

**Comment by joelriou** [comment]
> There seem to have been some comments that were lost before the definition of `fromNext` and `toPrev`. Was this intentional?

Indeed, it is intentional: these comments have become irrelevant because of a refactor that was done a few months ago.

**Pull request closed without merging**
