### PR TITLE
[Merged by Bors] - feat(CategoryTheory): all morphisms are mono and epi when Quiver.IsThin holds

### PR DESCRIPTION
**Pull request by joelriou**
In particular, in preorders, all morphisms are mono and epi.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
Can you formulate this using `Quiver.IsThin` instead?

**Comment by riccardobrasca** [comment]
There is a commetn by Andrew, but otherwise LGTM, thanks!

bors d+

**Comment by joelriou** [comment]
Thanks for the suggestion!

**Comment by joelriou** [comment]
!bench

**Comment by joelriou** [comment]
Thanks!

bors merge

**Pull request closed without merging**
