### PR TITLE
[Merged by Bors] - refactor(Cyclic): redefine, move definition

### PR DESCRIPTION
**Pull request by urkud**
Redefine `IsCyclic` without `Subgroup` dependency, move the definition to `Algebra/Group/Defs`.

---
I'm going to prove that certain groups aren't cyclic, and the relevant file doesn't import `SpecificGroups/Cyclic`.
I added `import Mathlib.Logic.Function.Defs` to `Algebra.Group.Defs` to have `Surjective`.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
@semorrison what was the rationale for `assert_not_exists Function.Injective`?

**Comment by urkud** [comment]
It was added in #9606 while removing `import Mathlib.Logic.Function.Basic` which is a bit heavier than `Mathlib.Logic.Function.Defs`.

**Comment by j-loreaux** [comment]
We've worked hard to get the dependencies for `Algebra.Group.Defs` very low. While I agree `Logic.Function.Defs` is not heavy, it's relative weight for such a low-level file is still relatively high. So, personally, I'd prefer to have another solution here.

Maybe expand the definition of `Function.Surjective` locally in this file, and add the actual `Function.Surjective` lemma in a later file?

**Comment by urkud** [comment]
@j-loreaux 
What if I move everything but the *definitions* from `Logic/Function/Defs`, so that it becomes a very light dependency?

**Comment by mattrobball** [comment]
Is there harm in just making a new file?

**Comment by urkud** [comment]
BTW, the only new Mathlib imports that come with `Function.Defs` are `Tactic.AdaptationNote` and `Attr.Register`. Probably, the script reports Batteries imports too.

**Comment by urkud** [comment]
> Is there harm in just making a new file?

What do you suggest to move to a new file?

**Comment by mattrobball** [comment]
`IsCyclic/IsAddCyclic` to `Algebra.Group.IsCyclic`?

**Comment by urkud** [comment]
I would expect that `Algebra/Group/IsCyclic` is a file with basic properties of `IsCyclic`, not a file with the definition.

**Comment by urkud** [comment]
Another option is to move everything but definitions from `Logic/Function/Defs` to a new file (or to `Function/Basic` if every file that needs them imports `Basic`).

**Comment by urkud** [comment]
@j-loreaux What are the benefits of not importing `Function/Defs` in `Algebra/Group/Defs`?

**Comment by j-loreaux** [comment]
Ah, I didn't see your earlier comment. I think I'm okay with the new imports pulled in by `Function.Defs`, but I would like other input.

My goal here is just to be very stingy with respect to imports of low-level files so that we don't end up slowly migrating back to the old paradigm.

**Comment by j-loreaux** [comment]
Whoever looks at this, tha main question is should we import `Logic.Function.Defs` into `Algebra.Group.Defs`. Ultimately, I'm okay with it, but @mattrobball suggested moving to another file, which I also think is a good option. Please weigh in or merge.

maintainer merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
