### PR TITLE
style(Mathlib/Data/Seq/Seq): rename `Stream'.Seq` to `Sequence`

### PR DESCRIPTION
**Pull request by Komyyy**
Using `Stream'.Seq` without opening `Stream'` is tiresome, but if we open it, we must discriminating declarations in `Stream'.Seq` and `Stream'`.
So, we rename `Stream'.Seq` to `Sequence`.
Additionally, we rename `Stream'.Seq1` & `Stream'.WSeq` to `Sequence1` & `WSequence`.

---

This PR consists [Continued fractions makes an isomorphism between irrationals and baire space
](https://github.com/users/Komyyy/projects/3/) project

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
I'm sceptical here, as I think primed names are user-unfriendly. I won't block if someone wants to proceed, but would prefer to see a better solution with usable names.

**Comment by Komyyy** [comment]
@semorrison
How about `Sequence`?

**Comment by semorrison** [comment]
I'd prefer if someone with more expertise on this material continued the review here!

**Comment by Komyyy** [comment]
@semorrison 
I renamed.

**Comment by grunweg** [comment]
@Komyyy  Coming here for PR triage: thanks for your PR. It currently has a merge conflict, which means it won't show up in the review queue (and is less likely to be noticed). Can you merge the `master` branch, please?

**Comment by Komyyy** [comment]
❗This project is temporarily frozen, PRs are all closed for a moment. [Detail](https://leanprover.zulipchat.com/#narrow/channel/287929-mathlib4/topic/Definition.20of.20regular.20continued.20fractions)

**Pull request closed without merging**
