### PR TITLE
[Merged by Bors] - chore: update list of style exceptions

### PR DESCRIPTION
**Pull request by grunweg**
Created by manually running `./scripts/update-style-exceptions.sh`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
This PR is rotting somewhat quickly (just changed again), but is fairly easy to create manually. May I ask for delegating rights?

**Comment by eric-wieser** [comment]
Perhaps a better use of time is to adapt [this CI](https://github.com/leanprover-community/azure-scripts/blob/master/.github/workflows/nolints.yml) to do this automatically.

**Comment by grunweg** [comment]
Updated to master again; I'm not aware of further in-flight PRs conflicting with this.

I can look into updating CI as a follow-up.

**Review by eric-wieser — APPROVED** [review]
bors merge

**Comment by grunweg** [comment]
@eric-wieser Follow-up PR is at #9857.

**Pull request closed without merging**
