### PR TITLE
[Merged by Bors] - refactor(Order/Filter): don't use `generate` for `CompleteLattice`

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
!bench

**Comment by urkud** [comment]
!bench

**Comment by urkud** [comment]
!bench

**Comment by urkud** [comment]
Note that improvements in the 2 files come from adding extra hints, not from making `sInf` irreducible.

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
