### PR TITLE
[Merged by Bors] - chore: Move `pow_lt_pow_succ` to `Algebra.Order.WithZero`

### PR DESCRIPTION
**Pull request by YaelDillies**
These lemmas can be defined earlier, ridding us of an import in `Algebra.GroupPower.Order`

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by j-loreaux** [comment]
This needs a (transitive) import fix after the one that was deleted. But,

bors d+

**Comment by YaelDillies** [comment]
bors merge

**Comment by YaelDillies** [comment]
bors merge

**Comment by YaelDillies** [comment]
bors merge

**Pull request closed without merging**
