### PR TITLE
[Merged by Bors] - feat: add IsCancelMulZero

### PR DESCRIPTION
**Pull request by riccardobrasca**
We add `IsCancelMulZero` and related classes. This is the continuation of [#606](https://github.com/leanprover-community/mathlib4/pull/606).

Corresponding mathlib3 PR [#17716](https://github.com/leanprover-community/mathlib/pull/17716).

### CODE REVIEW

**Comment by semorrison** [comment]
bors d+

Please wait until the mathlib3 PR is approved before merging.

**Comment by rosborn** [comment]
According to our current naming conventions, `is_cancel_mul_zero` should translate to `CancelMulZero` as it is a type class. Relevant [section](https://github.com/leanprover-community/mathlib4/wiki#type-classes) on the wiki.

**Comment by semorrison** [comment]
@riccardobrasca, can you do this rename?

**Comment by riccardobrasca** [comment]
> @riccardobrasca, can you do this rename?

Sure, I don't have time today but I will do it asap. But is is really a good idea? We have [IsEmpty](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Logic/IsEmpty.html#IsEmpty) and [Empty](https://leanprover-community.github.io/mathlib4_docs/Init/Prelude.html#Empty) and here the situation is the same. How can we distinguish between a class that contain data and the same class written as `Prop`?

**Comment by rosborn** [comment]
Ah, yea. It seems like this has already been discussed [here](https://github.com/leanprover-community/mathlib4/pull/606/files#r1028796528). Sorry if this was a false digression.

**Comment by riccardobrasca** [comment]
bors merge

**Pull request closed without merging**
