### PR TITLE
[Merged by Bors] - feat: add `auto-merge-after-CI` label

### PR DESCRIPTION
**Pull request by kim-em**
Immediately after the `awaiting-CI` label is removed, check if the PR is labelled `auto-merge-after-CI`, and if so have the mathlib4 bot issue a `bors merge`.

Note that for now bors is not actually listening to the mathlib4 bot, so we will have to enable that once this has been tested.

The main use case here is generating automatic bump PRs so that we can keep up with Lean 4 nightly with less busy work.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
Nice, okay now to try again without the label, to see what happens.

**Comment by semorrison** [comment]
Looks good, try again with the label.

**Comment by jcommelin** [comment]
bors d+

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
