### PR TITLE
[Merged by Bors] - chore: deactivate Prop-dependent instances

### PR DESCRIPTION
**Pull request by sgouezel**
See Zulip discussion at https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Subgroups.20are.20empty/near/439227685

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
It would nice to see the performance aspects but I don't worry about that (and the server is busy plowing through its backlog anyway). 

I'll wait for a bit for any comments here or on Zulip before summoning bors.

**Review by mattrobball — APPROVED** [review]
Thanks!

**Comment by YaelDillies** [comment]
As mentioned on Zulip, this is not an insane instance to have and it seems that there is a Lean bug hiding in that instance never applying.

**Comment by sgouezel** [comment]
I don't know if there's a bug or not, but what I know is that this instance is not used anywhere in mathlib. There is a price to all instances, albeit small, since they are often tried in typeclass inference, so having unused instances around looks just bad to me, and I'd rather desactivate them regardless of the Prop-dependent issue.

**Comment by YaelDillies** [comment]
There is also a price to people expecting an instance to be there when it is not.

**Comment by urkud** [comment]
@sgouezel Could you please link the relevant Zulip thread in the commit message?

**Comment by sgouezel** [comment]
@YaelDillies , in this case I don't expect anyone would expect this instance given how unusual it is. The fact that it is not used throughout mathlib looks like a good hint in this direction.

**Comment by YaelDillies** [comment]
I'm pretty sure I use it in LeanCamCombi 🤔

**Comment by sgouezel** [comment]
If you give me a convincing pointer, where it's natural to have decidability for some subsets of a given finset but not for all finsets, then I'll close the PR.

**Comment by joneugster** [comment]
What's the status of this PR, @sgouezel?

@mattrobball [wrote](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Subgroups.20are.20empty/near/439286350):
> Actually, the problems from this instance seem to come from using refine' in place of refine

Did #12997 or #13059 make a difference?

An option to address Yael's concerns somewhat might be to add a sentence to both docstrings explaining why they aren't instances anymore.

**Comment by sgouezel** [comment]
The status is that Yael hasn't given me a pointer showing that this instance is useful, so I think the PR is good, and it is awaiting review :-)

**Comment by joneugster** [comment]
!bench

**Comment by joneugster** [comment]
As far as I can tell, the original issue on Zulip was resolved independently, and while I don't know how to reproduce Matt's tests, it seems that has been addressed, too, and that nothing gained or significantly faster with these instances removed. 
Further, I can not reproduce the comment about he instance never applying, but that might be lack of trying from my side.

If this summary is correct, I don't see much benefit in removing the instances.

(If I missed something I think it would be good to explain here (or on Zulip) what's gained by the change.)

**Comment by mattrobball** [comment]
I changed core to toss out errors when it reached a certain edge case in typeclass synthesis. It turned out that certain tactics were at fault, `refine'` and `convert`, rather than instances. 

Generally, I don't think we can live in a world where all instances are available all the time. @fpvandoorn mentioned scoping instances that are used < 10 times. I don't think this instance is ever used (?). Would that be a reasonable solution here?

**Comment by fpvandoorn** [comment]
These instances seem bad to me. I expect Lean will struggle to apply then in cases that `p` is not a variable. 

I think that even if this is useful in LeanCamCombi, I think we should still (at least) scope these instances. The `-0.454 %` in type-class inference is probably just noise, but I can also imagine that doing this for 20-50 other instances will actually give a noticeable speed improvement.

I'll let @sgouezel decide if he wants to give @YaelDillies a few more days to give an example, or just to merge it outright.

bors d+

**Comment by sgouezel** [comment]
I'll wait a few days to see if @YaelDillies has a convincing example, and merge otherwise.

**Comment by YaelDillies** [comment]
Sorry, I am very busy for another week

**Pull request closed without merging**
