### PR TITLE
[Merged by Bors] - feat: port split_ifs tactic

### PR DESCRIPTION
**Pull request by dwrensha**
This is intended to be as close as possible of a translation of the mathlib3 version: https://github.com/leanprover-community/mathlib/blob/12a7da107a39ef936c5d4a8cb873018ad05b07a6/src/tactic/split_ifs.lean

### CODE REVIEW

**Comment by dwrensha** [comment]
(See #505 for some initial discussion.)

**Comment by semorrison** [comment]
@dwrensha, I migrated the tests over from mathlib3, and in fact detected a regression by doing so.

I've left your branch broken with the failing test in place, so you can find it easily. :-) Feel free to either comment out the test explaining what's going on, or fix it, as seems most appropriate!

**Comment by dwrensha** [comment]
Updated. The tests pass after I map Lean 3 `true` to Lean 4 `True`, and Lean 3 `false` to Lean 4 `False`. (Props not Bools.)

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
