### PR TITLE
[Merged by Bors] - feat: Sublattice generated by a product set

### PR DESCRIPTION
**Pull request by YaelDillies**
... is the product of the sublattices generated by the sets.

From LeanCamCombi

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by riccardobrasca** [comment]
Three weeks and of course master changed a lot :D

bors d+

**Comment by YaelDillies** [comment]
bors merge

**Pull request closed without merging**
