### PR TITLE
[Merged by Bors] - feat: Add `Polynomial.separable_map'`.

### PR DESCRIPTION
**Pull request by erdOne**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by riccardobrasca — APPROVED** [review]
This is strictly more general than the actual `separable_map`, right? In this case this should be the umprimed version (maybe you can even inline the proof of the weak case and only keep the more general one).

**Comment by riccardobrasca** [comment]
> This is strictly more general than the actual `separable_map`, right? In this case this should be the umprimed version (maybe you can even inline the proof of the weak case and only keep the more general one).

I mean something like
```
attribute [local instance] Ideal.Quotient.field in
lemma separable_map {S} [CommRing S] [Nontrivial S] (f : F →+* S) {p : F[X]} :
    (p.map f).Separable ↔ p.Separable := by
  refine ⟨fun H ↦ ?_, fun H ↦ H.map⟩
  obtain ⟨m, hm⟩ := Ideal.exists_maximal S
  have := Separable.map H (f := Ideal.Quotient.mk m)
  rwa [map_map, separable_def, derivative_map, isCoprime_map] at this
```

**Comment by riccardobrasca** [comment]
Thanks!

bors +

**Comment by riccardobrasca** [comment]
> Did you mean "r+"?

Almost, but thanks bors!!

bors d+

**Comment by erdOne** [comment]
bors merge

**Pull request closed without merging**
