### PR TITLE
[Merged by Bors] - refactor: add `compactSpace_spectrum` and `spectrum_nonempty` fields to the `ContinuousFunctionalCalculus`

### PR DESCRIPTION
**Pull request by j-loreaux**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by dupuisf** [comment]
I'm a bit surprised that this doesn't allow us to remove `[∀ a, CompactSpace (spectrum R a)]` parameters all over the place. Can you confirm that this is not an oversight?

**Comment by j-loreaux** [comment]
Oh, that's probably an oversight. I just fixed errors, but didn't think about cleaning up existing stuff. I'll see what I can do

**Comment by j-loreaux** [comment]
okay, I *think* I found these occurrences and removed them. I believe there used to be more, but Oliver had a PR which removed most of them (by generalizing a theorem from another part of the library).

**Comment by dupuisf** [comment]
Great; thanks!

bors r+

**Pull request closed without merging**
