### PR TITLE
[Merged by Bors] - feat(RingTheory/Algebraic): add some results on `Transcendental`

### PR DESCRIPTION
**Pull request by acmepjz**
- `transcendental_iff`, `transcendental_iff_ker_eq_bot`: similar to the API of `AlgebraicIndependent`
- `IsAlgebraic.of_aeval`, `Transcendental.aeval`: behavior of transcendental over `aeval`
- `Polynomial.transcendental`, `Polynomial.transcendental_X`: some specific polynomials are transcendental over its base ring
- `Transcendental.linearIndependent_sub_inv`: if `E / F` is a field extension, `x` is an element of `E` transcendental over `F`, then `{(x - a)⁻¹ | a : F}` is linearly independent over `F`
- `transcendental_algebraMap_iff`: negation of `isAlgebraic_algebraMap_iff`

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

discussion: https://leanprover.zulipchat.com/#narrow/channel/144837-PR-reviews/topic/.2317867.20some.20results.20on.20Transcendental/near/477438980

### CODE REVIEW

**Comment by acmepjz** [comment]
Sorry, I found duplicative results. Will change it soon.

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by bryangingechen** [comment]
This fell off the queue when bors crashed yesterday
bors r+

Just in case:
bors d+

**Pull request closed without merging**
