### PR TITLE
[Merged by Bors] - feat: port GroupTheory.PGroup

### PR DESCRIPTION
**Pull request by mattrobball**
---

- [x] depends on: #4316
[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4316
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4316~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

(In the future we'll have to think about names like `Padic` and `PGroup`. The uppercase `P` is pretty weird.)

**Comment by mattrobball** [comment]
> Thanks :tada:
> 
> 
> 
> bors merge
> 
> 
> 
> (In the future we'll have to think about names like `Padic` and `PGroup`. The uppercase `P` is pretty weird.)

I thoroughly agree.

**Pull request closed without merging**
