### PR TITLE
[Merged by Bors] - chore(Algebra/Polynomial): split `Eval.lean` into smaller files

### PR DESCRIPTION
**Pull request by Vierkantor**
This PR takes the rather large file `Algebra/Polynomial/Eval.lean` and splits it into the following smaller files:

* `Algebra/Polynomial/Eval/Defs.lean`: definition of evaluation and bundled homs
* `Algebra/Polynomial/Eval/Algebra.lean`: evaluating where the map is `algebraMap`
* `Algebra/Polynomial/Eval/Coeff.lean`: `eval` and `coeff`
* `Algebra/Polynomial/Eval/Degree.lean`: `eval` and `degree`
* `Algebra/Polynomial/Eval/Irreducible.lean`: `eval` and `Irreducible`
* `Algebra/Polynomial/Eval/SMul.lean`: `eval` and the module structure on `Polynomial`
* `Algebra/Polynomial/Eval/Subring.lean`: `eval` into a subring

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
maintainer merge

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Comment by Vierkantor** [comment]
Merge conflict :(

bors r-

**Comment by jcommelin** [comment]
bors r+

bors d+

**Pull request closed without merging**
