### PR TITLE
[Merged by Bors] -  chore: move Nat.find/findGreatest into their own file

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
This lightens the very low-level `Mathlib/Data/Nat/Defs.lean` and `Mathlib/Init/Data/Nat/Lemmas.lean` a bit.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by YaelDillies** [comment]
Hmm... what's the motivation? I'm doing the inverse move in #11866 with the intention of clearly marking what's PRable to Std vs what's not.

**Comment by jcommelin** [comment]
LGTM

bors d+

**Comment by YaelDillies** [comment]
I turned we've decided not to merge that PR

**Comment by jcommelin** [comment]
@YaelDillies wait, where was this decided? I think moving `Nat.find` to its own file is a good move.

**Comment by YaelDillies** [comment]
> Hmm... what's the motivation? I'm doing the inverse move in #11866 with the intention of clearly marking what's PRable to Std vs what's not.

☝️ I'm hoping for `Data.Nat.Defs` to be a ForBatteries file, with stuff that's clearly marked as upstreamable

**Comment by jcommelin** [comment]
I don't see how putting `find` in its own file makes upstreaming any harder. And this PR is moving find out of `Init`, which is a good thing.

`Init` is a grab bag directory. Being in that directory doesn't mean "probably should go to Batteries".

In particular, I don't understand what you mean by "inverse" in your comment.

**Comment by Ruben-VandeVelde** [comment]
I verified that the new file doesn't have any dependencies that Batteries would worry about: https://github.com/leanprover-community/mathlib4/compare/nat-find-reduce-deps

**Comment by semorrison** [comment]
bors merge

**Comment by Ruben-VandeVelde** [comment]
bors merge

**Comment by YaelDillies** [comment]
> I verified that the new file doesn't have any dependencies that Batteries would worry about: https://github.com/leanprover-community/mathlib4/compare/nat-find-reduce-deps

but can you ensure that via some `assert_not_exists`?

**Comment by urkud** [comment]
`bors` is complaining about `shake`, probably because of this PR but I'm not sure. Merging `master` to test it.
bors r-
bors d+

**Comment by Ruben-VandeVelde** [comment]
bors merge

**Comment by YaelDillies** [comment]
> > I verified that the new file doesn't have any dependencies that Batteries would worry about: https://github.com/leanprover-community/mathlib4/compare/nat-find-reduce-deps
> 
> but can you ensure that via some `assert_not_exists`?

🏓

**Pull request closed without merging**
