### PR TITLE
[Merged by Bors] - feat(CategoryTheory): pushout/pullback squares are stable by isomorphisms

### PR DESCRIPTION
**Pull request by joelriou**
The properties `IsPushout` and `IsPullback` are stable by isomorphisms.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
Would it be useful as an iff?

**Comment by joelriou** [comment]
> Would it be useful as an iff?
If we had a category of commutative squares, an `iff` lemma would be convenient, but in the unbundled setting, I do not think it would be useful.

**Comment by erdOne** [comment]
Okay sure.
Thanks!
maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
