### PR TITLE
[Merged by Bors] - chore: tidy various files

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Can you fix the merge conflict, please? Thanks!

**Review by grunweg — APPROVED** [review]
Thanks, looks good!
Feel free to maintainer merge on my behalf once you have merged master.

**Comment by Ruben-VandeVelde** [comment]
> Thanks, looks good! Feel free to maintainer merge on my behalf once you have merged master.

maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
