### PR TITLE
[Merged by Bors] - chore: don't import `Set.indicator` in `Topology.ContinuousOn`

### PR DESCRIPTION
**Pull request by YaelDillies**
This is a first step towards not depending on algebra in basic topology

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
So the issue here is that One counts as algebra, unlike Zero which is fundamental? That seems somewhat arbitrary. Assuming this is what we settle on, the code changes here seem fine.

maintainer merge?

**Comment by YaelDillies** [comment]
> So the issue here is that One counts as algebra, unlike Zero which is fundamental?

No, both count as algebra. What makes you think otherwise?

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by Ruben-VandeVelde** [comment]
> > So the issue here is that One counts as algebra, unlike Zero which is fundamental?
> 
> No, both count as algebra. What makes you think otherwise?

Well, `Zero`'s in `Init.Prelude` now

**Comment by YaelDillies** [comment]
Ah sure, but `Algebra.Group.Indicator` doesn't just import `One`. It imports all the basic algebra hierarchy.

**Pull request closed without merging**
