### PR TITLE
[Merged by Bors] - feat: Missing transfer instances

### PR DESCRIPTION
**Pull request by YaelDillies**
Match https://github.com/leanprover-community/mathlib/pull/18247

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by fpvandoorn** [comment]
Please fix error. If the change was simple, feel free to merge yourself

bors d+

**Comment by YaelDillies** [comment]
Uhoh, looks like we're hitting the same problem as in #1238. I suspect it has to do with `Function.Injective.addGroupWithOne` now being reducible.

Posted on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/reducible.20non-instances).

**Comment by eric-wieser** [comment]
Looks like this is happy after merging master

**Comment by fpvandoorn** [comment]
Ok, cool. Then let's merge this

bors merge

**Pull request closed without merging**
