### PR TITLE
[Merged by Bors] - feat: add some docstrings to lemmas specialized to Nat and Int

### PR DESCRIPTION
**Pull request by fpvandoorn**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by riccardobrasca** [comment]
Thanks!

bprs d+

**Comment by riccardobrasca** [comment]
bors d+

**Comment by fpvandoorn** [comment]
bors merge

**Comment by fpvandoorn** [comment]
It seems this was forgotten? I'll try again.

bors merge

**Pull request closed without merging**
