### PR TITLE
[Merged by Bors] - chore: remove CoeFun instances where FunLike is available

### PR DESCRIPTION
**Pull request by Vierkantor**
During the port we found that `FunLike` is robust enough not to need an extra `CoeFun` shortcut. Let's see if that rule can be consistently applied to the whole of the library.

There is still duplication between `FunLike` and `CoeFun` for `Grp`, `Mon`, `CommGrp` and `CommMon`, which will need a more thorough fix. See also https://github.com/leanprover-community/mathlib4/pull/17866.

There is also a shortcut instance that we need for speed reasons: `SemilinearIsometry.instCoeFun`. I don't know why this is so performance-sensitive but the benchmarks tell us that it is.

See also #17871 for removing porting notes and comments where this change happened earlier on.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Vierkantor** [comment]
!bench

**Review by jcommelin — COMMENTED** [review]
Thanks :tada: 

If CI passes, please remove the label `awaiting-CI` and merge this yourself, by adding a comment `bors r+`.

bors d+

**Comment by Vierkantor** [comment]
!bench

**Comment by Vierkantor** [comment]
Not sure why that one file is so much slower: I didn't touch anything involving `LinearMap` or `ContinuousLinearMap` which seem to be the only types of maps that I can find in that file. If there's no simple explanation, I'm willing to eat the slowdown in exchange for cleaner code.

**Comment by Vierkantor** [comment]
!bench

**Comment by Vierkantor** [comment]
Hmm. Binary search to see which subset of lemmas breaks the bench?

**Comment by Vierkantor** [comment]
See #17921 for the benchmarks proving that `SemilinearIsometry.instCoeFun` is to blame for the slowdown.

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
