### PR TITLE
feat(SetTheory/Cardinal/Basic): generalize universes

### PR DESCRIPTION
**Pull request by vihdzp**
We generalize the universes in `bddAbove_range` by taking in a `Small` hypothesis instead.

---

We don't perform this same change in `Ordinal` just yet, as there are a couple more theorems about the supremum that could also be generalized after #15820 goes through.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
Should we preserve the old version so avoid `have := `s everywhere?

**Comment by vihdzp** [comment]
Ideally we wouldn't even need `have` and this would just be an instance, but the docstring on `small_max` suggests this doesn't work. That said, it surprises me that just writing `have := small_max` without specifying arguments or universes is enough for the instance to be found. Maybe the regression was fixed?

I'll test if adding back the instance works. If not, I'll add back the old version with a prime.

**Comment by vihdzp** [comment]
I made #16516, which should make it so that the `have` are no longer necessary.

**Comment by vihdzp** [comment]
I've started a [Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/using.20UnivLE/near/468054654) to discuss the best course of action here.

**Comment by vihdzp** [comment]
I think I was a bit confused. I'll make the primed lemma in a bit.

**Comment by vihdzp** [comment]
I made the old version into a primed lemma. It's a bit unfortunate that this is the more useful version a lot of the time...

**Comment by vihdzp** [comment]
Just realized that this lemma can actually be subsumed by `bddAbove_of_small`. Will close this PR and open a new one deprecating it.

**Pull request closed without merging**
