### PR TITLE
chore(Archive/IMO/2024Q2): `apply (...).trans` instead of `suffices (...); exact`

### PR DESCRIPTION
**Pull request by madvorak**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by vihdzp — APPROVED** [review]

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Comment by eric-wieser** [comment]
I think the point in some of the archive is that they are more readable and less golfed than mathlib. So I don't think this change is a good one.

Let's let @jsm28 decide, as the original author of this file.

**Comment by vihdzp** [comment]
I don't think this really harms readability, all you're doing is reordering tactics to avoid writing a goal explicitly.

**Comment by semorrison** [comment]
But avoiding writing the goal explicitly ipso facto reduces readability!

**Comment by madvorak** [comment]
> I think the point in some of the archive is that they are more readable and less golfed than mathlib. So I don't think this change is a good one.
> 
> Let's let @jsm28 decide, as the original author of this file.

This is a good point.

I didn't want to golf per se; I'd just like to keep `suffices` to places where it is meaningful, which I believe are places where:
```
(...)
suffices (...)
. <short proof>
<long proof>
```

**Comment by eric-wieser** [comment]
> I'd just like to keep `suffices` to places where it is meaningful, which I believe are places where:

If your objection is that the short and longs proofs are the wrong way around, then the resolution is to swap `suffices` for `have`, which preserves the explicit statement.

I think the choice between `have`/`suffices` is subjective though, and not tied exclusively to Lean proof length.

**Comment by madvorak** [comment]
> > I'd just like to keep `suffices` to places where it is meaningful, which I believe are places where:
> 
> If your objection is that the short and longs proofs are the wrong way around, then the resolution is to swap `suffices` for `have`, which preserves the explicit statement.
> 
> I think the choice between `have`/`suffices` is subjective though, and not tied exclusively to Lean proof length.

Ah yes. I think `have` would be better here. So should I change it to `have` or close this PR?

**Comment by eric-wieser** [comment]
I vote close the PR, I suspect Joseph has better things to do than review subjective style changes to his proofs!

**Comment by vihdzp** [comment]
I may agree with this change, but yeah, this is bikeshedding.

**Pull request closed without merging**
