### PR TITLE
[Merged by Bors] - chore: rm `@[simp]` from factorial_succ

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
suggested by @alreadydone here https://github.com/leanprover-community/mathlib4/pull/6806#discussion_r1307755812

**Comment by alreadydone** [comment]
Thanks!
I can find some similar lemmas in mathlib that are simp lemmas (e.g. [Polynomial.hermite_succ](https://leanprover-community.github.io/mathlib4_docs/Mathlib/RingTheory/Polynomial/Hermite/Basic.html#Polynomial.hermite_succ), [Cardinal.aleph'_succ](https://leanprover-community.github.io/mathlib4_docs/Mathlib/SetTheory/Cardinal/Ordinal.html#Cardinal.aleph'_succ), aleph_succ, beth_succ) and some that are not ([GeneralizedContinuedFraction.convergents_succ](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Algebra/ContinuedFractions/Computation/ApproximationCorollaries.html#GeneralizedContinuedFraction.convergents_succ), [Sensitivity.f_succ_apply](https://leanprover-community.github.io/mathlib4_docs/Archive/Sensitivity.html#Sensitivity.f_succ_apply), [Function.iterate_succ_apply](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Logic/Function/Iterate.html#Function.iterate_succ_apply)), and I think it's reasonable to remove `simp` here.

maintainer merge

**Comment by semorrison** [comment]
bors merge

**Comment by mo271** [comment]
> Thanks! I can find some similar lemmas in mathlib that are simp lemmas (e.g. [Polynomial.hermite_succ](https://leanprover-community.github.io/mathlib4_docs/Mathlib/RingTheory/Polynomial/Hermite/Basic.html#Polynomial.hermite_succ), [Cardinal.aleph'_succ](https://leanprover-community.github.io/mathlib4_docs/Mathlib/SetTheory/Cardinal/Ordinal.html#Cardinal.aleph'_succ), aleph_succ, beth_succ) and some that are not ([GeneralizedContinuedFraction.convergents_succ](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Algebra/ContinuedFractions/Computation/ApproximationCorollaries.html#GeneralizedContinuedFraction.convergents_succ), [Sensitivity.f_succ_apply](https://leanprover-community.github.io/mathlib4_docs/Archive/Sensitivity.html#Sensitivity.f_succ_apply), [Function.iterate_succ_apply](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Logic/Function/Iterate.html#Function.iterate_succ_apply)), and I think it's reasonable to remove `simp` here.
> 
@alreadydone 
Perhaps also 
[Function.iterate_succ](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Logic/Function/Iterate.html#Function.iterate_succ) does not need to be simp?

**Comment by alreadydone** [comment]
Probably? If you [search for it](https://github.com/search?q=repo%3Aleanprover-community%2Fmathlib4%20Function.iterate_succ&type=code) you'll see lots of use of the primed version `Function.iterate_succ'` (or `Function.iterate_succ_apply'`) which simplifies it in another way. I must admit I'm not familiar with rationales to mark a lemma `@[simp]` or not, as I seldom at any `simp` attribute in my work at all ...

**Pull request closed without merging**
