### PR TITLE
feat: define Bitvec constants for -1, INT_MIN and INT_MAX

### PR DESCRIPTION
**Pull request by alexkeizer**
Define constant bitvectors that represent -1, the minimal negative signed integer, and the maximal positive signed integer, at arbitrary bitwidths

---

- [x] depends on #4994 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ChrisHughes24** [comment]
Why not just use `-1` for `negOne` if there is already a `Neg` instance and a `One` instance.

**Comment by alexkeizer** [comment]
> Why not just use `-1` for `negOne` if there is already a `Neg` instance and a `One` instance.

Having the constant allows us to attach a docstring explaining that this constant has bitpattern `1111...`, and that it coincides with `UINT_MAX`. Especially in situations where we use the constant not for its integer value, but because of either of these (not immediately apparent) properties, I think it's important to have some extra explanation as to why `-1` is used.

I also contemplated calling this constant `allOnes` (in reference to the bitpatter), or `uintMax`, for a bit more of a descriptive name.

**Comment by ChrisHughes24** [comment]
From a proving perspective it's a very bad idea to have multiple different ways of writing the same thing. It's hard to say what the correct perspective is here, because I guess programmers like having different names for the same thing. Maybe we have all the definitions but we note that it's recommended to use `-1` in theorem statements, and `-1` is the simp-normal form.

**Comment by ChrisHughes24** [comment]
Or maybe they should be abbreviations or notations or something.

**Comment by alexkeizer** [comment]
There is definitely a bit of a conflict between the programmer's perspective (who prefers longer, descriptive names for things) and the mathematician (who prefers concise notation). I don't know which perspective is right, but I guess for mathlib the second is more appropriate.

Regardless, we snould have a single simp normal form for all alternative spellings.
I wanted to include those lemmas here, but they're blocked on the `Vector` PR. I'd be OK with having `negOne` for the documentation, but including
```lean
theorem negOne_eq_neg_one : negOne n = -1 := by
  sorry
```

I explicitly did not make `negOne` an abbreviation of `-1`, because the `Vector.replicate` spelling is nicer to proof things with, and I expect a lot proofs to start with the reverse rewrite of `negOne_eq_neg_one`

**Comment by alexkeizer** [comment]
But if you think that is a bad reason, I am also OK with having
```lean
abbrev negOne := -1
```
And then do the rewrite to `Vector.replicate` as a theorem

**Comment by ChrisHughes24** [comment]
> I explicitly did not make `negOne` an abbreviation of `-1`, because the `Vector.replicate` spelling is nicer to proof things with, and I expect a lot proofs to start with the reverse rewrite of `negOne_eq_neg_one`

Why not just prove `neg_one_eq_replicate` and start proofs with that?

**Comment by alexkeizer** [comment]
That would also work, so then I'll keep `negOne` for the documentation, but change it to be an abbrev of `-1`?

**Comment by alexkeizer** [comment]
I had to reorder the file a bit, so that `-1` is actually defined in the Constants section. I also marked `negOne` as `simp`, so that `-1` is indeed the simp normal form.

**Pull request closed without merging**
