### PR TITLE
[Merged by Bors] - chore: Fix capitalisation of e-transforms

### PR DESCRIPTION
**Pull request by YaelDillies**
Everything was wrong here.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by b-mehta — APPROVED** [review]
Good catch. Make sure to merge master!

bors d+

**Comment by YaelDillies** [comment]
Why merge master? There's no merge conflict.

**Comment by b-mehta** [comment]
Oh for some reason it showed me earlier that there were merge conflicts, never mind

**Comment by robertylewis** [comment]
bors merge

**Pull request closed without merging**
