### PR TITLE
[Merged by Bors] - feat: `Option {b // b ≠ a} ≃ α`

### PR DESCRIPTION
**Pull request by BoltonBailey**
Extract from `partialFunEquivPointed` the equivalence between any type with a distinguished element and an Option type.

Co-authored-by: @YaelDillies <yael.dillies@gmail.com>
Co-authored-by: @fpvandoorn <fpvdoorn@gmail.com>

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by BoltonBailey** [comment]
See discussion [here](https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/Equivalence.20of.20type.20with.20an.20element.20to.20an.20option.20type/near/424331279).

**Comment by fpvandoorn** [comment]
LGTM

@BoltonBailey, are you also happy with these changes from @YaelDillies?

bors d+

**Comment by BoltonBailey** [comment]
Yeah seems great! Thanks @YaelDillies!

**Pull request closed without merging**
