### PR TITLE
[Merged by Bors] - feat: add an instance for `T3Space`

### PR DESCRIPTION
**Pull request by urkud**
Add an instance `[T0Space α] [RegularSpace α] : T3Space α`,
drop now unneeded lemmas like `TopologicalGroup.t3Space`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
bench!

**Comment by urkud** [comment]
!bench

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by Ruben-VandeVelde** [comment]
```
Error: ./././Mathlib/Topology/Algebra/Group/Basic.lean:1511:42: error: unknown constant 'TopologicalGroup.t2Space'
Error: ./././Mathlib/Topology/Algebra/Group/Basic.lean:1518:26: error: unknown constant 'TopologicalGroup.t2Space'
```

**Comment by ChrisHughes24** [comment]
This seems to be the one with the problem

bors r-

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
