### PR TITLE
[Merged by Bors] - feat: port RingTheory.Polynomial.Content

### PR DESCRIPTION
**Pull request by mattrobball**
---

- [x] depends on: #3057
[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3057
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3057~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by mattrobball** [comment]
Oops. Sorry

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
