### PR TITLE
feat: "prove" import order independence (and document existing order dependencies) by linting unsorted imports

### PR DESCRIPTION
**Pull request by euprunin**
---
Rationale:
* Reduces the risk of introduction of new unintentional import order dependencies
* Documents existing (potential) import order dependencies as linting exceptions
* Simplifies the identification and resolution of merge conflicts
* Establishes a standard format for imports

To verify that all modified lines in the last commit are import statements:

`% git diff HEAD~1 | grep '^[+-][^+-]' | cut -c2- | grep -v '^import '`

To verify that the total number of changes (additions and deletions) for any specific import statement is even:

`% git diff HEAD~1 | grep '^[+-][^+-]' | cut -c2- | sort | uniq -c | grep -v '[02468] import'`

### CODE REVIEW

**Comment by adomani** [comment]
Given the previous experiment with sorting imports, besides building, an important feature that this PR should have is `!bench` showing that there is no regression.  For me, an improvement in performance is a necessary condition for such a change.

**Comment by adomani** [comment]
Anyone: simply write a comment consisting only of !bench and it should work (maybe it is more permissive, I don't really know).

However, the branch should pass CI (at least the `lake build` step).

**Comment by grunweg** [comment]
Looking at the benchmark still shows an overall regression. (The "instructions" metric reports about 60*10⁹ additional instructions.) This is large enough that I don't think we should land this as-is. Can you look at this again?

The benchmarking page has the option to sort by "absolute change"; that could be helpful here...

**Comment by adomani** [comment]
Below is a summary of the changes by at least 10⁹ instructions: such differences roughly correspond to "significant" changes and should be taken somewhat seriously.

|File|Instructions|%|
|-|-:|:-:|
|`Increase`|||
|build|+10.886⬝10⁹|(+0.0%)|
|Mathlib.Analysis.Normed.Operator.Banach|+9.509⬝10⁹|(+8.53%)|
|Mathlib.Topology.Sheaves.SheafCondition.PairwiseIntersections|+6.355⬝10⁹|(+6.34%)|
|Mathlib.LinearAlgebra.TensorProduct.Graded.Internal|+5.539⬝10⁹|(+2.2%)|
|Mathlib.Analysis.SpecialFunctions.Trigonometric.Deriv|+5.496⬝10⁹|(+4.12%)|
|Mathlib.AlgebraicGeometry.StructureSheaf|+4.675⬝10⁹|(+2.86%)|
|Mathlib.Geometry.RingedSpace.PresheafedSpace.Gluing|+4.405⬝10⁹|(+1.16%)|
|Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Instances|+4.238⬝10⁹|(+1.47%)|
|Mathlib.NumberTheory.Cyclotomic.PrimitiveRoots|+2.927⬝10⁹|(+2.88%)|
|Mathlib.AlgebraicGeometry.Properties|+2.871⬝10⁹|(+8.17%)|
|Mathlib.Geometry.Manifold.Sheaf.Smooth|+2.789⬝10⁹|(+4.23%)|
|Mathlib.FieldTheory.AbelRuffini|+2.768⬝10⁹|(+3.10%)|
|Mathlib.Analysis.Seminorm|+2.507⬝10⁹|(+1.41%)|
|Mathlib.NumberTheory.Padics.PadicIntegers|+2.207⬝10⁹|(+4.21%)|
|Mathlib.FieldTheory.PurelyInseparable|+2.4⬝10⁹|(+0.79%)|
|Mathlib.Analysis.SpecialFunctions.Pow.NNReal|+1.983⬝10⁹|(+4.80%)|
|Mathlib.Algebra.Lie.Weights.Basic|+1.955⬝10⁹|(+1.45%)|
|Mathlib.RingTheory.Jacobson|+1.869⬝10⁹|(+2.13%)|
|Mathlib.Geometry.Manifold.VectorBundle.Basic|+1.848⬝10⁹|(+2.76%)|
|Mathlib.NumberTheory.ClassNumber.FunctionField|+1.756⬝10⁹|(+15.72%)|
|Mathlib.NumberTheory.Cyclotomic.Discriminant|+1.711⬝10⁹|(+3.94%)|
|Mathlib.FieldTheory.RatFunc.Basic|+1.706⬝10⁹|(+0.78%)|
|Mathlib.Geometry.Manifold.MFDeriv.SpecificFunctions|+1.701⬝10⁹|(+2.14%)|
|Mathlib.Geometry.Manifold.MFDeriv.Basic|+1.699⬝10⁹|(+2.25%)|
|Mathlib.AlgebraicTopology.FundamentalGroupoid.Basic|+1.685⬝10⁹|(+2.6%)|
|Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Topology|+1.663⬝10⁹|(+4.9%)|
|Mathlib.RingTheory.Valuation.ValuationSubring|+1.591⬝10⁹|(+1.25%)|
|Mathlib.Topology.Homotopy.HomotopyGroup|+1.485⬝10⁹|(+1.31%)|
|Mathlib.Analysis.PSeries|+1.452⬝10⁹|(+2.49%)|
|Mathlib.Data.Complex.Exponential|+1.451⬝10⁹|(+1.5%)|
|Mathlib.NumberTheory.GaussSum|+1.390⬝10⁹|(+4.27%)|
|Mathlib.Analysis.SpecialFunctions.Gamma.Beta|+1.339⬝10⁹|(+3.19%)|
|Mathlib.Geometry.Manifold.ContMDiff.NormedSpace|+1.306⬝10⁹|(+0.64%)|
|Mathlib.Topology.Sheaves.SheafCondition.EqualizerProducts|+1.269⬝10⁹|(+1.5%)|
|Mathlib.AlgebraicGeometry.FunctionField|+1.195⬝10⁹|(+6.61%)|
|Mathlib.Geometry.RingedSpace.LocallyRingedSpace.HasColimits|+1.150⬝10⁹|(+3.24%)|
|Mathlib.NumberTheory.Cyclotomic.Rat|+1.143⬝10⁹|(+0.89%)|
|Mathlib.RingTheory.Ideal.Over|+1.140⬝10⁹|(+2.14%)|
|Mathlib.MeasureTheory.Measure.Haar.Disintegration|+1.120⬝10⁹|(+2.11%)|
|Mathlib.Analysis.SpecialFunctions.Gaussian.FourierTransform|+1.117⬝10⁹|(+1.34%)|
|Mathlib.MeasureTheory.Measure.Haar.Unique|+1.94⬝10⁹|(+1.58%)|
|Mathlib.AlgebraicGeometry.PrimeSpectrum.Basic|+1.81⬝10⁹|(+3.90%)|
|Mathlib.RepresentationTheory.GroupCohomology.Resolution|+1.50⬝10⁹|(+0.36%)|
|Mathlib.NumberTheory.LegendreSymbol.GaussEisensteinLemmas|+1.47⬝10⁹|(+2.30%)|
|Mathlib.Data.Set.Pointwise.Interval|+1.31⬝10⁹|(+1.20%)|
|Mathlib.RingTheory.Ideal.Basic|+1.17⬝10⁹|(+3.22%)|
|`Decrease`|||
|Mathlib.Algebra.Module.PID|-10.790⬝10⁹|(-5.70%)|
|Mathlib.Algebra.Order.CauSeq.Basic|-5.829⬝10⁹|(-7.55%)|
|Mathlib.LinearAlgebra.TensorProduct.Graded.External|-5.312⬝10⁹|(-2.3%)|
|Mathlib.ModelTheory.Substructures|-4.126⬝10⁹|(-13.38%)|
|Mathlib.Analysis.SpecialFunctions.ContinuousFunctionalCalculus.ExpLog|-4.11⬝10⁹|(-11.8%)|
|Mathlib.Topology.VectorBundle.Hom|-3.913⬝10⁹|(-4.27%)|
|Mathlib.Analysis.NormedSpace.HahnBanach.SeparatingDual|-3.73⬝10⁹|(-6.89%)|
|Mathlib.NumberTheory.ModularForms.JacobiTheta.TwoVariable|-3.60⬝10⁹|(-3.21%)|
|Mathlib.RingTheory.RootsOfUnity.Complex|-3.35⬝10⁹|(-12.67%)|
|Mathlib.Topology.ContinuousFunction.Ideals|-2.834⬝10⁹|(-4.35%)|
|Mathlib.NumberTheory.FLT.Three|-2.592⬝10⁹|(-1.99%)|
|Mathlib.Analysis.Normed.Operator.BoundedLinearMaps|-2.579⬝10⁹|(-2.61%)|
|Mathlib.Topology.VectorBundle.Basic|-2.355⬝10⁹|(-3.89%)|
|Mathlib.Topology.Instances.ENNReal|-2.82⬝10⁹|(-2.55%)|
|Mathlib.MeasureTheory.Measure.MeasureSpace|-1.980⬝10⁹|(-2.13%)|
|lint|-1.928⬝10⁹|(-0.2%)|
|Mathlib.Analysis.SpecialFunctions.Complex.Arg|-1.853⬝10⁹|(-3.92%)|
|Mathlib.RingTheory.SimpleModule|-1.798⬝10⁹|(-2.61%)|
|Mathlib.Analysis.CStarAlgebra.GelfandDuality|-1.730⬝10⁹|(-2.7%)|
|Mathlib.FieldTheory.KummerExtension|-1.672⬝10⁹|(-1.16%)|
|Mathlib.Algebra.Order.ToIntervalMod|-1.523⬝10⁹|(-1.89%)|
|Mathlib.Analysis.Fourier.FourierTransformDeriv|-1.514⬝10⁹|(-0.36%)|
|Mathlib.RingTheory.Valuation.AlgebraInstances|-1.486⬝10⁹|(-1.59%)|
|Mathlib.NumberTheory.LSeries.HurwitzZetaEven|-1.380⬝10⁹|(-2.24%)|
|Mathlib.LinearAlgebra.Ray|-1.375⬝10⁹|(-1.86%)|
|Mathlib.AlgebraicGeometry.Modules.Tilde|-1.371⬝10⁹|(-3.74%)|
|Mathlib.Analysis.NormedSpace.OperatorNorm.Asymptotics|-1.349⬝10⁹|(-11.80%)|
|Mathlib.LinearAlgebra.ExteriorAlgebra.Basic|-1.340⬝10⁹|(-1.93%)|
|Mathlib.SetTheory.Ordinal.FixedPointApproximants|-1.335⬝10⁹|(-15.36%)|
|Mathlib.Algebra.Lie.Weights.RootSystem|-1.248⬝10⁹|(-0.62%)|
|Mathlib.MeasureTheory.Measure.ProbabilityMeasure|-1.242⬝10⁹|(-1.54%)|
|Mathlib.LinearAlgebra.Matrix.DotProduct|-1.238⬝10⁹|(-6.35%)|
|Mathlib.LinearAlgebra.Orientation|-1.190⬝10⁹|(-1.54%)|
|Mathlib.Algebra.Category.ModuleCat.ChangeOfRings|-1.159⬝10⁹|(-0.31%)|
|Mathlib.LinearAlgebra.Projectivization.Subspace|-1.126⬝10⁹|(-9.1%)|
|Mathlib.Analysis.SpecialFunctions.Stirling|-1.92⬝10⁹|(-2.13%)|
|Mathlib.RingTheory.Algebraic|-1.78⬝10⁹|(-2.46%)|
|Mathlib.RingTheory.PowerSeries.Inverse|-1.41⬝10⁹|(-3.88%)|

**Comment by Parcly-Taxel** [comment]
Gee, don't trigger the bench after every push! Only when you are satisfied with your changes and have everything compiling.

**Comment by grunweg** [comment]
Since this PR is performance neutral, I don't see a strong argument against merging it. I wonder if this is an efficient way use of everybody's time, as reviewing a diff of several hundred lines is always daunting and I'm how not sure how big the benefits are. I wouldn't object to merging this one, though.

**Pull request closed without merging**
