### PR TITLE
[Merged by Bors] - feat: port Analysis.SpecificLimits.Normed

### PR DESCRIPTION
**Pull request by int-y1**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by int-y1** [comment]
todo:

* [ ] `TFAE_exists_lt_isLittleO_pow` error with `tfae_finish`
* [ ] `hasSum_coe_mul_geometric_of_norm_lt_1` a problem with using `tsum_mul_left`
* [ ] `Monotone.cauchySeq_series_mul_of_tendsto_zero_of_bounded` error
* [ ] `Real.summable_pow_div_factorial` 'with' syntax is not yet supported in 'mono'

**Comment by mo271** [comment]
> * [x]  `TFAE_exists_lt_isLittleO_pow` error with `tfae_finish`

Seems like a tfae bug, I added an extra tfae_have, which is just a combination of others and it worked

**Comment by mo271** [comment]
> * ``
> * [x]  `hasSum_coe_mul_geometric_of_norm_lt_1` a problem with using `tsum_mul_left`

There was some trouble inferring the right instances. Setting etaExperience to true seems to fix it.

**Comment by mo271** [comment]
> [x] `Monotone.cauchySeq_series_mul_of_tendsto_zero_of_bounded` error

Helping refine by spelling out one of the holes worked.

**Comment by mo271** [comment]
[I'm not working on this right now...]

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2323
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
We shouldn't wait for critical ports on tactics being available, when it's easy to extract the term mode proof from mathlib3. `show_term` is your friend. :-)

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
