### PR TITLE
fix: add mk_all to Lint style

### PR DESCRIPTION
**Pull request by adomani**
See [Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/flakiness.20in.20style.20linter.3F)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
The actual issue has been discovered and resolved by Ruben's #16699, so I am closing this PR.

**Comment by bryangingechen** [comment]
I wonder if this could save contributors a tiny bit of time in the situtation where they have added new files but forgotten to add them to Mathlib.lean? Then with the current workflows those new files would not be linted until after they saw the complaint from `lake exe mk_all` at the very end of the build job and then pushed a new commit fixing that.

(If we want to go with something like this PR, then we may have to adjust the lint and suggest and bot fix style workflows to be consistent with the changes here as well).

**Comment by bryangingechen** [comment]
Now that I look at it more closely, the "lint and suggest" workflow runs `lake exe mk_all` in a parallel job, which saves even more time at the cost of using more (Github hosted) runners.

**Comment by adomani** [comment]
I also had #14077, but was not really happy with it, even though it was delegated.  If you think that it is fine, I can merge master and then `bors r+` it!

**Pull request closed without merging**
