### PR TITLE
[Merged by Bors] - feat(NumberTheory.SmoothNumbers): add `{smooth|rough}NumbersUpTo` and some API

### PR DESCRIPTION
**Pull request by MichaelStollBayreuth**
This adds definitions of the `k`-smooth numbers up to and including `N` as a `Finset` and of its complement in `{1, ..., N}` plus some API, in particular cardinality bounds. There are also a few additional API lemmas for `Nat.primesBelow` and `Nat.smoothNumbers` (including a decidability instance for membership in the latter).

This is a PR in preparation of the divergence of the sum of the reciprocals of the primes. See [here](https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/Sum.20over.201.2Fp.20diverges/near/409835682) on Zulip.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by MichaelStollBayreuth** [comment]
Marked as "WIP" for now, since I may want to add more things.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by MichaelStollBayreuth** [comment]
Some lemma names have changed in between. I'll merge master and fix that.

**Comment by MichaelStollBayreuth** [comment]
@jcommelin It builds again now. Can you kick it back on the queue?

**Comment by MichaelStollBayreuth** [comment]
@alreadydone The label doesn't seem to work. Maybe it has to be removed from the merge queue explicitly first?

**Comment by alreadydone** [comment]
Maybe it works if we re-trigger the CI; is that a waste of resources? But it's currently (strangely) showing a red cross so it's probably a good idea to re-trigger CI ...

**Comment by MichaelStollBayreuth** [comment]
The build shows an error in an unrelated file:
```
Error: ./././Mathlib/Algebra/BigOperators/Basic.lean:602:59: error: unexpected token '@['; expected 'abbrev', 'alias', 'axiom', 'binder_predicate', 'builtin_initialize', 'class', 'def', 'elab', 'elab_rules', 'example', 'inductive', 'infix', 'infixl', 'infixr', 'initialize', 'instance', 'irreducible_def', 'lemma', 'macro', 'macro_rules', 'notation', 'notation3', 'opaque', 'postfix', 'prefix', 'proof_wanted', 'scoped', 'structure', 'syntax' or 'theorem'
```
In my copy of Mathlib, this line is
```lean
  refine' Eq.trans _ (prod_sigma s t fun p => f (p.1, p.2))
```
so I have no idea what this error is about...

**Comment by alreadydone** [comment]
Probably that's due to the other PR #9237 in the same batch.
image
I've merged master which retriggered CI.

**Pull request closed without merging**
