### PR TITLE
[Merged by Bors] - feat: patch for new alias command

### PR DESCRIPTION
**Pull request by fgdorais**
---

- [x] depends on: #5992
- [x] depends on: https://github.com/leanprover/std4/pull/200

See also this [discussion on Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/alias.20command.20ordering).

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by fgdorais** [comment]
This is a *huge* PR because it reflects a change in notation for the `alias` command. The first commit deals with removing the old command and the second, the huge one, changes the notation for all old alias commands. Because of its nature, this PR will systematically have merge conflicts up until the end...

**Comment by kbuzzard** [comment]
For me this change is very welcome: I'd seen these alias commands before with the funny arrows and never really knew what they did; now it's absolutely clear without having to look anything up.

**Comment by fgdorais** [comment]
@semorrison I just updated this patch. Roll it into #6721 once it passes CI.

**Comment by semorrison** [comment]
Please merge or rebase after #6721 lands, and then send to bors!

bors d+

**Comment by fgdorais** [comment]
bors try

**Comment by fgdorais** [comment]
bors try

**Comment by fgdorais** [comment]
bors merge

**Pull request closed without merging**
