### PR TITLE
[Merged by Bors] - chore: port lint-style.py from mathlib

### PR DESCRIPTION
**Pull request by kim-em**
Some of these are no longer relevant, but I want to see what works before cleaning up.

### CODE REVIEW

**Comment by semorrison** [comment]
This runs, and respects the content of `scripts/style-extensions.txt`.

I propose that actually fixing style exceptions, and removing the style tests which are not relevant for mathlib4 (e.g. I think the curly brace linter), happens in a subsequent PR.

**Comment by gebner** [comment]
Obviously this should eventually be rewritten in Lean, but we can use the python script for now.

Before merging, we should remove the curly braces linter though because it has lots of false positives.

**Comment by semorrison** [comment]
I've removed the curly brace linter, the indentation linter and the `unfreeze_local_instance` linter, as they are not fit for purpose for Lean4. I've also added a TODO about re-implementing in Lean4!

**Comment by gebner** [comment]
Great, all exceptions look legit now!

bors merge

**Pull request closed without merging**
