### PR TITLE
feat: add unsorted imports linter

### PR DESCRIPTION
**Pull request by euprunin**
---
This is an easier to review alternative to PR #16419. This PR only adds the linter and does not change any imports. Currently unsorted imports are added to `nolints-style.txt`.

Rationale for sorting imports:
* Reduces the risk of introduction of new unintentional import order dependencies
* Documents existing (potential) import order dependencies as linting exceptions
* Simplifies the identification and resolution of merge conflicts
* Establishes a standard format for imports

### CODE REVIEW

**Review by mo271 — COMMENTED** [review]
LGTM
It is still a mystery to me why sometimes the order of the imports changes performance (if I understand correctly)

**Comment by grunweg** [comment]
I won't have time to review this in depth until October, sorry. That said, the implementation looks straightforward, so the harder part is deciding if this PR is desirable. (If import order had no performance effects, I would say "clearly yes", but sadly the story is not as simple.)

Two quick thoughts:
- given that this linter produces sometimes unhelpful warnings, I'm not sure if it should be active by default. (Putting comments when out of order imports are intentionally left so does seem useful, though.)
- I don't think putting 1800 entries into nolints-style should land as-is. If there are many exceptions, they should be auto-updatable (which that file intentionally is not); rather style-exceptions.txt should be restored. If we foresee exceptions changing, one could also just comment the few cases of intentional out of order imports. 
- If (almost) all imports should be sorted, I wonder if a PR changing most of these is fine and should land before (perhaps split into parts).

A good next step could be to start a discussion in the #mathlib stream, trying to gauge if this PR is desired or not.
I gather this PR and its predecessor have been sitting, mostly without attention for two weeks. I can imagine this is a rather unsatisfactory situation for you, @eprunin. I'm sorry for that. Collectively deciding about a (at least slightly) controversial PR takes time --- one way you can accelarate is by asking on zulip first.

(I don't remember a zulip threat about this, but haven't checked. If there was already, sorry for the noise. In that case, I'd rather label with PR with awaiting-zulip, or link to the discussion in the description.)

**Comment by grunweg** [comment]
Actually, let me label this with awaiting-zulip: I think there should first be a decision if this PR is wanted by the mathlib maintainers. (I am not a maintainer.)

**Comment by adomani** [comment]
Assuming that this is something that receives approval, I would probably recommend to create a PR depending on

#16574

that extends that linter by checking that the (parsed) imports are sorted.

**Pull request closed without merging**
