### PR TITLE
feat: port Data/RBTree/Init as deprecated definitions

### PR DESCRIPTION
**Pull request by arienmalec**
#align annotations and deprecation of `mathlib` `RBTree`

From (AKA deletes & deprecates) `mathlib` 7cca171008afb30576d2d4c51173700a780c23d0

### CODE REVIEW

**Comment by arienmalec** [comment]
Also needs the magic to ignore the deprecated linting

**Comment by arienmalec** [comment]
Keep open until I add the sorried ported theorems

**Comment by arienmalec** [comment]
Everything's there now; needs the lint-ignore-fu to make it compile. I'll probably comment out anything that doesn't have a trivial fix to typecheck.

**Comment by digama0** [comment]
the long lines at least should be fixed, and the formatting needs work (try to make it look more like the lean 3 file and less like something that a machine generated)

**Comment by digama0** [comment]
Hi @arienmalec , I think that this PR isn't going to be mergeable and perhaps this was too unusual of a target for straightforward porting. I suggest you find a simpler target which hasn't changed as radically as this and/or has less meta code in it.

**Comment by arienmalec** [comment]
Darn - just got it into shape where it doesn't error!

**Pull request closed without merging**
