### PR TITLE
[Merged by Bors] - feat: port Data.Nat.Choose.Multinomial

### PR DESCRIPTION
**Pull request by mo271**
- [x] depends on: #2168 

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2168
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by mo271** [comment]
Currently two things remain to be fixed:

- [ ] `multinomial_univ_three`, probably similar to the fix for ` multinomial_univ_two`, getting rid of `Matrix.foo`
- [ ] `sum_pow_of_commute`: here `Subsingleton (Finset.sym (∅ : Finset α) zero) ` and `IsEmpty (Finset.sym ∅ (succ n)) ` seem to be needed where mathlib3 seemed to be albe to infer those instance on its own. Also there is one place in the proof that still needs fixing, even with those two added.

**Comment by mo271** [comment]
I don't plan to work on this until the depedency is resolved

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2168~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by mo271** [comment]
This is now rebased and everything works, except `sum_pow_of_commute`, where we have two instances missing.
Can you have a look, if we need to add those instances somewhare, @xroblot?

**Comment by xroblot** [comment]
I added a couple of missing instances and fixed a few things. There is still one problem left. 

Note however that my fix for the missing instances was just to call explicitly the instance which is probably not the right fix. We may have to ask at some point on Zulip for a better way to fix that.

**Comment by mo271** [comment]
> We may have to ask at some point on Zulip for a better way to fix that.

https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Data.2ENat.2EChoose.2EMultinomial

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
