### PR TITLE
[Merged by Bors] - feat: port Logic/Basic

### PR DESCRIPTION
**Pull request by kim-em**
Two reasons to get this out of the way:
* it's at the root of all our (non-tactic) import trees, so blocking almost everything
* it's more complicated than most other things, because it contains a partial port of the mathlib3 content, but so does `Std4`

I've attempted to make sure everything from mathlib3's `logic.basic` is here, *unless* it is already in Std4. Additionally I've replaced some definitions with aliases.

Thanks for @javra's work on this.

Discussion of this PR is ongoing on [zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/porting.20logic.2Ebasic).

### CODE REVIEW

**Comment by javra** [comment]
Opened an [issue](https://github.com/leanprover/lean4/issues/1762) to investigate the difference in `simp` behavious

**Comment by semorrison** [comment]
Could we please not force push to public branches? I don't know what's going on with the merge conflicts here, and it's hard to work out when the history has been borked.

**Comment by javra** [comment]
@digama0 Sorry, I rebased and forgot this was a public branch for a brainfart seond.

**Comment by digama0** [comment]
bors merge

**Pull request closed without merging**
