### PR TITLE
[Merged by Bors] - feat: Port Combinatorics.SimpleGraph.StronglyRegular

### PR DESCRIPTION
**Pull request by casavaca**
---

- [x] depends on: #1883 

Help wanted: One error left: This `simp` doesn't work. It's weird because if you guide lean, `rw` doesn't work, even if it looks the same. I guess it has something to do with `Quot.liftOn` which hide behind `dsimp [Finset.card, Multiset.card]`?

```lean
theorem h : card (Set.toFinset (neighborSet G v ∩ neighborSet G w)) = k := sorry
example : Fintype.card (G.commonNeighbors v w) = k := by
  rw [←Set.toFinset_card]
  unfold commonNeighbors
  have hh := @h V _ G _ k v w
  rw [←hh] --- Here 1
  congr    --- Here 2
  simp [Set.fintypeInterOfRight]
```

at Here 1: look the same but it's not.
```lean
⊢ card (Set.toFinset (neighborSet G v ∩ neighborSet G w)) =
  card (Set.toFinset (neighborSet G v ∩ neighborSet G w))
```
at Here 2:
```lean
⊢ (Subtype.fintype fun x => x ∈ neighborSet G v ∩ neighborSet G w) =
    Set.fintypeInterOfRight (neighborSet G v) (neighborSet G w)
```
[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#1883
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#1883~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by kmill** [comment]
@casavaca It basically comes down to how in Lean 3 there's a feature where typeclass arguments can be solved for using unification as a fallback, and we designed a number of lemmas with this feature in mind. One workaround is to use `@` and `(_)` arguments (I've left a porting note).

**Pull request closed without merging**
