### PR TITLE
[Merged by Bors] - chore(Normed): move `abs_norm`, add `abs_norm'`

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by adomani — APPROVED** [review]
LGTM, although I wonder if @YaelDillies will feel inspired to split `Mathlib/Analysis/Normed/Group/Basic.lean`!  :smile:

**Comment by YaelDillies** [comment]
Certainly! My motivation here is to remove `Complex.abs` in favour of `norm`, so a split would be very good.

**Comment by urkud** [comment]
Can we merge this simple PR first?

**Comment by YaelDillies** [comment]
Oops, sorry, I meant to in my previous message.

maintainer merge

**Comment by urkud** [comment]
For some reason, the bot did ignore your command.

maintainer merge

**Pull request closed without merging**
