### PR TITLE
feat: port rbtree.init

### PR DESCRIPTION
**Pull request by arienmalec**
Initial port, covers most of the renaming and syntax. Need help with unsupported tactics/options for RBTree.

Made against 8c53048add6ffacdda0b36c4917bfe37e209b0ba

### CODE REVIEW

**Comment by arienmalec** [comment]
In
```
def ins : RBNode α → α → RBNode α
  | leaf _, x => red_node (leaf _) x (leaf _)
  --| leaf             x  := red_node leaf x leaf
```

I'd imagine the correct `mathlib` analogue would be
```
def ins : RBNode α → α → RBNode α
  | leaf y, x => red_node (leaf y) x (leaf y)
  --| leaf             x  := red_node leaf x leaf
```

But needs algo check.

**Comment by Ruben-VandeVelde** [comment]
Is this even used outside tactics / will tactics use this implementation or the one in std4?

**Comment by arienmalec** [comment]
Ah, there's an `RBMap` in std4! Would be far better to make the port use that...

It's transitively included in `data.tree`

**Comment by semorrison** [comment]
Sorry to waste your time on this, but yes, let's ditch this in favour of `RBMap`.

**Pull request closed without merging**
