### PR TITLE
[Merged by Bors] - feat(AlgebraicGeometry/Limits): Coproducts of Schemes

### PR DESCRIPTION
**Pull request by erdOne**
---

- [x] depends on: #14548 
- [x] depends on: #14549 
- [x] depends on: #14550 
- [x] depends on: #14551 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
What do you think of including something like
```lean
structure GlueData' where
  J : Type v
  U : J → C
  V : J × J → C
  f : ∀ i j, V (i, j) ⟶ U i
  f_mono : ∀ i j, Mono (f i j) := by infer_instance
  f_hasPullback : ∀ i j k, HasPullback (f i j) (f i k) := by infer_instance
  f_id : ∀ i, IsIso (f i i) := by infer_instance
  t : ∀ i j, V (i, j) ⟶ V (j, i)
  t_id : ∀ i, t i i = 𝟙 _
  t' : ∀ i j k, pullback (f i j) (f i k) ⟶ pullback (f j k) (f j i)
  t_fac : ∀ i j k, t' i j k ≫ pullback.snd = pullback.fst ≫ t i j
  t_inv' : ∀ i j, i ≠ j → t i j ≫ t j i = 𝟙 _
  cocycle : ∀ i j k, i ≠ j → j ≠ k → k ≠ i → t' i j k ≫ t' j k i ≫ t' k i j = 𝟙 _

namespace GlueData'

attribute [simp] t_id
attribute [instance] f_id f_mono f_hasPullback
attribute [reassoc] t_fac cocycle

variable {C}
variable (D : GlueData' C)

@[simp]
theorem t'_iij (i j : D.J) : D.t' i i j = (pullbackSymmetry _ _).hom := by
  have eq₁ := D.t_fac i i j
  have eq₂ := (IsIso.eq_comp_inv (D.f i i)).mpr (@pullback.condition _ _ _ _ _ _ (D.f i j) _)
  rw [D.t_id, Category.comp_id, eq₂] at eq₁
  have eq₃ := (IsIso.eq_comp_inv (D.f i i)).mp eq₁
  rw [Category.assoc, ← pullback.condition, ← Category.assoc] at eq₃
  exact
    Mono.right_cancellation _ _
      ((Mono.right_cancellation _ _ eq₃).trans (pullbackSymmetry_hom_comp_fst _ _).symm)

theorem t'_jii (i j : D.J) : D.t' j i i = pullback.fst ≫ D.t j i ≫ inv pullback.snd := by
  rw [← Category.assoc, ← D.t_fac]
  simp

theorem t'_iji (i j : D.J) : D.t' i j i = pullback.fst ≫ D.t i j ≫ inv pullback.snd := by
  rw [← Category.assoc, ← D.t_fac]
  simp

@[reassoc, elementwise (attr := simp)]
theorem t_inv (i j : D.J) : D.t i j ≫ D.t j i = 𝟙 _ := by
  by_cases h : i = j
  · subst h
    simp
  · exact D.t_inv' _ _ h

theorem t'_inv (i j k : D.J) :
    D.t' i j k ≫ (pullbackSymmetry _ _).hom ≫ D.t' j i k ≫ (pullbackSymmetry _ _).hom = 𝟙 _ := by
  rw [← cancel_mono (pullback.fst : pullback (D.f i j) (D.f i k) ⟶ _)]
  simp [t_fac, t_fac_assoc]

instance t_isIso (i j : D.J) : IsIso (D.t i j) :=
  ⟨⟨D.t j i, D.t_inv _ _, D.t_inv _ _⟩⟩

-- instance t'_isIso (i j k : D.J) : IsIso (D.t' i j k) :=
--   ⟨⟨D.t' j k i ≫ D.t' k i j, D.cocycle _ _ _, by simpa using D.cocycle _ _ _⟩⟩

def glueData (D : GlueData' C) : GlueData C where
  __ := D
  cocycle i j k := by
    dsimp
    by_cases hij : i = j
    · subst hij
      rw [D.t'_iij, D.t'_jii, D.t'_iji]
      ext
      · simp [fst_eq_snd_of_mono_eq, t_inv_assoc]
      · simp [fst_eq_snd_of_mono_eq]
    by_cases hjk : j = k
    · subst hjk
      rw [D.t'_iij, D.t'_jii, D.t'_iji]
      ext
      · simp [fst_eq_snd_of_mono_eq, t_inv_assoc]
      · simp [fst_eq_snd_of_mono_eq]
    by_cases hki : k = i
    · subst hki
      rw [D.t'_iij, D.t'_jii, D.t'_iji]
      ext
      · simp [fst_eq_snd_of_mono_eq, t_inv_assoc]
      · rw [← cancel_mono (D.f k k)]
        simp [fst_eq_snd_of_mono_eq, t_inv_assoc, pullback.condition]
    exact D.cocycle i j k hij hjk hki

end GlueData'
```

**Comment by alreadydone** [comment]
GlueData' is indeed useful; my [GlueData.mk₂](https://github.com/leanprover-community/mathlib4/pull/14167/files#diff-84f8c7bdded56b516d33e74834faf603f2a1cc1c213351b2f10f72a851b94cfcR78-R96) is a baby version of it. But maybe we can add the `i ≠ j` conditions to `V, f, f_mono, f_hasPullback, t, t', t_fac` and get rid of `f_id` and `t_id`?

**Comment by jcommelin** [comment]
Hmmm, then the data becomes a dependent function... and we would get even more `if then else`s everywhere. I suppose it could work...

At least, I think we can consider splitting the data into a structure (maybe this can be called `GlueData`?) and then different kinds of ways to check the axioms can be put on top of that.

**Comment by erdOne** [comment]
I'll try out the approach Johan mentioned. `GlueData.mk₂` is definitely useful, but I don't think we should introduce `if then else` everywhere.

**Comment by erdOne** [comment]
After some more thought, I think `GlueData'` is only useful when `i = j` and `i =/= j` need different approaches, so maybe adding `i ≠ j` in the data makes sense as well.

**Comment by adamtopaz** [comment]
There is quite a lot going on in this PR. I see at least four contributions:
1. `GlueData'`
2. Disjoint unions of schemes.
3. Disjoint unions of prime spectra.
4. General API about pullbacks/pushouts/strict initials.

It would be much easier to review this important work if you could break up this PR into smaller pieces.

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
