### PR TITLE
[Merged by Bors] - feat: port CategoryTheory.Abelian.Basic

### PR DESCRIPTION
**Pull request by mattrobball**
---

- [x] depends on: #2764
- [x] depends on: #2760
[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2764
* leanprover-community/mathlib4#2760
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2764~~
* ~~leanprover-community/mathlib4#2760~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by mattrobball** [comment]
The problem with `simpNF` appears to be [Lean4#2055](https://github.com/leanprover/lean4/issues/2055)

**Comment by semorrison** [comment]
Bumped to master in case Gabriel's changes in nightly-2023-03-17 help.

**Comment by mattrobball** [comment]
Thanks. When I bumped on my own machine, it didn't but 🤞

**Comment by semorrison** [comment]
Here's the snippet that shows that this really is https://github.com/leanprover/lean4/issues/2055

```
import Mathlib

open CategoryTheory Limits

variable (C : Type _) [Category C] [Preadditive C]

set_option maxHeartbeats 20000
set_option trace.Meta.synthInstance true
-- set_option trace.Meta.isDefEq true
-- set_option pp.all true
set_option profiler true

#synth HasZeroObject C
```

**Comment by semorrison** [comment]
Okay, we can just remove the troublesome instance. I've made a mathlib3 PR that verifies that removing the instance doesn't cause trouble downstream. I've left a porting note (and added one on the mathlib3 side), so hopefully when https://github.com/leanprover/lean4/issues/2055 is resolved we will remember to clean this up again.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
