### PR TITLE
[Merged by Bors] - feat: port Data.Finset.PImage

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
Currently blocked on missing port of `pfun`

**Comment by mo271** [comment]
There were some fixes with decidable necessary, perhaps not exactly how it was done now

**Comment by mo271** [comment]
Currently the formulation of the statement `pimage_eq_image_filter` is still broken, any hints welcome!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
