### PR TITLE
chore(Topology/PseudoMetric): split file

### PR DESCRIPTION
**Pull request by kim-em**

### CODE REVIEW

**Comment by grunweg** [comment]
Let me cross-reference #13977 which tries the same. (I'll be happy to review either, but submitting my PhD thesis takes priority -> I may take about a week to get to this.)

**Comment by YaelDillies** [comment]
@adomani, a clearly inaccurate declaration diff here!

**Comment by adomani** [comment]
I think that the output that you are seeing comes from this:
```
$ git diff --unified=0 master...HEAD | grep "structure. -/"
-structure. -/
-structure. -/
+structure. -/
+structure. -/
```
so, not ideal, but also not worrisome!

**Comment by adomani** [comment]
I confirm: if you change
```
  awk -v regex="^[+-]${begs}" 'BEGIN{ paired=0; added=0; removed=0 }
```
to
```
  awk -v regex="^[+-]${begs} " 'BEGIN{ paired=0; added=0; removed=0 }
```
in [no_lost_declarations](https://github.com/leanprover-community/mathlib4/blob/1616f72b4a8d0325ff08ebe4b4a9ccd30b90d0ee/scripts/no_lost_declarations.sh#L23), then here it reports no change.

**Comment by YaelDillies** [comment]
@adomani please tell me when you open a PR to fix the regex! 🙏

**Pull request closed without merging**
