### PR TITLE
feat(MeasureTheory/Function/StronglyMeasurable): coercions between measurability classes

### PR DESCRIPTION
**Pull request by igorkhavkine**
Adds coercions between measurability properties like (AE)Measurable and (AE)StronglyMeasurable, in the presence of necessary hypotheses.

---
A short Zulip discussion [here](https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/Vitali's.20convergence.20theorem/near/408276870). I don't know whether these coercions are would be encouraged by the "Mathlib way", but perhaps they're worth a discussion.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
Could you please try to drop explicit conversions in more places, then comment `!bench` to see how it affects compilation speed?

**Comment by urkud** [comment]
BTW, another possible coercion is `MeasurableSet s → NullMeasurableSet s μ`.

**Comment by igorkhavkine** [comment]
> Could you please try to drop explicit conversions in more places, then comment `!bench` to see how it affects compilation speed?

Forgive my ignorance. Where does the `!bench` directive go?

**Comment by urkud** [comment]
It compiles `Mathlib` and compares build times (more precisely, the number of instructions for each files) with the base commit. E.g., like here:
!bench

**Comment by urkud** [comment]
!bench

**Comment by igorkhavkine** [comment]
I've tried looking for places in Mathlib where these coercions could be used. I've had to look through a bunch of code that I have no idea about, and it wasn't easy to find obvious examples. I think doing this properly would take more time that I'd rather apply to other efforts. :-/ I'm not particularly attached to this PR, so I'm happy to just leave it here as an idea that may or may not come in useful someday.

**Comment by jcommelin** [comment]
@igorkhavkine Now that #9163 is merged, are you planning to continue working on this PR? If not, please feel free to close it.

**Comment by igorkhavkine** [comment]
I'm just going to close this PR. Probably should have done that way earlier. It was just an experimental idea. The code is available on Zulip if anyone becomes interested in this in the future.

**Pull request closed without merging**
