### PR TITLE
[Merged by Bors] - chore(LinearAlgebra/TensorProduct): fix duplication

### PR DESCRIPTION
**Pull request by yuma-mizuno**
This was unintentionally made in [#16776](https://github.com/leanprover-community/mathlib4/pull/16776) by myself.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by mo271 — APPROVED** [review]

**Comment by mo271** [comment]
Do we do deprecation alias for those?

**Comment by yuma-mizuno** [comment]
> Do we do deprecation alias for those?

I have added.

**Review by eric-wieser — APPROVED** [review]
bors d+

If you wanted, you could deprecate the `*fold` names in favor of subscripts (the reverse of what you've done here) if you'd find them easier to discover. Of course, `by ext x y z` works fine anyway, so no one should really need these lemmas...

**Comment by yuma-mizuno** [comment]
>Of course, by ext x y z works fine anyway, so no one should really need these lemmas...

In my understanding, `ext x y z` only works in the local ext setting in this file. I'm not sure why the setting is like this.

**Comment by yuma-mizuno** [comment]
The subscript name was an unintentional product, but it might not be a bad name.

**Comment by eric-wieser** [comment]
> > Of course, by ext x y z works fine anyway, so no one should really need these lemmas...
> 
> In my understanding, `ext x y z` only works in the local ext setting in this file.

Yes this is true,

> I'm not sure why the setting is like this.

This was a decision made near the end of mathlib3, for performance. We could try revisiting it now that we have better lean 4 and benchmarking infrastructure.

**Pull request closed without merging**
