### PR TITLE
feat: add a script to check for PR title and labelling

### PR DESCRIPTION
**Pull request by grunweg**
The script checks most items from the commit convention, ensures that a feature PR has a topic/area label,
and errors if any two labels are contradictory.

Extracted from #16303. That PR will make this workflow run in CI.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Since the other PR has CI issues, let me extract the validation logic to a separate PR, which can hopefully land earlier.
@bryangingechen @joneugster Would one of you like to re-review? There are lots of tests now, which might speed that up.

**Comment by bryangingechen** [comment]
Just checking: Lean files in `scripts` aren't checked by CI, right?

**Comment by grunweg** [comment]
It depends: syntax linters run on every file importing them, but otherwise CI shouldn't touch them.
This script is not used or touched by CI until a workflow uses it (as in, e.g., the next PR).

**Comment by bryangingechen** [comment]
I think there are comments on #16303 which apply here too. Shall we just proceed there, or do you think people will be using this script much outside of CI?

**Comment by grunweg** [comment]
I think this script is mostly useful for CI (and only split out because it is long enough). Closing this PR and just discussing on the other PR is fine.

I'll address the review comments later this week, right now I'm somewhat busy.

**Comment by grunweg** [comment]
I have addressed all comments on #16303 instead: let me close this PR for now.

**Pull request closed without merging**
