### PR TITLE
[Merged by Bors] - feat port: Data.Int.Order.Basic

### PR DESCRIPTION
**Pull request by ChrisHughes24**
10b4e499f43088dd3bb7b5796184ad5216648ab1

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
I'm running into a lot of trouble with div/mod here - it seems like those changed behaviour in lean4.

**Comment by ChrisHughes24** [comment]
I remember the definition of mod changed. Probably just make a PR to Lean4 correcting the definition

**Comment by ChrisHughes24** [comment]
[Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Int.2EofNat.20and.20Nat.2ECast) discussion about some coercion issues here

**Comment by semorrison** [comment]
We may be able to proceed here by merging https://github.com/leanprover-community/mathlib4/pull/972 into this PR.

**Comment by semorrison** [comment]
And #973 will give us mathlib3 compatible `Div Int` and `Mod Int` instances.

**Comment by ChrisHughes24** [comment]
Most of this file is about `div` and `mod` and the lemma names clash with the different definition of `div` and `mod` in `Std`. Should we change the name of `Int.div` and the lemmas about it?

**Comment by digama0** [comment]
The std convention is to rename all the lemmas to use `ediv` instead of `div`, even though it is written with the `/` notation now. I think we should keep doing this until a PR to change the names goes through.

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
