### PR TITLE
[Merged by Bors] - feat(SetTheory/Cardinal/Basic): out_lift_equiv

### PR DESCRIPTION
**Pull request by YnirPaz**
Prove `out_lift_equiv`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by vihdzp — APPROVED** [review]

**Comment by vihdzp** [comment]
Thinking about loud, it'd be nice to introduce `Cardinal.toType` as an alias for `out`, as we did for `Ordinal.toType`.

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by YnirPaz** [comment]
> Thanks 🎉
> 
> bors merge

Sorry had to merge, should work now.

**Comment by jcommelin** [comment]
CI is still unhappy...

**Comment by YnirPaz** [comment]
> CI is still unhappy...

I think it just remembered the bors error from the previous commit, it built fine. Either way I merge again.

**Comment by YnirPaz** [comment]
> > CI is still unhappy...
> 
> I think it just remembered the bors error from the previous commit, it built fine. Either way I merged again.

@jcommelin

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
