### PR TITLE
[Merged by Bors] - chore(Data/List/Rotate): add `@[simp]` to `rotate_replicate`

### PR DESCRIPTION
**Pull request by s1m7u**
---

As per #7987 check that `@[simp]` for `rotate_replicate` compiles.

### CODE REVIEW

**Review by ericrbg — APPROVED** [review]
maintainer merge

**Comment by mattrobball** [comment]
bors merge

**Comment by urkud** [comment]
Let's fix description first.
bors r-

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
