### PR TITLE
[Merged by Bors] - perf(AlgebraicGeometry): Fix slow and bad proofs

### PR DESCRIPTION
**Pull request by erdOne**
Fixed `AlgebraicGeometry/AffineSchemes.lean`, `AlgebraicGeometry/Morphisms/QuasiSeparated.lean` and  `AlgebraicGeometry/Morphisms/RingHomProperties.lean`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by digama0** [comment]
Note: I have pushed an update to the lean toolchain because this PR was on a [buggy version](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Potential.20data.20loss.20from.20.60lake.20clean.60.20with.204.2E2.2E0-rc2.2F3/near/397875701) of the toolchain. **WARNING**: checking out old commits of this PR using v4.2.0-rc2 or v4.2.0-rc3 can cause `lake clean` to delete your mathlib folder! If you need to do so, make sure to delete `lakefile.olean` manually before running any `lake` commands.

**Comment by erdOne** [comment]
!bench

**Comment by collares** [comment]
@erdOne Feel free to revert my hacky 42a9855 as part of this (much better) PR. I didn't know of this PR before.

**Comment by collares** [comment]
> @erdOne This seems like an improvement! Would you mind fixing the build please?

@jcommelin The build failure was just a "no space left on device error". I triggered a rebuild and it was green.

**Comment by erdOne** [comment]
@collares Thanks for the fix!

**Comment by erdOne** [comment]
!bench

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
