### PR TITLE
[Merged by Bors] - chore: bump lean4checker to v4.13.0-rc3

### PR DESCRIPTION
**Pull request by adomani**
I think that there might be further issues with `lake build`, but this change seems at least needed.

I am hoping that #17486 tests this.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
@kim-em @jcommelin @bryangingechen

Pinging you, in case you are interested!  :smile:

**Comment by adomani** [comment]
Could the issue also be a missing `v4.13.0-rc3` tag?

**Review by grunweg — COMMENTED** [review]
Seems innocuous and necessary. Thanks!
maintainer merge

**Comment by bryangingechen** [comment]
The tag seems to be missing indeed per the failure in #17486 so I'm hesitant to merge this before that is done.

**Comment by bryangingechen** [comment]
The [v4.13.0-rc3 tag now exists](https://github.com/leanprover/lean4checker/releases/tag/v4.13.0-rc3). I'm not sure if we're still waiting on some fix but in case we're not:
bors d+

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
