### PR TITLE
chore: remove duplicate HashSet.insertMany

### PR DESCRIPTION
**Pull request by kim-em**

### CODE REVIEW

**Comment by digama0** [comment]
I think we should not do this kind of thing. ForMathlib/Std/Core style directories should only ever be used within a given package; if they are actually being used cross package then they should just be upstreamed, or copied.

**Comment by semorrison** [comment]
Okay, I'll namespace these for now instead.

**Comment by semorrison** [comment]
Will this be okay for now? This is causing build errors on the `category_theory` branch, which is experimenting with `aesop`.

**Comment by digama0** [comment]
If you PR this to std it will be an easy merge, although I suppose it really should go in `Lean.HashMap` (I think it will still be an easy merge in that case). I think I see the issue now, there is an import redefinition error because we're trying to add to a type we don't own, and this is why the practice is not a very good idea in general.

**Comment by semorrison** [comment]
Okay, https://github.com/leanprover/lean4/pull/1889.

**Comment by semorrison** [comment]
Hmm, I don't recall clicking close or open for that last pair of status changes. I wonder if a bot has run amok. In any case:
* std4: https://github.com/leanprover/std4/pull/39
* aesop: https://github.com/JLimperg/aesop/pull/30

**Comment by semorrison** [comment]
This has landed in core, so this change will be taken care of in the next bump PR.

**Pull request closed without merging**
