### PR TITLE
[Merged by Bors] - style(Mathlib/Tactic/*): rename wrongly capitalized filenames

### PR DESCRIPTION
**Pull request by Komyyy**
`Mathlib.Tactic.Congrm`
→ `Mathlib.Tactic.CongrM`

`Mathlib.Tactic.Existsi`
→ `Mathlib.Tactic.ExistsI`

`Mathlib.Tactic.Widget.Congrm`
→ `Mathlib.Tactic.Widget.CongrM`

`Mathlib.Tactic.Widget.Gcongr`
→ `Mathlib.Tactic.Widget.GCongr`

Also, we rename the namespaces and subroutines in these files.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
I don't think we want to make this change without renaming the namespaces and subroutines in the code as well?
And I'd argue `sudo` is either `SUDo` for substitute user do or `Sudo` as a single word.

**Comment by Komyyy** [comment]
@erdOne
OK, I'll rename the namespaces and subroutines.
However, [sudo](https://en.m.wikipedia.org/wiki/Sudo) means "superuser do" so `SuDo` is correct.

**Comment by Komyyy** [comment]
@erdOne
I'm sorry to misunderstood [the naming convention](https://github.com/leanprover-community/mathlib4/wiki/Porting-wiki#naming-convention): **Acronyms** are written upper-/lowercase as a group, not all **abbreviation**.
So these names are capitalized correctly:
`Mathlib.Tactic.Linarith.*`
`Mathlib.Tactic.SudoSetOption`
I revert these changes.

**Comment by Komyyy** [comment]
@adomani
The main purpose of thgs PR is fixing filenames in `Mathlib.Tactic`, so renaming `test/Existsi.lean` is extra.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
