### PR TITLE
[Merged by Bors] - feat: Port Data.QPF.Multivariate.Constructions.Sigma

### PR DESCRIPTION
**Pull request by casavaca**
---

Help wanted:

```lean
def Sigma (v : TypeVec.{u} n) : Type u :=
  -- Porting note: should be Σα : A, F α v. but failed because somehow
  -- Σ bind to MvQPF.Sigma, not _root_.Sigma
  _root_.Sigma fun α : A => F α v
```

- [x] depends on: #2223 
[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2223
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by alexkeizer** [comment]
@casavaca I noticed you're working on a bunch of QPF related files. Are you aware of my previous work at https://github.com/alexkeizer/qpf4? That repo contains an older, manual port I did, so using that might help you reduce duplicate effort

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2223~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
