### PR TITLE
[Merged by Bors] - chore: Do not import algebra in `Data.Vector`

### PR DESCRIPTION
**Pull request by YaelDillies**
... and rename `Data.Vector` to `Data.Vector.Defs`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Looks reasonable to me; thanks!
maintainer merge

**Comment by jcommelin** [comment]
CI is unhappy, but otherwise this looks good.

bors d+

**Comment by YaelDillies** [comment]
bors merge

**Comment by YaelDillies** [comment]
bors merge

**Pull request closed without merging**
