### PR TITLE
chore: adapt to new simp default (`decide := false`)

### PR DESCRIPTION
**Pull request by collares**
Mostly smooth so far, but I think `norm_num` is less powerful for modulo and divisibility operations on integers. `(config := {decide := true})`  was added only as a last resort.

---

There are two test failures left: `test/ComputeDegree.lean` fails because `ComputeDegree` is less powerful now because its simp calls (either direct or indirect via `norm_num`) don't do decidability and can't simplify stuff like `6 ≤ WithBot.unbot' 0 48`. Similarly, `test/norm_num_ext.lean` reveals that `norm_num` now fails to simplify `List.sum` and `Multiset.sum` appropriately. Help is very much appreciated!

- [x] depends on: leanprover/lean4#2722
- [x] depends on: leanprover/std4#312
- [x] depends on: leanprover-community/aesop#78

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by collares** [comment]
!bench

**Comment by collares** [comment]
It would have been nice to have some speedups here, but that was not the main point: The real speedups happen when `simp` tries to decide something and fails after a long time. Those happen in development (see, e.g., https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Regression.20in.20simp) but don´t affect mathlib compilation speed.

**Comment by semorrison** [comment]
0.4% reduction in instruction count is nothing to sneeze at!

**Comment by semorrison** [comment]
bors merge

**Comment by collares** [comment]
```
 Error: ./././Mathlib/Algebra/GroupWithZero/Basic.lean:162:14: error: ambiguous, possible interpretations 
  _root_.or_iff_not_imp_left.mpr fun ha ↦ mul_left_cancel₀ ha (ab0.trans (mul_zero a✝).symm) : a✝ = 0 ∨ b✝ = 0
  
  Classical.or_iff_not_imp_left.mpr fun ha ↦ mul_left_cancel₀ ha (ab0.trans (mul_zero a✝).symm) : a✝ = 0 ∨ b✝ = 0
```

**Comment by semorrison** [comment]
bors merge

**Pull request merged**
