### PR TITLE
[Merged by Bors] - chore: split CategoryTheory.FinCategory

### PR DESCRIPTION
**Pull request by kim-em**
Minor clean up of imports, getting ready to minimize the heartbeats variation observed/reduced in #9732.

This has the effect of slightly (although not enough) delaying the import of `positivity` (which in turn imports the kitchen sink) into the category theory development.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Comment by sgouezel** [comment]
bors r-
Can you merge master?
bors d+

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
lake build

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
