### PR TITLE
[Merged by Bors] - feat: In characteristic p, `Nat.cast` is injective on `Iio p`

### PR DESCRIPTION
**Pull request by YaelDillies**
Add `CharP.natCast_injOn_Iio`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
Since you move code around and add new lemmas in one PR, could you please list new lemma names in the commit message?

**Comment by YaelDillies** [comment]
Done

**Comment by YaelDillies** [comment]
Reduced the diff

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
