### PR TITLE
[Merged by Bors] - chore: remove some double spaces

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
There many occurrences of two spaces after a period, entire sections are written in this style. I'm not sure if we want to make that more consistent, `\.  [A-Z]` (with 2 spaces) has 523 matches, while `\. [A-Z]` (which 1 space) has 16529 matches, so clearly this is more common.

**Comment by alexjbest** [comment]
Is this awaiting-review?

**Comment by mo271** [comment]
Yes! awaiting review now; I added a few more.

**Comment by sgouezel** [comment]
bors r+
Thanks!

**Pull request closed without merging**
