### PR TITLE
[Merged by Bors] - chore(AlgebraicTopology): create Quasicategory directory

### PR DESCRIPTION
**Pull request by gio256**
Moves:
- AlgebraicTopology.SimplicialSet.Quasicategory -> AlgebraicTopology.Quasicategory.Basic

Co-Authored-By: [Johan Commelin](https://github.com/jcommelin)

---
I did some grepping to try to update any references to these files in comments, and also deleted one `Todo` closed by #19270.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by joelriou** [comment]
I think it is better to keep `Nerve` as `SimplicialSet.Nerve` (there is nothing about quasi-categories in this file). Similarly, if someone formalizes Quillen's Theorems A/B, I would not see any reason to put it in the `QuasiCategory` folder (unless the proof uses quasi-categories!?).
In order to have slightly shorter names, I think the `Quasicategory` folder could rather be as `AlgebraicTopology.Quasicategory` rather than `AlgebraicTopology.SimplicialSet.Quasicategory`.

**Comment by joelriou** [comment]
Also, `StrictSegal` should stay in `SimplicialSet`.

**Comment by joelriou** [comment]
Then, the only change should be that `AlgebraicTopology.SimplicialSet.Quasicategory` be moved to `AlgebraicTopology.SimplicialSet.Quasicategory.Basic`.
The proof that nerves of categories are quasi-categories should then be put in a new file ``AlgebraicTopology.SimplicialSet.Quasicategory.Nerve` (while `SimplicialSet.Nerve` would keep only the most basic properties that are not related to quasi-categories).

**Comment by gio256** [comment]
@joelriou sounds good on all fronts. I will plan to make all of these changes in this PR, but let me know if you would prefer e.g. moving the proof that nerves are quasicategories to be broken up into a separate PR.

**Comment by gio256** [comment]
On second thought, that's going to be more chaotic than I thought. If it's alright with @joelriou, I will break out a separate PR adding `AlgebraicTopology/Quasicategory/StrictSegal.lean` and `AlgebraicTopology/Quasicategory/Nerve.lean` and moving the respective proofs into these files.

**Comment by joelriou** [comment]
Thanks!

bors merge

**Comment by gio256** [comment]
@joelriou apologies for adding to the confusion, I must have read your comments before you deleted them.

I've opened #19472, which I believe takes the additional steps you mentioned, though possibly adding `AlgebraicTopology.Quasicategory.Nerve` is a bit premature, as there is only the one `Quasicategory` instance in there right now.

**Pull request closed without merging**
