### PR TITLE
[Merged by Bors] - chore: classify `lemma was not necessary` porting notes (category theory)

### PR DESCRIPTION
**Pull request by pitmonticone**
Classifies by adding issue number (#10688) to porting notes claiming `ext/simp lemma was not necessary`.

### CODE REVIEW

**Comment by joelriou** [comment]
As these are `simp` or `ext` lemmas, I would think that it could be classified together with "added to ease automation" https://github.com/leanprover-community/mathlib4/issues/10688 (cf. PR #10689 )

**Comment by pitmonticone** [comment]
Hi @joelriou, thank you for your review. 

Could you please discuss your proposal [here](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Addressing.20porting.20notes.3F)?

**Comment by pitmonticone** [comment]
@joelriou Done.

**Comment by joelriou** [comment]
Thanks!

bors merge

**Comment by joelriou** [comment]
Retrying...

bors merge

**Pull request closed without merging**
