### PR TITLE
[Merged by Bors] - chore: rename `halfspace` to `halfSpace`

### PR DESCRIPTION
**Pull request by winstonyin**
Rename `halfspace` to `halfSpace`, treating `half` and `space` as two words. This conforms to the existing pattern in
* `EuclideanHalfSpace`
* `UpperHalfPlane`
* `HalfPlane.lean`

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Thanks for the PR! This does what it should and does that well.
maintainer merge

I don't have a strong preference between "halfspace" and "halfSpace". I care that these are used consistently. Currently, mathlib mostly prefers the latter, so using that seems like a reasonable choice.

**Comment by j-loreaux** [comment]
Is there a Zulip thread about this? It seems like that's in order for a decision like this.

**Comment by winstonyin** [comment]
@j-loreaux There isn't a Zulip chat yet, but I can create one if you think this is a non-trivial rename. There's already `EuclideanHalfSpace` and `HalfPlane`, so I think it make sense to conform `halfspace` to that pattern.

**Comment by j-loreaux** [comment]
Please add the other examples (e.g., UpperHalfPlane, etc.) to the PR description. Since this is the only odd one out, it's fine to go without Zulip.

**Comment by j-loreaux** [comment]
bors d+

**Comment by winstonyin** [comment]
bors d+

**Pull request closed without merging**
