### PR TITLE
[Merged by Bors] - feat: add some `pp_extended_field_notation`s

### PR DESCRIPTION
**Pull request by kbuzzard**
Add some `pp_extended_field_notation`, for opt-in cases with additional arguments.

---
Original PR description

These unexpanders make the Lean 4 prettyprinter behave more like Lean 3. You might think `trans e` is barely any different to `e.trans`, but the issue is that if the relevant namespaces aren't open then without the unexpander it's the more ungainly `Equiv.trans e`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

This is not any attempt to be exhaustive -- these were just the missing unexpanders which I ran into when trying to debug a failing `simp` in the port; it was just much easier for debugging purposes to make the lean 3 and lean 4 terms look as similar as possible.

### CODE REVIEW

**Comment by semorrison** [comment]
LGTM. I added `awaiting-review` for you, hopefully that is correct.

**Comment by jcommelin** [comment]
I love the effect of this PR!

But I wish Kevin wouldn't have to write 5 lines of repetitive code after every defn.
Could this be golfed to `@[derive unexpander] def FooBar` using some meta-programming?

**Comment by kmill** [comment]
#3811 gives a possible metaprogramming solution that can replace these with one liners

**Comment by semorrison** [comment]
I'll mark this `wontfix` for now, as #3811 is a more complete solution. @kbuzzard, perhaps you can close this once #3811 is merged.

**Comment by kmill** [comment]
Now that we have `pp_extended_field_notation` in mathlib, I went ahead and updated this PR and removed `wontfix`, since the dot notation for these things is opt-in. I also added in a couple more missing ones. I hope that's ok @kbuzzard and @semorrison.

I didn't update the PR summary.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
