### PR TITLE
[Merged by Bors] - fix: makefile missing semicolon, silence tests

### PR DESCRIPTION
**Pull request by kmill**
**Note:** *if you have a branch failing CI with "Error: Test output is not empty" then merge the `master` branch.*

Silences remaining tests. (The change that required silent tests seems to have passed its own test through bors, but in CI these tests remain noisy.)

Co-authored-by: Ruben Van de Velde <ruben.vandevelde+github@gmail.com>

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
The tests passed, it seems: thanks!

maintainer merge

**Comment by adomani** [comment]
maintainer merge

**Comment by adomani** [comment]
maintainer merge

**Comment by adomani** [comment]
maintainer merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
