### PR TITLE
[Merged by Bors] - chore(workflows): don't add or remove the 'awaiting-review' label

### PR DESCRIPTION
**Pull request by grunweg**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Overlaps with #14605: this PR just performs the minimal change (don't label awaiting-review).
CC @semorrison @jcommelin

**Comment by semorrison** [comment]
Closed in favour of https://github.com/leanprover-community/mathlib4/pull/14605

**Comment by grunweg** [comment]
Sure, let's have the other PR go in first. Note that this PR also removes a few references the other PR doesn't touch. Should those rather stay?

**Comment by fpvandoorn** [comment]
Yes, that seems useful. Please merge master.

**Comment by grunweg** [comment]
Merged master and update the PR description.

**Comment by fpvandoorn** [comment]
LGTM, but maybe @semorrison also wants to take a quick look.

**Comment by urkud** [comment]
LGTM

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
