### PR TITLE
[Merged by Bors] - ci: move workflow check into actionlint, add reviewdog suggestions

### PR DESCRIPTION
**Pull request by bryangingechen**
There was a step in our main CI workflow that checks that `bors.yml`, `build.yml` and `build_fork.yml` generated properly from the source in `build.in.yml`. However, this check is only necessary for the (very rare) PRs which touch files in `.github/`. For that reason, I've moved the check into the actionlint workflow, which has a `paths` filter restricting to PRs touching those files.

While looking at this, I also realized that we can get reviewdog to automatically suggest fixes, so I added some steps to enable it for both actionlint and the workflow check.

Finally, to simplify things, the workflow now only runs for `pull_request` events.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

One question: do we need these checks to run on `push` to `master`? According to `bors.toml`, these checks aren't required to pass for `bors` to merge things into `master` anyways. If we don't need it then I can delete quite a bit of code from `actionlint.yml`.

### CODE REVIEW

**Comment by bryangingechen** [comment]
See https://github.com/bryangingechen/mathlib4/pull/13 for what the suggestions from reviewdog look like. Note that these suggestions are not integrated with the `bot fix style` command because making changes to workflow files requires more permissions than we currently give that bot.

**Comment by adomani** [comment]
I really like the idea of outsourcing the workflow check to actionlint!

You are way more knowledgeable of CI, so it feels a little weird to

maintainer merge

but this looks great, thanks!

**Comment by bryangingechen** [comment]
Let me just ping @semorrison to see if they have an opinion on my question about whether we need to run these checks on pushes to `master`. (My preference would be to have this run only on pull_request events for simplicity.)

**Comment by semorrison** [comment]
@bryangingechen, I think it's fine if you change this to only run on `pull_request`.

bors d+

**Pull request closed without merging**
