### PR TITLE
[Merged by Bors] - feat: port MeasureTheory.Constructions.BorelSpace.Basic

### PR DESCRIPTION
**Pull request by Komyyy**
---

- [x] depends on: #4038
- [x] depends on: #4100

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Komyyy** [comment]
I will get busy today.

**Comment by Komyyy** [comment]
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/borelize.20tactic.20!4.234018

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4038
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4038~~
* ~~leanprover-community/mathlib4#4100~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
