### PR TITLE
[Merged by Bors] - refactor: Delete `Algebra.GroupPower.Lemmas` 

### PR DESCRIPTION
**Pull request by YaelDillies**
`Algebra.GroupPower.Lemmas` used to be a big bag of lemmas that made it there on the criterion that they needed "more imports". This was completely untrue, as all lemmas could be moved to earlier files in PRs:
- #9440
- #9442
- #9443
- #9455
- #9456
- #9457
- #9459
- #9461
- #9463
- #9466
- #9501
- #9502
- #9503
- #9505
- #9551
- #9553
- #9720
- #9739
- #9740
- #9805
- #9806
- and this one

There are several reasons for this:
* Necessary lemmas have been moved to earlier files since lemmas were dumped in `Algebra.GroupPower.Lemmas`
* In the Lean 3 → Lean 4 transition, Std acquired basic `Int` and `Nat` lemmas which let us shortcircuit the part of the algebraic order hierarchy on which the corresponding general lemmas rest
* Some proofs were overpowered
* Some earlier files were tangled and I have untangled them

This PR finishes the job by moving the last few lemmas out of `Algebra.GroupPower.Lemmas`, which is therefore deleted.

---

- [x] depends on: #9440
- [x] depends on: #9442
- [x] depends on: #9443
- [x] depends on: #9455
- [x] depends on: #9456
- [x] depends on: #9457
- [x] depends on: #9459
- [x] depends on: #9461
- [x] depends on: #9463
- [x] depends on: #9466
- [x] depends on: #9501
- [x] depends on: #9502
- [x] depends on: #9503
- [x] depends on: #9505
- [x] depends on: #9551
- [x] depends on: #9553
- [x] depends on: #9720
- [x] depends on: #9739
- [x] depends on: #9740
- [x] depends on: #9805
- [x] depends on: #9806

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ericrbg** [comment]
Can you put some comments / split up commits to make this reviewable when it is done? What is the motivation?

**Comment by PatrickMassot** [comment]
I guess this PR requires a huge changelog in the commit message.

**Comment by YaelDillies** [comment]
Yes, sorry. I can't do anything more before overmorrow, so I've put the PR out to have a big scary diff to point people to when they want to add lemmas and for @alexjbest to try out Leaff.

I will split off PRs and write some prose in the description in due time.

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
