### PR TITLE
[Merged by Bors] - feat: add lemma List.getD_map

### PR DESCRIPTION
**Pull request by BoltonBailey**
Adds a lemma, analogous to [Option.getD_map](https://leanprover-community.github.io/mathlib4_docs/Std/Data/Option/Lemmas.html#Option.getD_map), but for `List`.

Also fixes a few nearby lemmas to use `induction`/`cases` instead of `induction'`/`cases'`

~~Co-authored-by: GitHub Copilot~~

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by kim-em — COMMENTED** [review]
It would be nice if new content used the structured syntax for induction and cases.

**Comment by BoltonBailey** [comment]
> It would be nice if new content used the structured syntax for induction and cases.

Ok, fixed. I also fixed the nearby uses in the file for consistency.

**Comment by eric-wieser** [comment]
Please mention that in the PR description

**Comment by ocfnash** [comment]
Thanks!

bors merge

**Pull request closed without merging**
