### PR TITLE
[Merged by Bors] - feat: port RingTheory.DiscreteValuationRing.TFAE

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by Parcly-Taxel** [comment]
@jcommelin by the same logic as in #3469, shouldn't the filename here be `TFAE`?

**Comment by jcommelin** [comment]
@Parcly-Taxel yes, good catch! Thanks

**Pull request closed without merging**
