### PR TITLE
[Merged by Bors] - fix(Analysis/Normed/Group): make instance helpers reducible

### PR DESCRIPTION
**Pull request by eric-wieser**
[Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/defeq.20of.20.60NormedAddCommGroup.20.E2.84.82.60/near/422248635)

This slightly simplifies two downstream proofs, as a bonus.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
Thanks. Once it is green, please send it off. 

bors delegate+

**Comment by eric-wieser** [comment]
!bench

**Comment by j-loreaux** [comment]
I'm confused. I think all of these are marked `@[to_additive (attr := reducible)]`. Is there a reason that doesn't work and we should prefer `abbrev`?

**Comment by mattrobball** [comment]
I missed that some of them had `reducible` also. We should check that indeed these are indeed reducible as are the additive versions.

**Comment by mattrobball** [comment]
This doesn't solve the example from Zulip right? Either way, it is a principled change given the caveats in my previous comment.

**Comment by mattrobball** [comment]
Uh oh. Making a separate `AddGroupNorm.toNormedAddCommGroup`, tagging it with reducible, and deleting the `to_additive` on `GroupNorm.toNormedCommGroup` fixes the original example.

**Comment by mattrobball** [comment]
Oh ok. `to_additive` and `abbrev` don't get along. Using `to_additive (attr := reducible)` is ok also.

**Comment by mattrobball** [comment]
@eric-wieser can you change from `abbrev` to `to_additive (attr := reducible)` in the appropriate places. Ping me if you want me to look again or merge if you feel confident.

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
@j-loreaux and @alreadydone since you both have carefully looked over this once, would mind doing so again? I want to be sure I didn't miss any `def`'s constructing instances and that I didn't do something silly. 

If you know what the best way to fix the broken `simp` proof in Cauchy integrals too, that would be great!

**Comment by eric-wieser** [comment]
bors merge

**Pull request closed without merging**
