### PR TITLE
[Merged by Bors] - chore: remove temporary reviewdog fix

### PR DESCRIPTION
**Pull request by mo271**
- [x] depends on: https://github.com/reviewdog/action-suggester/pull/52

This reverts #12280 after the upstream fix
 https://github.com/reviewdog/reviewdog/issues/1696
has propagated to reviewdog/action-suggester@v1. This should happen when 
https://github.com/reviewdog/action-suggester/releases
has a release that uses [v0.17.4](https://github.com/reviewdog/reviewdog/releases/tag/v0.17.4) or higher.

When this happens, rebase this pull request and re-trigger to see that it doesn't fail with the 300 dummy files. Then remove the dummy files and merge this pull request.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
@semorrison 
This is now fixed upstream and works: https://github.com/leanprover-community/mathlib4/actions/runs/8828205814/job/24236745436
So we can merge this to remove the temporary fix.

**Comment by semorrison** [comment]
bors merge

**Comment by mo271** [comment]
@semorrison I think this was rejected because of a erroneous "blocked-by-other-PR" label?! Perhaps we can try again...

**Comment by Ruben-VandeVelde** [comment]
maintainer merge

**Pull request closed without merging**
