### PR TITLE
[Merged by Bors] - feat: port Analysis.NormedSpace.CompactOperator

### PR DESCRIPTION
**Pull request by loefflerd**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by loefflerd** [comment]
I got rid of all the failures except one (which unfortunately but doesn't seem to be solved by `etaExperiment`)

**Comment by loefflerd** [comment]
> I think it's worth flagging that the one remaining error disappears if #3809 gets merged!

Cool! That's some serious wizardry 🧙‍♂️

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3809
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3809~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ChrisHughes24** [comment]
#3809 was not merged in the end and #3840 was merged instead so this PR needs sorting out.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
