### PR TITLE
[Merged by Bors] - chore(*): drop unneeded imports of OmegaCompletePartialOrder

### PR DESCRIPTION
**Pull request by urkud**
Linter doesn't catch them,
because files that import it use instances from this file,
but there are other paths in many cases.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Command-Master — APPROVED** [review]
Thanks! lgtm, as long as those alternate paths aren't less efficient to find

**Comment by Command-Master** [comment]
!bench

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
