### PR TITLE
[Merged by Bors] - chore: add `induction_eliminator, cases_eliminator` to `WithTop` etc

### PR DESCRIPTION
**Pull request by urkud**
Add `@[elab_as_elim, induction_eliminator, cases_eliminator]` to

- `WithOne.recOneCoe` (added `cases_eliminator`)
- `WithZero.recZeroCoe` (added `cases_eliminator`)
- `ENNReal.recTopCoe`
- `ENat.recTopCoe`
- `EReal.rec`

Mostly cherry-picked from #12605 

Co-authored-by: @negiizhao

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
As a side effect, `cases a` on `WithTop`/`WithBot` uses `top`/`bot` instead of `none`. I'll fix compile tomorrow.

**Comment by eric-wieser** [comment]
> ~As a side effect, `cases a` on `WithTop`/`WithBot` uses `top`/`bot` instead of `none`.~ Reverted this change to keep this PR small.

I think this is #13128?

**Comment by urkud** [comment]
> > ~As a side effect, `cases a` on `WithTop`/`WithBot` uses `top`/`bot` instead of `none`.~ Reverted this change to keep this PR small.
> 
> I think this is #13128?

Indeed, you're right! Thank you! There are too many open PRs at the moment, hard to keep track...

**Review by eric-wieser — APPROVED** [review]
bors merge

Looking again this doesn't overlap with #13128 after all.

**Pull request closed without merging**
