### PR TITLE
[Merged by Bors] - chore(LinearAlgebra/BilinearForm): Add missing deprecated dates

### PR DESCRIPTION
**Pull request by mans0954**
Adds dates to results deprecated in #12132 and #12078.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
I know; I'm eagerly awaiting the upgrade :-) Sure, waiting is fine with me!

**Comment by grunweg** [comment]
Except for the date issue, this PR looks good to me.

**Comment by grunweg** [comment]
With the Lean upgrade just landed, this PR should be ready to be updated!

**Comment by mans0954** [comment]
@grunweg how's that?

**Review by grunweg — APPROVED** [review]
Looks good to me; thanks for following up on your PRs!

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

Thanks!

**Pull request closed without merging**
