### PR TITLE
[Merged by Bors] - chore(Data/List/Enum): move from `Basic`

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — APPROVED** [review]
I'm not sure if this qualifies as "easy", given Github's interface - I checked locally that this is purely code motion and import changes. Looks good to me.
Thank you for doing this!

**Comment by urkud** [comment]
OK, removed `easy`.

**Review by eric-wieser — APPROVED** [review]
bors merge

I'll take @grunweg's word for it that this is a move with no other changes

**Comment by urkud** [comment]
Let me fix the build
bors r-

**Comment by grunweg** [comment]
@eric-wieser If I see correctly, this is off the bors queue. Can you approve again, if you agree with the changes?

**Pull request closed without merging**
