### PR TITLE
[Merged by Bors] - chore: move totallyBounded_Ixx lemmas up a bit

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
!bench

**Comment by Ruben-VandeVelde** [comment]
This removes `Mathlib.Topology.MetricSpace.PseudoMetric` from the longest pole - making it consist of more files but fewer (cumulative) instructions.
```diff
 file                                                           | instructions | (cumulative) | parallelism
 -------------------------------------------------------------- | ------------ | ------------ | -----------
-Mathlib.Analysis.Normed.Group.Basic                            |       101660 |      1765583 | x6.58
-Mathlib.Topology.MetricSpace.IsometricSMul                     |        30950 |      1663922 | x6.25
-Mathlib.Topology.MetricSpace.Isometry                          |        13637 |      1632971 | x5.17
-Mathlib.Topology.MetricSpace.Antilipschitz                     |         8227 |      1619334 | x5.21
-Mathlib.Topology.MetricSpace.Bounded                           |        13839 |      1611106 | x5.21
-Mathlib.Topology.MetricSpace.Cauchy                            |         6656 |      1597267 | x5.24
-Mathlib.Topology.MetricSpace.PseudoMetric                      |        65176 |      1590611 | x5.26
-Mathlib.Topology.Algebra.Order.Compact                         |        27904 |      1525434 | x4.17
-Mathlib.Topology.Order.IntermediateValue                       |        51399 |      1497530 | x4.12
-Mathlib.Topology.Order.DenselyOrdered                          |        86087 |      1446130 | x4.22
+Mathlib.Analysis.Normed.Group.Basic                            |       101630 |      1699474 | x6.83
+Mathlib.Topology.Instances.Rat                                 |        12781 |      1597844 | x7.08
+Mathlib.Topology.Instances.Real                                |        13892 |      1585063 | x7.12
+Mathlib.Topology.Instances.Int                                 |         5091 |      1571170 | x5.40
+Mathlib.Topology.Instances.Discrete                            |         6816 |      1566079 | x5.38
+Mathlib.Topology.Metrizable.Uniformity                         |        13824 |      1559263 | x5.40
+Mathlib.Topology.Metrizable.Basic                              |         4903 |      1545438 | x5.43
+Mathlib.Topology.MetricSpace.Basic                             |         9673 |      1540534 | x5.44
+Mathlib.Topology.MetricSpace.ProperSpace                       |         5429 |      1530861 | x5.47
+Mathlib.Topology.Algebra.Order.Compact                         |        27904 |      1525431 | x4.17
+Mathlib.Topology.Order.IntermediateValue                       |        51399 |      1497527 | x4.12
+Mathlib.Topology.Order.DenselyOrdered                          |        86087 |      1446128 | x4.22
```

**Review by grunweg — COMMENTED** [review]
Sounds reasonable to me; thanks for doing this!
maintainer merge

**Comment by fpvandoorn** [comment]
bors merge

**Pull request closed without merging**
