### PR TITLE
[Merged by Bors] - doc(AlgebraicIndependent): remove outdated TODO and add new

### PR DESCRIPTION
**Pull request by alreadydone**
The TODO item was already completed as [IsTranscendenceBasis.isAlgebraic](https://leanprover-community.github.io/mathlib4_docs/Mathlib/RingTheory/AlgebraicIndependent.html#IsTranscendenceBasis.isAlgebraic). However, transcendence degree is nowhere to be found even though it appears in the tags.

---

cc @acmepjz 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alreadydone** [comment]
Apparently, the author @ChrisHughes24 of [mathlib3#9377](https://github.com/leanprover-community/mathlib/commit/1faf964e1857bfb011eab68e5af4f61505d2f76f) forgot to remove the TODO item.

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by alreadydone** [comment]
Since cache is back, let me try merge this again (added the label).

**Pull request closed without merging**
