### PR TITLE
[Merged by Bors] - feat: let `apply_fun` apply functions at LT and Ne hypotheses

### PR DESCRIPTION
**Pull request by alexjbest**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by kmill** [comment]
It'd be good to improve how elaboration of the function and of the `using` clause works, but getting `apply_fun` to work with LT and Ne hypotheses is an improvement too. Thanks.

I merged master for you (and adjusted the indentation a bit). Once CI passes, feel free to merge.

bors d+

**Comment by alexjbest** [comment]
Thanks again @kmill , I've been on vacation this week so let some of these prs lag a bit and really appreciate you fixing them. I'll try and think more about your comments shortly.

**Comment by kmill** [comment]
I just meant for some future work, and I wanted to write it down in case you wanted to think about it too. Some of the cases of `apply_fun` have more sophisticated elaboration routines to be able to propagate type information, and there's also a routine for trying to prove Injective that's not being used in this PR's code (that's fine). You could take a look at how the other Injective is elaborated, and we could try to make more uniform code.

I think the reason the type ascription's needed is that it's using `Tactic.elabTerm` instead of `Term.elabTerm`, but we can't just switch from one to the other without being sure to synthesize pending metavariables.

Anyway, this would all be for a future PR.

**Pull request closed without merging**
