### PR TITLE
[Merged by Bors] - chore: move style linters to the style namespace

### PR DESCRIPTION
**Pull request by grunweg**
Redone version of #15971.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by joneugster — APPROVED** [review]
You're missing a few and it's comforting to see that the Github action even tells you where.

Otherwise LGTM!

**Comment by grunweg** [comment]
Indeed - fixed now.

**Comment by grunweg** [comment]
This PR may incur a merge conflict with #15017.

**Comment by joneugster** [comment]
Thank you!

maintainer merge

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Pull request closed without merging**
