### PR TITLE
chore: disable new compiler for now

### PR DESCRIPTION
**Pull request by kim-em**
This was recently added as an option in Lean 4. It should reduce the size of oleans, and hopefully not otherwise have any practical effect.

When work on the new compiler resumes we can re-enable it or set up some other testing regime.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by digama0** [comment]
You will be interested to bump std to https://github.com/leanprover/std4/commit/176b4657e21ea6f5a1517c625ee97e89acad0126 so that you can enable the `disable_new_compiler` option in the lakefile.

**Comment by Kha** [comment]
> and hopefully not otherwise have any practical effect.

It *will* force downstream lakefiles to be changed accordingly, right? In particular, `lake new maths` will be wrong. We should probably measure the practical impact first.

**Comment by Kha** [comment]
!bench

**Comment by Kha** [comment]
Ah, I didn't notice the build failure. This is unlikely to succeed.

**Comment by semorrison** [comment]
> You will be interested to bump std to [leanprover/std4@176b465](https://github.com/leanprover/std4/commit/176b4657e21ea6f5a1517c625ee97e89acad0126) so that you can enable the `disable_new_compiler` option in the lakefile.

I am meant to use this as something like this?
```
require std from git "https://github.com/leanprover/std4" @ "main"
   with (Lean.NameMap.insert {} `disable_new_compiler "37")
```
(couldn't find nice syntax for constructing a `NameMap`, and the `String` value (here "37") seems to be irrelevant: Std4 is just checking `isSome`)

It doesn't have any effect on the build failures here.

**Comment by digama0** [comment]
yes, sorry for the implication that it would fix the bug, it is unrelated

**Comment by digama0** [comment]
Wait a minute, what is that `dummy_label_attr` doing there? I could have sworn I moved it out of the file, after it caused exactly this problem before. How did this ever work?

**Comment by digama0** [comment]
I've narrowed this down to nondeterminism in the order of hashmap iteration over the `[init]` declarations, see https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/initialization.20order.20fiasco/near/363247722 . I will push a separate fix to take the `dummy_label_attr` out of the file.

**Comment by collares** [comment]
!bench

**Comment by PatrickMassot** [comment]
@collares I don't think that benchmarking before removing builds error is very useful, it probably consumes computing resources for nothing.

**Comment by semorrison** [comment]
!bench

**Comment by semorrison** [comment]
A 5% reduction in olean size, and a 2% increase(?) in wall clock time. I think that's small enough not to worry.

**Comment by digama0** [comment]
I would suggest squashing and rebasing on current master, since most mathlib changes will confound the measurements here.

**Comment by semorrison** [comment]
!bench

**Comment by semorrison** [comment]
I think we're not going to bother proceeding with this, given the inconsequential change in size for the oleans.

**Comment by digama0** [comment]
I think there is still some sleuthing to be done on what exactly is in our oleans and why this didn't make as much of a difference as projected. I recall the oleans ~doubling in size when the new compiler was first enabled, so there might still be some remnants remaining, or something else could have changed in the meantime.

**Pull request closed without merging**
