### PR TITLE
[Merged by Bors] - feat: use rintro patterns for ext

### PR DESCRIPTION
**Pull request by gebner**

### CODE REVIEW

**Comment by gebner** [comment]
It's a bit disappointing that rcases patterns are not a superset of built-in patterns.

**Comment by digama0** [comment]
Are there places where it is actually useful to use builtin patterns instead of rcases patterns?

**Comment by gebner** [comment]
The two instances that I had to change here are merely annoying (and inconsistent with the usual pattern syntax), but it's easy to write `⟨x, y⟩` instead of `(x, y)`.  Other patterns are harder to replace: for example `{ re, .. }` or `mk x ..` have no corresponding rintro pattern at all.

**Comment by digama0** [comment]
actually `mk x ..` does, that would be `(x)`, you can just not name trailing arguments.

**Comment by gebner** [comment]
bors merge

**Pull request closed without merging**
