### PR TITLE
[Merged by Bors] - chore: split Mathlib.Topology.Algebra.UniformConvergence

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
This reduces the longest pole by two files.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
!bench

**Comment by Ruben-VandeVelde** [comment]
```diff
-Analyzing Mathlib at 965c7f81663aefc008aa7165ffa5e3ddca9b46d9
+Analyzing Mathlib at da25b0648041f8e44f0db7d1e6c5a3850fadef44
 file                                                           | instructions | (cumulative) | parallelism
 -------------------------------------------------------------- | ------------ | ------------ | -----------
-Mathlib.Analysis.NormedSpace.OperatorNorm.Basic                |       106202 |      2337365 | x7.62
-Mathlib.Analysis.LocallyConvex.WithSeminorms                   |       105728 |      2231162 | x7.82
-Mathlib.Topology.Algebra.Equicontinuity                        |         7224 |      2125434 | x7.28
-Mathlib.Topology.Algebra.UniformConvergence                    |        32758 |      2118210 | x7.30
+Mathlib.Analysis.NormedSpace.OperatorNorm.Basic                |       106201 |      2292635 | x7.77
+Mathlib.Analysis.LocallyConvex.WithSeminorms                   |       100980 |      2186433 | x7.97
 Mathlib.Analysis.LocallyConvex.Bounded                         |        40076 |      208545_ | x7.39
 Mathlib.Analysis.Seminorm                                      |       172595 |      204537_ | x7.30
```

**Comment by MichaelStollBayreuth** [comment]
```text
General information:
  build:                                               -2.0957 * 10⁹ (-0.00171%)

1 file got slower by at least 10⁹ instructions:
  Mathlib.Analysis.NormedSpace.PiTensorProduct.InjectiveSeminorm:
                                                       +3.7541 * 10⁹ (+1.28%)

No file got slower by at least 10%.

4 files got faster by at least 10⁹ instructions:
  Mathlib.Topology.Algebra.UniformConvergence:         -12.220 * 10⁹ (-37.3%)
  Mathlib.Analysis.LocallyConvex.WithSeminorms:        -4.7480 * 10⁹ (-4.49%)
  Mathlib.RepresentationTheory.GroupCohomology.Resolution:
                                                       -1.3676 * 10⁹ (-0.400%)
  Mathlib.Topology.Algebra.Equicontinuity:             -1.2507 * 10⁹ (-17.3%)

2 files got faster by at least 10%:
  Mathlib.Topology.Algebra.UniformConvergence:                        -37.3%
  Mathlib.Topology.Algebra.Equicontinuity:                            -17.3%
```

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
