### PR TITLE
[Merged by Bors] - chore(ContinuousLinearMapWOT): generalize and golf

### PR DESCRIPTION
**Pull request by ADedecker**
---

- [x] depends on: #17493 
- [x] depends on: #17319 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by dupuisf** [comment]
Very nice, thanks!  Are you planning to move the file out of `Normed` in a subsequent PR?

**Comment by ADedecker** [comment]
Ah, I didn't think about changing the files. Should I put it under `Analysis.LocallyConvex`? I'm unhappy with how much functional analysis ends up in `Topology` but I guess that's an option as well? Really I don't have an opinion.

**Comment by dupuisf** [comment]
`Analysis.LocallyConvex` seems like a logical place for it. I agree it should be in the `Analysis` top-level folder in any case.

**Comment by ADedecker** [comment]
I just moved the file, and realized I need to update the module docstring. I'll do that in a few hours.

**Comment by dupuisf** [comment]
Looks good, thanks!

bors r+

**Pull request closed without merging**
