### PR TITLE
[Merged by Bors] - feat: port FieldTheory.Laurent

### PR DESCRIPTION
**Pull request by urkud**
---

- [x] depends on: #4580

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4513
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by jcommelin** [comment]
Could this please be split into two pieces? One doing the fix, and the other the porting PR with a nice diff with mathport output?

**Comment by jcommelin** [comment]
Aah, I guess #4580 is doing the fix part.

**Comment by urkud** [comment]
I will rebase this PR on `master` once the fix is merged.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4580~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by urkud** [comment]
Rebased on `master`, waiting for CI

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
