### PR TITLE
[Merged by Bors] - feat: port RingTheory.DiscreteValuationRing.Basic

### PR DESCRIPTION
**Pull request by int-y1**
---

todo:

* [x] (optional) `theorem addVal_*`: these had type errors involving `Multiplicative PartENatᵒᵈ` and `PartENat`.
  i fixed these by adding `: PartENat` and `show PartENat from` to every theorem.
  find a more elegant approach
* [x] fix errors in `addVal_*`

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ChrisHughes24** [comment]
I fixed everything just by changing a `CoeFun` to a `FunLike`.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
