### PR TITLE
[Merged by Bors] - chore: import `Tactic.Positivity.Finset` in `Tactic.Positivity`

### PR DESCRIPTION
**Pull request by YaelDillies**
I keep on getting bitten by the missing import.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
I don't like the idea of `Data.Rat.Floor` depending on `Finset`s.

**Comment by j-loreaux** [comment]
This is a quite large change in the imports of several files, but it doesn't even appear that you are using them? Do you have a follow-up PR that justifies the inclusion of these new imports? I understand missing an import can be annoying, but it seems to me it would be better to add it locally on a per PR basis rather than invoking a large change like this.

**Comment by YaelDillies** [comment]
Sorry I am trying to reduce the imports back but I can hardky type currently. Andrew a,nd I will get to it in a minute

**Comment by YaelDillies** [comment]
What about now?

**Comment by kim-em** [comment]
bors merge

**Review by adomani — COMMENTED** [review]
Thanks!

Let's try this again

bors merge

**Comment by adomani** [comment]
This is a stress test for the new `bors x` mechanism.

bors r+

**Pull request closed without merging**
