### PR TITLE
[Merged by Bors] - chore: add missing spaces around = or :=

### PR DESCRIPTION
**Pull request by grunweg**
Follow mathlib style slightly better: "Use spaces on both sides of ":", ":=" or infix operators."

Automatically generated. Not exhaustive, as doing that everywhere has false positives with meta code.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
Great!

maintainer merge

**Comment by jcommelin** [comment]
bors d+

**Comment by grunweg** [comment]
Thanks for the really fast review!

**Pull request closed without merging**
