### PR TITLE
[Merged by Bors] - feat: port RingTheory.Ideal.QuotientOperations

### PR DESCRIPTION
**Pull request by LukasMias**
"timeouts at whnf"s that I do not know what to do with.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by j-loreaux** [comment]
@LukasMias in my ports of other files involving quotients I found that Lean 4 was significantly worse at unification. As a result, adding type ascriptions both sped up elaboration significantly as well as avoided whnf timeouts. For instance, in a statement of an equality `a = b`, Lean 4 could correctly deduce the type of `b`, but the type of `a` still had metavariables and it failed to unify them to match the type of `b`. The solution in that case was to provide a type ascription to `a` to avoid the metavariables. I found this out by doing `#check a` and `#check b`.

Without looking, I would bet something similar is happening here. If you don't manage it, I'll have a look later this evening.

**Comment by LukasMias** [comment]
> @LukasMias in my ports of other files involving quotients I found that Lean 4 was significantly worse at unification. As a result, adding type ascriptions both sped up elaboration significantly as well as avoided whnf timeouts. For instance, in a statement of an equality `a = b`, Lean 4 could correctly deduce the type of `b`, but the type of `a` still had metavariables and it failed to unify them to match the type of `b`. The solution in that case was to provide a type ascription to `a` to avoid the metavariables. I found this out by doing `#check a` and `#check b`.
> 
> Without looking, I would bet something similar is happening here. If you don't manage it, I'll have a look later this evening.

Appreciate the thoughts! Currently, it seems to be some problem with wrongly inferred instances. I could try to manually add them all, but that's not pretty, and I'm also not sure about the correct choices.

**Comment by mattrobball** [comment]
Two `simpNF` LHS simplifies errors left. Feel free to push this over the finish line. I probably won't touch it for a bit.

**Review by Parcly-Taxel — APPROVED** [review]

**Pull request closed without merging**
