### PR TITLE
[Merged by Bors] - feat: port Analysis.InnerProductSpace.Projection

### PR DESCRIPTION
**Pull request by Komyyy**
This PR also increase the priority of `Submodule.bot_ext`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Parcly-Taxel** [comment]
You don't need to make #4390 a separate PR, since it's so small and it helps just this PR. You can close #4390 and incorporate its change into here.

**Comment by Komyyy** [comment]
@Parcly-Taxel I closed #4390.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by jcommelin** [comment]
Whoops, CI wasn't done yet.

bors r-

bors d+

**Comment by jcommelin** [comment]
bors d=j-loreaux

**Comment by j-loreaux** [comment]
bors merge

**Pull request closed without merging**
