### PR TITLE
[Merged by Bors] - feat: completion of a nonarchimedean additive group

### PR DESCRIPTION
**Pull request by trivial1711**
We prove that the completion of a nonarchimedean additive group is a nonarchimedean additive group.

Detailed comments are included because I could not find a proof in the literature anywhere.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
I pushed a small tweak to make the lean code look more like your comments. The verbosity here is a bit unusual, so I'll let another reviewer make the call.

**Comment by eric-wieser** [comment]
> The verbosity here is a bit unusual

Could you elaborate a little on what motivated writing in this style? Did you start with a english proof, and try to translate it literally to Lean? Did you write a lean proof, then add lots of comments to explain it to a non-lean-user? I think the style is ok to keep, but the PR description would be a good place to explain the atypical amount of detail.

**Comment by trivial1711** [comment]
> > The verbosity here is a bit unusual
> 
> Could you elaborate a little on what motivated writing in this style? Did you start with a english proof, and translate it as literally as possible to Lean? Did you write a lean proof, then add lots of comments to explain it to a non-lean-user? I think the style is ok to keep, but the PR description would be a good place to explain the atypical amount of detail.

It's because I couldn't find a proof in the literature; it's one of those things that is considered a "folklore result". So I thought it would be useful to have a full proof written down somewhere.

**Comment by eric-wieser** [comment]
bors merge

Thanks!

**Pull request closed without merging**
