### PR TITLE
[Merged by Bors] - feat: port Analysis.SpecialFunctions.Log.Basic

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
Includes some additional declarations and golfs from #4017.

Co-authored-by: Yury G. Kudryashov <urkud@urkud.name>

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
Having looked at this quickly, I think I like @urkud's #4017 (he added some lemmas and golfed a bit, and Yury's golfing is always excellent. :-)

However I prefer your `_` over Yury's `_hx` for unused arguments, and I like your changes e.g. writing just `log` instead of `Real.log` in comments, and formatting the comments.

Can I just suggest you check with Yury if it's okay to push those changes to his branch, and then we'll merge that one?

**Comment by urkud** [comment]
@semorrison Or you can merge this one, and I'll turn my PR into "add lemmas / golf".

**Comment by semorrison** [comment]
Okay, let's do that then.

bors merge

**Comment by Parcly-Taxel** [comment]
@semorrison I went ahead and combined @urkud's changes from #4017 into here.

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
