### PR TITLE
[Merged by Bors] - refactor(LinearAlgebra/QuadraticForm): rename `Isometry` to `IsometryEquiv`

### PR DESCRIPTION
**Pull request by eric-wieser**
This is consistent with `LinearIsometryEquiv` vs `LinearIsometry`. The motivation is to make room for `QuadraticForm.Isometry` as the homomorphism.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by kex-y — APPROVED** [review]
I'm happy with the name change

**Review by ADedecker — COMMENTED** [review]
bors d+

LGTM modulo small issue in docstrings

**Review by ADedecker — COMMENTED** [review]
bors d+

LGTM modulo small issue in docstrings

**Comment by eric-wieser** [comment]
bors merge

**Pull request closed without merging**
