### PR TITLE
[Merged by Bors] - chore: enable subsingleton.elim in aesop_cat

### PR DESCRIPTION
**Pull request by kim-em**
See discussion at https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Failure.20of.20TC.20search.20in.20.60simp.60.20with.20.60etaExperiment.60.2E.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
Does it make sense to `!bench` this?

**Comment by semorrison** [comment]
!bench

**Comment by semorrison** [comment]
Can't hurt.

**Comment by jcommelin** [comment]
I get 404's when I try to follow the links.

**Comment by semorrison** [comment]
They work for me now. No significant change, infinitesimal improvement to wall-clock time, but surely within the margin of error.

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
