### PR TITLE
[Merged by Bors] - chore(LinearAlgebra/Matrix): split off `Matrix.stdBasis` to its own file

### PR DESCRIPTION
**Pull request by Vierkantor**
Previously, `LinearAlgebra.StdBasis` also defined the standard basis for matrices. We don't need matrices to define finite-dimensional spaces.

It would be nice to instead swap the import order: `LinearAlgebra.StdBasis` imported by `LinearAlgebra.Matrix.Basis`, but unfortunately that would cause a cycle with `LinearAlgebra.Matrix.ToLin`. Not entirely sure if that dependency is worth the hassle of further untangling.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Comment by jcommelin** [comment]
Please merge master

bors d+

**Comment by Vierkantor** [comment]
I think the right way to go to fix this PR is to split `RingTheory/Finiteness.lean` first, then the imports should hopefully resolve in the right way.

**Comment by Vierkantor** [comment]
The build passed so:

bors r+

**Pull request closed without merging**
