### PR TITLE
chore: bump packages

### PR DESCRIPTION
**Pull request by kim-em**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
!bench

**Comment by semorrison** [comment]
@Kha, any reaction to this benchmark?

**Comment by gebner** [comment]
This breaks caching since aesop enabled precompiled modules.

**Review by gebner — CHANGES_REQUESTED** [review]
This should not be merged until caching is fixed.

**Comment by Kha** [comment]
Seems fine to update to aesop d65e2400a95bd1549bb143c5c001be6c941c6532, the subsequent commits are exactly the problematic ones (the second one is responsible for https://github.com/leanprover-community/mathlib4/pull/3216#issuecomment-1493121409).

**Pull request closed without merging**
