### PR TITLE
[Merged by Bors] - chore: remove `open (scoped)? BigOperators` lines

### PR DESCRIPTION
**Pull request by Komyyy**
---

- [x] depends on: #13271

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by YaelDillies — COMMENTED** [review]
Is there not a bunch of `open scoped BigOperators` that can now be removed?

Also you will need to gather more opinion than just mine since I was the one suggesting the unscoping.

**Comment by loefflerd** [comment]
Oof, 769 files changed... the diff is so big my browser freezes trying to render it!

May I suggest splitting this into 3 PR's, for ease of reviewing? I suggest the following:

(1) the rename from `∏` to `∏ᶜ` in category theory
(2) the changes to the `BigOperators` files
(3) removing the `open scoped` lines elsewhere in mathlib

That way (1) and (2) will be small, and (3) will be long but completely mechanistic; so the reviewing will be much easier.

**Comment by Komyyy** [comment]
@loefflerd #13269

**Comment by YaelDillies** [comment]
maintainer merge

**Pull request closed without merging**
