### PR TITLE
[Merged by Bors] - chore: remove superfluous parentheses in calls to `ext`

### PR DESCRIPTION
**Pull request by kim-em**
---

- [x] depends on: #5219 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5219
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5219~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by sgouezel** [comment]
bors r+
Thanks!

**Comment by fpvandoorn** [comment]
the git history got messed up

**Pull request closed without merging**
