### PR TITLE
[Merged by Bors] - chore: rename `pochhammer`

### PR DESCRIPTION
**Pull request by mo271**
We rename `pochhammer` to `ascPochhammer`  to prepare adding `descPochhammer`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
This will result in a merge conflict with #6897 and #6906. I'm happy to work them out

**Comment by mo271** [comment]
bors d+

**Comment by mo271** [comment]
this should be ready to go again, the merge conflict was expected and is resolved now

**Comment by mo271** [comment]
I think this should merge cleanly by now...

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
