### PR TITLE
[Merged by Bors] - chore: typo in lean-pr-testing-comments.sh

### PR DESCRIPTION
**Pull request by nomeata**
sorry! Unfortunately these workflows are hard to test.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by nomeata** [comment]
This unbreaks mathlib-CI for lean. I just pushed it to `nightly-testing`, but it should still go `master`

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors d+

**Pull request closed without merging**
