### PR TITLE
feat: port MeasureTheory.Group.Action

### PR DESCRIPTION
**Pull request by Komyyy**
---

- [x] depends on: #4101
- [x] depends on: #4154

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4101
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
@Komyyy, is this really waiting on a performance improvement? Can we just proceed without? @digama0 has an alternative solution to the performance problem at https://github.com/leanprover-community/mathlib4/pull/4422.

**Comment by Komyyy** [comment]
@semorrison When #4422 is merged into master, I will reopen this PR.

**Comment by Komyyy** [comment]
Please refer to #4431.

**Pull request closed without merging**
