### PR TITLE
feat(CategoryTheory/WithTerminal): Add equivalence of categories.

### PR DESCRIPTION
**Pull request by jstoobysmith**
Added the following

- An equivalence between `WithTerminal C` and `WithTerminal D`, and between  `WithInitial C` and `WithInitial D`, from an equivalence between `C` and `D`.
-  An equivalence `(WithTerminal C)⥤ D` and the comma category `Comma (𝟭 (C ⥤ D)) (Functor.const C)`
-  An equivalence `(WithInitial C)⥤ D` and the comma category `Comma (Functor.const C) (𝟭 (C ⥤ D))`
-  An equivalence  `WithTerminal Cᵒᵖ` and `(WithInitial C)ᵒᵖ`
-  An equivalence `WithInitial Cᵒᵖ` and `(WithTerminal C)ᵒᵖ`

and related definitions and lemmas.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by TwoFX** [comment]
Hi, thank you for this PR. We definitely want all of these things (or variants thereof) in mathlib. We generally find that many small PRs are easier to review than one large PR (especially for contributors which don't have many merged PRs yet), and this PR should be quite easy to split up into multiple PRs (one for `map_id` and `map_comp`, one for the `Comma` stuff, one for the opposites, etc.). Would you mind splitting off `map_id` and `map_comp` into a separate PR for now and requesting a review from me on that one?

**Comment by jstoobysmith** [comment]
@TwoFX Yep I will split them up into smaller PRs. I actually may focus on the `Comma` stuff and the`Opposite` stuff first though, as these are what I actually need. 

Also, I think the `map_comp`, `map_id` stuff is most properly done by defining a strict 2-functor (one for `WithTerminal` and one for `WithInitial`) from the strict bicategory `Cat` to itself. But it seems like strict 2-functors aren't in MathLib4 yet.

**Comment by TwoFX** [comment]
@jstoobysmith Yes, with what we currently have, the correct way to state `map_id` and `map_comp` is as a natural isomorphism. We only state equalities of functors if they are definitional (i.e., the proof is `rfl`) since then the DTT issues are much less bad.

**Comment by jstoobysmith** [comment]
@TwoFX I've created another pull request #10533 which contains pseudofunctors from Cat to Cat.

**Pull request closed without merging**
