### PR TITLE
[Merged by Bors] - Fix typos

### PR DESCRIPTION
**Pull request by Fryie**
Fix typos:

* Use Π instead of ∀ for statement of Chinese Remainder Theorem
* Weistrass -> Weierstrass

---
Not sure if people would prefer this in two separate PRs.

For the first change, see: https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Mathematics.20in.20Lean.2C.20CRT.20-.20Notation.20confusion

For the second, the German name is technically "Weierstraß", but "Weierstrass" is acceptable in English - and also it's consistent with the spelling elsewhere in the codebase.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Thanks for your contribution to mathlib!

Did you mean to mark this PR as ready for review? If so, please apply the `awaiting-review` label (in the future; I just marked this one). (The [contribution guidelines](https://leanprover-community.github.io/contribute/index.html) contain this trick and a few more.)

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Review by grunweg — COMMENTED** [review]
Thanks for your contribution; I think both changes look good.

(While "Weierstraß" would indeed be nicer, I'd rather change *all* such instances, which can happen in a separate PR.)
maintainer merge

**Comment by grunweg** [comment]
Whoops, two people approved this at the same time :-) I guess we agree this change is good.

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
