### PR TITLE
[Merged by Bors] - chore: use AlgHom.restrictDomain

### PR DESCRIPTION
**Pull request by alreadydone**
I previously didn't know the existence of `AlgHom.restrictDomain` and wrote many lemmas using a longer expression that is exactly the definition of `AlgHom.restrictDomain`; I'm now changing all these lemmas to use `AlgHom.restrictDomain`. There are more appearances of `.comp (IsScalarTower.toAlgHom` but either the file doesn't import `AlgHom.restrictDomain`, or using it breaks the proof, so I only replaced one appearance.

---

[Another replacement can be made](https://github.com/leanprover-community/mathlib4/compare/restrictDomain_galRestrictHom?expand=1#diff-6c5be70eec39d6174e862455c4b40edf3675e04ab9b24e681dfbc42460fa8062), and if reviewers think it's appropriate, I can certainly merge.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
Seems reasonable

maintainer merge

**Comment by j-loreaux** [comment]
@alreadydone yes, please merge in the additional replacement.

**Comment by j-loreaux** [comment]
bors d+

**Review by alreadydone — COMMENTED** [review]
Thanks!
bors r+

**Pull request closed without merging**
