### PR TITLE
[Merged by Bors] - refactor: split `MeasureTheory.Group.Integration`

### PR DESCRIPTION
**Pull request by fpvandoorn**
I want to use the lemma `lintegral_add_right_eq_self` in a file that doesn't import Bochner integration.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by hrmacbeth** [comment]
Should the file name be `.LIntegral` rather than `.Lintegral`?  No preference from me, I will defer to someone who's willing to make a ruling about the naming convention.

**Comment by fpvandoorn** [comment]
I don't have a strong opinion, maybe `LIntegral` is indeed better. However, we're not consistent: `Lintegral` occurs 17 times in mathlib (mostly section names, but also a few declaration names). `LIntegral` occurs twice (section name)

**Comment by ocfnash** [comment]
I also slightly prefer `LIntegral` but I'll let you make the call.

bors d+

**Comment by fpvandoorn** [comment]
bors merge

**Pull request closed without merging**
