### PR TITLE
[Merged by Bors] - chore: script for `by` linebreaks

### PR DESCRIPTION
**Pull request by mo271**
Not quite sure if the `-i inplace` part will work on all systems...

### CODE REVIEW

**Comment by mo271** [comment]
It might be good, as suggested by @digama0 to run this when generating the files for mathlib3port

**Comment by eric-wieser** [comment]
Can mathport do this for us?

**Comment by mo271** [comment]
I think that would be very good! 
In fact it might even do this for lines of length 98, 99 and 100, resulting in some linter warning, that the person porting can take care of manually in those cases, because with this script those cases are not taken care of.

**Comment by rwbarton** [comment]
mathport used to get the `by` location correct (at least more of the time), it seems things changed in the run that resulted in https://github.com/leanprover-community/mathlib3port/commit/27def984dfd287bf25cbc09ac35d7bdcc475fe29.
But the old version has a lot of weird layout in declarations, as well.
It's also not clear to me what actually changed to cause the new layout...

**Comment by rwbarton** [comment]
Could you add a 1-2 line comment explaining what the script does (e.g. `# Modify all lean files in mathlib to put "by" at the end of the previous line, where possible`)?

**Comment by digama0** [comment]
> mathport used to get the `by` location correct (at least more of the time), it seems things changed in the run that resulted in [leanprover-community/mathlib3port@27def98](https://github.com/leanprover-community/mathlib3port/commit/27def984dfd287bf25cbc09ac35d7bdcc475fe29). But the old version has a lot of weird layout in declarations, as well. It's also not clear to me what actually changed to cause the new layout...

That run was [mathport #544](https://github.com/leanprover-community/mathport/actions/runs/3791621066/jobs/6447182970), and if you look at the [CI page](https://github.com/leanprover-community/mathport/actions/workflows/build.yml?page=3) from around then you will notice that that run was preceded by mathport being broken for several days, during which there was a [lean bump](https://github.com/leanprover-community/mathport/commit/c270f11613944e54a792a8c1a45fcca6521c46de#diff-20b3ac31799816b1e4a8d506b736400c782590eff87ea8ed16957d0289308bce) from lean4:nightly-2022-12-16 to lean4:nightly-2022-12-22. [During that period](https://github.com/leanprover/lean4/compare/f6cd6c069587cfe62dd68cb6330f9ad794a56724...a2f59591189824f30a7a512d6a72d24df3a7bfc7) the most likely commits that could have caused this are

* [fix: Format.align always prints whitespace](https://github.com/leanprover/lean4/commit/0d598dcfdf263398d8a68e95bad0d31a40f87b3b) by gebner
* [fix: parenthesize `by` `optParam` values](https://github.com/leanprover/lean4/commit/96ccf192e8a5fe216bbc63c688a06b2032bd14f5) by Kha
* [refactor: remove redundant state](https://github.com/leanprover/lean4/commit/533c770e36a6ea02093195e67ba19e13042cc378) by Kha

**Comment by mo271** [comment]
> Could you add a 1-2 line comment explaining what the script does (e.g. `# Modify all lean files in mathlib to put "by" at the end of the previous line, where possible`)?

Done

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
