### PR TITLE
[Merged by Bors] - style: replace `coe := fun x =>` by `coe x :=` and similar

### PR DESCRIPTION
**Pull request by madvorak**
---

Let's wait for the CI to complete. I did NOT build it locally.

### CODE REVIEW

**Comment by adomani** [comment]
I like this style: I do not think that this is specifically encouraged by the style guide, but I am happy to

maintainer merge

this PR!

**Comment by madvorak** [comment]
Please wait for the CI.

**Comment by sgouezel** [comment]
It doesn't build for now.

**Review by eric-wieser — APPROVED** [review]
bors merge

Thanks!

**Pull request closed without merging**
