### PR TITLE
[Merged by Bors] - chore: fix a typo in PolarCoord

### PR DESCRIPTION
**Pull request by xroblot**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Thanks for catching this! Can you add a deprecation alias for the lemma you renamed, please?
awaiting-author

**Review by grunweg — COMMENTED** [review]
Looks good now, thanks!
maintainer merge

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
