### PR TITLE
[Merged by Bors] - chore: remove scripts/mk_all.sh

### PR DESCRIPTION
**Pull request by grunweg**
It has since been rewritten in Lean, and is unused.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
CC @semorrison adomani

**Comment by adomani** [comment]
My main reason for wanting to keep this script was that Floris had problems using `lake exe mk_all` on windows.  However, I think that those issues were only marginally related to the lake script and they appear to have been solved.  I use the script regularly and CI uses is as well.  I would just like some confirmation from some MacOs user that it works as intended for them and then I'm happy to remove the shell script!

**Comment by semorrison** [comment]
Worked for me on macos.

bors merge

**Comment by Ruben-VandeVelde** [comment]
I'm sad to see this - I'm still using it regularly

**Comment by adomani** [comment]
Rubén, why do you not use `lake exe mk_all`?

**Pull request closed without merging**
