### PR TITLE
[Merged by Bors] - chore(SetTheory/Ordinal/Basic): deprecate results on `WellOrder`

### PR DESCRIPTION
**Pull request by vihdzp**
This PR is analogous to #18205.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by YaelDillies** [comment]
Sorry, I'm not sure I understand why it is analogous to https://github.com/leanprover-community/mathlib4/pull/18205. Are you planning of eventually getting rid of `WellOrder`?

**Comment by vihdzp** [comment]
`WellOrder` is an implementation detail. The preferred form of the quotient constructor is `type r`, and we should never be using anything like `⟦⟨α, r, wo⟩⟧`.

**Review by YaelDillies — COMMENTED** [review]
Hmm okay

maintainer merge

**Comment by b-mehta** [comment]
bors merge

**Pull request closed without merging**
