### PR TITLE
[Merged by Bors] - refactor: Redefine `pow` in terms of `iterate`

### PR DESCRIPTION
**Pull request by YaelDillies**
In the `Monoid` instances for `Function.End α`, `Equiv.Perm α`, `Monoid.End α`, `AddMonoid.End α`, `α →+* α`, replace the default `npowRec` by a custom one in terms of `Nat.iterate`. Write the expected coercion lemmas.

As a consequence, I can delete the recently introduced file `Algebra.Ring.Hom.IterateHom`.

Zulip discussion: https://leanprover.zulipchat.com/#narrow/stream/144837-PR-reviews/topic/.231388.20Redefine.20pow.20in.20terms.20of.20iterate

---

Rehash of https://github.com/leanprover-community/mathlib/pull/18077

### CODE REVIEW

**Comment by semorrison** [comment]
@YaelDillies, the original mathlib3 PR is marked as `too-late`, now. I'm removing `forward-port-placeholder` and `mathlib3-pair`. Could you prepare it for review directly to mathlib4, or close?

**Comment by semorrison** [comment]
Sorry, actually as this PR is empty I'll just close. Just open a new PR if you'd like to bring the material across.

**Comment by urkud** [comment]
Let me repeat my concern from Lean3 PR:

> Note that if we go forward with this refactor, the monoid structure on `CategoryTheory.End (GroupCat.of G)` will be no longer defeq to `Monoid.End.monoid`. I don't know whether we ever rely on this defeq.

**Comment by YaelDillies** [comment]
I don't understand how that's not fixable. Surely it's just a matter of tweaking the `pow` defeq in `Monoid (CategoryTheory.End (GroupCat.of G))`?

**Comment by urkud** [comment]
`Monoid (CategoryTheory.End _)` is defined uniformly for all categories, you can't fix `pow` for one category. If you want to be able to do that, then you need to include this data in the definition of `Category`.

**Comment by YaelDillies** [comment]
Yeah okay. I must say I don't think it's defeq's job to translate category-theoretic constructs to their group-theoretic equivalents. 

The fact that we can do it in simple cases doesn't mean it extends indefinitely and indeed I would rather have a `to_additive`-like tactic to perform the translation rather than relying on cosmic alignment of definitions.

Right now, this translation sounds like a pretty niche use case anyway?

**Comment by urkud** [comment]
The issue is not about translation. The issue is that we'll have 2 defeq types with propeq but not defeq instances about them.

**Comment by YaelDillies** [comment]
Well they're only defeq because one is a too-transparent type synonym of the other, right? Using that would be defeq abuse.

**Comment by urkud** [comment]
Could you please open a Zulip discussion? I don't want to merge this PR myself, but if another maintainer rules my objection as invalid/irrelevant, then I won't insist.

**Comment by jcommelin** [comment]
Zulip discussion: https://leanprover.zulipchat.com/#narrow/stream/144837-PR-reviews/topic/.231388.20Redefine.20pow.20in.20terms.20of.20iterate

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by kbuzzard** [comment]
Note that the Zulip discussion is not publicly viewable

**Pull request closed without merging**
