### PR TITLE
[Merged by Bors] - chore(Data/Polynomial/Basic): golf & make some variables implicit

### PR DESCRIPTION
**Pull request by astrainfinita**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by kbuzzard** [comment]
LGTM

**Comment by RemyDegenne** [comment]
Thanks!
bors r+

**Comment by eric-wieser** [comment]
bors d+

Please resolve the conflicts (`Type _` should be `Type*`)

**Pull request closed without merging**
