### PR TITLE
Add a LICENSE

### LINKED ISSUE #2: needs a LICENSE
If you are accepting external contributions, it will save you headaches later if you nail down the license ASAP.
Otherwise, you could get into an awkward situation where you need to chase down all contributors
to ask their permission about various ways you might want to use the code.

Simplest would be to copy the [Apache license from mathlib](https://github.com/leanprover-community/mathlib/blob/master/LICENSE).

### PR DESCRIPTION
**Pull request by Julian**
Closes #2.

### CODE REVIEW

**Comment by gebner** [comment]
I'm fine with licensing my contributions under Apache 2.

**Comment by digama0** [comment]
All my OSS work is public domain.

**Comment by Julian** [comment]
Would you prefer something else here?

(I think just saying something's public domain without a license is still a bit tricky if that's what you were suggesting -- IANAL of course but Wikipedia seems to corroborate: https://en.wikipedia.org/wiki/Public-domain-equivalent_license#Licenses though in a section with a Citation Needed... Obviously CC0 or whichever else is an option if others want that)

And I figured if folks were going to perhaps start copying/porting things out of mathlib that it's already itself Apache 2 so it'd get a bit tricky there, but yeah obviously let me know what you want! I see @dwrensha noticed the same thing I did, which was simply "it'll be easier if this were here earlier rather than later" :)

**Comment by digama0** [comment]
...which is to say I'm fine with putting an apache 2 license on it. As you say, we can't not use apache 2 since we will be copying large parts of mathlib.

**Pull request merged**
