### PR TITLE
[Merged by Bors] - chore: forward port leanprover-community/mathlib#19178

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
Which really only consists of a SHA update.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
I can't find it on the porting dashboard.

**Comment by Parcly-Taxel** [comment]
> I can't find it on the porting dashboard.

Wait 30 minutes or so.

**Comment by Parcly-Taxel** [comment]
@urkud and now it's there.

**Comment by Parcly-Taxel** [comment]
> Can we remove the `haveI` line also in Lean4?

Yes.

**Comment by riccardobrasca** [comment]
Thanks!

bors d+

**Comment by Parcly-Taxel** [comment]
bors merge

**Pull request closed without merging**
