### PR TITLE
[Merged by Bors] - feat: port GroupTheory.GroupAction.Opposite

### PR DESCRIPTION
**Pull request by antoinelab01**
mathlib SHA : fc2ed6f838ce7c9b7c7171e58d78eaf7b438fb0e

### CODE REVIEW

**Comment by antoinelab01** [comment]
It seems like there are some serious issues with `MulOpposite` being a type synonym. See https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/rw.20seeing.20through.20type.20synonym.3F for discussion.

**Comment by antoinelab01** [comment]
- depends on: #1036

**Comment by jcommelin** [comment]
I think that merging master helped.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Review by kbuzzard — COMMENTED** [review]
We've taken a gamble and merged the `MulOpposite` PR, refactoring it to make it a one field structure; in this file we see the benefits, as a bunch of proofs which needed `@` previously no longer do so.

I would say that this is ready to go but unfortunately there are a bunch of declarations generated by `to_additive` which are not aligned; I will do these now. If someone's finger is hovering over the merge button, can I ask them to wait for 15 minutes!

**Comment by kbuzzard** [comment]
Darn it, too late! I'll open another PR with my golfs and fixes.

**Pull request closed without merging**
