### PR TITLE
[Merged by Bors] - feat: Rationalise `ModEq` lemma names

### PR DESCRIPTION
**Pull request by YaelDillies**
Match https://github.com/leanprover-community/mathlib/pull/17902

### CODE REVIEW

**Review by kbuzzard — COMMENTED** [review]
The mathlib3 PR seems to have more changes to the int file (I didn't check the nat file). Doesn't the theorem name on line 112 of Data.Int.Modeq need to be changed?

**Comment by YaelDillies** [comment]
Well spotted!

**Comment by kbuzzard** [comment]
This looks fine now. I'd maintainer merge if it worked.

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
