### PR TITLE
[Merged by Bors] - chore: Move `DistribMulAction` on `Opposite`, `Pi`, `Prod`, `Sum`, `Sigma`, `Units`

### PR DESCRIPTION
**Pull request by YaelDillies**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
Just checking that the import increases in
* Mathlib.Algebra.GroupWithZero.Action.Units	
* Mathlib.Algebra.GroupWithZero.Action.Prod	
* Mathlib.Algebra.GroupWithZero.Action.Pi
reported by the bot above have been considered.

**Comment by YaelDillies** [comment]
@semorrison, these are new files. The imports are increasing from 0 (because the file didn't exist) to the number of imports they have.

@adomani, as you can see above, including new files in the import summary is confusing (maybe you should get info from git about file renames, and compare the new file to the old file instead of to an empty file?)

**Comment by adomani** [comment]
I need to think a little about this.  One way to mitigate this issue that is possibly easy to implement is to flag new/removed files.  So, in the report above, you would see

|Files|Import difference|
|-|-|
| `Mathlib.GroupTheory.GroupAction.Units` (removed file)|-296|
| `Mathlib.GroupTheory.GroupAction.Pi` (removed file)|-235|
| `Mathlib.GroupTheory.GroupAction.Prod` (removed file)|-204|
|<details><summary>3 files</summary> `Mathlib.Algebra.GroupWithZero.Units.Lemmas` `Mathlib.Algebra.Field.Basic` `Mathlib.Algebra.Ring.Action.Field`</details>|-100|
| `Mathlib.Algebra.Order.Field.InjSurj` `Mathlib.Tactic.CancelDenoms.Core`|-91|
| `Mathlib.Algebra.GroupWithZero.Action.Units` (new file)|195|
| `Mathlib.Algebra.GroupWithZero.Action.Prod` (new file)|204|
| `Mathlib.Algebra.GroupWithZero.Action.Pi` (new file)|323|

Otherwise, since git also bails somewhat on renames/splits, it might be trickier to implement and would have to use a logic closer to the one for the decl-diff for the the files changed.

The information about erased/new files is readily available, though.

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Comment by j-loreaux** [comment]
LGTM, thanks for the organizational effort @YaelDillies !

bors merge

**Pull request closed without merging**
