### PR TITLE
fix: add a workaround for lean4#2220 globally

### PR DESCRIPTION
**Pull request by eric-wieser**
This removes all the `local macro_rules` and adds a global one.

leanprover/lean4#2220 trips up every new user of mathlib.
Let's just override core ourselves, rather than telling everyone else to.

---

- [x] depends on: #8279
- [x] depends on: #8291
- [x] depends on: #8292

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by j-loreaux** [comment]
Agreed. Obviously wait until the other PR lands and you merge master here, but...

bors d+

**Comment by kmill** [comment]
Please do not merge this. There is a core fix in the works, and there is a branch with global fixes: https://github.com/leanprover-community/mathlib4/compare/nightly-testing...lean-pr-testing-2778

**Comment by eric-wieser** [comment]
@kmill, my plan is to extract some of the fixes from this branch as standalone style fixes; I think many of them are improvements even without the elaboration change.

This PR is looking like it will be fairly light on hacks; my claim is that it's worth merging even if a better solution is coming to core in 1-2 weeks (which might be 3-4 before mathlib sees it?)

**Comment by fpvandoorn** [comment]
Would it be possible to add @kmill's fix in mathlib, and then remove it in 1-4 weeks once it's in core?

**Comment by kmill** [comment]
@fpvandoorn If we add our own elaborator override, there are other hacks we have to insert that we'll have to undo, but those aren't so bad (ex: `simp [(. ^ .)]` to `simp [HPow.hPow]`).

@eric-wieser I'm not too happy that I learned about your independent efforts only because I happened to take a look at lean4#2220 and noticed this linked PR. I assume you're aware that the core PR had a linked mathlib branch of fixes? I would appreciate more synchronization here -- it feels like you're frustrated it's taking so long and don't mind silently making more work for me.

What would be very helpful is if you could start instead by reviewing my mathlib fixes (#8284). You can push better fixes to that branch if you want. But please don't add any intentionally conflicting fixes to mathlib that impede work toward actually fixing the issue...

**Comment by eric-wieser** [comment]
> @eric-wieser I'm not too happy that I learned about your independent efforts only because I happened to take a look at lean4#2220 and noticed this linked PR

Apologies, I should have labelled this RFC; I was not angling for a speedy merge, and didn't communicate that. My plan was to make a Zulip thread once I got everything compiling.

**Comment by eric-wieser** [comment]
> What would be very helpful is if you could start instead by reviewing my mathlib fixes (#8284). You can push better fixes to that branch if you want. But please don't add any intentionally conflicting fixes to mathlib that impede work toward actually fixing the issue...

What's the protocol for merging master in these PRs? I assume I push a commit to `nightly-testing-2023-11-08` that merges `master`?

**Comment by fpvandoorn** [comment]
Shall we close this?

**Pull request closed without merging**
