### PR TITLE
[Merged by Bors] - fix: add trailing line break to `noshake.json`

### PR DESCRIPTION
**Pull request by adomani**
Add a line break at the end of the `noshake.json` file.  Git does not like files that do not end in a new-line and when you `cat scripts/noshake.json` it is nicer if the file ends in a new line.  :smile: 

I labeled it as `bug`, because it bugs me. :cockroach: 

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by fpvandoorn** [comment]
bors merge

**Comment by YaelDillies** [comment]
I will remark that this line breaks has been added and removed several times in the past week, so this doesn't seem like a very long-term fix. Mind fixing `shake` itself instead?

**Comment by adomani** [comment]
I thought that this is what I did, no?

**Comment by adomani** [comment]
That is, I modified ``shake.Main`, not the `noshake` file itself.

**Comment by YaelDillies** [comment]
Ah sorry, that's not what your PR title said!

**Comment by adomani** [comment]
You are right: the title describes the effect, rather than the actual change.

**Pull request closed without merging**
