### PR TITLE
[Merged by Bors] - chore(Topology/Category): remove `ProfiniteMax` and `CompHausMax`

### PR DESCRIPTION
**Pull request by dagurtomas**
They are no longer necessary after [#3981](https://github.com/leanprover/lean4/pull/3981)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by dagurtomas** [comment]
!bench

**Comment by dagurtomas** [comment]
When removing `TopCatMax`, Lean didn't automatically find the instance `topCat_hasLimitsOfSize` in one case.

**Comment by dagurtomas** [comment]
!bench

**Comment by joelriou** [comment]
Thanks!

bors merge

**Comment by joelriou** [comment]
bors merge

**Pull request closed without merging**
