### PR TITLE
[Merged by Bors] - chore: Better names for `(⌊a⌋₊ : α) = ⌊a⌋` again

### PR DESCRIPTION
**Pull request by YaelDillies**
Also remove the six months old deprecated names

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by YaelDillies** [comment]
Note to other reviewers: I'm expecting Eric and no one else to review this.

**Review by eric-wieser — APPROVED** [review]
These names look better to me, thanks!

Can you mention in the description that you removed the deprecated names?

**Comment by eric-wieser** [comment]
bors d+

**Comment by YaelDillies** [comment]
bors merge

**Pull request closed without merging**
