### PR TITLE
[Merged by Bors] - feat: port LinearAlgebra.Matrix.Trace

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

- [x] depends on: #2960

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
Note that creating this PR has confused the porting dashboard, as it contains `data/matrix/basic` too.

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2960
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2960~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by Ruben-VandeVelde — APPROVED** [review]
lgtm

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
