### PR TITLE
[Merged by Bors] - feat: rewrite cylinders and projective families of measures in terms of `Finset.restrict`

### PR DESCRIPTION
**Pull request by EtienneC30**
Rewrite cylinders and projective families of measures in terms of `Finset.restrict`. This avoids type ascription, and allows to rewrite a restriction as the composition of two restrictions, which is helpful when manipulating projective families.

---

- [x] depends on: #16300
- [x] depends on: #16328

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by RemyDegenne — COMMENTED** [review]
This looks like a clear improvement, apart from all the `config := { unfoldPartialApp := true }`. Why are they needed? Is there a way to add API to something to make them go away?

**Comment by EtienneC30** [comment]
I did not want `Finset.restrict` and co to be unfolded by the simplifier when only partially applied, but this broke some `simp` proofs, that's why I added the `config`. Another way I thought of would be to add some lemma `restrict_def` which unfolds the partial app. It shouldn't be a `simp` lemma, but could be passed as an argument to `simp` or used with `rw`. In fact at the time I wrote the code I was a bit frustrated that natural `simp` proofs broke and did not want to add a new lemma to fix it because it would require to know about that lemma, but maybe I should go for this option instead?

**Comment by RemyDegenne** [comment]
Adding the lemma `restrict_def` seems the way to go. Don't give it the `simp` attribute but add it to the list of lemmas used by the `simp` calls in those proofs.

**Review by RemyDegenne — APPROVED** [review]
Thanks!
bors r+

**Pull request closed without merging**
