### PR TITLE
[Merged by Bors] - doc: fix some author fields in references

### PR DESCRIPTION
**Pull request by acmepjz**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by acmepjz** [comment]
I think that `\'{\i}` is also wrong, it should be `\'i`. Any opinions?

**Comment by faenuccio** [comment]
I have removed the `awaiting-review` label according to the decision explained here
https://leanprover.zulipchat.com/#narrow/stream/113486-announce/topic/Changes.20to.20the.20.23queue/near/450176907

**Comment by acmepjz** [comment]
> I have removed the `awaiting-review` label according to the decision explained here https://leanprover.zulipchat.com/#narrow/stream/113486-announce/topic/Changes.20to.20the.20.23queue/near/450176907

I see. Sorry for the inconvenience.

**Comment by eric-wieser** [comment]
> I think that `\'{\i}` is also wrong (it does not render correctly in my WIP pure Lean bibtex diacritic parser [leanprover/doc-gen4#200](https://github.com/leanprover/doc-gen4/pull/200)), it should be `\'i`. Any opinions?

https://tex.stackexchange.com/q/409927/41112 suggests that the original is valid, but unnecessary in modern LaTeX.

bors merge

Thanks!

**Pull request closed without merging**
