### PR TITLE
[Merged by Bors] - feat: define `UniformSpace.ofFun`

### PR DESCRIPTION
**Pull request by urkud**
Forward-port leanprover-community/mathlib#18495

---

* [`order.filter.basic`@`24e75f1ee89ff37e99581084704f3f6a950db2ea`..`e1a7bdeb4fd826b7e71d130d34988f0a2d26a177`](https://leanprover-community.github.io/mathlib-port-status/file/order/filter/basic?range=24e75f1ee89ff37e99581084704f3f6a950db2ea..e1a7bdeb4fd826b7e71d130d34988f0a2d26a177)
* [`topology.uniform_space.basic`@`59694bd07f0a39c5beccba34bd9f413a160782bf`..`e1a7bdeb4fd826b7e71d130d34988f0a2d26a177`](https://leanprover-community.github.io/mathlib-port-status/file/topology/uniform_space/basic?range=59694bd07f0a39c5beccba34bd9f413a160782bf..e1a7bdeb4fd826b7e71d130d34988f0a2d26a177)
* [`topology.uniform_space.absolute_value`@`2705404e701abc6b3127da906f40bae062a169c9`..`e1a7bdeb4fd826b7e71d130d34988f0a2d26a177`](https://leanprover-community.github.io/mathlib-port-status/file/topology/uniform_space/absolute_value?range=2705404e701abc6b3127da906f40bae062a169c9..e1a7bdeb4fd826b7e71d130d34988f0a2d26a177)

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by jcommelin — APPROVED** [review]
Thanks :tada: 

If CI passes, please remove the label `awaiting-CI` and merge this yourself, by adding a comment `bors r+`.

bors d+

**Comment by urkud** [comment]
bors merge

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
