### PR TITLE
chore: delay import of Mathlib.Tactic.Common

### PR DESCRIPTION
**Pull request by kim-em**
This slightly delays the import of Mathlib.Tactic.Common.

---

- [x] depends on: #6970
- [x] depends on: #6956

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by jcommelin — APPROVED** [review]
Thanks :tada: 

If CI passes, please remove the label `awaiting-CI` and merge this yourself, by adding a comment `bors r+`.

bors d+

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
To avoid bors clashing all night, I've rolled this into #6977

**Pull request closed without merging**
