### PR TITLE
[Merged by Bors] - feat: port GroupTheory.Perm.Cycle.Type

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
@Ruben-VandeVelde, can you explain why you uncommented the code in Data.Int.GCD? Is it actually relevant to this PR?

**Comment by Ruben-VandeVelde** [comment]
It's used in the proof for `isThreeCycle_sq`

**Comment by semorrison** [comment]
Hmm, I'm not happy about reinstating all these lemmas inside the `NormNum` namespace, on the presumption that they are not actually going to be relevant to whatever replaces this `norm_num` functionality. Can you just inline that one lemma at the point of use? (Of course leaving the porting note about the regression.)

If you could open an issue about `norm_num` computing gcds, that would be helpful too.

**Comment by Ruben-VandeVelde** [comment]
> Hmm, I'm not happy about reinstating all these lemmas inside the `NormNum` namespace, on the presumption that they are not actually going to be relevant to whatever replaces this `norm_num` functionality. Can you just inline that one lemma at the point of use? (Of course leaving the porting note about the regression.)
> 
> If you could open an issue about `norm_num` computing gcds, that would be helpful too.

Done, thanks

**Pull request closed without merging**
