### PR TITLE
[Merged by Bors] - feat: use `ring_nf` on `ring1` error message

### PR DESCRIPTION
**Pull request by digama0**
Fixes the issue at https://github.com/leanprover-community/mathlib4/pull/605#issuecomment-1315580574.

### CODE REVIEW

**Comment by hrmacbeth** [comment]
Would you consider using sums-of-products rather than Horner in the error message, if the user hasn't specified a normalization?  I know it's inconsistent, but it's easier to read.

(This was the old behaviour, see https://github.com/leanprover-community/mathlib/pull/15319.)

**Comment by digama0** [comment]
@hrmacbeth The horner form is no longer supported. The new `ring` tactic is based on the old `ring_exp` which uses sum of products form internally, and I'm assuming that people don't actually find horner form easier to read than sum of products form so there isn't much point in implementing it just for `ring_nf`.

In other words, the error message uses sum of products form by default, and you no longer have to specify it with `ring_nf SOP` anymore.

**Comment by hrmacbeth** [comment]
OK, perfect!

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
