### PR TITLE
[Merged by Bors] - feat: port Data.Real.Cardinality

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by dupuisf — COMMENTED** [review]
Thanks!

bors r+

**Comment by dupuisf** [comment]
I have no idea why the build fails on CI, it works fine on my machine.

**Comment by Parcly-Taxel** [comment]
> I have no idea why the build fails on CI, it works fine on my machine.

It needs #3314 or similar to avoid the kernel panic.

**Pull request closed without merging**
