### PR TITLE
[Merged by Bors] - feat: port ModelTheory.Fraisse

### PR DESCRIPTION
**Pull request by GabinKolly**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4391
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4391~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by jcommelin** [comment]
One nasty error left. See also https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/ModelTheory.2EFraisse.20.234565

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Comment by jcommelin** [comment]
bors merge

**Pull request closed without merging**
