### PR TITLE
feat: relate lists and infinite sequences

### PR DESCRIPTION
**Pull request by sven-manthe**
Transfer basic API on lists (append, take etc) to infinite sequences.
Taken from https://github.com/sven-manthe/A-formalization-of-Borel-determinacy-in-Lean

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by vihdzp** [comment]
You might want to implement these operations on [Stream'](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Data/Stream/Defs.html#Stream') instead.

**Comment by sven-manthe** [comment]
Indeed, all definitions and most lemmas are already there for Stream'. I'm not sure how to use this in relation to my project (when I started, I also created a `def ... := ℕ → A` and was told that using `ℕ → A` directly would be more coherent with mathlib style. However, the existence of Stream' suggests that these operations should not be available for sequences). A rather extreme change for my project would be the following, would this be considered appropriate for mathlib?: Register a global TopologicalSpace instance on Stream' given by the product of the discrete topologies (even if the underlying type has a nondiscrete topology). Then define bodies of trees, hence payoff sets of Gale-Stewart games as sets of Stream', not of sequences. Finally, relate those to PiNat/CantorScheme using the homeomorphism `id`.

**Comment by vihdzp** [comment]
I think it'd make more sense to register the product topology on `Stream`, and separately, define a type alias (if it doesn't already exist) to give a type the discrete topology.

**Comment by sven-manthe** [comment]
I indeed switched to `Stream'` for my project and thus will PR more API on that (after a short discussion I decided to use a `scoped instance` for the product of the discrete topologies on `Stream'` to avoid the meaningless typeclass arguments throughout).

**Pull request closed without merging**
