### PR TITLE
[Merged by Bors] - feat: port Probability.StrongLaw

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
This PR completes the port of the **entire** `Probability` folder to mathlib4 – for real this time.

---

- [x] depends on: #5331

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5331
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors d+

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5331~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by Parcly-Taxel** [comment]
bors merge

**Pull request closed without merging**
