### PR TITLE
[Merged by Bors] - chore: remove useless `include` porting note

### PR DESCRIPTION
**Pull request by dagurtomas**
This one was added by myself and not removed in #10503.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
maintainer merge

**Comment by mattrobball** [comment]
Thanks! If CI is green, please summon the bot. 

bors delegate+

**Comment by mattrobball** [comment]
cf leanprover/lean4#2452

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
