### PR TITLE
test: precompileModules := true

### PR DESCRIPTION
**Pull request by JovanGerb**
I'm testing to see how `precompileModules := true` influences the build time

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by JovanGerb** [comment]
bench!

**Comment by alexb-harmonic** [comment]
I think you'll probably need to open this PR from a branch of the mathlib repo itself not a fork (ask on zulip if you need permission)

**Comment by alexb-harmonic** [comment]
!bench

**Comment by alexjbest** [comment]
I think you'll probably need to open this PR from a branch of the mathlib repo itself not a fork (ask on zulip if you need permission) and i think it's !bench anyway

**Comment by alexjbest** [comment]
!bench

**Comment by JovanGerb** [comment]
Should I interpret this result as saying that it failed because it used up too much memory?

**Comment by JovanGerb** [comment]
Oh, no it ran out of time, running for 4 hours

**Comment by alexjbest** [comment]
That is strange, I would still try this from a branch of mathlib itself just in case. Did you build locally?

**Comment by JovanGerb** [comment]
I tried building locally now. At first it seems to work fine, but it ends up with about 30 problematic files, for example `Mathlib.Algebra.Order.Monoid.Units`. Working in the file itself works, but importing the file gives this error:
```
info: [1351/1354] Building Mathlib.Algebra.Order.Monoid.Units
error: failed to execute `c:\Users\jovan\.elan\toolchains\leanprover--lean4---v4.7.0-rc2\bin\lean.exe`: unspecified system_category error (error code: 87)
```
`Mathlib.Algebra.Order.Monoid.Units` imports 3 other files. I found that removing all definitions from the file doesn't solve the problem, but removing any 1 of its 3 imports does solve the problem.

**Comment by grunweg** [comment]
Coming here from PR triage: can you comment on the status of this PR? Is this an experiment, basically not intended to land, or would you like this to get reviewed? In the latter case, please merge master. Thanks!

**Comment by JovanGerb** [comment]
It was just an experiment that failed.

**Pull request closed without merging**
