### PR TITLE
[Merged by Bors] - feat: Port/Combinatorics.Composition

### PR DESCRIPTION
**Pull request by arienmalec**
---

- [x] depends on: #2144

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by arienmalec** [comment]
Remaining issues:

- [ ] `disjoint_range` depends on `wlog` -- merge when `wlog` available
- [ ]  `mem_range_embedding_iff` has `change..at..` issues
- [ ]  Major `nthFoo` to `get` refactoring
- [ ]  remaining proof issues

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2144
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2144~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
