### PR TITLE
[Merged by Bors] - doc(Algebra/Group/Defs): add note on names `SMul`, `VAdd`; typo fix

### PR DESCRIPTION
**Pull request by bustercopley**
Edited module docstring:
* Fixed recent accidental damage
* Added a note about the motivation for the names `SMul` and `VAdd`
[Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/.60SMul.60.20and.20.60VAdd.60)

### CODE REVIEW

**Review by grunweg — APPROVED** [review]
Looks good to me (but I don't have approval rights).

I tweaked the PR description so your (useful!) comment will appear in the commit message.

**Review by YaelDillies — APPROVED** [review]
Thanks, looks good!

**Comment by kbuzzard** [comment]
My concern is that you are using "Euclidean space" in the way Euclid used it, which is apparently not the way it's used in mathlib. It looks like you should be talking about an additive torsor for a vector space,  rather than Euclidean space (which as Eric pointed out _does_ have a zero)

**Comment by bustercopley** [comment]
I changed the wording after discussion on Zulip, so just for the sake of honesty I (re-)requested reviews from @YaelDillies, @grunweg and @kbuzzard. Sorry for the trouble!

**Comment by kbuzzard** [comment]
I think removal of the ambiguous term makes it better. Now I think it reads a bit funny because you're not saying what the vector space is acting on but I don't want to cause any more fuss. 

I know you've said that you don't want to use the word "torsor" for some reason (despite the fact that there are plenty of technical words in other docstrings), but the other side of this coin would be: who do you have in mind who wants to use VAdd but doesn't know what a torsor is? But honestly I don't really mind what this docstring says so if a maintainer is happy to merge this as it stands then that's fine.

**Comment by bustercopley** [comment]
I didn't think it was really _about_ torsors, any more than `SMul` is. Maybe I'm misunderstanding.

In any case, "See the file `Module.AddTorsor` for a motivating example for the name `VAdd` (vector addition)" seems better all round, so I have made that change.

**Comment by kbuzzard** [comment]
Thanks for bearing with me!

**Comment by kbuzzard** [comment]
maintainer merge

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
