### PR TITLE
[Merged by Bors] - chore: golf `EReal` inductions

### PR DESCRIPTION
**Pull request by eric-wieser**
These are no longer needed after #13264

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by pitmonticone** [comment]
Oh, I'm sorry. I didn't know that. 

Thank you very much for your PR @eric-wieser.

**Review by pitmonticone — APPROVED** [review]
Oh, I'm sorry. I didn't know that. 

Thank you very much for your PR @eric-wieser.

**Review by grunweg — COMMENTED** [review]
Thanks!
maintainer merge

**Pull request closed without merging**
