### PR TITLE
[Merged by Bors] - feat: port LinearAlgebra.AffineSpace.MidpointZero

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ChrisHughes24** [comment]
Looks like there will be a merge conflict.

bors r-

**Comment by ChrisHughes24** [comment]
This can be merged after the other PR is in master and the conflict is fixed.

bors d+

**Comment by Parcly-Taxel** [comment]
bors merge

**Pull request closed without merging**
