### PR TITLE
[Merged by Bors] - feat: List.product

### PR DESCRIPTION
**Pull request by ammkrn**

### CODE REVIEW

**Comment by gebner** [comment]
LGTM, please follow the commit guidelines and rename the PR title to something like `feat: ...`.

bors d+

**Comment by ammkrn** [comment]
Changed. Are the commit guidelines just those of vanilla mathilb?

**Comment by gebner** [comment]
I think we are trying to use the same commit messages as in Lean 4 now.  So it's `feat: List.product` (instead of `feat(data/list): list.product` in mathlib 3).

You can now write `bors r+` to merge the PR yourself.

**Pull request closed without merging**
