### PR TITLE
[Merged by Bors] - feat: port Algebra.Category.Module.Abelian

### PR DESCRIPTION
**Pull request by joelriou**
---
- [x] depends on: #4052
- [x] depends on: #4297

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4052
* leanprover-community/mathlib4#4297
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by kbuzzard** [comment]
Very nice diff, great to see the autoporter doing so well on stuff like this. A shame to see those necessary changes `f.range` -> `LinearMap.range f` but there's nothing you can do about that. 

maintainer merge

(although I don't think this works yet)

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4052~~
* ~~leanprover-community/mathlib4#4297~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
