### PR TITLE
[Merged by Bors] - chore: forward-port leanprover-community/mathlib#18854

### PR DESCRIPTION
**Pull request by j-loreaux**
This forward-ports all the files from leanprover-community/mathlib#18854 which have already been ported, and it also ports the new file `algebra.star.order`, which is a split from `algebra.star.basic` and was necessary to do at the same time.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ChrisHughes24** [comment]
thanks

bors merge

**Comment by ChrisHughes24** [comment]
Didn't check the build

bors r-

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by eric-wieser** [comment]
Is there a reason you didn't use `start_port.sh` here?

**Pull request closed without merging**
