### PR TITLE
[Merged by Bors] - chore(Order/SuccPred/Limit): organize induction principles

### PR DESCRIPTION
**Pull request by vihdzp**
We put all of our induction principles at the end of the file, and standardize both argument order and naming. 

We also golf `PredOrder.limitRecOn` by defining it in terms of `SuccOrder.limitRecOn` on the dual order.

---

Preliminary cleanup before I introduce `IsSuccPrelimit`.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by YaelDillies** [comment]
I don't understand how this is better than before. Before, the induction principles were ordered according to the typeclasses they required, and integrated within the corresponding sections.

**Comment by vihdzp** [comment]
The main reasons for me doing this are that
a) it's now easier to see what hypotheses each individual projection lemma for a given induction principle requires (and in particular, it's easier to note that they don't all work under the same generality!)
b) we can now add more induction principles (i.e. the ones for the new `IsSuccOrder`) without cluttering the rest of the file

**Comment by YaelDillies** [comment]
What `IsSuccOrder`?

**Comment by vihdzp** [comment]
*`IsSuccLimit`. Basically I don't want induction with minimal elements taking up a bunch of space in the middle of the file.

**Comment by YaelDillies** [comment]
I guess that's justifiable by them being new definitions

maintainer merge

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
