### PR TITLE
[Merged by Bors] - chore: reduce imports in Mathlib.Algebra.Group.Int

### PR DESCRIPTION
**Pull request by adomani**
Found by `linter.minImports` (#14840).

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Are these transitive imports (since `declarations_diff` shows no diff)? In any case, maintainer delegate

**Comment by YaelDillies** [comment]
Yes, they are transitive imports

**Comment by grunweg** [comment]
If they un-confuse your linter, let's land this.
maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by mattrobball** [comment]
bors merge

**Comment by mattrobball** [comment]
Wait

bors r-

@adomani is this still `WIP`

**Comment by riccardobrasca** [comment]
bors d+

**Comment by adomani** [comment]
!bench

**Comment by adomani** [comment]
bors r+

I labeled it as `WIP`, since I imagine that, while debugging the `minImports` linter, I will come across more of these.  Eventually, I would like to trust the linter enough to just produce all these removals automatically, but for the moment, it is going to be a trickle!

**Pull request closed without merging**
