### PR TITLE
[Merged by Bors] - chore: Rename `nat_cast`/`int_cast`/`rat_cast` to `natCast`/`intCast`/`ratCast`

### PR DESCRIPTION
**Pull request by YaelDillies**
Now that I am defining `NNRat.cast`, I want a definitive answer to this naming issue. Plenty of lemmas in mathlib already use `natCast`/`intCast`/`ratCast` over `nat_cast`/`int_cast`/`rat_cast`, and this matches with the general expectation that underscore-separated name parts correspond to a single declaration.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
Let's solicit a few more votes on https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/naming.20conventions.3A.20natCast.20vs.20nat_cast/near/346323810 first.

**Comment by YaelDillies** [comment]
Seems like there's a majority in favour

**Review by Parcly-Taxel — APPROVED** [review]

**Comment by eric-wieser** [comment]
Please make a PR to update the naming guide to explicitly record this clarification to the naming convention; if we're going to make this sweeping a change, we should make sure it's documented as the preferred naming convention.

**Comment by YaelDillies** [comment]
https://github.com/leanprover-community/leanprover-community.github.io/pull/459

**Comment by semorrison** [comment]
bors d+

**Comment by YaelDillies** [comment]
bors merge

**Pull request closed without merging**
