### PR TITLE
[Merged by Bors] - feat: port RingTheory.Kaehler

### PR DESCRIPTION
**Pull request by int-y1**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by xroblot** [comment]
I am working on this PR for a bit

**Comment by xroblot** [comment]
I have pushed some fixes but there are still some timeouts that I could not fix

**Comment by jcommelin** [comment]
@chabulhwi If you assigned this to yourself, does that mean you "adopt" it? If so, please remove the label.

**Comment by chabulhwi** [comment]
> @chabulhwi If you assigned this to yourself, does that mean you "adopt" it? If so, please remove the label.

I'm not so sure if I'll be able to fix the errors in this file, but I'll remove the "please-adopt" label for now.

**Comment by kbuzzard** [comment]
I asked about the local notation issue [here](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/no.20macro.20or.20.60.5Bquot_precheck.5D.60.20instance.20for.20syntax.20kind/near/373037339).

**Comment by xroblot** [comment]
I think there are no more errors in that file but I have to go now so someone can take over and complete this file for review

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
