### PR TITLE
[Merged by Bors] - fix: allow typeclass failures in exact?

### PR DESCRIPTION
**Pull request by kim-em**
As requested on [zulip](https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/.E2.9C.94.20tsum.20and.20HasSum/near/378162082).

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alexjbest** [comment]
What would stop `exact?` just matching and returning on something like `IsEmpty.Elim` right now for everything?

**Comment by eric-wieser** [comment]
I'm not sure that's much different to how it could return `Iff.mp ?_ ?_` for everything right now

**Review by eric-wieser — APPROVED** [review]

**Comment by alexjbest** [comment]
I'm worried about exact not apply, as far as I know that doesn't return iff.mp does it?

**Comment by eric-wieser** [comment]
Ah, I see your point now. Yes, I'd expect this to fail in `exact?` but succeed in `apply?`

**Comment by semorrison** [comment]
I'm confused, why would there be a problem in `exact?`? A lemma like `IsEmpty.Elim` will now successfully apply (so `apply?` will list it) but then the `IsEmpty` typeclass becomes a sub-goal, which, if it can't be discharged by `solve_by_elim`, will prevent `exact?` from reporting it.

**Comment by alexjbest** [comment]
maintainer merge

**Pull request closed without merging**
