### PR TITLE
[Merged by Bors] - feat: port algebra.abs

### PR DESCRIPTION
**Pull request by PatrickMassot**
Note that `mathport` completely dropped the line ``notation `|`a`|` := abs a`` in https://github.com/leanprover-community/mathlib3port/blob/5a66d9b4aff2f94aabca7f3daead2a383d7f2117/Mathbin/Algebra/Abs.lean.

### CODE REVIEW

**Comment by gebner** [comment]
See #307

**Comment by PatrickMassot** [comment]
I changed the notation following a suggestion by Sebastian. I also force pushed to make sure the first commit is the result of mathport, as suggested by Heather.

**Comment by gebner** [comment]
This is an interesting choice!

bors r+

**Comment by semorrison** [comment]
I've have added the FROZEN warning to algebra.abs in mathlib#17039.

**Pull request closed without merging**
