### PR TITLE
[Merged by Bors] - feat(Topology/ENNReal): add `finset_sum_iSup`

### PR DESCRIPTION
**Pull request by urkud**
Moves:
- finset_sum_iSup_nat -> finsetSum_iSup_of_monotone

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by YaelDillies** [comment]
If you could take the opportunity to fix the `finset_sum` to `finsetSum` (in accordance with the naming convention), that would be great.

**Comment by urkud** [comment]
> If you could take the opportunity to fix the `finset_sum` to `finsetSum` (in accordance with the naming convention), that would be great.

Done

**Review by YaelDillies — APPROVED** [review]
Thanks!

maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
