### PR TITLE
[Merged by Bors] - perf: improve some instances in Finsupp

### PR DESCRIPTION
**Pull request by ChrisHughes24**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ChrisHughes24** [comment]
!bench

**Review by mattrobball — COMMENTED** [review]
I think the actual changes to the code are straightforward and it would benefit everyone to have them in sooner rather than later. 

What would think about moving all the applications of comments from #7432 to #7432? Here and in the other PRs. That PR might take more discussion to sharpen.

**Comment by ChrisHughes24** [comment]
I don't understand what you want me to do about the comments

**Comment by mattrobball** [comment]
Sorry for being obtuse. I'm just saying move the comments involving the library note to the library note PR itself. For this and the others. 

I think we are still working out best practices for that note and don't think this should be held up by that process.

**Comment by mattrobball** [comment]
bors d+ 

Thanks!

**Pull request closed without merging**
