### PR TITLE
[Merged by Bors] - chore(VitaliFamily): rename `α` → `X`

### PR DESCRIPTION
**Pull request by urkud**
The module docstring uses `X` while the code used `α`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Thank you for doing this. Prior to this PR, `x` was often used as an element of \alpha - this notation is much better!
I have one follow-up question: this file now uses `x : X`, and `a` if there's another variable in `X`. Would you like to rename that one as well? (Apart from that, it's good to go!)

**Comment by urkud** [comment]
> Thank you for doing this. Prior to this PR, `x` was often used as an element of \alpha - this notation is much better! I have one follow-up question: this file now uses `x : X`, and `a` if there's another variable in `X`. Would you like to rename that one as well? (Apart from that, it's good to go!)

`a` was used for variables of type `Set X`. This doesn't follow our naming convention, so renamed to `s` or `t`.

**Comment by grunweg** [comment]
Thanks, looks good to me now.
maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
