### PR TITLE
[Merged by Bors] - fix: `shake` bug, improve noshake.json generation

### PR DESCRIPTION
**Pull request by digama0**
- [ ] depends on: #9830

This is the `noshake.json` file corresponding to the edits in leanprover/std4#533. There was a small bug in `shake` making it much more conservative than it needed to be, so there is a big mathlib PR #9830, on which this PR depends because CI will not pass without it.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
I had idly wondered (in light of e.g. #9559 or other drive-by import minimisation) if there was such a bug. This is great news, I look forward to the actual adjusting PR!

**Comment by sgouezel** [comment]
What about merging master, fixing the conflict, and then sending this one to bors (it has already been approved by Scott)? I expect the longer you wait, the more painful it will get.

**Comment by semorrison** [comment]
I've merged master and fixed the conflict, re-minimising imports there by hand.

bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
