### PR TITLE
[Merged by Bors] - chore: move some benchmarking files over from Kha/mathlib4-bench

### PR DESCRIPTION
**Pull request by Kha**
This allows us to customize the benchmarking metrics in this repo

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Kha** [comment]
!bench

**Comment by semorrison** [comment]
(Just a reminder that on the mathlib4 repo, if authors don't self-label with `awaiting-review`, PRs don't appear on the [#queue](https://github.com/leanprover-community/mathlib4/pulls?q=is:open+label:awaiting-review+sort:updated-asc+-label:blocked-by-other-PR+-label:merge-conflict+-status:failure+-label:awaiting-CI) and might never be noticed. :-)

**Comment by semorrison** [comment]
bors merge

**Comment by Kha** [comment]
> (Just a reminder that on the mathlib4 repo, if authors don't self-label with `awaiting-review`, PRs don't appear on the [#queue](https://github.com/leanprover-community/mathlib4/pulls?q=is:open+label:awaiting-review+sort:updated-asc+-label:blocked-by-other-PR+-label:merge-conflict+-status:failure+-label:awaiting-CI) and might never be noticed. :-)

Yeah, I assumed it would make more sense to mention specific people on such a specific PR but was still waiting for #5994 to pass first

**Pull request closed without merging**
