### PR TITLE
feat(Data/Subtype): port data/subtype.lean from mathlib3

### PR DESCRIPTION
**Pull request by dwrensha**
Ports all of the items from mathlib3's data/subtype.lean and adds `theorem heq_iff_eq` in Data/Logic/Basic.lean.

### CODE REVIEW

**Comment by gebner** [comment]
Thanks!  BTW, I'm not sure if you saw Mario's talk at FMM.  But we're most likely replacing all of the manually ported files here by automatically ported ones later this year (using a tool like https://github.com/dselsam/mathport/).

If you're doing it just for fun or to learn Lean 4 or because you need the files for another project, then please by all means continue.  But please be aware that we're probably going to delete everything here (except for the tactics).

**Comment by dwrensha** [comment]
Yes, I am aware that the plan is to use automation to port everything. I'm still motivated to work on manual porting things because:
  1. it's fun and educational,
  2. I'm impatient to start building mathlib-dependent things in Lean 4, and
  3. I'm not 100% confident that the automated porting effort will fully succeed, so it seems prudent to not put all of our eggs in that basket.

**Comment by digama0** [comment]
@dwrensha By the way, I'll say what I said in that talk as well: If you are doing manual porting, I want you to pay particular attention to things that can't be done as easily in lean 4 or need a workaround, and post them as issues on the https://github.com/dselsam/mathport/ repo. This is one of the most important things we need to learn at this stage in order to make sure porting goes smoothly.

**Comment by dwrensha** [comment]
I've been leaving notes in the ported code where things are not completely straightforward, e.g. https://github.com/leanprover-community/mathlib4/blob/7822926636f86c197bf3b9d14b4ad3b4a34701a1/Mathlib/Data/Subtype.lean#L138

I don't think I have a good enough understanding of mathport to be able to translate these notes into issues to open there.

**Pull request merged**
