### PR TITLE
[Merged by Bors] - chore: refactor of library_search, and don't timeout

### PR DESCRIPTION
**Pull request by kim-em**
This is a refactor of `library_search`, separating the logic of applying lemmas and flow control (i.e. stopping if we find a good one).

This version has an intermediate function that returns a lazy list of candidate results, using the new `ListM` API.

As an easy add-on, we make sure `library_search` never times out --- it watches the clock, and if it reaches 90% of available time it returns what it has so far.

After this refactor it will also be somewhat easier to improve the way results are returned when `library_search` doesn't close the goal. e.g. we should do some basic sorting to put more promising answers first.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alexjbest** [comment]
Really cool! Is there a visual sign for the end user that library search gave up rather than timeout (vs tried everything and reverted to suggest-like Behavioural). As a user it would be potentially helpful to know if maybe one should try again with a bigger timeout when willing to wait.

**Comment by semorrison** [comment]
> Really cool! Is there a visual sign for the end user that library search gave up rather than timeout (vs tried everything and reverted to suggest-like Behavioural). As a user it would be potentially helpful to know if maybe one should try again with a bigger timeout when willing to wait.

Good point. I will think about how to handle this.

**Comment by semorrison** [comment]
Okay, I now log a message suggesting increasing `maxHeartbeats` if we ran out of time.

**Comment by fpvandoorn** [comment]
LGTM

bors merge

**Pull request closed without merging**
