### PR TITLE
[Merged by Bors] - chore: Move `positivity` extensions

### PR DESCRIPTION
**Pull request by YaelDillies**
The goal here is to have access to `positivity` earlier in the import hierarchy

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
AFAIR, @semorrison removed some dependencies on `positivity` in a recent PR. Please coordinate.

**Comment by YaelDillies** [comment]
You're thinking of #9924. The current PR already builds on top of that one.

**Comment by semorrison** [comment]
bors d+

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
(Sorry, intended to merge the first time, fingers just remembered `d+` instead of `r+`.)

**Comment by YaelDillies** [comment]
bors merge

**Pull request closed without merging**
