### PR TITLE
[Merged by Bors] - feat: topology on `ℕ+`(`PNat`)

### PR DESCRIPTION
**Pull request by Komyyy**
---

This PR consists [Continued fractions makes an isomorphism between irrationals and baire space
](https://github.com/users/Komyyy/projects/3/) project

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Comment by Komyyy** [comment]
@urkud Sorry, this PR is causing build failure, I'm fixing this.

**Comment by Komyyy** [comment]
@urkud I have fixed!

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Pull request closed without merging**
