### PR TITLE
[Merged by Bors] - chore: create `Analysis.CstarAlgebra` folder

### PR DESCRIPTION
**Pull request by j-loreaux**
---

part of my organization of `Analysis.NormedSpace`

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Can you fix the build, please? Thanks!

**Comment by j-loreaux** [comment]
sorry, was in a meeting. I think it will build this time.

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
