### PR TITLE
fix: more instance priority changes

### PR DESCRIPTION
**Pull request by kbuzzard**
Pushing Floris' idea from #5941 a bit further.

The basic explanation is [here on Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/changing.20algebra.20instance.20priorities/near/374996945)

The Lean 4 issue is [#2325 ](https://github.com/leanprover/lean4/issues/2325)

The changes in this PR are right at the bottom of the algebra instance hierarchy.

These speedups are unrelated to the `with` issue which is currently actively making other files faster. This is an attempt to make the "default routes" better. Note however that one cannot always force Lean to go down the default routes because it might need to apply a lemma which is only valid for the structure on a non-default route.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by kbuzzard** [comment]
I cannot reproduce the linter issue locally.

**Comment by kbuzzard** [comment]
!bench

**Comment by kbuzzard** [comment]
!bench

**Comment by kbuzzard** [comment]
!bench

**Comment by kbuzzard** [comment]
No idea.

**Comment by kbuzzard** [comment]
Maybe [this](http://speedcenter.informatik.kit.edu/mathlib4/compare/b909cd9c-59ad-4242-9bac-4ef6e2443a6a/to/e7b27246-a3e6-496a-b552-ff4b45c7236e?hash2=4c08f67beff537595da0352e30160dea85f332ba) is the comparison between this PR and #5941 . So maxrss didn't go down any more.

**Comment by Kha** [comment]
> Why isn't it comparing to `master`?

http://speedcenter.informatik.kit.edu/mathlib4/run-detail/e7b27246-a3e6-496a-b552-ff4b45c7236e/f3dd5c320d6039ddbc829e869d918f8c1fd24920 was benchmarked only after this run

**Comment by jcommelin** [comment]
!bench

**Comment by kbuzzard** [comment]
!bench

**Comment by kbuzzard** [comment]
!bench

**Comment by kbuzzard** [comment]
!bench

**Comment by kbuzzard** [comment]
!bench

**Comment by Vierkantor** [comment]
The `CancelMonoid` changes seem like they do the same as, and therefore cause merge conflicts with, #6145.

**Pull request closed without merging**
