### PR TITLE
[Merged by Bors] - feat: port CategoryTheory.Grothendieck

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
What remains are two simp normal form linter errors:
```
#check @CategoryTheory.Grothendieck.grothendieckTypeToCatInverse_map_fiber_down_down /- Left-hand side does not simplify, when using the simp lemma on itself.
This usually means that it will never apply.
 -/
#check @CategoryTheory.Grothendieck.grothendieckTypeToCat_inverse_map_fiber_down_down /- Left-hand side does not simplify, when using the simp lemma on itself.
This usually means that it will never apply.
```

**Comment by Parcly-Taxel** [comment]
> What remains are two simp normal form linter errors:

Just `nolint simpNF` them away like I did at #2969.

**Comment by mo271** [comment]
> #check @CategoryTheory.Grothendieck.grothendieckTypeToCatInverse_map_fiber_down_down /- Left-hand side does not simplify, when using the simp lemma on itself.
> This usually means that it will never apply.

The file you linked to does not contain `nolint simpNF`

**Comment by Parcly-Taxel** [comment]
> Removing the `simps!`, but I'm unsure if this is the correct way of proceding here.

I pushed a more targeted fix that keeps the `simps!`, just `simpNF`ing the two problematic defs.

**Comment by semorrison** [comment]
Please don't merge this PR until I've had a chance to take a closer look at this and the simpNF nolints in https://github.com/leanprover-community/mathlib4/pull/2969. Apologies if it takes a few days for me to get there.

**Comment by semorrison** [comment]
Ok, I've looked at the lemma flagged by simpNF. It was incorrect, because it was a lemma equating two proofs of a proposition. Ideally `simps` would just recognise this by itself. For now, I just removed the lemma.

@Parcly-Taxel, can you please not use `nolint` unless you are certain it is the correct solution -- it wasn't here.

**Comment by semorrison** [comment]
I've asked @fpvandoorn on [zulip](https://leanprover.zulipchat.com/#narrow/stream/144837-PR-reviews/topic/!4.233204.20simps.20bug.20.28Grothendieck.20construction.29) about this.

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
