### PR TITLE
[Merged by Bors] - chore: remove unused lemmas about bit0/1

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
Deletions:
- bit0_mul
- mul_bit0
- bit1_mul
- mul_bit1
- Polynomial.natDegree_bit0
- Polynomial.natDegree_bit1
- Polynomial.bit0_comp
- Polynomial.bit1_comp

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Looks reasonable, thanks!
maintainer merge

**Comment by grunweg** [comment]
Actually: #14644 makes a different choice on some of these lemmas, and rewrites them instead. I haven't weighed that *very* carefully. Some of the later lemmas certainly *do* exist in non-bit0/1 form already.

**Comment by jcommelin** [comment]
Let's wait for #14745 to land first, and then merge master into this PR.

**Comment by grunweg** [comment]
#14745 has landed: marking as awaiting-author

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
