### PR TITLE
[Merged by Bors] - refactor: Rename instances in `Data.Fintype.Basic`

### PR DESCRIPTION
**Pull request by Komyyy**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by Parcly-Taxel** [comment]
@Komyyy the build for this PR is repeatedly failing in bors because of simpNF errors, you should probably fix this first.

**Comment by Komyyy** [comment]
@Parcly-Taxel I built on this branch, ran `./build/bin/runLinter` and it passed linting.

**Comment by Parcly-Taxel** [comment]
> @Parcly-Taxel I built on this branch, ran `./build/bin/runLinter` and it passed linting.

From [Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/!4.232798.20simpNF/near/341141763):

>The errors all relate to the `CategoryTheory.Preadditive.AdditiveFunctor` port that was pushed a mere hour ago. Perhaps the "ripple effect" changes from `Data.Fintype.Basic` need to be extended to that file

**Comment by Komyyy** [comment]
The previous linting didn't reflect `CategoryTheory.Preadditive.AdditiveFunctor`, sorry. I'm building to lint now.

**Comment by Komyyy** [comment]
It passed linting. Maybe the linter depends on a machine.

**Comment by ChrisHughes24** [comment]
I don't think it was this PR causing problems

bors r+

**Pull request closed without merging**
