### PR TITLE
refactor: families of arrows instead of presieves

### PR DESCRIPTION
**Pull request by dagurtomas**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by b-mehta** [comment]
Is there a reason to prefer families over presieves? Or conversely, do you think we should replace presieves entirely with families?

**Comment by dagurtomas** [comment]
I'm going to start by experimenting with refactoring `IsSheafFor` for families. It seems to me after working on #7949 and #8443 that the "arrows" sheaf condition is easier to work with. I don't think we should replace `Presieve` entirely by families, it seems useful in the definition of coverage etc. and as somehow the underlying structure of a sieve.

**Comment by joelriou** [comment]
@b-mehta: I see two reasons for promoting families of arrows over presieves.
- It seems that "presieve" is a mathlib-specific notion.
- The formulation of the sheaf condition is nice for sieves and for families of arrows, but for presieves it can be very ackward as we experienced it in previous PRs by @dagurtomas. I suggested developing the sheaf condition for families of arrows, and the code is much nicer now.

We may keep `Presieve` because I anticipe it would be painful to refactor the definition of Grothendieck *pretopologies* using only families of arrows rather than presieves (e.g. stating an equality of presieves is kind of ok, but I am not sure we want to state that families of arrows are equal, or that a family of arrows belongs to a `Set` of families of arrows).

**Comment by b-mehta** [comment]
I'm happy to have families of arrows too - but I'm not so sure what you mean by the sheaf condition being nicer for sieves than presieves. I wrote the definition of presieves for mathlib specifically for the sheaf condition! :)

**Comment by dagurtomas** [comment]
Certainly the sheaf condition is nicest in the form "every matching family has a unique amalgamation" for families of arrows, and in the form `YonedaSheafCondition` for sieves (there you have to use sieves, of course). Maybe that's what @joelriou meant?

**Comment by b-mehta** [comment]
But we have "every compatible family has a unique amalgamation" for presieves already! Perhaps there's some subtlety here that I'm missing. My recollection from a few years ago was that the way mathlib has these things set up is more convenient for both doing things with the regular topology and generalising to Lawvere-Tierney topologies. In particular, I experimented with families of arrows when figuring out the original sheaf API and found that it made many proofs longer in comparison to working with presieves. So I suppose my question is, are there specific examples of proofs that you think families of arrows make simpler, and could I try writing them with presieves instead?

**Pull request closed without merging**
