### PR TITLE
refactor(SetTheory/Ordinal/Arithmetic): deprecate `Ordinal.iSup_le`

### PR DESCRIPTION
**Pull request by vihdzp**
Unlike the other basic `iSup` theorems in the `Ordinal` namespace, this one doesn't require any `Small` assumptions, so it's completely equivalent to `ciSup_le'`.

---

There's the argument to be made that having this lemma is good for discoverability. That being said, I think this deprecation is a good move towards bringing the ordinal supremum API closer to the general supermum API.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by YaelDillies — COMMENTED** [review]
What proportion of the iSip/iInf API do you think will be generalised like this vs special-cased to `Ordinal`?

**Comment by vihdzp** [comment]
I only really see two categories of inf/sup theorems that make sense to specialize:

- Theorems that can be simplified by a `Small` hypothesis.
- Theorems that are written in terms of `0` rather than `⊥`

Everything else is just redundant.

**Comment by YaelDillies** [comment]
Is that not making up most of the lemmas? There's not much to say about conditional suprema/infima of possibly unbounded sets.

**Comment by vihdzp** [comment]
Well, at the moment there's a lot of bloat from `bsup` and `lsub` and all those other things I haven't deprecated.

Besides that, there are in fact still a bunch of theorems stated for `Ordinal` that could be generalized to conditionally complete lattices - those are the ones we marked with TODOs in the `sup` refactor.

**Comment by YaelDillies** [comment]
Sorry, I'm not convinced this PR is worth merging

**Comment by vihdzp** [comment]
Eh, it's alright. I wasn't too sure this would be an improvement.

**Pull request closed without merging**
