### PR TITLE
[Merged by Bors] - chore: fix grammar mistakes

### PR DESCRIPTION
**Pull request by int-y1**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alexjbest** [comment]
Did you use a script or something to find these? It might be helpful to record how you found all these for future reference.

**Comment by alexjbest** [comment]
maintainer merge

**Comment by int-y1** [comment]
My script went like this:

* Get all the comments in every file.
* Find the top 50 words. e.g. "a" and "be" are in the top 50.
* List the most uncommon word pairs. e.g. in "This seems to a be a problem", the word pair "a be" is uncommon.

Afterwards, I went over the list and fixed most of the grammar mistakes.

**Pull request closed without merging**
