### PR TITLE
[Merged by Bors] - feat: the (covariant) long exact sequence of Ext

### PR DESCRIPTION
**Pull request by joelriou**
We obtain the long exact sequence of `Ext`-groups `Ext X S.X₁ n₀ → Ext X S.X₂ n₀ → Ext X S.X₃ n₀ → Ext X S.X₁ n₁ → Ext X S.X₂ n₁ → Ext X S.X₃ n₁` when `n₀ + 1 = n₁` and `S` is a short exact short complex in an abelian category.

---

- [x] depends on: #14496
- [x] depends on: #14520
- [x] depends on: #14793 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by dagurtomas** [comment]
As I understand it, the lemmas `covariant_sequence_exact₁'` etc. are just auxiliary lemmas for the unprimed versions? Should they maybe be private or in an auxiliary namespace?

**Comment by joelriou** [comment]
> As I understand it, the lemmas `covariant_sequence_exact₁'` etc. are just auxiliary lemmas for the unprimed versions? Should they maybe be private or in an auxiliary namespace?

I considers these as alternative formulations: I would keep both in the same namespace, as it is.

**Comment by dagurtomas** [comment]
Sorry for the delay!

maintainer merge

**Comment by riccardobrasca** [comment]
This is great, thanks!

bors merge

**Comment by dagurtomas** [comment]
It was the linter for primed lemma names complaining. I've merged master and added docstrings "alternative formulation of ..." to them, are you happy with this @joelriou? Are these docstrings good enough to justify the primed names?

**Comment by joelriou** [comment]
> It was the linter for primed lemma names complaining. I've merged master and added docstrings "alternative formulation of ..." to them, are you happy with this @joelriou? Are these docstrings good enough to justify the primed names?

Thanks! This is good to me.

**Comment by riccardobrasca** [comment]
bors merge

**Pull request closed without merging**
