### PR TITLE
[Merged by Bors] - feat: port RingTheory.Filtration

### PR DESCRIPTION
**Pull request by int-y1**
---

todo:

* [x] `submodule_span_single` simp is timing out
* [x] `submodule_eq_span_le_iff_stable_ge` sorry
* [x] `submodule_fg_iff_stable` sorry

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by xroblot** [comment]
Pushed a fixed to `submodule_span_single`

**Comment by xroblot** [comment]
Pushed a fix of `submodule_eq_span_le_iff_stable_ge` (not very nice but it works)

**Comment by xroblot** [comment]
Pushed a fix of `submodule_fg_iff_stable` (the same trick works here too)

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
