### PR TITLE
[Merged by Bors] - feat: port ZFC set intersection

### PR DESCRIPTION
**Pull request by vihdzp**
Also fixes some erroneous theorem names from the port.

[`set_theory.zfc.basic`@`98bbc3526516bca903bff09ea10c4206bf079e6b`..`f0b3759a8ef0bd8239ecdaa5e1089add5feebe1a`](https://leanprover-community.github.io/mathlib-port-status/file/set_theory/zfc/basic?range=98bbc3526516bca903bff09ea10c4206bf079e6b..f0b3759a8ef0bd8239ecdaa5e1089add5feebe1a)

Mathlib 3: https://github.com/leanprover-community/mathlib/pull/18232

---

- [x] depends on: https://github.com/leanprover-community/mathlib/pull/18773

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib#18773
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib#18773~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by YaelDillies — APPROVED** [review]
This forward-port is a bit of a mess because bits of https://github.com/leanprover-community/mathlib/pull/18232 were already ported, and this forward-port fixes a few names and wrapping, but I've now checked both resulting files by hand and can safely say they match.

maintainer merge

**Pull request closed without merging**
