### PR TITLE
[Merged by Bors] - chore: try again with new contributor label

### PR DESCRIPTION
**Pull request by kim-em**
Add the `new-contributor` label if there are at most 5 exisiting PRs by this author. Also adds a CI status line "New Contributor Check (push) — Found n PRs by this author." regardless.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
Scott, thank you!  And thanks for the vote of confidence of being able to check this PR!

I do not really understand why the checks for permissions are there: it seems to work and this is great!

Also, I think that before the logic was to add the label by checking against closed PRs, while now it is checking open PRs.  Thus, your PR got labelled with the limit of 50, even though you have over 800.  In particular, if 22 of your PRs got closed immediately, then your next one would be labeled as `new-contributor`!

Having said that, I am happy to have the bot erroneously label as new contributors someone who has very few open PRs.  If it becomes annoying, we can always change the logic afterwards!

maintainer-merge

**Comment by adomani** [comment]
maintainer merge

**Comment by semorrison** [comment]
@adomani, I think that actually what's happening is there is a limit of 30 results in the query, and it is in fact returning all PRs, whether open or closed. In particular I only have 26 open PRs, so the fact that the status line reports that I have 30 means it is seeing more than the open ones (I hope).

Perhaps we could make this clearer by adding:
* an explicit upper bound for the number of results in the query, and/or
* detecting if there are exactly 30 results, and in that case having the status line say "Found \ge 30 PRs ...".

**Comment by adomani** [comment]
I looked for the status report, but could not find it, even though I see that it should print the relevant number.

Anyway, I probably prefer to merge this as is and see how it works "in the wild".  I think that it is good automation if the bot adds the label to new contributors.  If sometimes the label gets added to a not-too-new contributor, then we can amend.

**Comment by semorrison** [comment]
> I looked for the status report, but could not find it, even though I see that it should print the relevant number.
> 
> Anyway, I probably prefer to merge this as is and see how it works "in the wild". I think that it is good automation if the bot adds the label to new contributors. If sometimes the label gets added to a not-too-new contributor, then we can amend.

The status is in the CI results:

Untitled

**Comment by jcommelin** [comment]
bors d=adomani

**Comment by adomani** [comment]
> > I looked for the status report, but could not find it, even though I see that it should print the relevant number.
> > Anyway, I probably prefer to merge this as is and see how it works "in the wild". I think that it is good automation if the bot adds the label to new contributors. If sometimes the label gets added to a not-too-new contributor, then we can amend.
> 
> The status is in the CI results:
> Untitled

I had no idea that this message was accessible, so I did not even think of looking there!

**Comment by adomani** [comment]
Thanks!  Let's see how this performs and then fine-tune later, if needed!

bors r+

**Pull request closed without merging**
