### PR TITLE
[Merged by Bors] - feat: more `bound` lemmas

### PR DESCRIPTION
**Pull request by YaelDillies**
From LeanAPAP

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
bors d=girving

**Comment by girving** [comment]
These are great, thank you! `one_lt_mul` is exactly the right kind of use case for a branching bound lemma.

**Comment by YaelDillies** [comment]
> `one_lt_mul` is exactly the right kind of use case for a branching bound lemma.

Amazing! I wasn't sure I had understood

**Pull request closed without merging**
