### PR TITLE
[Merged by Bors] - feat: port Analysis.Calculus.Fderiv.Bilinear

### PR DESCRIPTION
**Pull request by urkud**
Also golf/extend theorems about bounded bilinear maps and rewrite the proof using the fact that the derivative of a bilinear map is a continuous bilinear map.

---

- [x] depends on: #4239

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4239
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by eric-wieser** [comment]
> Also golf/extend theorems about bounded bilinear maps

Why are we doing this during porting?

**Comment by urkud** [comment]
It was easier for me to rewrite the proof than to fix it. Also, why not? My modifications are backwards compatible.

**Review by fpvandoorn — APPROVED** [review]
The new file looks good

bors d+

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4239~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
