### PR TITLE
[Merged by Bors] - chore: move files into new `Analysis.Normed.Module`

### PR DESCRIPTION
**Pull request by j-loreaux**
---

part of my organization of `Analysis.NormedSpace`

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by riccardobrasca** [comment]
Sorry, I didn't notice your message on Zulip. LGTM, thanks!

bors d+

**Comment by j-loreaux** [comment]
bors merge

**Pull request closed without merging**
