### PR TITLE
[Merged by Bors] - feat: uniqueness of Haar measure in general locally compact groups

### PR DESCRIPTION
**Pull request by sgouezel**
We prove that two regular Haar measures in a locally compact group coincide up to scalar multiplication, and the same thing for inner regular Haar measures. This is implemented in a new file `MeasureTheory.Measure.Haar.Unique`. A few results that used to be in the `MeasureTheory.Measure.Haar.Basic` are moved to this file (and extended) so several imports have to be changed.

---

- [x] depends on: #8123
- [x] depends on: #8124
- [x] depends on: #8251
- [x] depends on: #8286 

Unfortunately, I don't see anything that can be split off the current PR. It's one big file `MeasureTheory.Measure.Haar.Unique`, plus the necessary adaptations to the other files.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by RemyDegenne** [comment]
This depends on #8251 and should not be labelled `awaiting-review` for now, right?

**Comment by hrmacbeth** [comment]
I have a completely surface-level question, having read the statements but not the proofs: is it possible to use `lintegral` rather than `integral` thoughout the `Uniqueness` file, thus downgrading the imports?

**Comment by sgouezel** [comment]
That's a good question. I have been careful to put that in a new file to avoid polluting more basic files with advanced imports, and normally the files that import this one should be pretty advanced so it shouldn't make a difference, but still.

The basic thing is integrating continuous functions with compact support, so the integral is naturally real-valued. My guess is that it's probably possible to cook up a version using lintegral instead of integral. I'm not sure it would be mathematically more natural, though. One mathematically subtle point is that I need Fubini for compactly supported functions and non-sigma-finite measures, which I have only implemented for integral, not lintegral.

**Comment by RemyDegenne** [comment]
Well that was a big one. But it looks great. Thanks!
bors r+

**Pull request closed without merging**
