### PR TITLE
[Merged by Bors] - feat: port CategoryTheory.Groupoid.VertexGroup

### PR DESCRIPTION
**Pull request by mo271**
- [x] depends on: #2883
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
Two things not working:

- [ ] the `[simps]` before ` vertexGroup` is giving weird error: `Failed to find constructor nvMonoid in structure Div.`
- [ ] in a failing simp in `vertexGroupIsomOfMap`, what is the correct way to port `vertex_group_mul`, i.e. how to access the `mul` of `vertexGroup`?

**Comment by mo271** [comment]
slightly weird that the linter suggested to use the name
`CategoryTheory.Groupoid.CategoryTheory.Functor.mapVertexGroup`, which does not seem rignt: please double check...

**Comment by mo271** [comment]
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/failing.20.60simps.60

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2883
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2883~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
