### PR TITLE
feat: StrictOrderedCommMonoids

### PR DESCRIPTION
**Pull request by madvorak**
---

Partially related to:
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/BigOperators.20theorems.20for.20Multiset

Tangentially related to:
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/OrderedCancelCommMonoid.20extends

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by YaelDillies — COMMENTED** [review]
This is just `OrderedCancelCommMonoid` all over again, right?

**Comment by madvorak** [comment]
I am not sure. I thought `StrictOrderedCommMonoids` was supposed to be weaker than `OrderedCancelCommMonoid` but cannot think of any justification now.

**Comment by YaelDillies** [comment]
It is weaker, but I doubt we care about the ones which are strict but not cancellative.

**Comment by madvorak** [comment]
I found a few examples that are `StrictOrderedCommMonoid` but not `OrderedCancelCommMonoid` but it is possible we don't care about any of them.

**Comment by fpvandoorn** [comment]
!bench

**Comment by fpvandoorn** [comment]
The benchmark results seem fine. Personally I think we should only add this if we soon actually want to commit an example of a StrictOrderedCommMonoid to mathlib that is not an OrderedCancelCommMonoid

**Comment by madvorak** [comment]
> The benchmark results seem fine. Personally I think we should only add this if we soon actually want to commit an example of a StrictOrderedCommMonoid to mathlib that is not an OrderedCancelCommMonoid

I don't have such plans.

**Pull request closed without merging**
