### PR TITLE
[Merged by Bors] - chore:  bump to nightly-2023-06-10

### PR DESCRIPTION
**Pull request by kim-em**
The bumps to nightly-2023-06-10, which includes @gebner's https://github.com/leanprover/lean4/pull/2266.

After this is merged I encourage everyone to look around at simp regressions!

- [x] depends on: #4954 (I've moved changes that work without lean4#2266 to this PR)

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4954
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4954~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by fpvandoorn** [comment]
Please update commit message and fix build failure

bors d+

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
