### PR TITLE
[Merged by Bors] - feat: the line derivative is measurable

### PR DESCRIPTION
**Pull request by sgouezel**
Last prerequisite for Rademacher theorem in #7003.

Along the way, we weaken the second-countability assumptions for strong measurability of the derivative and the right derivative.

---

- [x] depends on: #7115 
- [x] depends on: #7117

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
Please explain in the docstring why do we need `f` to be continuous (I guess, otherwise one can put different functions along different parallel lines, some are differentiable, some aren't).
Also, is it measurable as a function of the pair `(x, v)`?
bors d+

**Comment by sgouezel** [comment]
It is indeed measurable as a function of `(x, v)`, and this follows from the same argument applied to the function on `(E x E) x k` mapping `(x, v, t)` to `f (x + tv)`. I have added this to the file. Unfortunately, to get somewhat optimal second countability assumptions for this, I had to improve a result in a previous file. This means that the PR is now bigger (it also proves that if a subset is separable then so is its linear span), and that the delegation no longer makes sense. So, I am putting it back to `awaiting-review`.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
