### PR TITLE
[Merged by Bors] - feat: port Topology.MetricSpace.CantorScheme

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

- [x] depends on: #3496

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3496
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
bors d+

Please merge once bors is finished with the dependent PR.

**Comment by Parcly-Taxel** [comment]
bors merge

**Comment by Parcly-Taxel** [comment]
bors merge

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3496~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Pull request closed without merging**
