### PR TITLE
perf(Algebra/Algebra): un-instance `Subalgebra.algebra'` et al.

### PR DESCRIPTION
**Pull request by Vierkantor**
`Subalgebra.algebra'`, `Subalgebra.module'` and `IntermediateField.algebra'` are more general forms of the module/algebra structure that we don't actually seem to need in practice. Since finding these instances can be quite slow (cf. #9936), we might as well disable them outright (and enable them locally if ever needed).

---

 - [x] depends on: #9936

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
Looks good to me. You mention three instances in the PR description but only address two.

**Comment by eric-wieser** [comment]
I don't really like the idea of removing these instances; they're the type of thing that are really hard to find if you do need them. One example of where I believe they come up is showing that two submodules of an A-linear space are R-linearly equivalent. 
The fact an instance isn't used in mathlib doesn't mean it's useless; it might just mean that everything is mathlib is stated so generally that we need talk about these concrete cases.

This then causes trouble for downstream users who find they do want the concrete case, but then get annoyed because the general case doesn't seem to apply for them.

**Comment by mattrobball** [comment]
If lowered priority is enough to make Lean never look for these, I can be convinced to keep them. We should see the performance profile of this before continuing. 

!bench

**Comment by mattrobball** [comment]
!bench

**Comment by eric-wieser** [comment]
The benchmark comparison won't be meaningful until we resolve the conflicts

**Comment by Vierkantor** [comment]
> You mention three instances in the PR description but only address two.

I'm not sure what you mean: there are two instances that become `def`s in `Subalgebra/Basic.lean` and one in `IntermediateField.lean`.

**Comment by mattrobball** [comment]
Never mind. I missed it. 🤦‍♂️

**Comment by eric-wieser** [comment]
!bench

**Comment by mattrobball** [comment]
[This](http://speed.lean-fro.org/mathlib4/compare/e7b27246-a3e6-496a-b552-ff4b45c7236e/to/534b6a74-bcc9-4d27-bf7f-56246b1c352b?hash1=725f123f1d69cd0bbb38dd86c9624389dafe1ecc) is the comparison you are looking for right?

**Comment by eric-wieser** [comment]
> Here are the [benchmark results](http://speed.lean-fro.org/mathlib4/run-detail/534b6a74-bcc9-4d27-bf7f-56246b1c352b) for commit [ba606cd](https://github.com/leanprover-community/mathlib4/commit/ba606cd6e4558f4baafbc846e5e25cf23940b30d).Found no runs to compare against.

This is the second PR that I've seen this happen on today

**Comment by mattrobball** [comment]
It looks like there is no performance gain over just de-prioritization.

**Comment by Vierkantor** [comment]
If there is no performance gain, I don't see a reason to continue this PR. For `Submodule.module'` the added flexibility really is needed, so I expect if we disable these instances we'll want to re-enable them soon in the future. (Either because we need it in Mathlib, or someone depended on them for their own project.)

If anyone would like to push this PR forward, then please take over from me! Otherwise I'll close it sometime in the weekend I guess.

**Comment by eric-wieser** [comment]
I agree we should probably just close it. It's great that the priority tweak was sufficient.

**Pull request closed without merging**
