### PR TITLE
[Merged by Bors] - chore: drop some unnecessary imports

### PR DESCRIPTION
**Pull request by hrmacbeth**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
I think the actual problem here is that Riccardo put the wrong imports in `Mathlib.Algebra.Order.Hom.Basic` when porting!

**Comment by semorrison** [comment]
i.e. the correct fix is to revert your change, and replace the import block in `Mathlib.Algebra.Order.Hom.Basic` with

```
import Mathlib.Algebra.GroupPower.Order
```

(I identified this by trying to backport.)

**Comment by semorrison** [comment]
Please merge if CI accepts https://github.com/leanprover-community/mathlib/pull/18978!

bors d+

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
