### PR TITLE
[Merged by Bors] - feat(SetTheory/Ordinal/Basic): notation `typeLT α = type (α := α) (· < ·)`

### PR DESCRIPTION
**Pull request by vihdzp**
---

Another option might be to simply make the type argument in `type` explicit, but since the API makes a lot of use of unbundled relations, that would just make a lot of code longer.

This might also make sense to have for `typein`, but currently we use `typein (α := o.toType) (· < ·)` a lot when we should be using [`Ordinal.enumIsoToType`](https://leanprover-community.github.io/mathlib4_docs/Mathlib/SetTheory/Ordinal/Basic.html#Ordinal.enumIsoToType) instead, so I'd like to clean that up before seeing if introducing notation makes sense.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by YaelDillies — COMMENTED** [review]
Sure

maintainer merge

**Comment by vihdzp** [comment]
Wait a sec! I got a suggestion on Zulip to make this an abbreviation, so I'll implement that instead.

**Comment by b-mehta** [comment]
Thanks!

bors merge

**Comment by b-mehta** [comment]
bors merge

**Pull request closed without merging**
