### PR TITLE
[Merged by Bors] - chore: mv principal_subtype

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — APPROVED** [review]
Did you mean to drop the #align? Other than that, looks good.

**Comment by grunweg** [comment]
Oh, and: please remember to mark `awaiting-review` when you actually would like to get reviewed.

**Review by grunweg — COMMENTED** [review]
Looks good to me now.
maintainer merge

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
