### PR TITLE
[Merged by Bors] - feat: port Algebra.ContinuedFractions.Basic

### PR DESCRIPTION
**Pull request by int-y1**
---

Heavy changes to coe stuff.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by int-y1** [comment]
todo:

- [ ] `GeneralizedContinuedFraction.Pair`: See if it's possible to re-introduce `protected`. Also, figure out this comment: `unusual advanced open style`.
- [ ] 2 `norm_cast` errors

**Comment by joneugster** [comment]
hi @int-y1, on first glance I believe for these remaining issues it would be fine to just merge them with a porting note, your call.

In particular I think with `coe` there is enough that will need to be improved in the future, that it might be worth just revisiting the `norm_cast` issues later again.

**Comment by joneugster** [comment]
@int-y1 if you're happy with the changes, please feel free to add the `await-review` label, or feel free to revert any of them otherwise :)

The `protected` issue isn't addressed, but I think that is okay.

**Comment by int-y1** [comment]
These changes look ok. The issue with `protected` was something I considered optional.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
