### PR TITLE
[Merged by Bors] - chore: weaken typeclass assumptions `MetricSpace` → `PseudoMetricSpace`

### PR DESCRIPTION
**Pull request by grunweg**
Discovered through the linter in #17519 (but in fact not related to it).

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
!bench

**Comment by eric-wieser** [comment]
This generalization can go quite a lot further... Let me try pushing some more.

**Comment by eric-wieser** [comment]
I span off #17526 rather than getting carried away beyond MeasureTheory.

**Comment by eric-wieser** [comment]
!bench

**Comment by RemyDegenne** [comment]
It looks good and I think we could merge. Do you still want to try and get a working benchmark?

**Comment by grunweg** [comment]
!bench

**Comment by grunweg** [comment]
The speed-center is back up, so let's hopefully just wait a short moment until the benchmarking results are in. If this doesn't work, I'm happy to merge it as-is.

**Comment by grunweg** [comment]
Once more with feeling:

**Comment by grunweg** [comment]
!bench

**Pull request closed without merging**
