### PR TITLE
[Merged by Bors] - chore: further backports from leanprover/lean4#6123

### PR DESCRIPTION
**Pull request by kim-em**
Follow-up from #19852.

https://github.com/leanprover/lean4/pull/6123 fixes some inconsistencies in the behaviour of simp, by propagating Simp.Config settings through to Meta.Config. This requires us to be more explicit about unfolding let bindings in many places in Mathlib.

There are a few more changes that will only land in `nightly-testing` once https://github.com/leanprover/lean4/pull/6123 is in.

### CODE REVIEW

**Comment by eric-wieser** [comment]
bors d+

Thanks!

Its not clear to me whether `let x := ...; simp [x]` or `letI x := ...; simp` is better, but it doesn't really matter.

**Comment by kim-em** [comment]
bors merge

**Comment by kim-em** [comment]
Sneaking in some further backports, the fixes to Archive and Counterexamples.

**Comment by kim-em** [comment]
bors merge

**Pull request closed without merging**
