### PR TITLE
[Merged by Bors] - chore(Tactic/Basic): add `pp_with_univ` to some builtin types

### PR DESCRIPTION
**Pull request by eric-wieser**
These can't go in the same file as where `pp_with_univ` is defined, so here seems as good as anywhere.

This means `ULift A` now prints as `ULift.{v,u} A`. Ideally it would print as `ULift.{v} A` ([Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/pp_with_univ.20for.20only.20some.20universe.20arguments/near/386153934)), but this is a problem with pretty much every current use of `pp_with_univ`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by kmill** [comment]
It might be possible to create an `app_unexpander` to erase universe levels after the first if it ends up being annoying always seeing all of them.

**Comment by eric-wieser** [comment]
Prototypes in the Zulip thread very welcome!

**Comment by kmill** [comment]
(And just to be clear I don't mean to suggest that having an `app_unexpander` should be a prerequisite for merging this PR! I'd prefer not having them for now, but I mentioned it in case anyone looks at the history later.)

**Review by YaelDillies — APPROVED** [review]
The location is possibly suboptimal, but the import is small, only adds three lines to the file, and I guess we expect those `pp_with_univ` tags to be available virtually everywhere in mathlib.

maintainer merge

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by jcommelin** [comment]
bors d+

**Comment by jcommelin** [comment]
bors merge

**Pull request closed without merging**
