### PR TITLE
[Merged by Bors] - feat: make `ExistsUnique` notation throw an error when used with more than one binder

### PR DESCRIPTION
**Pull request by kmill**
[Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/How.20can.20I.20say.20.22there.20exist.20unique.20a.2C.20b.20such.20that.2E.2E.2E.22.3F/near/433824047)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
I can't review the meta code. The rest LGTM. Thanks!

**Comment by semorrison** [comment]
bors merge

**Comment by kmill** [comment]
@YaelDillies Do you think it would be better for it to say "expecting ','" rather than the way it gives an explanation why multiple binders is not allowed?

**Comment by YaelDillies** [comment]
I'm not sure I understand your message.

What I mean is that `∃! a : α, p a` could be notation for `ExistsUnique (fun a ↦ p a)` while `∃! (a : α) (b : β), p a b` could be notation for `∃ a b, p a b ∧ ∀ a' b', p a' b' → a' = a ∧ b' = b` and etc with more binders.

**Comment by kmill** [comment]
"Fix the syntax" suggests changing the syntax, but you're suggesting changing the interpretation of the current syntax, which is very different. It's an interesting idea, but that's something that would need discussion.

Also, this PR doesn't exclude that idea from being implemented, so why the urgency with asking to wait?

**Comment by YaelDillies** [comment]
No urgency. I was just surprised this suggestion hadn't come up.

**Pull request closed without merging**
