### PR TITLE
[Merged by Bors] - feat(Topology/Order): add more `CovBy.nhdsWithin...` lemmas

### PR DESCRIPTION
**Pull request by urkud**
- Add lemmas about `𝓝[<] a` and `𝓝[≤] a` in a `PredOrder`.
- Add lemmas about `𝓝[>] a` and `𝓝[≥] a` in a `SuccOrder`.
- Add `CovBy.nhdsWithin_Ici` and `CovBy.nhdsWithin_Iic`.
- Prove that an `OrderClosedTopology` on a linear order which is a `PredOrder` and a `SuccOrder` is discrete.
- Cleanup theorems about `OrderTopology` vs `DiscreteTopology`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by YaelDillies** [comment]
!bench

**Comment by urkud** [comment]
@YaelDillies Any ideas why it causes slow down? The new instance?

**Comment by YaelDillies** [comment]
Yes. As I was suspecting, this new `DiscreteTopology` instance is making typeclass synthesis search through the order hierarchy because `SuccOrder` is a mixin. Do you think it can be made a non-instance? When do you want it to fire?

**Comment by urkud** [comment]
I have no specific plans for this instance. I'll turn it into a non-instance (at least, for now).

**Comment by urkud** [comment]
!bench

**Comment by urkud** [comment]
@YaelDillies Now `!bench` says that the change makes `Mathlib` a bit faster.

**Review by YaelDillies — APPROVED** [review]
Thanks! 🚀

maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
