### PR TITLE
[Merged by Bors] - chore(Mathlib/Init/Data/Ordering/*): move `Mathlib.Init.Data.Ordering` to `Mathlib.Data.Ordering`

### PR DESCRIPTION
**Pull request by Komyyy**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by j-loreaux — COMMENTED** [review]
Thanks!

bors merge

**Comment by grunweg** [comment]
The files you're moving have a "note about files in Mathlib/Init" - can you also remove that, please?

**Comment by Komyyy** [comment]
@grunweg
Sorry, I have fixed now.
Without the merge conflicts, I would have missed this change.

**Comment by j-loreaux** [comment]
Me too. Sorry for that.

bors merge

**Comment by grunweg** [comment]
> @grunweg Sorry, I have fixed now. Without the merge conflicts, I would have missed this change.

No worries; thanks for the quick fix!

**Pull request closed without merging**
