### PR TITLE
[Merged by Bors] - feat(Order/Filter): Add lemmas about Filter.curry

### PR DESCRIPTION
**Pull request by Felix-Weilacher**
`Filter.curry` is a useful definition for reasoning about Fubini-type theorems, but there are almost no lemmas about it. This PR adds some in preparation for an upcomming PR on the Kuratowski-Ulam theorem. 

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by Felix-Weilacher** [comment]
I'm not sure what happened to the build, the proof that was said to have an error still works on my machine.

**Comment by grunweg** [comment]
My guess is that `master` changed in the mean-time - can you merge the master branch and verify things build?

**Comment by Felix-Weilacher** [comment]
It has been fixed

**Comment by robertylewis** [comment]
bors merge

**Pull request closed without merging**
