### PR TITLE
[Merged by Bors] - Chore: Rename files with Eisenstein series stuff.

### PR DESCRIPTION
**Pull request by CBirkbeck**
Accidentally created a `Mathlib/NumberTheory/ModularForms/EisensteinSeries/ModularForm.lean` file name. Made it a Basic.lean file and made the previous into a Defs.lean

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by loefflerd** [comment]
This seems to be purely a renaming PR, no new code added or removed, and I agree the new names are more sensible

maintainer merge

**Comment by loefflerd** [comment]
(I am assuming that you meant to put an "awaiting-review" tag on this, since you requested a review from Riccardo.)

**Comment by riccardobrasca** [comment]
> (I am assuming that you meant to put an "awaiting-review" tag on this, since you requested a review from Riccardo.)

[No more awaiting-review](https://leanprover.zulipchat.com/#narrow/stream/113486-announce/topic/Changes.20to.20the.20.23queue/near/450176907)!

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
