### PR TITLE
[Merged by Bors] - feat: `maintainer merge?`/`maintainer delegate?` switch for spoiler

### PR DESCRIPTION
**Pull request by adomani**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — APPROVED** [review]
Thanks for the quick fix!
This seems plausible - but since I have not fully descended into the dark dungeon of regex syntax in all kinds of different languages, including shell-in-yaml, I'd like somebody else to confirm.

Would you like to mention delegate in the PR title also?

**Comment by adomani** [comment]
Thanks!  I added `delegate` to the title as well.

**Comment by kim-em** [comment]
Would `?` make more sense than `!`? This is not intended to be "sudo maintainer merge" but "maintainer merge, but please check".

**Comment by adomani** [comment]
@kim-em I do prefer `maintainer merge?`, thanks!  I updated the PR.

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
