### PR TITLE
[Merged by Bors] - chore: clear some porting notes on rfl

### PR DESCRIPTION
**Pull request by mo271**
We remove some porting notes for `rfl`s that by now work again.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
It seems like two cases where a proof was broken during the port, and it was suspected that https://github.com/leanprover/std4/issues/62 was the reason now work again. So it seems the underlying cause of breakage might have been something else.

**Comment by eric-wieser** [comment]
!bench

**Comment by eric-wieser** [comment]
bors d+

I've seen cases where a `convert` proof for decidability instance is incredibly slow.

**Pull request closed without merging**
