### PR TITLE
[Merged by Bors] - feat: port GroupTheory.Perm.Cycle.Basic

### PR DESCRIPTION
**Pull request by LukasMias**
Lotsa stuff to do, please help. Also, `Equiv.Perm.Support` should be named `Equiv.Perm.support`, right? I carried out that renaming in here.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
I think this just needs linting now

**Comment by arienmalec** [comment]
> I think this just needs linting now

I fixed line breaks and deleted some mathport notes. The only one that wants checking is the very long "dubious translation" note, which doesn't seem to make sense...

**Pull request closed without merging**
