### PR TITLE
[Merged by Bors] - chore: Rename `DenseInducing` to `IsDenseInducing`

### PR DESCRIPTION
**Pull request by YaelDillies**
`Function.Embedding` is a type while `Embedding` is a proposition, and there are many other kinds of embeddings than topological embeddings. Hence this PR is a step towards
1. renaming `Embedding` to `IsEmbedding` and similarly for neighborhing declarations (which `DenseInducing` is)
2. namespacing it inside `Topology`

[Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/rename.20.60Inducing.60.20and.20.60Embedding.60.3F). See #15993 for context.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
Can you describe the motivation for this rename?

**Comment by YaelDillies** [comment]
`Function.Embedding` is a type while `Embedding` is a proposition, and there are many other kinds of embeddings than topological embeddings. Hence I am suggesting
1. To rename `Embedding` to `IsEmbedding` and similarly for neighborhing declarations (which `DenseInducing` is)
2. To namespace it inside `Topology`

**Comment by eric-wieser** [comment]
Please  explain that in the PR description!

It sounds to me like it would make more sense to rename `Embedding` first, but I guess it doesn't really matter if it all happens soon anyway.

In isolating, `Inducing` feels different to `Embedding` since only the latter is a noun.

**Comment by YaelDillies** [comment]
`Embedding` is the declaration with the biggest fallout, so my plan is to do it last.

> In isolation, `Inducing` feels different to `Embedding` since only the latter is a noun.

Maybe, but I think `Inducing`/`IsEmbedding` is strictly worse than `IsInducing`/`IsEmbedding`. Also note that mathlib docstrings have started using "inducing" as a noun!

**Comment by j-loreaux** [comment]
Please update the PR description per Eric's comment, as we want this in the git history.

Also, It doesn't look like you namespaced `IsDenseInducing`. Or did I miss it (I only looked on GitHub).

**Comment by YaelDillies** [comment]
As clarified on Zulip, namespacing will be done later, all declarations at once

**Comment by eric-wieser** [comment]
> Also note that mathlib docstrings have started using "inducing" as a noun!

Can you give an example, and maybe raise this on zulip?

**Comment by j-loreaux** [comment]
bors merge

**Pull request closed without merging**
