### PR TITLE
[Merged by Bors] - feat: Add `Module.Free` and `Module.Finite` instances for ideals

### PR DESCRIPTION
**Pull request by xroblot**
Add also a `NoZeroSMulDivisors` instance.

These instances, in particular, imply directly that integral ideals of number fields are free and finite $\mathbb{Z}$-modules. 

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by xroblot** [comment]
!bench

**Comment by xroblot** [comment]
!bench

**Comment by riccardobrasca** [comment]
When you says "imply directly" do you mean "by infer_instance"?

**Comment by xroblot** [comment]
> When you says "imply directly" do you mean "by infer_instance"?

Yes.

**Comment by riccardobrasca** [comment]
Great!

bors merge

**Pull request closed without merging**
