### PR TITLE
[Merged by Bors] - feat: image of a von Neumann bounded set under a multilinear map

### PR DESCRIPTION
**Pull request by urkud**
---

- [x] depends on: #10776 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ADedecker** [comment]
How much do you care about the non `ContinuousSMul` case? The reason I'm asking this is because, if you assume this and that the field is nontrivially normed (which you can always do), it turns out that `S` is bounded iff for all neighborhood `V` of zero, there is **some** scalar `r ≠ 0` such that `r • S ⊆ V`. We don't have this yet (which is a shame, it could probably be used to simplify a bunch of proofs, although the assumptions are rather strong), but it is essentially a direct consequence of [nhds_basis_balanced](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Analysis/LocallyConvex/BalancedCoreHull.html#nhds_basis_balanced). 
Once you have that, your result is easier to prove, since you can just take the product of one such element on each factor.

**Comment by urkud** [comment]
I don't care about spaces without `ContinuousSMul`. OTOH, if we already have a proof that works, then why decrease generality? Also, I don't think that the proof will be much shorter without `[Finite ι]`. Again, I don't care about the case `[Infinite ι]` but why not save a TC search every time we use the theorem?

**Comment by ADedecker** [comment]
The finiteness part shouldn't be a problem, you still have a neighborhood of zero in a product so you can ignore all components on which your neighborhood is `univ`. 

My point was mostly to have a more natural proof, I'm not a big fan of the idea that we end up doing a more complicated proof (maybe shorter in total lines of code of course, but I don't think that's the right metric for complexity) just for the sake of generality that we will never use.

I'm okay with keeping this proof for now because I know you have things which depend on it, I'm just a bit worried that later attempts to simplify this proof would be turned down because of "loss of generality".

**Comment by urkud** [comment]
My goal is to have some form of this statement merged. I only need it as a dependency for topology on `ContinuousMultilinearMap`s.

**Comment by urkud** [comment]
@ADedecker What do you want me to do with this PR to get it merged?

**Comment by ADedecker** [comment]
Sorry for the delay.

Let's merge this as is, I'll try to find some time soon to try the approach I suggested.

bors merge

**Pull request closed without merging**
