### PR TITLE
[Merged by Bors] - chore: deprecate "goal-style" `tfae_have` syntax

### PR DESCRIPTION
**Pull request by thorimur**
This PR deprecates the style of `tfae_have` syntax that behaves like Mathlib `have`, where the asserted hypothesis is prepended to the front of the goal list, in favor of `tfae_have ... := ...` syntax. It does so by preserving the old syntax and implementation in the same imports and logging a deprecation-styled warning. This warning can be turned off with `set_option Mathlib.Tactic.TFAE.useDeprecated true`.

This PR also includes some minor tweaks to `tfae_have` documentation and hover behavior to solidify `tfae_have ... := ...` as the current syntax.

It also modifies some old-style syntax that had crept into Mathlib in between the syntax removal (#11000) and this PR.

---

- [x] depends on: #11000 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
We didn't ever deprecated old-style mathlib `have`s (and in fact, sometimes they're still needed to work with `HasDerivAt`); so I'd actually argue that we also shouldn't deprecate this syntax.

**Comment by thorimur** [comment]
@eric-wieser Hmm, that presents a few options. Let's continue the discussion [on zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/tfae_have.201.20.E2.86.92.202.20.3A.3D.20syntax/near/472324532)!

**Comment by thorimur** [comment]
> We didn't ever deprecated old-style mathlib `have`s (and in fact, sometimes they're still needed to work with `HasDerivAt`); so I'd actually argue that we also shouldn't deprecate this syntax.

Since old-style `tfea_have` syntax is beginning to creep back in, I removed the `awaiting-zulip` tag (after waiting a day for objections to merging this as-is).

To reiterate the justification for merging as-is that I gave on zulip here on the PR: I think providing the ability to use a `set_option` to turn off the deprecation warning provides enough of an escape hatch (equivalent to sequestering old-style `have` in its own import) if it's ever truly necessary to use the old-style syntax.

**Comment by kim-em** [comment]
bors merge

**Pull request closed without merging**
