### PR TITLE
[Merged by Bors] - feat: add Aesop rules for Discrete category

### PR DESCRIPTION
**Pull request by JLimperg**
Adds a global Aesop `cases` rule for the `Discrete` category. This rule was previously added locally in several places.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by JLimperg** [comment]
Adding a global `cases` rule for the `Discrete` category could slow down unrelated Aesop calls, though I don't think it should matter much. Do we have a way to detect this kind of performance regression?

**Comment by semorrison** [comment]
Could you update the PR description?

**Comment by semorrison** [comment]
!bench

**Comment by semorrison** [comment]
If there is nothing alarming in the benchmarking output (if it ever arrives, I think the benchmark bot may be [broken](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/port.20progress/near/367952964)), please merge.

bors d+

**Comment by JLimperg** [comment]
Bot indeed seems to be broken. :disappointed: Merging anyway.

bors r+

**Comment by Kha** [comment]
> Bot indeed seems to be broken. disappointed Merging anyway.
> 
> bors r+

The base commit is in *checks notes*... 86th place in the benchmarking queue :disappointed:

**Pull request closed without merging**
