### PR TITLE
[Merged by Bors] - chore: add gitpod configuration

### PR DESCRIPTION
**Pull request by eric-wieser**
This is largely copied from mathlib3, but with the leanproject setup removed

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by hrmacbeth** [comment]
Thank you for doing this!  Do I understand correctly that it doesn't yet run `lake exe cache get`, the user has to do this?

**Comment by eric-wieser** [comment]
`lake exe cache get` doesn't work on gitpod at all, last time I checked; all the downloaded files are empty.

**Comment by hrmacbeth** [comment]
Oh darn, I use that a lot (for reviews and for teaching).  I'm glad you're experimenting with this and I hope someone figures out how to fix it!

**Pull request closed without merging**
