### PR TITLE
[Merged by Bors] - chore: replace many `refine'` with `refine`

### PR DESCRIPTION
**Pull request by adomani**
This PR replaces 7979 `refine'` with `refine`.  Many of the left-over ones cannot actually be directly replaced by `refine <add some ?>`.

[Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/144837-PR-reviews/topic/.2313166.20.60refine'.60.20to.20.60refine.60)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
!bench

**Comment by kbuzzard** [comment]
!Stoll-bench @MichaelStollBayreuth

**Comment by adomani** [comment]
[Benchmark using master from a couple of commits ago](http://speed.lean-fro.org/mathlib4/compare/e7b27246-a3e6-496a-b552-ff4b45c7236e/to/7154f447-eacb-45e1-b172-599fa45c4fa8?hash1=801a7d0eef7f568fbb26de3770097abcd981977d) (thanks Matt!).

**Comment by MichaelStollBayreuth** [comment]
Unfortunately, `http://speed.lean-fro.org/mathlib4/compare/e7b27246-a3e6-496a-b552-ff4b45c7236e/to/7154f447-eacb-45e1-b172-599fa45c4fa8?all_values=true` does not work here (which is how my script gets the json file with the information). If someone knowns the right incantation for this case, I can produce a more detailed summary.

**Comment by adomani** [comment]
@MichaelStollBayreuth, Matt provided a better bench that I linked shortly before you posted your comment: does that benchmark help?

**Comment by MichaelStollBayreuth** [comment]
@adomani That's the one I was trying.

**Comment by adomani** [comment]
Oh, sorry, I clicked on the link and I could see nothing.

**Comment by mattrobball** [comment]
Ok, I removed the lines starting with whitespace, an optional dot, optional whitespace, and then `refine`. This left about 2k lines of the diff. I went through those `?_` by `?_` to make sure nothing was off.

bors merge p=90001

**Pull request closed without merging**
