### PR TITLE
[Merged by Bors] - feat: port CategoryTheory.Monoidal.CoherenceLemmas

### PR DESCRIPTION
**Pull request by kim-em**
- [x] depends on: #4357

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4357
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4357~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
