### PR TITLE
[Merged by Bors] - chore: address porting notes in Archive.Wiedijk100Theorems.Partition

### PR DESCRIPTION
**Pull request by dwrensha**
`convert` no longer hits a timeout here.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by dwrensha** [comment]
compare to the mathlib3 versions of these theorems:
https://github.com/leanprover-community/mathlib/blob/65a1391a0106c9204fe45bc73a039f056558cb83/archive/wiedijk_100_theorems/partition.lean#L373-L395
https://github.com/leanprover-community/mathlib/blob/65a1391a0106c9204fe45bc73a039f056558cb83/archive/wiedijk_100_theorems/partition.lean#L421-L441

**Comment by dwrensha** [comment]
I tried to locate the first commit where the timeout were fixed, but as far as I can tell, not even the original commit (https://github.com/leanprover-community/mathlib4/commit/f3f3f1cb9e0147dab62fc62c26758c77e5a0c35a) hits timeouts when switched to `convert`.

So my hypothesis is that @Komyyy initially started the porting on an older version of mathlib4, but that by the time the PR was submitted and merged, the porting notes were already obsolete.

**Review by YaelDillies — APPROVED** [review]
Thanks!

maintainer merge

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
