### PR TITLE
[Merged by Bors] - chore: move Submodule.{map,comap} to Algebra.Module.Submodule.Map

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
Do you think the `mem_map_equiv` section belongs in this new file too?

**Comment by Ruben-VandeVelde** [comment]
Found a few more things, thanks for the suggestion

**Comment by eric-wieser** [comment]
bors d=@vierkantor

**Review by Vierkantor — APPROVED** [review]
Thanks!

bors r+

**Pull request closed without merging**
