### PR TITLE
[Merged by Bors] - feat: Port Data.Fintype.Perm

### PR DESCRIPTION
**Pull request by arienmalec**
Port of data.fintype.perm

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by nomeata** [comment]
I'll have to look at that build failure

**Comment by nomeata** [comment]
All green now, it seems, someone should press the button again.

**Comment by nomeata** [comment]
@ChrisHughes24 , can you try to merge again?

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
