### PR TITLE
[Merged by Bors] - feat: port NumberTheory.PrimesCongruentOne

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

- [x] depends on: #5144

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5144
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by jcommelin** [comment]
bors d+

Please merge this after the other PR has landed.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5144~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by Parcly-Taxel** [comment]
bors merge

**Comment by Parcly-Taxel** [comment]
bors merge

**Pull request closed without merging**
