### PR TITLE
[Merged by Bors] - feat(Algebra/Group/InjSurj): port file

### PR DESCRIPTION
**Pull request by j-loreaux**
mathlib3 SHA: f69e8f317a18ab43f12cdcacaa1a3765eb512065

This was a very straightforward port.

### CODE REVIEW

**Comment by dwarn** [comment]
Looks good to me!

**Comment by semorrison** [comment]
bors merge

**Comment by Ruben-VandeVelde** [comment]
```
error: stdout:
./././Mathlib/Algebra/Group/InjSurj.lean:173:13: error: (kernel) unknown constant 'AddCancelCommMonoid.toCommMonoid'
Building Mathlib.Data.Fin.Basic
./././Mathlib/Algebra/Group/InjSurj.lean:180:49: error: Declaration Function.Injective.addCancelCommMonoid not found.
```

**Comment by semorrison** [comment]
bors d+

**Comment by fpvandoorn** [comment]
What's going on here: `@[to_additive]` doesn't automatically translate projections to extended structures other than the first, in case that the extended structures have a field in common.

It is fixed by adding 
```lean
attribute [to_additive AddCancelCommMonoid.toAddCommMonoid] CancelCommMonoid.toCommMonoid
```
after `class CancelCommMonoid` in `Group/Defs`.

Remark: this can be fixed in `@[to_additive]` after leanprover/lean4#1881 is implemented.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
