### PR TITLE
[Merged by Bors] - fix: linarith handling of decimals

### PR DESCRIPTION
**Pull request by hrmacbeth**
[Zulip](https://leanprover.zulipchat.com/#narrow/channel/287929-mathlib4/topic/linarith.20regression.20on.20real.20numbers)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by hrmacbeth** [comment]
!bench

**Comment by hrmacbeth** [comment]
!bench

**Comment by kim-em** [comment]
bors d+

**Pull request closed without merging**
