### PR TITLE
[Merged by Bors] - feat: commutativity of `NonUnital{Star}Algebra.adjoin`

### PR DESCRIPTION
**Pull request by j-loreaux**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by j-loreaux** [comment]
Note: if the import here is deemed too large, then we probably want to split some of `Algebra.Star.SelfAdjoint` into a `Defs` file.

**Comment by ADedecker** [comment]
There is a nice trick for proving all of these without doing any work, by using that the bicentralizer/bicommutant of any commutative subset of a magma is commutative, and it has to contain `adjoin` for obvious reason, hence the result.

**Comment by j-loreaux** [comment]
Yeah, that's a nice trick, but we don't have any API for that currently, do we?

**Comment by ADedecker** [comment]
Well we have a bunch of incarnations of centralizers (you're probably the author of [NonUnitalStarSubalgebra.centralizer](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Algebra/Star/NonUnitalSubalgebra.html#NonUnitalStarSubalgebra.centralizer)), so I think the only missing piece is that basic lemma about the bicommutant of a commutative set in a magma. But if you have too much things depending on this and prefer to move forward I'm fine with just leaving a TODO somewhere about this.

**Comment by j-loreaux** [comment]
I've already started on this (the bicommutant stuff), but I'd prefer to do it in a separate PR if that's okay, as it will touch a bunch of files, and I'll have to do some reorganization.

**Comment by ADedecker** [comment]
Thanks! And sorry for sidetracking you into the bicommutant stuff :sweat_smile: 

bors merge

**Pull request closed without merging**
