### PR TITLE
[Merged by Bors] - perf(Algebra.GradedMonoid): scope theorem with weak keys 

### PR DESCRIPTION
**Pull request by mattrobball**
The keys for this theorem are `HSMul.hSMul _ _ _ _ _ _` so will be attempted on any term which has an `SMul` in it.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
Sure, this GradeZero stuff is dubious anyway.

Just to check, what scope does this end up going in?

**Comment by mattrobball** [comment]
`GradedMonoid`

**Comment by joneugster** [comment]
maintainer merge

**Pull request closed without merging**
