### PR TITLE
[Merged by Bors] - chore: Make `Finset.preimage` not depend on `Finset.sum`

### PR DESCRIPTION
**Pull request by YaelDillies**
and `Data.Finset.LocallyFinite` not depend on `Finset.sum` too

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
This makes `BigOperators/Basic` depend on `Set/Finite`. What do you think about creating a new file?

**Comment by YaelDillies** [comment]
I really really don't think that matters since the main reason to avoid importing `Set.Finite` is to avoid importing... `Finset`!

**Comment by urkud** [comment]
Let me have a look at the `import` graph of `Data.Set.Finite`.

**Comment by YaelDillies** [comment]
Given that the imports of `Algebra.BigOperators.Basic` are
```
import Mathlib.Algebra.BigOperators.Multiset.Lemmas
import Mathlib.Algebra.Function.Indicator
import Mathlib.Algebra.Ring.Opposite
import Mathlib.Data.Finset.Powerset
import Mathlib.Data.Finset.Sigma
import Mathlib.Data.Finset.Sum
import Mathlib.Data.Fintype.Pi
import Mathlib.Data.Int.Cast.Lemmas
import Mathlib.Data.Set.Image
```
this doesn't stick out to me. I agree that we need to split `Algebra.BigOperators.Basic`, but I don't think splitting it as "preimage lemmas" vs "the rest" is pertinent. So I suggest we do it in a later PR.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
