### PR TITLE
[Merged by Bors] - feat: `aeval` a Chebyshev polynomial

### PR DESCRIPTION
**Pull request by trivial1711**
The theorem `Polynomial.Chebyshev.aeval_T` states that if `R'` is an algebra over `R`, then `aeval x (T R n) = (T R' n).eval x`. We move this theorem and the equivalent `Polynomial.Chebyshev.algebraMap_eval_T`  from `Mathlib/Analysis/SpecialFunctions/Trigonometric/Chebyshev.lean` to `Mathlib/RingTheory/Polynomial/Chebyshev.lean`. We also add variants of this theorem for the Chebyshev C and S polynomials.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
> We move this theorem and the equivalent `Polynomial.Chebyshev.algebraMap_eval_T` from `Mathlib/Analysis/SpecialFunctions/Trigonometric/Chebyshev.lean` to `Mathlib/RingTheory/Polynomial/Chebyshev.lean`.

Why?

**Comment by trivial1711** [comment]
> > We move this theorem and the equivalent `Polynomial.Chebyshev.algebraMap_eval_T` from `Mathlib/Analysis/SpecialFunctions/Trigonometric/Chebyshev.lean` to `Mathlib/RingTheory/Polynomial/Chebyshev.lean`.
> 
> Why?

The theorem doesn't have anything to do with trigonometric functions.

**Comment by trivial1711** [comment]
I would be happy to move it back if you think that would make things better.

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
