### PR TITLE
[Merged by Bors] - feat: two missing injOn lemmas

### PR DESCRIPTION
**Pull request by PatrickMassot**
---

See the [Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/Image.20and.20InjOn/near/401173467)

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by fpvandoorn — COMMENTED** [review]
Please make `f` and `s` explicit in the first lemma.

bors d+

**Comment by j-loreaux** [comment]
I'm not going to object to the point of saying this shouldn't be merged, but I will say that I think it's going in slightly the wrong direction. Here, the `bijOn` / `injOn` / `surjOn` API is the thing the user should be encouraged to use. Notice how easy it was to get the desired statements from the existing lemma; going the other way is slightly messier.

**Comment by fpvandoorn** [comment]
That also seems reasonable to me. 
A middle ground would be to add the special case `∃ s' ⊆ s, BijOn f s' (f '' s)`.

**Comment by PatrickMassot** [comment]
bors merge

**Pull request closed without merging**
