### PR TITLE
[Merged by Bors] - bug fix: symm bug fix and FinEnum.lean change

### PR DESCRIPTION
**Pull request by zaxioms0**
In [FinEnum.lean](https://github.com/leanprover-community/mathlib4/blob/master/Mathlib/Data/FinEnum.lean#L166) there was a bug that prevented the `symm` tactic from working properly. After [discussing on zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Potential.20Bug.20in.20symm.20tactic), it's been fixed!

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by kmill** [comment]
I believe a similar bug also affects these lines: https://github.com/leanprover-community/mathlib4/blob/master/Mathlib/Tactic/Relation/Rfl.lean#L48 https://github.com/leanprover-community/mathlib4/blob/master/Mathlib/Tactic/Relation/Trans.lean#L108

**Comment by cppio** [comment]
`getMainTarget` already has `instantiateMVars`:
https://github.com/leanprover/lean4/blob/cbdd76f6b608a3791cdc5df0c49f2200f2170f1f/src/Lean/Elab/Tactic/Basic.lean#L319-L321

**Comment by fpvandoorn** [comment]
bors merge

Thanks

**Comment by fpvandoorn** [comment]
This was an error that arose from another PR. Doing nothing would probably have merged this PR after a retry (but I will agree that the bors error message is confusing).

bors d+

**Comment by zaxioms** [comment]
> This was an error that arose from another PR. Doing nothing would probably have merged this PR after a retry (but I will agree that the bors error message is confusing).
> 
> bors d+

good to know for the future. thanks!

**Pull request closed without merging**
