### PR TITLE
[Merged by Bors] - feat: missing API lemmas about the prod instance in Order/CompleteLattice

### PR DESCRIPTION
**Pull request by mans0954**
This adds lemmas about how `fst`, `snd`, and `swap` interact with `supₛ` and `infₛ`.

Manual port of https://github.com/leanprover-community/mathlib/pull/18029 by @eric-wieser

### CODE REVIEW

**Comment by eric-wieser** [comment]
Thanks for doing this, but I think it would be best to wait for mathport to run and discard the manual port in favor of the automatic one. There are some ongoing discussions on Zulip about that.

**Comment by mans0954** [comment]
> Thanks for doing this, but I think it would be best to wait for mathport to run and discard the manual port in favor of the automatic one. There are some ongoing discussions on Zulip about that.

I take it that's [here](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Mathport.20oneshot)

**Comment by eric-wieser** [comment]
https://github.com/leanprover-community/mathlib3port/blob/master/Mathbin/Order/CompleteLattice.lean should be ready in about 4 hours

**Review by kbuzzard — APPROVED** [review]
LTGM

**Comment by fpvandoorn** [comment]
bors merge

**Comment by eric-wieser** [comment]
Whoops, we forgot to update the SHA here.

**Pull request closed without merging**
