### PR TITLE
[Merged by Bors] - chore (Algebra.Order.Nonneg.Ring): split into unbundled and bundled ordered ring files 

### PR DESCRIPTION
**Pull request by mattrobball**
We split `Algebra.Order.Nonneg.Ring` into `Algebra.Order.Ring.Unbundled.Nonneg` which uses unbundled ordered algebra typeclasses, eg `CovariantClass`, and `Algebra.Order.Nonneg.Ring` which uses bundled class, eg `OrderedAddComm`. Using this we can avoid importing bundled ordered algebra classes until later downstream.

---

- [x] depends on: #14371 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by semorrison** [comment]
bors merge

**Comment by urkud** [comment]
bors failed, probably because of this file. Removing from the queue, delegating, and merging `master`.
bors r-
bors d+

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
