### PR TITLE
[Merged by Bors] - feat(CategoryTheory/Sites): add a left version of `sheafCongr`

### PR DESCRIPTION
**Pull request by dagurtomas**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by joelriou** [comment]
I think that both `sheafCongrLeft/Right` could be generalized to a single `sheafCongr` which would take as an input `e : C ≌ D`, `J : GrothendieckTopology C`, `K : GrothendieckTopology D` and the equality `(e.locallyCoverDense J).inducedTopology = K`. (This property could be part of a typeclass `[TransportGrothendieckTopologies e J K]`; maybe not the best name?)

**Comment by dagurtomas** [comment]
I generalised the equivalence, but I like the idea of the typeclass. I'll keep the awaiting author label and add that tomorrow.

**Comment by dagurtomas** [comment]
Ok, now with a typeclass. I think this will be useful in #10013

**Comment by joelriou** [comment]
Thanks!

bors merge

**Pull request closed without merging**
