### PR TITLE
[Merged by Bors] - feat: port Analysis.Convex.SpecificFunctions.Basic

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

- [x] depends on: #4129

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4129
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
@Ruben-VandeVelde, I fixed a few errors, but two failures of `linear_combination` remain.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4129~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by hrmacbeth** [comment]
> two failures of `linear_combination` remain.

Fixed

**Comment by semorrison** [comment]
bors p=10

bors merge

**Comment by fpvandoorn** [comment]
bors p=0

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
