### PR TITLE
[Merged by Bors] - feat: port SetTheory.Game.Domineering

### PR DESCRIPTION
**Pull request by timotree3**
---

- [x] depends on: #5653

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by timotree3** [comment]
[I asked in Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/naming.20conventions/near/371581249) about whether we should call it `domineering.l` or `domineering.L`. The PR currently uses lowercase, but I think uppercase is probably better even though it deviates from convention. I'll change it and a reviewer can always revert the last commit

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5653
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5653~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by fpvandoorn** [comment]
Thanks!

bors merge

**Pull request closed without merging**
