### PR TITLE
[Merged by Bors] - fix: typo in module doc of NumberTheory/Cyclotomic/Basic

### PR DESCRIPTION
**Pull request by fpvandoorn**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by riccardobrasca** [comment]
The file is `NumberTheory/Cyclotomic/Basic`, can you please fix the title?

**Comment by riccardobrasca** [comment]
Thanks!

bors d+

**Comment by fpvandoorn** [comment]
bors merge

**Pull request closed without merging**
