### PR TITLE
chore: revert #617 `↦` syntax

### PR DESCRIPTION
**Pull request by j-loreaux**
This reverts #617 which introduced the `↦` syntax for anonymous functions in place of `=>`. Unfortunately this caused some breakages with pretty-printing in various places. This reverts that syntax for now until we can have a better solution for `↦`.

---

Note: I didn't actually `git revert` the commit because there were lots of conflicts, so I found it easier to just remove the `Mathlib.Util.MapsTo` file, remove all the files that imported it, and do a search-and-replace for `↦` in place of `=>`. At the end, I only had to import `Std.Tactic.Lint` in two files (this was imported by `Mathlib.Util.MapsTo`). As for occurences of `↦` in docstrings, I looked through the search-and-replace and tried to leave `↦` when it appeared in docstrings.

### CODE REVIEW

**Comment by PatrickMassot** [comment]
Obviously, I am very strongly against merging this PR. The reasonable way forward is to fix the pretty printer issue. It's not even urgent since they don't block anything.

**Comment by semorrison** [comment]
@PatrickMassot, some context on this. We discussed this at the mathlib4 porting meeting last week. The question there came down to whether we prefer (for the short term):
1. Exists notation to work
2. The \mapsto arrow
with the understanding that having both was not possible without changes in Lean4 that were not going to happen until the new year.

The consensus of that meeting was that exists notation not working at all was a bigger problem than having \mapsto immediately, and hence we should revert. Sorry this discussion wasn't reflected properly on zulip so you didn't have a chance to participate. 

I don't think it's urgent either way, so I'm not in a hurry to merge this. Nevertheless, exists notation failing is an ongoing annoyance that many people would like out of the way for now.

**Comment by rwbarton** [comment]
Is it possible to make the `↦` arrow input-only (for now), and not be used by the pretty-printer?

**Comment by PatrickMassot** [comment]
I understand this is a temporary situation. But reverting back will be very painful if we go that road since we can't simply search and replace `=>` because it also happens in programming contexts.

**Comment by semorrison** [comment]
I have opened a Lean 4 issue https://github.com/leanprover/lean4/issues/1979 proposing that we fix this there, allowing ↦ as input form for everyone, and having ↦ in output only if a `pp` option is set. That option would default to false, but we would turn it on globally for mathlib4 in the lakefile.

**Comment by hrmacbeth** [comment]
Closing now that the notation has been enabled in Lean 4 (https://github.com/leanprover/lean4/pull/1984).

**Pull request closed without merging**
