### PR TITLE
[Merged by Bors] - feat: port Data.Analysis.Filter

### PR DESCRIPTION
**Pull request by int-y1**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by int-y1** [comment]
Remaining tasks:
* Write doc strings for the fields in `structure CFilter` and `structure Filter.Realizer`.
* Fix linter complaint on `theorem coe_mk`:
```
/- The `simpVarHead` linter reports:
LEFT-HAND SIDE HAS VARIABLE AS HEAD SYMBOL.
Some simp lemmas have a variable as head symbol of the left-hand side (after whnfR): -/
#check @coe_mk /- Left-hand side has variable as head symbol: f -/
```

**Comment by LukasMias** [comment]
I gave some reasoning for why I think the `@[simp]` attribute should be removed from `coe_mk`. I also tried for a bit to write some meaningful docstrings, but I did not have the time. Comparing the definition of CFilter with the definition of `ofFilter` seems helpful to form an analogy with classical filters, though.

**Comment by int-y1** [comment]
looks like docstrings aren't needed anymore

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
