### PR TITLE
[Merged by Bors] - feat: lemmas relating Finset.univ and List.get

### PR DESCRIPTION
**Pull request by timotree3**
We add sufficient lemmas for the simplifier to prove
`∀ (l : List α), Finset.univ.val.map l.get = ↑l`,
as well as the easier to apply phrasing
`∀ (l : List α), Finset.univ.val.map (f <| l.get ·) = ↑(l.map f)`.

We then add lemmas stating the corollaries for functions out of `Finset` which are built out of `Multiset.map`, such as `Finset.image` and `Finset.prod`.

---

I couldn't find a good file to put the corollaries for `Finset.fold`, `Finset.inf`, or `Finset.sup`.
Is it worth creating a new file that has both `Finset.univ` and `Finset.fold` imported to have these?

```lean
@[simp]
theorem Fin.inf_univ_get [SemilatticeInf α] [OrderTop α] (l : List α) :
    Finset.univ.inf l.get = l.foldr (· ⊓ ·) ⊤ := by
  simp [Finset.inf_def]

@[simp]
theorem Fin.inf_univ_get' [SemilatticeInf α] [OrderTop α] (l : List ι) (f : ι → α) :
    Finset.univ.inf (f <| l.get ·) = (l.map f).foldr (· ⊓ ·) ⊤ := by
  simp [Finset.inf_def]

@[simp]
theorem Fin.sup_univ_get [SemilatticeSup α] [OrderBot α] (l : List α) :
    Finset.univ.sup l.get = l.foldr (· ⊔ ·) ⊥ := by
  simp [Finset.sup_def]

@[simp]
theorem Fin.sup_univ_get' [SemilatticeSup α] [OrderBot α] (l : List ι) (f : ι → α) :
    Finset.univ.sup (f <| l.get ·) = (l.map f).foldr (· ⊔ ·) ⊥ := by
  simp [Finset.sup_def]
```

cc @madvorak who was working on some code that needed the sum corollary.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by madvorak** [comment]
Does `@[to_additive (attr := simp)]` put the `simp` attribute on the additive version only?

**Comment by timotree3** [comment]
> Does `@[to_additive (attr := simp)]` put the `simp` attribute on the additive version only?

I believe it puts it on both versions

**Review by BoltonBailey — APPROVED** [review]
All of these new lemmas look good to me.

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
