### PR TITLE
[Merged by Bors] - feat: add `lake exe shake` to CI

### PR DESCRIPTION
**Pull request by digama0**
- [X] depends on: #9830
- [X] depends on: #9772
- [X] depends on: #9996

This checks files for unused imports. The output here is piped through `gh-problem-matcher-wrap` so that it will show up as annotations.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
I think we need more straightforwardly human readable output. e.g.
```
./././Mathlib/GroupTheory/Subgroup/ZPowers.lean:
  remove #[Mathlib.Algebra.GroupPower.Lemmas]
  fix Mathlib.Algebra.GroupPower.Lemmas: #[Mathlib.Analysis.SpecificLimits.Basic, Mathlib.Data.Complex.Exponential]
```
should become:
````
In the file `Mathlib/GroupTheory/Subgroup/ZPowers.lean`, we can remove
```
import Mathlib.Algebra.GroupPower.Lemmas
```
after which we'll add that import back into the following files:
* Mathlib/Analysis/SpecificLimits/Basic.lean
* Mathlib/Data/Complex/Exponential.lean
````

**Comment by digama0** [comment]
I was hoping people would be using the github annotations, which are a bit more user friendly. The CLI output is more optimized for batch usage, where that kind of verbosity is a bit overwhelming if there are 30-100 of them.

**Comment by urkud** [comment]
> You can also just ignore the CLI output entirely and use `lake exe shake --fix > /dev/null || git diff HEAD` instead.

Can we turn this into clickable suggestions like we have for some style linters? Or it will fail because github won't accept suggestions to the lines that aren't touched by the PR?

**Comment by Vierkantor** [comment]
> You can also just ignore the CLI output entirely and use `lake exe shake --fix > /dev/null || git diff HEAD` instead.

That's definitely not something a user newly encountering `shake` is going to know, or teachable to the average mathematician. Before we encourage everyone to use this tool, we should make sure it doesn't raise further questions. Especially the output of `--fix` appearing to be in the imperative mood and the meaning of "fix" in the output looks confusing, and should be easy to fix. I've opened #9996 with my proposal.

**Comment by urkud** [comment]
What does `--gh-style` do and where can I see the output it generates?

**Comment by digama0** [comment]
`--gh-style` produces additional output from `shake` (which you can see in the build logs), these are lines that look like `file:line:col: warning: ...` and shake does not normally produce them. The purpose is that this particular error format is understood by `gh-problem-matcher-wrap`, and it uses them to produce annotations that appear on the PR itself next to other lint warnings. Just look for the comments about `unused import (use `lake exe shake --fix` to fix this...` in https://github.com/leanprover-community/mathlib4/pull/9751/files, and the annotations also appear on the build summary page https://github.com/leanprover-community/mathlib4/actions/runs/7632749681.

**Comment by semorrison** [comment]
> I was hoping people would be using the github annotations, which are a bit more user friendly. The CLI output is more optimized for batch usage, where that kind of verbosity is a bit overwhelming if there are 30-100 of them. You can also just ignore the CLI output entirely and use `lake exe shake --fix > /dev/null || git diff HEAD` instead.

I think we either need to have human readable output, or entirely suppress the non human readable output from the CI logs when you click on a red X! How is a new contributor meant to know they are meant to ignore this output?

**Comment by jcommelin** [comment]
Thanks :tada: 

If CI passes, please remove the label `awaiting-CI` and merge this yourself, by adding a comment `bors r+`.

bors d+

**Pull request closed without merging**
