### PR TITLE
[Merged by Bors] - feat: port Topology.Instances.Ereal

### PR DESCRIPTION
**Pull request by urkud**
### API changes

- Add `ENNReal.range_coe`, `ENNReal.range_coe'`, and `ENNReal.coe_strictMono`.
- Add instances for `DenselyOrdered EReal`, `T5Space EReal`, `ContinuousNeg EReal`, and `CanLift EReal ENNReal _ _`.
- Add `EReal.range_coe`, `EReal.range_coe_eq_Ioo`, `EReal.range_coe_ennreal`.
- Add `EReal.denseRange_ratCast`, `EReal.nhds_top_basis`, `EReal.nhds_bot_basis`.
- Deprecate `EReal.negHomeo` and `EReal.continuous_neg`.
- Generalize `orderTopology_of_ordConnected` to `StrictMono.induced_topology_eq_preorder` and `StrictMono.embedding_of_ordConnected`, use it to prove that some coercions are embeddings.
- Prove `TopologicalSpace.SecondCountableTopology.of_separableSpace_orderTopology` and helper lemmas `Dense.topology_eq_generateFrom`, `Dense.Ioi_eq_bunionᵢ`, and `Dense.Iio_eq_bunionᵢ`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ChrisHughes24** [comment]
The build fails with the latest master

**Comment by urkud** [comment]
@ChrisHughes24 I fixed compile.

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
