### PR TITLE
[Merged by Bors] - feat: add `alias` to the keywords tracked by `move_decls`

### PR DESCRIPTION
**Pull request by adomani**
As reported in #13725.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Looks straightforward to me (I didn't review super carefully, this since is not production code). Feel free to `maintainer merge` on my behalf.

**Comment by adomani** [comment]
Thanks!  I'll wait to see if @YaelDillies thinks that the new script works in the other PR: otherwise, in a couple of days I'll prod this along.

**Review by YaelDillies — APPROVED** [review]
Yep, looks good!

maintainer merge

**Comment by fpvandoorn** [comment]
bors merge

**Pull request closed without merging**
