### PR TITLE
[Merged by Bors] - feat port: Algebra.Order.LatticeGroup

### PR DESCRIPTION
**Pull request by ChrisHughes24**
10b4e499f43088dd3bb7b5796184ad5216648ab1

There are a lot of failures of `to_additive` in this file. Probably `to_additive` needs to be improved

### CODE REVIEW

**Comment by mans0954** [comment]
Another possibility would be to drop the multiplicative form and convert all the results to additive form. Applications of this theory are usually to partially ordered vector spaces, and the multiplicative form is rarely used.

**Comment by Ruben-VandeVelde** [comment]
I suspect all remaining issues are #1149. I don't know if we want to work around it by squeezing all the affected `simp`s.

**Comment by mans0954** [comment]
> I suspect all remaining issues are #1149. I don't know if we want to work around it by squeezing all the affected `simp`s.

I've removed all the appeals to `simp` from the mathlib3 version in [this PR](https://github.com/leanprover-community/mathlib/pull/18046) if that helps?

**Comment by mans0954** [comment]
@ChrisHughes24 It builds now.

**Pull request closed without merging**
