### PR TITLE
[Merged by Bors] - feat(Algebra/Homology): the homotopy category of cochain complexes is triangulated

### PR DESCRIPTION
**Pull request by joelriou**
In this PR, we show that for any additive category `C`, the pretriangulated category `HomotopyCategory C (ComplexShape.up ℤ)` is triangulated, i.e. the octahedron axiom holds.

---
- [x] depends on: #8951
- [x] depends on: #9032
- [x] depends on: #9370 
- [x] depends on: #10527

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by sgouezel** [comment]
Can you merge master, fix the  build, and send it back to bors?
bors d+

**Comment by Parcly-Taxel** [comment]
I am going to push a merge and fix.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
