### PR TITLE
[Merged by Bors] - feat: port Data.Set.Sups

### PR DESCRIPTION
**Pull request by mo271**
---

- [x] depends on: #2992

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
Can you check what is going on here, @YaelDillies? In mathlib at commit e96bdfbd, I get a similar problem, that I see in mathlib4:
```
sups.lean:168:0
unknown identifier 'image2_image2_image2_comm'
```
Does this need be fixed in mathlib first?

**Comment by YaelDillies** [comment]
It's because there needs to be a forward port of the dependencies first. I am writing it later today.

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2992
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2992~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by mo271** [comment]
This should fix the simpNF lints, but I'm unsure if they were justified. Please take a close look and possibly revert the last two commits and fix the simpNF lint complaints differntly.

**Comment by YaelDillies** [comment]
@Parcly-Taxel, please be sure something is ready for review before marking it as such. Here there were still some plain mathport output in the file along with linters to appease.

**Pull request closed without merging**
