### PR TITLE
[Merged by Bors] - feat(Analysis/Asymptotics/Asymptotics): generalize smul lemmas to normed rings

### PR DESCRIPTION
**Pull request by eric-wieser**
Using `BoundedSMul` instead of `NormedSpace` makes these true more generally. The old proofs do not generalize, so are replaced with copies of the `mul` proofs.

The `const_smul_self` lemmas match the existing `const_mul_self` ones.

`shake` then reports that the imports can be reduced.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
Should we allow `NormedDivisionRing`s (or even `SeminormedRing`s) in `NormedSpace`?

**Comment by eric-wieser** [comment]
Possibly; though arguably with that change it should be renamed to `NormedModule` I'm not convinced we really care about the typeclass at all; we have no single typeclass for TVS, and instead use a mixin like we do here for BoundedSMul.

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Comment by jcommelin** [comment]
This might be causing bors failure...

bors r-

bors d+

**Comment by eric-wieser** [comment]
bors merge

**Comment by urkud** [comment]
It has a merge conflict now. Please merge `master` and put it back on the queue.
bors r-
bors d+

**Comment by eric-wieser** [comment]
bors merge

**Pull request closed without merging**
