### PR TITLE
[Merged by Bors] - feat: port FieldTheory.PrimitiveElement

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
bors merge

**Comment by Vierkantor** [comment]
This PR depends on SplittingField.Construction which is receiving forward ports at the moment, and the Zulip chat suggests not merging it yet: https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/!4.234891.20.20FieldTheory.2ESplittingField/near/366437263

bors r-

**Comment by semorrison** [comment]
I think it is fine to merge this. None of the backporting PRs in mathlib3 have actually touched this file so far.

**Comment by riccardobrasca** [comment]
bors merge

**Pull request closed without merging**
