### PR TITLE
[Merged by Bors] - feat: port Analysis.NormedSpace.ENorm

### PR DESCRIPTION
**Pull request by int-y1**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by int-y1** [comment]
todo:

* [ ] `norm_cast` errors for `coe_inj` `coe_max` `max_map`

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Comment by j-loreaux** [comment]
I think this should be called `ENorm`, not `Enorm`. I'll change it tomorrow if no one gets around to it.

**Comment by jcommelin** [comment]
Aah, that makes a lot of sense. Sorry for missing it, and thanks for offering to fix it.

**Comment by jcommelin** [comment]
bors merge

**Comment by jcommelin** [comment]
Sorry for all the noise. Should be ready to go now.

bors r+

**Pull request closed without merging**
