### PR TITLE
[Merged by Bors] - chore: remove `#align`-oriented linters

### PR DESCRIPTION
**Pull request by adomani**
Now that `#align`s have been removed, these linters and exceptions are obsolete.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Thank you! I'll turn to the align-related code in the style linters next.
maintainer merge

**Comment by mattrobball** [comment]
bors delegate+

**Comment by grunweg** [comment]
Update: #14915 is blocked on removing the #align-ed comments (some are longer than 100 characters) - let's land this separately.

**Comment by adomani** [comment]
@grunweg by "let's land this separately" you mean that I can merge this one once it is green?  I was simply waiting for the `#`-command linter to confirm that no more `#align`-related statements were present before merging.

**Pull request closed without merging**
