### PR TITLE
[Merged by Bors] - chore: deprecate bad lemmas about WithTop/WithBot

### PR DESCRIPTION
**Pull request by eric-wieser**
`Order/WithBot.lean` seems to frequently confuse `WithBot.some` and `Option.some`, and some of the lemmas are strange as a result.

By teaching `cases` not to introduce `Option.some`, we no longer need these weird lemmas.

This deprecates:

* `List.maximum_eq_none` → `List.maximum_eq_bot`
* `List.minimum_eq_none` → `List.maximum_eq_top`
* `WithBot.some_le_some` → `WithBot.coe_le_coe`
* `WithBot.some_lt_some` → `WithBot.coe_lt_coe`
* `WithBot.none_lt_some` → `WithBot.bot_lt_coe`
* `WithBot.not_lt_none` → `WithBot.not_lt_bot`
* `WithBot.none_le` → `bot_le`
* `WithTop.some_le_some` → `WithTop.coe_le_coe`
* `WithTop.some_lt_some` → `WithTop.coe_lt_coe`
* `WithTop.some_lt_none` → `WithTop.coe_lt_top`
* `WithTop.not_none_lt` → `WithTop.not_top_lt`
* `WithTop.le_none` → `le_top`

It's still occasionally possible to end up with `Option.some a : WithTop A`, but when this happens you can rewrite by `some_eq_coe` first to fix it.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Does `since` syntax work in this case --- if so, can you also add a deprecation date? Thanks!
(Seeing this PR is not marked as awaiting-review, perhaps you intended to do this. In this case, sorry for the redundant advice!)

**Comment by grunweg** [comment]
Let me mark this as awaiting-author, to reflect its apparent current state.
awaiting-author

**Comment by eric-wieser** [comment]
I think I will probably split this PR into a cleanup PR and a deprecation PR, once CI passes

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Pull request closed without merging**
