### PR TITLE
[Merged by Bors] - feat: `swap` and `compl` of order relations

### PR DESCRIPTION
**Pull request by vihdzp**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by YaelDillies — COMMENTED** [review]
Are you sure those should be simp lemmas? I'm slightly scared of simp rewriting relations fed to instances like `CovariantClass`/`ContravariantClass`

**Comment by YaelDillies** [comment]
A bit wary, but okay

maintainer merge

**Comment by fpvandoorn** [comment]
Also somewhat wary, but the LHS shouldn't really appear often, so it should be fine.

**Comment by j-loreaux** [comment]
I agree with both Yaël and Floris here. I'm skeptical these should really be `@[simp]`. Likely they won't do much damage for the reason Floris mentioned, but I would prefer not to put them in unless there is a good reason.

@vihdzp can you explain why you need these to be `@[simp]`?

**Comment by vihdzp** [comment]
In reality I don't actually need them to be simp. I'll remove the attributes.

**Comment by fpvandoorn** [comment]
Oh, I did intent to `bors merge` on my previous message, but without simp is maybe a bit better.

bors merge

**Comment by vihdzp** [comment]
Is bors down? Why did this fail?

**Comment by YaelDillies** [comment]
Network issue, it seems

**Comment by fpvandoorn** [comment]
bors merge
bors d+

**Comment by vihdzp** [comment]
Maybe if I merge master?
bors r+

**Comment by fpvandoorn** [comment]
Weird that it took so many tries, and then suddenly worked again, the *second* time after merging master...

**Pull request closed without merging**
