### PR TITLE
[Merged by Bors] - fix: add space in no_lost_declarations regex

### PR DESCRIPTION
**Pull request by adomani**
As [reported](https://github.com/leanprover-community/mathlib4/pull/14048#issuecomment-2185315293) and [requested](https://github.com/leanprover-community/mathlib4/pull/14048#issuecomment-2185933007) by Yael!

I think that this change is an improvement, but I would be happier if there was a consensus that the `def`, `theorem`, `structure`,... keywords are followed by a space and not a line break before their identifier.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
> ### PR summary [fb2f0634d0](https://github.com/leanprover-community/mathlib4/pull/14080/commits/fb2f0634d05439f1fc653462ee85dc4619b25b30)
> #### Import changes
> No significant changes to the import graph
> 
> #### Declarations diff
> `- testingLongDiff4`
> 
> You can run this locally as follows

Note that the script omitted the `instance.` that appears as a test.

**Comment by YaelDillies** [comment]
Thanks!

maintainer merge

**Comment by semorrison** [comment]
Still marked as draft, so I'll just

bors d+

**Comment by adomani** [comment]
bors r+

Thanks!

**Comment by YaelDillies** [comment]
maintainer merge

Maybe @semorrison is not allowed to delegate? 🤔

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
