### PR TITLE
[Merged by Bors] - feat: port/CategoryTheory.Abelian.Homology

### PR DESCRIPTION
**Pull request by kim-em**
---

- [x] depends on: #3843

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3843
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3843~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by mattrobball** [comment]
Two timeouts remain. They do not occur with the `gebner/lean4:reenableeta230506` toolchain. Leaving as is for now.

**Pull request closed without merging**
