### PR TITLE
[Merged by Bors] - move(Algebra/Parity): Split file

### PR DESCRIPTION
**Pull request by YaelDillies**
Parity of elements in a group/ring is a basic algebraic concept, but it currently requires importing a bunch of algebraic order theory. As a consequence, `Algebra.Parity` currently holds a bunch of lemmas that really belong in earlier files but cannot due to import cycles.

This PR moves the content of `Algebra.Parity` to
* `Algebra.Group.Even` for the definition of `IsSquare` and `Even`
* `Algebra.Ring.Parity` for the definition of `Odd` and ring properties of `Even`
* `Algebra.Order.Group.Abs`, `Algebra.Order.Ring.Abs`, `Algebra.Order.Ring.Canonical`, `Algebra.Order.Sub.Canonical`, `Algebra.GroupPower.Order` for the various algebraic order properties of `Even` and `Odd`

As a result, `Even`/`Odd` are available much more widely without awkward dependencies and algebraic order lemmas are now in the correct files. The only slight downfall is that two lemmas in `Algebra.Ring.Parity` are stated using `Set.range`, hence I had to weaken a few `assert_not_exists` to forbidding `Data.Set.Basic` instead of `Data.Set.Defs`. This is inconsequential.

A side-effect of this PR is that I had to move some `bit0`/`bit1` lemmas. I could not find anywhere sensible to put them, so I am currently keeping them in `Algebra.Parity`. As a result, I had to reprove a few lemmas in `Algebra.GroupPower.Order`. I took the opportunity to generalise them.

This is a followup to https://github.com/leanprover-community/mathlib/pull/17391 motivated by https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Mathlib.2EAlgebra.2EAssociated and the move-only part of #11863.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
Yaël, thank you for the new PR, as this gives me a way of testing some improvements to the `no_lost_declarations` script!

This is a summary of just the names that have changed in this PR:
```
+ Additive.instDecidablePredEven
- even_abs
+ isSquare_mabs
+ Multiplicative.instDecidablePredIsSquare
```

Does this seem a reasonable output?

**Comment by YaelDillies** [comment]
`- even_abs` is incorrect as `isSquare_mabs` gets additivised to `even_abs`. I guess your script doesn't know about `to_additive`?

**Comment by adomani** [comment]
The script is just text-based and it is supposed to be a quick check that does not require CI to have run.  So, I think that it is fair if it flags as missing a `to_additivized` lemma.

The main idea is to help focus from the +474-478 lines to just checking the 4 highlighted lemmas.

This seems like a good simplification for reviewers.

**Comment by YaelDillies** [comment]
Yeah, makes sense. The rest of the list looks good.

**Comment by adomani** [comment]
Ok, thanks for confirming.  I will make the very short diff available as an option, then.

**Review by Ruben-VandeVelde — APPROVED** [review]
Thanks!

maintainer merge

**Comment by adomani** [comment]
Thanks for the report!

I can remove the extra ``` `` ``` easily.  I would have to think about omitting the `[inst]`, though, since this is one place where there is no name after `instance` and then it is unclear what should be used for comparison.

**Comment by adomani** [comment]
#12866

**Pull request closed without merging**
