### PR TITLE
[Merged by Bors] - fix: disable autoImplicit globally

### PR DESCRIPTION
**Pull request by eric-wieser**
Autoimplicits are [highly controversial](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/.60autoImplicit.20true.60.20is.20evil/near/355142480) and also [defeat the performance-improving work](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/autoimplicit.20and.20Type*/near/383878932) in #6474.

The intent of this PR is to make `autoImplicit` opt-in on a per-file basis, by disabling it in the lakefile and enabling it again with `set_option autoImplicit true` in the few files that rely on it.

That also keeps this PR small, as opposed to attempting to "fix" files to not need it any more.

I claim that many of the uses of `autoImplicit` in these files are accidental; situations such as:

* Assuming `variables` are in scope, but pasting the lemma in the wrong section
* Pasting in a lemma from a scratch file without checking to see if the variable names are consistent with the rest of the file
* Making a copy-paste error between lemmas and forgetting to add an explicit arguments.

Having `set_option autoImplicit false` as the default prevents these types of mistake being made in the 90% of files where `autoImplicit`s are not used at all, and causes them to be caught by CI during review.

I think there were various points during the port where we encouraged porters to delete the `universes u v` lines; I think having autoparams for universe variables only would cover a lot of the cases we actually use them, while avoiding any real shortcomings.

[A Zulip poll](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/mathlib4.3A.20autoImplicit.20false.20by.20default.3F/near/384265143) (after combining overlapping votes accordingly) was in favor of this change with `5:5:18` as the `no:dontcare:yes` vote ratio.

While this PR was being reviewed, a handful of files gained some more likely-accidental autoImplicits. In these places, `set_option autoImplicit true` has been placed locally within a section, rather than at the top of the file.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
Can you make one with it completely turned off to benchmark?

**Comment by eric-wieser** [comment]
That's a lot more work (and a lot more controversial). I assume you already realize, but I would expect the performance effect of the PR in its current form to be completely neutral. The goal for now is to limit the scope for accidental introduction of autoimplicits.

**Comment by mattrobball** [comment]
Yes. I would expect nothing to change performance wise. My point is that if we autoimplicit is itself is not performance neutral then that will need to be considered in whatever decision is reached.

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Comment by eric-wieser** [comment]
bors r-

Looks like a fix is needed first

**Comment by eric-wieser** [comment]
bors p=10

**Comment by eric-wieser** [comment]
bors merge

**Comment by eric-wieser** [comment]
bors merge

(Another set of PRs got merged and made this rot again. Apologies for hogging the queue, but if I don't the finish line will constantly be one step away)

**Comment by eric-wieser** [comment]
bors merge

This finally passes locally; the previous bors commands were just to ensure that another batch didn't force another 2 hour build/fix-iteration cycle on me.

**Pull request closed without merging**
