### PR TITLE
refactor(GroupTheory/Submonoid/Operations): Use `SubmonoidClass` and delete redundant instances

### PR DESCRIPTION
**Pull request by tb65536**
This PR refactors some `SMul` instances in `GroupTheory/Submonoid/Operations.lean` to use `SubmonoidClass`. This makes many other similar instances redundant.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
This seems like a good move. Let's also bench it.

!bench

**Comment by jcommelin** [comment]
!bench

**Comment by jcommelin** [comment]
@tb65536 Given this bench result, what do you think? Do you want to attempt to improve performance, or shall we punt on this?

**Comment by tb65536** [comment]
Probably just punt for now.

**Pull request closed without merging**
