### PR TITLE
[Merged by Bors] - feat(Archive/Imo): formalize IMO 1961q3

### PR DESCRIPTION
**Pull request by urkud**
---

- [x] depends on: #9881
- [x] depends on: #9878

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Is this PR ready for review?

**Comment by urkud** [comment]
Some docs are missing and I have no time to write them.

**Comment by joneugster** [comment]
It appears to me that this PR is in a reasonably good shape and it would be more desirable to have it in `Archive` as-is instead of waiting for more documentation (it's also not clear to me what documentation is supposedly missing). I suggest

maintainer merge

**Pull request closed without merging**
