### PR TITLE
[Merged by Bors] - feat: port CategoryTheory.Monoidal.End

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
TODOs:

- [ ] Fix `obj_μ_inv_app`
- [ ] handle simpNF linters
- [ ] remove lines with ` ambiguous notation` warning

**Comment by jcommelin** [comment]
What is the reason that you add `nolint simpNF`? Please document this for each case in a porting note.

**Comment by mo271** [comment]
> nolint simpNF



> What is the reason that you add `nolint simpNF`? Please document this for each case in a porting note.

I added porting note in all 4 cases. It seems that it thinks that it can use the lemme itself somehow in simp, or a `_assoc` version of that lemma. Perhaps this is a bug in the linter?!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
