### PR TITLE
[Merged by Bors] - feat: `essSup` of the uniform measure

### PR DESCRIPTION
**Pull request by YaelDillies**
From LeanAPAP

---

- [x] depends on: #17571

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by RemyDegenne** [comment]
Same comment as on the other PR that included that code: I'd be sad if the standard way to write the uniform distribution in Mathlib was `.count[|.univ]` and the standard way to talk about it in a name was `cond_count`. Nodoby but the initiated would find those.

You should introduce a definition named `discreteUniform` or `finiteUniform` or something similar, defined with `.count[|.univ]`  or directly with count and a smul. Add the minimal amount of API to make it usable, then use it in this PR. A uniform distribution on a finite type is common and useful enough to warrant a definition.

**Comment by YaelDillies** [comment]
The good thing about Yury's proposal is that sometimes we consider uniform distributions over a subset of the full type. This happens in additive combinatorics at least.

Is that an argument for renaming `ProbabilityTheory.condCount` to `ProbabilityTheory.discreteUniform`?

**Comment by RemyDegenne** [comment]
I think you are right, renaming `condCount` would be a simple and effective solution to the issue.

**Comment by RemyDegenne** [comment]
Thanks!
bors r+

**Pull request closed without merging**
