### PR TITLE
[Merged by Bors] - feat: port Topology.Algebra.Order.UpperLower

### PR DESCRIPTION
**Pull request by mo271**
- [x] depends on: #2344

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
`comm_semigroup.is_central_scalar` recently changed (got `to_additive`) and apparently `group_theory/group_action/opposite` needs some syncing or something...

**Comment by mo271** [comment]
already in progress, I see: https://github.com/leanprover-community/mathlib4/pull/2344

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2344
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2344~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
