### PR TITLE
[Merged by Bors] - feat: port of Data.FunLike

### PR DESCRIPTION
**Pull request by kim-em**
This is a very naive port of `data.fun_like`. I've never really engaged with this classes in mathlib3, and I haven't attempted to think about how they might work in Lean 4...

This PR is really just provocation, hoping that @Vierkantor may come and have a look. :-)

### CODE REVIEW

**Comment by Vierkantor** [comment]
Going through a few reviews at the moment, and then I'll take a look at this and #550 :)

**Review by Vierkantor — APPROVED** [review]
With my current knowledge of Lean 4 I think this port in good shape, and it seems to work well for `equiv`, but I'm sure we'll run into some annoying detail once we get into more complicated stuff like `semilinear_map_class`.

**Comment by gebner** [comment]
I've added a commit which registers `FunLike.coe` as a coercion function so that `norm_cast` works.

bors d+

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
