### PR TITLE
[Merged by Bors] - chore: move gcd_eq_one_of_gcd_mul_right_eq_one_* earlier

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
These don't use any abstract algebra.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — APPROVED** [review]
Looks good to me; thank you for doing this.

**Comment by grunweg** [comment]
Note that replacing the lemma uses is also done in #12347 (as part of a larger change).

**Review by YaelDillies — APPROVED** [review]
maintainer merge

**Comment by fpvandoorn** [comment]
bors merge

**Comment by Ruben-VandeVelde** [comment]
bors merge

**Pull request closed without merging**
