### PR TITLE
[Merged by Bors] - CI: add maintainer delegate from comment

### PR DESCRIPTION
**Pull request by adomani**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
myself merge

**Comment by adomani** [comment]
myself merge

**Comment by adomani** [comment]
myself merge

**Comment by adomani** [comment]
myself merge

**Comment by adomani** [comment]
myself merge

**Review by bryangingechen — APPROVED** [review]
Let's test it out!
bors r+

**Pull request closed without merging**
