### PR TITLE
[Merged by Bors] - refactor: generalize `SMul (Ideal R) (Submodule R M)` to `SMul (Submodule R A) (Submodule R M)`

### PR DESCRIPTION
**Pull request by alreadydone**
and redefine `Mul (Submodule R A) (Submodule R A)` using the latter.

---

- [x] depends on: #19711

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alreadydone** [comment]
!bench

**Comment by jcommelin** [comment]
!bench

**Comment by alreadydone** [comment]
I think we won't get bench comparison unless we change the base branch or merge `Ideal.mul` (#17708) first ...

**Comment by alreadydone** [comment]
!bench

**Comment by riccardobrasca** [comment]
Can you please merge master and bench again?

**Comment by alreadydone** [comment]
!bench

**Comment by alreadydone** [comment]
Hmm, looks like a rather positive change! `Mathlib.Algebra.Algebra.Operations` got 15.7% slower but also 12.2% longer.

**Comment by alreadydone** [comment]
> Hmm, looks like a rather positive change! `Mathlib.Algebra.Algebra.Operations` got 15.7% slower but also 12.2% longer.

Sorry, false alarm. The sped-up files were changed to avoid timeouts. Let me single those out to a separate PR ...

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
