### PR TITLE
[Merged by Bors] - chore: rename `MulEquiv.mulEquivOfUnique` to `MulEquiv.ofUnique`

### PR DESCRIPTION
**Pull request by YaelDillies**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by alreadydone — APPROVED** [review]
Deprecation please
maintainer delegate

**Comment by YaelDillies** [comment]
> Deprecation please

This is why it was WIP 😁

**Review by jcommelin — COMMENTED** [review]
Please add/inherit the docstring

bors d+

**Comment by urkud** [comment]
Should other similar definitions be renamed in the same batch? Here is the output of `git grep 'def.*OfUnique'`, probably contains some false positives:
```bash
$ git grep 'def.*OfUnique'
Mathlib/Algebra/GCDMonoid/Basic.lean:  default := normalizationMonoidOfUniqueUnits
Mathlib/Algebra/GCDMonoid/Basic.lean:def associatesEquivOfUniqueUnits : Associates α ≃* α where
Mathlib/Algebra/Group/Equiv/Basic.lean:def mulEquivOfUnique {M N} [Unique M] [Unique N] [Mul M] [Mul N] : M ≃* N :=
Mathlib/Algebra/Group/Equiv/Basic.lean:  default := mulEquivOfUnique
Mathlib/Algebra/Ring/Equiv.lean:def ringEquivOfUnique {M N} [Unique M] [Unique N] [Add M] [Mul M] [Add N] [Mul N] : M ≃+* N :=
Mathlib/Algebra/Ring/Equiv.lean:  default := ringEquivOfUnique
Mathlib/CategoryTheory/Limits/Shapes/Biproducts.lean:def limitBiconeOfUnique [Unique J] (f : J → C) : LimitBicone f where
Mathlib/CategoryTheory/Limits/Shapes/ConcreteCategory.lean:noncomputable def terminalOfUniqueOfReflects [ReflectsLimit (Functor.empty.{0} C) (forget C)]
Mathlib/CategoryTheory/Limits/Shapes/Products.lean:def limitConeOfUnique [Unique β] (f : β → C) : LimitCone (Discrete.functor f) where
Mathlib/CategoryTheory/Limits/Shapes/Products.lean:def colimitCoconeOfUnique [Unique β] (f : β → C) : ColimitCocone (Discrete.functor f) where
Mathlib/CategoryTheory/Limits/Shapes/Types.lean:noncomputable def typeEqualizerOfUnique (t : ∀ y : Y, g y = h y → ∃! x : X, f x = y) :
Mathlib/Data/FinEnum.lean:  default := ⟨1, Equiv.equivOfUnique α (Fin 1)⟩
Mathlib/Logic/Equiv/Defs.lean:def equivOfUnique (α β : Sort _) [Unique.{u} α] [Unique.{v} β] : α ≃ β where
Mathlib/Logic/Equiv/Defs.lean:def equivPUnit (α : Sort u) [Unique α] : α ≃ PUnit.{v} := equivOfUnique α _
Mathlib/MeasureTheory/MeasurableSpace/Embedding.lean:def ofUniqueOfUnique (α β : Type*) [MeasurableSpace α] [MeasurableSpace β] [Unique α] [Unique β] :
Mathlib/Order/RelIso/Basic.lean:def relIsoOfUniqueOfIrrefl (r : α → α → Prop) (s : β → β → Prop) [IsIrrefl α r]
Mathlib/Order/RelIso/Basic.lean:def relIsoOfUniqueOfRefl (r : α → α → Prop) (s : β → β → Prop) [IsRefl α r] [IsRefl β s]
Mathlib/Topology/CompactOpen.lean:def continuousMapOfUnique [Unique X] : Y ≃ₜ C(X, Y) where
Mathlib/Topology/Homeomorph.lean:def homeomorphOfUnique [Unique X] [Unique Y] : X ≃ₜ Y :=
Mathlib/Topology/Homotopy/HomotopyGroup.lean:def genLoopEquivOfUnique (N) [Unique N] : Ω^ N X x ≃ Ω X x where
Mathlib/Topology/Homotopy/HomotopyGroup.lean:def homotopyGroupEquivFundamentalGroupOfUnique (N) [Unique N] :
```

**Pull request closed without merging**
