### PR TITLE
[Merged by Bors] - feat: improve curl invocation

### PR DESCRIPTION
**Pull request by Kha**
---
~~No error feedback yet,~~ but this should already improve things quite a bit in practice

/cc @arthurpaulino @gebner

### CODE REVIEW

**Comment by arthurpaulino** [comment]
Does this require any bump on the `curl` versions that we [require/recommend](https://github.com/leanprover-community/mathlib4/blob/8c7b65ad8326d1219cff9e2e020db7b7d6fcee26/Cache/IO.lean#L80)?

**Comment by Kha** [comment]
Oh no, `--remove-on-error` does require 7.83.0 - April 27 2022. Ugh.

**Comment by Kha** [comment]
According to Repology, the only interesting distribution that has 7.69 but not 7.70 is Fedora 32, which is far EOL

**Comment by Kha** [comment]
I removed `--retry` again because it seems to hang on 7.70. Let's wait and see what errors people actually trigger first.

**Comment by gebner** [comment]
bors r+

We should probably also download the files to a temporary directory first, so that ctrl+c doesn't leave partial downloads behind.

**Comment by Kha** [comment]
> We should probably also download the files to a temporary directory first, so that ctrl+c doesn't leave partial downloads behind.

Then we'll just need an `IO` function for moving files first, heh. Or shell out again.

**Comment by Kha** [comment]
By the way, this could be trivially extended with a progress display, except I didn't want to worry about what to display on CI without access to `isatty()`

**Pull request closed without merging**
