### PR TITLE
[Merged by Bors] - chore: cleanup in Mathlib.Init

### PR DESCRIPTION
**Pull request by kim-em**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
Thanks :tada: 

If CI passes, please remove the label `awaiting-CI` and merge this yourself, by adding a comment `bors r+`.

bors d+

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
This is clashing with #6971 with bors. To save some time (they are both waiting to run), I'm just going to merge that into this PR.

**Comment by semorrison** [comment]
bors p=10

bors merge

**Pull request closed without merging**
