### PR TITLE
chore: bump gh-problem-matcher github action, to silence confusing messages

### PR DESCRIPTION
**Pull request by kim-em**
Resolving a [confusion](https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/tarski.20axiom.20geometry/near/392618240) reported on zulip, and recently patched in the Github action. https://github.com/liskin/gh-problem-matcher-wrap/pull/16

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alexjbest** [comment]
I was wrong to be so pessimistic about this being resolved upstream so quickly, nice!

**Comment by alexjbest** [comment]
I'm not sure this PR is actually needed though. Following the apparent GH actions conventions the v2 tag for problem matcher looks to be already tracking the minor version number also (i.e. v2 now points at v2.02 already) so explicitly pinning this minor version just means we won't automatically receive future improvements.

**Comment by alexjbest** [comment]
I just checked some recent logs and indeed I can't see the remove matcher line so indeed this seems like it just pins us to an old version (which doesn't seem helpful to me)

**Comment by semorrison** [comment]
Thanks for catching that, @alexjbest, I hadn't known.

**Pull request closed without merging**
