### PR TITLE
[Merged by Bors] - chore(deps): dependabot updates

### PR DESCRIPTION
**Pull request by bryangingechen**
Doing this manually because dependabot doesn't know how to update build.in.yml.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

Subsumes: #18017,  #18018, #18019, #18020, #18021, #18022

### CODE REVIEW

**Review by pitmonticone — APPROVED** [review]

**Comment by adomani** [comment]
Could we create a symlink to `build.in.yml` in `workflows`, so that dependabot edits this file as well?

**Comment by bryangingechen** [comment]
> Could we create a symlink to `build.in.yml` in `workflows`, so that dependabot edits this file as well?

I'm not sure if symlinks work, but maybe we could try using the [`directories` config option](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories) with both `.github` and `.github/workflows` explicitly (in a different PR?).

**Comment by adomani** [comment]
Yes, definitely no in this PR!

Thanks!

maintainer merge

**Comment by kim-em** [comment]
bors merge

**Pull request closed without merging**
