### PR TITLE
[Merged by Bors] - fix: patch for std4#197 (More add lemmas for `Nat`)

### PR DESCRIPTION
**Pull request by fgdorais**
---

- [x] depends on: https://github.com/leanprover/std4/pull/197

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by kim-em — APPROVED** [review]
Changes here all look reasonable to me, I would be happy to merge once the Std commit lands and this is updated to master.

**Comment by semorrison** [comment]
bors d+

(Obivously it will need to wait for Std.)

**Comment by fgdorais** [comment]
bors merge

**Pull request closed without merging**
