### PR TITLE
[Merged by Bors] - chore(InnerProductSpace/PiL2): `Fintype m` -> `Finite m`

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Looks reasonable, thanks!
maintainer merge

**Comment by j-loreaux** [comment]
Seems a relatively small gain, especially since `n` is still required to be a `Fintype`. I assume the `Fintype n` condition cannot be replaced with `Finite n` anywhere? Either way:

bors d+

**Comment by urkud** [comment]
@j-loreaux Yes, I'm just fixing errors reported by a linter I'm writing.

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
