### PR TITLE
[Merged by Bors] - feat(Counterexamples/DiscreteTopologyNonDiscreteUniformity): add a counterexample about discrete uniformity and Cauchy filters

### PR DESCRIPTION
**Pull request by faenuccio**
We construct a non-discrete uniformity on `ℕ` that induces the discrete topology and admits a non-principal Cauchy filter (actually, the identity sequence is Cauchy).

---

### CODE REVIEW

**Comment by ADedecker** [comment]
Do you care about the particular form of the counterexample ? If not, I think you can do much less work (and get a metric structure as a bonus) by endowing `ℕ` with the distance induced by the injection `fun n : ℕ ↦ (2 : ℝ) ^ (-n : ℤ)`. Then the identity is obviously Cauchy, and the topology is discrete because the singleton `{n}` is the preimage of the open set `Ioo ((2 : ℝ) ^ (-n - 1 : ℤ)) ((2 : ℝ) ^ (-n+1 : ℤ))`.

**Review by faenuccio — COMMENTED** [review]
> Do you care about the particular form of the counterexample ? If not, I think you can do much less work (and get a metric structure as a bonus) by endowing `ℕ` with the distance induced by the injection `fun n : ℕ ↦ (2 : ℝ) ^ (-n : ℤ)`. Then the identity is obviously Cauchy, and the topology is discrete because the singleton `{n}` is the preimage of the open set `Ioo ((2 : ℝ) ^ (-n - 1 : ℤ)) ((2 : ℝ) ^ (-n+1 : ℤ))`. 

Oh nice, this example did not cross my mind! I must say that
1. I kind of like my counterexample because it has a "point-set topology" flavour, without any distance, and I like the idea of playing with uniformities simply as filters. But this can be reversed as in "I do not like your counterexample due to its point-set topology flavour..." ;-).
2. Implementing yours does not seems 100% straightforward: since `ℕ` is not a group, it won't be a (semi)NormedAddGroup. I think that what you have in mind is the distance `dist (x, y) := (2 : ℝ) ^ (- |(x : ℤ) - (y : ℤ)|)) but for which there is very little API, so one would need to prove from first principles that it is a distance, no (like triangle inequality, symmetric, etc...). I am not saying it is "hard", just that AFAIU it is not a 10-lines application of things in the library (of course, I am going all-in saying this to you... bear with me).
3. All in all, I am happy to do whatever you suggest, from just forgetting about this counterexample, to implementing both, to having this one go first and at a second stage implement your example... What's your preference?

**Comment by ADedecker** [comment]
Let me start by answering the more technical things:
- The distance I had in mind is not `2 ^ (- |x - y|))` but `|2 ^ (- x) - 2 ^ (- y)|`, which *is* really easy to define (as a distance) using [MetricSpace.induced](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Topology/MetricSpace/Basic.html#MetricSpace.induced). In other words it's the only distance on `ℕ` for which `n ↦ 2 ^ (-n)` is an isometry. That said...
- ... once I put it like this, I realize that the "pulling back the distance to `ℕ`" part is really just making things more confusing. The "real" counterexample behind my suggestion is to consider the subset `S : Set ℝ := {2 ^ (-n : ℤ) | n : ℤ}`, and endow it with the induced topologies and uniformities. Then it is both discrete as a topological space, and non-closed (hence non-complete), so the uniformity can't be discrete because [UniformSpace.DiscreteUnif.cauchyConst](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Topology/UniformSpace/Cauchy.html#UniformSpace.DiscreteUnif.cauchyConst) forces completeness.
- Fun side note: my counterexample (in its original version, where you pull back the distance to `ℕ`) and yours are *exactly* the same! Indeed, your `n`-th fundamental entourage is the set of point which are at distance `< 2 ^ (-n)`.

This brings me to why I prefer my presentation: to me, the very manually crafted definition suggests "this is pathological behavior, you won't learn anything by reading the details". So it would feel more instructive to read a lemma saying "any non-closed but discrete subset of a uniform space is a counter example" (followed of course by a concrete construction of such a subset). So, if that makes sense to you, I think I would prefer having at least this version come first in the file.

**Comment by faenuccio** [comment]
> Let me start by answering the more technical things:
> 
> * The distance I had in mind is not `2 ^ (- |x - y|))` but `|2 ^ (- x) - 2 ^ (- y)|`, which _is_ really easy to define (as a distance) using [MetricSpace.induced](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Topology/MetricSpace/Basic.html#MetricSpace.induced). In other words it's the only distance on `ℕ` for which `n ↦ 2 ^ (-n)` is an isometry. That said...
> * ... once I put it like this, I realize that the "pulling back the distance to `ℕ`" part is really just making things more confusing. The "real" counterexample behind my suggestion is to consider the subset `S : Set ℝ := {2 ^ (-n : ℤ) | n : ℤ}`, and endow it with the induced topologies and uniformities. Then it is both discrete as a topological space, and non-closed (hence non-complete), so the uniformity can't be discrete because [UniformSpace.DiscreteUnif.cauchyConst](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Topology/UniformSpace/Cauchy.html#UniformSpace.DiscreteUnif.cauchyConst) forces completeness.
> * Fun side note: my counterexample (in its original version, where you pull back the distance to `ℕ`) and yours are _exactly_ the same! Indeed, your `n`-th fundamental entourage is the set of point which are at distance `< 2 ^ (-n)`.
> 
> This brings me to why I prefer my presentation: to me, the very manually crafted definition suggests "this is pathological behavior, you won't learn anything by reading the details". So it would feel more instructive to read a lemma saying "any non-closed but discrete subset of a uniform space is a counter example" (followed of course by a concrete construction of such a subset). So, if that makes sense to you, I think I would prefer having at least this version come first in the file.

Oh, very nice! After your explanation I certainly agree that your example should appear. To my eyes, the best presentation would be
1. The definition of your distance
1. The definition of my uniformity
1. The proof that `(your distance).toUniformity` = `my uniformity`
and somewhere (probably between 1. and 2.) the proof that this induces the discrete topology (whatever proof is shorter).

This would certainly require to add your distance in the docstring before my uniformity and to add the proof of the equality. I am desperately out of time now, so I would be very happy if you want to enforce this (if you agree with the plan). But you might be equally out of time, in which case we can let this wait (and hopefully not rotten)...

**Comment by faenuccio** [comment]
@ADedecker Do you think that you will reasonably happen to have a bit of time in the not-so-distant future to work a bit on this file? Since you have a somewhat clear idea on how you would want it to look like, and I am happy to follow your suggestions, I would prefer to avoid some trial-and-error, just doing stuff and then having to revert it back. Do you find it reasonable if I suggest one of the two following options:
1. We merge it as it is, but adding more doc (and a TODO) mentioning that this construction actually comes from that metric, and saying that it would be nice if in the future someone (some student of mine during a small internship :smirk: ?) re-opens the file and improves it with your suggestion; or
2. You at least propose a sorried skeleton and I start from there.

Thanks for your feedback!

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
