### PR TITLE
[Merged by Bors] - feat: add decidable instance to  ∈ singleton

### PR DESCRIPTION
**Pull request by arienmalec**
Adds `Decidable (j ∈ ({a} : Set α))` to help Lean 4 infer instances that Lean 3 automatically found

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by arienmalec** [comment]
> bors r+

Didn't merge...

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
