### PR TITLE
[Merged by Bors] - chore: replace `set_integral` with `setIntegral`

### PR DESCRIPTION
**Pull request by sgouezel**
Done with a global search and replace, and then (to fix the `#align` lines), replace `(#align \S*)setIntegral` with `$1set_integral`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Thank you for doing this! My only comment be a lot of work: can you add deprecation aliasses to all the definitions, lemmas and theorems you're renaming? Actually: I think it shouldn't be too hard to write a script to do this. Hang on...

**Comment by sgouezel** [comment]
Such a script already exists somewhere, let me try to find it on Zulip.

**Comment by sgouezel** [comment]
I found the script, see https://github.com/leanprover-community/mathlib4/pull/10185#issuecomment-1925481325. I have it running on the PR, I'll upload the result once it's done.

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Pull request closed without merging**
