### PR TITLE
[Merged by Bors] - feat: port Analysis.BoundedVariation

### PR DESCRIPTION
**Pull request by urkud**
This PR also corrects a mis-forward-port of leanprover-community/mathlib#18080

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
@urkud still working on this?

**Comment by urkud** [comment]
Yes

**Comment by j-loreaux** [comment]
I'm currently working on this.

**Comment by jcommelin** [comment]
@j-loreaux for some reason github doesn't want to show me the diff between mathport output and the HEAD of the PR branch. Did you maybe push in a funny way?

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
