### PR TITLE
[Merged by Bors] - fix: don't resynthesize type class arguments in `fun_prop`

### PR DESCRIPTION
**Pull request by lecopivo**
`fun_prop` was resynthesizing type class arguments the same way as  `simp` used to do. It seems to cause just troubles and seemingly no benefit so let's remove it from `fun_prop` too.

### CODE REVIEW

**Comment by j-loreaux** [comment]
!bench

**Comment by j-loreaux** [comment]
I don't understand at all why this would make anything *slower*. I will note that the places using `fun_prop` the most (continuous functional calculus files) did get marginally faster.

**Comment by lecopivo** [comment]
I also find it baffling. My wild guess is that type classes are cached anyway so resynthesizing them is not such a big deal. However, you might end up with instances that are defeq but not trivially so type checking takes longer.

But I do not know what the "instructions" metric is.

**Comment by j-loreaux** [comment]
Instructions are the best proxy we have for "amount of computation done independent of hardware"

**Comment by lecopivo** [comment]
Do we want to merge this? Is the 16% increase on that one file a blocker? Should that be investigated?

**Comment by j-loreaux** [comment]
I'm not entirely sure about this. It does speed things up a bit in the continuous functional calculus portion of the library, where we use `fun_prop` heavily, but I don't have a good understanding of the slowdown in the Sobolev file.

maintainer merge

**Comment by mattrobball** [comment]
Overall instructions are basically flat. So from that perspective this is fine. I think the slowdown you see is exactly as @lecopivo surmised (and as core would probably chastise us for). But if this works where it needs to right now, I think it is ok to run with and evaluate as we go.

bors merge

**Comment by sgouezel** [comment]
bors r-
Can you merge master, fix the lint, and then send it back to bors?
bors d+

**Pull request closed without merging**
