### PR TITLE
[Merged by Bors] - chore: Remove algebra imports to `Data.Fin.Basic`

### PR DESCRIPTION
**Pull request by YaelDillies**
Move the algebraic instance on `Fin n` from `Data.Fin.Basic` to a new file `Algebra.Group.Fin`. I credit Yakov for https://github.com/leanprover-community/mathlib/pull/5010.

The one bit of algebra that is still imported in `Data.Fin.Basic` is `NeZero`. This is in prevision of its future upstreaming to Batteries or Std.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Comment by YaelDillies** [comment]
> * `+` [NeZero

@adomani, another formatting issue here!

**Comment by adomani** [comment]
This presumably comes from a nameless instance: do you have any suggestion of what to print instead?

**Comment by YaelDillies** [comment]
Probably `instance : typeOfInstance` is fine, even if `typeOfInstance` doesn't contain all the binders (because some of them are declared in `variable` and you're using a regex).

**Comment by adomani** [comment]
@YaelDillies, with the changes in #12935, the `move-decls` bot would have report what is below for this PR:

---

* `+` instance [NeZero n] {a : ℕ} : OfNat (Fin n) a where
* `+` instNatCast
* `+` natCast_def

**Comment by YaelDillies** [comment]
Amazing! Can you get rid of `where`/`:=`? That's just noise here

**Comment by adomani** [comment]
With the update that I just pushed, you would see here:

---

* `+` instance [NeZero n] {a : ℕ} : OfNat (Fin n) a
* `+` instNatCast
* `+` natCast_def

**Comment by jcommelin** [comment]
bors merge

**Comment by YaelDillies** [comment]
> With the update that I just pushed, you would see here:
> 
> * `+` instance [NeZero n] {a : ℕ} : OfNat (Fin n) a
> * `+` instNatCast
> * `+` natCast_def

Is there a reason why the backticks are around the `+` and `-` instead of around the lemma names?

**Pull request closed without merging**
