### PR TITLE
[Merged by Bors] - feat: port Topology.Algebra.UniformMulAction

### PR DESCRIPTION
**Pull request by mcdoll**
---

- [x] depends on: #2480 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2480
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by mcdoll** [comment]
Possibly blocked by leanprover/lean4#2074 and some issues with `to_additive`

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2480~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
