### PR TITLE
[Merged by Bors] - chore: Split `RingTheory.FractionalIdeal.Basic`

### PR DESCRIPTION
**Pull request by xroblot**
The file `RingTheory.FractionalIdeal.Basic` is more than 1600 lines long. This PR splits it into two files: `Basic` and `Operations` following the model of `RingTheory.Ideal.Basic` and `RingTheory.Ideal.Operations`

 ---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by riccardobrasca** [comment]
Should we wait a couple of hours and merge the other PR before splitting?

**Comment by xroblot** [comment]
> Should we wait a couple of hours and merge the other PR before splitting?

Let's merge this one first and then I'll fix the other one and merge it.

**Comment by riccardobrasca** [comment]
Can you describe the splitting in the PR description?

**Comment by riccardobrasca** [comment]
bors d+

**Comment by xroblot** [comment]
Damn, it's the `leantar` error
```
error: /home/lean/.cache/mathlib/e3fcbaaf6ab40bbf.ltar: failed to fill whole buffer
uncaught exception: leantar failed with error code 1
```

**Pull request closed without merging**
