### PR TITLE
feat(Order/InitialSeg): `Subsingleton (α ≃o β)` on well-orders

### PR DESCRIPTION
**Pull request by vihdzp**
This allows us to generalize an instance which stated this for `Fin n`.

---

- [ ] depends on: #16706

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by YaelDillies — COMMENTED** [review]
Can you review what exactly the new transitive imports to `Order.Fin.Basic` are?

**Comment by vihdzp** [comment]
The new imports are
```
import Mathlib.Order.RelIso.Set
import Mathlib.Order.WellFounded
import Mathlib.Data.Sum.Order
```
`Order.WellFounded` is one of the earliest imports, only importing `Data.Set.Basic`. The only import of `Data.Sum.Order` was already in the import chain. `Order.RelIso.Set` only really adds some basic files about relation isomorphisms to the chain.

**Comment by YaelDillies** [comment]
I'll let maintainers decide whether that's acceptable.

maintainer merge

**Comment by fpvandoorn** [comment]
!bench

**Comment by fpvandoorn** [comment]
The last three results in `Order/Fin/Basic` seem also to be generalizable to well-orders, right? 
That would have my preference, because then we can also remove the import added in this PR.

**Comment by vihdzp** [comment]
`coe_orderIso_apply` is specific to `Fin` since it talks about the coercion to ℕ, but it doesn't depend on these results. `strictMono_unique` already exists as [`WellFounded.eq_strictMono_iff_eq_range`](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Order/WellFounded.html#WellFounded.eq_strictMono_iff_eq_range), but this gets renamed to `StrictMono.range_inj` in #16706 and refactored to take in the `WellFoundedLT` typeclass, so it might be better to wait for that PR to get merged. I'll also add `orderEmbedding_eq` to that PR.

**Comment by vihdzp** [comment]
Having `OrderEmbedding.range_inj`, it might even be possible to reprove this without using anything about initial segments.

**Comment by vihdzp** [comment]
Closing in favor of #16882, which proves this earlier in the import chain.

**Pull request closed without merging**
