### PR TITLE
[Merged by Bors] - feat: port CategoryTheory.Abelian.Projective

### PR DESCRIPTION
**Pull request by kbuzzard**
---

- [x] depends on: #4299 
- [x] depends on: #4319 
[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4299
* leanprover-community/mathlib4#4319
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4299~~
* ~~leanprover-community/mathlib4#4319~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by mattrobball** [comment]
The calls to `simp` involving `ofComplex` are still very slow (~8s individually). I am not sure if there is any easy fix so I marked it `awaiting-review` to get maintainer feedback.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
