### PR TITLE
[Merged by Bors] - perf: speed up integrable_rpow_neg_one_add_norm_sq

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
This goes from about 20 seconds to instantaneous locally.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Wow, great find! 20 seconds is really slow...

Can you add a comment saying that this was `measurability`, but has been expanded for performance reasons? (For extra bonus points: is there an issue about this/can you file one? Are the other such lemmas which are slow?)

I'd approve with that - consider this another `maintainer delegate` (i.e., feel free to `maintainer merge on my behalf if you feel you have addressed this - or ask on zulip if you'd like another opinion.)

**Comment by Ruben-VandeVelde** [comment]
Good point, I was going to add a comment but forgot. As far as I understand it, `fun_prop` should replace `measurability` at some point (but it doesn't work yet for this proof), so I don't think anyone will look at an issue.

maintainer merge

**Comment by grunweg** [comment]
Out of curiosity: how did you find this one? Do you know other `measurability` invocations which are really slow?
(If I have some free Lean time and like popping bubble wrap, fixing these could be a nice thing to do :-))

**Comment by Ruben-VandeVelde** [comment]
Purely by accident - I had put a `#minimize_imports` at the end of the file and was waiting for it to run - and waiting - and waiting...

**Comment by fpvandoorn** [comment]
It might also be interesting to see how `fun_prop` does.

bors merge

**Comment by grunweg** [comment]
> Purely by accident - I had put a `#minimize_imports` at the end of the file and was waiting for it to run - and waiting - and waiting...

Oh wow, that was a happy accident! I'll keep an item on my long list of things to investigate.
(Current plan: `set_option profiler true` globally, build mathlib and see which tactic calls stick out. I don't have time to look at this list right now, though.)

**Pull request closed without merging**
