### PR TITLE
[Merged by Bors] - feat: port Algebra.ContinuedFractions.Computation.CorrectnessTerminating

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
Do you have a sense of what `field_simp` is lacking? It would be good to fix this, if you're able to come up with a #mwe.

**Comment by Parcly-Taxel** [comment]
> Do you have a sense of what `field_simp` is lacking? It would be good to fix this, if you're able to come up with a #mwe.

@semorrison If `l1` and `l2` as shown below are used in place of `tmp_calc` and `tmp_calc'`, then with the helper lemma `hfr` (that in similar forms is also needed to fix the two other non-trivial – i.e. more than just fixing names – problems in this file), `ac_rfl` alone (as in the mathport output) closes the goal and the theorem compiles:

```lean
theorem compExactValue_correctness_of_stream_eq_some :
      -- ...
      rw [this]
      -- two calculations needed to show the claim
      have l1 : (↑⌊1 / ifp_n.fr⌋ * pA + ppA) + pA * Int.fract (1 / ifp_n.fr) = (pA * (1 / ifp_n.fr) + ppA) := sorry
      have l2 : (↑⌊1 / ifp_n.fr⌋ * pB + ppB) + pB * Int.fract (1 / ifp_n.fr) = (pB * (1 / ifp_n.fr) + ppB) := sorry
      have : Int.fract (1 / ifp_n.fr) ≠ 0 := by simpa using ifp_succ_n_fr_ne_zero
      -- now unfold the recurrence one step and simplify both sides to arrive at the conclusion
      have hfr : (IntFractPair.of (1 / ifp_n.fr)).fr = Int.fract (1 / ifp_n.fr) := rfl
      field_simp [compExactValue, continuantsAux_recurrence s_nth_eq ppconts_eq pconts_eq,
        nextContinuants, nextNumerator, nextDenominator, this, hfr, l1, l2]
      ac_rfl
```

And `field_simp` cannot turn `tmp_calc` and `tmp_calc'` into `l1` and `l2`. Here's an MWE based on the file:
```lean
import Mathlib.Tactic.FieldSimp

variable {K : Type _} [Field K] {f pA pB pC pD ppA ppB g : K} (h0 : f ≠ 0) (h1 : g ≠ 0)

theorem fails (t1 : pC / f + pA = (pA / g + ppA) / f) (t2 : pD / f + pB = (pB / g + ppB) / f) :
    (ppA * g + pA) / (ppB * g + pB) = (pC + pA * f) / (pD + pB * f) := by
  field_simp [h0, h1, t1, t2]
  ac_rfl

theorem passes (l1 : pC + pA * f = (pA / g + ppA)) (l2 : pD + pB * f = (pB / g + ppB)) :
    (ppA * g + pA) / (ppB * g + pB) = (pC + pA * f) / (pD + pB * f) := by
  field_simp [h0, h1, l1, l2]
  ac_rfl
```

**Comment by semorrison** [comment]
The #mwe doesn't seem right. `field_simp` fails in the same way in mathlib3:

```
import tactic.field_simp

variables {K : Type _} [field K] {f c d x y : K} (h0 : f ≠ 0) (h1 : y ≠ 0)

theorem fails (t1 : c / f = x) (t2 : d / f = y) :
    x / y = c / d :=
begin
  field_simp [t1, t2],
  ac_refl
end
```
I think to understand the regression we need an example where it succeeds in mathlib3 but fails in mathlib4.

**Review by jcommelin — APPROVED** [review]
Thanks :tada: (the `field_simp` issue is documented in a porting note, debugging it can be done orthogonal to this PR)

bors merge

**Pull request closed without merging**
