### PR TITLE
[Merged by Bors] - refactor(MeasureTheory/Function/L1Space): rm two porting notes

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
I'm not sure what #2243 has to do with it, but it is easy to remove.

**Comment by urkud** [comment]
What's wrong about having a `_def` lemma? Why not just drop the porting note?

Recently, we saw that our search tools (e.g., `loogle`) don't show definitional equalities in search output, which makes life harder for new users.

**Comment by mo271** [comment]
> What's wrong about having a `_def` lemma? Why not just drop the porting note?
> 
> Recently, we saw that our search tools (e.g., `loogle`) don't show definitional equalities in search output, which makes life harder for new users.

SGTM, removing two porting notes then.

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Pull request closed without merging**
