### PR TITLE
feat: port  Data.Array.Lemmas

### PR DESCRIPTION
**Pull request by Shreyas4991**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
We don't need to port this, or the downstream dependencies `Data.Buffer.Basic` or `Data.HashMap` as they are only used in meta code and have good alternatives available already in Lean 4.

**Comment by thorimur** [comment]
Reopening this PR and rewriting in terms of `Array` as per [zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/porting.20.60.2Earray.60.20files.20whose.20PR's.20were.20closed.3F)! We also need to match lemmas up with existing lemmas in std and port the remaining ones; eventually, those will end up in std too.

**Comment by jcommelin** [comment]
@Shreyas4991 would you like to pick this up, or would you prefer someone else to take over?

**Comment by Shreyas4991** [comment]
I'd prefer someone else take over, since I currently don't have time for porting.

**Comment by mattrobball** [comment]
Since Std is in the process of designing `DArray` and `Array'` which will more faithfully represent the Lean 3 types, we should wait to port these results. Until then, they have been no-aligned in #5821.

**Pull request closed without merging**
