### PR TITLE
[Merged by Bors] - chore(Init/Data/Nat/Basic): drop lemmas about bit0/bit1

### PR DESCRIPTION
**Pull request by jcommelin**
Deletions:
- nat.bit0_succ_eq
- nat.zero_lt_bit0
- nat.zero_lt_bit1
- nat.bit0_ne_zero
- nat.bit1_ne_zero

---

- [x] depends on: #14788

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Looks good, thanks!
maintainer merge

**Comment by semorrison** [comment]
bors merge

**Comment by urkud** [comment]
It looks like this PR conflicts with #14761. Please merge them in some order.
bors r-
bors d+

**Comment by grunweg** [comment]
Still looks good, thanks!
maintainer merge

**Comment by semorrison** [comment]
Fixing a test and sending back to bors.

bors merge

**Comment by grunweg** [comment]
It seems this PR needs imports shaken.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
