### PR TITLE
[Merged by Bors] - chore: forward-port leanprover-community/mathlib#19234

### PR DESCRIPTION
**Pull request by eric-wieser**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
Can't see anything but a transient SSL error during the bors build here, so I'm merging master to get a fresh CI.

**Comment by eric-wieser** [comment]
bors merge

(CI is green, I assume that's the only reason this was awaiting author)

**Comment by eric-wieser** [comment]
Whoops, misclick

bors merge

**Pull request closed without merging**
