### PR TITLE
[Merged by Bors] - chore(LinearAlgebra–Topology): remove `refine'`

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
Split from #13385; this excludes usages where `refine'` was used to replace `refine_struct` – except where the proofs for each field were already separately written out.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Parcly-Taxel** [comment]
!bench

**Comment by Parcly-Taxel** [comment]
!bench

**Review by adomani — APPROVED** [review]
Looks good to me, thanks!

Here is a summary of the non-`refine'`-to-`refine` changes:
* a couple of `convert`s in `LinearAlgebra`,
* a few scattered `apply`s (I'm not a big fan of `apply` with more than one side-goal, but this is a separate issue),
* some `exact`s -- this is a potential performance issue, but `!bench` does not highlight anything in particular,
* some removed porting notes.

Overall, this is an improvement, in my opinion!

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
