### PR TITLE
[Merged by Bors] - chore: split Algebra.Module.LocalizedModule

### PR DESCRIPTION
**Pull request by jcommelin**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
I think it makes sense to move everything about `IsLocalizedModule` to the new `IsLocalizedModule` file, and only keep the theorems about `LocalizedModule` in the old file. Not sure if it's possible though.
And can you move `Mathlib/Algebra/Module/Submodule/Localization.lean` to `Mathlib/Algebra/Module/LocalizedModule/Submodule.lean`? Thanks!

**Comment by jcommelin** [comment]
The new file imports a large chunk of stuff via the `.*.Bilinear` import. All the other stuff doesn't need that...

**Comment by erdOne** [comment]
Then maybe call it `LocalizedModule/IsLocalization`?

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
