### PR TITLE
[Merged by Bors] - feat(RingTheory/Localization/FractionRing): `fieldEquivOfAlgEquivHom` is injective

### PR DESCRIPTION
**Pull request by tb65536**
This PR adds a short lemma stating that `fieldEquivOfAlgEquivHom` is injective.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Comment by erdOne** [comment]
Note that there's also [`galRestrict`](https://leanprover-community.github.io/mathlib4_docs/Mathlib/RingTheory/IntegralClosure/IntegralRestrict.html#galRestrict) which this might be able to replace.

**Comment by tb65536** [comment]
I think `galRestrict` goes the other way (restricting from the fields to the rings, as opposed to extending from the rings to the fields).

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
