### PR TITLE
[Merged by Bors] - feat: port CategoryTheory.Subobject.FactorThru

### PR DESCRIPTION
**Pull request by joelriou**
---
- [x] depends on: #3444

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3444
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
bors d+

Please merge these in order.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3444~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by joelriou** [comment]
Thanks @semorrison for all these reviews!

bors r+

**Pull request closed without merging**
