### PR TITLE
[Merged by Bors] - chore(Data/Nat/Defs): Integrate `Nat.sqrt` material

### PR DESCRIPTION
**Pull request by YaelDillies**
Move the content of `Data.Nat.ForSqrt` and `Data.Nat.Sqrt` to `Data.Nat.Defs` by using `Nat`-specific Std lemmas rather than the mathlib general ones. This makes it ready to move to Std if wanted.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
No obvious concerns here.

maintainer merge

**Comment by j-loreaux** [comment]
It's a bit weird to me that this is moving *into* the `Defs` file. What's the motivation to not let it have it's own file? I saw the upstreaming comment, but I'm not sure how that helps.

**Comment by YaelDillies** [comment]
I mean, there is no `def` in `Data.Nat.Defs`. It's all lemmas about definitions from Std, which is what `Data.Nat.Sqrt` is as well.

**Comment by j-loreaux** [comment]
okay.

bors merge

**Pull request closed without merging**
