### PR TITLE
feat: allow docstrings on `#align` to describe dubiousness

### PR DESCRIPTION
**Pull request by eric-wieser**
These docstrings are shown by `#lookup3`

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by digama0** [comment]
I don't think this does what you want. The dubious field is used by mathport to determine whether a declaration can be aligned, and when you add the `\_x` it makes it align correctly, even if it couldn't with the original name. So making the rename dubious as well will just cause it to suggest adding even more `\_x` 's.

**Comment by eric-wieser** [comment]
I don't think I've seen mathport add an ₓ for a very long time. It looks to me like at some point during the port it just stopped suggesting them.

**Comment by digama0** [comment]
It was part of the dubious translation message we disabled

**Comment by digama0** [comment]
This is all to say: You can add a doc string if you want, but the `dubious` field has semantic meaning and you aren't using it correctly. Just add another field and have `#lookup3` show that.

**Comment by eric-wieser** [comment]
Is the dubious field ever populated by anything within mathlib3? Or is the extra metadata only attached within mathport itself?

**Comment by digama0** [comment]
It is used by mathport itself, but the environment extension has to be declared in mathlib so that mathport can use it.

**Pull request closed without merging**
