### PR TITLE
[Merged by Bors] - feat: port Topology.Algebra.MulAction

### PR DESCRIPTION
**Pull request by urkud**
---

- [x] depends on: #2185 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mcdoll** [comment]
I will try to look at it, but it might take some time to build

**Comment by mcdoll** [comment]
Last remaining error is that `continuousSMul_infₛ` fails to find the `TopologicalSpace X` instance, even though it is specified in the theorem.

**Comment by mcdoll** [comment]
I would rather wait to have `continuity` merged, then commenting out the attribute, but I leave that up to you.

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2185
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2185~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
