### PR TITLE
[Merged by Bors] - chore: add "porting notes" benchmarking metric

### PR DESCRIPTION
**Pull request by Kha**
---

- [ ] depends on: #5993 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Kha** [comment]
!bench

**Comment by Kha** [comment]
!bench

**Comment by Kha** [comment]
I keep forgetting about this PR - I have no idea why that additional benchmark would make it time out, it should be instantaneous /cc @semorrison

**Comment by mattrobball** [comment]
bors delegate+

**Comment by Kha** [comment]
Of course I had used the wrong quotes...

**Pull request closed without merging**
