### PR TITLE
[Merged by Bors] - chore: add `fun_prop` attribute to various continuity lemmas

### PR DESCRIPTION
**Pull request by j-loreaux**
---

Tomas, I've requested your review because I want to make sure all these lemmas have the right form for `fun_prop`.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by lecopivo** [comment]
All looks good!

At first I was worried that `Continuous.const_smul` is a variant of `continuous_mul_left`. The left/right variants of `Continuous.mul` are not necessary. But then I notices that `Continuous.const_smul` has actually different assumptions then `Continuous.smul`.

I'm happy to review any future PRs adding more `fun_prop` theorems!

**Review by lecopivo — APPROVED** [review]
All looks good!

**Comment by sgouezel** [comment]
Shouldn't we instead move the attribute directly to the lemmas in the library, to make sure that `fun_prop` is usable right away to prove continuity? Otherwise, `fun_prop` will only be usable in files that are downstream of all the files mentioned here.

**Comment by j-loreaux** [comment]
@lecopivo Is there a reason things like `continuous_star` are not tagged? These kinds of lemmas state `Continuous star` as opposed to `Continuous.star` which states `Continuous (fun x ↦ star (f x))`. I note that `fun_prop` can still prove it (by taking `f := id`) as is. Mainly I'm wondering if this is a performance issue. If we ever want to print the terms (especially in the case of a `fun_prop?` tactic), then it would be nice if we didn't have this extra `id` step cluttering the term.

**Comment by lecopivo** [comment]
I call these two ways for formulating the theorem to be in "uncurried form" or in "compositional form". `fun_prop` can work with both of them and I guess we should mark both. At some point, I would like to do a performance test to see if using theorems in uncurried or compositional is faster.

I talk about this a bit in:
https://github.com/leanprover-community/mathlib4/blob/master/test/fun_prop.lean

I agree that for `fun_prop?` it would be better to use the uncurried form if possible.

**Comment by lecopivo** [comment]
I think I added only theorems in compositional form as they are more general. For example 
```
theorem continuous_array_map 
    (f : W → X → Y) (xs : W → Array X) 
    (hf : Continuous (fun (w,x) => f w x)) (hxs : Continuous xs) :
    Continuous (fun w => Array.map (f w) (xs w)) := sorry
```
can't be stated in uncurried form.

**Comment by urkud** [comment]
> @sgouezel I think the current plan is to collect lemmas here for the moment, so that people can see which lemmas are appropriate to tag. Once we have a good feel for this, then we can redistribute the lemmas across the library. That's what was done with `gcongr` (in fact, the moving PR is still open #9393).

As the author of #9393, I don't think that this will work well for any educational purposes. My guess is that most people want to **just use** the tactic and not care about tagging theorems. For these people (incl. myself), the fact that the basic setup file has heavier-than-necessary dependencies is bad. So, I would tag lemmas right where they are.

**Comment by lecopivo** [comment]
> 
> As the author of #9393, I don't think that this will work well for any educational purposes. My guess is that most people want to **just use** the tactic and not care about tagging theorems. For these people (incl. myself), the fact that the basic setup file has heavier-than-necessary dependencies is bad. So, I would tag lemmas right where they are.

One of the reasons for putting it in a separate file was for my comfort not having to recompile whole mathlib if I change internals of `fun_prop`. But I should not trade my convenience for the convenience of everybody else. I will redistribute the attributes next week.

**Comment by urkud** [comment]
I understand why it's convenient while you're working on a tactic. Once we start using the tactic all over the library, it's better to have it available very early.

**Comment by j-loreaux** [comment]
@urkud how about merging this as is, with a promise that we'll distribute the lemmas in a PR this week?

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
