### PR TITLE
[Merged by Bors] - chore: remove brackets around `Type*`

### PR DESCRIPTION
**Pull request by JovanGerb**
[Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/.60outParam.60.20in.20instance.20argument/near/442059394)

I replaced all occurrences of `(Type*)` or `<| Type*` with just `Type*`

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Does what it says.
I *think* this is a desirable change... but I'd definitely welcome another pair of eyes!

maintainer merge

**Comment by grunweg** [comment]
You *did* mean to mark this `awaiting-review`, didn't you?

**Comment by JovanGerb** [comment]
awaiting-review

**Comment by fpvandoorn** [comment]
bors merge

**Pull request closed without merging**
