### PR TITLE
feat: Add IsEmpty deriving handler

### PR DESCRIPTION
**Pull request by TimothyGu**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
I'm wondering if this actually has any use cases. Is anyone actually defining empty inductive types?

**Comment by alexjbest** [comment]
I have the same thought, though the implementation looks very feature complete.
I think the use case for merging this would be clearer if the internals were widely useful for other derive handlers.
For instance can you also create derive handlers for any of `Subsingleton`, `Nonempty`, `Nontrivial`, `Countable`, `Enumerable`, `Denumerable` or other cardinality-esque typeclasses using any of the same design principles you've used here?

**Comment by alexjbest** [comment]
I now see you have #3610, which sort of answers my comment, but I'd love to see some more common structure factored out (if you think thats possible!)

**Comment by TimothyGu** [comment]
@semorrison Yeah there's no "real" use case for this, but since we already have a deriving handler for Fintype and I made one for Infinite (#3610), this more or less completes the picture.

**Comment by TimothyGu** [comment]
@alexjbest I've thought about generalizing this quite a bit, but at the currently available levels of abstraction, it's hard to factor out any sort of common structure. Looking at `Infinite`, `Fintype`, `IsEmpty`, and `Inhabited`, though they are all related to the cardinality of the set, the specific requirements are quite different. For instance, `Inhabited`'s handler checks/assumes all the constructor argument types are `Inhabited`; `IsEmpty` checks that _one_ of the constructor arguments is `IsEmpty`; `Infinite` checks _one_ of the constructor arguments is `Infinite` and everything else is `Nonempty`. (I haven't thought much about `Countable` or `Subsingleton`.)

In my conversations with @prakol16, he mentions it might be possible to extend the current `proxy_type%` mechanism to also work for recursive constructors using W-types. That could potentially be an avenue towards unifying all of these type instances. But until that happens, the code for Infinite and IsEmpty is already here, so why not include them.

**Comment by semorrison** [comment]
I'm very happy with the code for `Infinite`, I'm just concerned that the `IsEmpty` one might be a code path that is never run...!

**Comment by semorrison** [comment]
I'm going to close this for now. Please feel free to bring it up on zulip again if I'm missing something.

**Pull request closed without merging**
