### PR TITLE
[Merged by Bors] - feat: port Topology.MetricSpace.EMetricSpace

### PR DESCRIPTION
**Pull request by urkud**
---

- [x] depends on: #2406
- [x] depends on: #2388
- [x] depends on: #2511
- [x] depends on: leanprover-community/mathlib#18516

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2406
* leanprover-community/mathlib4#2388
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2406~~
* ~~leanprover-community/mathlib4#2388~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2406~~
* ~~leanprover-community/mathlib4#2388~~
* ~~leanprover-community/mathlib4#2511~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2406~~
* ~~leanprover-community/mathlib4#2388~~
* ~~leanprover-community/mathlib4#2511~~
* ~~leanprover-community/mathlib#18516~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada: 

If CI passes, please remove the label `awaiting-CI` and merge this yourself, by adding a comment `bors r+`.

bors d+

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
