### PR TITLE
[Merged by Bors] - feat: remove unnecessary `Classical.choice` in `split_ifs`

### PR DESCRIPTION
**Pull request by astrainfinita**
In rare cases, `Decidable p` is not an instance and `split_ifs` is still classical. I am not familiar with tactic and not sure if there is an easy method to deal with these cases.

---

- [x] depends on: #5565

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5565
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5565~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
Could you write a test case that demonstrates the change in behaviour here?

**Review by kmill — APPROVED** [review]
This seems like a correct implementation to me. I tend to find `evalTactic` a little unsettling, but (1) `andThenOnSubgoals` focuses on the main goal, which keeps any potential future changes to `by_cases` under control, and (2) there are no expressions in the syntax that will really be elaborated, so there's no risk of unexpected extra goals that `reduceIfsAt` will apply to.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
