### PR TITLE
[Merged by Bors] - fix: `attribute [simp] ... in` -> `attribute [local simp] ... in`

### PR DESCRIPTION
**Pull request by collares**
Mathlib.Logic.Unique contains the line `attribute [simp] eq_iff_true_of_subsingleton in ...`:

https://github.com/leanprover-community/mathlib4/blob/96a11c7aac574c00370c2b3dab483cb676405c5d/Mathlib/Logic/Unique.lean#L255-L256

 Despite what the `in` part may imply, this adds the lemma to the simp set "globally", including for downstream files; it is likely that `attribute [local simp] eq_iff_true_of_subsingleton in ...` was meant instead (or maybe `scoped simp`, but I think "scoped" refers to the current namespace). Indeed, the relevant lemma is not marked with `@[simp]` for possible slowness: https://github.com/leanprover/std4/blob/846e9e1d6bb534774d1acd2dc430e70987da3c18/Std/Logic.lean#L749. Adding it to the simp set causes the example at https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Regression.20in.20simp to slow down.

This PR changes this and fixes the relevant downstream `simp`s. There was also one ocurrence of `attribute [simp] FullSubcategory.comp_def FullSubcategory.id_def in` in Mathlib.CategoryTheory.Monoidal.Subcategory but that was much easier to fix.

https://github.com/leanprover-community/mathlib4/blob/bc49eb9ba756a233370b4b68bcdedd60402f71ed/Mathlib/CategoryTheory/Monoidal/Subcategory.lean#L118-L119

---
There are other instances of `attribute ... in` in the codebase:

```
Topology/Category/TopCat/Basic.lean:attribute [instance] ConcreteCategory.funLike in
LinearAlgebra/BilinearForm/TensorProduct.lean:attribute [ext] TensorProduct.ext in
SetTheory/Game/Short.lean:attribute [-instance] subsingleton_short in
RingTheory/Trace.lean:attribute [-instance] Field.toEuclideanDomain
RingTheory/Polynomial/Basic.lean:attribute [-instance] Ring.toNonAssocRing in
RingTheory/Polynomial/Basic.lean:attribute [-instance] Ring.toSemiring in
RingTheory/Polynomial/Basic.lean:attribute [-instance] Polynomial.semiring Polynomial.commSemiring in
```

I don't know if those are OK. Also, does the `in` in `attribute [local/scoped simp] ... in` do anything, or do they operate on the current file/current namespace (respectively) regardless?

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by sgouezel** [comment]
!bench

**Comment by sgouezel** [comment]
I'd like to see if it makes a performance difference to disable the simp lemma or not. Since you had to add it back in many places, it looks pretty useful as a simp lemma, so it would be good if we could keep it in the simpset.

**Comment by b-mehta** [comment]
It seems that this being a simp lemma is one of the reasons that [this regression in simp](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Regression.20in.20simp) occurs. More generally, having this in the global simp set can slow down `simp` calls which are then squeezed away, so I'm not sure that the mathlib benchmark alone is a fair judge.

**Review by sgouezel — COMMENTED** [review]
I'm still not completely convinced: the fact that several files are red in the bench show that the lemma is useful even in places where you haven't put it back, as it provides efficient shortcuts. (I'm not really against the change either, just hesitant).

**Comment by b-mehta** [comment]
> I'm still not completely convinced: the fact that several files are red in the bench show that the lemma is useful even in places where you haven't put it back, as it provides efficient shortcuts. (I'm not really against the change either, just hesitant).

That's fair - I'm viewing this as reverting an accidental change, rather than making a deliberate change. Specifically it seems to me like this lemma was never meant to be in the global simp-set

**Comment by collares** [comment]
For reference, the Zulip example is:

```lean
import Mathlib

set_option trace.profiler true

example : (fun i : Nat => 3) ≠ fun i : Nat => 4 := by simp (config := {decide := false}) [Function.funext_iff]
```

Before this PR:

```
[Elab.command] [0.285493s] example : (fun i : Nat => 3) ≠ fun i : Nat => 4 := by
      simp? (config := { decide := false }) [Function.funext_iff]
  [Elab.step] [0.280980s] simp? (config := { decide := false }) [Function.funext_iff]
    [Elab.step] [0.280965s] simp? (config := { decide := false }) [Function.funext_iff]
      [Elab.step] [0.280948s] simp? (config := { decide := false }) [Function.funext_iff]
        [Meta.synthInstance] [0.169180s] ❌ Subsingleton (ℕ → ℕ)
        [Meta.synthInstance] [0.067522s] ✅ CharZero ℕ
```

After:
```
[Elab.command] [0.116914s] example : (fun i : Nat => 3) ≠ fun i : Nat => 4 := by
      simp? (config := { decide := false }) [Function.funext_iff]
  [Elab.step] [0.113247s] simp? (config := { decide := false }) [Function.funext_iff]
    [Elab.step] [0.113230s] simp? (config := { decide := false }) [Function.funext_iff]
      [Elab.step] [0.113212s] simp? (config := { decide := false }) [Function.funext_iff]
        [Meta.synthInstance] [0.078150s] ✅ CharZero ℕ
```

**Comment by digama0** [comment]
Note: I have pushed an update to the lean toolchain because this PR was on a [buggy version](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Potential.20data.20loss.20from.20.60lake.20clean.60.20with.204.2E2.2E0-rc2.2F3/near/397875701) of the toolchain. **WARNING**: checking out old commits of this PR using v4.2.0-rc2 or v4.2.0-rc3 can cause `lake clean` to delete your mathlib folder! If you need to do so, make sure to delete `lakefile.olean` manually before running any `lake` commands.

**Comment by collares** [comment]
!bench

**Comment by collares** [comment]
!bench

**Comment by collares** [comment]
Note that `eq_iff_true_of_subsingleton` as a simp lemma causes `simpNF` failures which are currently marked as `nolint`. See, for example, https://github.com/leanprover-community/mathlib4/blob/bf4260cbab0a5be943fe4cfe97a9d54948ddc61a/Mathlib/SetTheory/Game/Short.lean#L43-L48.

As an experiment, I pushed a commit which adds `eq_iff_true_of_subsingleton`  as a normalization lemma for `aesop_cat`. A single file had longer build times before and after the last commit (`Mathlib.CategoryTheory.Abelian.InjectiveResolution`), but I think it shows that the performance regressions are specific to `aesop_cat`. I can't say if changing the tactic is a good idea, or if the way I did it is the best way of doing so, but at least it helps clarify the situation.

I will push a new commit adding `attribute [scoped simp] eq_iff_true_of_subsingleton` to Mathlib.CategoryTheory.Category.Basic instead of modifying `aesop_cat` to see how it performs.

**Comment by collares** [comment]
!bench

**Comment by collares** [comment]
To recap:

* The [first benchmark run I triggered](https://github.com/leanprover-community/mathlib4/pull/7678#issuecomment-1792718071), removing `eq_iff_true_of_subsingleton` from the simp set, reports a few regressions and a few speedups. This corresponds to the first two commits.
* The [second benchmark run](https://github.com/leanprover-community/mathlib4/pull/7678#issuecomment-1792959653) in addition adds `eq_iff_true_of_subsingleton` as an `aesop_cat` normalization simp lemma. Except for one file, the original regressions disappear. This is pretty strong evidence that previous slowdowns were all related to `aesop_cat`. Unfortunately, most of the wins also disappear. This corresponds to the first three commits.
* The [third benchmark run](https://github.com/leanprover-community/mathlib4/pull/7678#issuecomment-1793015322) reverts the `aesop_cat` change, adding `eq_iff_true_of_subsingleton` as a scoped simp lemma in the CategoryTheory namespace. This means `aesop_cat` will use it, but we don't pay a cost to add it to aesop's simp lemma list at each callsite. This corresponds to taking all four commits (the fourth one reverts the third one as well as adding a scoped simp lemma).

Therefore, there are three solutions with different tradeoffs. What all benchmarks had in common was a 5.3% decreasing in number of instructions during linting. This is probably related to the `nolint`ed `simpNF` failures I described earlier.

**Comment by collares** [comment]
@mattrobball I'll take the liberty to mention you here since this PR involves both performance and category theory, but feel free to ignore the ping if you want. Thanks!

**Comment by semorrison** [comment]
Discussion offline suggests we're going with the first option, and I'm happy with that!

bors d+

**Pull request closed without merging**
