### PR TITLE
[Merged by Bors] - chore: remove detrital heartbeat bumps

### PR DESCRIPTION
**Pull request by mattrobball**
With multiple changes, it is a good time to check if existing `set_option maxHeartbeats` and `set_option synthInstance.maxHeartbeats` remain necessary. This brings the number of files with such down from 23 to 9. Most are straight deletions though I did change one proof.

---

The remaining bumps are in 
```sh 
test/RewriteSearch/Polynomial.lean
test/LibrarySearch/basic.lean
test/Set.lean
Mathlib/Algebra/Jordan/Basic.lean
Mathlib/Algebra/Homology/DifferentialObject.lean
Mathlib/Geometry/Manifold/ContMDiff/NormedSpace.lean
Mathlib/Geometry/RingedSpace/PresheafedSpace/Gluing.lean
Mathlib/Algebra/Category/AlgebraCat/Monoidal.lean
Mathlib/CategoryTheory/Triangulated/Functor.lean
Mathlib/CategoryTheory/Monoidal/Internal/Module.lean
Mathlib/CategoryTheory/Limits/Shapes/Diagonal.lean
Mathlib/Topology/MetricSpace/GromovHausdorff.lean
Mathlib/Util/CountHeartbeats.lean
```

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by kmill** [comment]
Assuming it builds, and you don't make any more changes, go ahead and merge. Nice to see these aren't needed anymore.

bors d+

**Comment by mattrobball** [comment]
bors merge

**Comment by urkud** [comment]
Re-adding to the queue:
bors r-

**Pull request closed without merging**
