### PR TITLE
[Merged by Bors] - chore: bump to nightly-2023-08-03

### PR DESCRIPTION
**Pull request by kim-em**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
bors merge

It would be great if we could autogenerate a Lean4 change summary in the commit message in these PRs.

**Comment by eric-wieser** [comment]
bors d+

**Comment by eric-wieser** [comment]
bors merge

**Comment by tydeu** [comment]
@semorrison FYI, I believe I may have accidently broke remote dependencies in leanprover/lean4#2380 and have made leanprover/lean4#2383 as a fix. So it may be worth reverting this bump (or, at least, making the next bump as soon as the nightly releases).

**Pull request closed without merging**
