### PR TITLE
[Merged by Bors] - feat: `m/gcd m n` and `n` coprime if `m` squarefree

### PR DESCRIPTION
**Pull request by YaelDillies**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alexjbest** [comment]
Looks like a good candidate for dot notation, also should be true if either m is Nonzero or n is Nonzero I think. So the hypothesis could be an or statement

**Comment by YaelDillies** [comment]
This can't reasonably be dot notation because the predicate is `Squarefree`, not `Nat.Squarefree`. The `Squarefree m` hypothesis already implies `m ≠ 0` (and indeed the statement is false if we remove the `n ≠ 0` assumption).

**Comment by alexjbest** [comment]
Ah right, this is `Nat.gcd`, we really should combine those at some point (I'd imagine this lemma would be true more generally then).

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
