### PR TITLE
[Merged by Bors] - feat: Density of the image of a finset under a bijection

### PR DESCRIPTION
**Pull request by YaelDillies**
From LeanAPAP

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Please change the topic label if I guessed wrong! I'm trying to label every "feature" PR with an area label...

**Comment by YaelDillies** [comment]
Why do you keep lowercasing my PR titles btw?

**Comment by b-mehta** [comment]
> Why do you keep lowercasing my PR titles btw?

The PR title should not have its first letter capitalised: https://leanprover-community.github.io/contribute/commit.html
As far as I know, this has always been the convention!

**Comment by b-mehta** [comment]
bors merge

**Pull request closed without merging**
