### PR TITLE
[Merged by Bors] - feat: port Data.List.Indexes

### PR DESCRIPTION
**Pull request by int-y1**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by int-y1** [comment]
I'm giving up on this because it's too advanced for me. It seems like every statement needs a new proof.

**Comment by casavaca** [comment]
I managed to make it build, with at least some TODOs:

1. Naming: since Lean 4 changed implementation of `mapIdx`, the name of the theorem should probably changed.
2. I added lean 3 version for the proof, so probably use `protected` and `noalign`?
3. at line 176 `simp?` outputs `Try this: simp only [...,   _private.Std.Data.List.Init.Lemmas.0.List.zipWith._eq_1, ...]`. What is that? (I used `simp`)
4. If someone can simplify the proof it would be great.

**Comment by nomeata** [comment]
@int-y1, do you want to take over again and apply the final touches?

**Comment by int-y1** [comment]
This looks ready for review. A few notes:

* Lean 4 changed the definition of `mapIdx` and some other functions. As a result, there are more changes than usual.
* A large part of the file is dedicated to proving `new_def_eq_old_def`, which says "Lean 4's `mapIdx` = Lean 3's `map_with_index`". (This theorem made it easy to prove `mapIdx_eq_enum_map`)

**Comment by jcommelin** [comment]
Zulip thread about the old/new def: https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Data.2EList.2EIndexes.20!4.231812

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
