### PR TITLE
[Merged by Bors] -  chore: remove CoeFun instances where FunLike is available

### PR DESCRIPTION
**Pull request by Vierkantor**
During the port we found that `FunLike` is robust enough not to need an extra `CoeFun` shortcut. Let's see if that rule can be consistently applied to the whole of the library.

There is still duplication between `FunLike` and `CoeFun` for `Grp`, `Mon`, `CommGrp` and `CommMon`, which will need a more thorough fix. See also #17866.

I am currently bisecting to figure out exactly why the benchmarks are indicating a slowdown with no obvious cause.

---

- [ ] depends on: #17900 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Vierkantor** [comment]
!bench

**Comment by eric-wieser** [comment]
> During the port we found that `FunLike` is robust enough not to need an extra `CoeFun` shortcut.

Indeed, but we also found that the shortcut could often improve performance, as you are now running into!

**Comment by jcommelin** [comment]
@eric-wieser Could you please explain what you mean? Because the bench bot says there is no significant performance regression.

**Comment by kim-em** [comment]
I think "often" is compatible with what Anne is finding: removing the shortcut entirely causes a slowdown.

Let's just merge the parts that don't cause a slow down, and soon Anne will hopefully have localised the places where removing it really is damaging, and then we can study that.

**Comment by kim-em** [comment]
bors merge

**Pull request closed without merging**
