### PR TITLE
feat(CategoryTheory/Action): category of continuous actions

### PR DESCRIPTION
**Pull request by chrisflav**
Introduces the category `ContAction V G` for any concrete category `V` and monoid `G`. It is realized as a subcategory of `Action V G` with a `TopologicalSpace` instance on the underlying type such that the induced action is continuous.

Also introduces the full subcategory `DiscreteContAction V G` where the underlying topological space is discrete.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by joelriou** [comment]
The code looks nice to me, but I am not completely sure this is the best setup. For example, if `V` is `AddCommGroupCat`, there would be no continuity condition on the `+` and `-` laws: then, we would have to introduce suitable full subcategories in order to work with this notion.

I would be interested to know the opinion @101damnations, especially about whether this would be useful in the development of continuous cohomology.

**Comment by chrisflav** [comment]
> The code looks nice to me, but I am not completely sure this is the best setup. For example, if `V` is `AddCommGroupCat`, there would be no continuity condition on the `+` and `-` laws: then, we would have to introduce suitable full subcategories in order to work with this notion.
> 
Maybe we can introduce a typeclass `TopologicalConcreteCategory C` (or `ConcreteCategory.HasTopology C`) simply stating that there exists a topological space instance on each object `X` of `C`.

Then `ContAction V G` could just ask `V` to be a topological concrete category. The one for types would then be `ContAction TopCat G` and the one for topological groups could be `ContAction TopGroupCat G` where `TopGroupCat` is the category of topological groups with continuous homomorphisms.

**Comment by 101damnations** [comment]
> > The code looks nice to me, but I am not completely sure this is the best setup. For example, if `V` is `AddCommGroupCat`, there would be no continuity condition on the `+` and `-` laws: then, we would have to introduce suitable full subcategories in order to work with this notion.
> 
> Maybe we can introduce a typeclass `TopologicalConcreteCategory C` (or `ConcreteCategory.HasTopology C`) simply stating that there exists a topological space instance on each object `X` of `C`. Or maybe that the forgetful functor factorizes via `forget TopCat` ?
> 
> Then `ContAction V G` could just ask `V` to be a topological concrete category. The one for types would then be `ContAction TopCat G` and the one for topological groups could be `ContAction TopGroupCat G` where `TopGroupCat` is the category of topological groups with continuous homomorphisms.

This sounds like a good set up to me!

**Comment by chrisflav** [comment]
I opened #13006 with the alternative approach outlined above. I realized that `TopologicalConcreteCategory` basically already exists in the form of `HasForget₂ V TopCat`, so that's what I used.

**Comment by chrisflav** [comment]
Closed in favor of #13006.

**Pull request closed without merging**
