### PR TITLE
[Merged by Bors] - chore: replace `refine'` with one underscore by `refine`

### PR DESCRIPTION
**Pull request by adomani**
[Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Subgroups.20are.20empty/near/439585459)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
!bench

**Review by mattrobball — APPROVED** [review]
I scrolled through it all. Great!

**Comment by mattrobball** [comment]
bors merge p=9000

**Comment by MichaelStollBayreuth** [comment]
I've written a bash script and a Magma program to extract all files whose instruction count differs by at least 10⁹, and it reports this:
```text
==============================================================================
General information:
  build                                             : +1.1833 * 10⁹ 
(+0.00101%)

Files that got slower:
  Mathlib.Analysis.NormedSpace.PiTensorProduct.InjectiveSeminorm:
                                                      +1.4072 * 10⁹ (+0.504%)

Files that got faster:
==============================================================================
```

**Pull request closed without merging**
