### PR TITLE
[Merged by Bors] - feat: separated and locally injective maps

### PR DESCRIPTION
**Pull request by alreadydone**
A function from a topological space `X` to a type `Y` is a separated map if any two distinct points in `X` with the same image in `Y` can be separated by open neighborhoods. A constant function is a separated map if and only if `X` is a `T2Space`.

A function from a topological space `X` is locally injective if every point of `X` has a neighborhood on which `f` is injective. A constant function is locally injective if and only if `X` is discrete.

Given `f : X → Y` one can form the pullback $X \times_Y X$; the diagonal map $\Delta: X \to X \times_Y X$ is always an embedding. It is a closed embedding iff `f` is a separated map, iff the equal locus of any two continuous maps equalized by `f` is closed. It is an open embedding iff `f` is locally injective, iff any such equal locus is open. Therefore, if `f` is a locally injective separated map (e.g. a covering map), the equal locus of two continuous maps equalized by `f` is clopen, so if the two maps agree on a point, then they agree on the whole connected component. This is crucial to showing the uniqueness of path lifting and the uniqueness and continuity of homotopy lifting for covering spaces.

The analogue of separated maps and locally injective maps in algebraic geometry are separated morphisms and unramified morphisms, respectively.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by AntoineChambert-Loir** [comment]
The proof that coverings are separated is a bit complicated because two facts are missing:
- being separated is local on the base
- a trivial covering is separated
- itself because fiber products of separated maps are separated.
Playing with “local on the base ” might be inconvenient, though, because it may require some coercion, but that may be worth being tried.
(This is how this stuff is treated in Bourbaki.)

**Comment by alreadydone** [comment]
Is 10 lines long? :) And I'm not sure how to interpret "being separated is local on the base" since I don't assume the base space has a topology in `IsSaparatedMap`.

**Comment by alreadydone** [comment]
Currently the proof is very straightforward from the definition, which is the existence of local trivializations `U ≃ₜ V × F` around any point `e : E`. If another point `e'` projects to the same point in `V`, then `e` and `e'` must correspond to different points in the fiber `F`, and the preimage of these two points of `F` in `U` gives disjoint open neighborhoods of `e` and `e'`.

Maybe with another definition of covering maps Bourbaki's proof would be easier, but it certainly doesn't look like the case here ...

**Comment by jcommelin** [comment]
I'm going to merge this as is. When there is more API of the kind that ACL is talking about, then we can consider golfing the proof.

bors merge

**Pull request closed without merging**
