### PR TITLE
[Merged by Bors] - feat: port Order.Basic

### PR DESCRIPTION
**Pull request by pechersky**
`min` and `max` defaults are now the same between lean3 and lean4, so porting proofs in the future should be easier.

### CODE REVIEW

**Comment by semorrison** [comment]
Can you explain the TODO in the PR description? What are the choices?

**Comment by pechersky** [comment]
Updated the description

**Comment by semorrison** [comment]
Okay, I propose we backport the Lean 4 behaviour to Lean 3. Here's the PR:

* lean: https://github.com/leanprover-community/lean/pull/779
* mathlib: https://github.com/leanprover-community/mathlib/pull/17470

**Comment by semorrison** [comment]
Optionally wait until people have opinions on those PRs, but you can copy my changes in the mathlib PR here if you like.

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
