### PR TITLE
[Merged by Bors] - chore: move TopologicalSpace.SecondCountableTopology into the root namespace

### PR DESCRIPTION
**Pull request by sgouezel**
All the other properties of topological spaces like T0Space or RegularSpace are in the root namespace. Many files were opening `TopologicalSpace` just for the sake of shortening `TopologicalSpace.SecondCountableTopology`...

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by j-loreaux** [comment]
I think this is a nice change, but I'd like a second opinion, so:

maintainer merge

**Comment by YaelDillies** [comment]
Can it be renamed to `Topology.SecondCountable` instead?

**Comment by sgouezel** [comment]
I don't really care about the precise name, I just want to shorten it. The simplest move is probably just to rename it to `SecondCountableTopology` as in the current PR, and then in another PR move a bunch of things to the `Topology` namespace if someone is motivated to do it. Having just `Topology.SecondCountable` and the other properties of topological spaces in the root namespace would feel weird to me.

**Comment by RemyDegenne** [comment]
LGTM!
I agree that moving things to the Topology namespace should be done in another PR, if we do it. Let's merge this one first: it's a clean improvement over the current situation.
bors r+

**Pull request closed without merging**
