### PR TITLE
[Merged by Bors] - feat: set up fun_prop for Differentiable and HasFDeriv

### PR DESCRIPTION
**Pull request by lecopivo**
Basic setup for `fun_prop` for Differentiable(At/On/Within) and HasFDeriv(At/Within/Strict).

Mainly consists of marking theorems with `fun_prop` attribute but I had to formulate appropriate `_pi` and `_apply` theorems. Proofs of `_apply` theorems can probably be golfed into neater form.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by fpvandoorn** [comment]
Can you add some tests for `HasFDeriv`? E.g. can you automatically prove `HasDeriv (fun x => x^2) 0 0`? (note: I don't want the derivative to be `2*0` or `2*0^1`)

**Comment by lecopivo** [comment]
The fact that `fun_prop` can solve `HasFDerivAt` is just a happy coincidence. The tactic is not really designed to compute derivatives.

For example
```
#check (by fun_prop : HasFDerivAt (𝕜:=ℝ) (fun x : ℝ => x*x) _ (0 : ℝ))
```
prints out 
```
HasFDerivAt.mul (hasFDerivAt_id' 0)
  (hasFDerivAt_id' 0) : HasFDerivAt (fun y => y * y) (0 • ContinuousLinearMap.id ℝ ℝ + 0 • ContinuousLinearMap.id ℝ ℝ) 0
```
You can see that no simplification took place.

I'm working on `fun_trans` tactic which is designed to compute nice derivatives. It is just a custom simproc so all those zero eliminations are handled by the simplifier.

I don't think that modifying `fun_prop` to compute nice derivatives is a good idea. The tactic is complicated enough already. Therefore, either we leave it like this or remove `@[fun_prop]` from all the `HasFDerivAt` theorems.

**Comment by lecopivo** [comment]
And yes `HasDeriv` is not part of this PR. Only files in `Mathlib.Analysis.Calculus.FDeriv.*` were touched. I will make a PR with `Mathlib.Analysis.Calculus.Deriv.*` files some other day.

**Comment by fpvandoorn** [comment]
Thanks!

bors merge

**Comment by fpvandoorn** [comment]
PS: You are probably aware that there are more files that should be tagged, e.g. `Mathlib.Analysis.SpecialFunctions.Pow.Deriv`, and probably a whole lot more in `Mathlib.Analysis.SpecialFunctions`.

**Pull request closed without merging**
