### PR TITLE
[Merged by Bors] - feat: port Geometry.Euclidean.Angle.Oriented.Basic

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

- [x] depends on: #4602

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4602
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
bors d+

But please wait until #4602 has been reviewed and merged; this delegation is just about the `Oriented.Basic` file.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4602~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by Parcly-Taxel** [comment]
bors merge

**Pull request closed without merging**
