### PR TITLE
[Merged by Bors] - chore: fix "unnecessary have" lint errors

### PR DESCRIPTION
**Pull request by llllvvuu**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — APPROVED** [review]
These fixes certainly seem fine to me.
Can you update the PR description, please?

**Comment by llllvvuu** [comment]
Updated.

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Comment by fpvandoorn** [comment]
bors merge

**Pull request closed without merging**
