### PR TITLE
[Merged by Bors] - feat(NumberTheory/Harmonic): Euler-Mascheroni const = `-Γ'(1)`

### PR DESCRIPTION
**Pull request by loefflerd**
---

- [x] depends on: #11589
- [x] depends on: #11602

### CODE REVIEW

**Review by MichaelStollBayreuth — APPROVED** [review]
LGTM!

**Comment by MichaelStollBayreuth** [comment]
maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by urkud** [comment]
Re-adding to the queue:
bors r-

**Comment by riccardobrasca** [comment]
bors r-

same as in the other PR

**Comment by riccardobrasca** [comment]
bors d+

**Comment by urkud** [comment]
CI fails because of renamed `Nat.cast` lemmas.
bors r-

**Pull request closed without merging**
