### PR TITLE
[Merged by Bors] - feat: port NumberTheory.NumberField.CanonicalEmbedding

### PR DESCRIPTION
**Pull request by int-y1**
---

todo:

* [x] `def equivIntegerLattice` has lots of errors

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
not quite sure, why obtain didn't work here

**Comment by int-y1** [comment]
> not quite sure, why `obtain` didn't work here

I renamed an instance to `InfinitePlace.instNonempty`, but I forgot to commit it.
This instance renaming is no longer necessary.

**Comment by xroblot** [comment]
If nobody is working on this file at the moment, I'll work on it a bit

**Comment by xroblot** [comment]
This PR should be ok now

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
