### PR TITLE
[Merged by Bors] - fix(Algebra/DirectSum/Internal): delete some instances

### PR DESCRIPTION
**Pull request by kbuzzard**
See [Zulip](https://leanprover.zulipchat.com/#narrow/channel/287929-mathlib4/topic/rewrite.20failure.20on.20Subalgebra/near/478555535) discussion. One of these instances was breaking user code.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by riccardobrasca** [comment]
!bench

**Comment by kbuzzard** [comment]
heh, you both took the words out of my mouth :-)

**Comment by riccardobrasca** [comment]
Ops, I didn't see Matthew also benched it

**Comment by mattrobball** [comment]
Seems fine to me

**Comment by riccardobrasca** [comment]
I agree

**Comment by fpvandoorn** [comment]
Yes, looks good.

bors merge

**Pull request closed without merging**
