### PR TITLE
[Merged by Bors] - feat: CompletelyDistribLattice

### PR DESCRIPTION
**Pull request by gebner**
Adds new `CompletelyDistribLattice`/`CompleteAtomicBooleanAlgebra` classes for complete lattices / complete atomic Boolean algebras that are also completely distributive, and removes the misleading claim that `CompleteDistribLattice`/`CompleteBooleanAlgebra` are completely distributive.

 - Product/pi/order dual instances for completely distributive lattices, etc.
 - Every complete linear order is a completely distributive lattice.
 - Every atomic complete Boolean algebra is a complete atomic Boolean algebra.
 - Every complete atomic Boolean algebra is indeed (co)atom(ist)ic.
 - Atom(ist)ic orders are closed under pis.
 - All existing types with `CompleteDistribLattice` instances are upgraded to `CompletelyDistribLattice`.
 - All existing types with `CompleteBooleanAlgebra` instances are upgraded to `CompleteAtomicBooleanAlgebra`.

See [related discussion on Zulip](https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/Are.20CompleteDistribLattices.20completely.20distributive.3F/near/366667419).

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by gebner** [comment]
The only remaining `CompleteDistribLattice` instances are for simple graphs.  Those are completely distributive as well and could be upgraded, but I don't know the API well enough to make nice proofs.

**Comment by semorrison** [comment]
Could we have a `TODO` comment on the remainined `CompleteDistribLattice` instances?

**Comment by gebner** [comment]
I've now added a `CompleteAtomicBooleanAlgebra` class like Reid suggested.  This makes it a lot easier to define instances (since you only need one distributivity field instead of two, and get atomicity for free).  In particular, this made upgrading the SimpleGraph instances trivial.

**Comment by gebner** [comment]
> Could we have a `TODO` comment on the remainined `CompleteDistribLattice` instances?

To be clear, all remaining instances have been ported now.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
