### PR TITLE
chore: remove some `backward.isDefEq.lazyWhnfCore`

### PR DESCRIPTION
**Pull request by jcommelin**
there are a few remaining cases that still lead to timeouts

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
!bench

**Comment by grunweg** [comment]
All three files with changes slow down, two of them significantly (~10% in instructions).

**Comment by semorrison** [comment]
However the overall instruction count increase it pretty tiny. I'm happy with this as is.

**Comment by semorrison** [comment]
I'll delegate in case you want to think any further about it.

bors d+

**Comment by jcommelin** [comment]
I think it might be better to keep the flags around, and try to get better proofs before removing them.

**Pull request closed without merging**
