### PR TITLE
[Merged by Bors] - docs(Algebra/Order/Ring/Defs): tiny `IsDomain` corrections

### PR DESCRIPTION
**Pull request by madvorak**
---

Please check whether the new version is a correct description.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alexjbest** [comment]
Actually it might be better to emphasize that IsDomain is a mixin now and not part of the heierachy. So it's not actually a predecessor in a literal sense

**Comment by madvorak** [comment]
Would you remove `IsDomain` from the comments, or change the wording?

**Comment by alexjbest** [comment]
I would change the wording to `Ring` + `IsDomain` with linear order (or whatever the correct version is)

**Comment by madvorak** [comment]
I couldn't make sense out of it (i.e., I didn't find a combination `IsDomain` + something where "something" wouldn't be redundant for given purposes). If you find something, please, fill it in; otherwise, I better delete these two lines.

I am not saying it is ideal thing to do to the docs, but it is certainly better now than what there was before.

**Comment by madvorak** [comment]
> I couldn't make sense out of it (i.e., I didn't find a combination `IsDomain` + something where `IsDomain` wouldn't be redundant for given purposes). If you find something, please, fill it in; otherwise, I better delete these two lines.
> 
> I am not saying it [deleting these lines] is ideal thing to do to the docs, but it is certainly better now than what there was before.

**Review by YaelDillies — APPROVED** [review]
It does make sense. I pushed a fix with the new appropriate description.

maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors d+

**Comment by madvorak** [comment]
Thank you @YaelDillies !

Shouldn't " & `+` respects `≤` & `*` respects `<` " be there as well?
I am not sure what exactly implies the rest of the properties.

**Comment by madvorak** [comment]
> The point was to relate to non-order properties, so no it wouldn't make much sense.

Should it be removed from lines 68, 74, 81, 88 then?

**Comment by YaelDillies** [comment]
No, I mean the point of *those two specific lines*. Each item in a sublist removes one condition from the corresponding header. The ones about `IsDomain` are precisely removing the compatibility between algebraic and order operations.

**Comment by madvorak** [comment]
Sorry; it seems I don't understand what `IsDomain` does. If you are sure it is now correct, I will trust you and merge it as is.

**Comment by YaelDillies** [comment]
`IsDomain` just says that `a * b = 0 → a = 0 ∨ b = 0`. This is a consequence of linearity of the order + compatibility of the algebraic operations, but it is a purely algebraic condition.

**Comment by madvorak** [comment]
And what implies that `+` respects `≤` then?

**Comment by YaelDillies** [comment]
I think you are misunderstanding the point of this whole paragraph in the docs. It's supposed to answer questions of the form "I stated a lemma using `LinearOrderedRing` but never used the compatibility of `*` with `≤` for anything else than `a * b = 0 → a = 0 ∨ b = 0`. What should I do?", the answer to which would be "Use `Ring` + `IsDomain` + maybe `LinearOrder`".

**Comment by madvorak** [comment]
Yeah, I misunderstood it totally!

Should I merge it now as it is?

**Comment by YaelDillies** [comment]
The docstring did slightly go out of date (since `Domain` is no more) and I'm happy with this PR in its current form, so please do!

**Pull request closed without merging**
