### PR TITLE
[Merged by Bors] - doc(Combinatorics/Young/YoungDiagram): Change `Ssyt` to `SemistandardYoungTableau`

### PR DESCRIPTION
**Pull request by trivial1711**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Command-Master — APPROVED** [review]
Thanks!

**Review by grunweg — COMMENTED** [review]
(For the other reviewers: this is fixing an outdated doc-string; the new name is correct.)
Thanks! maintainer merge

**Comment by chrisflav** [comment]
Michael, your `maintainer merge` did not trigger apparently (maybe because it is not on a separate line?)

maintainer merge

**Review by dupuisf — COMMENTED** [review]
Thanks!

bors r+

**Pull request closed without merging**
