### PR TITLE
[Merged by Bors] - fix: allow porting Archive files

### PR DESCRIPTION
**Pull request by eric-wieser**
---

- [x] depends on: #5078

[Open in Gitpod](https://gitpod.io/from-referrer/)

Do we want `Archive.lean` and `Counterexamples.lean` to exist? How can we configure CI?

#4812 is a demo of a PR created with the updated version. I tested on a regular mathlib file and everything still seems to work.

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5078
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by eric-wieser** [comment]
Yes, that's the missing piece here. Counterexamples too. And use the appropriate filename in the commit message!

**Comment by eric-wieser** [comment]
@urkud, can you confirm the script now works for you? If so, please merge it!

**Comment by semorrison** [comment]
Yes, working for me. I didn't push as I accidentally did one that Yury has already pushed.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
