### PR TITLE
[Merged by Bors] - chore(Order): replace `Top` and `Bot` ancestors with `OrderTop` and `OrderBot`

### PR DESCRIPTION
**Pull request by eric-wieser**
Co-authored-by: negiizhao <egresf@gmail.com>

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
!bench

**Review by alreadydone — APPROVED** [review]
maintainer merge

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by eric-wieser** [comment]
bors merge

**Pull request closed without merging**
