### PR TITLE
[Merged by Bors] - perf(DirectSum.Ring): factor out data fields 

### PR DESCRIPTION
**Pull request by mattrobball**
During unification, we want Lean to unfold as little data as possible. Declaring instances with inlined data fields results in larger terms which need more checking. Here we factor out the `Mul` and `NatCast` instances.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by semorrison** [comment]
What's the status of this one? No measurable benchmarking result, but probably a good idea nonetheless?

**Comment by j-loreaux** [comment]
@mattrobball seems good to me. Go for it if you want.

bors d+

**Comment by mattrobball** [comment]
If you peek into the benchmark results you see some nontrivial gains. 

bors merge

**Pull request closed without merging**
