### PR TITLE
[Merged by Bors] - feat: induction principles for ContinuousMap via Stone-Weierstrass

### PR DESCRIPTION
**Pull request by j-loreaux**
This PR provides induction lemmas for `C(s, 𝕜)` and `C(s, 𝕜)₀` with `RCLike 𝕜`. The idea is that when `s` is compact, the `closure` hypothesis will follow from the Stone-Weierstrass theorem and a limit property of the motive `p`.

---

This is useful to show, for instance, that if `a b : A` are nonnegative commuting elements of a C⋆-algebra, then `a * b` is nonnegative (because `√a = cfc NNReal.sqrt a`, and `cfc f a` commutes with `b` for any `f` by the induction lemma, therefore, `a * b = √a * b * √a ≥ 0`).

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by j-loreaux** [comment]
That doesn't help? You still need your motive to satisfy some sort of limit condition.

**Comment by j-loreaux** [comment]
If you thought it would be useful, I could add something like this:
```
open Topology in
@[elab_as_elim]
theorem ContinuousMap.induction_on' {𝕜 : Type*} [RCLike 𝕜] {s : Set 𝕜} [CompactSpace s]
    {p : C(s, 𝕜) → Prop} (const : ∀ r, p (.const s r)) (id : p (.restrict s <| .id 𝕜))
    (add : ∀ f g, p f → p g → p (f + g)) (mul : ∀ f g, p f → p g → p (f * g))
    (star : ∀ f, p f → p (star f))
    (tendsto : ∀ f, (∃ᶠ g in 𝓝 f, p g) → p f) (f : C(s, 𝕜)) :
    p f := by
  refine f.induction_on const id add mul star fun h f ↦ tendsto f ?_
  have := polynomialFunctions.starClosure_topologicalClosure s ▸ mem_top (x := f)
  rw [← SetLike.mem_coe, topologicalClosure_coe, mem_closure_iff_frequently] at this
  exact this.mp <| .of_forall h
```

**Comment by dupuisf** [comment]
Yeah, that's the sort of statement I was thinking of. Maybe I'm wrong but it does look useful!

**Comment by j-loreaux** [comment]
I've added versions with `Filter.Frequently`.

**Review by JonBannon — COMMENTED** [review]
LGTM

**Comment by dupuisf** [comment]
Great; thanks!

bors r+

**Pull request closed without merging**
