### PR TITLE
[Merged by Bors] - feat: there are finitely many lists of a fixed length

### PR DESCRIPTION
**Pull request by YaelDillies**
From LeanCamCombi

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by vihdzp** [comment]
Isn't this basically [`Vector.finite`](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Data/Finite/Basic.html#Vector.finite)?

**Comment by YaelDillies** [comment]
Well spotted. Golfed

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Review by b-mehta — COMMENTED** [review]
Nice!

bors merge

**Pull request closed without merging**
