### PR TITLE
[Merged by Bors] - chore: remove several stray sections

### PR DESCRIPTION
**Pull request by grunweg**
- Topology/Separation: fix typo "section/end"
- Mathlib/NumberTheory/LSeries/HurwitzZeta.lean: fix typo "namespace/end" In both cases, a second identical section resp. namespace was *opened* instead of closing the existing one.

- Topology/ExtremallyDisconnected: remove superfluous anonymous section. The entire file is already inside a noncomputable section; this sections adds nothing on top. (The nested section is also processed as a noncomputable section.)

- RingTheory/Bialgebra/Basic, RingTheory/HopfAlgebra: remove section CommRing in favour of the namespace CommRing a few lines later

- ModuleCat/Sheaf/Colimits: remove duplicate namespace SheafOfModules
- Probability/Distributions/Uniform.lean: this file is inside a noncomputable section already; a *second* such section (nested right under the first) was superfluous

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Good catch! You're probably right - let's try the new linter on master.

**Comment by adomani** [comment]
Since it passes CI, and I'm happy with all the changes,

maintainer merge

Thanks!

**Comment by adomani** [comment]
maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
