### PR TITLE
[Merged by Bors] - perf (Site.DenseSubsite): speed up file 

### PR DESCRIPTION
**Pull request by mattrobball**
`rintro` and `obtain` are misbehaving here in a way `rcases` is not. We cut the instructions by ~40% by prefacing some `rintro` calls with a `dsimp` and by replacing `obtain`s with `have; rcases`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Review by grunweg — APPROVED** [review]
Nice find! Are there any other files with the same issue/is this indicate of a bug in rintro/rcases?

**Comment by mattrobball** [comment]
For 5 minutes, I stared at the implementations of `obtain` to try to figure why `have h; rcases h with` is much faster here and couldn't immediately find it. 

I think prefacing `rintro` with `dsimp` might be a good idea generally but there is probably something more surgical that can be done internal to the implementation.

**Comment by j-loreaux** [comment]
Can you please add some comments (preferably in a way that we can track as technical debt, but I'm not sure what that is) near at least one `dsimp; rintro` and one `have; rcases` explaining the change and the performance change?

bors d+

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
