### PR TITLE
[Merged by Bors] - chore: split Mathlib.MeasureTheory.Function.StronglyMeasurable.Basic

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
!bench

**Comment by Ruben-VandeVelde** [comment]
!bench

**Comment by Ruben-VandeVelde** [comment]
**If** those results are genuine, we're back to the linear algebra/ring theory side of mathlib for the longest pole:
```diff
-Analyzing Mathlib at d1d1e4b72c6e009edd97cabe1d661b021fe8eeae
+Analyzing Mathlib at 3ef20a3771f3b286e269e73b127d504f65d54f0a
 file                                                           | instructions | (cumulative) | parallelism
 -------------------------------------------------------------- | ------------ | ------------ | -----------
-Mathlib.MeasureTheory.Function.LpSeminorm.CompareExp           |        26571 |      3212793 | x8.59
-Mathlib.MeasureTheory.Function.LpSeminorm.Basic                |        58719 |      3186221 | x8.51
-Mathlib.MeasureTheory.Function.AEEqFun                         |        35309 |      3127501 | x8.19
-Mathlib.MeasureTheory.Function.StronglyMeasurable.Basic        |        71357 |      3092192 | x8.20
-Mathlib.Analysis.NormedSpace.BoundedLinearMaps                 |        95837 |      3020834 | x6.48
-Mathlib.Analysis.NormedSpace.Multilinear.Basic                 |       351807 |      2924997 | x6.42
-Mathlib.Analysis.NormedSpace.OperatorNorm.NormedSpace          |        75076 |      2573190 | x7.03
-Mathlib.Analysis.NormedSpace.OperatorNorm.Bilinear             |       160566 |      2498114 | x7.20
-Mathlib.Analysis.NormedSpace.OperatorNorm.Basic                |       106200 |      2337547 | x7.62
-Mathlib.Analysis.LocallyConvex.WithSeminorms                   |       105728 |      2231346 | x7.82
-Mathlib.Topology.Algebra.Equicontinuity                        |         7224 |      2125617 | x7.28
-Mathlib.Topology.Algebra.UniformConvergence                    |        32759 |      2118393 | x7.30
-Mathlib.Analysis.LocallyConvex.Bounded                         |        40075 |      2085634 | x7.39
-Mathlib.Analysis.Seminorm                                      |       172597 |      2045558 | x7.30
-Mathlib.Analysis.LocallyConvex.Basic                           |        38808 |      1872961 | x7.78
-Mathlib.Analysis.NormedSpace.Basic                             |        29717 |      1834152 | x7.50
-Mathlib.Analysis.Normed.MulAction                              |        18328 |      1804435 | x7.58
-Mathlib.Analysis.Normed.Field.Basic                            |        88554 |      1786106 | x7.65
-Mathlib.Analysis.Normed.Group.Basic                            |       101480 |      1697551 | x6.72
-Mathlib.Topology.MetricSpace.IsometricSMul                     |        30947 |      1596071 | x6.53
-Mathlib.Topology.MetricSpace.Isometry                          |        13630 |      1565123 | x5.40
-Mathlib.Topology.MetricSpace.Antilipschitz                     |         8223 |      1551493 | x5.43
-Mathlib.Topology.MetricSpace.Bounded                           |        13970 |      1543270 | x5.44
-Mathlib.Topology.MetricSpace.ProperSpace                       |         5472 |      1529300 | x5.48
-Mathlib.Topology.Algebra.Order.Compact                         |        27921 |      1523827 | x4.22
-Mathlib.Topology.Order.IntermediateValue                       |        51390 |      1495906 | x4.17
-Mathlib.Topology.Order.DenselyOrdered                          |        86127 |      1444516 | x4.27
-Mathlib.Topology.Order.IsLUB                                   |        15685 |      1358388 | x4.48
-Mathlib.Topology.Order.LeftRightNhds                           |        33011 |      1342702 | x4.52
-Mathlib.Topology.Order.Basic                                   |        36990 |      1309690 | x4.58
-Mathlib.Topology.Order.OrderClosed                             |        30431 |      1272700 | x4.16
-Mathlib.Topology.Separation                                    |        45336 |      1242268 | x4.24
-Mathlib.Topology.Compactness.SigmaCompact                      |         8106 |      1196932 | x4.20
-Mathlib.Topology.Compactness.LocallyCompact                    |         5462 |      1188825 | x4.22
-Mathlib.Topology.Compactness.Compact                           |        28699 |      1183362 | x4.23
-Mathlib.Topology.Bases                                         |        31553 |      1154663 | x4.30
-Mathlib.Topology.ContinuousOn                                  |        28727 |      1123110 | x4.39
-Mathlib.Topology.Constructions                                 |        37153 |      1094382 | x4.48
-Mathlib.Topology.Maps                                          |        12109 |      1057229 | x4.59
-Mathlib.Topology.Order                                         |        17096 |      1045119 | x4.64
-Mathlib.Topology.Defs.Induced                                  |         3504 |      1028023 | x4.70
-Mathlib.Topology.Basic                                         |        30409 |      1024518 | x4.71
-Mathlib.Topology.Defs.Filter                                   |         8023 |       994109 | x4.81
-Mathlib.Order.Filter.Ultrafilter                               |        12332 |       986085 | x4.72
-Mathlib.Order.Filter.Cofinite                                  |         6146 |       973753 | x4.71
-Mathlib.Order.Filter.AtTopBot                                  |        63624 |       967606 | x4.72
-Mathlib.Order.Filter.Bases                                     |        21732 |       903982 | x4.58
-Mathlib.Order.Filter.Prod                                      |        16154 |       882249 | x4.29
-Mathlib.Order.Filter.Basic                                     |        62918 |       866094 | x4.35
+Mathlib.MeasureTheory.Function.LpSeminorm.CompareExp           |        26235 |      3111898 | x7.64
+Mathlib.MeasureTheory.Integral.MeanInequalities                |        35170 |      3085663 | x7.58
+Mathlib.Analysis.MeanInequalities                              |        54554 |      3050493 | x7.29
+Mathlib.Analysis.SpecialFunctions.Pow.NNReal                   |        38041 |      2995938 | x7.04
+Mathlib.Analysis.SpecialFunctions.Pow.Real                     |        42411 |      2957896 | x7.12
+Mathlib.Analysis.SpecialFunctions.Pow.Complex                  |        25247 |      2915485 | x7.21
+Mathlib.Analysis.SpecialFunctions.Complex.Log                  |        17220 |      2890238 | x7.26
+Mathlib.Analysis.SpecialFunctions.Complex.Arg                  |        45677 |      2873017 | x7.29
+Mathlib.Analysis.SpecialFunctions.Trigonometric.Angle          |        54300 |      2827340 | x7.38
+Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic          |        91584 |      2773039 | x7.35
+Mathlib.Analysis.SpecialFunctions.Exp                          |        21743 |      2681455 | x7.56
+Mathlib.Analysis.Complex.Asymptotics                           |         3995 |      2659712 | x7.59
+Mathlib.Analysis.Complex.Basic                                 |        74156 |      2655717 | x7.53
+Mathlib.Data.Complex.Module                                    |        86268 |      2581561 | x7.17
+Mathlib.LinearAlgebra.FiniteDimensional                        |       105214 |      2495292 | x6.20
+Mathlib.LinearAlgebra.Dimension.DivisionRing                   |        45057 |      2390078 | x6.42
+Mathlib.LinearAlgebra.Dimension.RankNullity                    |        28586 |      2345020 | x6.48
+Mathlib.LinearAlgebra.Dimension.Constructions                  |        93087 |      2316433 | x6.52
+Mathlib.Algebra.Module.Torsion                                 |        87883 |      2223346 | x6.69
+Mathlib.GroupTheory.Torsion                                    |        18495 |      2135462 | x6.89
+Mathlib.GroupTheory.PGroup                                     |        19390 |      2116967 | x6.94
+Mathlib.GroupTheory.SpecificGroups.Cyclic                      |        43573 |      2097577 | x6.90
+Mathlib.GroupTheory.Exponent                                   |        25245 |      2054004 | x6.29
+Mathlib.Data.ZMod.Quotient                                     |        22133 |      2028759 | x6.25
+Mathlib.RingTheory.Int.Basic                                   |         7272 |      2006625 | x6.06
+Mathlib.RingTheory.PrincipalIdealDomain                        |        25741 |      1999353 | x6.07
+Mathlib.RingTheory.UniqueFactorizationDomain                   |        83598 |      1973612 | x6.12
+Mathlib.RingTheory.Noetherian                                  |       104006 |      1890013 | x6.31
+Mathlib.RingTheory.OrzechProperty                              |         6861 |      1786006 | x6.37
+Mathlib.RingTheory.Finiteness                                  |       102301 |      1779145 | x6.36
+Mathlib.RingTheory.Ideal.Maps                                  |        50401 |      1676843 | x5.89
+Mathlib.RingTheory.Ideal.Operations                            |        80941 |      1626442 | x6.05
+Mathlib.Algebra.Algebra.Operations                             |        67063 |      1545500 | x6.29
+Mathlib.Algebra.Algebra.Bilinear                               |        21530 |      1478437 | x5.40
+Mathlib.LinearAlgebra.TensorProduct.Basic                      |       260593 |      1456906 | x4.85
+Mathlib.Algebra.Module.Submodule.Bilinear                      |        14785 |      1196312 | x5.65
+Mathlib.LinearAlgebra.Span                                     |        71310 |      1181526 | x5.63
+Mathlib.LinearAlgebra.Basic                                    |        21997 |      1110216 | x5.55
+Mathlib.Algebra.Module.Submodule.Range                         |        25722 |      1088218 | x5.36
+Mathlib.Algebra.Module.Submodule.Ker                           |        26142 |      1062496 | x5.46
+Mathlib.Algebra.Module.Submodule.Map                           |        40854 |      1036354 | x5.58
+Mathlib.Algebra.Module.Submodule.Lattice                       |        31235 |       995499 | x5.75
+Mathlib.Algebra.Module.Submodule.Basic                         |        33368 |       964263 | x5.13
+Mathlib.Algebra.Group.Submonoid.Membership                     |        30285 |       930895 | x4.72
+Mathlib.Data.Finset.NoncommProd                                |        15227 |       900609 | x4.22
+Mathlib.Algebra.BigOperators.Group.Finset                      |        77544 |       885381 | x4.27
+Mathlib.Data.Finset.Preimage                                   |         4664 |       807837 | x4.44
 Mathlib.Data.Set.Finite                                        |        3527_ |       80317_ | x4.46
```

**Comment by MichaelStollBayreuth** [comment]
```text
General information:
  build:                                               -5.4889 * 10⁹ (-0.00449%)

No file got slower by at least 10⁹ instructions.

No file got slower by at least 10%.

3 files got faster by at least 10⁹ instructions:
  Mathlib.MeasureTheory.Function.StronglyMeasurable.Basic:
                                                       -10.363 * 10⁹ (-14.5%)
  Mathlib.MeasureTheory.Function.AEEqFun:              -1.5779 * 10⁹ (-4.47%)
  Mathlib.MeasureTheory.Function.Egorov:               -1.2830 * 10⁹ (-10.2%)

2 files got faster by at least 10%:
  Mathlib.MeasureTheory.Function.StronglyMeasurable.Basic:            -14.5%
  Mathlib.MeasureTheory.Function.Egorov:                              -10.2%
```
The `build` timings are probably noise...

**Comment by mattrobball** [comment]
There was some hiccup with benchmarking of #13754

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge
Thanks :tada:

bors merge

**Pull request closed without merging**
