### PR TITLE
[Merged by Bors] - chore(SetTheory/Game/PGame): Add note on `NatCast`

### PR DESCRIPTION
**Pull request by vihdzp**
I explain that this is not in fact the usual definition for natural numbers as games (a fact that just cost me a few hours of dev time...)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by YaelDillies — COMMENTED** [review]
The definition is not the usual one, but it is *equivalent* to the usual one, right? Can you also link to the theorem that asserts this?

**Comment by vihdzp** [comment]
We actually don't have that theorem yet. I prove it on #15716 though, so I can add said note there.

**Comment by YaelDillies** [comment]
Okay then

maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
