### PR TITLE
feat: port Analysis.Calculus.Deriv

### PR DESCRIPTION
**Pull request by urkud**
---

- [x] depends on: #4221
- [x] depends on: #4239
- [x] depends on: #4241
- [ ] depends on: https://github.com/leanprover-community/mathlib/pull/19113

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4221
* leanprover-community/mathlib4#4239
* leanprover-community/mathlib4#4241
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by eric-wieser** [comment]
The port dashboard says

> Please wait for [mathlib3#19038](https://github.com/leanprover-community/mathlib/pull/19038)

That PR is already maintainer merged; can we merge it to unblock this?

**Comment by urkud** [comment]
I'm sorry for missing this comment. I reviewed mathlib3#19038. I will deal with updated source file once that PR is merged and mathport will finish.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4221~~
* ~~leanprover-community/mathlib4#4239~~
* ~~leanprover-community/mathlib4#4241~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by eric-wieser** [comment]
@Parcly-Taxel: please don't, see @urkud's zulip post

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4221~~
* ~~leanprover-community/mathlib4#4239~~
* ~~leanprover-community/mathlib4#4241~~
* ~~leanprover-community/mathlib#19113~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by urkud** [comment]
In fact, I was able to use @Parcly-Taxel's fixes to this branch. I saved the file from this branch, then opened `ediff` in Emacs between this file and `mathport` output for each of the new files. Then I copied all small fixes while ignoring larger chunks. So, thank you @Parcly-Taxel but next time please ask the PR author before working on their PR unless the PR is `help-wanted`.

**Pull request closed without merging**
