### PR TITLE
[Merged by Bors] - chore: rename Fin.cast to Fin.castIso

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
@Parcly-Taxel did I mark this as help wanted when I wasn't looking?

**Comment by fpvandoorn** [comment]
Is this ready for review?

**Comment by Parcly-Taxel** [comment]
> Is this ready for review?

Yes.

**Comment by fpvandoorn** [comment]
@Parcly-Taxel: We have mentioned this before to you: please don't push to to other people's branches unless there is an `help-wanted` label.

**Pull request closed without merging**
