### PR TITLE
[Merged by Bors] - chore: fix some names

### PR DESCRIPTION
**Pull request by urkud**
* Protect `HasFTaylorSeriesUpToOn.fderivWithin`,
  `IsBoundedBilinearMap.fderiv`, and
  `IsBoundedBilinearMap.fderivWithin`.

* Rename
  - `isBoundedBilinearMapSmul` -> `isBoundedBilinearMap_smul`;
  - `isBoundedBilinearMapMul` -> `isBoundedBilinearMap_mul`;
  - `isBoundedBilinearMapComp` -> `isBoundedBilinearMap_comp`;
  - `isBoundedBilinearMapSmulRight` -> `isBoundedBilinearMap_smulRight`;
  - `isBoundedBilinearMapCompMultilinear` -> `isBoundedBilinearMap_compMultilinear`;
  - `ContinuousLinearMap.mulLeftRightIsBoundedBilinear` -> `ContinuousLinearMap.mulLeftRight_isBoundedBilinear`;
  - `nhdsWithin_eq_nhds_within'` -> `nhdsWithin_eq_nhdsWithin'`;
  - `ContinuousWithinAt.preimage_mem_nhds_within'` -> `ContinuousWithinAt.preimage_mem_nhdsWithin'`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by fpvandoorn** [comment]
bors d+

**Comment by urkud** [comment]
bors merge

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
