### PR TITLE
[Merged by Bors] - fix(Cardinal): fix theorem names

### PR DESCRIPTION
**Pull request by YnirPaz**
Remove unnecessary `of_lt_aleph_0` from 2 theorem names. Also fix typos in the comments of 2 other files.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by adomani — COMMENTED** [review]
Just adding the dates and LGTM!

**Comment by urkud** [comment]
bors d=adomani

**Comment by eric-wieser** [comment]
Please adjust the PR title to match the commit conventions before merging

**Comment by adomani** [comment]
Thanks!

bors r+

**Pull request closed without merging**
