### PR TITLE
feat(Algebra/Ring/Parity): Add lemma `odd_add_self_sub_one`

### PR DESCRIPTION
**Pull request by IvanRenison**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
Thanks for your PR. Do you have a particular motivation for adding this lemma. As you can see, it is pretty easy to obtain this by composing two other pieces. And it is not clear to me that this lemma will be used a lot...

**Comment by IvanRenison** [comment]
I was adding this:
```lean
lemma odd_iff_even_add_one {n : ℕ} [NeZero n] {k : Fin n} : Odd k ↔ Even (k + 1) := sorry
```
In the proof I arrived to `Odd (k + k - 1)` as goal and I thought that it was a good idea to have it as a separate lemma, but if you think is better not its okey

**Comment by jcommelin** [comment]
I think
```
lemma odd_iff_even_add_one {n : ℕ} [NeZero n] {k : Fin n} : Odd k ↔ Even (k + 1) := sorry
```
is a good lemma to add to the library!

**Comment by IvanRenison** [comment]
Okey. So, I close this pull request and use the composing?

**Comment by jcommelin** [comment]
You can also continue using this PR. Just update the title, and push the new code.

**Pull request closed without merging**
