### PR TITLE
[Merged by Bors] - chore(workflows/nightly_detect_failure): log messages

### PR DESCRIPTION
**Pull request by jcommelin**
The friendly bot repeats itself for no good reason.
We start logging messages to debug the issue.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
LGTM!

What I had in mind was printing to shell in which the action takes place.  However also printing to the actual message has the same effect!

There is an `or` in the condition: would this give you information regardless of which branch of the `or` is true?

**Comment by jcommelin** [comment]
No, it only prints messages if there are actually messages to print. But this should always be true, since the Zulip thread has been nonempty for decades :smiley:

**Comment by adomani** [comment]
Ok, I understand now!

If you nevertheless want to remove the precondition on line 206, I would still

maintainer merge

this PR!  :smile:

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
