### PR TITLE
[Merged by Bors] - feat: restore the module docstring code snippet

### PR DESCRIPTION
**Pull request by alexjbest**
We had this in mathlib3, allowing one to type `mo` (then press tab, at least for me) in an empty file and have a snippet template of a module docstring inserted with the title named to the filename, which can save a little time.
The implementation is now a bit overkill as it splits on `_` and capitalizes still to get from the filename to the module title, which likely has no affect for most lean 4 filenames.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ericrbg** [comment]
could we also have the copyright snippet?

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by alexjbest** [comment]
> could we also have the copyright snippet?

I think that's already there, did you try it?

**Comment by ericrbg** [comment]
indeed, fuzzy memory:)

**Pull request closed without merging**
