### PR TITLE
[Merged by Bors] - feat: port Archive.Examples.MersennePrimes

### PR DESCRIPTION
**Pull request by jcommelin**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
The remaining bit in this PR is a port of the tactic `LucasLehmer.run_test`.

**Comment by jcommelin** [comment]
bors d=thorimur

**Comment by kmill** [comment]
Can you hold off on merging for a bit? I'd like a chance to look through this

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
