### PR TITLE
[Merged by Bors] - feat: the forget functor from ModuleCat to AddCommGrp reflects all limits

### PR DESCRIPTION
**Pull request by joelriou**
The forget functor from the category of modules to abelian groups reflects all limits (regardless of universes).

This may reduce universe assumptions in #14254.

This contribution was created as part of the AIM workshop "Formalizing algebraic geometry" in June 2024.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by erdOne — APPROVED** [review]
Maybe we should have `t` be the first in line 24.
Otherwise LGTM.

**Comment by joelriou** [comment]
> Maybe we should have `t` be the first in line 24. Otherwise LGTM.

Good idea.  I have just put the universe `t` first.

**Comment by erdOne** [comment]
Thanks!
maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
