### PR TITLE
chore: fixes for leanprover/lean4#2749

### PR DESCRIPTION
**Pull request by kim-em**
leanprover/lean4#2749 causes a breakage in between ProofWidgets and Mathlib, that we need to get sorted out!

https://github.com/leanprover-community/ProofWidgets4/pull/32 is the testing PR at ProofWidgets that uses this toolchain.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by tydeu** [comment]
@semorrison It has been on the `get cache` step for over an hour. That seems concerning. Is this a known issue.

**Comment by semorrison** [comment]
> @semorrison It has been on the `get cache` step for over an hour. That seems concerning. Is this a known issue?

No it's not. The warnings

```
Warning: lake-packages/std/Std.lean not found. Skipping all files that depend on it
Warning: lake-packages/std/Std/Lean/Command.lean not found. Skipping all files that depend on it
Warning: lake-packages/std/Std/Data/List/Basic.lean not found. Skipping all files that depend on it
Warning: lake-packages/std/Std/Util/TermUnsafe.lean not found. Skipping all files that depend on it
Warning: lake-packages/std/Std/Lean/Expr.lean not found. Skipping all files that depend on it
Warning: lake-packages/std/Std/Data/List/Basic.lean not found. Skipping all files that depend on it
Warning: lake-packages/std/Std/Tactic/OpenPrivate.lean not found. Skipping all files that depend on it
```
are also unusual.

However locally it needed a `lake update proofwidgets` still, so I have just pushed that and we'll see if it comes good on the next try.

**Comment by tydeu** [comment]
@semorrison Oops, you posting the error made me realize it said `lake-packages` and at least one problem here is that cache hard-codes the path to `lake-packages` (now `.lake/packages`) here:

https://github.com/leanprover-community/mathlib4/blob/049141bc4e392809ec982618a8e5f7efb3256a62/Cache/IO.lean#L81

Ideally, it would be getting this from the `lake-manifest.json`, but, for now, I guess we can just change the it to `".lake" / "packages"`. However, the fact that it hangs indefinitely when the folder is missing is still concerning.

**Comment by semorrison** [comment]
Yes please, push away!

**Pull request closed without merging**
