### PR TITLE
[Merged by Bors] - feat: homeomorphisms preserve local compactness

### PR DESCRIPTION
**Pull request by smmercuri**
Add a theorem `Homeomorph.locallyCompactSpace` that if the codomain of a homeomorphism is a locally compact space, then the domain is also a locally compact space.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Thank you for your contribution, and welcome to mathlib!
I presume your PR is ready for review - hence have labelled it `awaiting-review`. (Otherwise, it may slip through the cracks.) Have you seen the [contribution guidelines](https://leanprover-community.github.io/contribute/index.html) already? They mention this fact, and a few other tips.

**Comment by fpvandoorn** [comment]
Note: we already have [ClosedEmbedding.locallyCompactSpace](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Topology/Compactness/LocallyCompact.html#ClosedEmbedding.locallyCompactSpace) and the proof could be roughly `h.closedEmbedding.locallyCompactSpace`. Because of that, I'm not sure it's worth adding, but it could be a nice shortcut.

**Comment by smmercuri** [comment]
> Note: we already have [ClosedEmbedding.locallyCompactSpace](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Topology/Compactness/LocallyCompact.html#ClosedEmbedding.locallyCompactSpace) and the proof could be roughly `h.closedEmbedding.locallyCompactSpace`. Because of that, I'm not sure it's worth adding, but it could be a nice shortcut.

Thanks for alerting me to `h.closedEmbedding.locallyCompactSpace`, that was off my radar! I agree that the previous version of the result was probably not worth adding as it was just a rename of that result. I wonder if it's worth adding the revised version however, making use of both directions `h.closedEmbedding` and `h.symm.openEmbedding` to give an if and only if. It might be easier to find for someone looking directly for a homeomorphism result on locally compact spaces. Although I no longer actually need this revised version in my own project as `h.closedEmbedding.locallyCompactSpace` will do, so I'm happy with either decision on whether the revised one is worth adding.

**Comment by fpvandoorn** [comment]
Sure, that seems worth it.

bors merge

**Pull request closed without merging**
