### PR TITLE
[Merged by Bors] - chore(Data/Stream/Init): use `ℕ` instead of `Nat` consistently

### PR DESCRIPTION
**Pull request by grunweg**
The file currently uses a mix of these: use the nice unicode character, since we can.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
That is a reasonable argument, in principle. Note that the file is currently inconsistent about this.

**Review by Komyyy — CHANGES_REQUESTED** [review]
This PR looks reasonable!
A further request from me is that `Stream.Defs` should also be edited.

**Comment by grunweg** [comment]
> This PR looks reasonable! A further request from me is that `Stream.Defs` should also be edited.

Done!

**Review by Komyyy — APPROVED** [review]

**Comment by Komyyy** [comment]
@grunweg Thank you!

**Comment by j-loreaux** [comment]
I asked Kim and they were fine with this.

bors merge

**Pull request closed without merging**
