### PR TITLE
feat: Generalize `IsLocalRingHom` to monoids.

### PR DESCRIPTION
**Pull request by erdOne**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ericrbg** [comment]
I have some of this already in #6045

**Comment by erdOne** [comment]
Great! What is the state of that PR?

**Comment by ericrbg** [comment]
It seems all fine, I'm happy to bump it as needed, but people don't want to merge it because they're scared about some small performance drops. I've pinged you in a relevant Zulip thread.

**Comment by erdOne** [comment]
Closing in favor of #6045.

**Pull request closed without merging**
