### PR TITLE
[Merged by Bors] - move(Topology/Order): Move anything that doesn't concern algebra

### PR DESCRIPTION
**Pull request by YaelDillies**
Move files from `Topology.Algebra.Order` to `Topology.Order` when they do not contain any algebra. Also move `Topology.LocalExtr` to `Topology.Order.LocalExtr`.

According to git, the moves are:

* `Mathlib/Topology/{Algebra => }/Order/ExtendFrom.lean`
* `Mathlib/Topology/{Algebra => }/Order/ExtrClosure.lean`
* `Mathlib/Topology/{Algebra => }/Order/Filter.lean`
* `Mathlib/Topology/{Algebra => }/Order/IntermediateValue.lean`
* `Mathlib/Topology/{Algebra => }/Order/LeftRight.lean`
* `Mathlib/Topology/{Algebra => }/Order/LeftRightLim.lean`
* `Mathlib/Topology/{Algebra => }/Order/MonotoneContinuity.lean`
* `Mathlib/Topology/{Algebra => }/Order/MonotoneConvergence.lean`
* `Mathlib/Topology/{Algebra => }/Order/ProjIcc.lean`
* `Mathlib/Topology/{Algebra => }/Order/T5.lean`
* `Mathlib/Topology/{ => Order}/LocalExtr.lean`

---

This is a rehash of https://github.com/leanprover-community/mathlib/pull/17859.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
maintainer merge

**Comment by mattrobball** [comment]
bors merge

**Comment by mattrobball** [comment]
bors delegate+

**Comment by YaelDillies** [comment]
bors merge

**Pull request closed without merging**
