### PR TITLE
[Merged by Bors] - feat(Logic/Function): add `Function.extend_const`

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by b-mehta** [comment]
Could be a nice simp lemma?

bors d+

**Comment by urkud** [comment]
@mattrobball Is it a good `simp` lemma, or the keys are too weak? Also, could you please teach me how to find the keys, so that I can do it myself next time instead of asking you?

**Comment by mattrobball** [comment]
`#discr_tree_simp_key` is the command. I can't get to a computer very soon but I'm guessing this fine since `extend` should appear.

**Comment by urkud** [comment]
!bench

**Comment by urkud** [comment]
`extend` is the only key. Unless benchmark shows a significant slowdown (I doubt that), I'm going to merge this PR with `@[simp]`.

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
