### PR TITLE
[Merged by Bors] - feat: port Order.CompleteBooleanAlgebra

### PR DESCRIPTION
**Pull request by ADedecker**

### CODE REVIEW

**Comment by ADedecker** [comment]
There seems to be a performance problem with `CompleteDistribLattice` that I don't understand: all three instances of it declared in this file take a lot of time (I'd say more than everything else in the file). If that matters, not that all of them are declared as `{ someFrameInstance, someCoframeInstance with }`. I tried changing the definition of `CompleteDistribLattice` to just extend both `Frame` and `Coframe`, but it didn't make things any better.

**Comment by semorrison** [comment]
bors merge

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
