### PR TITLE
[Merged by Bors] - feat: add lemma not_mem_singleton_iff

### PR DESCRIPTION
**Pull request by sinhp**
The contrapositive (?) of the lemma 
```
theorem mem_singleton_iff {a b : α} : a ∈ ({b} : Set α) ↔ a = b :=
  Iff.rfl
```
was missing. This PR adds 

```
@[simp]
theorem not_mem_singleton_iff {a b : α} : a ∉ ({b} : Set α) ↔ a ≠ b :=
  Iff.rfl
```
which can be useful in avoiding extra `have` statements in other proofs. 

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by dagurtomas** [comment]
This PR includes some Grothendieck construction stuff, which it shouldn't, according to the PR description

**Comment by sinhp** [comment]
> This PR includes some Grothendieck construction stuff, which it shouldn't, according to the PR description

So, I think this is because I am doing something wrong: I have only one mathlib repo locally, and do all my PRs from that. I do follow the Mathlib contribution guidelines in switching branches first, but nevertheless I get the problem that this PR for sets shows up as a continuation of `GrothendieckIsFunctorial` branch. What am I missing?

**Comment by erdOne** [comment]
`git checkout master Mathlib/CategoryTheory/Grothendieck.lean` on that branch will reset the file to master.
Be sure to back up first!

**Comment by sinhp** [comment]
> `git checkout master Mathlib/CategoryTheory/Grothendieck.lean` on that branch will reset the file to master. Be sure to back up first!

Just did that. Would the next step be for the current PR (i.e. not_mem_singleton_iff) be to commit the change (i.e. resetting Grothendieck.lean back to the master version) and push?

**Comment by erdOne** [comment]
Yes.

**Comment by erdOne** [comment]
Thanks!
maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
