### PR TITLE
[Merged by Bors] - chore: remove `CoeFun` instances where `FunLike` is available

### PR DESCRIPTION
**Pull request by Vierkantor**
During the port we found that `FunLike` is robust enough not to need an extra `CoeFun` shortcut. Let's see if that rule can be consistently applied to the whole of the library.

There is still duplication between `FunLike` and `CoeFun` for `Grp`, `Mon`, `CommGrp` and `CommMon`, which will need a more thorough fix. See also #17866.

This is the second half of #17870, and doesn't affect the benchmarks.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Vierkantor** [comment]
!bench

**Comment by Vierkantor** [comment]
Progress! So I suppose I'll make this PR ready for review and open a new one with half of the remaining changes.

**Comment by grunweg** [comment]
Thanks - landing this piece-wise is still a great improvement!
maintainer merge

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
