### PR TITLE
[Merged by Bors] - feat: generalize sheaf condition to only the relevant pullbacks existing

### PR DESCRIPTION
**Pull request by dagurtomas**
We define a predicate `Presieve.hasPullbacks` which says that the pullback of every pair of arrows in the presieve exists. This allows to generalize `Equalizer.Presieve.sheaf_condition` to categories that don't necessarily have all pullbacks (such as `Stonean`). 

Co-authored-by: Riccardo Brasca @riccardobrasca [riccardo.brasca@gmail.com](mailto:riccardo.brasca@gmail.com)
Co-authored-by: Filippo A E Nuccio @faenuccio [filippo.nuccio@univ-st-etienne.fr](mailto:filippo.nuccio@univ-st-etienne.fr)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by dagurtomas** [comment]
`Presieve.hasPullbacks` was https://github.com/adamtopaz/CopenhagenMasterclass2023/blob/master/Sieves/isSheafForPullbackSieve.lean#L13-L15

**Comment by dagurtomas** [comment]
Instead of doing all the primed versions of the definitions and theorems in [the Copenhagen repo](https://github.com/adamtopaz/CopenhagenMasterclass2023/blob/master/Sieves/isSheafForPullbackSieve.lean), I provided an instance [R.hasPullbacks] given [HasPullbacks C] and generalized the existing versions.

**Comment by dagurtomas** [comment]
It's a bit annoying that Lean doesn't automatically find an instance for `HasPullback f g` given `(hf : R f)`, `(hg : R g)` and `[R.hasPullbacks]`. Is there a way to fix this?

**Comment by dagurtomas** [comment]
> It's a bit annoying that Lean doesn't automatically find an instance for `HasPullback f g` given `(hf : R f)`, `(hg : R g)` and `[R.hasPullbacks]`. Is there a way to fix this?

And now the linter complains that there are unnecessary `have` statements...

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
