### PR TITLE
Revert "feat(NumberTheory/PrimeCounting): Lemma: The `n`th prime is greater or equal `n + 2`."

### PR DESCRIPTION
**Pull request by erdOne**
Reverts leanprover-community/mathlib4#13283

### CODE REVIEW

**Comment by kmill** [comment]
@erdOne What's your intention with reverting Kevin's mistaken merge? Do you not want it merged? Or are you trying to make sure it gets merged correctly through Bors?

**Comment by erdOne** [comment]
I thought force-pushing would also cause troubles? If the mistaken merge won't cause troubles later on then we can keep it.

**Comment by kmill** [comment]
Maintainers are talking about what to do here. Just to check, you're just helping with the revert process in case we need to revert it, but you're ok with https://github.com/leanprover-community/mathlib4/pull/13283 having been merged, correct?

**Comment by erdOne** [comment]
Yes.

**Comment by kmill** [comment]
Thanks for your quick action on this by the way. (I was writing a message to you and got distracted in the meantime.) We did end up deciding to risk Kevin's push to master given that it already went through review.

**Pull request closed without merging**
