### PR TITLE
[Merged by Bors] - fix(says tactic): Don’t stumble over `Try this:\n` instead of `Try this:␣`

### PR DESCRIPTION
**Pull request by nomeata**
as discussed in
https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/.E2.9C.94.20Lake.20build.20succeeds.20on.20local.2C.20but.20fails.20on.20GitHub.20Action/near/397679705

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Seasawher** [comment]
Thank you! 👍

**Comment by alexjbest** [comment]
I assume this is awaiting review as it does what it says already ;)

maintainer merge

**Comment by nomeata** [comment]
I'm unsure about the etiquette of already setting awaiting-review when CI is still running…

**Review by jcommelin — APPROVED** [review]
Thanks :tada: 

If CI passes, please remove the label `awaiting-CI` and merge this yourself, by adding a comment `bors r+`.

bors d+

**Comment by alexjbest** [comment]
Its fine to do so.
The definition of `queue` is `is:open label:awaiting-review sort:updated-asc -label:blocked-by-other-PR -label:merge-conflict -status:failure -label:awaiting-CI ` so if CI fails then it will never show up there, but it saves you having to check back by doing so and makes the situation clearer in cases like this (by the time I looked at it the tests step had already passed CI)

**Comment by nomeata** [comment]
merge r+

**Comment by nomeata** [comment]
bors r+

🤦🏻

**Pull request closed without merging**
