### PR TITLE
[Merged by Bors] - feat: `ExistsAddOfLE` lemmas

### PR DESCRIPTION
**Pull request by YaelDillies**
Add a few convenient versions of `le_iff_exists_add`.

From LeanAPAP

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
> Interestingly, some statements generalise from `ExistsAddOfLE α` to `ExistsAddOfLEOrGE α`, which makes them dualisable.

Can you list these? There are none currently in the PR, right?

**Comment by YaelDillies** [comment]
I'm not going to copy the entire diff of #11448, so cf #11448

**Comment by semorrison** [comment]
This feels quite baroque to me, and I'm sceptical that such a notion belongs in a basic file.

**Comment by YaelDillies** [comment]
> This feels quite baroque to me

Sorry, I'm not sure what this comment means concretely for this PR.

I can move the definition to a new file, but then the lemmas I'm generalising should move too, which is a bit weird given that this is supposed to be an in-place generalisation.

**Comment by semorrison** [comment]
I'm saying that I don't believe this is a sufficiently natural notion to live in this file, and you should find a different way to achieve your application!

**Comment by YaelDillies** [comment]
The only different way I see is the state at the first commit (I'm on my phone so I can't easily check this is actually the first on this PR right now, but if you don't see it I can dig up the reflog) and you can see that it is just a huge load of duplication.

Here's the basic issue distilled in one example: `a <= b -> c <= d -> a • d + b • c <=  a • c + b • d` is true both when `a b : Nat` and when `a b : OrderDual Nat` (and `c d : Real`, sya)


If that can give a bit more gravitas to this PR, I am currently writing a paper about the general strategy behind generalising inequalities using `smul`.

**Comment by YaelDillies** [comment]
Update: I meant https://github.com/leanprover-community/mathlib4/pull/11448/commits/5cea0b9bd58be4113638510bc58153baefc34cdf

Other update: Seems like Matthew heard your call: #14390

**Comment by YaelDillies** [comment]
As per https://leanprover.zulipchat.com/#narrow/stream/144837-PR-reviews/topic/.2313950.20Dualisable.20notion.20of.20ExistsAddOfLE/near/465023218, I have found a way to generalise the rearrangement inequality even further and I do not need this new typeclasse anymore. Please review #15813, #15815, #11448 instead!

**Comment by YaelDillies** [comment]
Actually, I need some lemmas in here, so I would reopen the PR but remove `ExistsAddOfLEOrGE` from the diff

**Pull request closed without merging**
