### PR TITLE
[Merged by Bors] - chore: remove almost all `import Lean`

### PR DESCRIPTION
**Pull request by grunweg**
Replacing it by more fine-grained imports. `Lean` is still imported in `Tactic.Basic` and `GCongr/Core`; these are left on purpose.

---

This needs a `shake`; help doing this is welcome.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
Why does the commit summary tool report increase in imports? Does it ignore `import Lean`?

**Comment by grunweg** [comment]
If I understand correctly, the summary script just counts the number of transitive import lines. So splitting one `import Lean` into several more fine-grained additions counts as an increase in the total number of imports, or so.
@adomani Is this correct? (I think is is reasonable behaviour of the summary comment.)

**Comment by urkud** [comment]
Could you please fix compile?

**Comment by grunweg** [comment]
Done, except for shaking imports.

**Comment by adomani** [comment]
I thought that the import summary was a count of all transitive imports, so this looks like it should have been a "negative" (i.e. desirable) change.

I'll ping @jcommelin as he was the one who wrote that part of the PR summary script.

**Comment by adomani** [comment]
I think that I know what the issue is: the script looks for files in the `Mathlib` dir.  This Means that it counts transitive dependencies *inside mathlib* and absolute `import`lines for imports from dependencies.

This can be considered a borderline bug, but should explain the current behaviour.

**Pull request closed without merging**
