### PR TITLE
[Merged by Bors] - chore: split off Defs from `Padics/PadicVal`

### PR DESCRIPTION
**Pull request by rwst**
Split `NumberTheory/Padics/PadicVal.lean` into minimal `PadicVal/Defs` that suffices for import in `Factorization/Defs` and `NumberTheory/Multiplicity`, and `PadicVal/Basic`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by rwst** [comment]
@semorrison This is as far one can get without changing the definitions or proofs. What would be the next step?

**Comment by rwst** [comment]
If you agree to this change, should I create a directory `PadicVal`?

**Comment by rwst** [comment]
!bench

**Comment by grunweg** [comment]
Import reduction PRs are great in principle. Can you merge master, please - then this one can get reviewed?

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
