### PR TITLE
[Merged by Bors] - feat: make `StarOrderedRing` a mixin

### PR DESCRIPTION
**Pull request by j-loreaux**
This makes `StarOrderedRing` take `StarRing` as a parameter instead of extending it, and as a result moves the typeclass to `Prop`. It was already a mixin with respect to the order and algebraic structure. There are two primary motivations:

1. This makes it possible to directly assume that `C(α, R)` is a `StarOrderedRing` with `[StarOrderedRing C(α, R)]`, as currently there is no typeclass on `R` which would naturally guarantee this property. This is relevant as we want this type class on continuous functions for the continuous functional calculus.
2. We will eventually want a `StarOrderedRing` instance on `C(α, A)` where `A` is a complex (or even real) C⋆-algebra, and making this a mixin avoids loops with `StarRing`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
> currently there is no typeclass on `R` which would naturally guarantee this property.

Is there a natural typeclass that _could_ exist here?

**Review by eric-wieser — APPROVED** [review]
I've tweaked your description to be more precise, please check it's still accurate!

1 feels slightly strange to me, but maybe there genuinely is no interesting typeclass on `R`. 2 feels a little inflexible, but no more so than our existing infrastructure for swapping between real and complex.

**Comment by eric-wieser** [comment]
!bench

**Comment by fpvandoorn** [comment]
LGTM

bors merge

**Pull request closed without merging**
