### PR TITLE
[Merged by Bors] - chore: move Init.Order.Defs to Order.Defs

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Thanks for continuing this clean-up. This PR is straightforward code-motion, and this file gets used a lot: let's send this to a maintainer to double-check.
maintainer merge

**Comment by YaelDillies** [comment]
I put a veto on this file. I am currently refactoring it deeply

**Comment by semorrison** [comment]
@YaelDillies, can you make sure that it ends up outside of `Init` when you're done? Do you have a timeframe? If it is more than a week or two we should just do this first.

**Comment by semorrison** [comment]
> Timeframe is "as soon as someone merges #15228"

Ping me when it is green. :-)

**Comment by Ruben-VandeVelde** [comment]
It is trivial to rebase #15228 over this PR; see <https://github.com/leanprover-community/mathlib4/compare/delete_init_order-2>. #15228 also contains a number of other changes that I'm not convinced are good, so I'd like to land this first anyway.

**Comment by YaelDillies** [comment]
It's not really "changes". I'm rewriting the file basically from scratch

**Comment by YaelDillies** [comment]
I maintain that this PR will mess up my diff in #15228 and I would have to revert it to get the correct behavior from github again.

**Review by Vierkantor — APPROVED** [review]
Everything in this file looks worthy of inclusion into Mathlib, and it's enough of a cohesive whole to end up in its own file. So: looks good to me!

bors r+

**Comment by Vierkantor** [comment]
Sorry, missed Yaël's comment. Let me read it and then decide again.

bors r-

**Comment by Ruben-VandeVelde** [comment]
I've already done the work you'd need to do to adapt to this PR, so I don't think that's an argument to block. Also, #15228 still doesn't build, and IMO should not land in this form at all.

**Comment by Vierkantor** [comment]
IMO, Yaël is right that we should start cleaning up and deprecating parts of the order definitions like strict weak orders and some of the derived lemmas that have gone unused. But I am not yet convinced all of their changes in #15228 are positive, and I do believe that merging this PR first will make reviewing #15228 easier. Especially since #15228 is not building yet, I don't see the issue with merging this right now.

I will happily fix the diff in #15228 for you :)

bors d+

**Comment by semorrison** [comment]
bors merge

**Comment by YaelDillies** [comment]
> I will happily fix the diff in #15228 for you :)

I believe it is time 🙏

**Comment by Vierkantor** [comment]
I don't have a computer with Lean with me today, so hopefully this rebase worked: https://github.com/leanprover-community/mathlib4/pull/new/delete_init_order-rebase2

**Pull request closed without merging**
