### PR TITLE
[Merged by Bors] - chore: another test for `linear_combination`

### PR DESCRIPTION
**Pull request by hrmacbeth**
Prior to https://github.com/leanprover/lean4/pull/5167, this test (would have) had a less helpful error message.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
I presume it makes sense to test this over Z, and not just over Q? (Naive question: why so?)
The code changes certainly look straightforward.
maintainer merge

**Comment by hrmacbeth** [comment]
We already have the `ℚ` test (see below).  But the `ℤ` test had a less helpful error message before the core commit https://github.com/leanprover/lean4/pull/5167.

**Comment by grunweg** [comment]
> We already have the `ℚ` test (see below). But the `ℤ` test would have had a less helpful error message before the core commit [leanprover/lean4#5167](https://github.com/leanprover/lean4/pull/5167). This PR guards against regressions in the error message.

Yes, I saw the test over Q. Thanks for explaining, this clear things up.

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
