### PR TITLE
[Merged by Bors] - feat(ImportGraph): add option to exclude tactics

### PR DESCRIPTION
**Pull request by joneugster**
Add an option `lake exe graph --excludeMeta` which removes all nodes that start with `Mathlib.[Tactic|Lean|Util]`

---

Implementation note: in replacement of all deleted nodes it adds a single node `Mathlib.Tactics` which is added as import to any node importing a deleted node. To avoid loops, this new node does not receive any imports from any other Mathlib files:

For example, there are imports `Mathlib.Tactic.X → Mathlib.Init.Logic → Mathlib.Tactic.Y`, so my approach now is to only display `Mathlib.Tactics → Mathlib.Init.Logic`

- [x] depends on: #6151

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
bors d+

(Obviously wait until the earlier PR has been updated and approved! :-)

**Comment by joneugster** [comment]
@semorrison in case you'd like to skim over the modifications I made while resolving merge conflicts:

1. renamed option to `--exclude-meta`
2. renamed new node to `«Mathlib.Tactics»` (with French quotes)
3. added comments to code

**Comment by semorrison** [comment]
I'm slightly concerned that someone somewhere will try to use `«Mathlib.Tactics»` as an import, but I don't see a better solution for now.

**Comment by semorrison** [comment]
bors merge

**Comment by joneugster** [comment]
> I'm slightly concerned that someone somewhere will try to use `«Mathlib.Tactics»` as an import, but I don't see a better solution for now.

That's why I added the French quotes at least. I considered something like `Mathlib.Tactics*` but that's not a valid `Name`.

**Pull request closed without merging**
