### PR TITLE
[Merged by Bors] - feat: port Topology.ContinuousFunction.Ideals

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
There was something wrong with the names
`WeakDual.characterSpace.continuousMapEval`
and 
`WeakDual.characterSpace.continuousMapEval_apply_apply`:

It should have been an upper case "c" in CharacterSpace or one would have to change the name space
In the relevant file, @j-loreaux left the following porting note:
```
-- porting note: even though the capitalization of the namespace differs, it doesn't matter
-- because there is no dot notation since `characterSpace` is only a type via `CoeSort`.
namespace CharacterSpace
``

Does this mean I should use the namespace "CharacterSpace" here as well and change the name of the theorems starting with `WeakDual.characterSpace` or should I keep my change of the namespace name to "characterSpace", see porting note.
Any thoughts, @j-loreaux ?

**Comment by j-loreaux** [comment]
@mo271 I wasn't exactly sure about this either, but my feeling is to keep the namespace uppercase (at the very least to be consistent with the previous file, or else change the namespace in that file too). It's possible we'll refactor `WeakDual.characterSpace` later so that it's actually a subtype, at which point the proper naming will be `WeakDual.CharacterSpace` anyway, making this a moot point.

I have addressed a lot of naming issues in this file (sorry, there were a bunch of tricky ones in there!)

**Comment by mo271** [comment]
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/!4.234852.20heartbeats.20of.20the.20linter

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
