### PR TITLE
[Merged by Bors] - chore: Rename `mul`-`div` cancellation lemmas

### PR DESCRIPTION
**Pull request by YaelDillies**
Lemma names around cancellation of multiplication and division are a mess.

This PR renames a handful of them according to the following table (each big row contains the multiplicative statement, then the three rows contain the `GroupWithZero` lemma name, the `Group` lemma, the `AddGroup` lemma name).

| Statement           | New name                | Old name                |
|---------------------|-------------------------|-------------------------|
| `(a * b) / a = b`     | `mul_div_cancel_left₀`     | `mul_div_cancel_left`   |
|                     | `mul_div_cancel_left`      | `mul_div_cancel'''`     |
|                     | `add_sub_cancel_left`      | `add_sub_cancel'`       |
| `(a * b) / b = a`     | `mul_div_cancel_right₀`      | `mul_div_cancel`        |
|                     | `mul_div_cancel_right`       | `mul_div_cancel''`      |
|                     | `add_sub_cancel_right`       | `add_sub_cancel`        |
| `a / (a * b) = b⁻¹` | `div_mul_cancel_left₀` | `div_mul_right` (roughly) |
|                     | `div_mul_cancel_left`  | `div_mul_cancel''`      |
|                     | `sub_add_cancel_left`  | `sub_add_cancel'`       |
| `b / (a * b) = a⁻¹` | `div_mul_cancel_right₀`  | `div_mul_left` (roughly) |
|                     | `div_mul_cancel_right`   | `div_mul_cancel'''`     |
|                     | `sub_add_cancel_right`   | `sub_add_cancel''`      |
| `a * (b / a) = b`   | `mul_div_cancel₀`       | `mul_div_cancel'`       |
|                     | `mul_div_cancel`        | `mul_div_cancel'_right` |
|                     | `add_sub_cancel`        | `add_sub_cancel'_right` |
| `(a / b) * b = a`   | `div_mul_cancel₀`       | `div_mul_cancel`        |
|                     | `div_mul_cancel`        | `div_mul_cancel'`       |
|                     | `sub_add_cancel`        | `sub_add_cancel`        |

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by fpvandoorn** [comment]
For these kinds of basic lemma renames, it might be good to make a Zulip thread with the suggested renames, and only do it if nobody objects for 1-2 days. 
Some of the old names matched the naming of [`mul_inv_cancel_right`](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Algebra/Group/Defs.html#mul_inv_cancel_right) + siblings (`mul_inv_cancel_left`, `inv_mul_cancel_left`, `inv_mul_cancel_right`).

That said, this is definitely an improvement over all the primed lemmas.

**Comment by YaelDillies** [comment]
[Zulip](https://leanprover.zulipchat.com/#narrow/stream/144837-PR-reviews/topic/.2311530.20Rename.20.60mul.60-.60div.60.20cancellation.20lemmas)

**Comment by fpvandoorn** [comment]
[Second Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/renaming.20basic.20Group.28WithZero.29.20lemmas) for more visibility. I'm happy to merge this in ~24 hours if there is no serious criticism.

**Comment by fpvandoorn** [comment]
I think the rename I suggested is popular. If you change the names to that naming scheme, then I'll merge/delegate this.

**Comment by fpvandoorn** [comment]
LGTM. I didn't have time yesterday to look at this again, so hopefully there are not conflicts.

bors merge (let's try, but I'm not too hopeful)
bors d+

**Comment by YaelDillies** [comment]
bors merge

**Pull request closed without merging**
