### PR TITLE
refactor(LinearAlgebra/SesquilinearForm/Properties): Refactor BilinForm dual and nondegenerate properties

### PR DESCRIPTION
**Pull request by mans0954**
Redefines `dualSubmodule`, `dualSubmoduleToDual`, `toDual`, `dualBasis`, `symmCompOfNondegenerate` and `leftAdjointOfNondegenerate` in terms of `LinearMap.BilinForm` instead of `BilinForm`. Associated results are migrated to `LinearMap.BilinForm` and the `BilinForm` versions recovered.

This is required inorder to define the `TraceForm` in `LinearMap.BilinForm` (#11057).

Contributes to #10553

Required for: #11057

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
Does anything use the old `BilinForm` files in this PR after this change? I'd be tempted to update them in place to be about `LinearMap.BilinForm`, so as to keep the history of the file, like we did with the `TensorProduct` file.

**Comment by mans0954** [comment]
> Does anything use the old `BilinForm` files in this PR after this change? I'd be tempted to update them in place to be about `LinearMap.BilinForm`, so as to keep the history of the file, like we did with the `TensorProduct` file.

@eric-wieser  That could work for `LinearAlgebra/BilinearForm/DualLattice`. I'm less sure what to do about `LinearAlgebra/BilinearForm/Properties` because several of the concepts in that file not touched by this PR (e.g. `IsRefl`, `IsAlt`, `IsSymm`) already have equivalents in `LinearAlgebra/SesquilinearForm`. (Not quite the same as commutativity of the semi-ring is required there.)

**Comment by mans0954** [comment]
> Does anything use the old `BilinForm` files in this PR after this change? I'd be tempted to update them in place to be about `LinearMap.BilinForm`, so as to keep the history of the file, like we did with the `TensorProduct` file.

@eric-wieser is #11278 better?

I asked on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Next.20steps.20for.20BilinForm) but got no response.

**Comment by mans0954** [comment]
I think this PR makes no sense in its current form now that #11278 has been merged, so closing.

**Pull request closed without merging**
