### PR TITLE
[Merged by Bors] -  chore: Move LinearMap.ker to a new file 

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
This shortens `Mathlib.LinearAlgebra.Basic`, which is both longer than we like and doesn't have a clear scope.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by riccardobrasca** [comment]
The motivation is that `[Mathlib/LinearAlgebra/Basic.lean](https://github.com/leanprover-community/mathlib4/pull/10233/files#diff-6f14283bfbc75a32a870660bc104a4b628a3645bacef2d02343637199a25f517)` is huge? It seems like a very good idea to me.

**Review by riccardobrasca — APPROVED** [review]

**Comment by jcommelin** [comment]
What explains the +170 new lines? Not just a copyright header and module docstring, right?

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
