### PR TITLE
feat: port Analysis.SpecialFunctions.Log.Basic

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
Uh-oh, @Parcly-Taxel did this simultaneously: #4019.

**Comment by Parcly-Taxel** [comment]
> Uh-oh, @Parcly-Taxel did this simultaneously: #4019.

And the fix is much cleaner there.

**Comment by urkud** [comment]
@Parcly-Taxel If the porting branch exists, then someone is working on it. Renaming your branch is a way to collisions like this. The status page can lag behind for at least 10 minutes.

**Comment by urkud** [comment]
@semorrison You can merge either of our PRs. If you merge #4019, then please don't close this one and change the labels instead. I'll turn it into a "golf/review API" PR.

**Comment by semorrison** [comment]
bors d+

@urkud, if it's okay with you could you wait to merge until @Parcly-Taxel has had a chance to see if there's something they would like to salvage from their simultaneous port?

**Comment by semorrison** [comment]
bors d-

**Pull request closed without merging**
