### PR TITLE
[Merged by Bors] - refactor(Geometry/Manifold/MFDeriv): split file

### PR DESCRIPTION
**Pull request by grunweg**
With about 2200 lines, this is the largest file in Geometry/Manifolds.

----------
- Can be reviewed commit by commit. (I adjusted imports later, but the substance of each commit stands on its own.)
- This file was very well structured; this made splitting it much easier. Thanks to all the previous authors!
- I'm open to splitting the moving of the main file into a separate commit (to preserve blame information better).
- My apologies for sneaking in one dot notation change; it's hard to rebase it out now :-(

- [x] depends on: #9588

### CODE REVIEW

**Comment by jcommelin** [comment]
>     * I'm open to splitting the moving of the main file into a separate commit (to preserve blame information better).

If you could do this: yes please!

**Comment by grunweg** [comment]
> > ```
> > * I'm open to splitting the moving of the main file into a separate commit (to preserve blame information better).
> > ```
> 
> If you could do this: yes please!

Split into #9588.

**Comment by riccardobrasca** [comment]
bors d+

**Pull request closed without merging**
