### PR TITLE
[Merged by Bors] - chore: remove stream-of-consciousness uses of `have`, `replace` and `suffices`

### PR DESCRIPTION
**Pull request by sgouezel**
No changes to tactic file, it's just boring fixes throughout the library.

This follows on from #6964.

---

The fixes have been found by disabling the tactics, in #10534, but the current PR does not touch the tactic files to make it easier to review and uncontroversial.

After this PR, there are just two remaining uses of the old style `have`, in `test/slim_check`, which I don't know how to convert to the new style without making them noisy (plus the other ones that will have been introduced to master in between!)

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
I have not read the diff, but I am keen in principle to get this merged.

**Comment by sgouezel** [comment]
I have reverted the two noisy tests to the previous versions, which are non-noisy but use the old-fashioned have. I think this shouldn't block this PR, since remaining issues can be discussed in #10534 while here we are just doing a cleanup of the library, which doesn't have to be complete.

**Comment by semorrison** [comment]
bors merge

**Comment by eric-wieser** [comment]
> since remaining issues can be discussed in #10534

While I definitely agree this split was a good idea, I think we might want to merge #10534 sooner rather than later, to avoid regressions appearing.

**Pull request closed without merging**
