### PR TITLE
[Merged by Bors] - feat: make nonZeroDivisors.coe_ne_zero simp

### PR DESCRIPTION
**Pull request by Command-Master**
Make `nonZeroDivisors.ne_zero` `@[simp]`

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Command-Master** [comment]
!bench

**Comment by Command-Master** [comment]
!bench

**Comment by Command-Master** [comment]
!bench

**Comment by erdOne** [comment]
maintainer merge

**Comment by fpvandoorn** [comment]
I want to test if the ~20 seconds extra simp-time is reproducible. This lemma is worth it if it is.

**Comment by fpvandoorn** [comment]
bors merge

**Pull request closed without merging**
