### PR TITLE
[Merged by Bors] - feat: port Counterexamples.DirectSumIsInternal

### PR DESCRIPTION
**Pull request by eric-wieser**
---

- [x] depends on: #5078

This uses the script from

- #4811

[Open in Gitpod](https://gitpod.io/from-referrer/)

We shouldn't merge this until we're convinced that CI is running on it.

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4811
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5078
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5078~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
