### PR TITLE
[Merged by Bors] - chore: remove comments about dubious translations

### PR DESCRIPTION
**Pull request by urkud**
---

This PR used to contain mostly unrelated material, and the first few comments are about the old diff.
- [x] depends on: #14916

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Thanks for your clean-up spree. How does this compare to #14914 and #14916? Is there any change not in those?

**Comment by urkud** [comment]
I missed these two other PRs. Once they're merged, I'll merge `master` and see if anything remains.

**Comment by grunweg** [comment]
`Data/Fin/Basic` also mentions "dubious translation" - do you think that should also be removed?

**Comment by urkud** [comment]
I won't have time for this for the next 3-4 hrs. Feel free to push to this branch.

**Comment by j-loreaux** [comment]
bors merge

**Pull request closed without merging**
