### PR TITLE
[Merged by Bors] - style: some formatting fixes

### PR DESCRIPTION
**Pull request by grunweg**
Found by the pedantic linter.

---

Commits can be reviewed independently.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by j-loreaux** [comment]
bors d+

**Comment by grunweg** [comment]
Thanks! This PR only changes whitespace (and linting passes), so let me go ahead and bors it already.
bors r+

**Comment by grunweg** [comment]
bors merge

**Pull request closed without merging**
