### PR TITLE
[Merged by Bors] - chore (Topology.Algebra.Algebra): name `DiscreteTopology.instContinuousSMul` and de-instance

### PR DESCRIPTION
**Pull request by mattrobball**
This instance is reasonable mathematically but creates complexity in the typeclass search. It is currently not used so we de-instance it. 

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
!bench

**Comment by urkud** [comment]
`DiscreteTopology` is not one of commonly used scopes, so I suggest that we just turn it into a `lemma`.

**Comment by j-loreaux** [comment]
bors d+

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
