### PR TITLE
[Merged by Bors] - feat: Lebesgue average

### PR DESCRIPTION
**Pull request by YaelDillies**
Match https://github.com/leanprover-community/mathlib/pull/19199

---

- [x] depends on: #5326

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5326
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by Ruben-VandeVelde** [comment]
Should this include changes to Mathlib.MeasureTheory.Integral.Lebesgue?

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5326~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
@YaelDillies, could you please merge master on this?

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
