### PR TITLE
[Merged by Bors] - chore: Delete declarations deprecated in 2023

### PR DESCRIPTION
**Pull request by YaelDillies**
Some of these are on my way.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by vihdzp** [comment]
There's nothing from 2022 here? In fact, it seems like there's nothing from before December 2023!

**Comment by YaelDillies** [comment]
They were dropped from the diff. See #17207.

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by eric-wieser** [comment]
Unfortunately this deletion doesn't show up in the mathlib changelog; I had to find it through github

**Comment by YaelDillies** [comment]
Is it because the changelog doesn't pick up on `alias`?

**Comment by eric-wieser** [comment]
Yes, I think that's the reason.

**Pull request closed without merging**
