### PR TITLE
[Merged by Bors] - chore(RingTheory/LocalRing): remove diamond

### PR DESCRIPTION
**Pull request by erdOne**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Can you add a test for this?

**Comment by erdOne** [comment]
I'm not sure what you meant by tests. Do you mean a test that the instance still exists?

**Comment by Ruben-VandeVelde** [comment]
See `MathlibTest/instance_diamonds`

**Comment by erdOne** [comment]
There were two instances of the same signature but with different implementations so I removed one.
I don't think the tests in that file applies here.

**Comment by kim-em** [comment]
bors merge

**Pull request closed without merging**
