### PR TITLE
[Merged by Bors] - feat: port Geometry.Manifold.ContMdiff

### PR DESCRIPTION
**Pull request by urkud**
---
I'm working on this PR.

- [x] depends on: #4636 
- [x] depends on: #5428

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by hrmacbeth** [comment]
Hi Yury, I guess you didn't see the note at
https://leanprover-community.github.io/mathlib-port-status/file/geometry/manifold/cont_mdiff
asking for this to wait on https://github.com/leanprover-community/mathlib/pull/19094.

I'm willing to withdraw the wait request and try to forward-port everything, but it will be a hassle -- can we discuss it?

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4636
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by urkud** [comment]
@hrmacbeth Probably, the "port status" update was not updated between the time you added the comment and the time I started the port. I'm going to postpone this PR and restart once mathlib3 PR is merged & `mathport` has a new version.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4636~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by hrmacbeth** [comment]
The PR the wait was requested on is now ready for review, and I split out the part that actually touches early-manifold files: https://github.com/leanprover-community/mathlib/pull/19209

**Comment by hrmacbeth** [comment]
@urkud Thanks for getting the new port started.  In case you didn't notice, a few lemmas in this file will depend on the forward-port #5371, which should be merged into master in the next few minutes.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4636~~
* ~~leanprover-community/mathlib4#5428~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
