### PR TITLE
[Merged by Bors] - feat: deprecate `div_le_div_of_le_of_nonneg`

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
This was noticed in the discussion around #9393.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
bors d=yaeldillies

**Comment by YaelDillies** [comment]
Actually, @newell has a refactor touching these files. Are you happy with this PR going through, Newell?

**Comment by newell** [comment]
Sorry about closing the PR and reopening it, my mouse had other ideas!

**Comment by YaelDillies** [comment]
Okay, let's merge this for now.

maintainer merge

**Comment by YaelDillies** [comment]
Sorry, meant

bors merge

**Pull request closed without merging**
