### PR TITLE
[Merged by Bors] - refactor(PartialHomeomorph): make (s : Opens \alpha) implicit

### PR DESCRIPTION
**Pull request by grunweg**
It is always used in conjunction with a hypothesis `hs` about `s`.

In Lean 3, these arguments were kept explicit on purpose: given a definition `myDef {x : α} (hx : MyProp x)`,
if the proof of `hx` was nontrivial (not a variable), Lean would pretty-print it as `myDef _`.

In Lean 4, setting `pp.proofs.withType` or `pp.proofs` to true makes such terms pretty-print as `myDef (x : MyProp)`.
Hence, this workaround is no longer necessary.

Follow-up to #9894.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
@winstonyin I'd be interested in your opinion on this, as you wrote #9894.

**Comment by urkud** [comment]
The reason why we kept these arguments explicit in Lean 3 was the following: if you have `myDef {x : α} (hx : MyProp x)` and the proof of `hx` is nontrivial (not just a variable), then Lean pretty prints it as `myDef _`. I don't know if this was fixed in Lean 4 (e.g., by printing the type of `hx` in this case). If not, then we should keep these explicit arguments for a while.

**Comment by grunweg** [comment]
Good point; I did not know that. I asked [on zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Pretty-printing.20of.20proof.20arguments).

**Comment by grunweg** [comment]
My understanding of the zulip discussion is that keeping the arguments explicit is no longer necessary. I'll update the commit message in a moment to mention this.

**Comment by sgouezel** [comment]
bors r+
Thanks!

**Pull request closed without merging**
