### PR TITLE
[Merged by Bors] - refactor : add namespace `UpperHalfPlane.ModularGroup`

### PR DESCRIPTION
**Pull request by shuxuezhuyi**
Rename some definitions and theorems about $SL(2, ℤ)$ in `Analysis/Complex/UpperHalfPlane/Basic.lean` to place them in the namespace `UpperHalfPlane.ModularGroup`, in order to avoid the confusion with definitions and theorems about $SL(2, ℝ)$. For example, `UpperHalfPlane.det_coe'` is renamed to `UpperHalfPlane.ModularGroup.det_coe'`, because we will have `UpperHalfPlane.SL2R.det_coe'`.

[Discussion on Zulip](https://leanprover.zulipchat.com/#narrow/stream/144837-PR-reviews/topic/.237885.20add.20namespace.20.60UpperHalfPlane.2EModularGroup.60)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
Can you explain the motivation in the PR title? Was this discussed on Zulip?

**Comment by shuxuezhuyi** [comment]
Discussion on Zulip: https://leanprover.zulipchat.com/#narrow/stream/144837-PR-reviews/topic/.237885.20add.20namespace.20.60UpperHalfPlane.2EModularGroup.60

**Review by AlexKontorovich — APPROVED** [review]
It looks ok to me, but others have expressed skepticism about whether this change is needed (as in the linked zulip thread).

**Comment by CBirkbeck** [comment]
Yeah I don't see this causing any problems, but I also don't understand why we need it.

**Comment by jcommelin** [comment]
Thanks :tada: 

If CI passes, please remove the label `awaiting-CI` and merge this yourself, by adding a comment `bors r+`.

bors d+

**Pull request closed without merging**
