### PR TITLE
[Merged by Bors] - chore: use #adaptation_note for the remaining cases

### PR DESCRIPTION
**Pull request by grunweg**
-------

This regressed somewhen... so merging a linter (like #13660, but other options are possible) for this could be useful.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by grunweg** [comment]
@jcommelin I've merged master, fixing the conflicts. Can you re-approve, please?

**Comment by urkud** [comment]
bors d+

**Comment by urkud** [comment]
bors merge

**Comment by grunweg** [comment]
Since CI passes last time, except for `shake` (which I just handled), let me
bors r+

**Comment by grunweg** [comment]
Thanks for the fast review!

**Comment by grunweg** [comment]
Once more
bors r+

**Pull request closed without merging**
