### PR TITLE
[Merged by Bors] - fix: make `change` tactic use `show` term directly

### PR DESCRIPTION
**Pull request by kmill**
`change` was using the `show` tactic when operating on the main goal, but it was relying on the programmed behavior of `show` rather than the behavior implied by its docstring, which claims it can be used to *select* a goal. This modifies `change` to apply the exact behavior needed to protect against any future changes to the `show` tactic.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by kmill** [comment]
@digama0 I think having this `case : patt => tac` tactic would be useful, but I'm not so sure about overriding `show`, even if it makes it do what it claims to do. Rather than `show`, it seems like it would be better to have the complimentary `case' : patt => tac` that doesn't require that the goal be solved since that would be more structured. Do you have any thoughts? Should this be a std4 PR?

**Comment by digama0** [comment]
I think that's a good plan. For sure, the goal switching behavior of `show` was used approximately never, and I would not mind having a different name for that tactic.

One other thing to consider for these case tactics is to support `_` / `?_` in place of the tactic block, to turn them into a goal selecting tactic instead of a scoping tactic. Compare with `cases with` / `induction with` / `match with` which all support using `?_` instead of a tactic block and take this as a suggestion to post the goals after the tactic instead of in the block.

**Comment by kmill** [comment]
@digama0 There's now an expanded version of the `cases` tactic at https://github.com/leanprover/std4/pull/160

I'm not sure I follow what you're saying about `_`/`?_` in place of a tactic block. I added a no-tactic-block version for bringing goals up to being the first goal(s), but if this isn't doing what you're suggesting then let's move this discussion over to that PR.

**Comment by semorrison** [comment]
Shall we close this in favour of https://github.com/leanprover/std4/pull/160?

**Comment by kmill** [comment]
@semorrison There was still one line in this PR I wanted to keep, so I've cut everything else out.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
