### PR TITLE
[Merged by Bors] - feat: port NumberTheory.Padics.RingHoms

### PR DESCRIPTION
**Pull request by xroblot**
A coercion in a previous file (done by me) was wrong so I fix it in this PR

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ChrisHughes24** [comment]
Is this awaiting review?

**Comment by xroblot** [comment]
Yes, I was waiting for CI to complete.

**Comment by ChrisHughes24** [comment]
If you're waiting for CI, you can add the awaiting-CI label which is automatically removed after CI passes.

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
