### PR TITLE
[Merged by Bors] - doc(*.yml): mention Sylow theorems

### PR DESCRIPTION
**Pull request by grunweg**
- mention them in the overview
- they have been upstreamed already: make 100.yaml point to the in-mathlib links
- add the same links to 1000.yaml

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by fpvandoorn** [comment]
Are the Sylow theorems already mentioned in `undergrad.yaml`?

LGTM

bors d+

**Comment by fpvandoorn** [comment]
except that these declarations don't exist?

**Comment by grunweg** [comment]
I had copy-pasted the module doc-string (and relied on CI to check existence): turns out the module doc-string was wrong. Fixed both (hopefully).

**Comment by grunweg** [comment]
Thanks for the quick review. CI passes, so
bors merge

**Comment by fpvandoorn** [comment]
bors r-

Sorry to unmerge, but if we're mentioning a result in 4-ish locations, maybe we should give it a name instead of using the auto-generated name?

**Comment by grunweg** [comment]
Fair point. How about `Sylow.isPretransitive_of_finite`?

**Comment by fpvandoorn** [comment]
Thanks!

bors merge

**Pull request closed without merging**
