### PR TITLE
[Merged by Bors] - chore: add more pp_dot attributes

### PR DESCRIPTION
**Pull request by kim-em**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
bors d+

Thanks!

**Comment by semorrison** [comment]
Strange, I have pushed a commit but it is not showing up here, or triggering a new CI run. :-(

**Comment by semorrison** [comment]
Just github being slow!

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
