### PR TITLE
[Merged by Bors] - chore: cleanup `AlgebraicGeometry.Pullbacks`

### PR DESCRIPTION
**Pull request by fpvandoorn**
* I noticed this file was a little slow and I decided to clean it up a bit.
* I don't actually know if this improves the compilation time of this file, but it cleans up all porting notes, adaption notes, `erw` and `change`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by fpvandoorn** [comment]
!bench

**Comment by mattrobball** [comment]
Great!

bors delegate+

**Comment by fpvandoorn** [comment]
!bench

**Comment by fpvandoorn** [comment]
bors merge

**Pull request closed without merging**
