### PR TITLE
[Merged by Bors] - chore(Topology/Basic): re-use variables; rename a : X to x : X

### PR DESCRIPTION
**Pull request by grunweg**
---

Best reviewed commit by commit.
I'm stuck at fixing the build error in PrimeSpectrum/Basic; help by an algebraic geometry person welcome.

@urkud Since you renamed the types in this file recently, would you like to take a look?

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
Please make CI happy first.

**Comment by grunweg** [comment]
CI is happy, except for one error in PrimeSpectrum/Basic (which I've asked about on zulip), and any later errors. (There are 50 further files, my local build has finished the first 25 without errors.)

**Comment by urkud** [comment]
I merged `master` to see if there are any conflicts with #9963

**Comment by urkud** [comment]
I think that `continuous_def` intentionally used `{}` for `TopologicalSpace` arguments so that it works well with `simp` when topologies are not those provided by instances.

**Comment by urkud** [comment]
Thanks! Once CI is happy, please merge this PR using `bors r+`
bors d+

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Comment by dwrensha** [comment]
> I think that `continuous_def` intentionally used `{}` for `TopologicalSpace` arguments so that it works well with `simp` when topologies are not those provided by instances.

The `{}` brackets worked better for some of my code, at least. See my comment: https://github.com/leanprover-community/mathlib4/commit/20c7b4b802f5ad61a2c1621e707b906cfe79366c#r137856007

**Comment by grunweg** [comment]
@dwrensha Thanks; I was not aware of this. I have submitted #10110 reverting that particular change.

**Pull request closed without merging**
