### PR TITLE
chore: move Real.iUnion_Iic_rat/iInter_Iic_rat

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
- [x] depends on: #10635

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — APPROVED** [review]
I trust you checked this (as opposed to even lower in the hierarchy) is a good location. LGTM.

**Comment by RemyDegenne** [comment]
Please coordinate with @mo271 : the PRs #10635 and #10298 are about the same lemmas.

**Comment by Ruben-VandeVelde** [comment]
@mo271 I'm happy to do whatever here, was just fixing the todo.

**Comment by mo271** [comment]
> @mo271 I'm happy to do whatever here, was just fixing the todo.

Me too @Ruben-VandeVelde, also just trying to fix the todo, it just got stuck in review. Perhaps @urkud can un-stuck this?
Otherwise perhaps just merge this here and I'll close my two pending prs...

**Comment by mo271** [comment]
@RemyDegenne 
A reasonable way to proceed here seems to me to first get #10635 merged and then use this pr here to fix the todo in  [CdfToKernel.lean](https://github.com/leanprover-community/mathlib4/pull/11638/files#diff-99a01092985b102c4609f0834336b17398571cc0c7d7c1375c443ac5375ae8bd). Should work with a fairly clean merge, which I'm happy to do...

**Comment by RemyDegenne** [comment]
The remaining small change is now included in PR #11529, which will be merged shortly. I am closing this PR. Thank you both!

**Pull request closed without merging**
