### PR TITLE
[Merged by Bors] - chore: turn `induction'` into `induction`

### PR DESCRIPTION
**Pull request by pitmonticone**
This PR turns `induction'` (soon to be deprecated) into `induction`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by YaelDillies** [comment]
I don't think we want to deprecate `induction'`?

**Comment by pitmonticone** [comment]
I've been told so by a few maintainers. Isn't it the case?

**Review by Parcly-Taxel — APPROVED** [review]

**Comment by YaelDillies** [comment]
Can you please start a Zulip discussion?

**Comment by pitmonticone** [comment]
Sure, I'll do it later today when I come back home.

**Comment by pitmonticone** [comment]
@YaelDillies Done https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Deprecation.20and.20Replacement.20of.20.60induction'.60.3F/near/465553445

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
