### PR TITLE
[Merged by Bors] - feat: port `zify`

### PR DESCRIPTION
**Pull request by mcdoll**
Initial port of `zify`. The tests are not really good, this is due to the fact that the relevant `norm_cast` lemmas do not exist yet.

### CODE REVIEW

**Comment by semorrison** [comment]
I added the attributes needed to make the tests all work, but only in the test file. We should move these to appropriate homes.

**Comment by semorrison** [comment]
Please in future make PRs (possibly even remaking this one) from a branch of this repo, so that CI can run.

**Comment by semorrison** [comment]
Okay, so we need to `import Mathlib.Init.Data.Int.Basic`, in order to get the `Preorder ℤ` instance. However as soon as the `CommRing ℤ` instance, which is currently defined in `Mathlib.Algebra.Ring.Basic`, the tests start failing again. 

In
```
example (a b c x y z : ℕ) (h : ¬ x*y*z < 0) (h2 : (c : ℤ) < a + 3 * b) : a + 3*b > c := by
  zify at h ⊢
  push_cast at h
  guard_hyp h : ¬↑x * ↑y * ↑z < (0 : ℤ)
  guard_target =ₐ ↑c < (↑a : ℤ) + 3 * ↑b
  exact h2
```
which right now succeeds in this branch, after add the import (and hence the `CommRing ℤ` instance), we get
```
hypothesis h has type ¬↑x * ↑y * ↑z < 0, not ¬↑x * ↑y * ↑z < 0
```
On the LHS `↑x` is `Int.ofNat x : ℤ`, while on the RHS `↑x` is `@Nat.cast ℤ NonUnitalNonAssocSemiring.toAddMonoidWithOne x : ℤ`.

**Comment by digama0** [comment]
bors merge

**Comment by digama0** [comment]
bors merge

**Comment by digama0** [comment]
bors merge

**Pull request closed without merging**
