### PR TITLE
feat: Implement unexpanders for `∀ᶠ x in f, p x`

### PR DESCRIPTION
**Pull request by Komyyy**
This PR:
~~1. implements notations of `∀ᶠ x in f, p x`, `∃ᶠ x in f, p x`, `∀ᵐ x ∂μ, p x`, and `∃ᵐ x ∂μ, p x` without `notation3`. This makes `∀ᶠ _ in f, p x` valid.~~
2. implements unexpanders of `∀ᶠ x in f, p x` `∃ᶠ x in f, p x`, `∀ᵐ x ∂μ, p x`, and `∃ᵐ x ∂μ, p x`.
3. refactors `notation`s so that `f =ᵐ[μ] g` and `f ≤ᵐ[μ] g` can be pritty-printed.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by digama0** [comment]
> implements notations of `∀ᶠ x in f, p x`, `∃ᶠ x in f, p x`, `∀ᵐ x ∂μ, p x`, and `∃ᵐ x ∂μ, p x` without `notation3`. This makes `∀ᶠ _ in f, p x` valid.

I would prefer that such issues are fixed in `notation3` rather than hacking around it (at the cost of a lot more code).

**Comment by Komyyy** [comment]
I agree with that the problem of binders should be fixed in `notation3`, but according to the document of `notation3`, it seems reasonable to replace `notation3` with other commands.
```lean
/--
`notation3` declares notation using Lean 3-style syntax. This command can be used in mathlib4
but it has an uncertain future and exists primarily for backward compatibility.
-/
```

**Comment by digama0** [comment]
It is, but at the same time mathlib declares a lot of binders and we definitely want a one-line way to do that. Replacing it with half a page or more of code per-binder is a regression.

**Comment by Komyyy** [comment]
This PR is incorporated to #4533.

**Comment by Komyyy** [comment]
Oops, 3. is not in #4533.
I've opened #4536.

**Pull request closed without merging**
