### PR TITLE
[Merged by Bors] - feat: base change of Clifford algebras

### PR DESCRIPTION
**Pull request by eric-wieser**
The main result here is `CliffordAlgebra (Q.baseChange A) ≃ₐ[A] A ⊗[R] CliffordAlgebra Q`; that is, the `A ⊗[R]` can be moved from `_ : QuadraticForm A (A ⊗[R] _)` to the outside and vice versa.

---

- [x] depends on: #6636
- [x] depends on: #6074
- [x] depends on: #6781
- [x] depends on: #6783
- [x] depends on: #6781
- [x] depends on: #6555
- [x] depends on: #6786
- [x] depends on: #7196

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ocfnash** [comment]
Thanks!

bors merge

**Comment by eric-wieser** [comment]
Whoops, I forgot to record the dependcy on #7196

**Comment by ocfnash** [comment]
Thanks!

This will be ready once #7196 lands.

bors d+

**Comment by eric-wieser** [comment]
I plan to give this a final cleanup pass before merging, as I think the new lemmas in the dependency might help.

**Comment by eric-wieser** [comment]
bors merge

Looks like I already did the cleanup using the new lemmas, but I was able to remove all the `noncomputable`s and the heartbeat bump.

**Pull request closed without merging**
