### PR TITLE
[Merged by Bors] - feat: port Geometry.Euclidean.MongePoint

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by int-y1** [comment]
@Ruben-VandeVelde is this ready?

**Review by jcommelin — APPROVED** [review]
It seems like `decide!` got a bit less smart. We should look into this at some point.
But for now, I don't see a reason not to merge this.

bors d+

**Comment by Ruben-VandeVelde** [comment]
Conflicted with https://github.com/leanprover-community/mathlib4/pull/5450

**Pull request closed without merging**
