### PR TITLE
[Merged by Bors] - doc: add a warning that `comap` is zero for non-injective functions

### PR DESCRIPTION
**Pull request by bjoernkjoshanssen**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Thanks for your PR! This does look useful to me; let's have a measure theory maintainer look at this.
maintainer merge

**Comment by urkud** [comment]
Please add a similar warning to the `comap` definition below. The `comapₗ` is an auxiliary definition.

**Comment by bjoernkjoshanssen** [comment]
Thanks @urkud I have added that as well now. Not sure if it should be a new PR or it is still this one.

**Comment by urkud** [comment]
Thanks! 
bors merge

**Pull request closed without merging**
