### PR TITLE
feat: units of Z/nZ are a fintype

### PR DESCRIPTION
**Pull request by kbuzzard**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

This adds the instance that (Z/nZ)^* is finite for all n; the trick is that for n=0 Z/nZ is infinite but the units are finite anyway. However constructivist nonsense means that another proof in mathlib breaks:
```lean
theorem card_units (p : ℕ) [Fact p.Prime] : Fintype.card (ZMod p)ˣ = p - 1 := by
  rw [Fintype.card_units, card]
```
now no longer works. I fix this by reducing to 900 the priority of the instance I'm proposing to add.

### CODE REVIEW

**Comment by eric-wieser** [comment]
There is a [Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/fintype.20.28units.20.28zmod.20n.29.29/near/252776463) about this.

**Comment by kbuzzard** [comment]
I am a whole lot less sure about this PR now I see that it causes a diamond.

**Comment by eric-wieser** [comment]
If this is actually being needed by real mathematics, I think it's ok to merge despite the diamond; though we should add a comment on the instance explaining the problem to users (the `example` is for the benefit of mathlib contributors).

Defeq diamond are bad but sometimes unavoidable. It's literally unequal diamonds that are disastrous, and this one is thankfully not one.

**Comment by kbuzzard** [comment]
The reason I'm now hesitant is that there are other ways to do what the student wants to do -- for example they could simply add `[NeZero n]` to their list of assumptions; their n is never zero in practice, I was just trying to be clever: they needed finiteness of the unit group and I said "aha, here we don't need to assume n isn't zero". I am not sure that that's a good justification for wilfully adding a diamond to mathlib, not least because they do need to assume n isn't zero in many many other places in the development.

**Pull request closed without merging**
