### PR TITLE
[Merged by Bors] - fix: don't memory map the exact?/rw? cache when not needed

### PR DESCRIPTION
**Pull request by kim-em**
This depends on https://github.com/leanprover/std4/pull/408

A terrible horrible no good mistake meant that we have been memory mapping the `exact?` and `rw?` caches in every single file that imports them, even when the tactics are not used in the file. This costs on the order of 0.25s per file, over approximately 3000 files... 

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
!bench

**Comment by semorrison** [comment]
I am startled that this makes so little difference. There is a 1.5% wallclock improvement.

Possibly my 250ms estimate per file was way off. Joe Hendrix told me that loading the cache from a file (on his laptop) was taking about 125ms, so I doubled that for the `rw?` cache...

**Comment by semorrison** [comment]
(I did do some print statement debugging here, putting an `IO.println "."` just before the `unpickle` commands. They were firing on every file, and now they don't.)

**Review by jcommelin — APPROVED** [review]
Thanks :tada: 

If CI passes, please remove the label `awaiting-CI` and merge this yourself, by adding a comment `bors r+`.

bors d+

**Comment by semorrison** [comment]
bors p=10

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
