### PR TITLE
[Merged by Bors] - chore: split Topology.UniformSpace.Basic

### PR DESCRIPTION
**Pull request by kim-em**
and reorganize material in UniformSpace.Compact (moving some material from Basic into it, and splitting parts of the original content out into later files)

### CODE REVIEW

**Comment by kim-em** [comment]
> I see that 2 files got heavy imports. Is it intentional?

Those are newly created files, so it is counting relative to a baseline of 0!

@adomani, could we perhaps make this clearer in the imports report?

**Comment by adomani** [comment]
I can think of two possibilities right now:
1. add `(new file)` next to each new file;
2. add a column that contains the head count also in the extended report, so there would be `0` for new files.

I imagine that either option is easy to implement, and both could be implemente ld as well.

What do you think?

**Comment by kim-em** [comment]
I think `(new file)` is great.

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Pull request closed without merging**
