### PR TITLE
feat: Port Algebra.Order.ZeroLEOne

### PR DESCRIPTION
**Pull request by mcdoll**
mathlib3 SHA: 39af7d3bf61a98e928812dbc3e16f4ea8b795ca3

---

I think I want to add a `ofNat` instance here, but I am afraid that then I have two `1 : α` that are not defeq. (`One.one` and `Nat.unaryCast 1` - they are equal by `zero_add`, but not defeq)

### CODE REVIEW

**Comment by semorrison** [comment]
I don't understand why you say you want to add an OfNat instance here?

**Comment by semorrison** [comment]
My preference would be to redo this PR after https://github.com/leanprover-community/mathlib/pull/17646 has landed.

**Comment by semorrison** [comment]
Note duplicated work in #654.

**Comment by mcdoll** [comment]
I want to have an `ofNat` instance because it feels weird to write `(2 : ℕ).unaryCast` all the time, in the original version it was just `2` and the `ofNat` instance took care of the coercion.

**Comment by semorrison** [comment]
I'll close this one for now, as it needs to be redone now https://github.com/leanprover-community/mathlib/pull/17646 has landed.

**Pull request closed without merging**
