### PR TITLE
feat(SetTheory/Game/PGame): compliment of Relabelling.negCongr

### PR DESCRIPTION
**Pull request by tristan-f-r**
Intermediate theorem I needed while writing the theory of dominated games.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by vihdzp — APPROVED** [review]
I think this is fine for now? But I believe there's plans (by @FR-vdash-bot?) to deprecate `Relabelling` in the near future now that `Identical` exists, so keep that in mind.

**Comment by LeoDog896** [comment]
> I think this is fine for now? But I believe there's plans (by @FR-vdash-bot?) to deprecate `Relabelling` in the near future now that `Identical` exists, so keep that in mind.

Interesting! I was just thinking about that right now. I assumed (by motivation of why relabelling would exist) that relabelling was a stronger relation than identical, but presumably it's not?

**Comment by vihdzp** [comment]
It is a stronger relation, and that's the issue. Mathematically, the games {0, 0 | } and {0 | } are entirely the same, because their left and right sets are the same. But in the way we set `PGame` up, these two are non-equal, and in fact, they're not even relabellings of each other, even though they are identical.

The distinction between these two games is an artifact of our type theoretic foundations, and isn't really mathematical, which is why we (at the very least I) want to get rid of the relabelling notion which does take it into account.

**Comment by LeoDog896** [comment]
> It is a stronger relation, and that's the issue. Mathematically, the games {0, 0 | } and {0 | } are entirely the same, because their left and right sets are the same. But in the way we set `PGame` up, these two are non-equal, and in fact, they're not even relabellings of each other, even though they are identical.
> 
> The distinction between these two games is an artifact of our type theoretic foundations, and isn't really mathematical, which is why we (at the very least I) want to get rid of the relabelling notion which does take it into account.

I see - that makes sense! The PR's motivation was to use a stronger relation for the theory of dominated games that I was writing. However, it makes sense that the notion of relabelling is quite useless in combinatorial game theory.

Feel free to close this if it gets in the way of that goal. +1:

**Comment by LeoDog896** [comment]
(I will close this now as I am in complete agreement with this stance, and no longer need this.)

**Pull request closed without merging**
