### PR TITLE
[Merged by Bors] - chore: cleanup skipAssignedInstances flags

### PR DESCRIPTION
**Pull request by kim-em**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
!bench

**Comment by kim-em** [comment]
I think those benchmark numbers are small enough that we shouldn't mind.

**Comment by adomani** [comment]
The second bot could in fact not post anything when the first one claims that there are no significant changes.  I had thought if implementing it like that in the initial PR, but opted against it.  However, if it is going to be overruled since the speed-center says that the changes are not significant (which is a very reasonable stand), it may shut up entirely.

**Review by Vierkantor — APPROVED** [review]
I agree that the code cleanup here is enough of a benefit compared to a ~1s slowdown in a few files. Thanks!

bors d+

**Comment by grunweg** [comment]
> The second bot could in fact not post anything when the first one claims that there are no significant changes. I had thought of implementing it like that in the initial PR, but opted against it. However, if it is going to be overruled since the speed-center says that the changes are not significant (which is a very reasonable stand), it may shut up entirely.

I *do* think that seeing these slow-downs is valuable. One can still ignore them, but on multiple occasions I was glad to know they existed. (Otherwise, I'll have to open the detailed report and sort by the absolute difference - which is definitely possible, but slower.)

**Comment by kim-em** [comment]
bors merge

**Comment by kim-em** [comment]
bors merge

**Pull request closed without merging**
