### PR TITLE
[Merged by Bors] - feat: port Order.Category.PartOrd

### PR DESCRIPTION
**Pull request by joelriou**
---

- [x] depends on: #3265

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3265
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3265~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ChrisHughes24** [comment]
@joelriou It makes it a lot easier to review if whenever you change the name of a file, you do so in a commit that makes no other changes, and preferably the first commit. It's difficult to see the diff with the mathport output otherwise.

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
