### PR TITLE
[Merged by Bors] - feat: port Logic.Function.Basic

### PR DESCRIPTION
**Pull request by kim-em**

### CODE REVIEW

**Comment by semorrison** [comment]
So far I've done the merge with the existing file, using previously ported proofs where the mathport proof is broken.

But I haven't attempted to
* fix the remaining broken proofs
* rename statements as appropriate (with #aligns)
* edit for style

**Comment by semorrison** [comment]
The problem with congr has been fixed in Lean 4, but we can't move to nightly-2022-10-29 because of https://github.com/leanprover/lean4/issues/1791.

**Comment by gebner** [comment]
Depends on #522

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
