### PR TITLE
[Merged by Bors] - chore: minor import adjustment

### PR DESCRIPTION
**Pull request by kim-em**
Easy cleanup after recent Std bumps.

---

- [x] depends on: #7126

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
bors d+

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
