### PR TITLE
[Merged by Bors] - fix: ensure that the linter fails when it should

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
I am not sure that I understand python, but this seems like it will complain only about the first failure and miss out on informing about all subsequent ones, right?  Could there be something that accumulates all possible failures, reporting on them, and then acting on the ones that do require action?

**Review by jcommelin — APPROVED** [review]
Thanks :tada: 

If CI passes, please remove the label `awaiting-CI` and merge this yourself, by adding a comment `bors r+`.

bors d+

**Comment by ericrbg** [comment]
Ruben, I agree with Damiano - this means that we drop all subsequent style errors. Why did you change these `if`s to `elif`s?

**Comment by ericrbg** [comment]
Oh, we're checking one error at a time, I see, I retratct the statement above

**Comment by Ruben-VandeVelde** [comment]
There is certainly room to clarify the code flow here; I plan to look at that at some point

**Pull request closed without merging**
