### PR TITLE
[Merged by Bors] - chore(Analysis/Normed/Group): Move boundedness lemmas

### PR DESCRIPTION
**Pull request by YaelDillies**
Split a new file `Analysis.Normed.Group.Bounded` off `Analysis.Normed.Group.Basic`. Basically no imports get shaved off in this PR, but it's preparing the way to #13713.

---

This can't be merged simultaneously as #13894.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer delegate

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Comment by riccardobrasca** [comment]
bors d+

(delegating because I am not sure this is ready to go since #13894 is merged)

**Comment by YaelDillies** [comment]
Oh, I've already fixed the conflicts.

bors merge

**Pull request closed without merging**
