### PR TITLE
[Merged by Bors] - ci: properly check cache

### PR DESCRIPTION
**Pull request by ericrbg**
Currently, the cache is locally existing in the runner, so the step that checks the cache trivially succeeds. This should stop any future silent cache failures.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
I don't understand what's going on here. The commands you've added only run when we are on a `lean-pr-testing-NNNN` branch? Could you explain in more detail what problem this PR is solving?

**Comment by ericrbg** [comment]
The `if` condition is negated; this runs only on branches that aren't the testing ones.

At the current moment, the check cache step (e.g., see [last master](https://github.com/leanprover-community/mathlib4/actions/runs/7777387707/job/21205627840)) doesn't re-download the cache and instead uses the one it just computed in order to upload it; we make sure we do so to actually check that the cache did upload properly and will work for end users. I think we need to do it this way as opposed to just changing the line below to `lake exe cache get!` because I don't think `get!` deletes files, so if some `ltar`s fail to upload this step wouldn't detect that.

**Comment by semorrison** [comment]
Ah, thanks. Why if the `rm` line there?

**Comment by ericrbg** [comment]
Because if get fails, we still have the oleans that were generated during building, I think. I think we have to clear both the ltars in the cache directory, and the oleans that were built earlier.

**Review by Ruben-VandeVelde — COMMENTED** [review]
I'm not fully confident here, but the change seems logical, and apparently works, while the current setup is certainly broken, so I'd be inclined to merge. It would be easy enough to revert if it does cause unexpected trouble.

maintainer merge

**Review by jcommelin — APPROVED** [review]
Let's try this

bors merge

**Pull request closed without merging**
