### PR TITLE
[Merged by Bors] - feat: Generalizing some results from CommRing to CommSemiring 

### PR DESCRIPTION
**Pull request by XavierXarles**
Most of the changes are minor.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
Is this still a draft?

**Comment by XavierXarles** [comment]
> Is this still a draft?

No, it's not, sorry.

**Comment by erdOne** [comment]
!bench

**Comment by erdOne** [comment]
That's surprising! I guess that's a good sign
maintainer merge

**Comment by mattrobball** [comment]
+3% wall clock isn’t great. Might be an artifact.

**Comment by mattrobball** [comment]
!bench

**Comment by XavierXarles** [comment]
> That's surprising! I guess that's a good sign maintainer merge

How one does this checking?

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by eric-wieser** [comment]
bors merge


(The diff was showing changes from #9125 too)

**Pull request closed without merging**
