### PR TITLE
[Merged by Bors] - feat(Convex/Gauge): add `continuousAt_gauge`

### PR DESCRIPTION
**Pull request by urkud**
---
Cleaning up old branches

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by dupuisf — COMMENTED** [review]
Thanks!

bors r+

**Comment by dupuisf** [comment]
I just realized a few seconds after pushing the button that we should put `@[continuity]` on that lemma.

bors d+

**Comment by urkud** [comment]
> I just realized a few seconds after pushing the button that we should put `@[continuity]` on that lemma.
> 
> bors d+

Can `continuity` prove the side goal? By `assumption` or in some other way?

**Comment by dupuisf** [comment]
Oh -- I meant `continuous_gauge`, not the new lemma.

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
