### PR TITLE
[Merged by Bors] - chore: unify binary inf and min

### PR DESCRIPTION
**Pull request by sven-manthe**
Unify binary inf and min, as discussed in https://leanprover.zulipchat.com/#narrow/channel/287929-mathlib4/topic/.60sup.60.2F.60inf.60.20or.20.60max.60.2F.60min.60.20for.20set.20interval.20lemmas.3F.

---
Regressions: The instance for the product of metric spaces and some dependent instances are noncomputable now. I had the impression that noncomputability for reals is usual and unproblematic throughout mathlib, but could have a look at it otherwise.
Things that still need to be done: Optionally unify notation in some lemmas to always use min and max for total orders.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by sven-manthe** [comment]
> > The instance for the product of metric spaces and some dependent instances are noncomputable now.
> 
> It can be fixed by adjusting the priority of instances. But [leanprover/lean4#2905](https://github.com/leanprover/lean4/issues/2905) causes the need to change the priority of instances of a lot of ordered algebraic typeclasses. You can also try to create shortcut instances only for `ENNReal` to see if it fixes everything.

I wasn't able to create the shortcut instances (Max on R≥0 is still deduced from some noncomputable ordered algebra instance). And I do not know enough about the typeclass inference algorithm and the classes in mathlib to play around with priorities

**Comment by fpvandoorn** [comment]
(gave a review in person)

**Comment by sven-manthe** [comment]
> (gave a review in person)

I think we misdiagnosed an issue: Max is still computable on the reals (and the LinearOrder uses the right fields). Previously, synthesizing Max on ℝ≥0 used the same computable instance, but synthesizing Sup went through an instance for subtype semilattices, which for a reason unclear to me is noncomputable. Now only the second route remains. So, if one really wants to fix this, one probably would have to check why this lattice-theoretic instance is noncomputable.

**Comment by fpvandoorn** [comment]
Looks good to me!

bors d+

**Pull request closed without merging**
