### PR TITLE
[Merged by Bors] - feat(Data/MvPolynomial/Basic): add and generalize some lemmas from Finsupp and MonoidAlgebra 

### PR DESCRIPTION
**Pull request by Hagb**
Most of these changes generalize from `DistribMulAction` to `SmulZeroClass`.
The new lemmas are all just proved using corresponding lemmas on the underlying types.

---
The corresponding PR to mathlib3 is https://github.com/leanprover-community/mathlib/pull/18855

- [x] depends on: #3752

* [`data.finsupp.basic`@`57911c5a05a1b040598e1e15b189f035ac5cc33c`..`f69db8cecc668e2d5894d7e9bfc491da60db3b9f`](https://leanprover-community.github.io/mathlib-port-status/file/data/finsupp/basic?range=57911c5a05a1b040598e1e15b189f035ac5cc33c..f69db8cecc668e2d5894d7e9bfc491da60db3b9f)
* [`algebra.monoid_algebra.basic`@`2651125b48fc5c170ab1111afd0817c903b1fc6c`..`f69db8cecc668e2d5894d7e9bfc491da60db3b9f`](https://leanprover-community.github.io/mathlib-port-status/file/algebra/monoid_algebra/basic?range=2651125b48fc5c170ab1111afd0817c903b1fc6c..f69db8cecc668e2d5894d7e9bfc491da60db3b9f)
* [`data.mv_polynomial.basic`@`0b89934139d3be96f9dab477f10c20f9f93da580`..`f69db8cecc668e2d5894d7e9bfc491da60db3b9f`](https://leanprover-community.github.io/mathlib-port-status/file/data/mv_polynomial/basic?range=0b89934139d3be96f9dab477f10c20f9f93da580..f69db8cecc668e2d5894d7e9bfc491da60db3b9f)

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
@ericrbg, generally its better to not create these PRs until the mathlib3 PR is merged, as then the reviewer can compare the mathlib output.

**Comment by ericrbg** [comment]
wrong name I think :b

**Comment by eric-wieser** [comment]
Whoops!

**Comment by eric-wieser** [comment]
@Hagb, this should be ready to revive in 18 hours or so. You can visit the pages of the form https://leanprover-community.github.io/mathlib-port-status/file/data/mv_polynomial/basic to see the auto-translated versions of your changes, in the "Changes in mathlib3port" section. Note that they are not there yet as the translator runs once a day.

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3752
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3752~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by Hagb** [comment]
Thank @Parcly-Taxel.
@eric-wieser Forward-porting should have been done.

**Review by eric-wieser — APPROVED** [review]
bors merge

Thanks!

The `by` line wrap changes in unrelated lemmas made this very slightly annoying to review, but I'll let you off @Parcly-Taxel since you split the rest into a standalone PR.

**Pull request closed without merging**
