### PR TITLE
[Merged by Bors] - chore: space after `←`

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
During the merge I removed one of two `section CommRing`, because it looked like it was added erroneously.

**Comment by mo271** [comment]
https://leanprover.zulipchat.com/#narrow/stream/144837-PR-reviews/topic/.238178.20space.20after.20.E2.86.90

**Comment by YaelDillies** [comment]
I don't think we should merge this given that there is no guideline and the `← ` idiom is mostly a result of mathport (or at least indistinguishable from a mathportism).

**Comment by YaelDillies** [comment]
Can we stop wasting time on this and worry about more important things?

**Comment by mo271** [comment]
> Can we stop wasting time on this and worry about more important things?

The hope is to save everybody's time by agreeing on one style and use that.

**Pull request closed without merging**
