### PR TITLE
[Merged by Bors] - feat: port Analysis.Complex.Circle

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
bors merge

**Comment by collares** [comment]
Conflicts with #4013 due to the nearby change to Mathlib.lean

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4013
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4013~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Pull request closed without merging**
