### PR TITLE
[Merged by Bors] - feat: port LinearAlgebra.Determinant

### PR DESCRIPTION
**Pull request by Komyyy**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3691
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3691~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by Parcly-Taxel** [comment]
Below I have pushed a commit that fixes all the comment naming and all but 10 errors in the file. Please feel free to fix the remaining errors.

**Comment by Komyyy** [comment]
This defEq problem seems essential and difficult.
Should we remain `maxHeartbeats` line?

**Review by Ruben-VandeVelde — APPROVED** [review]
I pushed https://github.com/leanprover-community/mathlib4/tree/port/LinearAlgebra.Determinant-2 to review the diff with mathport output.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
