### PR TITLE
[Merged by Bors] - chore(AlexandrovDiscrete): move `exterior` to new files

### PR DESCRIPTION
**Pull request by urkud**
I'm going to use `exterior` in files that don't need to know about `AlexandrovDiscrete`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by YaelDillies — COMMENTED** [review]
I'm not against it, but can you explain the motivation in the PR description?

**Comment by urkud** [comment]
E.g., I want to make https://leanprover-community.github.io/mathlib4_docs/Mathlib/Topology/Separation.html#IsCompact.closure use `IsCompact.exterior`.

**Review by YaelDillies — APPROVED** [review]
Good enough justication by me

maintainer merge

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
