### PR TITLE
[Merged by Bors] - feat: port Analysis.NormedSpace.LinearIsometry

### PR DESCRIPTION
**Pull request by faenuccio**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by faenuccio** [comment]
-- Porting note: The proof of `coe_injective` one line 173 is slightly longer than in Lean 3. The true problem arrives on line 194 with `congr_arg`: Lean4 cannot understand that `f` is a function although the instance `SemilinearIsometryClass` is passed explicitely. For instance,
```lean
def foo [SemilinearIsometryClass 𝓕 σ₁₂ E E₂] {f : 𝓕} : E → E₂ := f
```
leads to an error, while
```lean
def bar (h : SemilinearIsometryClass 𝓕 σ₁₂ E E₂) {f : 𝓕} : E → E₂ := h.coe f
```
works.

**Comment by faenuccio** [comment]
@Parcly-Taxel Can you comment/explain how you solved the issue on line 194 concerning `congr_arg`?

**Comment by Parcly-Taxel** [comment]
Probably this:

https://github.com/leanprover-community/mathlib4/pull/3289/commits/37feebcdd1308c1a915c4b19a469053c7dca80c7#diff-341df2991616b5911a6fbb661993ecf6c8dd6c68241ee69e63f1a1651cbbf29dR184

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
