### PR TITLE
[Merged by Bors] - perf (Abelian.Transfer): clean up a dsimp

### PR DESCRIPTION
**Pull request by mattrobball**
Cleaning up a `dsimp` improves performance.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Review by grunweg — APPROVED** [review]
Two birds with one stone: addresses a porting nice, shorter and nicer - and presumably even faster :tada:
Assuming benchmarking is neutral or positive (let alone wildly positive), looks good to me. (But I'm not an expert.)

Thank you for doing this, please keep going!

**Review by jcommelin — COMMENTED** [review]
bors d+

**Comment by mattrobball** [comment]
bors merge

**Comment by mattrobball** [comment]
bors r-

I should delete that `nolint`

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
