### PR TITLE
[Merged by Bors] - feat: port Data.Finsupp.Interval

### PR DESCRIPTION
**Pull request by nomeata**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by nomeata** [comment]
Ran out of time to finish that one, so anyone may take over. The next issue is with a `by convert rfl` proof that doesn’t work anymore.

**Comment by jcommelin** [comment]
Should we try to make the file work without
```
open Classical
```

It looks like that was at least the intention of some of the lemmas...

**Comment by nomeata** [comment]
It has that in lean3. As tempting as it is to clean things up, I think it make sense to stay focused on porting while porting. We can open an issue to keep track of it.

**Comment by jcommelin** [comment]
Fair enough.

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Comment by nomeata** [comment]
(I just had a look, and removing `open Classical` is not trivial.

**Pull request closed without merging**
