### PR TITLE
[Merged by Bors] - chore (Algebra.Order.WithTop): split into unbundled and bundled 

### PR DESCRIPTION
**Pull request by mattrobball**
Much of the results in `Algebra.Order.Monoid.WithTop` only depend on unbundled ordered algebra instance parameters. We split those results out into a new file `Algera.Order.Monoid.Unbundled.WithTop` leaving the facts about bundled ordered monoids.

---

- [x] depends on : #14390 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by riccardobrasca** [comment]
LGTM. Do you know why there are declarations that changed?

bprs d+

**Comment by riccardobrasca** [comment]
Ops

bors d+

**Comment by mattrobball** [comment]
> LGTM. Do you know why there are declarations that changed?

I couldn't figure why these got reported. I checked they were just moved. Maybe a bug with two declarations in the same file having the same name after stripping namespaces.

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
