### PR TITLE
WIP: tinker with Function.Surjective.module

### PR DESCRIPTION
**Pull request by kbuzzard**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
!bench

**Comment by kbuzzard** [comment]
I wonder why this change has such a detrimental affect on those files? Note to self -- chase this up.

**Comment by kbuzzard** [comment]
Mathlib.Algebra.Category.ModuleCat.Limits is 250 lines and compiles on my machine in 8 seconds, so a 15.7% increase is not the end of the world :-) Around half the time is spent on one declaration, `directLimitsIsColimit`. On master according to `count_heartbeats` this takes 140000-150000 heartbeats, and according to the profiler it takes about 5 seconds on my machine. Piping the trace output of the declaration to a file gives a 40952-line file.

With the change in this PR, the declaration now takes about 6 seconds, it goes up to 188426 heartbeats and the trace is now 49911 lines, an increase of 25%.

**Comment by kbuzzard** [comment]
master now has the change that this PR makes because it was also made in #6241 . Note that that PR was also benchmarked and similar slowdowns were observed in the same two files.

**Pull request closed without merging**
