### PR TITLE
feat: add `RelCovering`, golf

### PR DESCRIPTION
**Pull request by astrainfinita**
Mathlib3 PR: https://github.com/leanprover-community/mathlib/pull/18128

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by kbuzzard** [comment]
Note: the mathlib3 PR is still open.

**Comment by fpvandoorn** [comment]
Please align all new declarations, and make sure to merge master.

**Comment by eric-wieser** [comment]
I'm going to temporarily untag this `mathlib-pair`, since it's polluting the porting dashboard and the mathlib3 PR isn't reviewed

**Comment by jcommelin** [comment]
This pull request has not seen any activity for quite a while, and it does not pass all CI checks. For these reasons, I am closing it now.

If you are still interested in getting this PR merged, please re-open the PR, update the branch, and make sure that all CI checks pass, Please label the PR with `awaiting-review` when ready.

**Pull request closed without merging**
