### PR TITLE
[Merged by Bors] - feat(RingTheory/StandardSmooth): base change of standard smooth algebras

### PR DESCRIPTION
**Pull request by chrisflav**
Shows that being standard smooth is stable under base change.

This contribution was created as part of the AIM workshop "Formalizing algebraic geometry"
in June 2024.

Co-authored-by: Andrew Yang  @erdOne
Co-authored-by: Yung Tao Cheng @rontaucheng

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by jcommelin — COMMENTED** [review]
LGTM!

maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by chrisflav** [comment]
Thanks for the reviews!

Could someone give this another `bors r+`? (I caused a merge conflict with my own PR.)

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by riccardobrasca** [comment]
bors +

**Comment by riccardobrasca** [comment]
ops.

bors d+

**Pull request closed without merging**
