### PR TITLE
[Merged by Bors] - feat: port Analysis.Calculus.FDeriv.Basic

### PR DESCRIPTION
**Pull request by mcdoll**
---

- [x] depends on: #4091

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4091
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4091~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by collares** [comment]
Porting note says we should ping @urkud.

**Comment by urkud** [comment]
I guess, I'll have to forward port my unfinished refactoring... it's not ready yet, and I don't want to stall the porting.

**Comment by mcdoll** [comment]
Thanks Yury. I hope the forward porting will be not too painful.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
