### PR TITLE
[Merged by Bors] - feat: port Analysis.InnerProductSpace.LinearPMap

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

- [ ] depends on: #5521

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5521
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
LGTM, please merge it after the dependency has landed in master

bors d+

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5521~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
