### PR TITLE
[Merged by Bors] - chore(RingTheory/FinitePresentation): make `Algebra.FinitePresentation` a class

### PR DESCRIPTION
**Pull request by chrisflav**
Makes `Algebra.FinitePresentation` a class, matching `Algebra.FiniteType`. Changes theorems to instances where possible.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by chrisflav** [comment]
!bench

**Comment by chrisflav** [comment]
!bench

**Review by eric-wieser — COMMENTED** [review]
I worry slightly that:
```lean
def FinitePresentation (f : A →+* B) : Prop :=
  @Algebra.FinitePresentation A B _ _ f.toAlgebra
```
is going to be trouble, as this is a typeclass when unfolded but not otherwise.
Maybe this is just superstition left from Lean 3; no action needed unless another reviewer is also worried.

**Comment by chrisflav** [comment]
> I worry slightly that:
> 
> ```lean
> def FinitePresentation (f : A →+* B) : Prop :=
>   @Algebra.FinitePresentation A B _ _ f.toAlgebra
> ```
> 
> is going to be trouble, as this is a typeclass when unfolded but not otherwise. Maybe this is just superstition left from Lean 3; no action needed unless another reviewer is also worried.

I stuck to the design of `RingHom.FiniteType` here, which should have the same issue?

**Comment by mattrobball** [comment]
> I worry slightly that:
> 
> ```lean
> 
> def FinitePresentation (f : A →+* B) : Prop :=
> 
>   @Algebra.FinitePresentation A B _ _ f.toAlgebra
> 
> ```
> 
> is going to be trouble, as this is a typeclass when unfolded but not otherwise.
> 
> Maybe this is just superstition left from Lean 3; no action needed unless another reviewer is also worried.

The transparency differences between the two could be one source of trouble but since there is no data here I think that risk is minimized. What other spots come to mind?

Should this be an `abbrev` anyway?

**Comment by mattrobball** [comment]
It would be nice to minimize the named instance parameters.

**Comment by mattrobball** [comment]
I think this looks good. Thanks.

bors merge

**Comment by chrisflav** [comment]
Thanks for the reviews!

**Pull request closed without merging**
