### PR TITLE
[Merged by Bors] - perf (Preadditive.FunctorCategory): use `dsimp` before `ext`

### PR DESCRIPTION
**Pull request by mattrobball**
`dsimp` seems to significantly improve the performance of `ext` here and elsewhere.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
[Here](http://speed.lean-fro.org/mathlib4/compare/e7b27246-a3e6-496a-b552-ff4b45c7236e/to/5d118204-7867-466e-ab3b-5910c9ee687b?hash1=f2e0c5baa5254e9c8c87d759086af0086206d67f) is a comparison. 

```diff
  Benchmark                                                      Metric         Change
  ==========================================================================
+ ~Mathlib.CategoryTheory.Preadditive.FunctorCategory              instructions   -95.4%
```

**Review by grunweg — APPROVED** [review]
Well, the diff looks easy enough :-) though I don't understand the secrets of optimising Lean code well. Can you leave a comment somewhere that the extra dsimp is for performance?

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
