### PR TITLE
[Merged by Bors] - feat: port Topology.ContinuousFunction.ZeroAtInfty

### PR DESCRIPTION
**Pull request by int-y1**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
I did a rebase on top of the latest mathport output. Please do `git reset --hard origin/port/Topology.ContinuousFunction.ZeroAtInfty` next time you work on this branch.

**Comment by ChrisHughes24** [comment]
I don't understand why the linter fails in files that do not have dependencies touched by this PR.

**Comment by j-loreaux** [comment]
We'll see what CI says, but I think the issue was an `@[simps]` in a place where it shouldn't exist that was generating a stupid lemma of the form `[ContinuousMapClass F] [CompactSpace X] (f : F) (x : X) : f x = f x` (possibly with different instances on the right and left-hand sides of this, I didn't check). I think just deleting the `@[simps]` is the solution.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
