### PR TITLE
[Merged by Bors] - refactor: move some classes to `Prop`

### PR DESCRIPTION
**Pull request by urkud**
Also make `SubmonoidClass` extend `OneMemClass`.
This is a Lean 4 version of leanprover-community/mathlib#18015

### CODE REVIEW

**Comment by jcommelin** [comment]
This is matching a mathlib3 refactor, right? Can you please record it in the top post?

**Comment by riccardobrasca** [comment]
The mathlib3 PR is merged and this looks good so

bors merge

**Comment by riccardobrasca** [comment]
Hmm.. I don't understand why CI is failing here.

**Pull request closed without merging**
