### PR TITLE
[Merged by Bors] - feat: port CategoryTheory.Abelian.Pseudoelements

### PR DESCRIPTION
**Pull request by int-y1**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by int-y1** [comment]
todo:

* [ ] problem with `attribute [ext]` on `zero_morphism_ext` and `zero_morphism_ext'`

**Comment by semorrison** [comment]
@int-y1, we've become more strict about the shape of `ext` lemmas, for better or worse, so the right thing to do here is remove them.

I've also switched all the `pseudoZero`s back to `0`. In Lean 4 this instance has become safe as a global instance, because the `coe_sort` is replaced by `Pseudoelement`, so the instance is structural.

**Comment by semorrison** [comment]
If this looks good to you, please merge. Otherwise set back to `awaiting-review` or `help-wanted` as appropriate.

bors d+

**Comment by semorrison** [comment]
@int-y1, I started the next file, at #3882, please feel free to hack on it / adopt. :-)

**Pull request closed without merging**
