### PR TITLE
[Merged by Bors] - feat(Topology/UniformSpace/Ascoli): Arzela-Ascoli for an equicontinuous family of functions

### PR DESCRIPTION
**Pull request by tb65536**
This PR adds a version of Arzela-Ascoli for an equicontinuous family of functions that I will use to prove local compactness of the Pontryagin dual in #11335.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by YaelDillies — APPROVED** [review]
Thanks!

maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by jcommelin** [comment]
bors d+

**Comment by tb65536** [comment]
bors merge

**Comment by tb65536** [comment]
bors merge

**Pull request closed without merging**
