### PR TITLE
[Merged by Bors] - feat(NumberTheory/DirichletCharacter/Orthogonality): new file

### PR DESCRIPTION
**Pull request by MichaelStollBayreuth**
This PR is the final step in establishing the orthogonality relations for Dirichlet characters. 

See [here on Zulip](https://leanprover.zulipchat.com/#narrow/channel/144837-PR-reviews/topic/Orthogonality.20of.20Dirichlet.20characters/near/480747063).

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Comment by loefflerd** [comment]
Why do you assume throughout that there's a root of unity of order `n.totient`, and then derive the (strictly weaker) statement that you actually need, i.e. that there's a r.o.u. of order `(ZMod n)^x.exponent`, on-the-fly from this? I guess the answer is that the overwhelmingly most important use case is when `R` is the complex numbers and then you have roots of unity of all orders; and I don't want to hold up the progress of the wider project because of this detail. But it would be a pity if applications to e.g. rationality results for Dirichlet characters later get held up because nobody realises that the code in this file can be easily strengthened.

May I suggest we put in a TODO in the code, and a matching github issue, suggesting that in future it might be nice to implementing the  [Carmichael lambda function](https://en.wikipedia.org/wiki/Carmichael_function) and re-jig this code to require `HasEnoughRootsOfUnity R (carmichael_lambda n)` or some such? This would be a good first project for a learner.

**Comment by MichaelStollBayreuth** [comment]
If you think it makes sense to use the weaker hypothesis, I will do that. The main reason I used `n.totient` is that there appears to be no handy Mathlib name for [Carmichael's function](https://en.wikipedia.org/wiki/Carmichael_function). (Plus, as you say, I anticipated that this would mostly be used with algebraically closed fields as targets, where it doesn't really matter.)

**Comment by riccardobrasca** [comment]
> If you think it makes sense to use the weaker hypothesis, I will do that. The main reason I used `n.totient` is that there appears to be no handy Mathlib name for [Carmichael's function](https://en.wikipedia.org/wiki/Carmichael_function). (Plus, as you say, I anticipated that this would mostly be used with algebraically closed fields as targets, where it doesn't really matter.)

If the problem is only that the name is long to write you can always use a local notation or something. I agree it's not very important, but since it also comes at essentially zero cost I would go with David's suggestion.

**Comment by MichaelStollBayreuth** [comment]
Ii the end, it is only the `variable` line where one has to use the longer version, so that's not really a problem. Also, it saves a private lemma plus two proof lines, so I tink it is actually a good thing. Thanks @loefflerd !
I've also taken the opportunity of fixing an inconsistency in the direction of the isomorphism in one of the various duality statements (which also got rid of a few `.symm`s in the definitions).

**Comment by loefflerd** [comment]
This looks great now – the new treatment is both simpler and more general. Happy to recommend merging it in this form.

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
