### PR TITLE
[Merged by Bors] - feat: port/CategoryTheory.Category.Cat

### PR DESCRIPTION
**Pull request by mattrobball**
---

- [x] depends on: #2326
[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2326
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2326~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by dupuisf** [comment]
There is an extra file (`Mathlib.lean.orig`) being added by mistake here.

**Comment by mattrobball** [comment]
> There are two extra files (`Mathlib.lean.orig` and another `.orig` file) being added by mistake here.

Thanks. They are gone now.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
