### PR TITLE
[Merged by Bors] - chore(Function): rename some lemmas

### PR DESCRIPTION
**Pull request by urkud**
- Merge `Function.left_id` and `Function.comp.left_id` into `Function.id_comp`.
- Merge `Function.right_id` and `Function.comp.right_id` into `Function.comp_id`.
- Merge `Function.comp_const_right` and `Function.comp_const` into `Function.comp_const`, use explicit arguments.
- Move `Function.const_comp` to `Mathlib.Init.Function`, use explicit arguments.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors d+

**Comment by urkud** [comment]
bors merge

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
