### PR TITLE
[Merged by Bors] - chore(LinearAlgebra/Alternating): split

### PR DESCRIPTION
**Pull request by urkud**
I'm going to refactor/expand API about `domCoprod`, and I don't want to rebuild the whole library when I do it.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
bors d+

Can you add an explanation of why you want to make this split in the PR description? It seems harmless enough, but it would be nice to record the motivation.

**Comment by urkud** [comment]
bors merge

**Comment by eric-wieser** [comment]
Your explanation is the opposite of what I expected! I'm glad dom_coprod is useful to you, because it was a dead end for what I was trying to do!

**Comment by urkud** [comment]
> Your explanation is the opposite of what I expected! I'm glad dom_coprod is useful to you, because it was a dead end for what I was trying to do!

I'm going to use it to define exterior product of differential forms. For this, I'm going to migrate from tensor product to a bilinear map argument, as it is done for convolution.

**Comment by eric-wieser** [comment]
What's the advantage of using a bilinear map? That's equivalent to just composing the current version with a bilinear map at the very end, right?

**Comment by urkud** [comment]
I see two advantages:

- we have one definition (and one set of lemmas) that gives the desired result in all cases without pre/post-composing with other maps;
- in the continuous case, there is no canonical topology on the tensor product, so we need to use bilinear maps anyway.

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
