### PR TITLE
[Merged by Bors] - feat: port Topology.Category.Top.Limits.Basic

### PR DESCRIPTION
**Pull request by mattrobball**
---

- [x] depends on: #3653

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3653
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
Okay, I have chopped down this file to match https://github.com/leanprover-community/mathlib/pull/18871

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3653~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by Parcly-Taxel** [comment]
Check if putting `nolint` on the `TopCatMax` is the right decision here.

**Pull request closed without merging**
