### PR TITLE
[Merged by Bors] - feat(Combinatorics.SetFamily.Shadow): shadow_singleton

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
@YaelDillies: git blame on the mathlib3 repo seems to say you added the TODO, I don't quite understand  the relationship to `covers` and `GradeOrder`, so just use `simp` here.

**Review by YaelDillies — APPROVED** [review]
Ahah, I guess that's quick enough! I'm interested to know whether this proof will survive the generalisation of `shadow` to graded orders.

maintainer merge

**Comment by YaelDillies** [comment]
The relationship is that `shadow` makes sense in a general graded order (rather than merely `Finset _`) and then it should be necessary to use `covBy` to prove `shadow_singleton`.

**Comment by b-mehta** [comment]
Nice! Probably the graded version will want to say that the shadow of a set family in which every element has grade 1 is empty... 

bors merge

**Pull request closed without merging**
