### PR TITLE
[Merged by Bors] - feat(Analysis/Normed/Group/Ultra): triangle ineq for tsum & tprod

### PR DESCRIPTION
**Pull request by loefflerd**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by pechersky** [comment]
Do you think it would be appropriate here to add similar lemmas for
`finprod` and `finsum`? You could use the `⨆ (i : s)` syntax to avoid the
set-conditionally-complete-lattice problem. Lemmas like `tprod_eq_finprod`
could help golf using the lemmas proven here.

**Comment by loefflerd** [comment]
> Do you think it would be appropriate here to add similar lemmas for `finprod` and `finsum`? You could use the `⨆ (i : s)` syntax to avoid the set-conditionally-complete-lattice problem. Lemmas like `tprod_eq_finprod` could help golf using the lemmas proven here.

I thought you might say that :smile: The issue is that we would have multiple formulations to choose from (Finset.sup, Finset.sup', iSup over a subtype, sSup of the range), and I'm not sure which is best. I'd rather not add more API for the finite case in this particular PR; but if you think it's valuable, by all means make a separate PR for it.

In a somewhat opposite direction, I was actually thinking that it might be a good idea to have the tsum/tprod versions of `norm_prod_le_of_forall_le_of_nonempty` etc.

(As for golfing using `tprod_eq_finprod`: are you suggesting to derive the finite case _from_ the infinite one? That would probably be circular, since the proof of the `tprod` result works by applying the `prod` result to finite sub-products and taking a limit.)

**Comment by pechersky** [comment]
Fair! I thought since we `tprod` is over a type, and `finprod` is over a type where the (mul) support is a plain `Set`, that the type would still be fine to use in the iSup binder syntax. The circularity is avoided thus -- `finprod` uses `Set.Finite`, and this way we don't have to juggle a `Finset.sup(')` into an iSup.

**Comment by loefflerd** [comment]
> Fair! I thought since we `tprod` is over a type, and `finprod` is over a type where the (mul) support is a plain `Set`, that the type would still be fine to use in the iSup binder syntax. The circularity is avoided thus -- `finprod` uses `Set.Finite`, and this way we don't have to juggle a `Finset.sup(')` into an iSup.

Ah, I misunderstood, I'm sorry! I didn't realise `Finprod` was a separate thing, I thought it was just an abbreviation for `Finset.prod` etc. (As you can tell, I've never used it.)

**Comment by loefflerd** [comment]
It looks like we don't have the "normal", non-ultrametric triangle inequality for Finsums either, and apparently nobody has missed it yet, which suggests to me that adding the ultrametric Finsum triangle ineq probably isn't a high priority.

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
