### PR TITLE
feat(Data/Nat/BitVec/Lemmas) `toFin_intCast` + helper bitwise lemmas

### PR DESCRIPTION
**Pull request by technosentience**
Prove `toFin_intCast` and `ofFin_intCast` for bitvectors using helper lemmas about bitwise operations.

---

I haven't came up with better names than `add_pow_two_sub_one_xor_eq_pow_two_sub_one` for lemmas, so
suggestions would be appreciated.

I also wanted to prove the statement that `((2 ^ n - 1) ^^^ x) + 1` is the additive inverse of `x` modulo `2 ^ n`,
since it follows from the lemmas. But I'm not sure about the right definition for it, so I'm leaving it aside for now.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
@technosentience, would you be able to make this a PR to the lean4 repository (these should go in `Init/Data/BitVec/Lemmas.lean` and `Init/Data/Nat/Bitwise/lean`). If you ping me I will speedily review.

(For context, we would like to consolidate the BitVec library into the lean4 repository.)

**Comment by technosentience** [comment]
> @technosentience, would you be able to make this a PR to the lean4 repository (these should go in `Init/Data/BitVec/Lemmas.lean` and `Init/Data/Nat/Bitwise/lean`)? If you ping me I will speedily review.
> 
> (For context, we would like to consolidate the BitVec library into the lean4 repository.)

Hi @semorrison! There are quite a few lemmas from Std and Mathlib that are needed for this proof. Should I also import them into Init, and should I make a separate PR with them? I could try to cut down on some dependencies, but I definitely need the Std ones.

**Comment by semorrison** [comment]
@technosentience, I think you'll find that the lemmas you're referring to were already moved. There is a 1-month delay in Mathlib and Std updating to the newest Lean version, but that has just happened so everything should be close to in sync again.

**Comment by technosentience** [comment]
Hi! I double-checked the definitions and I don't think it makes sense to move this lemma to Init. `toFin_intCast` is defined in terms of `Int.cast` from Std and the `Ring` instance of `Fin n` from Mathlib. It's only needed to prove that `BitVec w` is a `CommRing`, so I think it should live in Mathlib.

**Comment by semorrison** [comment]
Sorry to be slow on this. I'm hesitant to add to Mathlib's BitVec material: I really want to strip it down to the bare minimum (e.g. the CommRing instance). What about moving the Nat lemmas into either a separate PR, or even a PR upstream? (Feel free to ping me on zulip; I've been behind on github inbox recently. :-)

**Comment by semorrison** [comment]
Actually, I guess this is fine, it's not really going outside that CommRing box at all anyway. You decide. :-)

bors d+

**Comment by jcommelin** [comment]
@technosentience In the mean time, the BitVec files have been removed from mathlib. Could you please move this PR to Batteries and/or Core.

Since this PR is no longer for mathlib, I am closing it.

bors d-

**Pull request closed without merging**
