### PR TITLE
[Merged by Bors] - feat: remove the text-based linters for module docstring, copyright and author lines

### PR DESCRIPTION
**Pull request by grunweg**
They are superseded by the header linter (#16574).

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
I suggest an experiment: add a file that breaks the rules and see that the new linter actually catches the errors. But probably people who are more involved in CI and metaprogramming have better ideas.

**Comment by grunweg** [comment]
I just added such a file, the linter works locally. Does that look sufficient to you? (If CI fails, I'll remove it again.)

**Comment by adomani** [comment]
The internal logic of the headerLinter is tested in `test/HeaderLinter.lean`.  The linter picked up non-complying copyright headers in development and I also think that I did a test similar to the ones that Michael just did while developing the linter.

The test here also seems to work: besides the fact that the "new" definition does not have a doc-string, there are also `build` errors coming from the malformed copyright header.

My main reason for not being immediately enthusiastic about removing these "text-based" linters is that the syntax linter will typically lint `Mathlib.Init` and whatever imports that, but the text-based ones also cover the "early" files.

**Comment by grunweg** [comment]
Wasn't the point of `Mathlib.Init` that every file imports it (or is imported in it)?
Checking the copyright headers of all these syntax linters is nice, I agree - but I don't think keeping a separate linter implementation around just for them makes too much sense.

**Comment by adomani** [comment]
Right, I simply have not yet accepted that the style-linters will not necessarily by style-compliant, that's all!  I agree that having as much as possible enforced in Lean is a good aim: once CI is happy, I am happy to maintainer merge this PR!

**Review by adomani — APPROVED** [review]
Looks good to me!

I see that Bryan self-assigned this PR, so I won't maintainer merge, in case he wants to add something, but I am happy with merging it!

Thanks!

**Comment by grunweg** [comment]
@adomani I just wrote #18725, importing the `header` linter in every file that is imported in Mathlib.Init. This should ensure all files are checked for missing copyright (or module doc-string). Does that assugae your concerns on this PR?

**Comment by adomani** [comment]
This is what was going to happen once the linter had been rewritten as a syntax linter, isn't it?  :wink: 

I'll

maintainer merge

and also ping @bryangingechen, in case there are any last-minute comments!

**Comment by bryangingechen** [comment]
LGTM, thanks for the ping!
bors r+

**Pull request closed without merging**
