### PR TITLE
[Merged by Bors] - chore: adaptations to lean 4.8.0

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
Mainly this adds names to instances, which are presumably necessary for some unspecified reason.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
Can you add an explanation of why all the instances were renamed?

The new names are fine, but I thought the new lean release was supposed to be better at naming them automatically; and it's strange to only give a name to one instance in a group of multiple.

(No changes needed to the diff, just a quick summary in the PR description is enough)

**Comment by eric-wieser** [comment]
bors d+

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors p=5

**Comment by kmill** [comment]
@eric-wieser I see a reason didn't make it in, but I'll record it here: there are a number of instances that are referred to in the docs, like the overview and the undergrad yaml files. The instance name changes (at least the ones I did) are giving the new names according to the new algorithm.

**Comment by Ruben-VandeVelde** [comment]
What Kyle said - and it's more robust to give explicit names when we're going to refer to them by name

**Comment by eric-wieser** [comment]
Thanks! I was curious to know if the issue was name *collisions* in the new algorithm. I guess the answer is no?

**Pull request closed without merging**
