### PR TITLE
[Merged by Bors] - feat: port Logic.Equiv.Array

### PR DESCRIPTION
**Pull request by maxwell-thum**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by maxwell-thum** [comment]
I think this may be a bit out of my range. I'm not at all familiar with the differences between `Array`s in Lean 3 and 4.

**Comment by maxwell-thum** [comment]
Oh, but if you do understand that stuff, this file is very short.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2194~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by Ruben-VandeVelde** [comment]
We're not porting this; see  #2194.

**Comment by thorimur** [comment]
Reopening this PR and rewriting in terms of `Array` as per [zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/porting.20.60.2Earray.60.20files.20whose.20PR's.20were.20closed.3F)!

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
