### PR TITLE
[Merged by Bors] - feat: port Algebra.Hom.Freiman

### PR DESCRIPTION
**Pull request by qawbecrdtey**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by LukasMias** [comment]
Porting this shows that the original mathlib3 file could be in a better state: the `comm_group` and `comm_monoid` instances contain a lot of declarations that are not really needed; the field `map_sum_eq_map_sum'` in `FreimanHomClass` should be named `map_sum_eq_map_sum` instead to be consistent with other HomClasses, and many names of additive versions of the theorems are just ever so slightly off (`add_freiman_hom.to_freiman_hom_injective` should be `add_freiman_hom.to_add_freiman_hom_injective`). I think we can merge this anyway and clean the mathlib3 file whenever convenient; not too much is downstream from this file currently, so either way there won't be much to fix..

**Comment by rwbarton** [comment]
bors merge

**Comment by rwbarton** [comment]
Looks like some changes to `List.repeat`--probably needs rewriting using `List.replicate`?

**Comment by LukasMias** [comment]
Replacing `repeat` with `replicate` wasn't so bad after all, haha. Now we should have it!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
