### PR TITLE
[Merged by Bors] - fix: make CI-task "check for noisy stdout lines" more verbose.

### PR DESCRIPTION
**Pull request by joneugster**
linter warnings print the following messages to stdout:

```
stdout:
./././MyProject/MyFile.lean:19:53: warning: unused variable `x` [linter.unusedVariables]
./././MyProject/MyFile.lean:19:53: warning: unused variable `y` [linter.unusedVariables]
```

With this change, the CI would at least print the first line after `stdout:`, partially helping with debugging.

---

I don't know how to test this.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alexjbest** [comment]
To test this you can always push a commit to this PR that shows this working in CI. It seems straightforward enough though

**Comment by joneugster** [comment]
[Message looks good](https://github.com/leanprover-community/mathlib4/actions/runs/6624542331/job/17993740486#step:11:6)

**Comment by alexjbest** [comment]
Lgtm thanks

maintainer merge

**Comment by alexjbest** [comment]
maintainer merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
