### PR TITLE
chore(Data/Num): migrate from `bit0`/`bit1`

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by rwst** [comment]
I'm adopting (resolve conflicts).

**Comment by urkud** [comment]
@rwst Please unassign whenever

- you stop working on this PR
- or it is ready for review.

Usually we use "Assigned To" for "assigned to a reviewer/maintainer for review", not for "assigned to someone to fix".

**Comment by rwst** [comment]
Right. To fix this properly, according to https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Deprecated.20since.202022/near/444791465, `bit0 n` should be replaced with `2*n`, and `bit1 n` with `2*n + 1`.

**Comment by rwst** [comment]
Nope. That's over my head. Sorry. Will be more careful when adopting.

**Comment by jcommelin** [comment]
See #14745 for an independent attempt.

**Comment by urkud** [comment]
I'm closing this PR in favor of @jcommelin 's.

**Pull request closed without merging**
