### PR TITLE
[Merged by Bors] - feat: generalize `LinearMap.exists_rightInverse_of_surjective` to projective modules

### PR DESCRIPTION
**Pull request by eric-wieser**
Previously it only held in vector spaces.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ADedecker** [comment]
I think this doesn't actually change that much in terms of the imports added in #17452 : the previous imports of `Topology.MetricSpace.Algebra` just happened to be very low in terms of algebra (e.g before tensor products). But maybe this just suggests that we shouldn't be scared of importing more algebra since it is still basic algebra.

But I think this change is good in itself, and we can do better by stating it for `Module.Projective` (the file about projective modules is at distance 1 from `Mathlib.LinearAlgebra.FreeModule.Basic`, all other imports are useless, so that doesn't sound like import creep) : it is just a special case of [Module.projective_lifting_property](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Algebra/Module/Projective.html#Module.projective_lifting_property).

At some point we should be able to do the same for [LinearMap.exists_leftInverse_of_injective](https://leanprover-community.github.io/mathlib4_docs/Mathlib/LinearAlgebra/Basis/VectorSpace.html#LinearMap.exists_leftInverse_of_injective) (in injective modules), but we don't seem to have the `Free -> Injective` instance so it's not useful for now.

I'm not sure my explanations are clear, feel free to tell me if not :sweat_smile:

**Comment by grunweg** [comment]
The changes in this PR look sensible to me, but the proposed generalisation to projective modules also does. Let me label it awaiting-author accordingly.
awaiting-author

**Review by alreadydone — COMMENTED** [review]
~~[Module.projective_lifting_property](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Algebra/Module/Projective.html#Module.projective_lifting_property) is more general than this, right?~~ Oh, it's already mentioned.

**Comment by ADedecker** [comment]
> [Module.projective_lifting_property](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Algebra/Module/Projective.html#Module.projective_lifting_property) is more general than this, right?

Yes, that's what I alluded to above. But I still think we should have a name for this special case which does *not* mention "projective", because some people will be looking for it without knowing what a projective module is.

**Comment by alreadydone** [comment]
> At some point we should be able to do the same for [LinearMap.exists_leftInverse_of_injective](https://leanprover-community.github.io/mathlib4_docs/Mathlib/LinearAlgebra/Basis/VectorSpace.html#LinearMap.exists_leftInverse_of_injective) (in injective modules), but we don't seem to have the `Free -> Injective` instance so it's not useful for now.

Free modules are usually very far from being injective, and I don't think `LinearMap.exists_leftInverse_of_injective` hold for the injection from the Z-module Z into Q, for example. (Q is an injective Z-module but Z is not.)

**Comment by ADedecker** [comment]
> > At some point we should be able to do the same for [LinearMap.exists_leftInverse_of_injective](https://leanprover-community.github.io/mathlib4_docs/Mathlib/LinearAlgebra/Basis/VectorSpace.html#LinearMap.exists_leftInverse_of_injective) (in injective modules), but we don't seem to have the `Free -> Injective` instance so it's not useful for now.
> 
> Free modules are usually very far from being injective, and I don't think `LinearMap.exists_leftInverse_of_injective` hold for the injection from the Z-module Z into Q, for example. (Q is an injective Z-module but Z is not.)

Of course you're right, this was nonsense. But [LinearMap.exists_leftInverse_of_injective](https://leanprover-community.github.io/mathlib4_docs/Mathlib/LinearAlgebra/Basis/VectorSpace.html#LinearMap.exists_leftInverse_of_injective) should still generalize to the case where `V` is an injective module, right? So really the main thing is that it doesn't hold for free modules because they are not necessarily injective? Or am I saying nonsense again?

**Comment by alreadydone** [comment]
> But [LinearMap.exists_leftInverse_of_injective](https://leanprover-community.github.io/mathlib4_docs/Mathlib/LinearAlgebra/Basis/VectorSpace.html#LinearMap.exists_leftInverse_of_injective) should still generalize to the case where `V` is an injective module, right? So really the main thing is that it doesn't hold for free modules because they are not necessarily injective?

Yeah, a injective linear map has a left inverse if the domain is injective, which is a direct application of [Module.Injective.extension_property](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Algebra/Module/Injective.html#Module.Injective.extension_property).

**Comment by eric-wieser** [comment]
> But [LinearMap.exists_leftInverse_of_injective](https://leanprover-community.github.io/mathlib4_docs/Mathlib/LinearAlgebra/Basis/VectorSpace.html#LinearMap.exists_leftInverse_of_injective) should still generalize to the case where `V` is an injective module, right?

Mathlib has no instance for `Module.Injective`, so I haven't made this generalization.

**Comment by eric-wieser** [comment]
Though I've split out #17747 to make it easier to attempt that refactor in future.

**Review by alreadydone — APPROVED** [review]
LGTM
If I read [this](https://github.com/leanprover-community/mathlib4/pull/17560#issuecomment-2400959768) correctly, 1249 files's imports increase by one file, which amount to less than 0.1% change in overall imports.

**Comment by alreadydone** [comment]
maintainer merge

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Pull request closed without merging**
