### PR TITLE
[Merged by Bors] - chore: follow the "reducible non-instances" library note

### PR DESCRIPTION
**Pull request by j-loreaux**
This marks some non-instance `def`s as `abbrev`s, per the relevant library note. Without this, we're placing default transparency roadblocks whenever these `def`s get used to create specific `instance`s on types.

---

This recently caused me some unnecessary pain.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by j-loreaux** [comment]
!bench

**Comment by dupuisf** [comment]
Thanks!

bors r+

**Comment by mattrobball** [comment]
bors delegate+

**Comment by j-loreaux** [comment]
bors merge

**Pull request closed without merging**
