### PR TITLE
refactor: make `CanonicallyOrdered...` mixin

### PR DESCRIPTION
**Pull request by astrainfinita**
I think this is the proposed refactor. (See https://github.com/leanprover-community/mathlib/pull/14556)

However it seems that all things get slower... :(

Need more love to speed it up.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by negiizhao** [comment]
!bench

**Comment by digama0** [comment]
Note: I have pushed an update to the lean toolchain because this PR was on a [buggy version](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Potential.20data.20loss.20from.20.60lake.20clean.60.20with.204.2E2.2E0-rc2.2F3/near/397875701) of the toolchain. **WARNING**: checking out old commits of this PR using v4.2.0-rc2 or v4.2.0-rc3 can cause `lake clean` to delete your mathlib folder! If you need to do so, make sure to delete `lakefile.olean` manually before running any `lake` commands.

**Comment by negiizhao** [comment]
!bench

**Comment by negiizhao** [comment]
!bench

**Comment by negiizhao** [comment]
!bench

**Comment by negiizhao** [comment]
!bench

**Pull request closed without merging**
