### PR TITLE
[Merged by Bors] - feat: port ModelTheory.Semantics

### PR DESCRIPTION
**Pull request by ChrisHughes24**
---
- [x] depends on: #3194 
- [x] depends on: #3195 
- [x] depends on: #3910

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3194
* leanprover-community/mathlib4#3195
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3194~~
* ~~leanprover-community/mathlib4#3195~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ChrisHughes24** [comment]
Some decisions need to be made here about `simp` normal forms. I think the author of these files might have had a normal form in mind, and it's not entirely clear what that is.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3194~~
* ~~leanprover-community/mathlib4#3195~~
* ~~leanprover-community/mathlib4#3910~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
