### PR TITLE
[Merged by Bors] - fix: to_additive translates constructors of inductive types

### PR DESCRIPTION
**Pull request by fpvandoorn**
[Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/.60to_additive.60.20with.20.60inductive.60)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alexjbest** [comment]
maintainer merge

**Comment by semorrison** [comment]
You seem to not be authorized

**Comment by alexjbest** [comment]
This is the first time I tried this on mathlib4 iirc, I've been a bit out of the loop recently! Is it intended that mathlib3 reviewers = mathlib4 reviewers right now?

**Comment by fpvandoorn** [comment]
It doesn't work yet on mathlib4. You can post in the maintainer merge thread manually. And indeed, that is the Scott bot.

Since this is a small change, I'll just merge it myself.

bors merge

**Comment by alexjbest** [comment]
I'm confused why it doesn't work yet though, the actions seem to be there, and it looks like kevin managed to trigger the bot to post in the reviewer stream the other day :shrug:
sounds good anyways

**Comment by fpvandoorn** [comment]
> I'm confused why it doesn't work yet though, the actions seem to be there, and it looks like kevin managed to trigger the bot to post in the reviewer stream the other day 🤷 sounds good anyways

I think that was a manual comment by Yael (that also confused me).

**Pull request closed without merging**
