### PR TITLE
[Merged by Bors] - feat(Data/Nat/Digits): sum_le_ofDigits

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
I'm not sure if this needs the `mono` attribute.

**Comment by ocfnash** [comment]
Thanks!

bors merge

**Comment by ocfnash** [comment]
Oops

bors r-

**Comment by ocfnash** [comment]
Looks like a spurious failure. If CI runs fine then feel free to merge.

bors d+

**Comment by mo271** [comment]
Thanks for the review!
bors r+

**Pull request closed without merging**
