### PR TITLE
[Merged by Bors] - refactor(Mathlib/Order): remove duplicate lemma `iInf_le'`

### PR DESCRIPTION
**Pull request by vasnesterov**
Remove `iInf_le'` which is equal to `iInf_le`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by vihdzp** [comment]
1. Can you deprecate this instead of removing it? Also, you should reprove it in terms of `iInf_le` in order to showcase that they're truly identical.
2. Can you also deal with `le_iSup'` in this same way?
3. Tangential, but how did this even happen? Were these lemmas initially different somehow?

**Comment by vasnesterov** [comment]
> 1. Can you deprecate this instead of removing it? Also, you should reprove it in terms of `iInf_le` in order to showcase that they're truly identical.
> 2. Can you also deal with `le_iSup'` in this same way? Can you check that there's no other lemmas like these that need to be dealt of?
> 3. Tangential, but how did this even happen? Were these lemmas initially different somehow?

1. What’s the point of deprecating it if no other declarations depend on it?
2. (and 3). I’m not very familiar with this part of Mathlib, so I’m unsure about the history of these lemmas or which other files should be checked. I found that these two are identical while searching for lemmas during the formalization of a different result. Other primed declarations in `CompleteLattice.lean` differ from their unprimed versions.

**Comment by vihdzp** [comment]
Other non-Mathlib projects might depend on this lemma (though admittedly that seems quite unlikely). So the general policy to deprecate lemmas before deleting them, to give downstream users a chance to fix their code instead of just having it suddenly break.

**Comment by vasnesterov** [comment]
Thank you for the explanation! I hadn't thought of that. I've deprecated them.

**Comment by j-loreaux** [comment]
Thanks!

bors merge

**Pull request closed without merging**
