### PR TITLE
[Merged by Bors] - perf(AG.RingHomProperties): less defeq abuse

### PR DESCRIPTION
**Pull request by mattrobball**
We remove all uses (but one minor one) of `erw` in `affineLocally_iff_affineOpens_le` and add some explicit universe annotations. This speeds up the file by ~~50%~~ 40%.

---

Follow-ons to clean up the proof welcome!

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by semorrison** [comment]
bors d+

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
