### PR TITLE
[Merged by Bors] - feat(AlgebraicGeometry): Define preimmersions.

### PR DESCRIPTION
**Pull request by erdOne**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
There is apparently a massive import increase to Mathlib.Geometry.RingedSpace.SheafedSpace. can this be avoided?

**Comment by erdOne** [comment]
Every downstream file that imports `Mathlib.Geometry.RingedSpace.SheafedSpace` also imports `Mathlib.RingedSpace.Stalks`, so this change only affects that single file. IMO stalks are fundamental to sheafed spaces, so this import is permissible from a library design POV. But if you insist I could split the new additions into a new file.

**Comment by joelriou** [comment]
Thanks!

bors merge

**Comment by grunweg** [comment]
Can you fix the build, please? Thanks!

**Comment by erdOne** [comment]
Should be good to go now.

**Comment by jcommelin** [comment]
bors merge

**Pull request closed without merging**
