### PR TITLE
[Merged by Bors] - doc: RingTheory/Generators clarification

### PR DESCRIPTION
**Pull request by kbuzzard**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

I've only just started looking at this material (I've had a hectic last few weeks) and my first reaction was "I don't even understand the module docstring".

### CODE REVIEW

**Comment by erdOne** [comment]
Thanks!
Is this awaiting-review or do you plan to fix more?

**Comment by kbuzzard** [comment]
Oh sorry, I just failed to mark it awaiting-review.

**Comment by erdOne** [comment]
Thanks!
maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
