### PR TITLE
[Merged by Bors] - chore: replace `continuity` by `fun_prop`, easy cases

### PR DESCRIPTION
**Pull request by grunweg**
Inspired by #12661: let's start with some easy instances, so we can focus on the difficult ones.

In particular, this PR does not depend on any in-progress bugfixes, not tries to change a default value `by continuity` to `by fun_prop`.

I am not at all confident about the tagging of lemmas with fun_prop: I remember this being subtle, but can't find any documentation on this. @lecopivo Can you advise on these lemmas (or simply link to the right documentation if I just overlooked it)?

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
CC @urkud

**Comment by grunweg** [comment]
!bench

**Comment by lecopivo** [comment]
Most of the theorems look fine to me. I remember there were some issues with `Sigma` so I'm not sure that all the theorems will be actually used. 

I will investigate the use of `Sigma` a bit closer but that should not block this PR.

**Comment by lecopivo** [comment]
When checking you tagged the right theorem just add option
```
set_option trace.Meta.Tactic.fun_prop.attr true`
```
Every `fun_prop` attribute should produce a message. Check if the message say that the theorem is really about the function you think it should be.

**Pull request closed without merging**
