### PR TITLE
testing: lean4#2728

### PR DESCRIPTION
**Pull request by thorimur**
This PR is just for building and benching at the moment.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by thorimur** [comment]
!bench

**Comment by thorimur** [comment]
!bench

**Comment by thorimur** [comment]
!bench

**Comment by YaelDillies** [comment]
I am closing this PR since it seems it has fulfilled its purpose. Feel free to reopen it.

**Pull request closed without merging**
