### PR TITLE
[Merged by Bors] - feat: align `init.{core, logic}`

### PR DESCRIPTION
**Pull request by digama0**
With this, the files `init.core` and `init.logic` are synchronized, although we aren't currently tracking files from `init` in [port-status](https://github.com/leanprover-community/mathlib/wiki/mathlib4-port-status).

### CODE REVIEW

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
This did not compile with master. I merged, and fixed the imports in `Simps`.

In `Init.Logic`, the new `@[trans]` attribute PR'd in #253 incorrectly rejected the `@[trans]` attribute on 
```
@[deprecated, trans] theorem Implies.trans {p q r : Prop} (h₁ : p → q) (h₂ : q → r) :
    p → r := fun hp => h₂ (h₁ hp)
```
I left a note and removed the attribute for now.

**Comment by digama0** [comment]
The original lean 3 would have rejected it too - I rewrote the theorem to use `->` instead of `Implies`, but I guess that's not an option in this case.

**Comment by digama0** [comment]
bors merge

**Pull request closed without merging**
