### PR TITLE
[Merged by Bors] - chore(Analysis/Distribution): move the SchwartzSpace file to a new folder Distribution

### PR DESCRIPTION
**Pull request by sgouezel**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ADedecker** [comment]
maintainer merge
Are you doing this for a particular reason? I'm currently digging up my drafts on (usual) distributions to actually PR them to mathlib, so I hope there's no collision in sight :sweat_smile:

**Comment by sgouezel** [comment]
I need the fact that, if a locally integrable function has vanishing integral against all smooth compactly supported functions, then it is zero almost everywhere (towards Rademacher theorem on ae differentiability of Lipschitz functions). The natural place for the file would be in a distribution folder although this statement does not need the definition of distributions (and hopefully wouldn't overlap with what you are doing).

**Comment by ADedecker** [comment]
No overlap indeed, and I'll be glad if the result is already there when I need it, so that's perfect!

**Comment by ocfnash** [comment]
bors merge

**Pull request closed without merging**
