### PR TITLE
[Merged by Bors] - feat: port Algebra.Homology.Additive

### PR DESCRIPTION
**Pull request by joelriou**
---
- [x] depends on: #3206
- [x] depends on: #3505

(Note: I mistakenly merged this with #3206 and #3505. Then, we should wait these two PRs are merged...)

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3206
* leanprover-community/mathlib4#3505
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by Parcly-Taxel** [comment]
> (Note: I mistakenly merged this with #3206 and #3505. Then, we should wait these two PRs are merged...)

Why not just close this PR, delete the branch and make a new branch/PR with just the `Algebra.Homology.Additive` file?

**Comment by joelriou** [comment]
> Why not just close this PR, delete the branch and make a new branch/PR with just the `Algebra.Homology.Additive` file?

Of course, I could have done this. But #3206 is already ready to merge :) and #3505 is straightforward, so that it is not causing a serious delay anyway.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3206~~
* ~~leanprover-community/mathlib4#3505~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Pull request closed without merging**
