### PR TITLE
[Merged by Bors] - feat(to_additive + Cyclic): auto `cyclic --> addCyclic`

### PR DESCRIPTION
**Pull request by adomani**
Teach the conversion `Cyclic ↦ addCyclic` to `to_additive`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alreadydone** [comment]
Thanks!

maintainer merge

**Comment by RemyDegenne** [comment]
Thanks!
bors r+

**Comment by eric-wieser** [comment]
@adomani, is there a reason you've taken to listing the affected files in the commit message? This is tracked automatically by git, so seems redundant (and therefore at risk of being wrong) to me.

**Comment by adomani** [comment]
Eric, I removed the affected files in this PR.  I have a script that creates the commit message and had it in there.  I'll get rid of it!

**Pull request closed without merging**
