### PR TITLE
[Merged by Bors] - feat: port NumberTheory.Basic

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by LukasMias** [comment]
FYI, `set_option maxHeartbeats 450000` makes this work. 
`set_option trace.Meta.isDefEq true`
and `set_option profiler true` reveal that what takes so long in here are DefEq comparisons between `Semiring.toNonAssocSemiring` and `NonAssocRing.toNonAssocSemiring`, which often has come up together with issue 2074. Maybe this is another example of this?

**Comment by Parcly-Taxel** [comment]
> FYI, `set_option maxHeartbeats 450000` makes this work. `set_option trace.Meta.isDefEq true` and `set_option profiler true` reveal that what takes so long in here are DefEq comparisons between `Semiring.toNonAssocSemiring` and `NonAssocRing.toNonAssocSemiring`, which often has come up together with issue 2074. Maybe this is another example of this?

The proper way is to use type ascriptions. Pinging @j-loreaux for this.

**Comment by jcommelin** [comment]
Could you try disabling the two instances mentioned by Lukas? If you search for "2074" in mathlib4 you will find a lot of examples of how this is done.

**Comment by Parcly-Taxel** [comment]
> Could you try disabling the two instances mentioned by Lukas? If you search for "2074" in mathlib4 you will find a lot of examples of how this is done.

What two instances?

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
