### PR TITLE
[Merged by Bors] - feat: `PosSMulMono ℚ α → PosSMulMono ℚ≥0 α`

### PR DESCRIPTION
**Pull request by YaelDillies**
From LeanAPAP

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by eric-wieser — COMMENTED** [review]
What's the scenario in which these apply?

**Comment by YaelDillies** [comment]
Not entirely clear. I thought I needed these instances, but the ones added in #15328 turned out to be enough for my applications.

**Comment by eric-wieser** [comment]
!bench

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
