### PR TITLE
[Merged by Bors] - chore: Move `RingTheory/NonZeroDivisors` under `Algebra` instead.

### PR DESCRIPTION
**Pull request by erdOne**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
Please move the file to `Algebra/` instead, since I think mixing multiplication and zero places it outside group theory topicwise.

**Comment by erdOne** [comment]
Now that I look at this again, the definition of `nonZeroDivisors` is definitionally equal to `nonZeroDivisorsLeft`. Should we make the former an `abbrev` of the latter? (Or maybe the other way around)

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by jcommelin** [comment]
> Now that I look at this again, the definition of `nonZeroDivisors` is definitionally equal to `nonZeroDivisorsLeft`. Should we make the former an `abbrev` of the latter? (Or maybe the other way around)

Possibly, but in a follow-up PR.

**Pull request closed without merging**
