### PR TITLE
[Merged by Bors] - feat: port Topology.Algebra.ValuedField

### PR DESCRIPTION
**Pull request by ymonbru**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ymonbru** [comment]
I think that i spoted all the syntax errors.
For the remaining, lean is complaining about conversion or being unable to conclude the proof

**Comment by int-y1** [comment]
todo:

* [ ] `valuedCompletion_apply` has a `norm_cast` error

**Comment by jjaassoonn** [comment]
> todo:
> 
> * [ ]  `valuedCompletion_apply` has a `norm_cast` error

I pushed a commit where this `norm_cast` is removed (`Γ₀` can't be coerced into another type). The same treatment is done at `DistribMulActionHom.coe_toLinearMap` in `Algebra.Module.LinearMap.lean`.

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
