### PR TITLE
[Merged by Bors] - feat: port Order.PrimeIdeal

### PR DESCRIPTION
**Pull request by urkud**
---

- [x] depends on: #2351

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2351
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2351~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors d+

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
