### PR TITLE
[Merged by Bors] - feat(RingTheory): the residue field of a prime ideal

### PR DESCRIPTION
**Pull request by erdOne**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by YaelDillies — APPROVED** [review]
This looks good to me. Could a commutative algebraist confirm?

maintainer merge?

**Comment by faenuccio** [comment]
Do you provide an isomorphism between this definition and simply `R/I` (without localizing)? I cannot find it. I am not saying that this should be the approach, but at least having the iso.

**Comment by erdOne** [comment]
@faenuccio We have the `IsFractionRing (R ⧸ I) I.ResidueField` instance. When `I` is maximal we have a field instance on `R ⧸ I` so the isomorphism would come from general machinery about `IsFractionRing`. Or should I restate it here?

**Comment by faenuccio** [comment]
Oh I see, you probably have in mind `ringEquivOfRingEquiv`. In that case I agree it is not needed, perhaps you can add a line of doc close to the instance, pointing to the above `Equiv` in case someone needs it.

**Comment by faenuccio** [comment]
maintainer delegate

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by erdOne** [comment]
@faenuccio I'm not sure if I understand what you meant but I added `Ideal.bijective_algebraMap_quotient_residueField` for maximal ideals and hopefully this is enough?

**Comment by faenuccio** [comment]
> @faenuccio I'm not sure if I understand what you meant but I added `Ideal.bijective_algebraMap_quotient_residueField` for maximal ideals and hopefully this is enough?

Yes, perfect! I think it's perfect to go.

**Comment by riccardobrasca** [comment]
bors merge

**Pull request closed without merging**
