### PR TITLE
feat: port Archive.100-theorems-list.42InverseTriangleSum

### PR DESCRIPTION
**Pull request by int-y1**
---

- [ ] depends on: leanprover-community/mathlib#19195
this took <10s

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by int-y1** [comment]
It looks like Lean 4 doesn't understand `import Archive.100-theorems-list.42InverseTriangleSum`

**Comment by Komyyy** [comment]
I've created the topic.
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Archive.2E100-theorems-list.2EXXTheoremName.20causes.20error.20!4.235114

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib#19195
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib#19195~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by int-y1** [comment]
Might be easier to make a new branch

**Comment by Komyyy** [comment]
mathlib3port is updated.

**Pull request closed without merging**
