### PR TITLE
[Merged by Bors] - feat: port LinearAlgebra.CliffordAlgebra.Even

### PR DESCRIPTION
**Pull request by eric-wieser**
---

- [x] depends on: #5406

[Open in Gitpod](https://gitpod.io/from-referrer/)

Please `rebase -i` this to remove the dependent commits before merging (I will likely not be around to do so)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5406
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5406~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by int-y1** [comment]
1 linter message left:

```
Error: ./Mathlib/LinearAlgebra/CliffordAlgebra/Even.lean:271:1: error: CliffordAlgebra.even.lift_ι.{uR, uM, uA} LINTER FAILED:
simplify fails on left-hand side:
failed to synthesize
  CommMonoid { x // x ∈ CliffordAlgebra.even Q }
(deterministic) timeout at 'typeclass', maximum number of heartbeats (20000) has been reached (use 'set_option synthInstance.maxHeartbeats <num>' to set the limit)
```

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
