### PR TITLE
[Merged by Bors] - feat: orthogonality of Lie algebra root spaces

### PR DESCRIPTION
**Pull request by ocfnash**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by sgouezel** [comment]
Can you fix the build and send it back to bors?
bors d+

**Comment by ocfnash** [comment]
bors merge

**Comment by ocfnash** [comment]
bors merge

**Pull request closed without merging**
