### PR TITLE
[Merged by Bors] - CI: move-decls can be accessed by a comment

### PR DESCRIPTION
**Pull request by adomani**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
move-decls

**Comment by adomani** [comment]
move-decls

**Comment by adomani** [comment]
move-decls

**Comment by adomani** [comment]
move-decls

**Comment by adomani** [comment]
move-decls

**Comment by adomani** [comment]
move-decls

**Comment by adomani** [comment]
move-decls

**Comment by adomani** [comment]
move-decls

**Comment by adomani** [comment]
move-decls

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
