### PR TITLE
[Merged by Bors] - feat: port Data.MvPolynomial.Monad

### PR DESCRIPTION
**Pull request by j-loreaux**
- [x] depends on: #2861 
- [x] depends on: #2886

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2861
* leanprover-community/mathlib4#2886
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
https://github.com/leanprover-community/mathlib/pull/18593 will force us to pause on this one to do Data.MvPolynomial.Variables first.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
