### PR TITLE
[Merged by Bors] - feat: simp config opts in norm_num

### PR DESCRIPTION
**Pull request by digama0**
This adds support for `norm_num (config := ...)`, which just forwards the config args to `simp`. The case of `{decide := false}` came up in https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Prove.20decidable.20statement.20by.20evaluation/near/390390131 .

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by PatrickMassot** [comment]
bors d+

**Comment by collares** [comment]
Some of the examples in https://github.com/leanprover-community/mathlib4/pull/7112/files#diff-203e2e217555b4c41ded98d75664b4ac0f3f19b571ce96bb6f40abfab664566bL338-R358 can be reenabled by passing `config := {decide := true}` now, if desired.

**Pull request closed without merging**
