### PR TITLE
[Merged by Bors] - chore(Data/Nat): split Prime.lean

### PR DESCRIPTION
**Pull request by rwst**
Splitting `Prime.lean` into `Defs`, `Basic`. The split aims at separation of defs and needed lemmas from everything else. With this split 13/18 Mathlib modules no longer import the whole `Prime.lean`. `Prime/Defs.lean` is about half the size.

Motivation is a circular dependency that would prevent me from adding a lemma to `Prime.lean`.

https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/split.20Nat.2FPrime.2Elean

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by rwst** [comment]
The following files now import the shorter Prime/Defs:
```
Mathlib/Tactic/NormNum/Prime.lean
Mathlib/NumberTheory/Primorial.lean
Mathlib/FieldTheory/Tower.lean
Mathlib/Combinatorics/Schnirelmann.lean
Mathlib/Logic/Godel/GodelBetaFunction.lean
Mathlib/Algebra/CharP/Defs.lean
Mathlib/Algebra/CharP/ExpChar.lean
Mathlib/ModelTheory/Algebra/Field/CharP.lean
Mathlib/Data/Nat/Multiplicity.lean
Mathlib/Data/Nat/Prime/Basic.lean
Mathlib/Data/Nat/PrimeNormNum.lean
Mathlib/Data/Num/Prime.lean
Archive/Imo/Imo2008Q3.lean
Archive/Imo/Imo1988Q6.lean
test/slim_check.lean
test/hint.lean
test/rewrites.lean
test/LibrarySearch/basic.lean
```

The follwing files still import the full Prime/Basic (dependency given):
```
Mathlib/Dynamics/PeriodicPts.lean
  l.424: eq_prime_pow_of_dvd_least_prime_pow
Mathlib/Algebra/Order/Floor/Prime.lean
  l.24: exists_prime_mul_pow_lt_factorial
Mathlib/Data/Nat/Choose/Dvd.lean
  l.26,28: dvd_factorial
Mathlib/Data/Nat/Factors.lean
  l.41,62,77,101: factors_lemma
  l.325: eq_two_or_odd
Mathlib/Data/Int/NatPrime.lean
  l.31: succ_dvd_or_succ_dvd_of_succ_sum_dvd_mul
Mathlib/Data/PNat/Prime.lean
  l.153: ne_one
Archive/Imo/Imo1959Q1.lean
  l.37: coprime_of_dvd'
test/observe.lean
  ?
```

**Comment by mattrobball** [comment]
!bench

**Comment by semorrison** [comment]
@mattrobball, this is just noise, right??

If so, I'm happy to proceed.

**Comment by mattrobball** [comment]
Yes, we should crank up the limits for this on the benchmarking server

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
