### PR TITLE
[Merged by Bors] - feat: port FieldTheory.Finiteness

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by Ruben-VandeVelde** [comment]
I guess the conflict would be with #3372.

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
