### PR TITLE
refactor: make `CanonicallyOrdered...` mixin

### PR DESCRIPTION
**Pull request by astrainfinita**
---

Retry #6326

Should we remove `Mathlib.Algebra.Order.Ring.Canonical` from `Mathlib.Algebra.Order.Ring.Nat`?

```
.\.\.\.\Mathlib\Algebra\Order\Ring\Nat.lean:
  remove #[Mathlib.Algebra.Order.Group.Nat, Mathlib.Algebra.Order.Ring.Canonical]
  add #[Mathlib.Algebra.Ring.Parity, Mathlib.Algebra.Order.Ring.Defs]
  instead
    import [Mathlib.Algebra.Order.Sub.Canonical, Mathlib.Algebra.Order.Group.Nat] in Mathlib.Data.Nat.Cast.Order
    import [Mathlib.Algebra.Order.Group.Nat] in Mathlib.Data.Rat.Lemmas
    import [Mathlib.Algebra.Order.Sub.Canonical, Mathlib.Algebra.Order.Group.Nat] in Mathlib.Data.PNat.Basic
    import [Mathlib.Algebra.Order.Sub.Canonical, Mathlib.Algebra.Order.Group.Nat] in Mathlib.Data.Set.Pointwise.Basic
    import [Mathlib.Algebra.Order.Group.Nat] in Mathlib.Data.Nat.GCD.Basic
    import [Mathlib.Algebra.Order.Sub.Canonical, Mathlib.Algebra.Order.Group.Nat] in Mathlib.Data.Nat.SuccPred
    import [Mathlib.Algebra.Order.Ring.Canonical] in Mathlib.SetTheory.Cardinal.Basic
    import [Mathlib.Algebra.Order.Ring.Canonical] in Mathlib.Data.Set.Semiring
    import [Mathlib.Algebra.Order.Sub.Canonical] in Mathlib.Data.Nat.Prime
    import [Mathlib.Algebra.Order.Group.Nat] in Mathlib.Data.Nat.WithBot
    import [Mathlib.Algebra.Order.Group.Nat] in Mathlib.Data.Nat.MaxPowDiv
    import [Mathlib.Algebra.Order.Group.Nat] in Mathlib.Algebra.Tropical.Basic
    import [Mathlib.Algebra.Order.Ring.Canonical] in Mathlib.Combinatorics.SimpleGraph.Regularity.Equitabilise
    import [Mathlib.Algebra.Order.Ring.Canonical, Mathlib.Algebra.Order.Group.Nat] in Mathlib.Combinatorics.SetFamily.HarrisKleitman
    import [Mathlib.Algebra.Order.Sub.Canonical, Mathlib.Algebra.Order.Group.Nat] in Mathlib.Data.Nat.Upto
    import [Mathlib.Algebra.Order.Group.Nat] in Mathlib.Data.Bool.Count
    import [Mathlib.Algebra.Order.Ring.Canonical, Mathlib.Algebra.Order.Group.Nat] in Mathlib.Data.Nat.Dist
    import [Mathlib.Algebra.Order.Group.Nat] in Mathlib.SetTheory.Lists
```

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by negiizhao** [comment]
!bench

**Comment by negiizhao** [comment]
!bench

**Comment by negiizhao** [comment]
!bench

**Comment by grunweg** [comment]
Coming here from PR triage: can you comment on the status of this PR? Is this an experiment, basically not intended to land, or would you like this to get reviewed? In the latter case, please merge master. Thanks!

**Pull request closed without merging**
