### PR TITLE
[Merged by Bors] - perf (Functor.Flat): restructure proof to reduce simp time

### PR DESCRIPTION
**Pull request by mattrobball**
This file recently jumped almost 200% in #8051. Changing a `simpa using X` call into a `convert X <;> simp` cuts the clock time for the file in half.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
bench!

**Comment by mattrobball** [comment]
!bench

**Comment by j-loreaux** [comment]
bors merge

**Comment by mattrobball** [comment]
bors merge-

**Comment by mattrobball** [comment]
Sorry there is a line I commented out that I should either delete or uncomment

**Comment by mattrobball** [comment]
@j-loreaux if you want to pull the trigger again, please do. 🙏

**Comment by j-loreaux** [comment]
bors merge

**Pull request closed without merging**
