### PR TITLE
[Merged by Bors] - chore: reduce imports in 14 files under `GroupTheory`

### PR DESCRIPTION
**Pull request by rwst**
Remove 32 imports from 14 files in `GroupTheory`, as hinted by `#min_imports`

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
These again look like transitive imports, but sure, why not? Thanks!
maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors d+

**Comment by grunweg** [comment]
> Thanks!
> 
> bors d+

(CI already passes here - if you like, you could also `bors merge` right away.)

**Comment by rwst** [comment]
bors merge

**Pull request closed without merging**
