### PR TITLE
[Merged by Bors] - fix: bug fixes to rw?

### PR DESCRIPTION
**Pull request by kim-em**
As reported on [zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/panic.20and.20error.20with.20rw.3F/near/370495531)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alexjbest** [comment]
Are these the same fixes as #5528?

**Comment by semorrison** [comment]
@alexjbest, I think these fixes are slightly better (using telescoping), so I'd prefer to go with this one. I think the tests here cover the new tests in #5528.

Sorry I didn't see it earlier. (My github inbox is out of control and I rely on the #queue.)

**Comment by alexjbest** [comment]
I like the idea of using telescoping, it's much cleaner of course, but manually skipping loose bvars did have a strong motivation. How does your implementation handle expressions with a variable under the binder though, seeing as rw can't handle them returning those matches and trying rw with them won't work as the rw will fail. How about we also try simp_rw and return that as a suggestion too in that case (we will need to check that simp_rw actually did something)

**Comment by fpvandoorn** [comment]
Am I correct that `getSubexpressionMatches` will operate multiple times on identical subexpressions that occur multiple times in `e` (and hence will be exponentially slower than a tactic that would only operate on each subexpression once)? 
If so, maybe there should be a note/todo for that (I don't know a good solution, because `memoFix` doesn't accept monadic operations). I don't know the logic of `rw?` to understand if this is a big performance problem.

In any case, LGTM.

**Comment by semorrison** [comment]
Yes, `getSubexpressionMatches` will not skip repeated subexpressions. I'll add a note.

**Comment by semorrison** [comment]
@alexjbest, I put in some tests to check that at least in limited conditions it can rewrite both in binders and body. However I didn't attempt any cases where `rw` would fail but `simp_rw` would succeed. Let's put that (excellent idea) off for a separate PR, however.

**Comment by kmill** [comment]
I had to convince myself that `getSubexpressionMatches` is OK, but the only issue as far as `rw` goes is that it allows lemmas that might only apply to subexpressions with bound variables. We could be more careful with filtering, but it might not be worth it (who knows, it could be slower overall to do the filtering than have the occasional inapplicable rw lemma). I'm sure there will be future improvements, but for now

bors merge

**Pull request closed without merging**
