### PR TITLE
[Merged by Bors] - fix: typo in polyrith

### PR DESCRIPTION
**Pull request by fpvandoorn**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
Given this mistake slipped in because we decided not to add a test in https://github.com/leanprover-community/mathlib4/pull/12285, can you add a test now?

bors d+

**Comment by bustercopley** [comment]
> Given this mistake slipped in because we decided not to add a test in #12285, can you add a test now?
> 
> bors d+

Should we run that past the kind people at Sagecell first? Queries from mathlib CI might outnumber genuine interactive calls.

**Comment by eric-wieser** [comment]
Ideally we can write a test that doesn't hit the server, but maybe that's not possible here.

**Comment by fpvandoorn** [comment]
I haven't looked at the Lean 3 testing framework for polyrith, I don't have time to invest in figuring that out, and I don't want every little commit here to make 10+ calls to the Sage API.

I think we shouldn't hold up bugfixes until someone writes proper tests for polyrith. Suffices to say that I tested it locally on my machine.

bors merge

**Pull request closed without merging**
