### PR TITLE
[Merged by Bors] - chore(Data/List/Func): Delete

### PR DESCRIPTION
**Pull request by YaelDillies**
This file was used in the Lean 3 implementation of `omega` and nowhere else. It's mathematically redundant with `Data.List.ToFinsupp`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Parcly-Taxel** [comment]
How about you combine this with #11846?

**Comment by YaelDillies** [comment]
The reasons to delete the two files are different, so are the possible objections. Hence I prefer having two PRs.

**Comment by fpvandoorn** [comment]
LGTM

It's easy to get it back if we miss it.

**Comment by fpvandoorn** [comment]
bors merge

**Pull request closed without merging**
