### PR TITLE
[Merged by Bors] - refactor: Generalise ordered field lemmas to ordered groups with zero

### PR DESCRIPTION
**Pull request by YaelDillies**
Also generalise `LinearOrderedCommGroupWithZero`  lemmas, add a few missing ones and unify the names.

Note that this doesn't generalise all eligible lemmas as there are too many for a single PR.

Unify:
* `le_div_iff` → `le_div_iff₀`
* `le_div_iff'` → `le_div_iff₀'`
* `div_le_iff` → `div_le_iff₀`
* `div_le_iff'` → `div_le_iff₀'`
* `mul_le_one₀` → `mul_le_one'`
* `one_le_mul₀` → `one_le_mul'`

From LeanAPAP

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
I see that you rename some lemmas. Please describe the API changes in the commit message.

**Comment by urkud** [comment]
!bench

**Comment by jcommelin** [comment]
bors d+

**Comment by YaelDillies** [comment]
Nothing in the bors backlog right now. Let's try

bors merge

**Pull request closed without merging**
