### PR TITLE
[Merged by Bors] - docs(Archive/IMO/2011Q5): replace non-Lean notation in comment

### PR DESCRIPTION
**Pull request by madvorak**
Use `f n` instead of `f(n)` for function application.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by vihdzp** [comment]
This isn't Lean 3 notation, it's just mathematical plaintext. I think either way to write this down is fine.

**Comment by madvorak** [comment]
> This isn't Lean 3 notation, it's just mathematical plaintext.

Yeah. In either case, we can do better.

**Comment by urkud** [comment]
@madvorak I edited the title and the commit message. Feel free to revert or edit otherwise.
bors d+
@vihdzp I think that plain text math notation should be in `$$`s, not in `` ` ``s.

**Pull request closed without merging**
