### PR TITLE
[Merged by Bors] - chore(RingTheory/Polynomial): rename `frange` to `coeffs`

### PR DESCRIPTION
**Pull request by chrisflav**
Renames `Polynomial.frange` to `Polynomial.coeffs`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by chrisflav** [comment]
> Can you motivate this renaming by comparing with other parts of the library? Or is it simply a personal preference?

I find `coeffs` more telling than `frange` and it was suggested here:
https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/Ring.20of.20definition/near/437593971

**Comment by faenuccio** [comment]
> > Can you motivate this renaming by comparing with other parts of the library? Or is it simply a personal preference?
> 
> I find `coeffs` more telling than `frange` and it was suggested here: https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/Ring.20of.20definition/near/437593971

Oh perfect, I had not followed that chat. Perfect, then!

**Comment by jcommelin** [comment]
@chrisflav Could you please add a `deprecated alias` for the old names? (And please use the new `since` feature of `deprecated`.
So something like
```
@[deprecated (since := "2024-05-07")] alias zpow_ne_zero_of_ne_zero := zpow_ne_zero
```

Otherwise, LGTM. And thanks for doing this.

bors d+

**Comment by chrisflav** [comment]
Thanks for the reviews!

**Pull request closed without merging**
