### PR TITLE
[Merged by Bors] - chore: move differentiability of Gamma to a new file

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
This PR is technically fine (only code motion etc.) - but can you say something about its motivation?

**Comment by Ruben-VandeVelde** [comment]
!bench

**Comment by Ruben-VandeVelde** [comment]
This removes the `Mathlib.Analysis.MellinTransform` from the longest pole:
```diff
-Analyzing Mathlib at 765ccc9135f3ebeec047798d6c715dc3224c0c73
+Analyzing Mathlib at c475f01b6fa5491e2fd05efe4538ac187ac42b52
 | file                                                           | instructions | cumulative | parallelism |
 | :------------------------------------------------------------- | -----------: | ---------: | :---------: |
-| Mathlib                                                        |        10702 |    6307863 |    20.28    |
+| Mathlib                                                        |        10703 |    6266221 |    20.42    |
-| Mathlib.NumberTheory.FLT.Three                                 |       127311 |    6297161 |    8.62     |
+| Mathlib.NumberTheory.FLT.Three                                 |       127309 |    6255518 |    8.68     |
-| Mathlib.NumberTheory.Cyclotomic.Three                          |        46071 |    6169850 |    8.74     |
+| Mathlib.NumberTheory.Cyclotomic.Three                          |        46070 |    6128208 |    8.80     |
-| Mathlib.NumberTheory.Cyclotomic.Rat                            |       119318 |    6123779 |    8.75     |
+| Mathlib.NumberTheory.Cyclotomic.Rat                            |       119325 |    6082137 |    8.81     |
-| Mathlib.NumberTheory.Cyclotomic.Discriminant                   |        41521 |    6004461 |    8.90     |
+| Mathlib.NumberTheory.Cyclotomic.Discriminant                   |        41523 |    5962812 |    8.96     |
-| Mathlib.NumberTheory.NumberField.Discriminant                  |       205644 |    5962939 |    8.77     |
+| Mathlib.NumberTheory.NumberField.Discriminant                  |       205636 |    5921289 |    8.83     |
-| Mathlib.NumberTheory.NumberField.CanonicalEmbedding.ConvexBody |       162411 |    5757295 |    9.02     |
+| Mathlib.NumberTheory.NumberField.CanonicalEmbedding.ConvexBody |       162404 |    5715652 |    9.09     |
-| Mathlib.MeasureTheory.Measure.Lebesgue.VolumeOfBalls           |        69491 |    5594883 |    7.42     |
+| Mathlib.MeasureTheory.Measure.Lebesgue.VolumeOfBalls           |        69494 |    5553248 |    7.47     |
-| Mathlib.Analysis.SpecialFunctions.Gamma.BohrMollerup           |        36353 |    5525392 |    7.48     |
+| Mathlib.Analysis.SpecialFunctions.Gamma.BohrMollerup           |        36373 |    5483753 |    7.54     |
-| Mathlib.Analysis.SpecialFunctions.Gaussian.GaussianIntegral    |        41091 |    5489038 |    7.52     |
+| Mathlib.Analysis.SpecialFunctions.Gaussian.GaussianIntegral    |        40976 |    5447380 |    7.56     |
-| Mathlib.Analysis.SpecialFunctions.Gamma.Basic                  |        41453 |    5447947 |    7.56     |
-| Mathlib.Analysis.MellinTransform                               |        36686 |    5406493 |    7.61     |
+| Mathlib.Analysis.SpecialFunctions.Gamma.Basic                  |        36497 |    5406403 |    7.60     |
 | Mathlib.Analysis.SpecialFunctions.ImproperIntegrals            |        15728 |    536980_ |    7.64     |
```

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Pull request closed without merging**
