### PR TITLE
feat: port CategoryTheory.Additive.Basic

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by Parcly-Taxel** [comment]
The problem with simpNF appears to be https://github.com/leanprover/lean4/issues/2055; cf. #2769

**Comment by semorrison** [comment]
I'm going to remove `awaiting-review` and add `blocked-by-core-PR`, as it seems we won't be able to merge this until there's a fix for https://github.com/leanprover/lean4/issues/2055. If you think of a way around this, please feel free to update the labels.

**Pull request closed without merging**
