### PR TITLE
[Merged by Bors] - refactor: decapitalize names in `@[mk_iff]`

### PR DESCRIPTION
**Pull request by urkud**
* `@[mk_iff] class MyPred` now generates `myPred_iff`, not `MyPred_iff`
* add `Lean.Name.decapitalize`
* fix indentation and a few typos in the docs/comments.

Partially addresses issue #9129

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by alreadydone — APPROVED** [review]
I'm not qualified to review the [meta](https://github.com/leanprover-community/mathlib4/pull/9378/files#diff-8e7360645fce8f987e04fca15b59837daba20f6a4b8a24b0629b472f06f7d85e) [code](https://github.com/leanprover-community/mathlib4/pull/9378/files#diff-95f806a8cd7b480ba988c9b6bd65705f9162b734691b7cedf67ec4ee7d5d6c78), but the rest look great!

(The essential change in the second file is probably just this [one line](https://github.com/leanprover-community/mathlib4/pull/9378/files#diff-95f806a8cd7b480ba988c9b6bd65705f9162b734691b7cedf67ec4ee7d5d6c78R411) though, and the big diffs are just indentation fixes.)

**Comment by alreadydone** [comment]
maintainer merge

**Review by jcommelin — APPROVED** [review]
Thanks :tada: 

If CI passes, please remove the label `awaiting-CI` and merge this yourself, by adding a comment `bors r+`.

bors d+

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
