### PR TITLE
[Merged by Bors] - chore: Remove `generalize'`

### PR DESCRIPTION
**Pull request by erdOne**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
Shall we remove `generalize'` altogether?

**Comment by Parcly-Taxel** [comment]
> Shall we remove `generalize'` altogether?

Yes.

**Comment by j-loreaux** [comment]
I'm okay with this, but it's not really solving the problem, just sidestepping it.

maintainer merge

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
