### PR TITLE
[Merged by Bors] - feat: add `mul_self_tsub_mul_self`

### PR DESCRIPTION
**Pull request by eric-wieser**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by YaelDillies** [comment]
Can we have `a ^ n - b ^ n = (a - b) ...`?

**Comment by eric-wieser** [comment]
I guess you mean [`geom_sum₂_mul`](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Algebra/GeomSum.html#geom_sum%E2%82%82_mul)? That sounds like a nice puzzle for a future PR

**Review by YaelDillies — COMMENTED** [review]
Okay then

maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by eric-wieser** [comment]
bors merge

**Pull request closed without merging**
