### PR TITLE
[Merged by Bors] - feat: port RingTheory.WittVector.Verschiebung

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
This is missing the `ghostCalc`  tactic, I suppose. Should we wait for that to be ported or workaround?
Any thoughts, @jcommelin?

**Comment by jcommelin** [comment]
I'm excited that this is now working. Basically ready to go, I think.

```
ghost_calc _ _; -- FIXME without the semicolon, ghost_calc eats the next tactic
```
It would be good if we can fix this.

**Comment by semorrison** [comment]
@jcommelin, fixed the semicolon issue. There are two places I added FIXMEs where the comments need rewriting. Could you generally read through all the comments and make sure they reflect the new tactic design?

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
