### PR TITLE
[Merged by Bors] - chore: add test file to import everything

### PR DESCRIPTION
**Pull request by kim-em**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Good idea! (Out of curiosity: were there any bugs in the past caught by this? Or is this just a precaution?)

As a follow-up, would you like to ensure this stays in sync with the lakefile, somehow - or is that an unimportant concern? Feel free to maintainer merge on my behalf once you thought about this.

**Review by grunweg — APPROVED** [review]

**Comment by semorrison** [comment]
Yes, it would be nice to stay in sync, but I coudn't think of an easy way to do this --- we don't want to simply scrape the manifest, because some dependencies (e.g. `Cli` and `ImportGraph`) are not used in Mathlib proper so may not have been built by the time the test runs.

I think that dependencies change slowly enough, and the test is not critical, that we can hope for the best here, at least for now.

**Comment by grunweg** [comment]
Sounds reasonable - so let me
maintainer merge

**Comment by j-loreaux** [comment]
bors merge

**Pull request closed without merging**
