### PR TITLE
feat: add constructive version of CategoryTheory.Zigzag

### PR DESCRIPTION
**Pull request by sven-manthe**
Since Zigzag is the more appropriate name for the new concept and not for the old one (which is its propositional truncation), I renamed the old one to Zigzagable. I intend to use this for a proof that the colimit of a functor mapping all morphisms to isomorphisms with filtered domain exists (and is trivial).
Taken from https://github.com/sven-manthe/A-formalization-of-Borel-determinacy-in-Lean

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by joelriou** [comment]
I must say I am not very enthousiastic about the name change. Instead, given a category `C`, I would suggest defining a quiver "ZigzagQuiv C" (which should be `LocQuiver W` from `CategoryTheory.Localization.Construction` for the class of morphisms `W := ⊤`), and then considering the path category of this quiver. It would be even better to improve this `LocQuiver`/path category API for a general class of morphisms `W`.

The application you suggest may probably be interpreted in terms of the localization of categories API, as a functor `F : J ⥤ C` which maps all morphisms to isomorphisms factors through the localization `J[W^{-1}]` with `W :=⊤` and it seems that what you want to show is that the category `J[W^{-1}]` is equivalent to the punctual category, and then `F` is isomorphic to a constant functor, etc.

Actually, I have a stronger version of the dual statement in this file https://github.com/leanprover-community/mathlib4/blob/jriou_localization/Mathlib/CategoryTheory/Limits/Constructions/EventuallyConstant.lean
If a functor `F : J ⥤ C` from a cofiltered category is "eventually constant" (some suitable transition maps are isomorphisms), then `F` has a limit. If your work only need this result, I may PR it to mathlib (I will need it anyway for some applications to homology).

**Comment by sven-manthe** [comment]
> Actually, I have a stronger version of the dual statement in this file https://github.com/leanprover-community/mathlib4/blob/jriou_localization/Mathlib/CategoryTheory/Limits/Constructions/EventuallyConstant.lean If a functor `F : J ⥤ C` from a cofiltered category is "eventually constant" (some suitable transition maps are isomorphisms), then `F` has a limit. If your work only need this result, I may PR it to mathlib (I will need it anyway for some applications to homology).

The result I need is: If F is a functor from the dual order of naturals to a category (say with small limits) such that all transitions maps are mapped to isomorphisms, then the projection lim F -> F 0 is an isomorphism. If I see this correctly, you proved this, so I'd be happly if you PR'ed your result.

**Comment by sven-manthe** [comment]
Probably, then I'll just close this PR. When doing the namespace, I underestimated how often the old definition was used, and my code here was written almost one year ago when I learned Lean. Back then, I also didn't find the results on localization in mathlib that allow the more conceptual proof you sketched and so did this in a rather brute-force way.

**Comment by sven-manthe** [comment]
I just separated https://github.com/leanprover-community/mathlib4/pull/19017 and will close this PR after the discussion finished. (If you don't manage to PR your result during the next few months, I'll probably use the localization argument you suggested.)

**Comment by joelriou** [comment]
This is #19021

**Comment by sven-manthe** [comment]
Thank you!

**Pull request closed without merging**
