### PR TITLE
[Merged by Bors] - feat(Condensed): a sequential limit of epimorphisms in light condensed modules is epimorphic

### PR DESCRIPTION
**Pull request by dagurtomas**
This is deduced from the more general statement about morphisms in the category of sheaves for the coherent topology on a preregular extensive category. 

This will eventually be used to prove that the category of light condensed modules has countable AB4*, see #18497 (WIP).

---

- [x] depends on: #18186
- [x] depends on: #18185 
- [x] depends on: #18325  

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by dagurtomas** [comment]
Working on a slightly different statement needed for #18497

**Review by riccardobrasca — APPROVED** [review]
"on a preregular finitary extensive concrete category where the effective
epimorphisms are precisely the surjective ones" this is starting to look like a joke :D

Anyway LGTM, thanks!

**Comment by dagurtomas** [comment]
A cleaner condition would probably be to drop the concreteness and surjectivity assumption and just require that a sequential limit of effective epimorphisms is effective epi. I'll change it now so please don't merge yet.

**Comment by dagurtomas** [comment]
Ok, now it's "on a preregular finitary extensive category where sequential limits of effective epimorphisms are effective epimorphisms" :D

**Comment by riccardobrasca** [comment]
bors d+

**Comment by dagurtomas** [comment]
Thanks! 

bors merge

**Pull request closed without merging**
