### PR TITLE
[Merged by Bors] - chore(SetTheory/Ordinal/Basic): `Ordinal.NeZero.One` → `Ordinal.instNeZeroOne`

### PR DESCRIPTION
**Pull request by vihdzp**
---

Should other instances like `Ordinal.zeroLEOneClass` or `Ordinal.orderBot` also be renamed?

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
Yes, feel free to do the others as well. 

maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by TwoFX** [comment]
bors d+

**Comment by vihdzp** [comment]
Added a couple more analogous renames.

bors r+

**Pull request closed without merging**
