### PR TITLE
[Merged by Bors] - fix: remove stale comment

### PR DESCRIPTION
**Pull request by kbuzzard**
---

When ported, two lines in this file looked like
```lean
-- Syntactic tautology
#noalign lie_submodule.to_submodule_eq_coe
```

and then a year later we deleted the `#noalign` line, leaving a stale comment about nothing.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by pitmonticone** [comment]
maintainer merge

**Comment by jcommelin** [comment]
Good catch! I think there are a few more examples in mathlib. Would you mind hunting them down with `git grep -i "syntactic tautology"` so that we can remove all of them in one go?

**Comment by pitmonticone** [comment]
@kbuzzard I should have caught all of those comments mentioned by Johan. May I push directly here for efficiency?

**Comment by j-loreaux** [comment]
@pitmonticone I'll answer for Kevin, as I don't imagine I'll be stepping on his toes: sure. Thanks.

**Comment by kbuzzard** [comment]
It's a bit weird reviewing my own PR but I just checked the other instances which Pietro has caught and they look good to me!

**Comment by j-loreaux** [comment]
bors merge

**Pull request closed without merging**
