### PR TITLE
[Merged by Bors] - chore: move `#help` to Batteries (batteries#969)

### PR DESCRIPTION
**Pull request by fgdorais**
---

Once [batteries#969](https://github.com/leanprover-community/batteries/pull/969) is merged:
- [x] Edit lakefile to point batteries back to main
- [x] Run `lake update batteries`
- [x] Merge

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by fgdorais** [comment]
@kim-em We added `#help` to batteries but we forgot to delete it from Mathlib. This PR completes the task.

**Comment by kim-em** [comment]
Please merge after the Batteries PR.

bors d+

**Comment by grunweg** [comment]
Friendly ping from your local review triage. This PR looks great, is there anything else needed to merge it?

**Pull request closed without merging**
