### PR TITLE
[Merged by Bors] - chore (abel): abel shouldn't depend on ordered algebra

### PR DESCRIPTION
**Pull request by mattrobball**
If we change the import from `NormNum` to `NormNum.Basic`, we avoid some annoying dependecies.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by grunweg** [comment]
Seems reasonable, thanks!
maintainer merge

**Comment by j-loreaux** [comment]
bors merge

**Comment by YaelDillies** [comment]
Hah! That's great. I complained about this on Zulip two months ago.

**Pull request closed without merging**
