### PR TITLE
[Merged by Bors] - refactor(Algebra/Category): replace `TypeMax` constructions by `UnivLE` assumptions

### PR DESCRIPTION
**Pull request by chrisflav**
Replaces `TypeMax` limit constructions in `MonCat`, `GroupCat`, `Ring`, `AlgebraCat` and `ModuleCat` by the `UnivLE` analogs. Also generalizes some universe assumptions.

---

- [x] depends on: #11419

Note that the `MonCatMax` etc. `abbrev`s are kept for the time being, since they are still used in some other files (mostly the corresponding colimit files). Entirely getting rid of `MonCatMax` and friends remains a TODO to not make the diff even bigger.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by joelriou** [comment]
Since #11487 and #11148 we know that the limit of a functor to types `F` exists iff `Small F.sections`. Then, it should be possible to show existence of limits in other concrete categories under the weaker assumption that this smallness property holds for the functor obtained by composition with the forget functor. Do you think your PR could be generalized accordingly? (I am referring to limits only, not colimits.)

(In future PRs, we may even add that a limit in the category of rings (for example) exists iff it exists after applying the forget functor. Then, it would be possible to show that these forget functor commute to all limits, without any restriction on universes. This would be convenient in the development of API for (pre)sheaves of modules.)

**Comment by chrisflav** [comment]
> Since #11487 and #11148 we know that the limit of a functor to types `F` exists iff `Small F.sections`. Then, it should be possible to show existence of limits in other concrete categories under the weaker assumption that this smallness property holds for the functor obtained by composition with the forget functor. Do you think your PR could be generalized accordingly? (I am referring to limits only, not colimits.)

See the latest commit.

**Comment by joelriou** [comment]
Thanks for this effort!

bors merge

**Comment by chrisflav** [comment]
Thanks for the review!

**Pull request closed without merging**
