### PR TITLE
perf: Use preferred parents in ring transfer definitions

### PR DESCRIPTION
**Pull request by YaelDillies**
Make sure that `Function.Injective.somethingRing` looks like
```
def ... : SomethingRing β :=
  { hf.a f ...,
    hf.b f ...,
    hf.c f ... with }
```
  if `SomethingRing α extends A α, B α, C α`.

This should hopefully give a performance boost in applications.

Incidentally, there were a few missing transfer definitions, so I added them as I needed them.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by YaelDillies** [comment]
!bench

**Review by mattrobball — CHANGES_REQUESTED** [review]
It would nice to split out the changes into two steps:
- Add the preferred parents where they are not and add any intermediate instances necessary
- Use the spread style. 

This would give a better sense of the benefits of the first part.

**Comment by YaelDillies** [comment]
I'm thinking what I'm doing here is automatable. Do you think we should have a `mk_inj_surj` attribute (similar to `mk_iff`) which automatically generates those definitions?

**Comment by mattrobball** [comment]
> I'm thinking what I'm doing here is automatable. Do you think we should have a `mk_inj_surj` attribute (similar to `mk_iff`) which automatically generates those definitions?

I think this is a good idea in general. There is currently a good deal of boilerplate when applying these `fun _ _ _ _ => rfl` etc

**Comment by mattrobball** [comment]
[Here](http://speed.lean-fro.org/mathlib4/compare/e7b27246-a3e6-496a-b552-ff4b45c7236e/to/3a1d2b9e-6a14-4d55-8c6e-12f8710c3feb?hash1=999e59b2453250ade57b45bd1d8eba7ae5f9216c) is a reasonable comparison I think

**Comment by YaelDillies** [comment]
Split off #10131.

!bench

**Comment by YaelDillies** [comment]
@mattrobball, do the fails here convince you to go ahead directly with #10131 ?

**Comment by mattrobball** [comment]
Sorry for the late response. Let's wait a day or two until v4.6-rc1 lands. 

Ultimately just the systemization of the instance construction and declaration patterns is sufficient to motivate the change. 

I just want to make sure that nothing surprising happens.

**Comment by YaelDillies** [comment]
Indeed, the performance issues have disappeared. @mattrobball, the ball is on your side.

**Comment by YaelDillies** [comment]
!bench

**Comment by mattrobball** [comment]
Hmm. Might be good to bench the whole thing again. Once the bot catches back up.

**Comment by YaelDillies** [comment]
What do you mean? Are you saying the results above are inaccurate?

**Comment by YaelDillies** [comment]
Closing now that #10131 has been merged.

**Pull request closed without merging**
