### PR TITLE
[Merged by Bors] - feat: `extract_lets` tactic 

### PR DESCRIPTION
**Pull request by kmill**
This tactic is for taking `let` bindings in the local context and "intro-ing" these bindings. It is like a `cases` tactic for `let` bindings. It can be used like `extract_lets x y at h` or `extract_lets at h` using `intros`-like identifier lists.  It also supports `extract_lets at *`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by digama0** [comment]
I think it should not be called `intro`, you can't intro a hypothesis and this seems like a teaching hurdle. I would suggest something more descriptive like `intro_lets at h`.

**Comment by kmill** [comment]
@digama0 New name: `extract_lets`, and I made use `intros`-like identifier list handling, which makes `extract_lets at *` more useful.

**Comment by semorrison** [comment]
Do you want to import it in `Mathlib.Tactic.Common`? (I think everything without theory dependencies should be there.)

bors d+

**Comment by kmill** [comment]
bors merge

**Pull request closed without merging**
