### PR TITLE
[Merged by Bors] - chore: fix #minimize_imports

### PR DESCRIPTION
**Pull request by kim-em**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
I found something that seems strange.  If I save a new file with this
```lean
import Mathlib.RingTheory.Nilpotent

lemma IsNilpotent.prod {A B : Type*} [MonoidWithZero A] [MonoidWithZero B]
    {a : A} {b : B} (ha : IsNilpotent a) (hb : IsNilpotent b) :
    IsNilpotent (a, b) := by
  rcases ha with ⟨m, _⟩
  rcases hb with ⟨n, _⟩
  use max m n
  simpa only [Prod.pow_mk, Prod.mk_eq_zero] using
    ⟨pow_eq_zero_of_le (m.le_max_left n) ‹_›, pow_eq_zero_of_le (m.le_max_right n) ‹_›⟩

#find_home IsNilpotent.prod
```
the final `#find_home` tells me to place this lemma in the current file.  However, there is a single import and placing the lemma at the end of `Mathlib.RingTheory.Nilpotent` of course works.  I have not debugged the cause of this, though.

**Comment by adomani** [comment]
Ok, maybe the issue above is related to this one and is therefore not really an issue with `#find_home`:
```lean
import Mathlib.Data.Nat.Basic
import Mathlib.Util.Imports

theorem add_zero' {n : Nat} : n + 0 = n := by
  simp [Nat.add_zero]

theorem add_zero'' {n : Nat} : n + 0 = n := by
  simp only [Nat.add_zero]

#print add_zero'  -- uses `add_zero` and hence pulls instances from `Mathlib.Data.Nat.Basic`
#print add_zero'' -- essentially uses `rfl`

#find_home add_zero'  -- `Mathlib.Data.Nat.Basic`
#find_home add_zero'' -- `Lean.Data.Parsec` and several others
```

**Comment by adomani** [comment]
Besides the experiment above, that seems unrelated to `#find_home`, the changes look good to me!

It seems that sometimes, `simp` inserts "equation-like lemmas" that it creates in the current file and this blindsides `#find_home`.  Here is an extension of the comment with an example of this behaviour.

```lean
import Mathlib.RingTheory.Nilpotent

lemma IsNilpotent.prod {A B : Type*} [MonoidWithZero A] [MonoidWithZero B]
    {a : A} {b : B} (ha : IsNilpotent a) (hb : IsNilpotent b) :
    IsNilpotent (a, b) := by
  rcases ha with ⟨m, _⟩
  rcases hb with ⟨n, _⟩
  use max m n
  simpa only [Prod.pow_mk, Prod.mk_eq_zero] using
    ⟨pow_eq_zero_of_le (m.le_max_left n) ‹_›, pow_eq_zero_of_le (m.le_max_right n) ‹_›⟩

lemma IsNilpotent.prod' {A B : Type} [MonoidWithZero A] [MonoidWithZero B]
    {a : A} {b : B} (ha : IsNilpotent a) (hb : IsNilpotent b) :
    IsNilpotent (a, b) := by
  rcases ha with ⟨m, _⟩
  rcases hb with ⟨n, _⟩
  use max m n
  rw [Prod.pow_mk, Prod.mk_eq_zero]
  exact ⟨pow_eq_zero_of_le (m.le_max_left n) ‹_›, pow_eq_zero_of_le (m.le_max_right n) ‹_›⟩

#find_home IsNilpotent.prod  -- `Mathlib.Algebra.NewFile`
#find_home IsNilpotent.prod' -- `Mathlib.RingTheory.Nilpotent`

#print IsNilpotent.prod  --  blah blah `Mathlib.Algebra.NewFile._auxLemma.1`
#print IsNilpotent.prod' --  only results in `Mathlib.RingTheory.Nilpotent` or earlier
```

**Comment by adomani** [comment]
Also, I realize now `#find_home` is completely unaffected by the change in this PR.  So, it seems that I took this PR as an excuse to understand a weird behaviour of an unrelated function!  :facepalm:

**Comment by adomani** [comment]
Would it be a good idea to remove the current file also in `#find_home`?  I am suggesting this, since the example above shows that certain lemmas are autogenerated in the current file, but would have been auto-generated in whichever file the lemma was used.  Maybe having a `#find_home!` option that always removes the current file and `#find_home` that is unchanged?

Here is a concrete suggestion:
```lean
-- change the beginning of `Lean.Name.findHome` to
def Lean.Name.findHome (n : Name) (env : Option Environment) : CoreM NameSet := do
  let current? := match env with | some env => env.header.mainModule | _ => default
  let required := (← n.requiredModules).toArray.erase current?
  ...

-- and then `#find_home` to
elab "#find_home" bang:"!"? n:ident : command => do
  let n ← resolveGlobalConstNoOverloadWithInfo n
  let env := if bang.isSome then some (← getEnv) else none
  for i in (← Elab.Command.liftCoreM do n.findHome env) do
    logInfo i
```

In easy to paste format:
```lean
def Lean.Name.findHome (n : Name) (env : Option Environment) : CoreM NameSet := do
  let current? := match env with | some env => env.header.mainModule | _ => default
  let required := (← n.requiredModules).toArray.erase current?
  let imports := (← getEnv).importGraph.transitiveClosure
  let mut candidates : NameSet := {}
  for (n, i) in imports do
    if required.all fun r => n == r || i.contains r then
      candidates := candidates.insert n
  for c in candidates do
    for i in candidates do
      if imports.find? i |>.getD {} |>.contains c then
        candidates := candidates.erase i
  return candidates

open Elab in
/--
Find locations as high as possible in the import hierarchy
where the named declaration could live.
Using `#find_home!` will forcefully remove the current file.
-/
elab "#find_home" bang:"!"? n:ident : command => do
  let n ← resolveGlobalConstNoOverloadWithInfo n
  let env := if bang.isSome then some (← getEnv) else none
  for i in (← Elab.Command.liftCoreM do n.findHome env) do
    logInfo i
```

**Comment by semorrison** [comment]
@adomani, could we maybe do this discussion of `#find_home` elsewhere? It's related to this PR as far as I can see.

**Comment by adomani** [comment]
You are right: new PR at #7075!  I will remove the clutter from this one.

**Comment by adomani** [comment]
LGTM!  :smile:

**Comment by Vierkantor** [comment]
Thanks!

For posterity, the fix is discussed in this Zulip thread: https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/bug.20in.20.23minimize_imports.2C.20vs.2E.20.20.23redundant_imports

bors r+

**Pull request closed without merging**
