### PR TITLE
feat: add `rw_equiv` tactic

### PR DESCRIPTION
**Pull request by alexkeizer**
Given an equivalence `eqv : α ≃ β`, the `rw_equiv` tactic rewrites the type of variables `x : α` in the local context to `x : β`.
The tactic performs roughly the following steps:
  * rewrite `x` to `eqv.invFun (eqv.toFun x)`
  * `generalize eqv.toFun x = x`
  * Clear the original, now-shadowed, declaration of `x` from the context

---

I've been in a few discussions over the past weeks centred on the question whether representation Foo or Bar is more appropriate for some type, where Foo and Bar are equivalent types.

This tactic aims to make that choice less important, by making it easier to context switch between a goal stated in terms of `Foo` to a goal in terms of `Bar`.

The current PR only adds a tactic to change the type of variable in the context, but I also intend to develop a slightly more advanced `simp_equiv` tactic in a subsequent PR, which will allow us to register structure-preservation lemmas along the line of the following
```lean
def Foo.ofBar : Foo -> Bar
  := sorry

def Foo.add : Foo -> Foo -> Foo
  := sorry

def Bar.add : Bar -> Bar-> Bar
  := sorry

@[simp_equiv] -- register the following theorem as "structure-preservation" simp-lemma
theorem Foo.add_ofBar (x y : Bar) :
  add (ofBar x) (ofBar y) = ofBar (Bar.add x y)
```

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
Perhaps add a link to the original `equiv_rw` in mathlib3, in case someone wants to port the additional functionality later?

**Comment by semorrison** [comment]
(Possibly we could also rename to `equiv_rw` for continuity?)

**Comment by alexkeizer** [comment]
That makes sense, I did not know about `equiv_rw`. I'll have a look, and see if I can reuse some of the ideas there

**Comment by alexkeizer** [comment]
I see that `equiv_rw` uses the coercion from `eqv.symm : \b \equiv \a` to a function `\b -> \a`, instead of directly using `eqv.invFun` like I did. Do you reckon I should change the PR to follow that, to be consistent?

**Pull request closed without merging**
