### PR TITLE
[Merged by Bors] - chore: benchmark userspace instructions only per file

### PR DESCRIPTION
**Pull request by Kha**
This should make the metric even more deterministic, which is its primary purpose

### CODE REVIEW

**Comment by Kha** [comment]
!bench

**Comment by Kha** [comment]
@digama0 You might be interested in this given our recent discussion on Zulip. Locally I saw stddev fall to ~1/10 from this. I think this is the best compromise between determinism and wall-time approximation we can get with a metric for files (and we don't want to add another metric to all 4000 files). Impact seems to be between -0.1% and -30% instructions depending on the file complexity, i.e. smaller files spend more instructions in the kernel relatively speaking.

**Comment by Kha** [comment]
!bench

**Comment by Kha** [comment]
Results look good to me: we usually have ~10 or more files with more than 0.5% change, now it's 2: http://speed.lean-fro.org/mathlib4/run-detail/e7b27246-a3e6-496a-b552-ff4b45c7236e/9ece728c2d37c4eb29e68e734794a311ec9f77b2. It would probably make sense to use instructions:u everywhere then.

**Review by Kha — COMMENTED** [review]
Measure userspace instructions everywhere

**Comment by Kha** [comment]
!bench

**Comment by mattrobball** [comment]
Let's try this out. 

bors delegate+

**Pull request closed without merging**
