### PR TITLE
[Merged by Bors] - feat: port Analysis.Fourier.RiemannLebesgueLemma

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
I think just one more error in `tendsto_integral_exp_smul_cocompact`, but I'm failing to see where it goes wrong.

**Comment by dupuisf** [comment]
Can you run the comment-fixing script?

**Comment by Ruben-VandeVelde** [comment]
Done, thanks for the reminder

**Review by dupuisf — COMMENTED** [review]
Thanks!

bors r+

**Pull request closed without merging**
