### PR TITLE
[Merged by Bors] - feat: port RingTheory.AdjoinRoot

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

TODO:

* lots of timeouts, particularly around `induction_on`
* `Ideal.Quotient.mk` no longer works as dot notation

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
@Ruben-VandeVelde, I had also started porting this file.  I made some progress on the inductions by giving the explicit `C` field: should I push to this branch?

**Comment by adomani** [comment]
Removing `elab_as_elim` helps Lean, a little, to figure out what `C` is.  This example:
```lean
example {x : AdjoinRoot f} : x = x := by
  apply induction_on _ x
  intro x
  rfl
```
fails if you put `elab_as_elim` back.

**Comment by riccardobrasca** [comment]
I've fixed the two sorry. No idea why the mathlib3 proof stopped working.

**Comment by adomani** [comment]
@riccardobrasca, thank you very much for the fixes and the speed ups!  The original file was also slow, although the speed issue is mitigated by the parallel evaluation of the declarations.

I added a porting note on the splitting.  LGTM!  (Although I have been involved quite a bit in the porting process!)

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
