### PR TITLE
[Merged by Bors] - feat: port Data.Matrix.Invertible

### PR DESCRIPTION
**Pull request by xroblot**
---

- [x] depends on: #5369 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Parcly-Taxel** [comment]
Evidently you need to port the rest of leanprover-community/mathlib#19204 along with this new file, no?

**Comment by xroblot** [comment]
Yes, I am working on it

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5369
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5369~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
