### PR TITLE
fix: mk_all ignores locally removed files

### PR DESCRIPTION
**Pull request by adomani**
@YaelDillies pointed out that their preference was to exclude files that are removed, but not yet staged.

From the point of view of CI, the change should be invisible, since CI acts on an unmodified branch.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by YaelDillies** [comment]
Maybe this could be a flag to the command? Namely `./scripts/mk_all.sh` takes unstaged changed into account, but `.scripts/mk_all.sh --ignore-unstaged` ignores them.

I also wonder whether we could write the script in Lean so that any downstream project can create their all file as `lake exe mk-all`.

**Comment by adomani** [comment]
I can easily implement the flag.  As for writing the function in Lean, this is a first possibility:
```lean
def mkAll (mathlib : String := "Mathlib") : IO Unit := do
  let pth ← System.FilePath.walkDir mathlib
  let files := (pth.filter (·.extension == some "lean")).qsort (·.toString < ·.toString)
  let withImport ← files.mapM fun f => do
    return "import " ++ (← Lean.moduleNameOfFileName f none).toString
  IO.FS.writeFile (mathlib ++ ".lean") (String.intercalate "\n" withImport.toList)
```
After that, running `#eval mkAll` would create the `Mathlib.lean` file with all the imports.

However, *all* really means *all* (.lean) files in the `Mathlib` folder, whether or not they are in the output of `git ls-files` or not.  I asked a question about running `git ls-files` from Lean [here](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/.60git.20ls-files.60.20in.20Lean).

**Comment by YaelDillies** [comment]
Given that Lean libraries aren't necessarily backed by a git repository, so I think not using the information from git is the correct default behaviour. You could recover the current behaviour by adding a `--git` flag to get the information from git.

**Comment by adomani** [comment]
I am implementing the simple version of the `mk_all` script at #11853.  There, you can find the flag:
```lean
-- use git
run_cmd mkAll (git? := true) (cands := candidates)

-- recurse into dirs
run_cmd mkAll (git? := false) (cands := candidates)
```
(The argument are actually not optional, but the explicit labels make them clearer, I hope!)

**Comment by YaelDillies** [comment]
I believe this PR could simply be closed since we will soon remove `./scripts/mk_all.sh` entirely

**Comment by grunweg** [comment]
Since #11853 has landed, this PR can be closed, right?

**Comment by YaelDillies** [comment]
I think we should just delete `mk_all.sh` now, yes

**Comment by adomani** [comment]
@YaelDillies should I delete this PR?  Is there some extra functionality that you would like `lake exe mk_all` to have that should be rescued from here?

If you are ok with closing, feel free to do so yourself as well!

**Comment by YaelDillies** [comment]
Yes, let's close this PR

**Pull request closed without merging**
