### PR TITLE
[Merged by Bors] - feat: port RingTheory.Localization.Integral

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

- [x] depends on: #4217

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4217
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4217~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
