### PR TITLE
[Merged by Bors] - feat: port Topology.Algebra.UniformGroup

### PR DESCRIPTION
**Pull request by mcdoll**
---

- [x] depends on: #2472

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2472
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2472~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by mcdoll** [comment]
Most low hanging fruit has been collected, but the remaining errors shouldn't be too hard either.

**Pull request closed without merging**
