### PR TITLE
[Merged by Bors] - chore: Merge `Algebra.Group.Centralizer` into `Algebra.Group.Center`

### PR DESCRIPTION
**Pull request by YaelDillies**
---

- [x] depends on: #13030
- [x]  depends on: #13921
- [x] depends on: #13944 
- [x] depends on: #14331

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/center.20and.20centralizer

**Comment by YaelDillies** [comment]
Conclusion seems to be that it's fine to merge the files.

**Comment by Ruben-VandeVelde** [comment]
I think this is doing too much all at once, so I'll split off some changes the coming days

**Review by Ruben-VandeVelde — APPROVED** [review]
lgtm, but I touched this a lot, so please take another look. (Commit by commit might be helpful)

maintainer merge

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
