### PR TITLE
[Merged by Bors] - chore: split Order.Defs

### PR DESCRIPTION
**Pull request by kim-em**

### CODE REVIEW

**Comment by kim-em** [comment]
I'm removing the `large-import` tag: this strictly imports less (except for the fact that there are more files now!)

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by Vierkantor** [comment]
Looks like we can do even more downstream shaking!

bors d+

**Comment by kim-em** [comment]
bors merge

**Pull request closed without merging**
