### PR TITLE
[Merged by Bors] - feat: port Analysis.SchwartzSpace

### PR DESCRIPTION
**Pull request by mcdoll**
---

- [x] depends on:  #5083 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
@int-y1 Have a look at `hPow` trick. You can see it while porting other files too.

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5083
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5083~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
