### PR TITLE
[Merged by Bors] - refactor(AlgebraicGeometry): Introduce `Scheme.toSpecΓ`

### PR DESCRIPTION
**Pull request by erdOne**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
!bench

**Comment by erdOne** [comment]
!bench

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by jcommelin** [comment]
Let's try again

bors r+

**Comment by erdOne** [comment]
bors merge

**Pull request closed without merging**
