### PR TITLE
[Merged by Bors] - [Merged by Bors] - feat: the union of the regular and extensive coverages generates the coherent topology

### PR DESCRIPTION
**Pull request by dagurtomas**
We define the regular and extensive coverages on categories and prove that their union generates the coherent topology on extensive, regular, precoherent categories.

- [x] depends on: #6878 
- [x] depends on: #6879
- [x] depends on: #6896 

Co-authored-by: Riccardo Brasca @riccardobrasca [riccardo.brasca@gmail.com](mailto:riccardo.brasca@gmail.com)
Co-authored-by: Filippo A E Nuccio @faenuccio [filippo.nuccio@univ-st-etienne.fr](mailto:filippo.nuccio@univ-st-etienne.fr)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by dagurtomas** [comment]
I've opened two smaller, independent PR's that this one depends on: #6878, #6879

**Comment by dagurtomas** [comment]
I've now opened #6896 with just the definitions of the coverages

**Review by riccardobrasca — APPROVED** [review]
LGTM, thanks!

**Comment by joelriou** [comment]
Thanks!

bors merge

**Pull request closed without merging**
