### PR TITLE
[Merged by Bors] - feat: make `Fintype (SimpleGraph V)` computable

### PR DESCRIPTION
**Pull request by kmill**
Adds `DecidableEq V` to the `Fintype (SimpleGraph V)` instance's type signature, which can be easily satisfied in a noncomputable setting.

---

- [x] depends on: #3989

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3989
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3989~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ocfnash** [comment]
bors merge

**Comment by kmill** [comment]
bors r-

This PR comes from back when autoimplicits were still enabled.

**Pull request closed without merging**
