### PR TITLE
[Merged by Bors] - chore(CategoryTheory.IsConnected): remove redundant hypothesis in `of_induct`

### PR DESCRIPTION
**Pull request by sven-manthe**
remove the unnecessary hypothesis by proving it

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Thanks!
maintainer merge

**Comment by sven-manthe** [comment]
This build failure looks like a linter bug to me, as the have is used in typeclass inference.

**Comment by fpvandoorn** [comment]
The file compiles for me after deleting line 209. This makes sense: you removed the `Nonempty` assumption from `IsConnected.of_induct`, so it's not used anymore.

**Comment by fpvandoorn** [comment]
bors d+

**Comment by sven-manthe** [comment]
Oh, I misread the line it referred to... Thanks

**Pull request closed without merging**
