### PR TITLE
[Merged by Bors] - chore: a non-lean linter for #-commands

### PR DESCRIPTION
**Pull request by adomani**
This PR introduces an `awk`-based linter for checking that `Mathlib/*.lean` files do not contain `#`-commands.

It takes the names of the commands that begin with `#` by running
```lean
import Mathlib
#help command
```
and after that it is all text-based substitutions.

It triggers an error on lines that begin with `#cmd`, omitting (most) lines contained comment blocks.

CI for this PR should fail until #10772 and #10827 have been merged.

---

#10772 has been merged and the error message for the check decreased.

#10827 has been merged and the error message disappeared.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
Okay, not lovely, but better than nothing! :-)

bors d+

**Comment by adomani** [comment]
Thanks for the approval and for merging the remaining "test" PR.

I hope that this is just a temporary fix.

I'm trying to see how actual Lean linters work and hopefully I'll be able to replace this one by a proper linter.

**Comment by alexjbest** [comment]
I think this would have been better to add as an extra linter for the style linter python script. In the same way as we ban set option there. This would be a much less complicated way of doing things imo, and we would get things like reviewdog for free almost

**Comment by adomani** [comment]
@alexjbest in case you are curious, I have a draft version of the same linter, but written in lean as a "syntax linter": #11019.

If that one is preferred, then I am happy to remove this one!

**Pull request closed without merging**
