### PR TITLE
feat(AlgebraicGeometry/Morphisms): closed immersions

### PR DESCRIPTION
**Pull request by jonasvanderschaaf**
Co-authored-by: 101damnations <101damnations@github.com>

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jonasvanderschaaf** [comment]
I realise that locally surjective has been defined for morphisms of sheaves as something equivalent to surjective on stalks. If this is the desired definition I will update the code.

**Comment by 101damnations** [comment]
Making the API for a new definition as your first PR is a big challenge - I don't know how comprehensive it's gotta be for it to get merged. If you get a chance I would recommend taking a look at the organisation and content of the `IsOpenImmersion` folder and some other files in the `Morphisms` folder too, and maybe adding or reordering things to emulate some of them.

I have done a bunch of half-baked tidying and reorganisation; please let me know if anything's inscrutable.

I've also added an introduction template at the beginning - not all sections need to be filled if they're not relevant.

**Comment by joelriou** [comment]
Most of the content of file looks good to me. It is likely that it no longer compiles after merging with `origin` (because of small changes in the `MorphismProperty` API), but the fix should not be too hard. In terms of API, I would say that you should add some lemmas which allow to use the properties `base_closed` and `surj_on_stalks`, like a lemma `surjective_stalkMap_of_isClosedImmersion` (or just `surjective_stalkMap`?) which take as input the assumption `[IsClosedImmersion f]`. Then, in the proof of `Scheme.isClosedImmmersion_of_comp` (I would favour this name over `Scheme.IsClosedImmersion.ofComp`), you would no longer need the `rcases`.
(Eventually, it would be nice to relate the surjectivity on stalks with locally surjective maps, but this can wait for another PR.)

**Comment by jonasvanderschaaf** [comment]
Thank your for your comments. Unfortunately, I don't really have the time or interest right now to pursue merging this into mathlib. If someone wants to take this code and turn it into a proper commit that's fine with me, but I'm probably not going to do it.

**Comment by chrisflav** [comment]
@101damnations are you interested in adopting this PR? If not, I'll look into it. In any case this PR needs to be re-opened on a mathlib branch.

**Comment by 101damnations** [comment]
Sorry to have abandoned helping out with this for so long. I don't think I'll adopt it - thank you very much @chrisflav if you take it on.

**Comment by chrisflav** [comment]
Since this PR is on a fork, I opened #12917 based on this one from a mathlib branch.

**Comment by jonasvanderschaaf** [comment]
An edited version of this has been merged in #12917. I will close it here as well.

**Pull request closed without merging**
