### PR TITLE
[Merged by Bors] - chore: whitespace changes remaining after merging lean#2074 workarounds

### PR DESCRIPTION
**Pull request by kim-em**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by jcommelin — COMMENTED** [review]
Thanks :tada: 

If CI passes, please remove the label `awaiting-CI` and merge this yourself, by adding a comment `bors r+`.

bors d+

**Comment by semorrison** [comment]
bors merge

**Comment by collares** [comment]
This conflicts with #4030 quite a lot

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
