### PR TITLE
[Merged by Bors] - chore: Rename a few lemmas about `Pi.mulSingle`

### PR DESCRIPTION
**Pull request by YaelDillies**
Before this PR, the `MonoidHom` version of `Pi.mulSingle` was called `MonoidHom.single` for brevity; but this is confusing when contrasted with `MulHom.single` which is about `Pi.single`.

After this PR, the name is `MonoidHom.mulSingle`.

Also fix the name of `Pi.single_div` since it is about `Pi.mulSingle` (and we don't have the lemma that would be called `Pi.single_div`).

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
bors d+

I don't think this was an error, I think it was a decision at the time which turned out to become inconsistent later. I've edited the description accordingly; please merge if you're ok with it.

**Comment by YaelDillies** [comment]
`Pi.single_div` is unambiguously an error, right?

**Comment by YaelDillies** [comment]
`Pi.single_div` is unambiguously an error, right?

**Comment by YaelDillies** [comment]
bors merge

**Pull request closed without merging**
