### PR TITLE
[Merged by Bors] - chore(ZMod/Basic): move two lemmas

### PR DESCRIPTION
**Pull request by rwst**
Move the lemmas `val_eq_zero` and `val_intCast` up. Necessary for proving some lemmas without using `ModEq`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by rwst** [comment]
@riccardobrasca Thanks but .. Why did it fail? And it said "Retrying..." but didn't?

**Comment by riccardobrasca** [comment]
Can you please merge master and see if there is a CI error?

**Comment by riccardobrasca** [comment]
bors merge

**Pull request closed without merging**
