### PR TITLE
[Merged by Bors] - fix: category_theory -> CategoryTheory in note

### PR DESCRIPTION
**Pull request by mo271**
This changes the name of a library_note from
"category_theory universes" to
"CategoryTheory universes"
to be more in line with the new naming conventions.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
I checked for other occurrences of new names used in a library_note but didn't find any

**Review by dupuisf — COMMENTED** [review]
Thanks!

bors r+

**Comment by mo271** [comment]
I can't see Details for the `bors — Build failed` run, but https://github.com/leanprover-community/mathlib4/actions/runs/4211872392/jobs/7310499221 it seems like some caching was not working as intented. Seems unrelated to the pull request at hand, perhaps we can try again to
bors r+

**Pull request closed without merging**
