### PR TITLE
[Merged by Bors] - feat: port Data.Set.Functor

### PR DESCRIPTION
**Pull request by dupuisf**

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
lgtm

**Comment by rwbarton** [comment]
It looks like the new `seqLeft_eq`/`seqRight_eq` proofs are necessary because in Lean 4 we have
```lean
class Monad (m : Type u → Type v) extends Applicative m, Bind m : Type (max (u+1) v) where
  map      f x := bind x (Function.comp pure f)
  seq      f x := bind f fun y => Functor.map y (x ())
  seqLeft  x y := bind x fun a => bind (y ()) (fun _ => pure a)
  seqRight x y := bind x fun _ => y ()
```
while Lean 3 had
```lean
class applicative (f : Type u → Type v) extends functor f, has_pure f, has_seq f, has_seq_left f, has_seq_right f :=
(map       := λ _ _ x y, pure x <*> y)
(seq_left  := λ α β a b, const β <$> a <*> b)
(seq_right := λ α β a b, const α id <$> a <*> b)
```
and the laws that we need to prove are exactly the defining equations of the Lean 3 default definition of `seq_left` and `seq_right`.

We should probably prove two lemmas somewhere that say that the new default Monad `seqLeft` and `seqRight` are equal to the old defaults, assuming enough laws hold already (though I am not sure exactly how to formulate this).

**Comment by dupuisf** [comment]
As Mario pointed out on Zulip, there is a constructor in `Std.Classes.LawfulMonad` that does this, and this file has now been updated to use it.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
