### PR TITLE
[Merged by Bors] - chore: fix lake exe graph --exclude-meta

### PR DESCRIPTION
**Pull request by kim-em**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
See attached examples:
* [before.pdf](https://github.com/leanprover-community/mathlib4/files/12518524/before.pdf)
* [after.pdf](https://github.com/leanprover-community/mathlib4/files/12518523/after.pdf)

**Review by joneugster — COMMENTED** [review]
I pushed a more refined proposal, feel free to revert/modify it as you see fit.

This suggested code removes all filtered nodes in the graph but then it adds back edges wherever there was a transitive connection that went through filtered nodes. i.e if there were imports `source → tacticFile₁ → tacticFile₂ → target` it will now add `source → target` as a new edge.

The two defs I added might need renaming and relocating.

That leaves `upstreamOf` unused, but I don't see a problem leaving it in as pendant to `downstreamOf`.

**Review by kim-em — COMMENTED** [review]
Looks good to me, thank you @joneugster!

**Review by jcommelin — COMMENTED** [review]
bors d+

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
