### PR TITLE
[Merged by Bors] - feat: port Data.List.Zip

### PR DESCRIPTION
**Pull request by zeramorphic**
- [x] depends on: #1380

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#1380
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by zeramorphic** [comment]
Porting note: `length_zipWith` wasalready in `Std`, so was removed.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#1380~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
