### PR TITLE
[Merged by Bors] - feat: nth Prime 0 = 2

### PR DESCRIPTION
**Pull request by rwst**
See https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/2.20is.20the.20first.20prime

Needed as induction start for a formal BOOK proof.

Co-authored-by: Kyle Miller <kmill31415@gmail.com>

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by acmepjz — COMMENTED** [review]
Looks good to me. Do you think it's a good idea to make this a simp lemma?

**Comment by rwst** [comment]
Thanks. I don't think so.

**Comment by riccardobrasca** [comment]
> Thanks. I don't think so.

Why not? It seems a reasonable `simp` lemma.

**Comment by rwst** [comment]
> > Thanks. I don't think so.
> 
> Why not? It seems a reasonable `simp` lemma.

I'm lacking experience with this decision, thanks. This is now added.

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
