### PR TITLE
[Merged by Bors] - chore: Rename `IsROrC` to `RCLike`

### PR DESCRIPTION
**Pull request by YaelDillies**
`IsROrC` contains data, which goes against the expectation that classes prefixed with `Is` are prop-valued. People have been complaining about this on and off, so this PR renames `IsROrC` to `RCLike`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by kbuzzard** [comment]
This is fine by me, although I have only recently understood the scope of the problem. Many properties of topological spaces (e.g. `CompactSpace`, `QuasiSober`, `QuasiSeparatedSpace`, `T0Space`, `T2Space` etc etc) are `Prop`s with no `Is`, plenty of other `Prop`s (e.g. `Odd`, `Even`) have no `Is`, and conversely there are a other non-Props with `Is` names like `CategoryTheory.IsLeftAdjoint`, `CategoryTheory.IsRightAdjoint`, `CategoryTheory.IsEquivalence`.

**Comment by sgouezel** [comment]
I think this is a good change, but I'd like to have a second support.
maintainer merge

**Comment by fpvandoorn** [comment]
Given how much we already violate the meaning of the `Is`-prefix, I'm not entirely convinced by this change. The previous name was more descriptive for people using the class (`LikeROrC` also satisfies this property, if we want to remove the `Is`).
I'm not necessarily against this PR though, we (and new users) will get used to the new name.

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
