### PR TITLE
[Merged by Bors] - feat: port Data.Finset.Interval

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
We should have an instance deducing this from `DecidableEq`.

**Comment by mo271** [comment]
> We should have an instance deducing this from `DecidableEq`. Probably, Lean 3 can use https://leanprover-community.github.io/mathlib_docs/data/finset/basic.html#finset.decidable_dforall_finset but Lean 4 can't do it, so we need to add an instance (based on the ported version of that instance).

I tried to do it in the same way as for `⊆`, but it doesn't work. Please have a look, @urkud

**Comment by mo271** [comment]
@urkud, do you have an idea how to add an instance or would it be better to open a zulip thread on this?

**Comment by mo271** [comment]
> > We should have an instance deducing this from `DecidableEq`. Probably, Lean 3 can use https://leanprover-community.github.io/mathlib_docs/data/finset/basic.html#finset.decidable_dforall_finset but Lean 4 can't do it, so we need to add an instance (based on the ported version of that instance).
> 
> I tried to do it in the same way as for `⊆`, but it doesn't work. Please have a look, @urkud

I think I got it to work now

**Pull request closed without merging**
