### PR TITLE
[Merged by Bors] - feat(MeasureTheory): add `ae_restrict_of_forall_mem`

### PR DESCRIPTION
**Pull request by dupuisf**
I found myself repeatedly needing this lemma.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by j-loreaux** [comment]
maintainer merge

**Comment by urkud** [comment]
Why not use `rw [ae_restrict_iff']` instead?

**Comment by dupuisf** [comment]
I was using `ae_restrict_iff_subtype` directly at the beginning, but after four or five times I thought it was time to write the lemma I actually wanted.

**Comment by urkud** [comment]
Another option is `(ae_restrict_mem _).mono`. If you prefer your lemma, then we can add it, but please move it near `ae_restrict_mem`.
bors d+

**Pull request closed without merging**
