### PR TITLE
[Merged by Bors] - chore: two dots to cdots

### PR DESCRIPTION
**Pull request by adomani**
Replace two `.` with `·`.

Found by the linter at #12143.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — APPROVED** [review]
Thanks for the clean-up; looks good!

**Comment by urkud** [comment]
Do you mean "two dots to cdots"?

**Comment by adomani** [comment]
Yury, yes, i meant dogs to cdots!  I updated the PR title.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
