### PR TITLE
[Merged by Bors] - feat: lemmas about Multiset.join

### PR DESCRIPTION
**Pull request by timotree3**
- `Multiset.map_join` corresponding to [`List.map_join`](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Data/List/Basic.html#List.map_join)
- `Multiset.prod_join` corresponding to [`List.prod_join`](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Data/List/BigOperators/Basic.html#List.prod_join)
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by madvorak** [comment]
LGTM

**Comment by madvorak** [comment]
maintainer merge

**Comment by eric-wieser** [comment]
> maintainer merge

This only works for people on the list of [reviewers with special permissions](https://leanprover-community.github.io/teams/reviewers.html); but your review is still appreciated!

**Comment by ocfnash** [comment]
Thanks!

bors merge

**Pull request closed without merging**
