### PR TITLE
[Merged by Bors] - feat: port Data.Set.Intervals.OrdConnectedComponent

### PR DESCRIPTION
**Pull request by LukasMias**

### CODE REVIEW

**Comment by LukasMias** [comment]
Might be a hot second before I figure out how to adapt the ```wlog/lift``` proof at the end, so help is definitely welcome.

**Comment by LukasMias** [comment]
I think I could deal without ```wlog```, but I'm not sure how to work without ```lift```. Considering that the porting of ```lift``` has gotten some significant push in the last days (https://github.com/leanprover-community/mathlib4/pull/723), maybe it's worth waiting for this.

**Comment by LukasMias** [comment]
Okay, working around ```lift``` was easy after all. The only problem left is that ```wlog``` in the last proof is not implemented yet, and I cannot quickly think of a _short_ way to replace it and I don't have much time to think about it now. If anyone knows how to work around the missing ```wlog``` without duplicating large amounts of code, be my guest!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
