### PR TITLE
[Merged by Bors] - feat: compact subsets in products as cofiltered limits of projections

### PR DESCRIPTION
**Pull request by dagurtomas**
We exhibit a compact subset in a product of totally disconnected Hausdorff spaces as a limit of its projections to finite subsets of the indexing set, in the category `Profinite`. The proof is structured in the same way as `Profinite.isIso_asLimitCone_lift` and `DiscreteQuotient.exists_of_compat`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by dagurtomas** [comment]
I'm not sure where to put the stuff that is currently in `section General` in `Mathlib/Topology/Category/Profinite/Product`. And maybe the rest belongs in `Mathlib/Topology/Category/Profinite/AsLimit`?

**Comment by joelriou** [comment]
About `ProjRestrict`, etc, would not it be better to redesign it (and also `Proj` and `Set.proj`) so that if we have `φ : ι' → ι` then there is an induced "pullback" map `(∀ i, π i) → (∀ i', π (φ i))`. Then, `Set.proj` is the direct image of a subset `C` by this map. (If it is not absolutely necessary, I am a little disturbed by the `Inhabited` instances which may seem to be a little bit artificial. If such assumptions is needed, `Nonempty`, which is a `Prop`, would presumably be better.)

**Comment by ADedecker** [comment]
I agree with Joël (I meant to comment on that a while ago but then forgot about it, I'm very sorry). Incidentally I need similar results, so #6836 is proving continuity for these "precomposition" maps (although they are not literally precompositions because of dependent types). You could also use [Set.restrict](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Data/Set/Function.html#Set.restrict) for the particular case of inclusion of a set into a type, but it's probably easier to work in greater generality than with subsets!
Then, if you really need to extend by dummy values, you can probably prove a continuity result for [Function.extend](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Logic/Function/Basic.html#Function.extend). Does that make sense?

**Comment by dagurtomas** [comment]
Thanks for the suggestions! I'm on vacation and will look at this in more detail when I get back. Regarding the `Inhabited` instances, the reason I'm using them is that in my application (#6286, Nöbeling's theorem) and the setting I originally did this in was for the space `I → Bool`, where `default` is `false`. It's really convenient to stay inside the space `I → Bool` throughout that proof, and thus map everything to the "dummy" value `false`.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by ADedecker** [comment]
bors r-

@jcommelin This was tagged as awaiting-author for a good reason, and I would like to continue this discussion when Dagur comes back from vacation.

**Comment by dagurtomas** [comment]
Ok I'm back. Here are some thoughts:

I would argue that the map `Proj J : ((i : ι) → π i) → ((i : ι) → π i)` is quite canonical when the `π i` are `Inhabited`. I'm not extending by what you call a dummy element, I'm extending by the *default* element. I don't see why it would be better to write it as a composition of a map`((i : ι) → π i) → ((j : {i // J i}) → π j.val)` and `Function.extend : ((j : {i // J i}) → π j.val) → ((i : ι) → π i)` as Anatole suggests, when I can instead write it cleanly in one line.  

In my application, Nöbeling's theorem, it is very convenient that `ι` stays fixed throughout the proof. I realise that in the context of this PR it might seem weird to require it when a similar end result is true regardless of the factors being `Inhabited`, but there is the explanation. I could try do something similar without requiring the factors to be inhabited, where the transition maps in the limits would go between products with different indexing sets. But again, in my application, I need the transition maps to stay within the same fixed product.

**Comment by joelriou** [comment]
The main statement (here) does not require `Inhabited`, which is the reason we feel it is not canonical. For this PR, I would suggest redefining `FinsetsToProfinite` in a way that seems more natural to me and Anatole (without any arbitrary choice given by `Inhabited`) and obtain the result that the corresponding cone is limit. Then, for the your application, if it is critical to the proof, you may *additionally* define another `FinsetsToProfinite'` based on an `Inhabited` assumption, and then, it will be easy to show that these two functors are isomorphic and the corresponding cones corresponds, so that one of cones is limit iff the other is.

**Comment by dagurtomas** [comment]
Ok, I've removed all the `Inhabited` instances. I'm still thinking about how to apply this in Nöbeling but for now this works as a standalone PR, if you want to take a look again.

**Comment by dagurtomas** [comment]
If this gets merged, then Nöbeling (#6286) is ready for review

**Comment by joelriou** [comment]
The definitions/statements in this PR looks good to me, but they do not seem to be in appropriate namespaces. The results about profinite sets should be in the `Profinite` namespace. I think that `FinsetFunctor` and `precomp` should be renamed and/or put in a namespace in a way which reflects the fact that this is topology; also it seems that `SetFunctor` would be better than `FinsetFunctor`.

**Comment by dagurtomas** [comment]
I moved `precomp` to `Topology/ContinuousFunction/Basic`, and put everything else in the `Profinite` namespace. I changed both the `FinsetFunctor` namespace and the name of the functor `FinsetsToProfinite` to `Profinite.IndexFunctor`, where `index` refers to the indexing set of the product. Does this make sense?

**Review by joelriou — APPROVED** [review]

**Comment by dagurtomas** [comment]
Build fails because of "no space left on device"...

**Comment by ADedecker** [comment]
That happens from time to time, we've removed the affected runner for now until someone can fix the issue. I restarted the build.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
