### PR TITLE
[Merged by Bors] - feat(GroupTheory/OrderOfElement): equivalences preserve orders

### PR DESCRIPTION
**Pull request by MichaelStollBayreuth**
We add the statement that (multiplicative and additive) equivalences preserve the order of an element.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
I think it is enough to assume that `e` is injective?

**Comment by erdOne** [comment]
Wait I just found `orderOf_injective`

**Comment by MichaelStollBayreuth** [comment]
OK, that simplifies things. (I guess I didn't think of looking for the injective version...)
I still think it's good to have an explicit `MulEuiv` version so that one can write `e.orderOf_eq m` when `e` is an equivalence.

**Comment by erdOne** [comment]
I think it should go under the injective counter part, and maybe made a simp lemma?

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
