### PR TITLE
chore: update/remove heart beat bumps 

### PR DESCRIPTION
**Pull request by mattrobball**
Cleaning up after #6474, we remove/lower many bumps to heart beats.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by eric-wieser** [comment]
For the sake of review, could you rewrite history here to split the first commit in two with the new elaborator in its own commit?

**Comment by mattrobball** [comment]
Sure. Where do I put it to make it available for all of mathlib? I just dropped it into `Mathport.Rename` which I am sure is not what you are supposed to do.

**Comment by eric-wieser** [comment]
Maybe `Mathlib.Init.Type` or `Mathlib.Init.UnivWildcard`?

**Review by eric-wieser — COMMENTED** [review]
Am I right in saying that everything in https://github.com/leanprover-community/mathlib4/pull/6370/files/2637c7e806bc15f25dbbc719a3ee86d1dccb905b..466a8a7f811099cec09a1d601053cd9c98d7e3c2 is a place where the universes are not actually free variables?

**Comment by mattrobball** [comment]
Yes. Very nice corollary. I'm going to circle back and make it more explicit.

**Comment by eric-wieser** [comment]
Some of those look rather concerning to me; just to be super clear: they're not just places where they're *currently* not free variables; but places where using free variables actually causes a failure?

**Comment by mattrobball** [comment]
Everything was changed because of a failure somewhere. The vast majority was in the declaration itself where the change was

**Comment by mattrobball** [comment]
`Subalgebra.Basic` was an entirely reverted for expediency. (I didn't quickly find the cause of an error.) There might one or two others.

**Comment by mattrobball** [comment]
I carefully went back through where all the replacements of `Type _` with `Type*` failed and made notes. Some particular issues:
- `Bundled.of` is not fully universe polymorphic. This might be causing some of the slowdowns we have seen later in the category. 
- `SMul` and `VAdd` both have problems with `to_additive` generation when fully polymorphic 
- `initialize_simps_projection` also seems to have trouble when fully polymorphic, see eg 'IsometryEquiv` or `AlgHom.Simps.apply`

**Comment by mattrobball** [comment]
!bench

**Pull request closed without merging**
