### PR TITLE
[Merged by Bors] - chore(ConcreteCategory/Bundled): remove outdated comment about Bundled.map

### PR DESCRIPTION
**Pull request by grunweg**
the definition is not reducible, so apparently this is fine.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by j-loreaux** [comment]
Can someone familiar with the category theory portion of the library have a look?

maintainer merge

**Comment by mattrobball** [comment]
I agree with the sentiment of the comment. Do we know why it is not an `abbrev`?

**Comment by j-loreaux** [comment]
@grunweg Can you try just making it an `abbrev` and seeing what breaks?

**Comment by grunweg** [comment]
!bench

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
