### PR TITLE
[Merged by Bors] - feat: Port RingTheory.Polynomial.Tower

### PR DESCRIPTION
**Pull request by casavaca**
Rename only.

---

- [x] depends on: #2822 
[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2822
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2822~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by Parcly-Taxel — APPROVED** [review]

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by fpvandoorn** [comment]
merge conflict

bors r-
bors d+

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
