### PR TITLE
[Merged by Bors] - chore(GroupTheory/Perm/List): nthLe -> get migration

### PR DESCRIPTION
**Pull request by t4ccer**
chore(GroupTheory/Perm/List): nthLe -> get migration

Rewrite theorems in GroupTheory/Perm/List to use `List.get`. Deprecate old ones and rewrite them as thin wrappers around new ones.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Welcome to mathlib and thanks for your contribution! I did some work in this direction before - I'm very happy to see you doing more along this avenue. I presume you'd like your PR to be reviewed - I've labelled it `awaiting-review` to mark it as such.
(This label and a few more tricks are documented in the [contribution guide](https://leanprover-community.github.io/contribute/index.html).)

**Comment by semorrison** [comment]
Fantastic, I was blocked by this. I'm going to merge master myself. Apologies for pushing direct to your PR, but I need this asap. :-)

**Comment by semorrison** [comment]
bors p=10

bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
