### PR TITLE
[Merged by Bors] - chore(RepresentationTheory.GroupCohomology): make namespaces lower camel case

### PR DESCRIPTION
**Pull request by 101damnations**
---

Absolutely no idea why I thought these namespaces needed to be upper camel case.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by joelriou** [comment]
I am not sure that `groupCohomology` is better than `GroupCohomology`. For example, we have `CategoryTheory`, and not `categoryTheory`. Most namespaces in mathlib start with an uppercase letter:
```
joel@kalyani ~/lean/mathlib4 $ grep '^namespace [a-z]' **/*.lean|wc -l
130
joel@kalyani ~/lean/mathlib4 $ grep '^namespace [A-Z]' **/*.lean|wc -l
6761
```
(I am not sure what is the best justification for this, but it seems that lowercase initials in namespaces are used in order to develop the API around a definition which starts with a lowercase letter: for example, we have the definition of the object `kernel f`, and then we have `kernel.lift`.)

**Comment by 101damnations** [comment]
Thank you - yeah, I've changed namespaces to lower camel when there's a definition with that name.

**Comment by digama0** [comment]
Note: I have pushed an update to the lean toolchain because this PR was on a [buggy version](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Potential.20data.20loss.20from.20.60lake.20clean.60.20with.204.2E2.2E0-rc2.2F3/near/397875701) of the toolchain. **WARNING**: checking out old commits of this PR using v4.2.0-rc2 or v4.2.0-rc3 can cause `lake clean` to delete your mathlib folder! If you need to do so, make sure to delete `lakefile.olean` manually before running any `lake` commands.

**Comment by joelriou** [comment]
Thanks!

bors merge

**Pull request closed without merging**
