### PR TITLE
[Merged by Bors] - fix: remove check for `olean`s in `assert_not_imported`

### PR DESCRIPTION
**Pull request by adomani**
See [Zulip](https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/assert_not_imported) for a discussion of the issues arising from looking for `olean`s, rather than `lean`s.

As a test, this PR also incorporates some uses of `assert_not_imported` to verify that CI and `!bench` work!

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
Very good point: I just cherry-picked all the commits from that PR into this one!

**Comment by adomani** [comment]
!bench

**Comment by grunweg** [comment]
Thank! maintainer delegate, i.e. feel free to maintainer merge on my behalf once benchmarking has come back positively.

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
