### PR TITLE
docs: tactic writing tutorial

### PR DESCRIPTION
**Pull request by arthurpaulino**

### CODE REVIEW

**Comment by EdAyers** [comment]
I can help with this!

**Comment by EdAyers** [comment]
Ok that's everything I've got. Feel free to edit or delete or restructure!

**Comment by digama0** [comment]
I think that the tutorial should be written in markdown with lean code blocks, instead of being a lean file with markdown blocks. That will also fix the build error.

**Comment by arthurpaulino** [comment]
@digama0 I talked to Edward and we're going to extract the tutorial content from this repo to avoid the mess of the process. Once the markdown files are ready I will let the community know we will be able to choose their destiny. In the meantime, I intend to code in Lean to make sure everything typechecks and then convert those files to markdown using my `lean2md.py` script.

**Pull request closed without merging**
