### PR TITLE
[Merged by Bors] - feat: port CategoryTheory.Bicategory.CoherenceTactic

### PR DESCRIPTION
**Pull request by joelriou**
---
So far, only the nontactic code is ported.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
I'm working on the tactics now.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by jcommelin** [comment]
@semorrison bors wasn't happy...

bors d=semorrison

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
