### PR TITLE
[Merged by Bors] - feat(FieldTheory/Adjoin): add some results of `extendScalars`

### PR DESCRIPTION
**Pull request by acmepjz**
- `extendScalars_{self|top|inf|sup}` for intermediate fields and subfields
- also add `restrictScalars_{inf|sup}` and `bot_toSubfield`
- add a missing helper lemma `toSubfield_injective`

---

- [x] depends on: #15148
- [x] depends on: #15088

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
LGTM thanks!
maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by acmepjz** [comment]
It's waiting in queue for a whole day...

**Comment by erdOne** [comment]
This is very strange. It is not in a queue [here](https://mathlib-bors-ca18eefec4cb.herokuapp.com/repositories/16) I'll ask in the reviewer stream on Zulip.

**Pull request closed without merging**
