### PR TITLE
[Merged by Bors] - feat(Topology/Order/Group): zmultiples aren't dense

### PR DESCRIPTION
**Pull request by urkud**
---

- [x] depends on: #15544
- [x] depends on: #15547

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by YaelDillies** [comment]
@pechersky, did you see this PR? It seems very relevant to your current line of work

**Comment by pechersky** [comment]
I hadn't seen it, thanks for pointing it out. It's very similar -- I use `DenselyOrdered` on the group itself, and work on `closure` instead. @urkud, should we talk about whether we're going in the same direction?

**Comment by urkud** [comment]
@pechersky Please ping me on Zulip tomorrow.

**Pull request closed without merging**
