### PR TITLE
[Merged by Bors] - feat: minimal port of `Fintype (Fin n)`

### PR DESCRIPTION
**Pull request by kim-em**
- [x] depends on: #429

### CODE REVIEW

**Comment by semorrison** [comment]
@digama0, I've hopefully followed the style corrections you made on #433 here.

This PR is not strictly necessary for #437, just for the tests. If you think it's best to avoid porting too much stuff by hand at this point, we can probably get by without this and defer having proper tests for `fin_cases` until later.

**Comment by digama0** [comment]
I don't think we have to be super surgical about porting only the bare minimum here; I generally port entire files when it seems like I might need some part of them (although possibly we can make an exception for the really large files). Most of this stuff is destined for std4 anyway.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
