### PR TITLE
[Merged by Bors] - refactor: Use `nsmul` in `zsmul_rec`

### PR DESCRIPTION
**Pull request by YaelDillies**
It's annoying that `zsmulRec` uses `nsmulRec` to define `zsmul` even when the user already set `nsmul` explicitly. This PR changes `zsmulRec` to take `nsmul` as an argument.

### CODE REVIEW

**Comment by urkud** [comment]
What's the status of this PR? It appeared on https://leanprover-community.github.io/mathlib-port-status/out-of-sync

**Comment by semorrison** [comment]
@YaelDillies, the original mathlib3 PR is marked as `too-late`, now. I'm removing `forward-port-placeholder` and `mathlib3-pair`. Could you prepare it for review directly to mathlib4, or close?

**Comment by jcommelin** [comment]
This pull request has not seen any activity for quite a while, and it does not pass all CI checks. For these reasons, I am closing it now.

If you are still interested in getting this PR merged, please re-open the PR, update the branch, and make sure that all CI checks pass, Please label the PR with `awaiting-review` when ready.

**Comment by fpvandoorn** [comment]
LGTM

bors merge
bors d+

**Pull request closed without merging**
