### PR TITLE
[Merged by Bors] - chore(Monoid/Unbundled/Pow): cleanup

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
@YaelDillies There are some duplicate lemmas in this file. I moved them close to each other. Do you have a preference about which ones should be deprecated?

**Review by YaelDillies — COMMENTED** [review]
The pattern used in earlier files is to have the lemmas in the `Left` namespace be aliased in the root namespace. For the specific lemmas here, I have argued before that it would be nice to find a typeclass that abstracts both the `Left` and `Right` lemmas (it's pretty specific to `pow`/`zpow` since we're relying on the fact that going to the multiplicativ opposite doesn't change `pow`/`zpow`). However, it might be overengineering for what's ultimately a series of a few lemmas.

**Review by YaelDillies — APPROVED** [review]
maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
