### PR TITLE
[Merged by Bors] - feat(Data/Set/Basic, Order/RelClasses): add @[simp] to subset_refl and subset_empty_iff

### PR DESCRIPTION
**Pull request by apnelson1**
As per the description. 

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by apnelson1** [comment]
!bench

**Comment by bustercopley** [comment]
!bench

**Comment by kbuzzard** [comment]
benchmarking costs time (and hence money); it's probably best to only benchmark once CI has declared that mathlib is compiling.

**Comment by bustercopley** [comment]
> benchmarking costs time (and hence money); it's probably best to only benchmark once CI has declared that mathlib is compiling (because that's the only way to get meaningful results).

Huh. I assumed it waited for the build to succeed before doing anything at all. It would be convenient if it did.

**Comment by bustercopley** [comment]
!bench

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
