### PR TITLE
[Merged by Bors] - feat (RingTheory/Localization/LocalizationLocalization): Generalize from CommRing to CommSemiring

### PR DESCRIPTION
**Pull request by XavierXarles**
Change hypothesis CommRing to CommSemiring in the first section of the file

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
Remember to put a line between the commit message and the ---- below next time. Otherwise it will be parsed as markdown syntax and become a title.

**Comment by erdOne** [comment]
!bench

**Comment by erdOne** [comment]
LGTM
maintainer merge

**Review by TwoFX — APPROVED** [review]
Thanks!

bors r+

**Pull request closed without merging**
