### PR TITLE
[Merged by Bors] - chore(LocallyConvex/Bounded): rename `variable`s

### PR DESCRIPTION
**Pull request by urkud**
Instead of introducing a normed field `𝕜` and a nontrivially normed field `𝕝`,
prove a theorem for a normed field, then assume that `𝕜` is a nontrivially normed field.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Makes sense - thanks for cleaning this up!
maintainer merge

**Comment by j-loreaux** [comment]
bors merge

**Comment by urkud** [comment]
I'm going to wait for the larger update to be merged first.
bors r-

**Comment by urkud** [comment]
No, the larger update has conflicts with `master`, not with this branch.
bors merge

**Pull request closed without merging**
