### PR TITLE
feat: teach lake exe cache about Archive and Counterexamples

### PR DESCRIPTION
**Pull request by kim-em**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by digama0** [comment]
Do we really need this? It seems a bit myopic to just be throwing everything into the cache without a plan for how to handle things which aren't mathlib.

**Comment by semorrison** [comment]
We certainly want to change that caches ProofWidgets, it's annoying that those files still get rebuilt every time.

**Comment by semorrison** [comment]
I don't particularly care if `Archive` and `Counterexamples` are cached, but it seems useful to have `cache` know about these files. Without this change if you run `lake exe cache get Archive/Imo/Imo2001Q6.lean` it will just say it doesn't know what you're talking about --- whereas clearly it should at least get the caches for the upstream dependencies within mathlib.

**Comment by semorrison** [comment]
I agree that at some point we need plans for caches that can be owned by other people, and plans for upstreaming `cache`, of course. I'm just not sure why not having such plans at this point is a blocker to improving functionality for mathlib4 as it is today (i.e. containing `Archive` and `Counterexamples` as subprojects).

**Comment by digama0** [comment]
I think we should continue this discussion on zulip

**Pull request closed without merging**
