### PR TITLE
[Merged by Bors] - feat: port CategoryTheory.Preadditive.Projective

### PR DESCRIPTION
**Pull request by urkud**
---

It would be nice if someone who better understands category theory has a look.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by joelriou** [comment]
@urkud: in order to ease automation of proofs by `aesop_cat`, I have added a few `ext` lemmas for (co)products and binary (co)products. This makes these proofs automatic in this file. However, this may break a few proofs in other files, but the fix should be easy though.

Lean complains about universes at https://github.com/leanprover-community/mathlib4/pull/3615/files#diff-b895f9cc25c2521664e7621d0a0cc9b5d28de7c97dbadac62e6abe1073558809R253-R258
I have no idea what causes this problem...

**Comment by semorrison** [comment]
@joelriou, would you mind having a look at my changes in https://github.com/leanprover-community/mathlib4/pull/3615/commits/9c709e5c8b0aa928255bec0c8bc04a2a0afcc8db (and backported as https://github.com/leanprover-community/mathlib/pull/18890)?

**Comment by urkud** [comment]
@joelriou, @semorrison Is it ready for review now? Or it is waiting for leanprover-community/mathlib#18890 now?
@Parcly-Taxel Please don't change labels on my PRs.

**Comment by joelriou** [comment]
@semorrison It looks good to me!

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
