### PR TITLE
[Merged by Bors] - feat: port CategoryTheory.Sites.Subsheaf

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
I'm worried by the instances we have to exhibit by hand here, and would like to investigate, but don't have energy for this now. One might cross-fingers and see if #3414 helps...?

**Comment by jjaassoonn** [comment]
@semorrison please see comment above. Will #3414 help with universe level (the first one) as well as the second one? Maybe it is worth noting that in the first one if F and F' are specified to be `Type _`, Lean can actually find the required instance, it's just not the most general universe level.

**Comment by semorrison** [comment]
> @semorrison please see comment above.

I don't see a comment above?

**Comment by semorrison** [comment]
At least the first set of instances can be avoided by using `TypeMax.{v, u}` instead of `Type max v u`. If my internet stabilises I'll push. :-)

**Comment by jjaassoonn** [comment]
> I'm worried by the instances we have to exhibit by hand here, and would like to investigate, but don't have energy for this now. One might cross-fingers and see if #3414 helps...?

I just merged master branch and tried to see `reenableeta` and `TypeMax`  fixes, but instances still needs to be specified.

**Comment by semorrison** [comment]
Found something slightly better.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
