### PR TITLE
[Merged by Bors] - chore: 'cache' hashes Lean.versionString

### PR DESCRIPTION
**Pull request by kim-em**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alexjbest** [comment]
is this ready for review?

**Comment by semorrison** [comment]
Yes, thank you, I forgot to label!

**Comment by alexjbest** [comment]
I think this looks good then


maintainer merge

**Comment by ocfnash** [comment]
bors merge

**Comment by tydeu** [comment]
@semorrison To make sure there is no breakage between Lake and cache, it seems like it would be better to hash `Lean.githash` like Lake does.

**Pull request closed without merging**
