### PR TITLE
[Merged by Bors] - feat: `a⁻¹ * b = 1 → a = b`

### PR DESCRIPTION
**Pull request by YaelDillies**
and other basic lemmas.

From PFR

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by fpvandoorn** [comment]
Do we already have the `iff` version for all of these lemmas?

bors d+

**Comment by YaelDillies** [comment]
Yes. They are `mul_inv_eq_one`/`mul_inv_eq_one₀` and `inv_mul_eq_one`/`inv_mul_eq_one₀` for the first two, and the ones in the docstrings for the other four.

maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by YaelDillies** [comment]
Sorry, muscle memory.

bors merge

**Pull request closed without merging**
