### PR TITLE
[Merged by Bors] - chore: Make `Finset.univ_nonempty` be simp

### PR DESCRIPTION
**Pull request by YaelDillies**
`Set.univ_nonempty` already is

From LeanAPAP

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by b-mehta** [comment]
Isn't this the kind of lemma that shouldn't be simp (and similarly for `Set.univ_nonempty`) because it makes `simp` go on a long instance search?

**Comment by YaelDillies** [comment]
This is an instance search that often succeeds, no? So it shouldn't be so long. In any case, we can see:

!bench

**Comment by b-mehta** [comment]
!bench

**Comment by b-mehta** [comment]
bors merge

**Pull request closed without merging**
