### PR TITLE
[Merged by Bors] - feat: #find_home

### PR DESCRIPTION
**Pull request by kim-em**
---

- [x] depends on: #5513 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5513
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by alexjbest** [comment]
How fast does this feel in practice? (e.g. for an example deep in the hierarchy with a lemma whose home is somewhere in the middle)

I think when we did similar things in lean 3 we needed marginally more optimal algorithms to get something usable, but I could believe that this is fine in lean 4.

**Comment by semorrison** [comment]
It's indeed not super fast:
```
import Mathlib

def test := Convex

#time #find_home test
```
takes 10s on my machine. That's usable-but-annoying?

I'd prefer not to work on this PR more in the near future, but am happy to either merge as is or to mark `please-adopt` and leave it for later.

**Comment by semorrison** [comment]
There are also some false positives, e.g.:
```
import Mathlib

def test := (Convex, CategoryTheory.Groupoid)

#time #find_home test
-- Mathlib.AlgebraicTopology.FundamentalGroupoid.Basic
-- Mathlib.Tactic
```

**Comment by alexjbest** [comment]
I would vote for merge as is and improve later then, otherwise I fear it will just never happen!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5513~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
