### PR TITLE
perf: small speedup

### PR DESCRIPTION
**Pull request by kbuzzard**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

I'm trying to work out why group cohomology is slow (NB: I wrote this last August; it's much less slow now in Feb!). I think there are several reasons and I'm hoping this is one of them.

### CODE REVIEW

**Comment by kbuzzard** [comment]
!bench

**Comment by kbuzzard** [comment]
Well, group cohomology didn't get any faster, but some other things did...

**Review by jcommelin — COMMENTED** [review]
I would like to see whether this patch is still needed after recent (and upcoming) changes to Lean. So I suggest we bench again when mathlib is bumped to the next rc.

**Comment by kbuzzard** [comment]
Darn it! I did the wrong kind of merge.

**Comment by kbuzzard** [comment]
Closed in favour of #11368

**Pull request closed without merging**
