### PR TITLE
[Merged by Bors] - fix: ignore Aesop tactic/commands in unused tactics linter

### PR DESCRIPTION
**Pull request by JLimperg**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by JLimperg** [comment]
@adomani could you take a quick look at this linter-related PR? Should be very uncontroversial.

**Review by adomani — COMMENTED** [review]
Yes, this looks like the right place to get the linter to ignore the syntax!

Since I'm not at a computer, could I ask you to make sure that the linter is globally active in the test file, by adding `set_option linter.unusedTactic true`?  I'm still not completely sure of the mechanism with which linters operate on dependencies.

Once that is done, feel free to merge!

bors d

(It's the first time that I `bors` a PR!)

**Comment by JLimperg** [comment]
Done, thank you very much!

bors merge

**Comment by JLimperg** [comment]
Hm, if I understand the bors docs correctly, the delegation syntax is `bors d+`.

**Comment by adomani** [comment]
Oops!

Thanks!

bors merge

**Pull request closed without merging**
