### PR TITLE
[Merged by Bors] - feat: port Order.Category.FinBoolAlgCat

### PR DESCRIPTION
**Pull request by joneugster**
---

- [x] depends on: #5023
- [x] depends on: #5051

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5023
* leanprover-community/mathlib4#5051
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5023~~
* ~~leanprover-community/mathlib4#5051~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by j-loreaux** [comment]
The `FunLike` instance that was added seems suspicious; not that it's the wrong function, just that I suspect it only causes further issues.

**Comment by semorrison** [comment]
I've replaced the `FunLike` instance with a `BoundedLatticeHomClass` instance.

I've also added a note saying that we should go back and refactor the earlier bundled order categories to use this formulation. As we are now at a mathlib3 leaf, there's no need to do this now.

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
