### PR TITLE
Add a nix flake build

### PR DESCRIPTION
**Pull request by Anderssorby**
Adding a nix flake to enable builds and dependency fetching with nix.
This has several opinionated choices about structure which can be negotiated.

### CODE REVIEW

**Comment by Kha** [comment]
I would argue that solutions that do not automatically keep the flake.lock<->lean-toolchain versions in sync are strictly worse than no Nix solution.

**Comment by Anderssorby** [comment]
Well, on NixOS using lake is not an option. Can't we just leave it up to the nix users to keep this up to date? When we eventually unify the two solutions this will no longer be an issue. I think this is an acceptable maintenance for a project in development.

**Comment by Anderssorby** [comment]
@Kha If you added a commit hash to the lean-toolchain file it would be easy to parse it and keep it in sync with nix.

**Comment by Kha** [comment]
> Well, on NixOS using lake is not an option

Using it in Nix builds may currently not be an option, but `lake` is only a `nix shell nixpkgs#elan` away

> @Kha If you added a commit hash to the lean-toolchain file it would be easy to parse it and keep it in sync with nix

This is not sufficient for Lean as a flake input since there's also the nar hash. My current plan is to implement a custom fetcher that creates the flake.lock at fetch time (i.e. when we have full network access to retrieve the given release tag).

**Comment by Kha** [comment]
I'm not sure I've stated this before, but my philosophy is that any Nix/Lean integration should be a net benefit that does not annoy/disadvantage anyone not using it.

**Comment by Anderssorby** [comment]
> should be a net benefit that does not annoy/disadvantage anyone not using it.

I totally agree on this, but this should also extend to lake + elan. Currently using this on NixOS is a pain and it constantly breaks because NixOS uses nonstandard locations, which is why I have uninstalled it. Also I don't see how having a flake file would affect users not using it. I don't expect non nix users to update the flake and that should not be a big issue.

> This is not sufficient for Lean as a flake input since there's also the nar hash.

Flake supports specifying the git hash of inputs. 
```nix
{
  inputs = {
    lean = {
      url = "github:leanprover/lean4/3ad8dcb7ffdc3b01ae326798bf2e3a7e11cd961b";
    };
}
```

Also my ambition is to unify the two solutions by creating a nix evaluator / transpiler + parser +  derivation generator implemented in Lean. https://github.com/Anderssorby/Nix.lean/tree/acs/parser
I don't  have a lot of experience with this though. Contributions are welcome. This could  also be a benefit to the general nix ecosystem

**Comment by gebner** [comment]
I completely agree with Sebastian that Nix support should not incur any costs on the non-Nix developers.  I don't want to maintain and support two build systems.  (And since Nix doesn't work on Windows, we'll always have to support the non-Nix build.)  Until we have `lake2nix`, adding Nix support just adds extra development cost without significant benefits.  The number of people who only want to use Nix and not lake is very, very small.

I'm not at all enthusiastic about moving the source code into yet another subdirectory and adding a flake-specific direnv file.  (The PR also doesn't build with lake, but I assume you plan to fix that.)

In my very personal opinion, the Nix build is an amazingly cool tech demo but completely unsuitable for production use.  It doubles the maintenance and development cost on every front: editor support, tooling, documentation, build setup in each project, and even twice the CI time.  In return, you get very little.  Lake runs everywhere that Nix runs.  But you can't use Nix on Windows.  Or to link against system libraries on non-NixOS systems.  You can't even use the Nix build for packages in *nixpkgs* because of the prohibition on IFD and lack of recursive Nix.

> I don't expect non nix users to update the flake and that should not be a big issue.

We're upgrading the Lean version relatively often, so non-Nix users will have to touch flake.nix as well.

> Well, on NixOS using lake is not an option.

On NixOS, lake is very much an option.  I'm using it every day.

> constantly breaks because NixOS uses nonstandard locations

It will only break if there's an stdenv change (or gmp change, but that's even more rare).  Personally, I run into very few issues because I'm regularly deleting ~/.elan to free up space (every nightly is like half a gigabyte).

**Comment by Anderssorby** [comment]
Getting this PR merged was a long shot. I mostly did this change to enable building mathlib with nix.
> We're upgrading the Lean version relatively often, so non-Nix users will have to touch flake.nix as well.
Why? Not updating or maintaining the flake.nix will not affect non-nix users. I feel it should be acceptable that maintaining the flake.nix would be the responsibility of only the nix users.

**Comment by gebner** [comment]
> I feel it should be acceptable that maintaining the flake.nix would be the responsibility of only the nix users.

Then I'm okay with this PR as long as it only adds the flake.nix/flake.lock files.  No restructuring, no direnv files, and the README should make clear that the nix build is experimental/unstable.  (But please be aware that we upgrade the Lean version every few days, so the Nix setup will stop working very quickly if it is not updated.)

**Comment by enricozb** [comment]
In case someone comes across this trying to get a nix-only lean workflow, including mathlib, here's what I've done: I have a `flake.nix` file with the following contents:
```nix
{
  description = "My Lean Package";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  inputs.lean4.url = "github:leanprover/lean4";
  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, nixpkgs, lean4, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        leanPkgs = lean4.packages.${system};

        lean-stdlib = leanPkgs.buildLeanPackage {
          name = "Std";
          src = pkgs.fetchFromGitHub {
            owner = "leanprover";
            repo = "std4";
            rev = "5507f9d8409f93b984ce04eccf4914d534e6fca2";
            sha256 = "0gyflmiisnxhy488z1fr50h7f60f1lqz1ffqzns880zx7407lwsk";
          };
        };

        lean-qq = leanPkgs.buildLeanPackage {
          name = "Qq";
          src = pkgs.fetchFromGitHub {
            owner = "gebner";
            repo = "quote4";
            rev = "c71f94e34c1cda52eef5c93dc9da409ab2727420";
            sha256 = "1p782kvxr0a838v2j02nqph0lyngv98c3qngc0xv8vmb4jbmg3ap";
          };
        };

        lean-aesop = leanPkgs.buildLeanPackage {
          name = "Aesop";
          deps = [ lean-stdlib ];
          src = pkgs.fetchFromGitHub {
            owner = "JLimperg";
            repo = "aesop";
            rev = "c68fb1d5a9172498230d81d95c61f6461bea6722";
            sha256 = "16gvidv5yr8dl9kmm599cszp6asph033macfpzi3bmg5zpyl34g4";
          };
        };

        lean-mathlib = leanPkgs.buildLeanPackage {
          name = "Mathlib";
          deps = [ lean-stdlib lean-qq lean-aesop ];
          src = pkgs.fetchFromGitHub {
            owner = "leanprover-community";
            repo = "mathlib4";
            rev = "98f40c35a2da7b450c5908784b6dcc20ba32ec3d";
            sha256 = "0hpkmg6887w6b461y2m0n895p6dvlqnjhacpj647bj2ml8x15zdp";
          };
        };

        lean-mypkg = leanPkgs.buildLeanPackage {
          name = "MyPackage";
          deps = [ lean-stdlib lean-mathlib ];
          src = ./.;
        };

      in {
        devShells.default = pkgs.mkShell {
          packages = with leanPkgs; [ lean-all vscode lean-mypkg.modRoot ];
        };
      });
}
```
I basically had to hardcode the deps between the various repos (std4, quote4, mathlib4, etc.). Along with [nix-direnv](https://github.com/nix-community/nix-direnv#flakes-support), this will let you have a lean workflow that's scoped to a directory.

**Comment by jcommelin** [comment]
This pull request has not seen any activity for quite a while, and it does not pass all CI checks. For these reasons, I am closing it now.

If you are still interested in getting this PR merged, please re-open the PR, update the branch, and make sure that all CI checks pass, Please label the PR with `awaiting-review` when ready.

**Pull request closed without merging**
