### PR TITLE
[Merged by Bors] - chore: bump to nightly-2023-02-03

### PR DESCRIPTION
**Pull request by hrmacbeth**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by hrmacbeth** [comment]
For the record, the following works on current master and is broken by the bump:
```lean
import Mathlib.Data.Int.Order.Basic

example {n : ℤ} (hn : n ≤ 1) : n ^ 2 < 2 :=
  calc
    n ^ 2 ≤ 1 ^ 2 := sorry
    _ < 2 := sorry
/-
invalid 'calc' step, failed to synthesize `Trans` instance
  Trans LE.le LT.lt ?m.548
-/
```
This is the https://github.com/leanprover/lean4/issues/2040/https://github.com/leanprover/lean4/issues/2073 trade-off again.

**Comment by hrmacbeth** [comment]
The above issue was filed as https://github.com/leanprover/lean4/issues/2079 and fixed, thanks @gebner !  Have updated the PR to catch the nightly with that fix.

**Review by dupuisf — COMMENTED** [review]
Thanks!

bors r+

**Comment by hrmacbeth** [comment]
Some problem in `Combinatorics/Young/YoungDiagram`, I'll fix later.

**Comment by hrmacbeth** [comment]
I tracked down the things that broke to
https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/calc.20unification
https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Special.20sauce.20in.20List.2Eget.3F
so now I'm going to merge.

**Pull request closed without merging**
