### PR TITLE
[Merged by Bors] - feat: port NumberTheory.LegendreSymbol.ZModChar

### PR DESCRIPTION
**Pull request by nick-kuhn**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by nick-kuhn** [comment]
> 

Also, the time spent compiling the proofs is still quite bad.

**Comment by Parcly-Taxel** [comment]
@nick-kuhn Please be aware that `start-port.sh` can get the capitalisation of names wrong, and that it is better to follow precedent (Ctrl-F for existing conventions) rather than just letting things be.

**Comment by Parcly-Taxel** [comment]
I've also bumped _slightly_ `maxHeartbeats` for the two mod-8 character defs, which makes things a little breezier and definiely nicer.

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
