### PR TITLE
[Merged by Bors] - feat: port RingTheory.Localization.NumDen

### PR DESCRIPTION
**Pull request by int-y1**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by int-y1** [comment]
1 simpNF linter message left

**Comment by ChrisHughes24** [comment]
Is there some reason for the rename `denom` -> `den`?

**Comment by Parcly-Taxel** [comment]
> Is there some reason for the rename `denom` -> `den`?

The two fields of the `Rat` type in mathlib4 are `num` and `den`, whereas the latter was `denom` in mathlib3. Do you want it changed back to `denom` here?

**Comment by ChrisHughes24** [comment]
That sounds like a good reason.

bors r+

**Pull request closed without merging**
