### PR TITLE
feat: Notation `≤∧≥` for `AntisymmRel (· ≤ ·)`

### PR DESCRIPTION
**Pull request by vihdzp**
---

See [Zulip](https://leanprover.zulipchat.com/#narrow/channel/287929-mathlib4/topic/Notation.20for.20AntisymmRel/near/485545682).

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by vihdzp** [comment]
I've only ever seen it used in that context a handful of times ever. I think it's pretty easy to look past that and instead read `⋚` as both `≤` and `≥` at the same time.

Another idea I had was to use either `≤≥` or `≥≤`, though that reads as being much more obviously made up to me.

**Comment by eric-wieser** [comment]
Some other prior art here is the C++ `x <=> y` operator, which means `compare x y`, and is arguably the ascii version of `⋚`.

**Comment by vihdzp** [comment]
I think there's a reason we don't use `<=>` in Lean. In C++ all the comparison operators just return an `int`, and the same is true for `<=>`. In Lean they return a `Prop`, whereas `cmp` returns an `Ordering`. So our convention is more alike [Rust](https://doc.rust-lang.org/std/cmp/trait.Ord.html#tymethod.cmp) instead. Maybe that means using the `⋚` symbol causes no ambiguity here?

**Comment by eric-wieser** [comment]
> In C++ all the comparison operators just return an `int`, and the same is true for `<=>`.

Strictly this isn't true, `<=>` returns a [`std::strong_ordering`](https://en.cppreference.com/w/cpp/utility/compare/strong_ordering) or any number of similar types, depending on the strength of the ordering.

**Comment by vihdzp** [comment]
Well, are there any other suggestions? I'm not particularly beholden to `⋚`, I just don't want to write `AntisymmRel (· ≤ ·) a b` over and over.

**Comment by eric-wieser** [comment]
https://math.stackexchange.com/q/482499/1896 has some similar notation suggestions

**Comment by vihdzp** [comment]
Note that comparability isn't the same thing as the antisymmetrization relation. Also note that the symbols `≶` and `⋚` are distinct! Not sure what this all implies.

**Comment by eric-wieser** [comment]
Just to check `a ≸ b` is problematic for you because it only means the right thing in a preorder?

**Comment by vihdzp** [comment]
Actually, `a ≸ b` doesn't mean the right thing except in the very specific case of a preorder whose antisymmetrization is a linear order. Generally, `¬ a < b ∧ ¬ b < a` can also be satisfied when `a` and `b` are incomparable.

**Comment by kim-em** [comment]
My vote is just for no notation. Notation like this is easier on the writer, perhaps, but in my opinion harder on the reader. So just do the work. :-)

**Comment by eric-wieser** [comment]
I think I could support a `scoped` notation here, but probably @YaelDillies should chime in too.

**Comment by YaelDillies** [comment]
I personally think it is so niche to write `AntisymmRel` that no notation is okay

**Comment by vihdzp** [comment]
> I personally think it is so niche to write `AntisymmRel` that no notation is okay
Conversely, maybe it's niche precisely because of how hard it is to write? ;)

However niche it might be in general, I still have to write this at least a few dozen times in order to generalize the `PGame.Equiv` API to other preorders. So even a local notation would be very convenient.

Niels on the Xena Discord suggested `≗` as a notation (read as order equivalent). I like this: it's both a senseless symbol with no risk of ambiguity, but the notation also makes sense. What do you think about making this into a scoped notation?

**Comment by vihdzp** [comment]
The Zulip poll overall shows a preference for no notation. I'll close this PR and rework the other `AntisymmRel` PR I currently have open.

**Pull request closed without merging**
