### PR TITLE
[Merged by Bors] - feat(CategoryTheory/Comma): limit properties of subcategories defined by morphism properties

### PR DESCRIPTION
**Pull request by chrisflav**
We show that under suitable assumptions on `P` the full subcategory of `Over X` defined by `P` has terminal objects and pullbacks.

---

- [x] depends on: #18088

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by erdOne — APPROVED** [review]
I think most of them still hold when replacing `⊤` by arbitrary properties up to some condition, but I don't think they would be useful in the near future.
Thanks! 
maintainer merge

**Comment by joelriou** [comment]
Thanks!

bors merge

**Comment by kim-em** [comment]
Could you please take a look at all the import regressions described in https://github.com/leanprover-community/mathlib4/pull/18134#issuecomment-2432826861?

I don't think we should be merging (or even maintainer merging) PRs with large import regressions until there has been some investigation into how/if this can be avoided.

**Comment by chrisflav** [comment]
Sorry for ignoring the `large-imports` label, in this case I thought it was okay since the lemma `over_iso_iff` seemed to me at the right place there right next to `arrow_iso_iff`. I now moved it to a later file.

Maybe someone should either cancel whatever bors is still doing on this PR or give it another go.

**Comment by joelriou** [comment]
As far as I can remember, it had seemed to me the increase in imports was relatively moderate. Thanks for fixing it!

bors merge

**Pull request closed without merging**
