### PR TITLE
feat: Decomposing a submodule of a product

### PR DESCRIPTION
**Pull request by YaelDillies**
From PFR

Co-authored-by: hi@llllvvuu.dev

---

I'm sure this can be improved, but I'm not sure how. I need guidance.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ADedecker** [comment]
I don't really know the use case, but the underlying result I see is that any submodule `S` of `A × B` decomposes as the direct sum of its intersection with `B` and its intersection with the graph of some linear map from `A` to `B`. This linear map is obtained by taking a section of the surjective map `S →ₗ[R] (map (LinearMap.fst R A B) S)` and extending that section to a map from `A` to `B`.

Composing with the obvious linear equiv between the graph of a linear map and its domain gets you the result.

But maybe this just makes things harder to use in practice.

**Comment by YaelDillies** [comment]
> the underlying result I see is that any submodule `S` of `A × B` decomposes as the direct sum of its intersection with `B` and its intersection with the graph of some linear map from `A` to `B`.

Yes, that's exactly right.

> Composing with the obvious linear equiv between the graph of a linear map and its domain gets you the result.
> 
> But maybe this just makes things harder to use in practice.

I think that's the right approach. How would you state the theorem and prove it?

**Comment by loefflerd** [comment]
Hmm. I promised I'd look at this, but on looking at it, I realise you're not actually proving the same lemma I thought you were proving.

What I _thought_ was going on was the following:
```lean
variable {R A B : Type*} [Ring R] [AddCommGroup A] [AddCommGroup B]
  [Module R A] [Module R B]

/--
**Goursat's Lemma**: given `R`-modules `A, B`, and a submodule `V ⊆ A × B`, there are submodules
`A' ⊆ A` and `B' ⊆ B`, and an equivalence `f : A / A' ≃ B / B'`, such that `V` is precisely the
preimage in `A × B` of `graph f ⊆ A' × B'`.
-/
theorem exists_equiv_fstMod_sndMod (V : Submodule R (A × B)) 
    (hv₁ : Surjective (Prod.fst ∘ V.subtype)) (hv₂ : Surjective (Prod.snd ∘ V.subtype)):
    ∃ (A' : Submodule R A) (B' : Submodule R B) (f : (A ⧸ A') ≃ₗ[R] (B ⧸ B')),
    ∀ p : A × B, p ∈ V ↔ f ⟦p.1⟧ = ⟦p.2⟧ := sorry
```

This is a rather cleaner and more symmetric statement than the one you're proving; and it's clearly a lemma which Mathlib ought to have, and apparently doesn't yet. But it isn't the same lemma as the one you're proving here. Do you think there's a prospect of deriving the lemma you're proving from this one?

**Comment by loefflerd** [comment]
(BTW, I made a PR for Goursat's lemma here: #18667. But I haven't yet got around to checking whether my speculation is correct that the result you're proving here is derivable from Goursat.)

**Comment by YaelDillies** [comment]
The result in this PR is actually used to prove a Goursat-like statement in PFR. See [the Lean code](https://github.com/teorth/pfr/blob/a3de43bd735cb17b74c1fcda6cadd5babea10896/PFR/HomPFR.lean#L35-L58) and [the blueprint entry](https://teorth.github.io/pfr/blueprint/sect0009.html#a0000000287).

I don't quite see how to deduce that Goursat-like statement from usual Goursat because usual Goursat only gives us info about the subgroup once we take its image in some quotient, while here we want to describe `H` precisely. Unless, I've missed something the quotient map really does lose some information.

In case it turns out useful, I have now proved Goursat for subgroups (#18823), depending on the vertical line test for monoid homs (#18822).

**Comment by YaelDillies** [comment]
Oh! Sorry, I just spent several hours proving Goursat 🙈

**Comment by loefflerd** [comment]
Oops, sorry! I should have posted here when I made the PR. Your Goursat is not the same as mine, though: yours is better, since you prove it for (possibly non-commutative) groups, while my proof at #18667 only works for modules over a ring.

FWIW, I'm not sure I agree with your comment:

> usual Goursat only gives us info about the subgroup once we take its image in some quotient

Goursat provides you with an isomorphism between quotients whose _preimage_ is the given subgroup. That's a complete characterisation of the given subgroup, it loses nothing. It isn't just saying that the _image_ of the given subgroup in the quotient is the graph of some isomorphism, which would indeed be a weaker statement.

**Comment by YaelDillies** [comment]
> yours is better, since you prove it for (possibly non-commutative) groups, while my proof at #18667 only works for modules over a ring.

Mine doesn't have linearity of the map, nor the version where the projections are not surjective, although I suspect both are easy to deduce from what I have. Feel free to push to my Goursat branch

**Comment by YaelDillies** [comment]
I will close this for now because I think I can bypass this weird result in PFR

**Pull request closed without merging**
