### PR TITLE
[Merged by Bors] - chore: split `NumberTheory.NumberField.CanonicalEmbedding`

### PR DESCRIPTION
**Pull request by BoltonBailey**
#8361 indicates that this is the most compute-intensive file on the longest pole for compiling Mathlib. It's bottlenecked dependency is `Mathlib.MeasureTheory.Measure.Lebesgue.VolumeOfBalls`, and this import isn't used until the second half of the file, in the sections regarding convex bodies. I am therefore splitting the file at that point, from the context of the file it seems to me that this is a sensible split anyway.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Bystander's question: how come the diff is -600, + 1100 lines? You are just moving code, right?

**Comment by BoltonBailey** [comment]
Because I haven't deleted the lemmas I duplicated  when I copied the file yet.

**Comment by BoltonBailey** [comment]
!bench

**Comment by BoltonBailey** [comment]
!bench

**Review by grunweg — APPROVED** [review]
I checked locally that this PR is just code motion (except for the header in the new file of course: copyright header, slightly longer module docstring and the local notation `"E" K`.

Looks plausible to me. Thanks for working on this split!

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by xroblot** [comment]
Sorry, I am bit late on this PR but I would rather make a new directory `CanonicalEmbedding` since I am planning to add more things about this soon. I'll make a PR to update this split if that's okay.

**Comment by xroblot** [comment]
#11917

**Pull request closed without merging**
