### PR TITLE
[Merged by Bors] - feat(CategoryTheory/Limits): epi/mono in functor categories

### PR DESCRIPTION
**Pull request by joelriou**
In this file, we obtain new versions of lemmas `NatTrans.mono_iff_mono_app` (resp. `NatTrans.epi_iff_epi_app`) when the category has pullbacks (resp. pushouts). The previous versions of these lemmas were deduced from the existence of adjunctions which relied on the existence of (co)products.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by joelriou** [comment]
The lemmas are duplicates...

**Comment by dagurtomas** [comment]
Do we really want to remove the old lemmas, rather than just rename them, since the new lemmas aren't generalizations of the old ones? Or am I misunderstanding?

**Comment by joelriou** [comment]
> Do we really want to remove the old lemmas, rather than just rename them, since the new lemmas aren't generalizations of the old ones? Or am I misunderstanding?

I have put the old lemmas back, as `epi_iff_epi_app'`, etc.

**Comment by dagurtomas** [comment]
Thanks!

maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
