### PR TITLE
[Merged by Bors] - feat: port Data.Fintype.Quotient

### PR DESCRIPTION
**Pull request by Komyyy**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib#18315
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by collares** [comment]
It seems that the related mathlib3 changes (mathlib#18417 and mathlib#19050, for example) will already require forward porting. Would it be better to forward port the whole thing once it is done?

**Comment by Komyyy** [comment]
@collares  It seems desirable to forward the whole thing once #18315 is merged.

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
