### PR TITLE
[Merged by Bors] - chore (AlgebraicGeometry.PrimeSpectrum): move results not requiring Zariski topology to files in `RingTheory`

### PR DESCRIPTION
**Pull request by mattrobball**
Results from `AlgebraicGeometry` are used back in `RingTheory` with many unecessary imports coming along with it. We move all possible results from `AlgebraicGeometry.PrimeSpectrum.Basic` and `AlgebraicGeometry.PrimeSpectrum.Noetherian` to a new file `RingTheory.PrimeSpectrum` and all possilbe results from `AlgebraicGeometry.PrimeSpectrum.Maximal` to a new file `RingTheory.MaximalSpectrum`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by semorrison** [comment]
Would you be able to add some `assert_not_exists` to make sure we don't backslide?

**Comment by semorrison** [comment]
bors d+

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
