### PR TITLE
[Merged by Bors] - chore: bump Std to leanprover/std4#541

### PR DESCRIPTION
**Pull request by kim-em**
Notable changes: lemmas were added in https://github.com/leanprover/std4/pull/538 about `gcd` and `lcm`, that now have implicit arguments. Mostly this is a positive change in Mathlib, we can just delete the arguments. The one to consider in review is in [`ModEq`](https://github.com/leanprover-community/mathlib4/pull/9828/files#diff-bf7908935cfca2e7d7959ec20d701fcda99586d0b7620b05b0a803988fdbd4fc).

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
What was the rationale for making the arguments implicit in Std?

**Comment by semorrison** [comment]
> What was the rationale for making the arguments implicit in [leanprover/std4#538](https://github.com/leanprover/std4/pull/538)?

No rationale, it was done without reference to what mathlib was doing. i.e. I wrote them from scratch and took advantage of autoImplicit. :-) I'm happy to switch back if there is a reason to.

I do want a quick resolution on this PR, because I can't update `bump/v4.6.0` until Mathlib `master` is using the HEAD of Std's `main` again, and this will cause problems the longer it is delayed.

Thus if you, or any maintainer, says "the change to implicit argument is bad", then I will promise to change them back, but not here.

**Comment by PatrickMassot** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
