### PR TITLE
[Merged by Bors] - chore: add source information to `maintainer merge` Zulip message

### PR DESCRIPTION
**Pull request by adomani**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
maintainer merge

**Comment by adomani** [comment]
maintainer merge

**Review by adomani — COMMENTED** [review]
And now from review and mobile

maintainer merge

**Review by jcommelin — COMMENTED** [review]
Let's try this out

bors merge

**Comment by jcommelin** [comment]
bors merge

**Pull request closed without merging**
