### PR TITLE
[Merged by Bors] - chore(test/toAdditive): remove commented test

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
@alexjbest : please check that this test is doing what it is supposed to ported from:

https://github.com/leanprover-community/mathlib/blob/65a1391a0106c9204fe45bc73a039f056558cb83/test/to_additive.lean#L86

Can also be proved with `rfl` I suppose..

**Comment by alexjbest** [comment]
Unfortunately I no longer understand what the old test was meant to do, beyond that its surely checking that the additive versions of some lemmas have the norm_cast attribute. If `norm_cast` includes a call to rfl then I guess the test is useless as is. But I don't know if it does

**Comment by mo271** [comment]
I don't know what `norm_cast` does exactly. Here 
`show_term{norm_cast}` gives
```
exact Eq.mpr (id Mathlib.Algebra.Group.Units._auxLemma.2) (of_decide_eq_true (Eq.refl true))
```
and `show_term{rfl}` gives 
```
exact Eq.refl
  ↑(AddUnits.mkOfAddEqZero 0 0 (of_eq_true ((congrFun (congrArg Eq (add_zero 0)) 0).trans (eq_self 0))))
```

Adding back the test does not hurt I suppose, but I'd also be happy to remove it.
What should we do, @alexjbest?

**Comment by alexjbest** [comment]
I think removing it is probably best. That generated term doesnt look like its doing what was intended anyway, which is fine as it finds a proof but it sounds like its using decidablity which is stronger than the lean 3 version anyway

**Comment by alexjbest** [comment]
maintainer merge

**Comment by jcommelin** [comment]
I suppose this is a "commented test" instead of an "uncommented test"? Please update the PR title.

bors d+

**Pull request closed without merging**
