### PR TITLE
[Merged by Bors] - feat port Data.Int.Gcd

### PR DESCRIPTION
**Pull request by riccardobrasca**
fc2ed6f838ce7c9b7c7171e58d78eaf7b438fb0e

- [x] depends on #1040  
- [x] depends on #1043
- [x] depends on #1050 
- [x] depends on #1055

### CODE REVIEW

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by riccardobrasca** [comment]
bors merge

**Comment by riccardobrasca** [comment]
bors merge

**Pull request closed without merging**
