### PR TITLE
perf(Algebra.CharTwo/Zero): scope lemmas 

### PR DESCRIPTION
**Pull request by mattrobball**
These have very general keys but narrow application. We scope them to their namespaces.

In particular, the `no_index`ed `ofNat` simp theorems are now explicitly opted into. If the handling of `ofNat` changes in core, this makes it easy to update.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
> Here are the [benchmark results](http://speed.lean-fro.org/mathlib4/run-detail/c535d7a7-2c9f-4d9d-afa2-b23ef2a17e69) for commit [754a204](https://github.com/leanprover-community/mathlib4/commit/754a2040263dd3a4978471f27cafcbbb63b33b81). There were [no significant changes](http://speed.lean-fro.org/mathlib4/compare/085156a8-725b-499f-b0b5-4b868c90fc3b/to/c535d7a7-2c9f-4d9d-afa2-b23ef2a17e69) against commit [2edef7d](https://github.com/leanprover-community/mathlib4/commit/2edef7d509a7aeba89793a84905121a9f19171b6).

Dropped total instructions by 200B and linting instructions by 100B/1%

**Comment by j-loreaux** [comment]
While I like the idea of this, I feel like it's going to be hard to remember, and annoying to need to explicitly open this scope. What I suspect is likely is that people are going to expect a `simp` lemma to be capable of handling something, it will fail, and they'll have no idea why.

It was necessary to `open scoped ofNat in` many places.

**Comment by mattrobball** [comment]
Let me split the CharTwo/CharZero scoping and the OfNat issues. 

There is some hope that the core issues with handling of OfNat will be resolved at some point. I will say more on the split.

**Comment by mattrobball** [comment]
#15631 does everything but the `OfNat` simp theorems and should be straightforward

**Comment by mattrobball** [comment]
#15631 and #15676 achieve most of the performance gains with no downsides. 

Closing this

**Pull request closed without merging**
