### PR TITLE
feat(MeasureTheory/Measure/WithDensity): add `withDensity_ae_eq`

### PR DESCRIPTION
**Pull request by gaetanserre**
For a given density `d`, if it is a.e. nonnegative, then, for any functions `f` and `g`, `f =ᵐ[μ.withDensity d] g ↔ f =ᵐ[μ] g`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by JasonKYi** [comment]
Can you replace the current `withDensity_absolutelyContinuous'` with the following:
```lean
lemma withDensity_absolutelyContinuous'' {μ : Measure α} {f : α → ℝ≥0∞}
    (hf : AEMeasurable f μ) (hf_ne_zero : ∀ᵐ x ∂μ, f x ≠ 0)  :
    μ ≪ μ.withDensity f := by
  refine Measure.AbsolutelyContinuous.mk (fun s hs hμs ↦ ?_)
  rw [withDensity_apply _ hs, lintegral_eq_zero_iff' hf.restrict, 
    ae_eq_restrict_iff_indicator_ae_eq hs, Set.indicator_zero', Filter.EventuallyEq, ae_iff] at hμs
  simp only [ae_iff, ne_eq, not_not] at hf_ne_zero
  simp only [Pi.zero_apply, Set.indicator_apply_eq_zero, not_forall, exists_prop] at hμs 
  have hle : s ⊆ {a | a ∈ s ∧ ¬f a = 0} ∪ {a | f a = 0}
  . exact fun x hx ↦ or_iff_not_imp_right.mpr <| fun hnx ↦ ⟨hx, hnx⟩
  exact measure_mono_null hle <| nonpos_iff_eq_zero.1 <| le_trans (measure_union_le _ _) 
    <| hμs.symm ▸ zero_add _ |>.symm ▸ hf_ne_zero.le
```
and then your lemma is then simply 
```lean 
theorem withDensity_ae_eq {f g : α → β} {d : α → ℝ≥0∞}
    (hd : AEMeasurable d μ) (h_ae_nonneg : ∀ᵐ x ∂μ, d x ≠ 0) :
    f =ᵐ[μ.withDensity d] g ↔ f =ᵐ[μ] g := by
  refine ⟨fun h ↦ Measure.AbsolutelyContinuous.ae_eq ?_ h, 
    fun h ↦ Measure.AbsolutelyContinuous.ae_eq (withDensity_absolutelyContinuous μ d) h⟩
  refine withDensity_absolutelyContinuous'' hd  h_ae_nonneg 
```
Note that with this you only need ae measurability

**Comment by gaetanserre** [comment]
Thank you for your suggestion. It indeed relax the Measurable hypothesis on `d`. By the way, I was able to show 
```lean
theorem withDensity_apply_eq_zero' {f : α → ℝ≥0∞} {s : Set α} (hf : AEMeasurable f μ) :
    μ.withDensity f s = 0 ↔ μ ({ x | f x ≠ 0 } ∩ s) = 0
```
which is basically the same as `withDensity_apply_eq_zero` but relaxing the Measurable assumption. It makes the proof of `withDensity_apply_eq_zero` way simpler:
```lean
theorem withDensity_apply_eq_zero {f : α → ℝ≥0∞} {s : Set α} (hf : Measurable f) :
    μ.withDensity f s = 0 ↔ μ ({ x | f x ≠ 0 } ∩ s) = 0 :=
  withDensity_apply_eq_zero' <| Measurable.aemeasurable hf
```
I will probably be able to prove `ae_withDensity_iff'` and `ae_withDensity_iff_ae_restrict'` and probably more using only AEMeasurable assumption. Do we want that?

**Comment by JasonKYi** [comment]
Yes, if you are able to relax the conditions that'd be great

**Comment by gaetanserre** [comment]
Ok, I'll do another PR for everything. Thanks!

**Pull request closed without merging**
