### PR TITLE
[Merged by Bors] - Congruence subgroup namespace

### PR DESCRIPTION
**Pull request by CBirkbeck**
Put congruence subgroups into their own namespace, so that things like `Gamma` don't live in the root namespace.

---

- [x] depends on : #14572 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by loefflerd** [comment]
LGTM. I don't know why the bot removed the "blocked by other PR" label, though. 

Maintainers: please merge this **once #14572 is in**.

maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors d+

**Pull request closed without merging**
