### PR TITLE
doc(Tactic): add docstrings for a few lemmas

### PR DESCRIPTION
**Pull request by pitmonticone**
Add docstrings for a few lemmas.

I believe this accessible, clear, explicit, unambiguous documentation style could really help a lot Lean/Mathlib beginner users. 

If it's considered good enough, I will do the same for as many definitions and theorems as I can when I find the time.

### CODE REVIEW

**Comment by grunweg** [comment]
As I said on the other PR, I personally prefer more succint docstrings. I presume this matches the target audience of mathlib better.

That said: thank you for adding documentation; this is valuable! (If you're looking for particular targets, both adding/extending module docstrings as well as documention missing definitions and notation (see the nolints.json for hints) is very useful.)

**Comment by pitmonticone** [comment]
> As I said on the other PR, I personally prefer more succinct docstrings. I presume this matches the target audience of mathlib better. (This might be just my personal opinion.)

I totally get your perspective, but I still tend to adhere to the motto "the more pedantic, the better" 😆. 
We could launch a poll on Zulip 😆.  

> That said: thank you for adding documentation; this is valuable! (If you're looking for particular targets, both adding/extending module docstrings as well as documention missing definitions and notation (see the nolints.json for hints) is very useful.)

Thank you for your extensive and educational reviews. I will certainly tackle both the remaining `ERR_MOD` and `docBlame` in the next days.

**Comment by j-loreaux** [comment]
@pitmonticone thanks for thinking of this. And in general, we definitely prefer more documentation. But in this specific case, I don't think these docstrings add anything beyond what exists in the statement of the lemmas themselves.

I'm marking as `awaiting-author` for now, but probably this can just be closed. I'll let you close it unless you have further discussion you want to happen about it.

**Comment by pitmonticone** [comment]
Hi @j-loreaux, thanks for your comment.

I've nothing to add.

**Comment by j-loreaux** [comment]
In that case, I think you should open an RFC issue instead of a PR. And please clearly explain the goals in that issue, potentially using these as examples.

**Comment by pitmonticone** [comment]
Ok, thank you @j-loreaux. 

I close this PR.

**Pull request closed without merging**
