### PR TITLE
[Merged by Bors] - feat: port Analysis.Calculus.Deriv.Support

### PR DESCRIPTION
**Pull request by urkud**
---

Github shows `Deriv.Basic` as a part of this PR. In fact, the first commit in the history is already in `master`. I don't know how to fix this. Please ignore that file.

- [x] depends on: #4434

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4434~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by urkud** [comment]
Avoiding merge conflicts on the queue:
bors r-

**Comment by fpvandoorn** [comment]
Interesting that `Basic` is shown in the files changed tab. Note that it shows the diff correctly here:
https://github.com/leanprover-community/mathlib4/compare/port/Analysis.Calculus.Deriv.Support

**Comment by urkud** [comment]
@fpvandoorn I rebased on `origin/staging` before that commit was merged. Probably, this was a bad idea.

**Comment by urkud** [comment]
bors merge

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
