### PR TITLE
[Merged by Bors] - feat: make `discrete_of_t1_of_finite` an instance and rename

### PR DESCRIPTION
**Pull request by j-loreaux**
Also adds the lemma `Set.Finite.continuousOn` which seems to be missing.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by j-loreaux** [comment]
we should benchmark this when CI is done to make sure any instance loops created don't cause problems.

**Comment by grunweg** [comment]
As CI is done, let me benchmark this as mentioned above. (Let me know if this is unwanted and I'll stop!!)

**Comment by grunweg** [comment]
!bench

**Comment by dupuisf** [comment]
Thanks!

bors r+

**Pull request closed without merging**
