### PR TITLE
[Merged by Bors] - chore: remove `include/omit` porting notes

### PR DESCRIPTION
**Pull request by adomani**
See [this Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Addressing.20porting.20notes.3F/near/421342495).

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
maintainer merge

**Comment by mattrobball** [comment]
cf leanprover/lean4#2452

**Comment by mattrobball** [comment]
Thanks! Once it clears CI, please summon the bot. 

bors delegate+

**Pull request closed without merging**
