### PR TITLE
[Merged by Bors] - chore: rename LocalHomeomorph to PartialHomeomorph

### PR DESCRIPTION
**Pull request by grunweg**
`LocalHomeomorph` evokes a "local homeomorphism": this is *not* what this means.
Instead, this is a homeomorphism on an open set of the domain (extended to the whole space, by the junk value pattern). Hence, partial homeomorphism is more appropriate, and avoids confusion with `IsLocallyHomeomorph`.

A future PR will rename `LocalEquiv` to `PartialEquiv`.

[Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Naming.20around.20local.20homeomorphisms/near/407090631)

---

Best reviewed commit by commit: each commit message clearly states what's in it.

### CODE REVIEW

**Review by alreadydone — APPROVED** [review]
Thanks! LGTM

Renaming LocalEquiv to PartialEquiv also sounds good to me; fortunately the name was not taken by [PEquiv](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Data/PEquiv.html#PEquiv), the same concept with a different design.

**Comment by grunweg** [comment]
Wow, you're fast :-) Thanks for the fast approval!

**Comment by fpvandoorn** [comment]
Unfortunately it also got a merge conflict quickly...

**Comment by fpvandoorn** [comment]
Thanks! This was on my "should be done eventually"-list for a while.

Let's try to merge this quickly. Please merge master, and merge with `bors r+` if the checkmark is green.

bors d+

**Comment by grunweg** [comment]
Builds and tests pass, so... bors r+
Thank you for the fast review!

**Pull request closed without merging**
