### PR TITLE
feat: Convert functions between subsets to functions between types

### PR DESCRIPTION
**Pull request by shuxuezhuyi**
We define `Function.toval` and provide some relevant APIs.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by shuxuezhuyi** [comment]
Discussion on Zulip : https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/Convert.20functions.20between.20subsets.20to.20functions.20between.20types

**Comment by YaelDillies** [comment]
Same thing here. There's no evidence that your `Function.toval` makes anything easier in your application (in fact I think it doesn't even apply), so I believe this should not be merged and that you should instead use `Function.extend` directly.

**Comment by shuxuezhuyi** [comment]
@YaelDillies You can find an application of `Function.toval` in the proof of `StrictMonoOn.Ioo_continuous_extend_Icc` in https://github.com/leanprover-community/mathlib4/blob/fc5bea5b4c824410e7ffc1b6805dd08e5ec4619d/Mathlib/Topology/Algebra/Order/IccExtendFromIoo.lean

**Comment by shuxuezhuyi** [comment]
I have modified the statement and proof of `StrictMonoOn.Ioo_continuous_extend_Icc` in
https://github.com/leanprover-community/mathlib4/blob/1e418f49f853255c6b63a6bf760e35fa8c079507/Mathlib/Topology/Algebra/Order/IccExtendFromIoo.lean , but I still use `Function.toval`.

**Comment by shuxuezhuyi** [comment]
You can find another application of `Function.toval` in the proof of `Homeomorph.Ioo_extend_Icc` in https://github.com/leanprover-community/mathlib4/blob/0959c896fd0c72bc4c226df5986a7561f88bf594/Mathlib/Topology/Algebra/Order/IccExtendFromIoo.lean

**Comment by jcommelin** [comment]
@YaelDillies has demonstrated that we can use `Function.extend` instead of `Function.toVal`: https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/Convert.20functions.20between.20subsets.20to.20functions.20between.20types/near/394473880

I understand that you have been using `toVal` in some other code. But I think it is possible to convert this code to use `extend` instead.
It seems that this was discussed on zulip, but the link above no longer works...

**Comment by j-loreaux** [comment]
@shuxuezhuyi do you see how `Function.toval` isn't necessary and we can just use `Function.extend`? If so, I think this PR can be closed.

**Comment by shuxuezhuyi** [comment]
I've changed my mind. I agree we should close these PRs.

**Pull request closed without merging**
