### PR TITLE
[Merged by Bors] - chore: move `Init.Logic` and its remaining dependencies to `Deprecated`

### PR DESCRIPTION
**Pull request by Vierkantor**
The results in this file have been deprecated for a while and none seem to be used in Mathlib except for other deprecated results that aren't used either. So let's move everything to the `Deprecated` folder in order to empty out the `Init` folder.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Looks reasonable, thanks!
maintainer merge

**Review by jcommelin — COMMENTED** [review]
bors d+

I fear this will give a merge conflict in Mathlib.lean with the other PR. So let's put them in different bors batches.

**Comment by Vierkantor** [comment]
Looks like this will merge cleanly so:

bors merge

**Comment by Vierkantor** [comment]
It did not, in fact, merge cleanly :( Let's try again!

bors merge

**Comment by kim-em** [comment]
bors merge

**Pull request closed without merging**
