### PR TITLE
[Merged by Bors] - feat: port Data.Nat.Parity

### PR DESCRIPTION
**Pull request by urkud**
Backported in leanprover-community/mathlib#18221.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by urkud** [comment]
@jcommelin I think, we should wait till I resolve issues in the mathlib 3 PR and sync the changes back to mathlib 4.

**Review by Ruben-VandeVelde — APPROVED** [review]

**Comment by Ruben-VandeVelde** [comment]
This is ready.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
