### PR TITLE
[Merged by Bors] - feat: port AlgebraicGeometry.Morphisms.FiniteType

### PR DESCRIPTION
**Pull request by mattrobball**
---

- [x] depends on: #5663
[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5663
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
bors d+

**Comment by mattrobball** [comment]
bors merge

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5663~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
