### PR TITLE
feat: a deprecation tool

### PR DESCRIPTION
**Pull request by adomani**
###  `deprecate_to` -- a deprecation tool

Writing
```lean
deprecate_to id₁ id₂ ... idₙ 2024-02-23
theorem easy₁ : True := .intro
```
where `id₁ id₂ ... idₙ` is a sequence of identifiers adds to the environment the following aliases:
```lean
@[deprecated] alias easy₁ := id₁
@[deprecated] alias easy₂ := id₂
...
@[deprecated] alias easyₙ := idₙ
```
where `easy₁ easy₂ ... easyₙ` are the non-blacklisted declarations autogenerated by the initial theorem.

Some relevant Zulip threads:
* [deprecation automation](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/deprecation.20automation)
* [`Try this` with a sequence of commands](https://leanprover.zulipchat.com/#narrow/stream/239415-metaprogramming-.2F-tactics/topic/Try.20this.20with.20a.20sequence.20of.20commands)
* [`Mathlib` deprecation cycle](https://leanprover.zulipchat.com/#narrow/stream/345428-mathlib-reviewers/topic/Mathlib.20deprecation.20cycle)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by thorimur** [comment]
I like this! I do wonder if it should either
1. simply be a macro instead of a suggestion
2. or somehow record the command that generated it in its output.

(Either way, the infrastructure you've put in place would still work!)

But I think that this would be better to discuss on zulip. Can you please link to any topics in which this was discussed in the PR description?

**Comment by adomani** [comment]
@thorimur, I added some of the relevant Zulip discussions in the PR description!

I suspect that [deprecation automation](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/deprecation.20automation) is the most relevant.

**Comment by adomani** [comment]
I like a lot your idea of making this a `macro/elab`!  I still need to sort out a few changes:
1. the visible name should probably be the final one, not the one to be deprecated;
2. if everything else stays hidden (which is very good!), it is more important to get the old_name <--> new_name pairing correct.

For 2., I think that there may be a form of the syntax that prints out the pairing, so that you can check that they happened correctly.

This is a possibility
```lean
deprecated_names < ... old_names ... > "2024-03-05"
theorem new_names ...
```
with the optional `!` flag
```lean
deprecated_names! < ... old_names ... > "2024-03-05"
theorem new_name ...
--  also prints the pairing `old_names.zip new_names`
```

The date in this case would be mandatory, rather than optional.

**Comment by adomani** [comment]
@thorimur, I am very happy with the suggestion of making the command essentially a `macro` to auto-generate the deprecated `alias`es.

I converted the code of the previous version into this newer form.

**Comment by grunweg** [comment]
I just ran into a situation today where this tool would be really useful. Thank you for writing this; I look forward to seeing it land :-)

**Comment by semorrison** [comment]
@grunweg, could you explain that situation?

So far I'm skeptical this is actually an improvement over writing out `@[deprecated] alias`. Plus it's another way to same the same thing, which is a negative by itself.

**Comment by adomani** [comment]
@YaelDillies I suspect that the [file at this commit](https://github.com/leanprover-community/mathlib4/blob/ae9b03f5c25522614df9bc00e3933328b8d8b13d/Mathlib/Tactic/DeprecateMe.lean) is what you have in mind?  The code initially provided a `Try this` suggestion with all the deprecations and I think that the link above should be to the file at the commit before I changed it to a macro, instead of a `Try this` suggestion.

**Comment by YaelDillies** [comment]
Yep, seems like it! Mind switching back to that approach?

**Comment by adomani** [comment]
Yaël, I opened #13691 at the earlier commit, the one with the `Try this` suggestion.

**Comment by adomani** [comment]
I am closing this PR in favour of #13691.  If there is interest in this one, it can always be re-opened.

**Pull request closed without merging**
