### PR TITLE
[Merged by Bors] - perf: speedup using `Submodule.restrictScalars_mem` instead of relying on defeq

### PR DESCRIPTION
**Pull request by alreadydone**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alreadydone** [comment]
!bench

**Comment by alreadydone** [comment]
These two occurences were discovered because they timed out in another PR; maybe more are still hidden. Not sure who might know about more situations that could benefit from this. Maybe @erdOne?

**Comment by erdOne** [comment]
I feel like this defeq abuse(?) happen very often (and I'm definitely guilty of many of them) that I unfortunately cannot give you a list of where it occurs.

**Comment by riccardobrasca** [comment]
This looks like a positive change, thanks!

bors merge

**Pull request closed without merging**
