### PR TITLE
[Merged by Bors] - chore(Mathlib/Algebra/BigOperators/Basic): unscope `∑ x ∈ s, f x` notations

### PR DESCRIPTION
**Pull request by Komyyy**
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Unscoping.20big.20operators

---

- [x] depends on: #13269 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by loefflerd** [comment]
Looks reasonable to me.

maintainer merge

**Comment by sgouezel** [comment]
Should we remove all the `open scoped BigOperators` (or even `open BigOperators`) accordingly?

**Comment by loefflerd** [comment]
@sgouezel That's the next PR in the series. (I asked @Komyyy to separate the PR into chunks for ease of reviewing, so the next PR will be huge but completely mechanical.)

**Comment by sgouezel** [comment]
Then
bors r+
Thanks!

**Pull request closed without merging**
