### PR TITLE
[Merged by Bors] - perf (Data.Rat): reduce algebra instances for Rat

### PR DESCRIPTION
**Pull request by mattrobball**
This removes the `with` pattern from the `Field` and `CommSemiGroupWithZero` instances on `Rat`.

The resulting term decreases in size by an order of magnitude (at least).

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by eric-wieser** [comment]
Removing those comments seems fine to me. I think in the long run we should have a linter to catch diamonds here.

**Comment by eric-wieser** [comment]
bors d+

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
