### PR TITLE
[Merged by Bors] - feat: port LinearAlgebra.Dual

### PR DESCRIPTION
**Pull request by urkud**
---

I'm going to come back to this PR in a day or two. If you're going to work on this PR, then please leave a comment when you start working, then leave a comment when you stop working on it. ~~Working on it.~~ See [Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/LinearAlgebra.2EDual)

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
I'll start working on this for a little bit

**Comment by mo271** [comment]
I'm done for now..

**Comment by Parcly-Taxel** [comment]
My turn now?

**Comment by kmill** [comment]
I'll take a look now

**Comment by kmill** [comment]
It seems one workaround for this `simp_rw` issue is to use `conv` and `rw`, so I did that up until `evalEquiv`, which is having some sort of timeout issue.

It's likely what I did is not the optimal solution, but I don't really understand the root cause yet. At least `conv`/`rw` isn't introducing anything bad, since it's more-or-less a more precise version of `simp_rw`.

**Comment by urkud** [comment]
The root cause is described in [Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/LinearAlgebra.2EDual): `simp` uses discrimination trees, so it doesn't try to apply lemmas about `LinearMap`s to `Dual`s and vice versa.

**Comment by mattrobball** [comment]
Removing the timeouts is mainly what remains

**Comment by mattrobball** [comment]
Three timeouts to resolve. Two are ok with hearbeat bumps.

**Comment by semorrison** [comment]
Okay, let's go!

bors merge

**Pull request closed without merging**
