### PR TITLE
[Merged by Bors] - feat: add a Linters file

### PR DESCRIPTION
**Pull request by adomani**
Add a new file `Mathlib.Linters` that is intended to be the entry-point for all `Mathlib` linters.

This file currently contains only `Mathlib.Tactic.Lint` and is imported in `Mathlib.Common`.

As linters seem to be invisible by Shake for dependencies, I also made this file invisible to Shake by marking it as
* `ignoreAll`, meaning that all its imports are considered necessary;
* `ignoreImport`, meaning that where it is imported, it is considered necessary.

[Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Mathlib.2FTactic.2F*)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
I like this idea: the specifics of *how* implement this seem blocked on zulip. Let me mark this PR as such.

(I wonder whether importing this in `Tactic.Basic` would be better. But such details may depend on the zulip thread.)

**Review by kmill — APPROVED** [review]
Just like how `Tactic` is singular, I think perhaps it should be `Mathlib.Tactic.Linter`. Other than than minor quibble, this seems like a good idea.

**Comment by semorrison** [comment]
bors d+

**Pull request closed without merging**
