### PR TITLE
[Merged by Bors] - feat: port Order.Hom.Basic

### PR DESCRIPTION
**Pull request by kim-em**
mathlib3 git sha 62a5626868683c104774de8d85b9855234ac807c

- [x] depends on: #772 
- [x] depends on: #838

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#772
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by Ruben-VandeVelde** [comment]
Merging with #838 helps move things forward a bit, but nee

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#772~~
* ~~leanprover-community/mathlib4#838~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
