### PR TITLE
[Merged by Bors] - feat: port LinearAlgebra.Finrank

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
@Parcly-Taxel, I think the simpNF linter is probably correct here. I've created https://github.com/leanprover-community/mathlib/pull/18794 to test whether we can safely remove the offending lemmas.

**Comment by ChrisHughes24** [comment]
This can be merged after the corresponding [mathlib3 PR](https://github.com/leanprover-community/mathlib/pull/18794) is merged and the SHA is updated with the mathlib3 commit once it appears in master.

bors d+

**Comment by ChrisHughes24** [comment]
bors d-

**Comment by semorrison** [comment]
That (merging with master) was unpleasant. 

bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
