### PR TITLE
[Merged by Bors] - feat: port changes to `Cardinal` files

### PR DESCRIPTION
**Pull request by vihdzp**
My bad for letting these pile up.

* [`set_theory.cardinal.basic`@`4c19a16e4b705bf135cf9a80ac18fcc99c438514`..`e05ead7993520a432bec94ac504842d90707ad63`](https://leanprover-community.github.io/mathlib-port-status/file/set_theory/cardinal/basic?range=4c19a16e4b705bf135cf9a80ac18fcc99c438514..e05ead7993520a432bec94ac504842d90707ad63)
* [`set_theory.cardinal.continuum`@`3d7987cda72abc473c7cdbbb075170e9ac620042`..`e08a42b2dd544cf11eba72e5fc7bf199d4349925`](https://leanprover-community.github.io/mathlib-port-status/file/set_theory/cardinal/continuum?range=3d7987cda72abc473c7cdbbb075170e9ac620042..e08a42b2dd544cf11eba72e5fc7bf199d4349925)
* [`set_theory.cardinal.cofinality`@`bb168510ef455e9280a152e7f31673cabd3d7496`..`7c2ce0c2da15516b4e65d0c9e254bb6dc93abd1f`](https://leanprover-community.github.io/mathlib-port-status/file/set_theory/cardinal/cofinality?range=bb168510ef455e9280a152e7f31673cabd3d7496..7c2ce0c2da15516b4e65d0c9e254bb6dc93abd1f)
* [`set_theory.cardinal.ordinal`@`8da9e30545433fdd8fe55a0d3da208e5d9263f03`..`7c2ce0c2da15516b4e65d0c9e254bb6dc93abd1f`](https://leanprover-community.github.io/mathlib-port-status/file/set_theory/cardinal/ordinal?range=8da9e30545433fdd8fe55a0d3da208e5d9263f03..7c2ce0c2da15516b4e65d0c9e254bb6dc93abd1f)
* [`set_theory.ordinal.arithmetic`@`b67044ba53af18680e1dd246861d9584e968495d`..`e08a42b2dd544cf11eba72e5fc7bf199d4349925`](https://leanprover-community.github.io/mathlib-port-status/file/set_theory/ordinal/arithmetic?range=b67044ba53af18680e1dd246861d9584e968495d..e08a42b2dd544cf11eba72e5fc7bf199d4349925)

---

- [x] depends on: https://github.com/leanprover-community/mathlib/pull/18771
- [x] depends on: #3247

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3247
* leanprover-community/mathlib#18771
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib#18771~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib#18771~~
* ~~leanprover-community/mathlib4#3247~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by eric-wieser — APPROVED** [review]
bors merge

**Pull request closed without merging**
