### PR TITLE
[Merged by Bors] - feat(Algebra/Homology): study of the source of the associator isomorphism for the action of bifunctors on homological complexes

### PR DESCRIPTION
**Pull request by joelriou**
In this PR, we decompose the differential on a homological complex of the form `mapBifunctor (mapBifunctor K₁ K₂ F₁₂ c₁₂) K₃ G c₄` into three components.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by dagurtomas** [comment]
Thanks!

maintainer merge

**Comment by kim-em** [comment]
bors merge

**Comment by joelriou** [comment]
Retrying...

bors merge

**Comment by joelriou** [comment]
Retrying again...

bors merge

**Pull request closed without merging**
