### PR TITLE
[Merged by Bors] - chore (Data.Nat.GCD.Basic): minimize imports

### PR DESCRIPTION
**Pull request by mattrobball**
We avoid importing bundled ordered algebra classes by specializing to existing `Nat`-results, in this file about `Nat`. Then we run `#min_imports` to update the imports.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Can you fix the build, please? Feel free to maintainer merge on my behalf with that addressed.

**Comment by mattrobball** [comment]
Working on the effectful fix rather than the easy one atm

**Comment by mattrobball** [comment]
Ok. It should build now.

**Comment by grunweg** [comment]
Thanks!
maintainer merge

**Pull request closed without merging**
