### PR TITLE
[Merged by Bors] - feat: port CategoryTheory.Limits.Presheaf

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
TODO:
- [ ] in `extendAlongYoneda_map` and `restrictYonedaHomEquiv_natural` for some reason `ext` is not working as expected
- [ ] `isExtensionAlongYoneda`
- [ ] `colimitOfRepresentable`
- [ ] `natIsoOfNatIsoOnRepresentables`
- [ ] For the very last line: `invalid 'end', name mismatch`?

Help is appreciated!

**Comment by semorrison** [comment]
For the `ext` misbehaviour, I would like to see if merging #3340 changes anything. Assuming it persists, I guess we need to add an additional ext lemma for morphisms in the category of types (aka `funext`).

**Comment by kbuzzard** [comment]
I hacked my way around the `ext` failures, which probably isn't the right thing to do because they'll perhaps bite us again. I fixed all but one of the errors and added some porting notes.

**Comment by kbuzzard** [comment]
I need to stop doing Lean right now but I've just got the last proof to compile, by painfully taking apart what appears to be a nonconfluent simp set and doing everything in the right order. Obviously this needs to be fixed -- so please don't merge this yet -- but I have no time so I thought I'd just bank the proof and if nobody tidies it up within the next 24 hours I might have time to do it myself.

**Comment by kbuzzard** [comment]
I think that the "not sure what happened there" commit was in error -- I have no time to fix this right now. The file was compiling locally for me.

**Comment by semorrison** [comment]
> 8891f38

You accidentally undid my commit. I've fixed it.

**Comment by kbuzzard** [comment]
Thanks Scott and sorry! Was just rushing out the door but wanted get last proof up.

**Comment by ChrisHughes24** [comment]
> I hacked my way around the `ext` failures, which probably isn't the right thing to do because they'll perhaps bite us again. I fixed all but one of the errors and added some porting notes.

Can this be fixed by changing the priority of appropriate `ext` lemmas?

**Comment by kbuzzard** [comment]
@Parcly-Taxel is again doing their "change labels on other people's PR's" trick, but there is arguably a discussion to be had about the `ext` failures here before this is merged.

**Comment by semorrison** [comment]
I haven't looked at the `ext` failures here, but is it as simple as we're just missing some? `ext` uses a more restrictive indexing scheme now, so very often we just need additional lemmas whose syntactic form matches the use case (i.e. it might not be as complicated as priorities). I have to run soon, but I can try to look at this if no one has sorted it out in the meantime. :-)

**Comment by kbuzzard** [comment]
Modulo the git nightmare caused by @Parcly-Taxel this is now finally awaiting review. It is supposed to depend on #3593

**Comment by kbuzzard** [comment]
OK so this PR is finally ready. The changes in `Mathlib/CategoryTheory/Elements.lean` are I think some remnant of the recent force push -- they're nothing to do with this PR as far as I can see, and just appear to be whitespace changes.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
