### PR TITLE
 feat(Algebra/Order/GroupWithZero): add one_lt_zpow₀ and zpow_lt_zpow_right₀

### PR DESCRIPTION
**Pull request by judithludwig**
This PR adds the lemmas one_lt_zpow₀ and zpow_lt_zpow_right₀ to Algebra.Order.GroupWithZero.Canonical.lean .
Co-authored-by: Christian Merten (github: chrisflav).
Used in project Formalization of the Bruhat-Tits Tree. 

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by riccardobrasca** [comment]
!bench

**Comment by riccardobrasca** [comment]
What is the file suggested by `find_home!`?

**Comment by riccardobrasca** [comment]
@YaelDillies what do you think of the new import list?

**Comment by judithludwig** [comment]
> What is the file suggested by `find_home!`?

for `one_lt_zpow₀` it gives me [Mathlib.Analysis.Normed.Group.Basic, Mathlib.RingTheory.PowerSeries.Basic, Mathlib.LinearAlgebra.AffineSpace.MidpointZero, Mathlib.LinearAlgebra.AffineSpace.Ordered, Mathlib.Algebra.CharP.Basic, Mathlib.GroupTheory.OrderOfElement, Mathlib.RingTheory.MvPolynomial.Basic, Mathlib.Data.Matrix.CharP, Mathlib.ModelTheory.Algebra.Field.CharP, Mathlib.Algebra.CharP.Algebra, Mathlib.Data.Complex.Module] for the first lemma and
for the second one this:
[Mathlib.Algebra.Order.Ring.Cast, Mathlib.Data.Nat.Cast.SetInterval, Mathlib.Order.Interval.Finset.Box, Mathlib.Data.Int.SuccPred, Mathlib.Algebra.Order.Ring.Abs, Mathlib.Data.Int.Star].

**Comment by judithludwig** [comment]
> This lemma should probably not exist at all. Does `one_lt_zpow` not satisfy your needs? If not, I am currently doing a series of PRs unifying the `LinearOrderedField` and `LinearOrderedCommGroupWithZero` versions of lemmas. See eg #17215 and #17378.

Why do you think the lemma (I assume you are refering to `one_lt_zpow₀`) should not exist? 

`one_lt_zpow` seems to be for semifields, right?  
We are working with valuation rings and the target of a valuation is a `LinearOrderedCommGroupWithZero`. So this seems to be the right context.

**Comment by judithludwig** [comment]
I'm closing the PR as the lemmas [one_lt_zpow₀](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Algebra/Order/GroupWithZero/Unbundled.html#one_lt_zpow%E2%82%80) and [zpow_lt_zpow_right₀](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Algebra/Order/GroupWithZero/Unbundled.html#zpow_lt_zpow_right%E2%82%80) were added in the meantime by @YaelDillies.

**Pull request closed without merging**
