### PR TITLE
feat: port FieldTheory.Finite.Basic

### PR DESCRIPTION
**Pull request by riccardobrasca**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by riccardobrasca** [comment]
I am tagging this `help wanted ` just in case someone needs this file and wants to work on it, there is nothing really problematic about it. I don't have time for the rest of the day, I will finish it tomorrow.

**Comment by jcommelin** [comment]
Github doesn't want to show me the diff between mathport output and HEAD. I don't know why...

**Comment by riccardobrasca** [comment]
> Github doesn't want to show me the diff between mathport output and HEAD. I don't know why...

It's possible I've made something wrong with git (I run the script twice in two different days since I didn't realize mathport was not running). I redo everything from scratch and open a new PR (in addition to the automatically created commits, there will be only one commit fixing everything, but I don't think this is a problem).

**Comment by riccardobrasca** [comment]
Is [this](https://github.com/leanprover-community/mathlib4/pull/4583) better?

**Comment by jcommelin** [comment]
Thanks, I merged the other one.

**Pull request closed without merging**
