### PR TITLE
perf: improve elaboration of `FunLike.coe`

### PR DESCRIPTION
**Pull request by eric-wieser**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
Unless there have been relevant changes to core, the required fixes are the going to be the same as #7905, cf #8185.

**Comment by mattrobball** [comment]
I had certainly done that locally and thought I had pushed. Let me ping the author of #7905 over there. The main credit here goes to recognizing the problem and providing the first viable fix. The rest is just refinement

**Comment by eric-wieser** [comment]
I think `Co-authored-by` is sufficient for that; you went through the work of making all the fixes in that PR across 87 files!

**Comment by mattrobball** [comment]
I am still curious about the overall impact in exposing implicit arguments to `headBeta` beyond `CoeFun`

**Comment by eric-wieser** [comment]
Duplicate of #8185

**Pull request closed without merging**
