### PR TITLE
[Merged by Bors] - chore: adaptation to batteries#1055

### PR DESCRIPTION
**Pull request by fgdorais**
---

Once [batteries#1055](https://github.com/leanprover-community/batteries/pull/1055) is merged:

- [x] Edit lakefile to point to batteries/main
- [x] Run `lake update batteries`
- [x] Commit and merge

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by kim-em** [comment]
bors merge

**Comment by kim-em** [comment]
This will hold up nightly-testing, so:

bors p=10

**Comment by kim-em** [comment]
bors merge

**Comment by kim-em** [comment]
bors merge

**Comment by mattrobball** [comment]
bors merge

**Comment by mattrobball** [comment]
bors merge

**Comment by kim-em** [comment]
bors merge

**Pull request closed without merging**
