### PR TITLE
[Merged by Bors] - feat(NumberTheory/NumberField/Basic): lemmas for extension of ring of integers

### PR DESCRIPTION
**Pull request by mbkybky**
Add some lemmas and `instance`s for extension of number fields or ring of integers.

Co-authored-by: Yongle Hu @mbkybky
Co-authored-by: Jiedong Jiang @jjdishere

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mbkybky** [comment]
!bench

**Comment by mbkybky** [comment]
!bench

**Comment by riccardobrasca** [comment]
I am a bit surprised all these instances are not there. Have you tried to prove that with `infer_instance`? I a file with `import Mathlib` to be sure.

**Comment by mbkybky** [comment]
> I am a bit surprised all these instances are not there. Have you tried to prove that with `infer_instance`? I a file with `import Mathlib` to be sure.

Yes, they cannot be proven by `inferInstance`. See [my attempts in Lean 4 Web](https://live.lean-lang.org/#codez=JYWwDg9gTgLgBAWQIYwBYBtgCMCwAofAOyRAFMBnMJAY1LgDkBXELUqAMWFPQBN98AbkijAkWdHQAUAaTgAZOAC44AFQCeYUgCoAlHADanbjzjSAugaO95F/QEF0Ac1JYoSUzYNMWbKyfNezKwcXNZyZvx4wITkMEiEtEpwAJLkAMrUSOjCKhAA7mxwkoCsG4B7O6Z6JeVyegqKALxw0QBmbMkxcQmkkdGx8YnKqe0wpI5u6ADC6BDkjFBSZfKVi9K1So0tbR393QR4APQAtIdwdoRqcKQAHiMxwBCEcKwwBaSPIoSOcBDNTYQjzig5CawOiAPGADo4Id9vhep1EtdbuR7oQAPpZZyuJBo4DkYajcZJBxYtwQob/QlZIorZbVPQNP6tKDtPpdSJHE5nC5It4oh5PUgvUhvOAfL4/P4AtjAyWEIKFZqhHig4GECBC1BsUSEKEwuHbLqXG581G48j0DVobXxQI+ELGUy2bzBPyeQYWq1akS2qoVGn09ZMrZs2g9Q0DBgQABabAgaQQjHQABFgAI8dBgX7VgGlkHNiyI7sDaG6MpLbGoPHEym0xmgbmc3UNoRmayEbsgA).

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Comment by bryangingechen** [comment]
This fell off the queue when bors crashed yesterday
bors r+

Just in case:
bors d+

**Pull request closed without merging**
