### PR TITLE
[Merged by Bors] - perf (GradedObject.Trifunctor): rearrange proof

### PR DESCRIPTION
**Pull request by mattrobball**
Calling `dsimp` before `ext` is more efficient.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
[Here](http://speed.lean-fro.org/mathlib4/compare/e7b27246-a3e6-496a-b552-ff4b45c7236e/to/baf999a7-b3d7-4983-a850-b48da58b5882?hash1=f2e0c5baa5254e9c8c87d759086af0086206d67f) is a valid comparison. 

```diff
  Benchmark                                                      Metric         Change
  ==========================================================================
+ ~Mathlib.CategoryTheory.GradedObject.Trifunctor              instructions   -58.2%
```

**Review by grunweg — APPROVED** [review]
Want to leave a comment that this order is for efficiency reasons?

**Comment by grunweg** [comment]
Also, here and elsewhere: holy cow, these are impressive! Do you know what deeper conclusions can be drawn from this? (Does this suggest a change to Lean core, for example? This is a naive question.)

**Comment by semorrison** [comment]
bors merge

**Comment by mattrobball** [comment]
@grunweg Thanks for the review! Here and in the other PR. 

Sprinkling in a single `dsimp` seems to be pretty standard and probably not worthy of mention. 

I don't think it's implicating anything in core. Unification can be a tight balance for performance so that small modifications to the expression can cost more than you'd expect. `dsimp` is usually pretty efficient and it is often better to use a simplified term earlier.

**Pull request closed without merging**
