### PR TITLE
[Merged by Bors] - feat: port CategoryTheory.Monoidal.Rigid.FunctorCategory

### PR DESCRIPTION
**Pull request by joelriou**
---
- [x] depends on: #4646

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4646
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4646~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
Not sure why bors rejected this one. Perhaps a commit was added while it was processing? I've merged master again to get another CI run.

bors d+

**Comment by Parcly-Taxel** [comment]
> Not sure why bors rejected this one.

There was a merge conflict.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
