### PR TITLE
[Merged by Bors] - refactor: Move the data fields of `MonoidalCategory` into a `Struct` class

### PR DESCRIPTION
**Pull request by eric-wieser**
This matches the approach for `CategoryStruct`, and allows us to use the notation within `MonoidalCategory`.

It also makes it easier to induce the lawful structure along a faithful functor, as again it means by the time we are providing the proof fields, the notation is already available.

This also eliminates `tensorUnit` vs `tensorUnit'`, adding a custom pretty-printer to provide the unprimed version with appropriate notation.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
!bench

**Comment by eric-wieser** [comment]
!bench

**Comment by joelriou** [comment]
I think this PR goes in the right direction. Could you just merge with master so as to see nothing breaks?

bors d+

**Comment by eric-wieser** [comment]
This was indeed broken by (my PRs to) master, but they were the whole point in this refactor anyway; see my last commit for the motivation for this change.

**Comment by eric-wieser** [comment]
!bench

**Comment by eric-wieser** [comment]
@joelriou: happy to merge despite the performance hit in `

**Comment by eric-wieser** [comment]
!bench

**Pull request closed without merging**
