### PR TITLE
[Merged by Bors] - chore: homogenize TODO format

### PR DESCRIPTION
**Pull request by mo271**
This makes sure that the by far most common way of declaring TODOs in module doc comments is also used by the few that deviated from that. This makes sure that it is easier to find those.

Drive by: fix number of `#` for some other headings, to make doc strings more uniform.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
There is also 50 occurrences of "Future Work", which I suppose could also be replaced with "TODO", but that seems more controversial, so I leave it for now...

**Review by rwst — APPROVED** [review]
Exactly what is described, except the very last change, which leaves three ###s.  LGTM

**Comment by mo271** [comment]
> Exactly what is described, except the very last change, which leaves three ###s. LGTM

For this one, the three ###s make sense, because there are multiple TODOs in different levels.

**Comment by eric-wieser** [comment]
bors merge

Thanks!

**Pull request closed without merging**
