### PR TITLE
[Merged by Bors] - feat: port LinearAlgebra.Matrix.Charpoly.Basic

### PR DESCRIPTION
**Pull request by adomani**
Very few fixes were needed for this file!

---

- [x] depends on:  #4106 

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4106
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by adomani** [comment]
I realize now that merging the other PR might make reviewing trickier than it could be.  The first "relevant" commit is `6d0bfd1899f75295501c3f69d9a2e100414c3672`.

**Comment by ChrisHughes24** [comment]
> I realize now that merging the other PR might make reviewing trickier than it could be. The first "relevant" commit is [6d0bfd1](https://github.com/leanprover-community/mathlib4/commit/6d0bfd1899f75295501c3f69d9a2e100414c3672).

This is fine, I just compare the diff with some different commits. People do this all the time.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4106~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
