### PR TITLE
[Merged by Bors] - feat: implement intermediate state for simp_rw

### LINKED ISSUE #3680: simp_rw does not allow inspecting intermediate goal states
There is nowhere that I can put my cursor to see the state between the two rewrites
```lean4
example {x : ℕ} : 1 + x * 2 = x + x + 1 := by
  simp_rw [mul_two, add_comm]
```

This was possible in Lean 3.

[Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Stepping.20through.20simp_rw/near/326712986)

### PR DESCRIPTION
**Pull request by alexjbest**
closes #3680, see https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Stepping.20through.20simp_rw/near/326712986

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by eric-wieser — COMMENTED** [review]
Is it possible to add a test for this?

**Comment by alexjbest** [comment]
I'm sure its possible, but I'm not sure I have the skills to write it ;). Maybe if someone could point to examples of similar tests in mathlib that could serve as an example

**Comment by alexjbest** [comment]
Unfortunately withRWRulesSeq includes some logic to try different equation lemmas, so using it directly seems to result in some failures.
It does look to be a nicer output than a more basic implementation so I'm trying to decide whether to copypaste the code for a simprw specific version that does less, or just go with a simpler implementation (that doesn't handle the arrows or initial token so well)

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3757
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by fpvandoorn** [comment]
LGTM

It would be nice if you could also annotate error messages. In Lean 3 the error message was "`simp` failed to simplify" without indication which of the `simp_rw` steps caused this error. It would be nice if you could print the rule that failed. (doesn't have to be in this PR)

bors d+

**Comment by alexjbest** [comment]
Ok i will do that in the follow up, when the errors are added for simps that do nothing.
Thanks for the suggestion.

**Pull request closed without merging**
