### PR TITLE
[Merged by Bors] - refactor(RingTheory/IntegrallyClosed): generalize to `IsIntegrallyClosedIn`

### PR DESCRIPTION
**Pull request by Vierkantor**
This refactor adds a new definition `IsIntegrallyClosedIn R A` equal to `IsIntegralClosure R A A`, and redefines `IsIntegrallyClosed R` to equal `IsIntegrallyClosed R (FractionRing A)`. This should make it possible and convenient to generalize away from the fraction fields.

This also more closely approximates the conventions of the Stacks project.

This is a second attempt at the refactor, after #7116 which was much more messy.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by trivial1711 — COMMENTED** [review]
Hello, thank you for the contribution. This looks great; I only have two comments.

First, I think `isIntegrallyClosed_iff` and `IsIntegralClosure.of_isIntegrallyClosed` should both be deduced from the analogous statement about `IsIntegrallyClosedIn`. This would make it easier to prove `AlgHom.isIntegrallyClosedIn` as well.

```lean
theorem isIntegrallyClosedIn_iff {R A : Type*} [CommRing R] [CommRing A] [Algebra R A] :
    IsIntegrallyClosedIn R A ↔
      Function.Injective (algebraMap R A) ∧
        ∀ {x : A}, IsIntegral R x → ∃ y, algebraMap R A y = x := by
  sorry
```

```lean
lemma IsIntegralClosure.of_isIntegrallyClosedIn {S R A : Type*} [CommRing S] [CommRing R]
    [CommRing A] [Algebra S R] [Algebra S A] [Algebra R A]
    [IsScalarTower S R A] [IsIntegrallyClosedIn R A] (hRS : Algebra.IsIntegral S R) :
    IsIntegralClosure R S A := by
  sorry
```

Second, it would be nice to have the theorem that if `R` is the integral closure of `S` in `A`, then `R` is in fact integrally closed in `A` (which can be thought of as a converse of the lemma `IsIntegralClosure.of_isIntegrallyClosedIn` above). I understand if you think this is out of scope for a refactor PR, though.

**Comment by Vierkantor** [comment]
Done! I generalized your second suggestion to `IsIntegralClosure` :)

**Comment by riccardobrasca** [comment]
!bench

**Review by trivial1711 — APPROVED** [review]

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
