### PR TITLE
feat: port RepresentationTheory.Rep

### PR DESCRIPTION
**Pull request by 101damnations**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by 101damnations** [comment]
There are 8 broken things left in this file, and I haven't linted yet. I'll try and fix some more things in the morning but I'm very new to Lean 4 so I'll be slow. Some of my fixes are probably poor for this reason too.

**Comment by joelriou** [comment]
I have fixed the missing `PreservesLimits/Colimits` instances. I will probably not have time to work more on this file soon, so let us know in case you struggle too much on this file.

**Comment by 101damnations** [comment]
The errors about the behaviour of the monoidal closed instance on `Rep k G` seem horrible. I'm going to try defining the internal hom functor directly instead (in a Lean 3 PR) and show it's adjoint to tensoring; I won't get to use `monoidal_closed.of_equiv` anymore but it's so hard to work with.

**Comment by kbuzzard** [comment]
This is currently waiting on https://github.com/leanprover-community/mathlib/pull/19170

**Comment by 101damnations** [comment]
The mathlib3 [refactor](https://github.com/leanprover-community/mathlib/pull/19170) has been merged so I'll close this and open a new PR.

**Comment by 101damnations** [comment]
The mathlib3 [refactor](https://github.com/leanprover-community/mathlib/pull/19170) has been merged so I'll close this and open a new PR.

**Pull request closed without merging**
