### PR TITLE
[Merged by Bors] - chore: generalize tower instances for Module.End

### PR DESCRIPTION
**Pull request by eric-wieser**
This now matches the generality of `Module.End.instAlgebra`, meaning that the generality is available to `M/R/S` not just `A/R/S`.

[Context](https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/Quadratic.20forms.20with.20values.20in.20a.20larger.20ring/near/452999484) on Zulip.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
!bench

**Comment by eric-wieser** [comment]
!bench

**Comment by MichaelStollBayreuth** [comment]
<b>General information:</b>
```text
build:                                                 +17.486 * 10⁹ (+0.0145%)
```


<b>5 files got slower by at least 10⁹ instructions:</b>
```text
Mathlib.LinearAlgebra.TensorProduct.Graded.External:   +12.720 * 10⁹ (+5.05%)
Mathlib.NumberTheory.RamificationInertia:              +6.2988 * 10⁹ (+2.21%)
Mathlib.RepresentationTheory.GroupCohomology.Resolution:
                                                       +3.2498 * 10⁹ (+1.15%)
Mathlib.CategoryTheory.Monad.Basic:                    +2.0253 * 10⁹ (+3.83%)
Mathlib.CategoryTheory.Limits.FilteredColimitCommutesFiniteLimit:
                                                       +1.1211 * 10⁹ (+3.08%)
```


<b>No file got slower by at least 10%.</b>


<b>4 files got faster by at least 10⁹ instructions:</b>
```text
Mathlib.Algebra.Quaternion:                            -2.1989 * 10⁹ (-1.08%)
Mathlib.RepresentationTheory.Rep:                      -1.8161 * 10⁹ (-1.36%)
Mathlib.Analysis.NormedSpace.PiTensorProduct.InjectiveSeminorm:
                                                       -1.5930 * 10⁹ (-0.692%)
Mathlib.RingTheory.Ideal.Quotient:                     -1.3934 * 10⁹ (-2.84%)
```


<b>No file got faster by at least 10%.</b>

**Comment by MichaelStollBayreuth** [comment]
The files involving `Graded` tend to be rather variable in their timings...

**Review by MichaelStollBayreuth — APPROVED** [review]
LGTM, but perhaps somebody with more insight into the algebra hierarchy of the typeclass system can comment on the timings.

**Comment by eric-wieser** [comment]
I think the timings look acceptable enough.  The main slowdown is in a leaf file that mainly exists to prove an API works. Perhaps @jcommelin has an opinion.

**Review by kbuzzard — APPROVED** [review]
Thanks!

bors merge

**Pull request closed without merging**
