### PR TITLE
perf (GroupTheory.SubMonoid): direct inheritance for instances

### PR DESCRIPTION
**Pull request by mattrobball**
We replace calls to `Function.Injective.x` with direct inheritance.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by eric-wieser** [comment]
Instead of manually inlining things, can we somehow use `dsimp_result`? This new version is harder to maintain in the face of new fields (such as `op_nsmul` being added)

**Comment by mattrobball** [comment]
The maintenance is bothering me also. I think a better solution might be having a version where the map creates the data. `dsimp_result` can be tried.

**Comment by fpvandoorn** [comment]
please merge master and mark as `awaiting-review` if it's ready for review

**Pull request closed without merging**
