### PR TITLE
[Merged by Bors] - feat: port Combinatorics.SimpleGraph.Finsubgraph

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

- [x] depends on: #4002

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
@Ruben-VandeVelde I think this is good to go now!

**Comment by Ruben-VandeVelde** [comment]
Thanks!

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by collares** [comment]
Conflicts with #4002 due to the nearby Mathlib.lean change

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4002
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4002~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by eric-wieser — APPROVED** [review]
bors merge

**Pull request closed without merging**
