### PR TITLE
[Merged by Bors] - chore(LinearAlgebra/LinearIndependent): generalize a section from rings to semirings

### PR DESCRIPTION
**Pull request by yuma-mizuno**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Seems innocuous. Thanks!
maintainer merge

**Comment by grunweg** [comment]
@eric-wieser In case you'd like to get nerd-sniped generalising this further :-)

**Comment by Vierkantor** [comment]
Thanks!

bors merge

**Comment by eric-wieser** [comment]
> @eric-wieser In case you'd like to get nerd-sniped generalising this further :-)

Done

bors merge

**Pull request closed without merging**
