### PR TITLE
[Merged by Bors] - feat: port Analysis.Calculus.Deriv.Prod

### PR DESCRIPTION
**Pull request by urkud**
---

- [x] depends on: #4434

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4434
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4434~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by urkud** [comment]
Avoiding merge conflicts on the queue:
bors r-

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
