### PR TITLE
[Merged by Bors] - feat: avoid junk values in statement of Riemann hypothesis

### PR DESCRIPTION
**Pull request by kbuzzard**
Mathematicians will be unnerved by us evaluating the zeta function at 1 and getting a complex number. Pointed out by Jordan Ellenberg on Twitter.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — APPROVED** [review]
Should the PR title say "Riemann hypothesis" instead of Riemann zeta functions? After all, this PR doesn't change the zeta function at all.

Looks plausible to me (but I'm not a number theorist).

**Comment by kbuzzard** [comment]
The title follows the style guide -- the thing in brackets is the name of the file which is being changed.

**Comment by grunweg** [comment]
AIUI, the file being changed is optional now. I don't mind that being included. But I would find some mention that the definition of `RiemannHypothesis` is being changed (not the zeta function itself) helpful.

**Comment by kbuzzard** [comment]
Please feel free to edit the title of the PR.

**Comment by ocfnash** [comment]
bors merge

**Pull request closed without merging**
