### PR TITLE
[Merged by Bors] - feat(NumberTheory/Harmonic): Euler-Mascheroni constant

### PR DESCRIPTION
**Pull request by loefflerd**
Add the Euler-Mascheroni constant `γ` (the limit of `harmonic n - log n` as `n` goes to infinity)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
Looks nice.

maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by loefflerd** [comment]
Build is failing on the new file from this PR, so something needs a rebase (probably because of #11530). 

bors r-

**Comment by riccardobrasca** [comment]
bors d+

**Pull request closed without merging**
