### PR TITLE
[Merged by Bors] - refactor: replace `@[reducible]` with `abbrev`

### PR DESCRIPTION
**Pull request by tydeu**
A test to see how many uses of `@[reducible]` in Mathlib can be replaced with `abbrev`.

**TODOs:**
* `@[to_additive (attr := reducible)] def`
* `attribute [reducible] ConcreteCategory.forget`

### CODE REVIEW

**Comment by tydeu** [comment]
!bench

**Comment by semorrison** [comment]
The significant slow-down, in Mathlib.Logic.Small.Ring, is a percentage slow-down in a fast file, so I'm not too worried there. There is a small over-all instruction speed up of about 0.5%, but unfortunately a wall-clock slow-down of 1%.

**Comment by semorrison** [comment]
!bench

**Comment by semorrison** [comment]
Ok, wall-clock slow-down disappeared on the second bench, so let's ignore it.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
