### PR TITLE
[Merged by Bors] - feat: port Order.BoundedOrder

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
- [x] depends on: #642
- [x] depends on: https://github.com/leanprover-community/mathlib/pull/17730

Tracking mathlib commit: [e50b8c261b0a000b806ec0e1356b41945eda61f7](https://github.com/leanprover-community/mathlib/commit/e50b8c261b0a000b806ec0e1356b41945eda61f7)

### CODE REVIEW

**Comment by kbuzzard** [comment]
Oh now I see that this file hasn't really been done and it looks like more of a placeholder. Shall I go ahead with the mathlib3 splitting of this file @Ruben-VandeVelde @semorrison ? It will make it easier to port as four files of 500 lines rather than this one file of 2000 lines.

**Comment by Ruben-VandeVelde** [comment]
Also todo: fix the Prop → PropCat translations

**Comment by kbuzzard** [comment]
Note that the mathlib3 splitting PR is now merged. I think the next thing to do (which I'm happy to do) is to wait for mathlib3port to run on the now much shorter file and then to merge the results with the partial porting we have here.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#642~~
* leanprover-community/mathlib#17730
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#642~~
* ~~leanprover-community/mathlib#17730~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by Ruben-VandeVelde** [comment]
The remaining lint errors are these, which sound concerning:
```
/- The `synTaut` linter reports:
THE FOLLOWING DECLARATIONS ARE SYNTACTIC TAUTOLOGIES. This usually means that they are of the form `∀ a b ... z, e₁ = e₂` where `e₁` and `e₂` are identical expressions. We call declarations of this form syntactic tautologies. Such lemmas are (mostly) useless and sometimes introduced unintentionally when proving basic facts using `rfl`, when elaboration results in a different term than the user intended. You should check that the declaration really says what you think it does. -/
-- Mathlib.Order.BoundedOrder
#check OrderTop.ext_top.{u_1} /- LHS equals RHS syntactically -/
#check OrderBot.ext_bot.{u_1} /- LHS equals RHS syntactically -/

/- The `unusedArguments` linter reports:
UNUSED ARGUMENTS. -/
-- Mathlib.Order.BoundedOrder
#check OrderTop.ext_top.{u_1} /- argument 3 A : OrderTop α -/
#check OrderBot.ext_bot.{u_1} /- argument 3 A : OrderBot α -/
```

**Comment by semorrison** [comment]
Great, thanks!

bors merge

**Pull request closed without merging**
