### PR TITLE
[Merged by Bors] - chore(AlgebraicTopology): moved some files into SimplicialSet

### PR DESCRIPTION
**Pull request by emilyriehl**
The files `KanComplex.lean`, `Nerve.lean`, and `Quasicategory.lean` are moved from AlgebraicTopology into the SimplicialSet subfolder. The file `AlgebraicTopology/SimplicialSet.lean` is moved as well and renamed to`AlgebraicTopology/SimplicialSet/Basic.lean`.

---

-->

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by emilyriehl** [comment]
This precisely implements the changes discussed [on Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/what.20belongs.20in.20the.20SimplicialSet.20folder.20on.20mathlib.3F/near/475943392).

**Comment by emilyriehl** [comment]
I don't understand the merge conflict, which is with a file that does not exist in this branch.

**Comment by joelriou** [comment]
> I don't understand the merge conflict, which is with a file that does not exist in this branch.

If you do `git pull; git merge origin`, it may fix the non-existent problem...

**Comment by joelriou** [comment]
Thanks!

bors merge

**Pull request closed without merging**
