### PR TITLE
[Merged by Bors] - chore: remove sed-based hashCommand linter

### PR DESCRIPTION
**Pull request by grunweg**
The linter was rewritten in Lean in #11019. This removes one separate workflow step.

---
- [ ] depends on: #11019

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by adomani** [comment]
This looks good to me, of course!

If you merge master, the diff will become much smaller, now that the linter is in mathlib!

**Comment by grunweg** [comment]
I rebased master (and fixed a typo in the `HashCommandLinter`'s docstring - which I remembered too late).

**Comment by adomani** [comment]
Thanks for fixing the typo!

I am happy with removing the CI step, although I wonder whether waiting for a couple of days to see them both working at the same time is a good idea.

**Comment by adomani** [comment]
I think that this is indeed an improvement.

maintainer merge

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
