### PR TITLE
[Merged by Bors] - fix: simpa syntax

### PR DESCRIPTION
**Pull request by digama0**
Fix for #235

### CODE REVIEW

**Comment by gebner** [comment]
To repeat my remark on the other PR, is this worth it?  I feel like we're trying way too hard to replicate Lean 3 syntax in Lean 4, clearly the parser is not intended for this kind of syntax.

**Comment by digama0** [comment]
I think that `simpa ! ?` looks really bad, and there aren't any other good sigils to replace the meaning of `!` and `?` (which are used in many tactics with similar meaning, although `!` is a bit vague). People are going to misspell these all the time. The version here seems like a reasonable compromise, in that it supports both `simpa !` and `simpa!`, although of course this does nothing to address the fact that it's really four tactics under the hood. Still, it's not prohibitive to support this in the tactic and I consider the UX quality more important than the implementation.

**Comment by gebner** [comment]
> People are going to misspell these all the time.

This is a good point.  I've pushed a commit which removes most of the duplication.

**Comment by digama0** [comment]
Works for me. Do you want to use this trick on all the other syntaxes? The `simpaArgsRest` does add an extra node, so this will probably  affect mathport too (although many of these are done via syntax quotations).

bors merge

**Pull request closed without merging**
