### PR TITLE
[Merged by Bors] - feat(LinearAlgebra/Lagrange): Generalize typeclasses.

### PR DESCRIPTION
**Pull request by wrenna-robson**
Generalize some key definitions in the definition of Lagrange interpolation.

In particular, the definition of the nodal polynomial does not need to be over a field. 

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
Did you have to modify any defs or proofs, or is this just a reorder? The diff makes it hard to distinguish the cases. Could you generalize the old lemmas in place rather than moving them?

**Comment by linesthatinterlace** [comment]
I did have to modify a few proofs, mostly by removing unneeded dependencies. What I could do is move the moved stuff back (mostly it was just that it seemed odd to have nodal not nearer the top of the file), and focus my efforts just on the actual changes, and save any moving for a larger refactor of the file.

**Comment by linesthatinterlace** [comment]
I probably would have done this except my partner wanted to go to sleep. I can look at it in the morning if you like.

**Comment by linesthatinterlace** [comment]
There we go.

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
