### PR TITLE
[Merged by Bors] - feat(RingTheory/Flat/Basic): add `lTensor_preserves_injective_linearMap`

### PR DESCRIPTION
**Pull request by acmepjz**
also move `lTensor_inj_iff_rTensor_inj` to `LinearMap`

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by alreadydone — APPROVED** [review]
Thanks, LGTM
maintainer merge

**Comment by alreadydone** [comment]
Sorry, there seems to be a build error in Flat.lean

**Comment by acmepjz** [comment]
> Sorry, there seems to be a build error in Flat.lean

It's expected since I marked an existing theorem as deprecated. 😂 Now we need to find out all the occurrences of it and got them replaced.

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
