### PR TITLE
[Merged by Bors] - feat: port LinearAlgebra.Matrix.ToLinearEquiv

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

- [x] depends on: #3710
- [x] depends on: #4265
 
[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
Happy for leanprover-community/mathlib#18895 to go in first? I don't know whether it will make this file easier or harder to port. It certainly isn't a big deal for me to forward-port later if you'd rather it didn't.

**Comment by eric-wieser** [comment]
This now needs to wait for two new dependencies to be ported

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3710
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3710~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3710~~
* ~~leanprover-community/mathlib4#4265~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Pull request closed without merging**
