### PR TITLE
Fix Windows style line-endings in Mathlib/Analysis/Specificlimits/IsROrC.lean.

### PR DESCRIPTION
**Pull request by yangky11**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

`Mathlib/Analysis/Specificlimits/IsROrC.lean` uses `\r\n`, which is inconsistent with all other files. I changed them to `\n`.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Can you edit the linter script to detect this?

**Comment by yangky11** [comment]
@eric-wieser I'm happy to help but not familiar with how the linter works. Should the check be added into this file? https://github.com/leanprover-community/mathlib4/blob/master/scripts/lint-style.py

**Comment by eric-wieser** [comment]
Yes exactly! Note also that CI deliberately doesn't run from forks; you'll need to ask on the Lean Zulip chat to have write permissions on non-master branches, as discussed on the website.

**Comment by yangky11** [comment]
will do, thx!

**Pull request closed without merging**
