### PR TITLE
[Merged by Bors] - feat: add uppercase lean 3 linter

### PR DESCRIPTION
**Pull request by digama0**
* [ ] depends on: #1794

Implements a linter for lean 3 declarations containing capital letters (as [suggested on Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/non-aligned.20definitions/near/323102645)).

### CODE REVIEW

**Comment by rwbarton** [comment]
I'm going to add some logic to allow the most common Lean 3 name components with capital letters (`Prop`, `Pi`, and the intervals), since it is a bit much to add all the nolints otherwise.

**Comment by fpvandoorn** [comment]
bors merge
bors d+ (if there is a conflict)

**Comment by fpvandoorn** [comment]
as expected, this has merge conflicts

bors r-

**Comment by rwbarton** [comment]
bors merge

**Pull request closed without merging**
