### PR TITLE
[Merged by Bors] - chore(RingTheory/LocalRing): strengthen `Module.free_of_flat_of_isLocalRing`

### PR DESCRIPTION
**Pull request by chrisflav**
Make the fact that the proof works with any `k`-basis of `k ⊗[R] M` explicit and deduce from this that any generating family contains a basis.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by jcommelin — COMMENTED** [review]
maintainer merge

**Review by alreadydone — COMMENTED** [review]
Notice that FinitePresentation can be replaced by Finite by [00NZ](https://stacks.math.columbia.edu/tag/00NZ), and we can still extract the same lemma. I might do this soon if no one else does :)

**Comment by chrisflav** [comment]
> Notice that FinitePresentation can be replaced by Finite by [00NZ](https://stacks.math.columbia.edu/tag/00NZ), and we can still extract the same lemma. I might do this soon if no one else does :)

Yes, that's why there is the comment
```
-- TODO: Generalise this to finite free modules.
```
in L254.

**Comment by alreadydone** [comment]
Good catch! Somehow the equational criterion #12666 was already merged when the comment was added in #14375 though.

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by alreadydone** [comment]
> Notice that FinitePresentation can be replaced by Finite by 00NZ, and we can still extract the same lemma. I might do this soon if no one else does :)

I've PR'd 00NZ as #20460. I'm not touching the old proofs, because they work under the weaker assumption that `𝔪 ⊗ M → M` is injective and doesn't need full flatness (that `I ⊗ M → M` for every ideal `I`). I provide an example such that `𝔪 ⊗ M → M` is injective and M is finite but not free in the commit message of #20460.

It has also been shown that a finitely presented flat module is projective in #20452 as a trivial consequence of the equational criterion.

**Pull request closed without merging**
