### PR TITLE
[Merged by Bors] - feat: port Order.Filter.CountableInter

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jcommelin** [comment]
The name of the branch and the title of the PR don't match.

**Comment by urkud** [comment]
> The name of the branch and the title of the PR don't match.

Another side effect of merging another branch. Next time I'll create a PR before merging.

**Comment by urkud** [comment]
Rebased on `staging`, so should become based on `master` soon.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
