### PR TITLE
feat(Algebra/Module): Projectivity is local on stalks for finitely presented modules.

### PR DESCRIPTION
**Pull request by erdOne**
Written at the AIM algebraic geometry workshop

Co-authored-by: David Swinarski

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alreadydone** [comment]
Just to collect some interesting results:
+ [TFAE in the finitely presented case](https://stacks.math.columbia.edu/tag/00NX)
+ [Projectivity is Zariski local](https://mathoverflow.net/questions/6719/is-projectiveness-a-zariski-local-property-of-modules-answered-yes)
+ [A (non-finitely generated) projective module which is not locally (on basic opens) free](https://stacks.math.columbia.edu/tag/05WG)

**Comment by erdOne** [comment]
Feel free do to 2 following Raynaud-Gruson :)

**Comment by alreadydone** [comment]
Certainly reasonable to have it as a proof_wanted :)

**Comment by erdOne** [comment]
Subsumed by #18131

**Comment by alreadydone** [comment]
I was just made aware that Liran Shaul posted [*Formalization in Lean of faithfully flat descent of projectivity*](https://arxiv.org/abs/2603.04376) last month, see [Zulip](https://leanprover.zulipchat.com/#narrow/channel/113488-general/topic/Lecture.20on.20Monday.209.2E3.20related.20to.20Lean/near/577805624).

**Pull request closed without merging**
