### PR TITLE
[Merged by Bors] - refactor(Algebra/Star/StarAlgHom): Reverting {_ : ...} to [...]

### PR DESCRIPTION
**Pull request by mans0954**
During porting (#2603) parameters to some instances were made implicit to avoid [dangerous instances](https://github.com/leanprover-community/mathlib4/pull/2603/files#diff-8017bfdc9f21755fb88462d9ba5909d1590cfe91939577ce589ef704a831df57R700). Is this still necessary?

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mans0954** [comment]
!bench

**Comment by grunweg** [comment]
Just for the record: the dangerous instance linter has not been ported from mathlib to mathlib4 yet. (So, someone who understands this issue should look at it; linters alone would not catch such issues right now. I don't understand this question well enough to comment.)

**Review by eric-wieser — APPROVED** [review]
LGTM, this doesn't look related to dangerous instances to me.

**Comment by j-loreaux** [comment]
Right, it wasn't about dangerous instances, but rather the order in which arguments were synthesized. I think Gabriel came up with a solution during porting. Given that the bench doesn't show any significant change, I think it's fine to change them back.

bors merge

**Pull request closed without merging**
