### PR TITLE
chore(SetTheory/Ordinal/Enum): `enumOrd_strictMono` → `strictMono_enumOrd`

### PR DESCRIPTION
**Pull request by vihdzp**
This matches the naming convention.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Thanks, looks good to me!
maintainer merge

**Comment by YaelDillies** [comment]
No it doesn't match the naming convention actually. It's not very precisely written down, but the practice is that predicates that are analogous to an atom already suffixed by the naming convention already also get suffixed. Eg:
* We use `_inj` for `f a = f b ↔ a = b`, so we also use `_injective` for `Injective f`, `_surjective` for `Surjective f`, `_bijective` for `Bijective f`...
* We use `_mono` for `a ≤ b → f a ≤ f b` and `_anti` for `a ≤ b → f a ≤ f b`, so we also use `_mono` for `Monotone f``, `_anti` for `Antitone f`, `_strictMono` for `StrictMono f`, `_strictAnti` for `StrictAnti f`, same thing for the `On` versions, etc...

Predicates that are not analogous to an atom already suffixed by the naming convention don't get suffixed, eg `IsClosed`, `IsOpen`, `Convex`, etc...

**Comment by vihdzp** [comment]
That's good to know, since in that case I have a few other PRs to tweak.

**Comment by YaelDillies** [comment]
I've opened https://github.com/leanprover-community/leanprover-community.github.io/pull/539 to record that naming convention.

**Pull request closed without merging**
