### PR TITLE
[Merged by Bors] - feat(Algebra/GroupWithZero/InjSurj): port file

### PR DESCRIPTION
**Pull request by j-loreaux**
mathlib3 SHA: 6b3325cdf0b4b23496391a451324c95a1dc36d9e

porting notes:
* overall, very straightforward
* I made `GroupWithZero` extend `Nontrivial` to match mathlib3, and we didn't have this instance previously because it didn't extend that class.

### CODE REVIEW

**Comment by urkud** [comment]
LGTM but I don't consider myself to be a mathlib4 expert. Let me see if this works in this repo:
maintainer merge

**Comment by semorrison** [comment]
You seem to not be authorized

**Comment by urkud** [comment]
But you came here, so you can review the PR...

**Comment by semorrison** [comment]
Haha, that wasn't actually me, @urkud. When I set up the maintainer merge bot I guess I used my personal credentials. I will go fix that. :-)

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
