### PR TITLE
[Merged by Bors] - feat(Calculus/FDeriv): add `DifferentiableAt.isBigO_sub`

### PR DESCRIPTION
**Pull request by urkud**
* rename `HasFDerivWithinAt.isBigO` to `HasFDerivWithinAt.isBigO_sub`;
* rename `HasFDerivAt.isBigO` to `HasFDerivAt.isBigO_sub`;
* add `DifferentiableWithinAt.isBigO_sub`;
* add `DifferentiableAt.isBigO_sub`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by MichaelStollBayreuth — APPROVED** [review]
LGTM

**Comment by urkud** [comment]
Should I add special cases for `x₀=0`?

**Comment by MichaelStollBayreuth** [comment]
Then there should also special cases for `f x₀ = 0`, I would think. Then every lemma wold have four versions. It may be convenient to have these, but I'm not sure this is really a good idea.
But maybe some other people can chime in on this.

**Comment by urkud** [comment]
I agree that I shouldn't (unless this specific case will be used many times).

**Comment by alreadydone** [comment]
If you are not adding the `x₀ = 0` / `f x₀ = 0` versions, why the rename? I think the current names are fine, and if we want to add those versions, we may add a subscript 0 to those lemmas.

**Review by alreadydone — APPROVED** [review]
Oh I see it's for consistency with [HasFDerivAtFilter.isBigO_sub](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Analysis/Calculus/FDeriv/Basic.html#HasFDerivAtFilter.isBigO_sub) etc.
LGTM then!
maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
