### PR TITLE
[Merged by Bors] - feat(Order/Basic): add `gcongr` lemmas

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
Should I put these lemmas elsewhere instead?

**Review by YaelDillies — APPROVED** [review]
Thanks!

maintainer merge

**Comment by kim-em** [comment]
Yes, I'd prefer that these lemmas were put somewhere else.

**Comment by kim-em** [comment]
bors d+

**Comment by urkud** [comment]
@kim-em Where do you want them to go?

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
