### PR TITLE
[Merged by Bors] - feat: port Analysis.SpecialFunctions.Integrals

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Parcly-Taxel** [comment]
I've got the whole file sorted out; I'm going to push.

**Comment by urkud** [comment]
@Parcly-Taxel Next time please ask for permission of the PR author **before** starting to work. This way you avoid duplication of effort. We have plenty of files on the queue and PRs with `help-wanted` label.

**Comment by urkud** [comment]
@Parcly-Taxel You were going to push 2h ago. Did you forget?

**Comment by urkud** [comment]
@Parcly-Taxel Sorry for miscommunication on my side.

**Pull request closed without merging**
