### PR TITLE
feat(Logic/Small/Set): `Small (Iic a) → Small (Ixx a)`, etc.

### PR DESCRIPTION
**Pull request by vihdzp**
This allows showing that all intervals of e.g. ordinals or cardinals bounded above are small by only proving it for one of them.

---

I could also add the dual instances `Small (Ici a) → Small (Ixx a)`, but this is probably not worth it if we don't have good concrete examples where it'd be useful.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by YaelDillies — COMMENTED** [review]
I don't really understand the motivation. Why don't you just prove that `Ixx a` is u-small for `a : Ordinal.{u}`, `a : Cardinal.{u}`?

**Comment by vihdzp** [comment]
I'm just trying to avoid code duplication. By the way, these lemmas can also be proved for the new type `Nimber`.

**Review by YaelDillies — COMMENTED** [review]
Sure, but the lemmas are all one-liners?

**Comment by vihdzp** [comment]
eh, fair enough.

**Pull request closed without merging**
