### PR TITLE
experiment with minor change to CommGroup definition to see if it speeds stuff up

### PR DESCRIPTION
**Pull request by ChrisHughes24**
---
Probably not a route we want to go down, but worth looking at. It's a 1% reduction in instructions, with massive speedups and slowdowns in lots of places.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ChrisHughes24** [comment]
!bench

**Comment by ChrisHughes24** [comment]
!bench

**Comment by ChrisHughes24** [comment]
!bench

**Comment by digama0** [comment]
Note: I have pushed an update to the lean toolchain because this PR was on a [buggy version](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Potential.20data.20loss.20from.20.60lake.20clean.60.20with.204.2E2.2E0-rc2.2F3/near/397875701) of the toolchain. **WARNING**: checking out old commits of this PR using v4.2.0-rc2 or v4.2.0-rc3 can cause `lake clean` to delete your mathlib folder! If you need to do so, make sure to delete `lakefile.olean` manually before running any `lake` commands.

**Comment by urkud** [comment]
This PR has quite a few merge conflicts now. Is it still relevant, or should we close it?

**Comment by ChrisHughes24** [comment]
It's no longer relevant

**Pull request closed without merging**
