### PR TITLE
[Merged by Bors] - chore: add funprop attributes for differentiability of usual functions

### PR DESCRIPTION
**Pull request by sgouezel**
See Zulip thread at https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Is.20there.20a.20way.20to.20simplify.20the.20proof.20of.20differentiable.3F/near/475104903

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Thanks! The changes to `Trigonometric/Deriv` look good to me.

The other changes *look* good, but I need some more time to double-think if they are suitable in light of [this comment about uncurried vs compositional form](https://github.com/leanprover-community/mathlib4/pull/17304#issuecomment-2388527997). Have you thought about that detail already? If you have, feel free to maintainer merge on my behalf.

**Comment by sgouezel** [comment]
I think it's already good enough for automatic use (indeed, it solves the original poster issue), as it's nicely compositional. If it turns out it doesn't solve all problems we can revisit later, but my guess is this formulation is the right one.

**Comment by YaelDillies** [comment]
As Michael points out, your lemmas are not in compositional form, so they won't solve everything you expect (and you need to tag twice as many of them at least). I would encourage you to read and understand @lecopivo's comment on my PR.

**Comment by lecopivo** [comment]
I think all the theorems are fine.

Theorems about sums and products are in the compositional form which is necessary as they are high order functions. Of course, you could also add primed version where the result of the sum is a function and you evaluate it. Similar to the linked PR with my comment.

Theorems about `sin`,... are not in compositional form and it is totally ok. For simple functions it is fine to state the theorems in "simple/uncurried" form. User wise `fun_prop` should behave the same whether you state differentiability theorem for `sin` in compositional or uncurried form. There might be a mild speed difference(but I'm not sure what is faster) and difference in the length of the generated proof term.

**Review by YaelDillies — APPROVED** [review]
maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
