### PR TITLE
[Merged by Bors] - feat: pp.beta

### PR DESCRIPTION
**Pull request by kmill**
I do not recommend using this feature, but since Lean 3 had it, and since it's possible for us to implement it as mathlib code, here it is.

This is future-proof against core implementing it in the sense that [if it gets implemented](https://github.com/leanprover/lean4/issues/715) there will likely be a name collision, and then these two modules can be deleted.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Vierkantor — APPROVED** [review]
Thanks! Could you add a test case? Otherwise, everything is very neat.

bors d+

**Comment by ocfnash** [comment]
In this [Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/144837-PR-reviews/topic/.237205.20pp.2Ebeta/near/397124302) I have proposed adding a file containing the following minimal tests:
```lean
import Mathlib.Util.PPBeta
import Mathlib.Data.FunLike.Basic

variable (F α β : Type) [FunLike F α (fun _ => β)] (f : F) (a : α)

set_option pp.beta true in
/--
info: ↑f a : β
-/
#guard_msgs in
#check f a

set_option pp.beta false in
/--
info: ↑f a : (fun x ↦ β) a
-/
#guard_msgs in
#check f a
```
so that this can be merged.

**Comment by ocfnash** [comment]
The failure of the tests occurs because the output of `#check` differs when run from the command line by `lake` and when run in VS Code. In VS Code I see `↦` whereas running `lake` I see `=>`. See https://github.com/leanprover-community/mathlib4/pull/7205/commits/bcc59e1af0506b0702a28e8096a62f6f14df35fd

**Comment by ocfnash** [comment]
I note two "thumbs up" approvals from maintainers to my question on the Zulip thread so I am declaring this ready.

bors merge

**Pull request closed without merging**
