### PR TITLE
feat: Convert functions on subsets to functions between types

### PR DESCRIPTION
**Pull request by shuxuezhuyi**
We define `Function.toval'` and provide some relevant APIs.

Co-authored-by: Yaël Dillies <yael.dillies@gmail.com>

---

- [x] depends on: #7449

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by shuxuezhuyi** [comment]
Discussion on Zulip: https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/Convert.20functions.20between.20subsets.20to.20functions.20between.20types

**Review by YaelDillies — COMMENTED** [review]
What's your use case? I think you should just use `Function.extend`.

**Comment by shuxuezhuyi** [comment]
Maybe I just had some frustration using `Function.extend`. I will try to learn how to use `Function.extend`, but I think it's nice to have a simple definition of `Function.toval` now.

**Comment by YaelDillies** [comment]
Give me concrete problems you have with `Function.extend` and I will show you how to solve them.

**Comment by shuxuezhuyi** [comment]
Thanks, @YaelDillies . I know how to handle it now. That is, when `simp` reduces the parameter of `Classical.choose` in `Function.extend` to an empty `_`, I just need to replace `simp` with `simp [Subtype.coe_injective]`. Now I can use `Function.extend` to define `Function.toval` and build the subsequent APIs. However, I think it's fine to keep the current definition of `Function.toval`, as it is essentially a simpler version of `Function.extend`, and `toval_eq_extend` already provides a way to switch to `Function.extend`.

**Comment by shuxuezhuyi** [comment]
For the reason why I do not use `Function.extend` here, see the discussion on zulip: https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/.60simp.60.20fail.20with.20.60Classical.2Echoose.60

**Comment by YaelDillies** [comment]
I don't want `Function.toval` in mathlib. However I am happy to help you overcome the troubles you have using `Function.extend`.

**Comment by shuxuezhuyi** [comment]
Mathlib is an infrastructure for formalizing mathematics. It will never contain the formalization of the whole mathematics, so it should have a compact design. Since `Function.extend` is generic, if we want to extend a function, we should use `Function.extend`. However, that does not mean we have to use `Function.extend` directly. Sometimes we need to provide a more user-friendly method based on the underlying method. I could use `Function.extend` to define `Function.toval`, but I would rather make it easier for people to add APIs to `Function.toval` in the future.
You might think that `Function.toval` is redundant, since it can be defined using `Function.extend`. But I think users do not always want generic tools. In many cases, users need tools that are less general but more useful in specific context. For example, `Set.IccExtend` is not defined using `Function.extend`.
I could create a new file `Mathlib/Logic/Function/ApiForExtend.lean` and try to generalize the APIs of `Function.toval` to that of `Function.extend`, but I still need `Function.toval`.

**Comment by urkud** [comment]
Adding more definitions means supporting more API and more code to support during refactors, CI runs, ports to new versions of Lean/Std.
At least, we don't need both `toval` and `toval'`. We can have a special version of `Function.extend` for `Subtype.val` (and a bunch of lemmas proved by unfolding the definition and using lemmas about `Function.extend`) but we never use this special case in `Mathlib` yet, so I wouldn't recommend adding it unless you're going to add a file with a useful mathematical result that uses this definition.

**Comment by shuxuezhuyi** [comment]
@urkud Thanks for the explanation.​ `Function.toval` is just grammar sugar to me. I am rewriting my code using `Function.extend` instead of `Function.toval`. I will submit them in the new PRs.

**Comment by shuxuezhuyi** [comment]
I've changed my mind. I agree we should close these PRs.

**Pull request closed without merging**
