### PR TITLE
[Merged by Bors] - chore: further refactors of prerequisites of `norm_num`

### PR DESCRIPTION
**Pull request by kim-em**
---

- [x] depends on: #7094 ([diff](https://github.com/leanprover-community/mathlib4/compare/11sup...11_2))

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by jcommelin — APPROVED** [review]
bors d+

**Comment by semorrison** [comment]
bors p=5

bors merge

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
