### PR TITLE
[Merged by Bors] - feat(CategoryTheory): surjective/injective factorizations in concrete categories

### PR DESCRIPTION
**Pull request by joelriou**
In this PR, we show that if `C` is a concrete category that has strong epi mono factorizations and is such that `forget C` preserves both epi and mono, then any morphism in `C` can be factored in a functorial manner as a composition of a surjective morphism followed an injective morphism.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by erdOne — COMMENTED** [review]
Is this PR ready for review? It looks good to me though.

**Review by dagurtomas — APPROVED** [review]

**Comment by joelriou** [comment]
Thanks! Indeed, it is ready for review.

**Comment by erdOne** [comment]
Thanks!
maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
