### PR TITLE
[Merged by Bors] - chore: Rename to `Grp`

### PR DESCRIPTION
**Pull request by YaelDillies**
This is a proposal to rename what was in mathlib `Group` and in mathlib4 `GroupCat` to its literature name `Grp`. This has the advantage not to conflict with `group` that has been capitalised to `Group` and to be shorter.

---

A similar decision could be applied to `ModuleCat` and `MonCat`.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by joelriou** [comment]
The `Cat` suffix was added intentionally, see 
https://github.com/leanprover-community/mathlib4/wiki/Porting-wiki#categories "Categories are suffixed with `Cat`"

**Comment by YaelDillies** [comment]
Yes I know. This is an alternative to that last resort solution.

**Comment by fpvandoorn** [comment]
Please reach a consensus about this renaming on Zulip first

**Comment by YaelDillies** [comment]
It seems like the consensus is that this is a good thing. @semorrison, can you confirm?

**Comment by urkud** [comment]
Could you link to Zulip discussion, please?

**Comment by YaelDillies** [comment]
See https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Naming.20convention/near/354445098 and below.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
