### PR TITLE
chore (Module.Basic): move material about modules over `Rat` 

### PR DESCRIPTION
**Pull request by mattrobball**
This avoids importing ordered ring classes in this low level file.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
I took the liberty to mark this as ready for review - please adjust if this is incorrect!

**Comment by grunweg** [comment]
This PR is just import motion now - can you fix the title accordingly? Apart from that, the changes look good to me - feel free to maintainer merge on my behalf once you have fixed this!
awaiting-author

**Comment by grunweg** [comment]
This PR is just import motion now - can you fix the title accordingly? Apart from that, the changes look good to me - feel free to maintainer merge on my behalf once you have fixed this!
awaiting-author

**Comment by mattrobball** [comment]
Wasted time :/

**Pull request closed without merging**
