### PR TITLE
[Merged by Bors] - feat: add `{Even,Odd}.natCast`

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — COMMENTED** [review]
lgtm

maintainer merge

**Comment by YaelDillies** [comment]
Can you add the `Int.cast` versions?

**Comment by riccardobrasca** [comment]
LGTM taking into account Yael's comment.

bors d+

**Comment by urkud** [comment]
> Can you add the `Int.cast` versions?

Do you know a good home for `Odd.intCast`?

**Pull request closed without merging**
