### PR TITLE
[Merged by Bors] - feat: Basic theorems for iteratedFDerivWithin

### PR DESCRIPTION
**Pull request by jvlmdr**
Basic theorems for iteratedFDerivWithin

---

Broken out from  #10022

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mcdoll** [comment]
Can you prove the non-`within` variants from your version in one line?

**Comment by jvlmdr** [comment]
> Can you prove the non-`within` variants from your version in one line?

Yep, good point, updated accordingly. Thanks!

I'm not certain that my style is idiomatic, feel free to let me know if I should make changes.

**Comment by mcdoll** [comment]
LGTM
maintainer merge

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Comment by jvlmdr** [comment]
Thanks very much @urkud @mcdoll !

**Pull request closed without merging**
