### PR TITLE
[Merged by Bors] - chore: update nolints.json

### PR DESCRIPTION
**Pull request by grunweg**
Created by running `lake exe runLinter --update Mathlib` locally.

Most changes are due to leanprover/std4#269: proof fields in classes or structures do not require a docstring any more.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Let me look at the new output
- about 6500 added `checkType` warnings: are they new; should they stay? (I can remove them manually if needed.)
- about 1000 removed `docBlame` warnings: these docstrings are not added; it seems the lint doesn't warn about missing docs on class or structure fields any more.
- ~50 new `impossibleInstance` warnings (not checked)
- ~450 new `simpComm` warnings (no idea what this is)
- ~5500 new `simpNF` warnings
I spot-checked these in `Filter.Germ`; there's no `simpNF` next to these lemmas. I don't get why they show up.
- 1212 new `simpVarHead` warnings; not sure why these are emitted
- 2 new `structureInType` warnings, 4 new `synTaut` warnings, 2 new `unusedArguments` warnings

**Comment by eric-wieser** [comment]
> * I spot-checked these in `Filter.Germ`; there's no `simpNF` next to these lemmas. I don't get why they show up.
> * 1212 new `simpVarHead` warnings; not sure why these are emitted

My understandding was that `@[nolint _]` is completely orthogonal to `nolints.json`, but perhaps I'm mistaken. I don't understand how this file could grow if that were the case.

**Comment by digama0** [comment]
> My understandding was that `@[nolint _]` is completely orthogonal to `nolints.json`, but perhaps I'm mistaken. I don't understand how this file could grow if that were the case.

`@[nolint _]` and `nolints.json` are not orthogonal: a lint is suppressed if either mechanism is used. The meaning is slightly different: `nolints.json` is for grandfathered / unintentional lint suppression, while `@[nolint]` is for deliberate lint suppression. (That is, it is reasonable to have a goal of "drive `nolints.json` to empty", but not "remove all `@[nolint]`".)

**Comment by digama0** [comment]
I am suspicious about the conditions under which this linter script was run. The 6000 checkType warnings are saying that the statement of the theorem doesn't typecheck, this seems *very* suspicious. Also my understanding is also like Eric's, that this file can never grow from `--update` because any nolint which was not in the original file and is being added is a lint warning that would be generated without `--update`, and we run that in CI. So either there is an issue in the CI script or in the way `runLinter --update` was run (e.g. if the oleans were out of date).

**Comment by grunweg** [comment]
Your intuition was spot on: I merged master, updated my cache with `lake exe cache get!` and ran this line again; new output pushed. Now it's just removals of `docBlame` warnings.

My comment above about the `docBlame` changes still stands: spot-checking a few declarations, most are still without docstring: it seems the lint doesn't warn about undocumented fields in classes or structures any more.

**Comment by eric-wieser** [comment]
>  it seems the lint doesn't warn about undocumented fields in classes or structures any more.

Yes, this is due to https://github.com/leanprover/std4/pull/269 and is deliberate

**Comment by grunweg** [comment]
Updated the PR description accordingly.

**Comment by kmill** [comment]
Looks good to me. The handful of added lines are all from reordering the list.

bors r+

**Pull request closed without merging**
