### PR TITLE
[Merged by Bors] - feat: port Algebra.Homology.Functor

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
bors said there was a merge conflict, but I don't see anything upon merging master. Let's try again:

bors merge

**Comment by ChrisHughes24** [comment]
The merge conflict is with #3492 . I'll take this one off the queue for now

bors r-

**Pull request closed without merging**
