### PR TITLE
chore: fix Ideal.Quotient.field

### PR DESCRIPTION
**Pull request by riccardobrasca**
See [zulip](vhttps://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/heartbeats.20w.2F.20modules.20over.20ring.20quotients).

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by riccardobrasca** [comment]
!bench

**Comment by kbuzzard** [comment]
This version:
```
@[reducible]
protected noncomputable def field (I : Ideal R) [hI : I.IsMaximal] : Field (R ⧸ I) :=
  { toCommRing := Quotient.commRing I
    inv := (Quotient.groupWithZero I).inv
    mul_inv_cancel := (Quotient.groupWithZero I).mul_inv_cancel
    inv_zero := (Quotient.groupWithZero I).inv_zero }
```
completely removes all `let`s from the declaration. Is it any better?

**Comment by eric-wieser** [comment]
The `let` isn't the problem I don't think, it's the eta expansion. Using `toCommRing` is likely slightly better than the approach in this PR.

Note that https://github.com/leanprover/lean4/pull/2478, if it lands, will make this PR effectively a no-op.

**Comment by eric-wieser** [comment]
In fact @kbuzzard, your spelling is evil because it throws away the `zpow` and `div` fields of `groupWithZero`, and so is a recipe for instance diamonds.

**Comment by kbuzzard** [comment]
!bench

**Comment by mattrobball** [comment]
I've got two versions now.
- The current version of leanprover/lean4#2478 which patches the current elaboration to avoid the eta expansion. 
- A new version that elaborates **all** structure instances using left-to-right semantics while avoiding unnecessary eta expansions. 

Performance of the latter is worse but only slightly so (perhaps surprisingly). In particular, it will get near the same speed up. 

When I come up for some air, I will test things on both toolchains.

**Comment by mattrobball** [comment]
Or if you want to test yourself before I can, see #9007 and #9843 have working mathlib with the two toolchains

**Comment by mattrobball** [comment]
`synthInstance.maxHeartbeats 14000` works on #9007 and `15000` on #9843

**Comment by riccardobrasca** [comment]
Have the recent changes made this useless? Sorry for asking but I am very busy at the moment and I am not following all the amazing improvements you are making!

**Comment by mattrobball** [comment]
Yes, this and the current version on master give the same term up to a zeta reduction (which doesn't seem to make any difference).

**Comment by riccardobrasca** [comment]
Thanks!

**Pull request closed without merging**
