### PR TITLE
[Merged by Bors] - chore: bump to nightly-2023-03-31

### PR DESCRIPTION
**Pull request by kim-em**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
CI seems to pass,

bors d+

Up to you whether you want to benchmark this in some way.

**Comment by semorrison** [comment]
!bench

**Comment by semorrison** [comment]
Oh dear, this benchmarking looks terrible, right? @Kha.

**Comment by Kha** [comment]
Very curious. +2% overall isn't necessarily terrible, but definitely warrants a closer look. Could you try without packages updates first?

**Comment by semorrison** [comment]
How do you actually see 2% overall from these results? I only see relative changes for lots of different components.

Wouldn't it be better to be showing absolute changes from `!bench`?

**Comment by semorrison** [comment]
Trying again with updating the packages.

**Comment by semorrison** [comment]
!bench

**Comment by Kha** [comment]
> How do you actually see 2% overall from these results?

If you click on "significant changes", you can find deltas for all metrics including "build: task/wall-clock", which are basically `time`'s `user/total`. I think only changes >+/-5% are listed above. Including total changes as well should be possible, and perhaps we should even filter by some threshold to keep the list a little shorter and more relevant.

**Comment by Kha** [comment]
@JLimperg This is unexpected, I don't think enabling `--profile` should make Aesop produce any trace output 
image

**Comment by semorrison** [comment]
@Kha, I'm still tentative about understanding the benchmarking results. Am I right in interpreting that last response that this PR, which just bumps Lean itself, is safe, and I should merge? (Then try again bumping the packages later.)

**Comment by JLimperg** [comment]
Yeah sorry, I'll disable these messages.

Apr 1, 2023 23:35:53 Sebastian Ullrich ***@***.***>:

**Comment by Kha** [comment]
> Am I right in interpreting that last response that this PR, which just bumps Lean itself, is safe, and I should merge?

Yes, looks good now. Which was to be expected, there really isn't any lean4 commit in there that should influence mathlib4 in any way.

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
