### PR TITLE
feat: port Algebra.Order.ZeroLeOne

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
- [x] depends on #608

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
```lean
theorem zero_le_two [Preorder α] [One α] [AddZeroClass α] [ZeroLeOneClass α] [CovariantClass α α (· + ·) (· ≤ ·)] :
    (0 : α) ≤ 2 :=
  add_nonneg zero_le_one zero_le_one
```
yields
```
failed to synthesize instance
  OfNat α 2
```

I could replace the RHS by `1 + 1`, but that doesn't seem useful.

**Comment by semorrison** [comment]
Just replace the typeclass arguments with an `AddMonoidWithOne`? (Whatever it takes to summon the `OfNat` instance.)

**Comment by semorrison** [comment]
Could you please fix the long lines?

**Comment by semorrison** [comment]
Note duplicated work in #664.

Moreover, @YaelDillies has proposed a mathlib3 refactor https://github.com/leanprover-community/mathlib/pull/17646 which would simply merge this file into other files. I propose we just close both of these PRs for now.

Zulip discussion at https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/naming.20conventions

**Comment by mcdoll** [comment]
I've fixed all the problems in #664 
If you want to port a file please make sure to claim it in the wiki-file before putting in any work, otherwise we will have more duplicates.

**Pull request closed without merging**
