### PR TITLE
[Merged by Bors] - chore: reduce imports in 3 files under `Data`

### PR DESCRIPTION
**Pull request by rwst**
Removes unnecessary imports.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
These all look like transitive imports - but I don't see harm in removing those. Thanks for your contribution!
maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by riccardobrasca** [comment]
bors merge

**Comment by riccardobrasca** [comment]
Come on bors!

bors merge

**Pull request closed without merging**
