### PR TITLE
[Merged by Bors] - chore(Algebra/Order/Module/Defs): remove unused assumptions

### PR DESCRIPTION
**Pull request by astrainfinita**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
Why the linter doesn't catch them?

**Comment by negiizhao** [comment]
Maybe some lemmas use it, but the argument `[OrderedAddCommGroup β]` already provides it.

**Comment by urkud** [comment]
I think that these lemmas were accidentally moved from `Monoid` to `Group` section.

**Comment by YaelDillies** [comment]
"unused" is not quite the correct word. They are rather "redundant". It seems this redundancy happened as I was writing the proofs and forgetting to update some statements. Anyway, the change is unequivocally good, so

maintainer merge

**Comment by YaelDillies** [comment]
Turns out I had already found an even better generalisation in #11448, which is still sitting there unreviewed 😅

**Pull request closed without merging**
