### PR TITLE
[Merged by Bors] - feat: port Control.Traversable.Equiv

### PR DESCRIPTION
**Pull request by zeramorphic**

### CODE REVIEW

**Comment by zeramorphic** [comment]
Why are those naming changes being made? I thought that terms of Props were supposed to be lower snake case.

**Comment by rwbarton** [comment]
My understanding is when MultiWordThings get put into the context of a theorem name, the initial letter is de-capitalized but the rest stays the same, e.g. (from porting wiki)
```lean
-- follows rules 1 and 5
theorem neZero_iff {R : Type _} [Zero R] {n : R} : NeZero n ↔ n ≠ 0 := sorry
-- manual align is needed due to `lowerCamelCase` with several words inside `snake_case`
#align ne_zero_iff neZero_iff
```

**Comment by zeramorphic** [comment]
Ah, I think I may have misunderstood the naming rules.

**Comment by rwbarton** [comment]
To be honest, I'm not sure anyone fully understands the new naming rules :)

**Comment by rwbarton** [comment]
bors merge

**Pull request closed without merging**
