### PR TITLE
[Merged by Bors] - chore: create Mathlib.Init

### PR DESCRIPTION
**Pull request by adomani**
This PR creates the `Mathlib.Init` file.

This file is intended to be imported by virtually all `Mathlib` files.
This PR also imports `Mathlib.Init` in all `Mathlib` files that import no `Mathlib` file.

In the long run, some very basic files, some tactics and some linters will be imported in `Mathlib.Init`, so that the commands defined there would be available as widely as possible in `Mathlib`.

There is also the file `scripts/init_creation.sh` that contains the instructions to regenerate the `Mathlib/Init.lean` file.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
Thanks for starting the process of having a meaningful init file! Separating this into multiple stages makes sense, and this looks like a fine first step to me.
In my mind, the next step is "write a linter that ensure each mathlib file either transitively imports `Mathlib.Init`, or is imported by it. So, I don't quite see why including the script is useful here. (I don't see much harm in keeping it either, and removing it when the above linter is added.)

**Comment by grunweg** [comment]
Let's have another pair of eyes:
maintainer merge

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
Let's merge matter and try again

**Comment by grunweg** [comment]
#15833 will fix the lint-style failure

**Comment by semorrison** [comment]
Please merge once #15833 has landed.

bors d+

**Comment by mattrobball** [comment]
Let's wait until there are no performance surprises to merge

**Comment by adomani** [comment]
!bench

**Comment by mattrobball** [comment]
Thanks! LGTM

**Comment by vihdzp** [comment]
Is the omission of the copyright header on `Mathlib.Init` intentional?

**Comment by adomani** [comment]
> Is the omission of the copyright header on `Mathlib.Init` intentional?

It is, and it also required reviving the copyright linter!  😀

**Pull request closed without merging**
