### PR TITLE
[Merged by Bors] - chore(Algebra/Polynomial): don't import `Ideal` when defining `Polynomial.roots`

### PR DESCRIPTION
**Pull request by Vierkantor**
This PR moves around a few definitions in order to free the definition of `Polynomial.roots` of the knowledge of `Ideal`. This was mostly motivated by writing `assert_not_exists Ideal` in a few files and being amazed that it did exist.

In particular, the following changes are made:
* results involving ideals in `Algebra/Module/Submodule/Pointwise.lean` go to `RingTheory/Ideal/Operations.lean` (the first place that they are used) 
* results on ideal membership in `RingTheory/Localization/Defs.lean` go to `RingTheory/Localization/Ideal.lean` (idem)
* results on adjoining polynomials to a ring in `Algebra/Polynomial/AlgebraMap.lean` go to the new file `RingTheory/Adjoin/Polynomial.lean` (I couldn't find an obvious place to put this: `RingTheory/Adjoin/Basic.lean` does not know polynomials)
* results on ideal membership in `Algebra/Polynomial/Div.lean`, `Algebra/Polynomial/RingDivision.lean` and a few from `RingTheory/Polynomial/Basic.lean` go to the new file `RingTheory/Polynomial/Ideal.lean` (merging this with `RingTheory/Polynomial/Basic.lean` is an okay option but would increase the downstream imports a lot)

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]
This seems worth doing

maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by riccardobrasca** [comment]
I guess this needs to a `merge master`.

bors d+

**Comment by Vierkantor** [comment]
bors merge

**Pull request closed without merging**
