### PR TITLE
[Merged by Bors] - chore: bump Std to Std#254

### PR DESCRIPTION
**Pull request by kim-em**
---

- [x] depends on: #8105

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by PatrickMassot — COMMENTED** [review]
bors d+

**Comment by semorrison** [comment]
bors merge

**Comment by semorrison** [comment]
bors merge

**Comment by eric-wieser** [comment]
bors r-

This seems to be failing CI

bors d+

**Pull request closed without merging**
