### PR TITLE
[Merged by Bors] - feat: port Algebra.Module.PID

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

- [x] depends on: #5534

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4705
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5534~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by mo271** [comment]
From my point of view this is good to go. It is still very slow...

**Comment by Ruben-VandeVelde** [comment]
Thanks!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
