### PR TITLE
[Merged by Bors] - chore: update std4 11-03

### PR DESCRIPTION
**Pull request by digama0**
The main change is that `guard_target` and friends now use reducible defeq instead of syntactic eq by default.

### CODE REVIEW

**Comment by gebner** [comment]
> feat: add defeq matching to guard_hyp, use reducible by default

I'm not sure if that is a good idea.  It means `x > y` matches `y < x`.  In mathlib3, we use `transparency.none` instead, which I think is better.

**Comment by digama0** [comment]
`transparency.none` doesn't exist any more, `.reducible` is the nearest approximation.

**Comment by digama0** [comment]
Let's not block on this issue, since it requires lean 4 changes. If you have a better holistic solution @gebner we can update std4 and mathlib4 to match.

bors merge

**Comment by gebner** [comment]
> transparency.none doesn't exist any more, .reducible is the nearest approximation.

Oh wow, I didn't notice until now.  Then `reducible` is of course the best we can do.

**Pull request closed without merging**
