### PR TITLE
[Merged by Bors] - feat: port CategoryTheory.Category.Quiv

### PR DESCRIPTION
**Pull request by joelriou**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Parcly-Taxel** [comment]
Should the file name be `QuivCat` to match `RelCat`, `KliesliCat`, etc. in the same folder?

**Comment by fpvandoorn** [comment]
bors d+

Please merge after addressing/commenting on the previous comment

**Comment by joelriou** [comment]
> Should the file name be `QuivCat` to match `RelCat`, `KliesliCat`, etc. in the same folder?

Thanks. I have renamed `Quiv` as `QuivCat`.

**Pull request closed without merging**
