### PR TITLE
[Merged by Bors] - chore(SuccPred/Limit): rename 2 lemmas

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by vihdzp** [comment]
Sure, why not.

**Review by vihdzp — APPROVED** [review]
Sure, why not.

**Review by Ruben-VandeVelde — APPROVED** [review]
maintainer merge

**Comment by kim-em** [comment]
bors merge

**Pull request closed without merging**
