### PR TITLE
[Merged by Bors] - feat(GroupTheory/GroupAction/Basic): orbit lemmas for product

### PR DESCRIPTION
**Pull request by jsm28**
Add a few basic lemmas about orbits in relation to the action of a monoid or group on `α × β` induced by its actions on `α` and `β`.

From AperiodicMonotilesLean.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by jsm28** [comment]
The CI failure of "Compute transitive imports workflow run", `error: pathspec 'origin/import-count' did not match any file(s) known to git`, looks like a problem with the CI system, not with this PR.

**Review by BoltonBailey — APPROVED** [review]
Perhaps move the `{β : Type*} [MulAction M β]` up to the `variable` declaration for aesthetics, but otherwise this looks fine to me.

**Comment by jsm28** [comment]
Moved to `variable` lines as suggested.

**Comment by tb65536** [comment]
maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
