### PR TITLE
[Merged by Bors] - feat(ModelTheory/Order): Translate order-preserving maps in and out of model theory

### PR DESCRIPTION
**Pull request by awainverse**
Provides instances of `Language.order.(Strong)HomClass` for classes of order-preserving maps
Shows that elements of a `Language.order.HomClass` are monotone (strictly if injective)

---

- [x] depends on: #16341
- [x] depends on: #16373

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by YaelDillies — APPROVED** [review]
Thanks!

maintainer merge

**Comment by awainverse** [comment]
I was able to successfully create `OrderHom`s and `OrderEmbedding`s in the cases I cared about using `Monotone` and `StrictMono`, but I just found myself needing to instantiate an `OrderIso` from model theory. I'm leaning towards leaving that as a `def`.

**Comment by awainverse** [comment]
I've added `StrongHomClass.toOrderIsoClass` as just a def. All tests seem to be ok with this on the branch [ `fraisse_order`](https://github.com/leanprover-community/mathlib4/tree/fraisse_order)

**Comment by YaelDillies** [comment]
Okay, let's try again then

maintainer merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
