### PR TITLE
[Merged by Bors] - refactor: Unify the different versions of `mul_eq_one`

### PR DESCRIPTION
**Pull request by YaelDillies**
Replace `mul_eq_one_iff` and `Associates.mul_eq_one_iff` by a single lemma `mul_eq_one`. Rename `mul_eq_one_iff'` to `mul_eq_one_iff_of_one_le`. Similarly for the additive versions.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
Please describe API changes in the commit message.

**Comment by YaelDillies** [comment]
What about now?

**Comment by urkud** [comment]
AFAICT, `mul_eq_one_iff'` is not the same as the other two. Please fix the description. Otherwise LGTM. Thanks!
bors d+

**Comment by YaelDillies** [comment]
bors merge

**Pull request closed without merging**
