### PR TITLE
[Merged by Bors] - feat: port RingTheory.RootsOfUnity.Minpoly

### PR DESCRIPTION
**Pull request by mo271**
- [x] depends on: #5076

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5076
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by mo271** [comment]
https://github.com/leanprover-community/mathlib4/labels/help-wanted: In the original file there was a `omit hpos` many of the theorems don't have it. The omit is not ported, so what is the best way to proceed. Right now I made it build by adding the hpos assumption in many places, but it feels a bit wrong.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5076~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by riccardobrasca** [comment]
> [ help-wanted](https://github.com/leanprover-community/mathlib4/issues?q=is%3Aopen+label%3Ahelp-wanted+sort%3Aupdated-desc) The author needs attention to resolve issues : In the original file there was a `omit hpos` many of the theorems don't have it. The omit is not ported, so what is the best way to proceed. Right now I made it build by adding the hpos assumption in many places, but it feels a bit wrong.

I am having a look, but Lean should be smart enough to figure it out by itself now.

**Comment by riccardobrasca** [comment]
I am asking a question on zulip to check if the note I left is the expected behavior.

**Comment by riccardobrasca** [comment]
Yes, this one is now surely good. Let me just wait a little bit to see if we can do something better.

**Comment by riccardobrasca** [comment]
> I am asking a question on zulip to check if the note I left is the expected behavior.

For future references, the discussion is [here](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Auto.20include.20variables) and it is a known issue. The general solution with `include/omit` is to use sections (in this case it was just one lemma, so it was easier).

**Comment by riccardobrasca** [comment]
In any case this one is ready to go, thanks!

bors merge

**Pull request closed without merging**
