### PR TITLE
[Merged by Bors] - chore(CategoryTheory/Monoidal/Comon_): cleanup

### PR DESCRIPTION
**Pull request by kim-em**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by joelriou** [comment]
Thanks!

bors merge

**Comment by joelriou** [comment]
After merging with master, some proofs broke:

bors r-

**Comment by semorrison** [comment]
Thanks, fixed up the proofs. (Happily they got slightly easier, not harder!)

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
