### PR TITLE
[Merged by Bors] - feat: port Data.Real.Pi.Bounds

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Comment by adomani** [comment]
@jcommelin, sorry, I pushed a tiny change, without realizing that you had `bors merge`d the PR...

**Comment by adomani** [comment]
Let me try:

bors merge

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
