### PR TITLE
[Merged by Bors] - chore: robustifying for debug.byAsSorry (part 5)

### PR DESCRIPTION
**Pull request by kim-em**

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
Thanks! All these look reasonable to me.
maintainer merge

**Comment by grunweg** [comment]
(Or perhaps "maintainer delegate", in case further fixes are necessary.)

**Comment by riccardobrasca** [comment]
Thanks!

bors d+

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
