### PR TITLE
[Merged by Bors] - feat(Mathlib/AlgebraicGeometry): Move material on restriction to new file

### PR DESCRIPTION
**Pull request by erdOne**
Also provides new notations and fixed slow proofs

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
!bench

**Comment by jcommelin** [comment]
Nice! If the bench is positive, please merge this.

bors d+

**Comment by erdOne** [comment]
bors merge

**Comment by erdOne** [comment]
bors merge

**Pull request closed without merging**
