### PR TITLE
[Merged by Bors] - feat: port Topology.UniformSpace.Equicontinuity

### PR DESCRIPTION
**Pull request by mcdoll**
---

- [x] depends on: #2159

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#2159
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#2159~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by mcdoll** [comment]
The previous formulation of `comp_rangeSplitting` was a bad translation of the mathlib3 version.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
