### PR TITLE
[Merged by Bors] - feat: require @[simps!] if simps runs in expensive mode

### PR DESCRIPTION
**Pull request by fpvandoorn**
* This does not change the behavior of `simps`, just raises a linter error if you run `simps` in a more expensive mode without writing `!`.
* Fixed some incorrect occurrences of `to_additive, simps`. Will do that systematically in future PR.
* Fix port of `OmegaCompletePartialOrder.ContinuousHom.ofMono` a bit

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
I'm going to merge `master`.

**Comment by urkud** [comment]
I merged `master`, now almost all non-meta changes are about adding `!` here and there (all but one you mention in the commit message). I'm not an expert in meta programming but meta changes look good to me.

**Comment by urkud** [comment]
maintainer merge

**Comment by fpvandoorn** [comment]
I'm treating maintainer merge as bors d+

bors merge

**Pull request closed without merging**
