### PR TITLE
[Merged by Bors] - chore: refactor LinarithConfig object so defaults are easier to find

### PR DESCRIPTION
**Pull request by robertylewis**
`LinarithConfig` was defined before `CertificateOracle` was instantiated, so it couldn't have a proper default. The default was chosen inline in the middle of a long function. Now that we have multiple oracles, it's important to make the default choice visible!

---

Addresses a comment at https://github.com/leanprover-community/mathlib4/pull/12819#issuecomment-2165185245

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by grunweg — COMMENTED** [review]
I don't know the linarith code, but this seems straightforward: most of this is code motion; the rest seems easy enough. Please ask a more expert reviewer if you think this would be useful (I have no idea who that could be, though)!
maintainer merge

**Comment by robertylewis** [comment]
Fixed. But this may have minor conflicts with #12819 which is now on the queue, so let's hold off on bors until that lands.

**Comment by PatrickMassot** [comment]
bors merge

**Comment by PatrickMassot** [comment]
bors merge

**Pull request closed without merging**
