### PR TITLE
[Merged by Bors] - feat: port AlgebraicTopology.DoldKan.Projections

### PR DESCRIPTION
**Pull request by joelriou**
---
- [x] depends on: #3526

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#3526
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
bors d+

Please merge once dependent PRs have been merged.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#3526~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by joelriou** [comment]
Thanks @semorrison for these reviews!

bors r+

**Pull request closed without merging**
