### PR TITLE
[Merged by Bors] - feat: port Algebra.DirectSum.Ring

### PR DESCRIPTION
**Pull request by int-y1**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by int-y1** [comment]
Lean 4 keeps exceeding the max heartbeat limit. I'll stop working on this.

**Comment by nomeata** [comment]
I had a look, but couldn’t make progress. The very slow defEq checks probably mean that something is not working as it should. Even this small lemma is too slow
```
private theorem mul_to_mulHom (a b : ⨁ i, A i) : a * b = mulHom A a b := rfl
```
Needs more expert eyes than mine.

**Comment by nomeata** [comment]
Maybe related to #1260? Also mentions Rings and Timeouts.

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
