### PR TITLE
[Merged by Bors] - refactor(Opposite): `Opposite.mk` -> `Opposite.op` 

### PR DESCRIPTION
**Pull request by mattrobball**
It was observed on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/making.20.60op.60.20irreducible) that we should really have `op` as the custom name for the `Opposite` constructor as long as it remains a structure.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
!bench

**Comment by joelriou** [comment]
It is strange that the CI build succeeds even though there is still a sorry!

**Comment by mattrobball** [comment]
Oh yeah. That doesn't seem good

**Comment by mattrobball** [comment]
!bench

**Review by jcommelin — APPROVED** [review]
Thanks :tada: 

If CI passes, please remove the label `awaiting-CI` and merge this yourself, by adding a comment `bors r+`.

bors d+

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
