### PR TITLE
[Merged by Bors] - feat: Independence of singletons

### PR DESCRIPTION
**Pull request by YaelDillies**
Port a bit of https://github.com/leanprover-community/mathlib/pull/18506, but it's mostly handmade.

---

- [x] depends on: #2513

Rémy, I tried understanding your new independence API but I still feel like I'm butchering your file.

From LeanCamCombi

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by RemyDegenne** [comment]
I will review this more thoroughly in the next two days, but right now I can say that it looks like many results could be generalized to independence with respect to a kernel and a measure (like most results about independence). For example, we could have, in Independence/Kernel.lean,
```
theorem iIndepSets_singleton_iff {s : ι → Set Ω} {_mΩ : MeasurableSpace Ω}
    {κ : kernel α Ω} {μ : Measure α} :
    iIndepSets (fun i ↦ {s i}) κ μ ↔
      ∀ S : Finset ι, ∀ᵐ a ∂μ, κ a (⋂ i ∈ S, s i) = ∏ i in S, κ a (s i) := by
```
I actually wrote a few of those results for #6098 because I wanted to deduce the conditional independence version. That was before I remembered that you had similar lemmas for independence.

If you don't want to generalize the various lemmas yourself, I can do it and push to this PR. Feel free to take from #6098 if you want to do it (I don't think everything is in there, but the example above is).

As for butchering "my" file, no worries: I think the API is far from perfect and I would love it if someone else were to help put some order to it.

**Comment by YaelDillies** [comment]
I had a similar thought about generalizing the results to kernels, but I wasn't sure enough to do it without your advice.

I don't know anything about kernels, so i will have to do some reading.

**Comment by RemyDegenne** [comment]
Sorry, I wrote that I would come back to review more, but the conclusion is simply that this should be generalized and I should have marked it awaiting-author. @YaelDillies, do you mind if I do it and push to this branch?

**Comment by YaelDillies** [comment]
Please do! If you don't have time to do it, I can do it myself tonight, since I've now understood what kernels were.

**Comment by RemyDegenne** [comment]
I've generalized everything to kernel independence. Now we need another reviewer. @JasonKYi perhaps?

**Comment by JasonKYi** [comment]
Can you resolve the merge conflict?

**Comment by JasonKYi** [comment]
Looks good!
maintainer merge

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
