### PR TITLE
[Merged by Bors] - feat(Algebra/Category/Ring/Colimits): category of (possibly non-commutative ring) has colimits

### PR DESCRIPTION
**Pull request by jjaassoonn**
We already have that category of commutative rings has colimits, the same construction works for category of rings.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by erdOne** [comment]
If it is the same construction, can you show that `CommRingCat => RingCat` creates all colimits?

**Comment by jjaassoonn** [comment]
> If it is the same construction, can you show that `CommRingCat => RingCat` creates all colimits?

I just realized I don't understand the maths proof:
We need that the colimit of commutative ring viewed as objects of `RingCat` is still a commutative ring. I am not sure if this true in general.

**Comment by erdOne** [comment]
Ah yes you are right. 
maintainer merge

**Comment by semorrison** [comment]
bors merge

**Pull request closed without merging**
