### PR TITLE
[Merged by Bors] - chore(*): rename `Cstar*` to `CStar*`

### PR DESCRIPTION
**Pull request by urkud**
Moves:
- Cstar* -> CStar*

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
Please fill in the "renames" section of the PR template.

**Comment by urkud** [comment]
The example in the template has an asterisk, so I used `Cstar* -> CStar*`. Do you want me to add more details?

**Comment by j-loreaux** [comment]
Thanks! bors merge

**Comment by urkud** [comment]
@j-loreaux You forgot a newline
bors merge

**Comment by j-loreaux** [comment]
Oops, thanks

**Pull request closed without merging**
