### PR TITLE
[Merged by Bors] - feat: port Topology.MetricSpace.EMetricParacompact

### PR DESCRIPTION
**Pull request by mo271**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
3 `linarith` failures left

**Comment by mo271** [comment]
Please take a look at the place where we now have an explicit `3 = 2 + 1` where `bit1` worked before, see porting note. Is there a better way?

**Comment by urkud** [comment]
Checked out, looking into this.

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
