### PR TITLE
[Merged by Bors] - chore(Topology/../LiminfLimsup): change assumptions of 2 instances

### PR DESCRIPTION
**Pull request by urkud**
- Assume `LinearOrder` instead of `Preorder`.
- Assume `ClosedIciTopology`/`ClosedIicTopology` instead of `OrderTopology`.

`OrderTopology` is usually not the right topology for non-linear orders, so restricting from `Preorder` to `LinearOrder` doesn't break anything.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by YaelDillies** [comment]
> * Assume `LinearOrder` instead of `Preorder`.
> * Assume `ClosedIciTopology`/`ClosedIicTopology` instead of `OrderTopology`.

Actually, could you only do the second? I need a `BoundedLENhdsClass` instance on `ℝⁿ` and your second change without your first gives a way to find that instance. There's already a way through `Pi.instBoundedLENhdsClass`, but I still take that as a sign that the `ClosedIciTopology → BoundedLENhdsClass` instance is a good idea.

**Comment by urkud** [comment]
@YaelDillies  `eventually_le_nhds` needs a `LinearOrder`.

**Review by YaelDillies — APPROVED** [review]
Ah, I hadn't caught that but it makes sense indeed.

maintainer merge

**Comment by sgouezel** [comment]
bors r+
Thanks!

**Pull request closed without merging**
