### PR TITLE
[Merged by Bors] - lower priority of Instance involving SMul and Subtype

### PR DESCRIPTION
**Pull request by Thmoas-Guan**
Lower priority of instance `IntermediateField.instSMulSubtypeMemOfAlgebra` to 900.
Because it would cause trouble when synthesizing instance `SMul K L` where `K < L` are `IntermediateField F E`

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mattrobball** [comment]
The instance can be synthesized already. Can you check the impact of just removing it?

**Comment by Thmoas-Guan** [comment]
Let me have a try!

**Comment by Thmoas-Guan** [comment]
!bench

**Comment by mattrobball** [comment]
Those results are very strange. I'll look at the import graph next chance I get. Thanks!

**Comment by mattrobball** [comment]
!bench

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
