### PR TITLE
refactor(NumberTheory/FLT): Change `n ≥ 3` to `n > 2`

### PR DESCRIPTION
**Pull request by tb65536**
This PR changes `n ≥ 3` to `n > 2`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by tb65536** [comment]
It just seemed like it's more common in mathlib to write `k < n` rather than `k+1 <= n` since the former is a bit simpler, but I could be wrong.

**Comment by riccardobrasca** [comment]
Unless there is a real motivation (TBH I don't see it, but who knows), I propose to take .this picture as the official statement of FLT.
image

**Comment by riccardobrasca** [comment]
I mean, with the modifications that makes it not obviously false...

**Comment by tb65536** [comment]
Fair enough :)

**Pull request closed without merging**
