### PR TITLE
[Merged by Bors] - feat: port Analysis.Complex.UpperHalfPlane.Metric

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
---

- [x] depends on: #5531

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5531
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors d+

Please merge once the dependency has landed in master.

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5531~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by Parcly-Taxel** [comment]
bors merge

**Pull request closed without merging**
