### PR TITLE
[Merged by Bors] - feat: port Algebra.ContinuedFractions.Computation.Approximations

### PR DESCRIPTION
**Pull request by int-y1**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by int-y1** [comment]
todo:

* [ ] `fib_le_of_continuantsAux_b` unknown tactic `mono`
* [ ] `abs_sub_convergents_le` unknown tactic `mono`
* [ ] in theorem names and parameter names, use `get?` and `nth` consistently

**Comment by mo271** [comment]
I fixed the missing `mono` tactic manually, adding a porting note: I think we shouldn't wait until the tactic is ported...

**Comment by jjaassoonn** [comment]
All checks have passed, why is this PR marked `help-wanted`?

**Comment by mo271** [comment]
I don't know, perhaps because of the 
>
> - [ ]  in theorem names and parameter names, use get? and nth consistently

**Comment by Ruben-VandeVelde** [comment]
Did `mono` fail to make progress or was it a missing `import Mathlib.Tactic.Monotonicity`?

**Comment by mo271** [comment]
I suppose we didn't import `mono` at the time. I tried it now:
For the first `mono` it worked somewhat, although `tauto` and `norm_num` after it were necessary now and not before.
For the second case `mono` simplifies to something that is harder to prove than what needs to be done before.

**Comment by Ruben-VandeVelde** [comment]
I think the names are fine.

**Comment by j-loreaux** [comment]
LGTM

maintainer merge

**Pull request closed without merging**
