### PR TITLE
[Merged by Bors] - chore: fix "open Mathlib" benchmark

### PR DESCRIPTION
**Pull request by Kha**

### CODE REVIEW

**Comment by eric-wieser** [comment]
Is this fixing an incorrect value or a crash?

**Comment by semorrison** [comment]
It is preemptively adapting to an upcoming change in behaviour in `lake`.

**Comment by semorrison** [comment]
bors d+

(I won't send it immediately to bors in case it is intentionally not marked `awaiting-review`.)

**Pull request closed without merging**
