### PR TITLE
[Merged by Bors] - chore: split application of the layer cake formula into its own file

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
---

This should slightly improve the longest pole.

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
!bench

**Comment by Ruben-VandeVelde** [comment]
!bench

**Comment by Ruben-VandeVelde** [comment]
```diff
-Analyzing Mathlib at 913dc471aee5ed0e647c470ada11517708044991
+Analyzing Mathlib at 5c1a212efea94ddb08b31f05691db40cdf43e1c4
 file                                                           | instructions | (cumulative) | parallelism
 -------------------------------------------------------------- | ------------ | ------------ | -----------
-Mathlib                                                        |         8020 |      5628110 | x21.59
-Mathlib.NumberTheory.Cyclotomic.Three                          |        33251 |      5620089 | x9.11
-Mathlib.NumberTheory.Cyclotomic.Rat                            |       116162 |      5586838 | x9.09
-Mathlib.NumberTheory.Cyclotomic.Discriminant                   |        42628 |      5470676 | x9.26
-Mathlib.NumberTheory.NumberField.Discriminant                  |       216420 |      5428047 | x9.18
-Mathlib.NumberTheory.NumberField.CanonicalEmbedding.ConvexBody |       188679 |      5211627 | x9.50
-Mathlib.MeasureTheory.Measure.Lebesgue.VolumeOfBalls           |        63614 |      5022948 | x7.69
-Mathlib.Analysis.SpecialFunctions.Gamma.BohrMollerup           |        37616 |      4959333 | x7.75
-Mathlib.Analysis.SpecialFunctions.Gaussian.GaussianIntegral    |        38268 |      4921716 | x7.81
-Mathlib.Analysis.SpecialFunctions.Gamma.Basic                  |        39229 |      4883448 | x7.85
-Mathlib.Analysis.MellinTransform                               |        40446 |      4844219 | x7.90
-Mathlib.Analysis.SpecialFunctions.ImproperIntegrals            |        15860 |      4803772 | x7.95
-Mathlib.Analysis.SpecialFunctions.JapaneseBracket              |        98517 |      4787912 | x7.71
-Mathlib.MeasureTheory.Integral.Layercake                       |        29846 |      4689395 | x7.82
-Mathlib.Analysis.SpecialFunctions.Integrals                    |       115381 |      4659548 | x7.86
+Mathlib                                                        |         8019 |      5598362 | x21.71
+Mathlib.NumberTheory.Cyclotomic.Three                          |        33249 |      5590342 | x9.16
+Mathlib.NumberTheory.Cyclotomic.Rat                            |       116162 |      5557093 | x9.14
+Mathlib.NumberTheory.Cyclotomic.Discriminant                   |        42628 |      5440930 | x9.31
+Mathlib.NumberTheory.NumberField.Discriminant                  |       216421 |      5398302 | x9.23
+Mathlib.NumberTheory.NumberField.CanonicalEmbedding.ConvexBody |       188677 |      5181881 | x9.55
+Mathlib.NumberTheory.NumberField.CanonicalEmbedding.Basic      |       147390 |      4993203 | x9.39
+Mathlib.NumberTheory.NumberField.Embeddings                    |       131726 |      4845813 | x8.60
+Mathlib.Analysis.Complex.Polynomial                            |        29487 |      4714087 | x8.49
+Mathlib.Analysis.Complex.Liouville                             |        16739 |      4684600 | x7.99
+Mathlib.Analysis.Complex.CauchyIntegral                        |        53856 |      4667860 | x8.01
+Mathlib.MeasureTheory.Integral.CircleIntegral                  |        70001 |      4614004 | x7.87
 Mathlib.Analysis.SpecialFunctions.NonIntegrable                |        14965 |      4544___ | x7.90
 Mathlib.MeasureTheory.Integral.FundThmCalculus                 |        9049_ |      4529___ | x7.50
```

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
