### PR TITLE
fix(test/rewrites): add infos

### PR DESCRIPTION
**Pull request by adomani**
Do not drop infos from output of `rw?`.

The discussion at the end of #6868 prompted reviewing the changes in that PR that affected `rewrites`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by kmill — COMMENTED** [review]
I think we should be careful being aware of what we're trying to test in these tests. Some are simply about whether `rw?` succeeds, and others are about the heuristics `rw?` uses and which lemmas it finds. For the first, we don't care about the exact list of lemmas it chose, and for the second we do.

Ideally for the second type of test we have a framework for this along with some carefully curated list of lemmas for `rw?` to try (like @digama0 suggested in #6868).

In the following comments, I've given my thoughts for each existing `#guard_msgs` test and whether we should drop the info or not.

**Comment by adomani** [comment]
Kyle, I agree with all your suggestions!  I am simply going to wait to implement them until someone else also agrees with them, maybe by liking your proposals, before implementing them.

A quick heuristic seems that, when the output of `rw?` contains at least 3 suggestions, we drop the info.  The converse is almost true as well.

**Comment by digama0** [comment]
I think we should remove all the imports from this file except for `Mathlib.Tactic.Rewrites`, which should significantly reduce the number of suggestions, and for anything other than regression tests we should either keep the info or replace it with a synthetic example (and keep the info).

**Comment by adomani** [comment]
Mario, I do not understand why, but this is what happens:
```lean
import Mathlib.Tactic.Rewrites
--import Mathlib.Data.List.Basic

set_option autoImplicit true

example (f : α → β) (L M : List α) : (L ++ M).map f = L.map f ++ M.map f := by
  rw?

/-  suggestions:
Try this: rw [@List.map_append]
-- List.map f L ++ List.map f M = List.map f L ++ List.map f M

Try this: rw [← @List.map_append]
-- List.map f (L ++ M) = List.map f (L ++ M)

Try this: rw [← @List.append_eq]
-- List.map f (List.append L M) = List.map f L ++ List.map f M

Try this: rw [← @List.foldr_self_append]
-- List.map f (List.foldr List.cons M L) = List.map f L ++ List.map f M

Try this: rw [← @List.toArray_eq_toArray_eq]
-- List.toArray (List.map f (L ++ M)) = List.toArray (List.map f L ++ List.map f M)

Try this: rw [← @List.filterMap_eq_map]
-- List.filterMap (some ∘ f) (L ++ M) = List.filterMap (some ∘ f) L ++ List.filterMap (some ∘ f) M

Try this: rw [List.map_eq_mapTR]
-- List.mapTR f (L ++ M) = List.mapTR f L ++ List.mapTR f M
-/
```

while, if you uncomment `import Mathlib.Data.List.Basic`, then you get
```lean
Try this: rw [@List.map_append]
-- "no goals"
```
and nothing else.

**Comment by digama0** [comment]
How does `rw?` close goals? It's possible that it needs something to be `@[refl]` marked and `Mathlib.Tactic.Rewrites` alone doesn't import anything other than lean/std and so is missing a lot of mathlib annotations.

**Comment by adomani** [comment]
I think that the same behaviour begins at `import Mathlib.Init.Core`.

**Comment by adomani** [comment]
You are completely right, Mario!  Adding just `attribute [refl] Eq.refl` and no other import, gives a single suggestion!

**Comment by adomani** [comment]
> I think we should remove all the imports from this file except for `Mathlib.Tactic.Rewrites`, which should significantly reduce the number of suggestions, and for anything other than regression tests we should either keep the info or replace it with a synthetic example (and keep the info).

I agree with this.  However, a lot of the tests do not even compile with more imports.  Maybe we should have
* one test file for the actual output of `rw?`, testing heuristics and implementations with minimal imports and
* another test file with all the required imports that tests "expected behaviour", such as closing/non-closing goals, seeing through stuff and so on.

**Comment by digama0** [comment]
> another test file with all the required imports that tests "expected behaviour", such as closing/non-closing goals, seeing through stuff and so on.

That also sounds like it would need minimal imports. Specific behavior like seeing through stuff should be done in controlled situations, closing/non-closing goals should be confined to regression tests and can be mocked in the test file.

**Comment by adomani** [comment]
Ok, I split off a file containing the tests that should be less controversial and has small imports.  I left the possibly more controversial tests and the large imports in the other.  Maybe this will focus the discussion!

**Pull request closed without merging**
