### PR TITLE
[Merged by Bors] - chore(Order/UpperLower/Basic): move definitions to `Defs` file

### PR DESCRIPTION
**Pull request by vihdzp**
This way I can avoid the large imports warning in #17632.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by YaelDillies** [comment]
I have to think whether that's the right thing to do, rather than eg making `OrdConnected` a less heavy import

**Comment by vihdzp** [comment]
I think it makes sense to have these definitions in a `Defs` file, for the same reason other `Defs` files make sense: this is a pretty basic notion which you often need no API whatsoever to prove. `OrdConnected`, or any of the other imports in `UpperLower.Basic`, aren't really all that heavy. It's just that the file I need them in is a very early file as well.

**Comment by vihdzp** [comment]
So, did you think about this?

**Comment by YaelDillies** [comment]
Yes I have thought about it. I would like to have a general `Order.Defs` file with all the very basic definitions, rather than one `Defs` file per set of basic definitions.

**Comment by vihdzp** [comment]
I like that approach. Will adjust this PR accordingly.

**Comment by vihdzp** [comment]
Actually, turns out `Order/Defs` is so low-level `Set` hasn't been defined at that point! So we do need at the very least two Defs files.

**Comment by YaelDillies** [comment]
Can't we import Data.Set.Defs there?

**Comment by vihdzp** [comment]
I feel a bit uneasy modifying the imports of a file only 50 imports deep, but I guess I can try. I'll do so tomorrow.

**Comment by vihdzp** [comment]
The large import warning is pretty misleading, since the count just goes from 39 to 44 :P

**Comment by YaelDillies** [comment]
And only a handful of files have their imports increased at all 🎉

**Comment by YaelDillies** [comment]
maintainer merge

**Comment by urkud** [comment]
Thanks! :tada:
bors merge

**Comment by vihdzp** [comment]
@urkud This PR is ready for Bors now.

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
