### PR TITLE
[Merged by Bors] - fix: avoid `with` in `Finsupp.module`

### PR DESCRIPTION
**Pull request by kbuzzard**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

If this does actually improve performance it's a good example of "`with` considered harmful"

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
LGTM, thanks!

bors d+

**Comment by kbuzzard** [comment]
Just to comment that I've now checked that all of the four maxHeartbeats changes fail on the commit of master which this branched off.

**Comment by eric-wieser** [comment]
If that's the case I'm happy for you to just merge this: we'll probably want to run the benchmark one more time once its merged anyway to indicate the result on the main graph.

**Comment by kbuzzard** [comment]
Perhaps I'll wait until it passes CI. I've compiled it locally (many times!) but only up to the group cohomology files.

**Pull request closed without merging**
