### PR TITLE
[Merged by Bors] - feat: port FieldTheory.Finite.GaloisField

### PR DESCRIPTION
**Pull request by xroblot**
~~This PR should wait until the discussion [here](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/!4.234891.20.20FieldTheory.2ESplittingField/near/367157525) is resolved~~

- [x] depends on: #5284

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by riccardobrasca** [comment]
We are waiting for [!4#5284](https://github.com/leanprover-community/mathlib4/pull/5284), but I think you can already use the new mathport output (don't forget to update the hash!)

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#5284
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#5284~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by ChrisHughes24** [comment]
bors merge

**Pull request closed without merging**
