### PR TITLE
[Merged by Bors] - feat(Algebra/GroupWithZero/WithZero): `WithZero.map'`

### PR DESCRIPTION
**Pull request by mariainesdff**
---

- [x] depends on: #12351

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by eric-wieser — COMMENTED** [review]
This looks like the wrong approach to me; what you call `coeMonoidHom` is usually called `map`, and most `map` definitions actually fall out as a special case of `lift`:
```lean
/-- Coercion as a monoid hom -/
@[simps]
def coeMonoidHom [MulOneClass G] : G →* WithZero G where
  toFun := (↑)
  map_one' := rfl
  map_mul' _ _ := rfl

/-- The (multiplicative) universal property of `WithZero` -/
noncomputable nonrec def lift [Monoid G] [MonoidWithZero H] :
    (G →* H) ≃ (WithZero G →*₀ H) where
  toFun f :=
    { toFun := fun
        | 0 => 0
        | (g : G) => f g
      map_zero' := rfl
      map_one' := map_one f
      map_mul' := fun
        | 0, _ => (zero_mul _).symm
        | (_ : G), 0 => (mul_zero _).symm
        | (_ : G), (_ : G) => map_mul f _ _ }
  invFun F := F.toMonoidHom.comp coeMonoidHom
  left_inv _ := rfl
  right_inv f := DFunLike.ext _ _ fun
    | 0 => (map_zero f).symm
    | (_ : G) => rfl
```

**Comment by mariainesdff** [comment]
> This looks like the wrong approach to me; what you call `coeMonoidHom` is usually called `map`, and most `map` definitions actually fall out as a special case of `lift`:

Thanks, I have refactored it as suggested. Since the names `WithZero.map` and `WithZero.lift` are already taken (for additive maps), I have used `WithZero.map'` and`WithZero.lift'`, but please let me know if you have other naming suggestions.

**Comment by eric-wieser** [comment]
`mapMonoidHom` and `liftMonoidHom` would also be good names. Perhaps we should rename the existing defs in the same style, rather than picking favorites with `'`?

**Comment by eric-wieser** [comment]
Looking more closely, I think the primed name is ok. Can you copy across some of the other API for the unprimed version?

**Comment by erdOne** [comment]
maintainer merge

**Comment by YaelDillies** [comment]
Could you move this out of `Algebra.Group`? Everything is supposed to be additivisable there. What about `Algebra.GroupWithZero.WithZero`?

**Review by YaelDillies — APPROVED** [review]

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Pull request closed without merging**
