### PR TITLE
feat(List/EraseIdx): new file

### PR DESCRIPTION
**Pull request by urkud**
---

- [x] depends on: #12326

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by urkud** [comment]
TIL that we have `List.eraseIdx` in core and `List.removeNth` in `Std`. Not sure what should we do about this.

**Comment by urkud** [comment]
As far as I understand, @digama0 prefers for lemmas like these to be tested in Mathlib before moving upstream.

**Comment by urkud** [comment]
I can reopen this PR agains batteries, of course.

**Comment by digama0** [comment]
I think this is more of a concern for new definitions as opposed to new lemmas about existing definitions. There are still possibly things one can get wrong about lemmas that can be worked out by getting use, like the implicitness and order of binders, but for the most part it's already in scope just for being a definition about upstream things.

**Comment by urkud** [comment]
Then I'll close this PR and reopen it in Batteries tomorrow.

**Pull request closed without merging**
