### PR TITLE
[Merged by Bors] - feat: port GroupTheory.FiniteAbelian

### PR DESCRIPTION
**Pull request by mo271**
- [x] depends on: #4707

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by mo271** [comment]
Not sure if the instance `Unique (Fin Nat.zero →₀ ℤ)` should be added in some other place, but putting it right in the proof works. Should we add a porting note that this was inferred automatically before?

**Comment by semorrison** [comment]
This PR/issue depends on:
* leanprover-community/mathlib4#4707
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Comment by semorrison** [comment]
This PR/issue depends on:
* ~~leanprover-community/mathlib4#4707~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!

**Review by jcommelin — APPROVED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
