### PR TITLE
[Merged by Bors] - chore: move some lemmas to Analysis.Normed.Group.Uniform

### PR DESCRIPTION
**Pull request by Ruben-VandeVelde**
From #13713.

Co-authored-by: Yaël Dillies <yael.dillies@gmail.com>

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
!bench

**Comment by Ruben-VandeVelde** [comment]
!bench

**Comment by Ruben-VandeVelde** [comment]
```diff
-Analyzing Mathlib at feba7083215c280aeda7173e3013e2e61177f4ee
+Analyzing Mathlib at 6409cee35dc384daef04b0edfc695a41ae2ec145
 | file                                                           | instructions | cumulative | parallelism |
 | :------------------------------------------------------------- | -----------: | ---------: | :---------: |
-| Mathlib.Analysis.Normed.MulAction                              |        18392 |    1842073 |    7.51     |
-| Mathlib.Analysis.Normed.Field.Basic                            |        88954 |    1823680 |    7.58     |
-| Mathlib.Analysis.Normed.Group.Constructions                    |        15750 |    1734726 |    6.63     |
-| Mathlib.Analysis.Normed.Group.Basic                            |        85574 |    1718976 |    6.68     |
-| Mathlib.Topology.MetricSpace.IsometricSMul                     |        31168 |    1633401 |    6.46     |
-| Mathlib.Topology.MetricSpace.Isometry                          |        13856 |    1602233 |    5.34     |
-| Mathlib.Topology.MetricSpace.Antilipschitz                     |         8002 |    1588377 |    5.38     |
-| Mathlib.Topology.MetricSpace.Bounded                           |        14219 |    1580374 |    5.39     |
-| Mathlib.Topology.MetricSpace.ProperSpace                       |         5533 |    1566155 |    5.42     |
-| Mathlib.Topology.Algebra.Order.Compact                         |        28095 |    1560622 |    4.18     |
-| Mathlib.Topology.Order.IntermediateValue                       |        51599 |    1532526 |    4.12     |
+| Mathlib.Analysis.Normed.MulAction                              |        18392 |    1811923 |    7.64     |
+| Mathlib.Analysis.Normed.Field.Basic                            |        88949 |    1793530 |    7.71     |
+| Mathlib.Analysis.Normed.Group.Uniform                          |        24172 |    1704580 |    6.74     |
+| Mathlib.Analysis.Normed.Group.Basic                            |        65714 |    1680408 |    6.76     |
+| Mathlib.Topology.Instances.Rat                                 |        12824 |    1614693 |    6.96     |
+| Mathlib.Topology.Instances.Real                                |        13929 |    1601869 |    7.00     |
+| Mathlib.Topology.Instances.Int                                 |         5136 |    1587939 |    5.42     |
+| Mathlib.Topology.Instances.Discrete                            |         6825 |    1582802 |    5.32     |
+| Mathlib.Topology.Metrizable.Uniformity                         |        13787 |    1575976 |    5.34     |
+| Mathlib.Topology.Metrizable.Basic                              |         4945 |    1562189 |    5.37     |
+| Mathlib.Topology.MetricSpace.Basic                             |         9750 |    1557243 |    5.38     |
+| Mathlib.Topology.MetricSpace.PseudoMetric                      |        66566 |    1547492 |    5.41     |
 | Mathlib.Topology.Order.DenselyOrdered                          |        86287 |    148092_ |    4.22     |
 | Mathlib.Topology.Order.IsLUB                                   |        15787 |    1394639 |    4.42     |
```

**Comment by YaelDillies** [comment]
I've opened #13977 to reduce the long pole further from here.

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
