### PR TITLE
[Merged by Bors] - chore: Make more arguments to `inter_subset_left` implicit

### PR DESCRIPTION
**Pull request by YaelDillies**
There are a few commonplace lemmas whose explicit arguments are (almost) always inferred in practice. This means that one needs to put brackets around and feeds them underscores very often. This is annoying.

Remove the explicit arguments to the six most commonplace (series of) lemmas that are like that:
* `inter_subset_left`
* `inter_subset_right`
* `subset_union_left`
* `subset_union_right`
* `Set.diff_subset`/`Finset.sdiff_subset`
* `Function.Injective.InjOn`

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by rosborn** [comment]
I'm roughly 90% sure this should build.

**Comment by rosborn** [comment]
Should I split off the `inter_subset_(left|right`, `subset_union_(left|right)`, and `InjOn` each into their own PRs to hopefully get them reviewed faster? This diff is already quite large.

**Comment by YaelDillies** [comment]
No, don't bother. I'll ask for a quick review of everything when CI is happy.

**Review by Parcly-Taxel — APPROVED** [review]

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
