### PR TITLE
[Merged by Bors] - fix(test/Lint.lean): re-enable test for duplicate namespaces

### PR DESCRIPTION
**Pull request by grunweg**
There is a standard hack for dealing with linters running on #guard_msg themselves - so re-enable the test using it.
One test broke during the std->batteries rename; fix it.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by grunweg** [comment]
CC @adomani since you wrote the test, and @semorrison since you last modified it

**Comment by adomani** [comment]
Does it work to disable the test in the file with `set_option linter.dupNamespace false` and then leaving in just the `set_option linter.dupNamespace true in` after each `#guard_msgs`?

Otherwise, looks good to me!

**Comment by grunweg** [comment]
Yes, it does - just made this change. (Sorry for the force push!)

**Comment by adomani** [comment]
To fix the failing test, I think that it suffices to change `Std.Tactic.Alias.alias` to `Batteries.Tactic.Alias.alias` in the `Mathlib.Tactic.Lint`.

**Comment by grunweg** [comment]
Thanks, that did the trick - fixed.

**Review by adomani — APPROVED** [review]
Thanks!

maintainer merge

**Comment by adomani** [comment]
maintainer merge

**Comment by bryangingechen** [comment]
Thanks!
bors r+

**Pull request closed without merging**
