### PR TITLE
[Merged by Bors] - refactor: Unsimp `div_pow`/`div_zpow`

### PR DESCRIPTION
**Pull request by YaelDillies**
... and additive versions. These lemmas are not affine (`n` appears twice on the RHS and only once on the LHS). Also note that `mul_pow` and `mul_zpow` are analogous but not simp.

From LeanAPAP

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
Is `mul_zpow` a simp lemma? If so, then I'm not sure I agree with this PR; if not, then I think that's a good justification to include in the description.

**Review by eric-wieser — APPROVED** [review]
bors merge

Thanks!

**Comment by urkud** [comment]
bors merge

**Comment by eric-wieser** [comment]
This breaks
```
example : (Complex.I / 3) ^ 2 = -(1 / 9) := by norm_num
```
which is annoying

**Comment by YaelDillies** [comment]
Those lemmas can be added back to the `norm_num` simp set. That's what I did for `field_simp`

**Pull request closed without merging**
