### PR TITLE
[Merged by Bors] - chore: update style exceptions

### PR DESCRIPTION
**Pull request by grunweg**
This includes a re-ordering, due to rewriting the 'file length' check in Lean. All of this is automatically generated, so a one-time effect only.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by j-loreaux** [comment]
bors merge

**Comment by j-loreaux** [comment]
sorry, does this depend on another PR @grunweg ?

**Comment by grunweg** [comment]
@j-loreaux No, it does not: this PR stands on its own.

**Comment by j-loreaux** [comment]
bors merge

**Pull request closed without merging**
