### PR TITLE
[Merged by Bors] - perf(CategoryTheory/Sites/Sheaf): speed up a slow proof

### PR DESCRIPTION
**Pull request by joelriou**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by dagurtomas** [comment]
maintainer merge

**Comment by mattrobball** [comment]
How does this perform vs #15592 ?

**Comment by dagurtomas** [comment]
`set_option profiler true` reports 

On this PR:
```
dsimp took 423ms
compilation of CategoryTheory.Presheaf.isSheafForIsSheafFor' took 746ms
```

On #15192:
```
simp took 108ms
dsimp took 389ms
simp took 368ms
```

**Comment by mattrobball** [comment]
The problem was compilation so this is good.

**Comment by mattrobball** [comment]
bors merge

**Pull request closed without merging**
