### PR TITLE
[Merged by Bors] - feat: "outer product" of functions that tend to zero on the cocompact filter

### PR DESCRIPTION
**Pull request by trivial1711**
Let `M` be a topological space with a continuous multiplication operation and a zero.

We prove that if `f : α → M` and `g : β → M` are continuous functions that both tend to zero on the cocompact filter, then the "outer product" `fun (i : α × β) ↦ (f i.1) * (g i.2)` also tends to zero on the cocompact filter.

We then specialize this result to the case that `α` and `β` have the discrete topology.

Co-authored-by: Anatole Dedecker <anatolededecker@gmail.com>

---

- [x] depends on: #12305
- [x] depends on: #19650

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by ADedecker** [comment]
Very nice work, thanks a lot!

I think it would be nice to split up some useful lemmas from the main proof, e.g a version of [Filter.Tendsto.zero_mul_isBoundedUnder_le](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Analysis/Normed/Field/Basic.html#Filter.Tendsto.zero_mul_isBoundedUnder_le) where the "IsBoundedUnder" hypothesis is replaced by "being disjoint from `cocompact`". Then I would deduce a lemma saying that multiplication tends to zero along the infimum of `coprod (𝓝 0) (𝓝 0)` and any filter on the product which is disjoint from `cocompact`. And finally deduce your current result. 

Does that make sense to you? The reason I'm suggesting this is because I think at least the first intermediate lemma will be useful, and probably the second as well (although I'm less sure).

**Comment by trivial1711** [comment]
Yes, that makes sense. Thank you for reading it. I'll work on it soon.

**Comment by trivial1711** [comment]
I proved the lemmas that ADedecker requested. They're on another branch: https://github.com/leanprover-community/mathlib4/tree/trivial1711-mulzero-cocompact

I can't figure out how to actually use those lemmas to simplify the proof of `tendsto_mul_cocompact_nhds_zero`, though.

I apologize that this has taken so long.

**Comment by ADedecker** [comment]
You don't have to apologize at all! In fact I should probably be the one apologizing for causing troubles by giving unclear instructions. What I had in mind is the following:
- using [Filter.Tendsto.prod_map_coprod](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Order/Filter/Prod.html#Filter.Tendsto.prod_map_coprod) and [Filter.coprod_cocompact](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Topology/Compactness/Compact.html#Filter.coprod_cocompact), get that `Prod.map f g` tends to `(𝓝 0).coprod (𝓝 0)` along the cocompact filter. 
- but `Prod.map f g` also converges to `𝓟 (range (Prod.map f g))`, which is disjoint from the cocompact filter since that range is contained in a compact set.
- hence, you can apply `tendsto_mul_nhds_zero_of_disjoint_cocompact` (from your new PR) to `l = map (Prod.map f g) (cocompact _)` to get the result.

Does that make sense? If you're tired of this I can have a go at it as well.

**Comment by trivial1711** [comment]
Hi, I will try to modify the proof to use those facts as you describe. For now, I have reconfigured the branches so that this PR (#12313) now depends on #19650, instead of the other way around. Can you take a look at that one?

**Comment by trivial1711** [comment]
I'm still not entirely sure what to do with this. You can push directly to this branch if you have a way to simplify the proof.

**Comment by ADedecker** [comment]
I just pushed what I had in mind!

**Comment by trivial1711** [comment]
Thanks; I've added you as a coauthor.

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
