### PR TITLE
[Merged by Bors] - chore(*): use `gcongr` and `omega` here and there

### PR DESCRIPTION
**Pull request by urkud**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by eric-wieser** [comment]
I guess this batch was found by searching for `add_le_add`?

**Comment by urkud** [comment]
Yes, I searched for `add_le_add`, then golfed some of the instances.

**Review by Ruben-VandeVelde — APPROVED** [review]
Seems fine

maintainer merge

**Review by jcommelin — COMMENTED** [review]
Thanks :tada:

bors merge

**Pull request closed without merging**
