### PR TITLE
[Merged by Bors] - chore: move (locally) ringed spaces out of `AlgebraicGeometry`

### PR DESCRIPTION
**Pull request by hrmacbeth**
Create new folder `Geometry.RingedSpace` for (locally) ringed spaces and move about half of the contents of `AlgebraicGeometry` there.  Files renamed:
```
AlgebraicGeometry.OpenImmersion.Scheme → AlgebraicGeometry.OpenImmersion
AlgebraicGeometry.RingedSpace → Geometry.RingedSpace.Basic
AlgebraicGeometry.LocallyRingedSpace → Geometry.RingedSpace.LocallyRingedSpace
AlgebraicGeometry.LocallyRingedSpace.HasColimits → Geometry.RingedSpace.LocallyRingedSpace.HasColimits
AlgebraicGeometry.OpenImmersion.Basic → Geometry.RingedSpace.OpenImmersion
AlgebraicGeometry.PresheafedSpace → Geometry.RingedSpace.PresheafedSpace
AlgebraicGeometry.PresheafedSpace.Gluing → Geometry.RingedSpace.PresheafedSpace.Gluing
AlgebraicGeometry.PresheafedSpace.HasColimits → Geometry.RingedSpace.PresheafedSpace.HasColimits
AlgebraicGeometry.SheafedSpace → Geometry.RingedSpace.SheafedSpace
AlgebraicGeometry.Stalks → Geometry.RingedSpace.Stalks
```

See [Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/split.20AlgebraicGeometry).

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by alreadydone** [comment]
```
AlgebraicGeometry.RingedSpace → Geometry.RingedSpace.Basic
```

This may cause confusion as PresheafedSpace and ShafedSpace are more basic files in the same folder. Geometry.RingedSpace.RingedSpace is a bit repetitive but acceptable to me.

**Comment by joelriou** [comment]
> ```
> AlgebraicGeometry.RingedSpace → Geometry.RingedSpace.Basic
> ```
> 
> This may cause confusion as PresheafedSpace and ShafedSpace are more basic files in the same folder. Geometry.RingedSpace.RingedSpace is a bit repetitive but acceptable to me.

`Geometry.RingedSpace.Basic` seems ok to me. We have other folders where `Basic.lean` import other "more basic" files in the same folder (e.g. `RepresentationTheory.GroupCohomology`).

**Review by alreadydone — APPROVED** [review]
LGTM, and I confirm these are all the files that can be moved from the AlgebraicGeometry folder. PresheafedSpace.Gluing and Stalks are missing from the PR description though.

**Comment by hrmacbeth** [comment]
> PresheafedSpace.Gluing and Stalks are missing from the PR description though.

Thanks, fixed!

**Comment by jcommelin** [comment]
Thanks :tada:

bors merge

**Pull request closed without merging**
