### PR TITLE
[Merged by Bors] - refactor: rename `HasSup`/`HasInf` to `Sup`/`Inf`

### PR DESCRIPTION
**Pull request by Komyyy**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by Ruben-VandeVelde — APPROVED** [review]

**Comment by ChrisHughes24** [comment]
bors merge

**Comment by ChrisHughes24** [comment]
bors r-
bors d+

**Comment by urkud** [comment]
I'm going to merge master and fix compile.

**Comment by Komyyy** [comment]
Thank you, @urkud!
bors r+

**Pull request closed without merging**
