### PR TITLE
[Merged by Bors] - feat: `1 - x⁻¹ ≤ log x`

### PR DESCRIPTION
**Pull request by YaelDillies**
From LeanAPAP

Co-authored-by: Bhavik Mehta <bhavik.mehta8@gmail.com>

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by b-mehta** [comment]
I'm not really sure this deserves to be a lemma in this file (or even a public lemma at all) - it's a trivial consequence of `log_le_sub_one_of_pos` and should be used as such in applications

**Comment by YaelDillies** [comment]
Given that we spent several hours trying to prove it on Xena, I'm not sure I would call that "trivial"...

**Comment by b-mehta** [comment]
I disagree pretty strongly on that - you can see from the proof that it's literally an application of that lemma combined with basic algebra - variants like this show up really often in practice, clearly not all of them should be lemmas.

The one variant I wouldn't mind having is 1 - 1/x <= log(x), since then we have a lower and upper bound on log. Again your lemma is a trivial consequence of this.

**Comment by b-mehta** [comment]
Okay now I'm happy :)

bors merge

**Pull request closed without merging**
