### PR TITLE
[Merged by Bors] - feat: generalize `AEMeasurable.indicator` to `NullMeasurableSet`

### PR DESCRIPTION
**Pull request by ADedecker**
---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by kkytola — COMMENTED** [review]
This meaningful generalization looks like a clear improvement, and it is implemented efficiently with just a few lines of changes.

(Full disclosure: my own PR #6225 depends on this.)

**Comment by RemyDegenne** [comment]
For many lemmas in measure theory, we have a version for measurable and another version for ae/null measurable, with the same name as the measurable one suffixed by `₀`. The reason is that measurable sets are much more common than null-measurable sets and we want to avoid the conversion. See for example [MeasureTheory.Measure.restrict_apply₀](https://leanprover-community.github.io/mathlib4_docs/Mathlib/MeasureTheory/Measure/MeasureSpace.html#MeasureTheory.Measure.restrict_apply%E2%82%80) . Could you do that here? That is, don't replace the measurable set version, but add a new one for null-measurable sets?
Also, could you add a null-measurable version of `aemeasurable_indicator_iff` as well?

**Comment by ADedecker** [comment]
Oh I didn't know about it, that makes sense.

**Comment by RemyDegenne** [comment]
Thanks!
bors r+

**Pull request closed without merging**
