### PR TITLE
chore: fix Data.Bool to use `_root_.decide_eq_true`

### PR DESCRIPTION
**Pull request by pechersky**
by calling out to `_root_`
There was a clash between PRs

### CODE REVIEW

**Comment by pechersky** [comment]
Locally, this is causing `make lint` to complain -- not sure why both commits succeeded on CI, I would have thought the first would have failed.

**Comment by kbuzzard** [comment]
This looks fine to me but I don't know about the lint issues.

**Comment by pechersky** [comment]
`make lint` isn't so much about the linter, I use it as the most noisy lean builder

**Comment by semorrison** [comment]
@pechersky, I'm confused, this PR has no effect: there's no `Bool.decide_eq_true` to disambiguate with.

**Pull request closed without merging**
