### PR TITLE
[Merged by Bors] - chore: @[simp] cancel_(right|left)

### PR DESCRIPTION
**Pull request by kim-em**
---

- [x] depends on: #6297

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Comment by semorrison** [comment]
!bench

**Comment by semorrison** [comment]
One file got slower, but overall wall-clock is identical (epsilon faster), so I propose not worrying.

**Comment by kbuzzard** [comment]
I don't understand: how will the simplifier find these injectivity/surjectivity assumptions?

**Comment by jcommelin** [comment]
What is the motivation for this PR? Are you planning to golf some proofs in mathlib? Or some others?

**Comment by semorrison** [comment]
This was motivated by @jakelev and I working on our [`transport`](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/status.20of.20.60tactic.2Ftransfer.2Elean.60/near/380967084) tactic, where we often have `Injective` or `Surjective` in the context and would like `simp_all` to just close obvious goals. Adding lemmas like this are very helpful for this.

So, no, not planning on golfing specific goals, we just wanted `simp_all` to be more powerful when there was already an `Injective` hypothesis available.

Not sure I'm going to have much opportunity to work on `transport` in the near future, so this isn't urgent.

**Comment by ocfnash** [comment]
> I don't understand: how will the simplifier find these injectivity/surjectivity assumptions?

These can be triggered if `simp` figures out the injectivity hypothesis (say) some other way. For example if we added `simp` to `RingHom.injective` (and I'd argue we should) then the changes here should ensure that `RingHom.cancel_left` fires when the source is a division ring.

Mostly though the huge amount of repetition in the library that this PR highlights makes me wonder if `cancel_left` and `cancel_right` could be folder into the `FunLike` API.

**Comment by semorrison** [comment]
> I don't understand: how will the simplifier find these injectivity/surjectivity assumptions?

@kbuzzard, e.g. `aesop` will use `simp_all`, so injectivity hypotheses in the local context are useful.

If you have an injectivity hypotheses `h`, it's also nice to just be able to write `simp [h]`, without having to go find the names of the lemmas that use `h`.

**Comment by sgouezel** [comment]
Let's get this in. Thanks!
bors r+

**Pull request closed without merging**
