### PR TITLE
[Merged by Bors] - feat(Order/RelIso): define missing instances

### PR DESCRIPTION
**Pull request by urkud**
Define `EmbeddingLike (r ↪r s) α β` and `EquivLike (r ≃r s) α β`.

---

[Open in Gitpod](https://gitpod.io/from-referrer/)

### CODE REVIEW

**Review by YaelDillies — APPROVED** [review]
Thanks!

maintainer merge

**Comment by riccardobrasca** [comment]
Thanks!

bors merge

**Comment by YaelDillies** [comment]
This looks like a transient error. Mind retrying?

**Comment by riccardobrasca** [comment]
bors merge

**Comment by urkud** [comment]
bors merge

**Pull request closed without merging**
